### ISSUE TITLE
Unable to compile object with Microsoft.Dynamics.Nav.OpenXml

### ISSUE THREAD

**Issue by dejfidson** [Microsoft/nav-docker#101]
Hi everyone. I have a problem with the Cside client. I am not running through the ClickOnce but I have copy of client in my local folder.
When I compile an object that uses Microsoft.Dymamics.Nav.OpenXml (DotNet) then error occured (as you can see below)

**.NET interop: exception occurred, 'Could not load file or assembly DocumentFormat.OpenXml, Version=2.5.5631.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 or one of this dependencies. The system cannot find the file specified.'.**

I checked dll file in my local folder where is the copy of client and the dll file is there. I don't know why cannot load this assembly.

_My container is created by function New-CSideDevContainer from NavContainerHelper Cmdlet._

**Comment by freddydk** [comment]
Do you have the object id of an object in the base app, which uses this DLL?

**Comment by dejfidson** [comment]
For example TAB370

**Comment by Koubek** [comment]
Hi @dejfidson, I have just tried to compile T-370 on my Win10 and I have no problem with that. 

I have been using my [template](https://github.com/Koubek/nav-docker-examples/tree/master/local_cside) which is nothing so sophisticated as [navcontainerhelper](https://github.com/Microsoft/navcontainerhelper).

I have been using the latest image version (I can recommend using the latest images always) + November update (which is not so important):
```
                "country": "es",
                "created": "201711091248",
                "cu": "november",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Freddy Kristiansen",
                "nav": "devpreview",
                "osversion": "10.0.14393.1770",
                "tag": "0.0.3.3",
                "version": "11.0.19097.0"
```

**Comment by freddydk** [comment]
I think this is the navdeveloperpreview azure vm - and I think what you need to do is, to install OpenXml SDK on the Azure VM (where you run the classic dev. environment)
https://www.microsoft.com/en-us/download/confirmation.aspx?id=30425

**Comment by dejfidson** [comment]
@freddydk you're right! It was enough to install openxml. I will close this issue.
Thank you

**Comment by freddydk** [comment]
I will add this to the Azure template as this is part of that and not really the docker image.
Thanks for reporting this.
