### ISSUE TITLE
Exception calling "Save" with "1" argument(s): "Could not find a part of the path 'C:\RoleTailored Client\ClientUserSettings.config'." when using additionalsetup.ps1

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/nav-docker#102]
Wanted to run the Windows Client and C/Side from container so I added AdditionalSetup.ps1 in C:\myfolder with this lines of code:
````
 if (!(Test-Path "$myPath\RoleTailored Client" -PathType Container)) {
    Write-Host "Copy RoleTailoted Client files"
    Copy-Item -path $roleTailoredClientFolder -destination $myPath -force -Recurse -ErrorAction Ignore
}

$ClientUserSettingsFileName = "$runPath\ClientUserSettings.config"
[xml]$ClientUserSettings = Get-Content $clientUserSettingsFileName
$clientUserSettings.SelectSingleNode("//configuration/appSettings/add[@key='Server']").value = "$hostname"
$clientUserSettings.SelectSingleNode("//configuration/appSettings/add[@key='ServerInstance']").value="NAV"
$clientUserSettings.SelectSingleNode("//configuration/appSettings/add[@key='ServicesCertificateValidationEnabled']").value="false"
$clientUserSettings.SelectSingleNode("//configuration/appSettings/add[@key='ClientServicesPort']").value="$publicWinClientPort"
$clientUserSettings.SelectSingleNode("//configuration/appSettings/add[@key='ACSUri']").value = ""
$clientUserSettings.SelectSingleNode("//configuration/appSettings/add[@key='DnsIdentity']").value = "$dnsIdentity"
$clientUserSettings.SelectSingleNode("//configuration/appSettings/add[@key='ClientServicesCredentialType']").value = "$Auth"
$clientUserSettings.Save("$destFolder\RoleTailored Client\ClientUserSettings.config")
````
I run docker for CTP16 image with windows auth and with shared folder
````
PS C:\Windows\system32> docker run --name navserver2 -h navserver2 -e ACCEPT_EULA=Y -e auth=Windows -e username=idordevic -e password=<mypassword> -e usessl=N -v C:\myfolder:c:\run\my  navdocker.azurecr.io/dynamics-nav:11.0.18843.0-finus
````
But I receive this log: 
![image](https://user-images.githubusercontent.com/20359384/32779607-ae03d334-c93e-11e7-8154-26c4ac0ee85a.png)

When I look into C:\myfolder I can see new RoleTailored Client folder with finssql and NAV.client.exe but the config file is missing. 

Do you have an idea what it could be? Seems like $clientUserSettings.Save("$destFolder\RoleTailored Client\ClientUserSettings.config") is failling.

**Comment by freddydk** [comment]
What is the value of $destFolder?
Shouldn't that be $myPath?

**Comment by ivandjordjevic** [comment]
Yes, that helped. Changing line from...

````
$clientUserSettings.Save("$destFolder\RoleTailored Client\ClientUserSettings.config")
````
to 
````
$clientUserSettings.Save("$myPath\RoleTailored Client\ClientUserSettings.config")
````
... resolved the issue. Thanks!

**Comment by Koubek** [comment]
@ivandjordjevic BTW, If you want a stable solution, you can use my scripts available here:
https://github.com/Koubek/nav-docker-examples/tree/master/local_cside

They are well tested, aware of the new flag that will allow you running synchronization of the metadata required to run C/SIDE and AL side-by-side etc. 

It will also generate `_finsql-on-docker.exe` for you in the RTC folder, you can just click on the file and you are in the correct C/SIDE environment (everything will be preconfigured in the `_finsql-on-docker.exe` file).
