### ISSUE TITLE
Unable to Connect a NAV Container to another Database server using gMSA

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/nav-docker#103]
Been trying to connect to SQL server from NAV container with no success for a few days now. gMSA is enabled based on the instructions [**here**](https://docs.microsoft.com/cs-cz/virtualization/windowscontainers/manage-containers/manage-serviceaccounts)...

Running command for connection to SQL server devnav20181\devnav20181 and database DynamicsNAVDemo:
````
docker run --name navwithsqlserver -h navwithsqlserver -e DatabaseServer=devnav20181 -e 
DatabaseInstance=devnav20181 -e DatabaseName=DynamicsNAVDemo -e ACCEPT_EULA=Y 
navdocker.azurecr.io/dynamics-nav:11.0.18843.0-finus 
````
Creating docker container stops after Creating Windows user step with message: 
````
Microsoft Dynamics NAV Server is currently not ready to serve requests. 
Try again later, or contact your system administrator.
````
Do you know how can we troubleshoot this or have idea what could be the issue here?

**Comment by ivandjordjevic** [comment]
The same result is also if I try to run container with Auth set to Windows and using my AD user and password.

**Comment by tfenster** [comment]
Do you see anything in the error logs **inside** the Container (system and application)

**Comment by tfenster** [comment]
Oh, and just wondering: Do you really have a SQL server machine named devnav20181 that also has an instance devnav20181?

**Comment by ivandjordjevic** [comment]
@tfenster yes, that's the name:

![image](https://user-images.githubusercontent.com/20359384/32809797-9718d48a-c998-11e7-8013-67cb46764cc9.png)

From log it looks like it was complaining for SetupLicense.ps1 script that was overridden. When I removed that, now is just hanging there:

````
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 18
at <ScriptBlock>, C:\Run\navstart.ps1: line 378
at <ScriptBlock>, C:\Run\start.ps1: line 18
at <ScriptBlock>, <No file>: line 1
````

**Comment by ivandjordjevic** [comment]
Here the actual new log:
````
TimeGenerated : 11/14/2017 6:34:36 PM
EntryType     : Error
Message       : Server instance: NAV
                <ii>Cannot establish a connection to the SQL Server/Database.
                
                This could be due to one of the following reasons:
                
                * SQL Server is not started.
                * The database does not exist.
                * Proper permissions have not been given to the NAV Server 
                Account.
                
                Try again later or contact your system administrator.</ii>

TimeGenerated : 11/14/2017 6:34:36 PM
EntryType     : Error
Message       : Server instance: NAV
                Tenant ID: 
                <ii>User: 
                Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavCSideException
                Remappable: True
                ErrorCode: 22924076
                ErrorNumber: 52012
                ModuleNumber: 93
                SuppressMessage: False
                DiagnosticsSuppress: False
                SuppressExceptionCreatedEvent: False
                FatalityScope: None
                Message:
                  <ii>Cannot establish a connection to the SQL Server/Database.
                  
                  This could be due to one of the following reasons:
                  
                  * SQL Server is not started.
                  * The database does not exist.
                  * Proper permissions have not been given to the NAV Server 
                Account.
                  
                  Try again later or contact your system administrator.</ii>
                StackTrace:
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.OpenCon
                nectionIfNeeded()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnectionScope.Ac
                quireSqlConnectionFromPool(NavDatabase database, Boolean 
                requireExclusiveConnection, TransactionType transactionType, 
                NavSqlConnection lastUsedSqlConnection)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnectionScope..c
                tor(NavDatabase database, Boolean requireNewConnection, 
                TransactionType transactionType, Boolean tryReuseConnection, 
                NavSqlConnection lastUsedSqlConnection, Boolean 
                requireExclusiveConnection)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnectionScope.Cr
                eate(NavDatabase database, TransactionType transactionType)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlMetadataCommands.T
                ableExists(NavDatabase database, String tableName)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseProperties
                .ReadDatabaseVersionNo()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseProperties
                .CheckDatabaseVersion()
                     at Microsoft.Dynamics.Nav.Runtime.NavDatabase.VerifyConnec
                tion(Int32 attemptCount)
                Source: Microsoft.Dynamics.Nav.Ncl
                HResult: -2146233088
                </ii>

TimeGenerated : 11/14/2017 6:34:36 PM
EntryType     : Error
Message       : Server instance: NAV
                Tenant: <ii>nav-systemapplication</ii>
                <ii>Tenant ID: nav-systemapplication
                The connection to SQL server could not be established
                Database server: DEVNAV20181.ALTUSDYNAMICS.LOCAL\DEVNAV20181
                Database name: DynamicsNAVDemo.</ii>

TimeGenerated : 11/14/2017 6:34:36 PM
EntryType     : Error
Message       : Server instance: NAV
                Category: HealthCheck
                ClientSessionId: 00000000-0000-0000-0000-000000000000
                ClientActivityId: 00000000-0000-0000-0000-000000000000
                ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
                ServerActivityId: 00000000-0000-0000-0000-000000000000
                EventTime: 11/14/2017 23:34:36
                Message <ii>Tenant ID: nav-systemapplication
                The connection to SQL server could not be established
                Database server: DEVNAV20181.ALTUSDYNAMICS.LOCAL\DEVNAV20181
                Database name: DynamicsNAVDemo.</ii>
                ProcessId: 1412
                Tag: 000008R
                ThreadId: 11
                CounterInformation: 

TimeGenerated : 11/14/2017 6:34:36 PM
EntryType     : Error
Message       : Server instance: NAV
                Tenant ID: 
                <ii>User: 
                Type: System.Data.SqlClient.SqlException
                ClientConnectionId: fec1c352-f282-4b58-af98-13362b25202a
                Class: 14
                LineNumber: 65536
                Number: 18456
                Server: DEVNAV20181.ALTUSDYNAMICS.LOCAL\DEVNAV20181
                State: 1
                Source: .Net SqlClient Data Provider
                ErrorCode: -2146232060
                Message: <ii>Login failed for user 'NT AUTHORITY\ANONYMOUS 
                LOGON'.</ii>
                StackTrace:
                     at System.Data.SqlClient.SqlInternalConnectionTds..ctor(Db
                ConnectionPoolIdentity identity, SqlConnectionString 
                connectionOptions, SqlCredential credential, Object 
                providerInfo, String newPassword, SecureString 
                newSecurePassword, Boolean redirectedUserInstance, 
                SqlConnectionString userConnectionOptions, SessionData 
                reconnectSessionData, DbConnectionPool pool, String 
                accessToken, Boolean applyTransientFaultHandling)
                     at System.Data.SqlClient.SqlConnectionFactory.CreateConnec
                tion(DbConnectionOptions options, DbConnectionPoolKey poolKey, 
                Object poolGroupProviderInfo, DbConnectionPool pool, 
                DbConnection owningConnection, DbConnectionOptions userOptions)
                     at System.Data.ProviderBase.DbConnectionFactory.CreateNonP
                ooledConnection(DbConnection owningConnection, 
                DbConnectionPoolGroup poolGroup, DbConnectionOptions 
                userOptions)
                     at System.Data.ProviderBase.DbConnectionFactory.TryGetConn
                ection(DbConnection owningConnection, TaskCompletionSource`1 
                retry, DbConnectionOptions userOptions, DbConnectionInternal 
                oldConnection, DbConnectionInternal& connection)
                     at System.Data.ProviderBase.DbConnectionInternal.TryOpenCo
                nnectionInternal(DbConnection outerConnection, 
                DbConnectionFactory connectionFactory, TaskCompletionSource`1 
                retry, DbConnectionOptions userOptions)
                     at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCo
                mpletionSource`1 retry)
                     at System.Data.SqlClient.SqlConnection.TryOpen(TaskComplet
                ionSource`1 retry)
                     at System.Data.SqlClient.SqlConnection.Open()
                     at 
                Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.TryConnect()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.<>c__Di
                splayClass108_0.<ExecuteAction>b__0()
                HResult: -2146232060
                </ii>





TimeGenerated : 11/14/2017 6:34:47 PM
EntryType     : Error
Message       : Server instance: NAV
                Tenant ID: 
                <ii>User: 
                Type: System.IO.IOException
                Message:
                  <ii>There are no more files.
                  </ii>
                StackTrace:
                     at System.IO.__Error.WinIOError(Int32 errorCode, String 
                maybeFullPath)
                     at System.IO.Directory.DeleteHelper(String fullPath, 
                String userPath, Boolean recursive, Boolean 
                throwOnTopLevelDirectoryNotFound)
                     at System.IO.Directory.Delete(String fullPath, String 
                userPath, Boolean recursive, Boolean checkHost)
                     at Microsoft.Dynamics.Nav.Runtime.TempPathHelper.RemovePat
                h(String path)
                Source: mscorlib
                HResult: -2147024878
                </ii>

TimeGenerated : 11/14/2017 6:34:47 PM
EntryType     : Error
Message       : Server instance: NAV
                Tenant ID: 
                <ii>User: 
                Type: System.IO.IOException
                Message:
                  <ii>There are no more files.
                  </ii>
                StackTrace:
                     at System.IO.Directory.DeleteHelper(String fullPath, 
                String userPath, Boolean recursive, Boolean 
                throwOnTopLevelDirectoryNotFound)
                     at System.IO.Directory.Delete(String fullPath, String 
                userPath, Boolean recursive, Boolean checkHost)
                     at Microsoft.Dynamics.Nav.Runtime.TempPathHelper.RemovePat
                h(String path)
                Source: mscorlib
                HResult: -2147024878
                </ii>
````

**Comment by Koubek** [comment]
I can see you are missing `-e auth=Windows` (which is not mandatory but we use it with **gMSA** as we can authenticate using our windows accounts) and `--security-opt "credentialspec=file://[container_hostname].json"`. `--security-opt` is a must. Without this flag **gMSA** does not work.

If the previous is OK and you are still in troubles, I would recommend some internal validations (running the following commands from the container):
+ Run container with `-e ExitOnError=N` flag. With this flag, the container will remain active.
+ After failure goto the container `docker exec -it [container_name] powershell and try the following`:
  * `ping devnav20181`
  * `nltest /query` - the result must be the following:
    ```
    Flags: 0
    Connection Status = 0 0x0 NERR_Success
    The command completed successfully
    ```

**Comment by ivandjordjevic** [comment]
Thanks @Koubek for pointing out --security.opt. I wasn't using that. Also, I added Windows Auth. My container hostname is navwithsqlserver, but --security-opt="credentialspec=file://navwithsqlserver.json" is not found:
````
docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: credential spec 
'C:\ProgramData\docker\CredentialSpecs\navwithsqlserver.json' for container f049055f4b3cdb3a59c23225bb16db76b8db8bfc8701b66fd8d7c882c2c6336e as the 
file could not be read: "open C:\\ProgramData\\docker\\CredentialSpecs\\navwithsqlserver.json: The system cannot find the file specified.".
At line:4 char:1
+ docker run --name navwithsqlserver `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Program File...le specified.".:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
````

When I try with different security opt:
````
--security-opt="credentialspec=file://..." 
````
l get a different "Access is denied" result, but still no success. I run PS as Administrator:
````
docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: credential spec 
'C:\ProgramData\docker\CredentialSpecs\...' for container 6ae9aac2cc10c03317fe4c4d32e2a938f33137a6bb3a061ba56df0d491560604 as the file could not be 
read: "open C:\\ProgramData\\docker\\CredentialSpecs\\...: Access is denied.".
At line:4 char:1
+ docker run --name navwithsqlserver `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Program File...ss is denied.".:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
````

My latest script looks like this:
````
$imageNameTag = "navdocker.azurecr.io/dynamics-nav:11.0.18843.0-finus"
docker rm navwithsqlserver -f
docker pull $imageNameTag
docker run --name navwithsqlserver `
           --hostname navwithsqlserver `
           --volume c:\myfolder:c:\run\my `
           --env accept_eula=Y `
           --env usessl=N `
           --env Auth="Windows" `
           --env username="altusdynamics\idordevic" `
           --env DatabaseServer=devnav20181.altusdynamics.local `
           --env DatabaseInstance=devnav20181 `
           --env DatabaseName=DynamicsNAVDemo `
           --env ExitOnerror=N `
           --security-opt="credentialspec=file://..." `
           $imageNameTag
````

**Comment by Koubek** [comment]
Have you created the file? It must be located in `C:\ProgramData\Docker\credentialspecs\` by default and in your case the name should be `navwithsqlserver.json`.

The file must have its specific content, everything is described here:
https://blogs.msdn.microsoft.com/containerstuff/2017/01/30/create-a-container-with-active-directory-support/

I have created our PowerModule for container management, this is distributed via GPOs and one of the functions is `New-gMSA`. I run it from every `run.ps1` - this is an example (you can see more internal PS functions being called from the script):

```PowerShell
$ErrorActionPreference = 'Stop'

# ===================================================================
# Preset variables
$image = 'microsoft/dynamics-nav:2017-cu9-es'
$ip = "[my_static_ip]"
$hostname = "[my_hostname]"
$databaseServer = "[my_db_server]"
$databaseInstance = "[my_db_server_instance]"
$dbName = "my_db_name"
# ===================================================================

# Create/update gMSA + DNS update
$navVersionDir = Get-DockerNavVersionDir $image
Set-ContainerDnsServerResourceRecordASet $ip $hostname
New-gMSA $hostname

# Run container
docker run -d `
    --hostname=$hostname `
    --name=$hostname `
    --network OliviaTransparentStatic `
    --ip=$ip `
    --security-opt "credentialspec=file://$hostname.json" `
    --restart=always `
    -v $PSScriptRoot\my:c:\run\my `
    -v "D:\DOCKER\SHARE\$hostname\Add-ins:C:\Program Files\Microsoft Dynamics NAV\$navVersionDir\Service\Add-ins\Docker-Share" `
    -v "D:\DOCKER\SHARE\$hostname\Temp:C:\Temp" `
    -e "databaseServer=$databaseServer" `
    -e "databaseInstance=$databaseInstance" `
    -e "databaseName=$dbName" `
    -e ACCEPT_EULA=Y `
    -e auth=Windows `
    -e clickonce=Y `
    $image
```

**Comment by ivandjordjevic** [comment]
After successfully creating credential file under C:\ProgramData\docker\credentialspecs, I can now run docker image that finally returns Ready for Connections... but now there is a new error log that says:

**Cannot find a variable with the name 'securePassword'.**:

![image](https://user-images.githubusercontent.com/20359384/32965675-8c79965e-cbd7-11e7-9f86-a0e1ee2b0b57.png)

**Comment by Koubek** [comment]
This looks good but I am worried you are using an older image. This error came with the secure password improvement and was fixed several days ago. Please, `docker pull` the same image you are using and `docker run` again.

Let\`s see :)

**Comment by freddydk** [comment]
Correct - and if the image you are trying to run doesn't exist in a version, where this bug is fixed, you can add
-e ExitOnError=N
to your parameter list and then it will ignore the error (it is the very last line in navstart, and it only happens when running gMSA)

**Comment by Koubek** [comment]
I think it exists.

**Comment by ivandjordjevic** [comment]
The images was up to date with the one on navdocker.azurecr.io. I was already pulling image and then running it. I have also modified script to use ExitOnError=N.

I was only able to access existing SQL database but with using **NAVUserPassword** authentication which creates new user that I could use to login from web client.  I guess this proves that gMSA credentials are working when connecting to existing SQL server? However, when I run the script with Windows Authentication it's still a little bit tricky..  

There is that 'Secure Password' error, so I'm wondering if the image **navdocker.azurecr.io/dynamics-nav:11.0.18843.0-finus** has the fixed secure password improvements..? There is no CTP16 for US on Docker hub to pull image from there, or I'm using the wrong URL (**microsoft/dynamics-nav:11.0.18843.0-finus**)?

Since I'm connecting to existing NAV database I can see the new **navwithsql:7046/nav** server instance from NAV container in development environment but with no successful connection when opening windows and web client (http://navwithsql/NAV/WebClient/).

Web client presents the Authentication Required (default browser login dialog) even though I'm using Windows Authentication. Typing my windows credentials there still doesn't work.

When running the container using gMSA with Windows Authentication do I need to provide only my username in format: domain\username (without password)? In my case it only matters that the NAV container is using Windows authentication because users are already set in existing NAV User table.

The script I'm using: 
````
$imageNameTag = "navdocker.azurecr.io/dynamics-nav:11.0.18843.0-finus"
$hostname = "navwithsql"

docker rm $hostname -f
docker pull $imageNameTag
docker run --name $hostname `
           --hostname $hostname `
           --volume c:\myfolder:c:\run\my `
           --env accept_eula=Y `
           --env usessl=N `
           --env DatabaseServer=devnav20181.altusdynamics.local `
           --env DatabaseInstance=devnav20181 `
           --env DatabaseName="DynamicsNAVDemo" `
           --env Auth="Windows" `
           --env Username="altusdynamics\idordevic" `
           --security-opt "credentialspec=file://svc_dockersql.json" `
           --env ExitOnError=N `
           $imageNameTag
````
....and the output I receive:
````
11.0.18843.0-finus: Pulling from dynamics-nav
Digest: sha256:340b2be1cda162056097faea1a57e794cb65d576be4414225387ed2a00cf48c7
Status: Image is up to date for navdocker.azurecr.io/dynamics-nav:11.0.18843.0-finus
Initializing...
Hostname is navwithsql
PublicDnsName is navwithsql
Running Specific Image
Using Windows Authentication
Starting Internet Information Server
Using Database Connection devnav20181.altusdynamics.local/devnav20181 [DynamicsNAVDemo]
Modifying NAV Service Tier Config File for Docker
Modifying NAV Service Tier Config File with Instance Specific Settings
Start NAV Service Tier
Creating DotNetCore NAV Web Server Instance
Creating http download site
WARNING: This license is not compatible with this version of Dynamics NAV.
Container IP Address: 172.22.214.239
Container Hostname  : navwithsql
Container Dns Name  : navwithsql
Web Client          : http://navwithsql/NAV/WebClient/
Dev. Server         : http://navwithsql
Dev. ServerInstance : NAV

Files:
http://navwithsql:8080/al-0.11.14380.vsix

Ready for connections!
Cannot find a variable with the name 'securePassword'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 436
at <ScriptBlock>, C:\Run\start.ps1: line 18
at <ScriptBlock>, <No file>: line 1
````

**Comment by Koubek** [comment]
@ivandjordjevic

You can see I do not use this variable:
`--env Username="altusdynamics\idordevic"`

BTW:
+ What overrides do you use (what files do you have in your **my** folder)?
+ What is the image version (use image labels to reveal the information)?

**Comment by ivandjordjevic** [comment]
@Koubek 
I use only AdditionalSetup.ps1 to copy RoleTailored Client folder to myFolder. 

Image version is:
````
LABEL country=finus created=201710262240 cu= maintainer=Freddy Kristiansen nav=main version=11.0.18843.0
````

**Comment by freddydk** [comment]
It is actually the fields you left out, that are important.
November preview looks like this:
            "Labels": {
                "country": "W1",
                "created": "201711091201",
                "cu": "november",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Freddy Kristiansen",
                "nav": "devpreview",
                "osversion": "10.0.14393.1770",
                "tag": "0.0.3.3",
                "version": "11.0.19097.0"
            },

**Comment by ivandjordjevic** [comment]
Here it is:
````
 "Labels": {
     "country": "finus",
     "created": "201710262240",
     "cu": "",
     "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
     "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
     "maintainer": "Freddy Kristiansen",
     "nav": "main",
     "osversion": "10.0.14393.1770",
     "tag": "0.0.3.1",
     "version": "11.0.18843.0"
 },
````

**Comment by freddydk** [comment]
That is a special build from MS Collaborate, which will not be rebuild.
The bug is fixed in the next update - until that you can use -e ExitOnError=N to ignore the error.
As this is the very last thing that happens in the navstart script, it should not have any effect.

**Comment by freddydk** [comment]
You can also grab the november preview from the official docker hub.
microsoft/dynamics-nav:devpreview-finus
The bug is fixed in that one.

**Comment by Koubek** [comment]
I would suggest using the image being proposed by @freddydk . Then omit `--env Username="altusdynamics\idordevic"`. Of course, on SQL you need to assign permissions to the user (**gMSA account** aka **container hostname** which is the same in this case). This is the reason we use security groups for containers (we assign permissions on SQL against these groups and not against a specific container).

**Comment by Koubek** [comment]
@ivandjordjevic I have an alternative fix for your problem with `securePassword` variable. 

You can add `AdditionalSetup.ps1` into your `my` folder and add the following code:
```PowerShell
# Invoke default behavior
. (Join-Path $runPath $MyInvocation.MyCommand.Name)

# Temporary workaround to 'fix' a bug in the image.
$securepassword = ""
```

**Comment by Addice73** [comment]
@Koubek  
I'm stuck  with "cannot find file" . Created a `navwithsqlserver.json` under `C:\ProgramData\Docker\credentialspecs\ bu`t ... no-way

PS C:\WINDOWS\system32> docker run -e accept_eula=Y navdocker.azurecr.io/dynamics-nav:11.0.19394.0-it --security-opt="credentialspec=file://navwithsqlserver.json" 

docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 1bf77dfea185f4da90665005c662bf72c8f30c3cab8ddf3668e8f2311ae1db1d encountered an error during 
CreateProcess: failure in a Windows system call: Impossibile trovare il file specificato. (0x2) extra info: {"CommandLine":"--security-opt=credentialspec=file://navwithsqlserver.json","WorkingDirectory":"
C:\\","Environment":{"COUNTRYURL":"https://nav2016wswe0.blob.core.windows.net/dvd/9fe46316-ff66-43fa-9a0d-1a46d76fe844","DatabaseInstance":"SQLEXPRESS","DatabaseName":"CronusIT","DatabaseServer":"localhos
t","NAVDVDURL":"https://nav2016wswe0.blob.core.windows.net/dvd/e44c4618-e859-4ce6-8688-e9057750b8b8","VSIXURL":"https://nav2016wswe0.blob.core.windows.net/dvd/al-0.12.15355.vsix","accept_eula":"Y"},"Creat
eStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}.
In riga:1 car:1
+ docker run -e accept_eula=Y navdocker.azurecr.io/dynamics-nav:11.0.19 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Program File...leSize":[0,0]}.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by marknitek** [comment]
First: We got gMSA and external SQL working, thats fine.
But:
Can Someone explain why i need a seperate credentialspec file for every container? There is no -Name Information in that created .json file, so i don't see the point. But of course it does not work when i try to create a container with a different Name then the one i used to create the credentialspec file.
How do they interact? Do I need a gMSA Account per Container?? 

I realy would prefer not spin up containers without the need of any pre-steps so that i could use solutions like kubernetes in the future (would not be possible if i need to run Powershell on the Host before creating the container)

**Comment by Koubek** [comment]
Hi @tfenster, AFAIK, Swarm should be working with gMSA. I can remember I was running on our test Swarm cluster NAV containers using gMSA. And it was months ago. Since that moment there were some slight changes but more in terms of the unification in compose-file format.

Please, have a look at this: https://docs.docker.com/compose/compose-file/#credential_spec

**Comment by Koubek** [comment]
Yes, definitely, due to the latest information available (the links you posted) we still need to follow the standard rule - create a smaccount with the same name as the container has (or in the case of the Swarm we should say the name of the service).

I was always trying to follow this rule for gMSA: smaccount name = container name / service name = host name.

**Comment by marknitek** [comment]
@tfenster @Koubek thanks for clarification, i already "feared" that this is the case. Unfortunatly there are some misleading info on that subject and i had the feeling that this should work with a single account for multiple containers. 
So, i guess you guys spin up your containers trough a script based aproach instead of a desired state aproach?
We are currently in the process designing our dev/test infrastructure and the question is if its possible to use configuration based container creation instead of script based aproach to achieve a "desired state" aproach.
If we need to create gMSA before for every container that would be an issue for configuraiton based aproach i guess (it would still need an script for gMSA creation, which kind of prevents me from using standard tooling).
How do you guys solve this? How do you manage 100 or more containers?

**Comment by tfenster** [comment]
@marknitek Yes, we use script-based creation. I have to say that I don't know a lot about DSC but I see the same problem. A different but somewhat related approach is to use a mgmt tool like portainer which for the same reason also doesn't work for the gMSA case.

For your last question: We are currently not running 100 containers but maybe 25 more or less permanently and then some depending on dynamic dev and pm needs. The permanently running ones are managed mostly through compose files (where we also have scripts creating those). The dynamic demand is handled through a thin custom API on some docker hosts which takes request from a NAV based "self service" GUI. It then executes a script which creates the gMSA, in some cases downloads custom baks and dlls and then starts the container

The next step will involve roughly 250 containers but I think the approach should scale ok

**Comment by marknitek** [comment]
@tfenster @Koubek  today i found this Blogpost: https://blogs.windows.com/windowsexperience/2018/07/10/announcing-windows-server-2019-insider-preview-build-17709/

> Group Managed Service Accounts We’ve improved the scalability and reliability of containers that use group managed service accounts (gMSA) to access network resources. You should see fewer authentication errors when using a single gMSA with multiple container instances. **Additionally, you no longer need to set the container’s host name to be the same as the gMSA**. We also fixed a bug that prevented you from using gMSAs with Hyper-V isolated containers.

I would love to test this out like NOW, but i have no spare time right now... 
Anybody else?

**Comment by tfenster** [comment]
@marknitek Very interesting! I should be able to do some testing :) Thanks for mentioning it, I didn't see that one

**Comment by Koubek** [comment]
Sorry, I can't test it I don't have access to any gMSA-enabled environment now (new job, lower permissions :)). I don't have any insider instance to test on.

Anyway, I am not sure whether I understand correctly the text coming in bold. What was quite annoing, especially at the beginning before we started using some automation, was the fact, that we needed to create an account on DC, json file on the docker host and this for each container. And the names had to be the same.

**Comment by tfenster** [comment]
@marknitek environment is up and running, now I'll need NAV on Server 2019

**Comment by tfenster** [comment]
@marknitek @Koubek A gMSA with a different name than the container definitely works in Server 2019 👍 

Starting the container with gMSA tst19 and container / host name tstme
```
docker run --rm --security-opt credentialspec=file://tst19.json --name tstme --hostname tstme -ti  mcr.microsoft.com/windowsservercore-insider:10.0.17738.1000
```

Perfectly able to get AD information and add an AD user to a local group
```
PS C:\> Add-WindowsFeature RSAT-AD-PowerShell

True    No             Success        {Remote Server Administration Tools, Activ...

PS C:\> Import-Module ActiveDirectory

PS C:\> Get-ADUser -Identity tfenster

DistinguishedName : CN=Fenster\, Tobias,OU=User,OU=_INFOMA,DC=global,DC=fum
Enabled           : True
GivenName         : Tobias
Name              : Fenster, Tobias
ObjectClass       : user
ObjectGUID        : c38a51fa-8551-4bf4-8e1f-16626d0d429f
SamAccountName    : tfenster
SID               : S-1-5-21-1960130858-3242946568-2400973019-8349
Surname           : Fenster
UserPrincipalName : tfenster@infoma.de

PS C:\> Add-LocalGroupMember -Group Administrators -Member tfenster

PS C:\> Get-LocalGroupMember Administrators

ObjectClass Name                PrincipalSource
----------- ----                ---------------
User        FUM-GLOBAL\tfenster ActiveDirectory
User        tst19\Administrator Local
```

Currently only testing in a windowsservercore container as I get a weird error if I try to run NAV with a credentialspec in Server 2019 but I'll dig into that as well

**Comment by tfenster** [comment]
@marknitek @Koubek And it works with NAV as well 👍 (For whatever reason the memory right at the beginning of the container startup script gets only an empty response which stopped the container from starting but as soon as I removed that, it worked flawlessly.) I have two containers up and running, tstme2 and tstme3, both using gMSA tst19$ and in both I can add windows users and sso to the WebClient

**Comment by Koubek** [comment]
@tfenster Great new!!!

**Comment by marknitek** [comment]
@tfenster awesome! Thanks a lot for your effort!
