### ISSUE TITLE
Docker pull error.

### ISSUE THREAD

**Issue by navaddins** [Microsoft/nav-docker#104]
I have a issue during docker pull. The error is show as below.
image operation system "windows" cannot be use on this platform.

i'm running "Docker CE Version 17.09.0-ce-win33" on Windows 10 Enterprise Edition Version 1702 OS Build 15063.726.

All version same error.
docker pull microsoft/dynamics-nav:2017
docker pull microsoft/dynamics-nav:2016-cu18
docker pull microsoft/dynamics-nav:2017-dk
docker pull microsoft/dynamics-nav

![capture](https://user-images.githubusercontent.com/33715070/32880581-2eed53de-cae9-11e7-9ed2-cbfa7fbdccad.PNG)

do I miss anything?

**Comment by freddydk** [comment]
Look at the very first item in this troubleshooting blog post: https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/

**Comment by navaddins** [comment]
Case is soved as per @freddydk. Initial my docker is under windows mode.  May be it change switch back to linx mode after upgrade the docker.

Thanks,
