### ISSUE TITLE
Docker Images for Nav 2013 and Nav 2015

### ISSUE THREAD

**Issue by elweilando** [Microsoft/nav-docker#105]
Knows anyone if there will be also docker images for NAV 2013, 2013 R2 and 2015?

**Comment by freddydk** [comment]
NAV 2013 and NAV 2013R2 will be out of support very soon, we have no plans of delivering docker images for them
If the demand for NAV 2015 docker images is high, then we might have a look.

**Comment by forki** [comment]
There would be definitely lots of interest for nav 2015 from our customers

Am 18.11.2017 06:08 schrieb "Freddy Kristiansen" <notifications@github.com>:

**Comment by Koubek** [comment]
@forki NAV on Docker is not PRO approved. It is intended to be used on DEV & TEST envs. At least for now and the nearest future.

**Comment by forki** [comment]
Yes I do understand that. But our customers have staging environments as
well.

Am 18.11.2017 08:02 schrieb "Jakub Vaňák" <notifications@github.com>:

**Comment by elweilando** [comment]
I agree with @forki. And it's the same for me with 2013. Even if the support ends, our customer has no intentions to upgrade to a newer version for various reasons at the time. so we still need the older plattforms to develop and test.
@freddydk  is it possible to create own docker-images?

**Comment by freddydk** [comment]
We am not going to ship docker images for 2015 and before, but I will try to make the generic image able to install NAV 2015. Supporting earlier versions is basically modifying the installer script to be able to install them. I will blog about the generic image too.
Shoot me an email to freddy dot kristiansen at microsoft dot com with which version, cu and localization you want to test.

**Comment by freddydk** [comment]
Basically you would do something like this:

docker run -v c:\versions\nav2015:c:\navdvd -e accept_eula=Y microsoft/dynamics-nav:generic
= run the generic image with a navdvd shared into the container.

(doesn't work yet)

**Comment by freddydk** [comment]
Works now...
https://blogs.msdn.microsoft.com/freddyk/2017/11/29/can-i-run-nav-2015-and-earlier-on-docker/
