### ISSUE TITLE
Could not download symbols. Reason: No published package matches the provided arguments.

### ISSUE THREAD

**Issue by louagej** [Microsoft/nav-docker#106]
I Installed a nex NAV-Container with this powershell script.
`New-CSideDevContainer `
    -containerName DEVServer `
    -accept_eula `
    -accept_outdated `
    -auth NavUserPassword `
    -Credential admin `
    -doNotExportObjectsToText `
    -imageName microsoft/dynamics-nav:devpreview `
    -licenseFile "C:\Users\<Username>\Documents\Licence\fin.flf" `
    -memoryLimit 3G `
    -updateHosts `
    -Verbose`

After installing, I can connect to the web client and the classic dev environment.
But when I'm trying to connect with Visual studio code, I get the message:

> Could not download symbols. Please see the Visual Studio Code output log for more details.
![2017_11_22_ 000](https://user-images.githubusercontent.com/7229592/33110325-6ef62c00-cf47-11e7-8142-6b4906d3f3ca.png)

This is what appears in the log file:
`[2017-11-22 05:37:14.27] The request for path /nav/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.19097.0&tenant=default failed with code NotFound. Reason: No published package matches the provided arguments.
[2017-11-22 05:37:14.27] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application locale and version are specified in the app.json file.
`
The Version in my app.json matches the one on the server:
`"application": {
    "version": "11.0.19097.0",
    "locale": "W1"
  }`
![2017_11_22_ 002](https://user-images.githubusercontent.com/7229592/33110527-b49d6fba-cf48-11e7-8b4c-8617f443a81b.png)

And the servername matches the name in my launch.json:
![2017_11_22_ 001](https://user-images.githubusercontent.com/7229592/33110487-7650ab78-cf48-11e7-925e-b4d82182154e.png)

**Comment by freddydk** [comment]
when you are running navuserpassword, the container defaults to https.
you can specify -usessl:$false to your new-container command or use https in the launch.json.
After running the image, it displayed the server url, you can also write docker logs devserver and you will get the output again.

**Comment by louagej** [comment]
As you recommended in your mail, I removed the container and created a New-CSideDevContainer with -usessl:$false. and I also tried to set the tenant blank instead of default.

_> when you are running navuserpassword, the container defaults to https.
you can specify -usessl:$false to your new-container command or use https in the launch.json.
After running the image, it displayed the server url, you can also write docker logs devserver and you will get the output again._

Unfortunately I still get the sames error message in the VSCode log:
````
[2017-11-26 08:30:54.17] The request for path /nav/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.19097.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2017-11-26 08:30:54.17] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application locale and version are specified in the app.json file.
````

**Comment by freddydk** [comment]
Yeah, I actually deleted that comment because I found out it wasn't true.
What version of the AL extension is installed in VS code and where did you get it?

**Comment by louagej** [comment]
I'm using the October Update
![2017_11_26_ 000](https://user-images.githubusercontent.com/7229592/33238301-5bee8b88-d28b-11e7-9213-309dac0f0dc1.png)

**Comment by freddydk** [comment]
Ok, that's the problem.
The docker image is November preview.
docker logs <name> will show you the url for downloading the AL extension matching the docker image.
Download and install that one should solve your problem.
I will try to make it more obvious when using new-navcontainer what the .vsix is.

**Comment by louagej** [comment]
Hi,
This solved the problem:
![2017_11_26_ 001](https://user-images.githubusercontent.com/7229592/33238672-96c855a2-d292-11e7-90aa-6e43a25bd9fa.png)

Does this mean that for future programming, we have customers with let's say 5 different NAV-versions, we'll have to download 5 different AL Language extensions in VS Code?

**Comment by freddydk** [comment]
Only if you are using preview or insider builds.
Else - one of the ideas of extensions v2 is to ensure that no customer is left behind.
