### ISSUE TITLE
SQL authentication with AD user

### ISSUE THREAD

**Issue by kaspermoerch** [Microsoft/nav-docker#107]
I create a container with this command:
```
New-CSideDevContainer `
    -containerName $ContainerName `
    -imageName $ImageName `
    -memoryLimit 3G `
    -Credential $AdminCredential `
    -licenseFile $LicenseFile `
    -updateHosts `
    -doNotExportObjectsToText `
    -accept_eula
```

When creating the container I am on my company network - logged in with my AD user. Everything works fine and C/Side starts and connects to the database using windows authentication.

When I'm not on my company network (meaning the domain controller is out of reach) I get this error (sorry for the danish):
![image](https://user-images.githubusercontent.com/1166791/33114675-38a75ba8-cf5e-11e7-9eac-e2091c89c697.png)

If I change the login to database credentials and use `sa` as user and enter my password I am able to connect to the database.

**Comment by Koubek** [comment]
Yes, this is well-known fact that you need to be logged into your company network to make the authentication working.

**Comment by freddydk** [comment]
Yeah, I don't think there is not much we can do about that

**Comment by kaspermoerch** [comment]
Okay, thank you.

Just wanted to put it out there in case others encounter the same issue.

**Comment by freddydk** [comment]
Thanks, and actually Stan did run into this exact problem during his presentation on Tech Days...
