### ISSUE TITLE
Container can't be reached from host machine

### ISSUE THREAD

**Issue by mrabus** [Microsoft/nav-docker#108]
Hey docker experts, 

i am struggeling to connect to my devpreview container. I guess this is rather a wrong setup on my side than a bug. Nevertheless any help would be much appreciated. 

I created a standard container using the following command:
docker run -e accept_eula=Y -m 8G microsoft/dynamics-nav:devpreview-de

That finishes and states the standard messages:
Container IP Address: 172.17.1.224
Container Hostname  : 3beaf9d1d5b1
Container Dns Name  : 3beaf9d1d5b1
Web Client          : https://3beaf9d1d5b1/NAV/WebClient/
NAV Admin Username  : admin
NAV Admin Password  : password
Dev. Server         : https://3beaf9d1d5b1
Dev. ServerInstance : NAV

Files:
http://3beaf9d1d5b1:8080/al-0.11.14434.vsix
http://3beaf9d1d5b1:8080/certificate.cer

Ready for connections!

When I try to connect to the container (e.g. the web client or to download the vsix), i can't reach the container. I tried it using the container name and the ip. 

I attached the docker inspect of my container:
[
    {
        "Id": "3beaf9d1d5b180c51762e7712c47ea4e8a372fe88565b00e958eac91dd88bfda",
        "Created": "2017-11-22T09:06:35.4028211Z",
        "Path": "powershell",
        "Args": [
            "-Command",
            "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
            ".\\Run\\start.ps1"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1924,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-11-22T09:06:54.2395036Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2017-11-22T10:46:09.6053555+01:00",
                        "End": "2017-11-22T10:46:09.8727644+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-22T10:46:39.911912+01:00",
                        "End": "2017-11-22T10:46:40.174952+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-22T10:47:10.2021317+01:00",
                        "End": "2017-11-22T10:47:10.5821441+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-22T10:47:40.6198052+01:00",
                        "End": "2017-11-22T10:47:40.8730477+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-22T10:48:10.9062838+01:00",
                        "End": "2017-11-22T10:48:11.1651711+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:58cb0cbfaaf00426c0d1a72f4eecca2e0a60de58a1c53b7330ce7a8e2ab7f883",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\Docker\\containers\\3beaf9d1d5b180c51762e7712c47ea4e8a372fe88565b00e958eac91dd88bfda\\3beaf9d1d5b180c51762e7712c47ea4e8a372fe88565b00e958eac91dd88bfda-json.log",
        "Name": "/relaxed_williams",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "c:\\temp:c:\\run\\my"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "hyperv",
            "CpuShares": 0,
            "Memory": 8589934592,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\windowsfilter\\3beaf9d1d5b180c51762e7712c47ea4e8a372fe88565b00e958eac91dd88bfda"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\temp",
                "Destination": "c:\\run\\my",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "3beaf9d1d5b1",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "accept_eula=Y",
                "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-0.11.14434.vsix",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/441cce9c-697f-4594-a483-1b0a1cfcf573",
                "DatabaseServer=localhost",
                "DatabaseInstance=SQLEXPRESS",
                "DatabaseName=CronusDE",
                "COUNTRYURL=https://nav2016wswe0.blob.core.windows.net/dvd/6aa8b35e-7dbb-4e9b-b547-fe4873a242f1"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "microsoft/dynamics-nav:devpreview-de",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "de",
                "created": "201711091241",
                "cu": "november",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Freddy Kristiansen",
                "nav": "devpreview",
                "osversion": "10.0.14393.1770",
                "tag": "0.0.3.3",
                "version": "11.0.19097.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "9a5b0f994fef5cabf4ae784a4d817d28deb71ed37e2412b9ca3f6ec71c46e053",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "80/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "9a5b0f994fef",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "b365f6bb3e92165615b9bf68fe34fdfb5e6f5b5f6281b2cfa3686e8c41415c5e",
                    "EndpointID": "d1be93654047a6b3205ccf62d84be1e2792b72a4588dd25bc2fae4e2e6b7649f",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.1.224",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:31:a2:c3",
                    "DriverOpts": null
                }
            }
        }
    }
]

Does anyone have any clue what I could do to connect to my container?

Thank you for your help in advance!

**Comment by Koubek** [comment]
Hi, do you host your containers on Win10 or WinServer 2016?

**Comment by freddydk** [comment]
https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/

Did you try step 4 in this?

**Comment by mrabus** [comment]
Hi you two,

thanks for your suggestions. 

@Koubek : I am running on a Windows 10 (Enterprise) host. 
@freddydk: I tried the steps, but the behavior remains as is. 
Name resolution should be no problem as the host is not in a company network.
I tried recreating the container using the navcontainerhelper and see the updated hosts file, but still ping is not working.

**Comment by freddydk** [comment]
So name resolution also did also not work with a windowsservercore machine?

**Comment by mrabus** [comment]
The name resolution does work for the devpreview (hosts file includes the container) but not for windowsservercore (hosts file does not include this container).

**Comment by freddydk** [comment]
so name resolution for devpreview works - but you cannot ping it, nor access the web client.
you also cannot access the web client using the ip address.
Sounds like firewall issues or proxy problem.

**Comment by freddydk** [comment]
Did you ever get this to work?

**Comment by mrabus** [comment]
Just yesterday I did. A complete reinstall of the host's operating system fixed it for me. I guess some settings in my network settings was messed up.

**Comment by freddydk** [comment]
Thanks
