### ISSUE TITLE
Cannot Connect Web Client

### ISSUE THREAD

**Issue by J-Draeger** [Microsoft/nav-docker#110]
Hello,
I just started trying this out (as I'm sure many are), and have run into a snag Connecting to my Web Client.  Thank you for your efforts getting this out there to share with everyone.

Here are the Steps I took:

1. Installed Docker and changed to Windows Containers.
2. Opened PowerShell as Admin
3. Ran "docker pull Microsoft/dynamics-nav:2017-na"
4. Ran "docker run -e accept_eula=Y -m 4G Microsoft/dynamics-nav:2017-na  (Results Below)
PS C:\WINDOWS\system32> docker run -e accept_eula=Y -m 4G microsoft/dynamics-nav:2017-na
Initializing...
Hostname is a6c67086ce44
PublicDnsName is a6c67086ce44
Running Specific Image
Using NavUserPassword Authentication
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
Starting Internet Information Server
Using Database Connection localhost/SQLEXPRESS [CronusNA]
Modifying NAV Service Tier Config File for Docker
Creating Self Signed Certificate
Self Signed Certificate Thumbprint D18FC79BAE0F4024B875503CF1A1B475563FE2E4
Modifying NAV Service Tier Config File with Instance Specific Settings
Start NAV Service Tier
Using existing license file
Creating Web Site
Creating NAV Web Server Instance
Creating http download site
Creating Windows user
Enabling SA
Creating NAV user
Container IP Address: 172.21.173.142
Container Hostname  : a6c67086ce44
Container Dns Name  : a6c67086ce44
Web Client          : https://a6c67086ce44/NAV/WebClient/
NAV Admin Username  : admin
NAV Admin Password  : Xyra2592

Files:
http://a6c67086ce44:8080/certificate.cer

Ready for connections!

5. Tried pinging IP Address 172.21.173.142 successfully.
6. Tried navigating to Web Client with Internet Browser using the Web Client URL listed above and received the following:

Can't connect securely to this page

This might be because the site uses outdated or unsafe TLS security settings.  If this keeps happening, try contacting the website's owner.

Your TSL security settings aren't set to the defaults, which could also be causing this error.

7. Checked Internet Options -> Advanced Tab - Security and have the following checked:
Use SSL 3.0, Use TLS 1.0, Use TLS 1.1 and Use TLS 1.2.

Let me know if you have any ideas what I could try next.

Thank You!

**Comment by Koubek** [comment]
What web browser do you use? Please, could you try Google Chrome?

**Comment by J-Draeger** [comment]
Hi Jakub,

I tried this in Google Chrome and I get the following message now:

This site can't be reached
The connection was reset.
Try:
- Checking the connection
- Checking the proxy and firewall
- Running Windows Network Diagnostics
ERR_CONNECTION_REST

**Comment by Koubek** [comment]
So I suppose you can ping IP and name without any problem... The problems start when assessing the application via a browser.

Do you use any special antivirus/antimalware piece of software on your host? 

I am afraid that some of them are pretty "aggressive" and can override the default behavior of PKI subsystem defined on Windows. For example Eset (Nod32). Be aware that just pausing this antivirus does not change its behavior in PKI area, it is necessary to turn off related switches explicitly.

**Comment by J-Draeger** [comment]
Jakub,

I do get a reply from both, but when I ping the "name" it comes back with a different IP than I expected.
Ping 172.21.173.142 -> I Get a Reply
Ping a6c67086ce44 it says reply from 76.227.212.108
It also says Pinging a6c67086ce44.ompimail.com (which is the domain I'm on).

It looks like we have Symantec Endpoint Protection Antivirus Software.
I apologize, I'm not familiar with the term PKI. It falls outside my knowledge. (does this stand for Public Key Infrastructure?)

**Comment by Koubek** [comment]
OK, so this is the problem. Please, try to assign a hostname by your own or update the host file (in the second one you can use https://github.com/Microsoft/navcontainerhelper which can be very helpful here).

To set hostname you should use `--hostname` (eg: `--hostname=mycontainer1`). Then you will be able to use this hostname to access the container. I usually assign the same value for `--hostname` and `--name` (container name).

**Comment by J-Draeger** [comment]
Jakub,

So I have one thing that worked for me.  I used https://172.21.173.142/NAV/WebClient and was able to connect by ignoring the Security Warning.

I will try what you mentioned above with the --hostname parameter.  Is this parameter set when I do the docker run command?

**Comment by Koubek** [comment]
Exactly, you can access using the correct IP but of course, this is not a very convenient way.

And yes, you will set the `--hostname` parameter when `docker run`.

I would strongly recommend read Freddy`s blog. There are several blog posts where all these basics are being explained. And in the root directory of this repo you can find **Hand-on-Labs** document which is also very useful to start with NAV on Docker.

**Comment by J-Draeger** [comment]
Hi Jakub,

Using the --hostname switch did set my container hostname, but the https://JoesContainer/NAV/WebClient/ url still doesn't work.

I am quite satisfied that I am able to connect via the IP, but if you want me to try anything else I would be more than happy to do this.

Thank you for getting me pointed in the right direction and I will make sure to read through Freddy's Blog as well.

**Comment by Koubek** [comment]
I repeat - you can update manually your hosts file (`C:\Windows\System32\drivers\etc\hosts`) or you can automate it using [navcontainerhelper](https://github.com/Microsoft/navcontainerhelper).

**Comment by J-Draeger** [comment]
Yes, that works.  Sorry, I missed that.  -- Thanks for your help!

**Comment by Koubek** [comment]
No problem ;)

**Comment by freddydk** [comment]
Yeah - I have the same problem when I am connected to the Microsoft Corporate network, the DNS doesn't resolve correctly, probably because of some  proxy thing.
