### ISSUE TITLE
Endless Loop at end of deplyoment

### ISSUE THREAD

**Issue by KVS-CBL** [Microsoft/nav-docker#111]
Why is there an endless Loop in Run/MainLoop.ps1
Does not this slows the deployment?

On our test Server the systemsays "Ready for connections!" and sleeps till the end of days...

**Comment by Koubek** [comment]
At this moment your service inside the container is ready to serve requests. The loop is endless, logically. In the standard images (not overrides by your own scripts) the code inside the loop just read and report related error messages (from Event Log).

Why slows the deployment? I don\`t understand well. You can also kill the powershell session and work, the container is running in the background.

You can also use `-d` to start the container in detached mode but you won\`t see the progress. 

Please, read some docker basics if you are unfamiliar with Docker. It will help you to understand better.
