### ISSUE TITLE
Storage problem starting CTP17 on W10.

### ISSUE THREAD

**Issue by guidorobben** [Microsoft/nav-docker#112]
PS C:\WINDOWS\system32> docker run -e accept_eula=Y CTP17
_Initializing...
Hostname is ---
PublicDnsName is ---
Running Specific Image
Using NavUserPassword Authentication
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Using Database Connection localhost/SQLEXPRESS [CronusNL]
Modifying NAV Service Tier Config File for Docker
Creating Self Signed Certificate
Self Signed Certificate Thumbprint ---
Modifying NAV Service Tier Config File with Instance Specific Settings
Start NAV Service Tier
Using existing license file
Creating DotNetCore NAV Web Server Instance
Creating http download site
Not enough storage is available to process this command.__

I have 20GB free on the C:. What could be causing the storage problem? Is it the 20gb or something else?

**Comment by freddydk** [comment]
On Windows 10 you need to give the container more memory:
https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/

**Comment by Koubek** [comment]
Of course, I would try to assign the memory flag (best practices on Win10). 

@freddydk  Anyway, the error here is slightly different (more like HDD space problem). Do you think it has something to do?

**Comment by freddydk** [comment]
@Koubek the error we get with lack of memory are very different.

**Comment by Koubek** [comment]
@freddydk Yes, I wrote "*slightly*" but of course, these are two different worlds, indeed. Maybe some sort of irony... just written by myself doesn\`t sound ironically enough ;)

**Comment by freddydk** [comment]
Did you manage to get this resolved?

**Comment by guidorobben** [comment]
I did not get it to work. I was also running out of HDD space. It turns out I had more problems. I think I need to setup this on a server and try again.
