### ISSUE TITLE
Import-NAVEncryptionKey fails...always?

### ISSUE THREAD

**Issue by dynamicsblog** [Microsoft/nav-docker#114]
Hi, I tried to **switch the database credentials from "Windows" to "Database"**. For this, I have first to set up the encryption. I have tried different new encryption keys by using cmdlet New-NAVEncryptionKey and then Import-NAVEncryptionKey... but I get always _the error_

_----------
Import-NAVEncryptionKey : The import failed. The provided encryption key file contains invalid data and could not be imported.
----_

The key files are created using nav powershell cmdlets... ? 
Any idea? 

Thanks, Rene

**Comment by freddydk** [comment]
Tobias Fenster blogged about how to do this a few days ago.
https://www.axians-infoma.de/navblog/how-to-connect-nav-on-docker-to-an-existing-sql-database-quick-and-dirty/
More interestingly probably is that today, new images will be published which allows you to set databaseusername and databasepassword (or databasesecurepassword) as parameters right there on docker run.
I also recommend you take a look at navcontainerhelper from the powershell gallery, where you can specify -databasecredential and this will be transferred to the container securely. blog post coming up on my blog.

**Comment by dynamicsblog** [comment]
Thank you Freddy, I will try it! 
/Rene

**Comment by freddydk** [comment]
Did you manage to make this work?

**Comment by dynamicsblog** [comment]
Hi Freddy not yet, I had to use it as it is because I needed the machine. But I have scheduled a new test in the next days! 
Rene

**Comment by dynamicsblog** [comment]
Hi Freddy, experimenting with this ... it just supports to be used with an external SQL or does it also set up a default nav container with database credentials (service tier to sqlexpress) ? 

So I want to have default nav container with database credentials instead of NT Authority/System ? 
Btw. I did not find an environment variable to set up the service tier account when running docker?  I am right? 

Thanks,
Rene

**Comment by freddydk** [comment]
The NAV Service Tier is running as a system account, so yes, unless you use gMSA, you will have to use database authentication with SQL Server.
