### ISSUE TITLE
Report preview inside the web client seems not to work .. 

### ISSUE THREAD

**Issue by dynamicsblog** [Microsoft/nav-docker#115]
When you are working with the web client (developer preview-at) and run a report preview inside the browser (every browser) only a blank screen appears.

tested scenario: 
. a standard report without filter - blank. 
. a standard report with a filter with (no data exists for it)- report preview header appears. 
. a standard report with filter - (data exists) - blank. 
. a custom report on a custom table - working.

Using a locally installed CTP installation preview works fine. 

Ideas?
Thanks,
Rene

**Comment by freddydk** [comment]
I seem to remember that one version of the docker image had a wrong reportviewer component installed.
Could you do a docker inspect on the container and send the labels section (versions etc)
Thanks

**Comment by dynamicsblog** [comment]
{
        "Id": "2e2d7a48c325c31db5e85044e4f5fb172d5df997e01a0d395c636d0e264aa04a",
        "Created": "2017-11-29T07:31:56.8472666Z",
        "Path": "powershell",
        "Args": [
            "-Command",
            "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
            ".\\Run\\start.ps1"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 5424,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-11-29T07:32:13.5900535Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2017-11-30T10:51:43.7688785Z",
                        "End": "2017-11-30T10:51:44.7815717Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-30T10:52:14.7813233Z",
                        "End": "2017-11-30T10:52:15.6943311Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-30T10:52:45.7908057Z",
                        "End": "2017-11-30T10:52:47.3326029Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-30T10:53:17.3321425Z",
                        "End": "2017-11-30T10:53:19.2356138Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-30T10:53:49.2361048Z",
                        "End": "2017-11-30T10:53:54.1404805Z",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:61ad6d7785c67ce58852dc93f5209edb51440669f75ca43499d93a5940d18605",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\docker\\containers\\2e2d7a48c325c31db5e85044e4f5fb172d5df997e01a0d395c636d0e264aa04a\\2e2d7a48c325c31db5e85044e4f5fb172d5df997e01a0d395c636d0e264aa04a-json.log",
        "Name": "/nav2018DP1117",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": [
            "c495f831302c9570693ea237122b2f10dc1914a4827b3d0d551623907f946d40",
            "af3b2a9b332ebe49435c5aff5dc7880bd9191f9f209e971ef75e0483b4e0ac6b"
        ],
        "HostConfig": {
            "Binds": [
                "C:\\DEMO:C:\\DEMO",
                "C:\\DEMO\\Extensions\\nav2018DP1117\\my:C:\\Run\\my"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "process",
            "CpuShares": 0,
            "Memory": 4294967296,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\docker\\windowsfilter\\2e2d7a48c325c31db5e85044e4f5fb172d5df997e01a0d395c636d0e264aa04a"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\demo",
                "Destination": "c:\\demo",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\demo\\extensions\\nav2018dp1117\\my",
                "Destination": "c:\\run\\my",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "nav2018DP1117",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "auth=Windows",
                "username=vmadmin",
                "ExitOnError=N",
                "locale=de-AT",
                "licenseFile=",
                "useSSL=N",
                "securePassword=76492d1116743f0423413b16050a5345MgB8ADEARAB0ADAARgBhAC8AdABOAEgAYQBEAFcAbQBlAHMAMQBuAEMAeQBRAFEAPQA9AHwAYQBjAGYANgA3AGUAOAA4ADAAMwAxAGQAYgAzADgAMgA4AGYAYQBiADcAYwAyADQAMwBiADMAMQA2AGEAYgAyADkAZQBkADgANQBhAGYANQBmADcAOABjADMAMwBkAGQAZgBhADUAYwAxADIAOAA1AGEAZgA0ADQAOAAzAGIANwA=",
                "passwordKeyFile=C:\\DEMO\\Extensions\\nav2018DP1117\\my\\aes.key",
                "removePasswordKeyFile=Y",
                "accept_eula=Y",
                "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-0.11.14434.vsix",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/441cce9c-697f-4594-a483-1b0a1cfcf573",
                "DatabaseServer=localhost",
                "DatabaseInstance=SQLEXPRESS",
                "DatabaseName=CronusAT",
                "COUNTRYURL=https://nav2016wswe0.blob.core.windows.net/dvd/c2da5ec1-1942-457a-b6fe-1d1f4da9754f"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "microsoft/dynamics-nav:devpreview-at",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "at",
                "created": "201711091228",
                "cu": "november",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Freddy Kristiansen",
                "nav": "devpreview",
                "osversion": "10.0.14393.1770",
                "tag": "0.0.3.3",
                "version": "11.0.19097.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "3b8c8b357459cfe165bb7d02a5a99603908a4b93c54cdacb041a7b0fcc51fa6d",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "80/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "3b8c8b357459",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "d0cb92b2db364c39e4046a4d3b72e38edabc31994defc1d28385c4873a53ea57",
                    "EndpointID": "672c1d996427b8e93e7bcae6d98bf918d0726f28d4c647abc74e53a907f7e94d",
                    "Gateway": "172.18.224.1",
                    "IPAddress": "172.18.239.186",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:93:2b:b8",
                    "DriverOpts": null
                }
            }
        }
    }

**Comment by freddydk** [comment]
I can repro this and we are investigating.
Are you saying, that a custom created report works...?

**Comment by dynamicsblog** [comment]
only if the custom report uses a custom table... because of this I thought it is a performance issue..but tables with fewer data like "payment terms" produce the same issue..

**Comment by freddydk** [comment]
The reason for this is a missing DLL in the container.
If you copy the t2embed.dll from c:\windows\system32 on the host to the same folder in the container, then it should work. Until this is fixed in NAV on Docker generic image, you can use this after starting the contianer:
Copy-FileToNavContainer -containerName <containerName> -localPath C:\windows\System32\t2embed.dll -containerPath C:\Windows\System32\t2embed.dll

**Comment by hgnamvn** [comment]
Thank freddydk,

I really work well.

**Comment by freddydk** [comment]
generic image 0.0.4.4 contains this fix and new images based on 0.0.4.4 are being rolled out as we speak.
