### ISSUE TITLE
Question: Powershell scripts not executing on docker run while they are mapped

### ISSUE THREAD

**Issue by LaurensT1** [Microsoft/nav-docker#116]
I have following docker run command:

`docker run -m 4G --hostname="demo_container" --name="demo_container" -v "c:\my\:c:\run\my" -e 'accept_eula=Y' -e username=admin -e password=Azerty123! microsoft/dynamics-nav:2017-cu3-be
`

I map my local folder c:\my to the container folder c:\run\my. In my local folder I have two .ps1 files that should be executed, but they don't. I have also tried  an exec command:

`docker exec -it demo_container "c:\run\my\settings_OpzetDBenInstance_LF.exe"`
and
`docker exec -it demo_container "c:\run\my\OpzetDBenInstance_LF.exe"`

As can be assumed from the script name, I execute a settings file that contains variables to be used by the actual commandscript, which reads it with 
`$settings = 'C:\my\run\settings_OpzetDBenInstance_LF.exe'`
 `. ($settings)`

This has proven to perfectly work locally. However, when I execute these in Docker I get the error: 

> [2J[H[1;31;40m. : The term 'C:\my\run\settings_OpzetDBenInstance_LF.exe' is not recognized [22;37;40m
[1;31;40mas the name of a cmdlet, function, script file, or operable program. Check the [22;37;40m
[1;31;40mspelling of the name, or if a path was included, verify that the path is [22;37;40m
[1;31;40mcorrect and try again.[22;37;40m

My question is, how do I get the settings file to be correctly read by my command file? I have no clue how, since I already use the -it parameter, which should run the commands in a session.

If anybody knows (extra, less important question though): as you can see i'm executing .exe files which I converted from .ps1 to .exe files. Docker exec only seems to accept win32 applications? Is there a way to just execute the .ps1 files via docker? I've been looking on the web but haven't found anything, not much documentation for these kinds of issues.

Thanks in advance!

**Comment by freddydk** [comment]
You write that you have two powershell scripts that should be executed - and later you show two .exe files?

The PowerShell scripts that you can place in the my folder, which will be executed follow a strict naming which you can read about in the how to document on this site.
ex. AdditionalSetup.ps1 is executed at a certain time.
if you place files there with names not given in the how to they will never be executed

**Comment by Koubek** [comment]
Hi, I would like to help you but I am a bit confused. I don\`t understand your problem very well.

You say: 
> In my local folder I have two .ps1 files that should be executed, but they don't.
But then you are trying to run two **exe** files (instead of **ps1** files):
```
docker exec -it demo_container "c:\run\my\settings_OpzetDBenInstance_LF.exe"
docker exec -it demo_container "c:\run\my\OpzetDBenInstance_LF.exe"
```

You should be able run **ps1** file in the containers without any issue. Actually, practically everything we use to run containers (the internal scripts) are PowerShell scripts.

**Comment by LaurensT1** [comment]
Yes, it's indeed confusing. I execute .exe files which I converted from the ps1 files as a workaround to see if the mapping was correct, since they didn't seem to be executed on docker run. I didn't know they had to be strictly named. I will try what freddydk said, that should work. I didn't know that. Thanks a lot!

**Comment by freddydk** [comment]
Scripts are called with a purpose - SetupDatabase is called to setup the database etc.
You should read the document carefully and not just try your way - else you will be back with a lot of other questions here.

**Comment by LaurensT1** [comment]
Yes, I figured that out already by checking out the how to, thanks for the confirmation. I will put my settingsfile and actual commandsfile in one .ps1 file and put it under 'AdditionalSetup.ps1'. I think according to the documentation this will be the best method in my situation?
