### ISSUE TITLE
PS scripts on docker

### ISSUE THREAD

**Issue by ShdowX** [Microsoft/nav-docker#117]
Hello,

How can I run my powershell scripts on the docker container?

For example:
I want to export .navdata file from a template company, then create 2 new company's and import this .navdata file back into the 2 company's.

Is this possible on docker?

Kind Regards,
Nicasens Kenneth

**Comment by freddydk** [comment]
Yes
docker exec -it <containername> powershell
will start a powershell prompt inside the container.
then do 
. c:\run\prompt.ps1
in order to load all NAV Powershell Cmdlets
or use navcontainerhelper which have functions like enter-navcontainer or open-navcontainer.

**Comment by ShdowX** [comment]
I will try that, thanks for the quick reaction.

**Comment by jeesus450** [comment]
navcontainerhelper module has also Invoke-ScriptInNavContainer function.

Example:
Invoke-ScriptInNavContainer -containerName $containerName -scriptblock {Write-Host "Test"}
