### ISSUE TITLE
PS script works locally, but returns 'company does not exist' on NAV function 'copy-NAVcompany' onDocker

### ISSUE THREAD

**Issue by LaurensT1** [Microsoft/nav-docker#118]
Hello,

I have following function in a PS script (called AdditionalSetup.ps1):

`function CopyNAVCompanies(){

    for ($i = 0; $i -lt $CompanySuffix.Count; $i++) 
    {
        for ($j = 0; $j -lt $SourceCompanies.Count; $j++) 
        {            
            $DestinationCompany = $DestinationCompanies[$j] + $CompanySuffix[$i]
            Copy-NAVCompany -ServerInstance $NewNAVserverInstance -SourceCompanyName $SourceCompanies[$j] -DestinationCompanyName $DestinationCompany        
        }
    }
`
This for-loop loops over an array of suffixes and makes for every item found in this suffix array a copy of a company found another array 'sourceCompany' and concatenates this suffix with it. These variables are declared like this:

`$SourceCompanies = "CRONUS BELGIQUE SA, CRONUS BELGIË NV"`
`$CompanySuffix = "-MD","-DYN"`

Most important thing to note: I'm trying to test this in docker, because I know that for 

> microsoft/dynamics-nav:2017-cu3-be

both CRONUS BELGIQUE SA and CRONUS BELGIË NV are default companies for this image.

This function has proven to work locally, but on docker I get following error:

> VERBOSE: Closing admin connection to ServerInstance 
'MicrosoftDynamicsNavServer$NAV'
VERBOSE: Admin connection to ServerInstance 'MicrosoftDynamicsNavServer$NAV' 
has been closed
The Company does not exist. Identification fields and values: Name='C'

How come? I set the variable that declares the NAV-instance like this: `$NewNAVserverInstance = 'NAV' because I know Docker uses NST name 'NAV'.

My docker run is set like this:

`docker run -m 4G --hostname="demo_container" --name="demo_container" -e 'accept_eula=Y' -v "c:\my\:c:\run\my" -e username=admin -e password=Azerty123! microsoft/dynamics-nav:2017-cu3-be
`

What might be the cause of this? I preload the NAV cmdlets in my script already. I also tried an alternative method of opening a powershell session on my container AFTER initialization with `docker run -it demo_container powershell`, then executing the prompt.ps1 script which successfully loads NAV cmdlets and then just executing my script by browsing to the correct mapped folder and then executing my own script, but this returns the same error.

**Comment by freddydk** [comment]
I have a hard time seing that this works locally.
$SourceCompanies = "CRONUS BELGIQUE SA, CRONUS BELGIË NV"
make $sourcecompanies a string - not an array.
When you enumerate over that you get each character as an item - hence the name='C'
if you want to create an array, I think you need to use:
$SourceCompanies = @("CRONUS BELGIQUE SA","CRONUS BELGIË NV")

**Comment by freddydk** [comment]
Did you manage to make the script work?
Can I close the issue?

**Comment by LaurensT1** [comment]
Yes, the script works now. I also completely understand the concept of what and when the strictly named PS-scripts are executed thanks to this GitHub page and a previous question of mine. Thanks a lot for your help!
