### ISSUE TITLE
NAV 2016-RTM-NA image - clickonce error

### ISSUE THREAD

**Issue by pzentner** [Microsoft/nav-docker#119]
I just pulled dynamics-nav:2016-rtm-na and when I am trying to install the dev environment through ClickOnce, I am running into the following error:

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://test:8080/NAV/Finsql/Deployment/Finsql.application resulted in exception. Following failure messages were detected:
		+ Downloading http://test:8080/NAV/Finsql/Deployment/ApplicationFiles/Microsoft.Dynamics.Nav.Client.exe did not succeed.
		+ The file 'C:\Users\test\AppData\Local\Temp\Deployment\9RXMBP0D.NM9\60M5HOR4.7EY\Microsoft.Dynamics.Nav.Client.exe' already exists.

I have deleted all files from the Temp directory to make sure that it wasn't anything from an earlier download. I also removed any other installs. It seems that the creation of clickonce doesn't work properly for - at least this version. I am assuming that this is part of the generic NAV image and should also be an issue with others, but I have not had any issue with the latest dev preview image.

So, it seems that the manifest might have an issue for this.

**Comment by freddydk** [comment]
Typically we see this if people are using Chrome.
For some reason, the clickonce manifest doesn't work with chrome, if you used Chrome, could you try IE?

**Comment by pzentner** [comment]
I was using Edge, does this also not work? Does it have to be the "old IE"?

We have the 2016 and 2017 DEV ENV as ClickOnce on our Azure servers and have no problem with the manifest in chrome and IE and Edge, but we also have implemented a bit differently, which might be the reason why it does work and doesn't work here.

But basically, after I ran into this issue, I pulled the latest Modern DEV image and tried the ClickOnce deploy with the exactly same browser tab for the new version and it worked. Switched back to the old and it didn't work - same browser (Edge)





Peter Zentner
NAV-X, LLC
Phone: +1 877.779.6289
Email: pzentner@nav-x.com
Website: www.nav-x.com
Address: 670 N Beers Street, Bldg 4 - 2nd Floor, Holmdel, NJ 07733

**Comment by freddydk** [comment]
Ok, sounds like there is an issue. 
Will put it on my list of things to check, but the list is fairly long.

If you want to take a stab at figuring out what is wrong you can copy the SetupClickOnceDirectory.ps1 script to a local folder and share that folder to the container using -v c:\local:c:\run\my and modify the script.
This way you will override the standard and you are in control.

**Comment by eknraw** [comment]
@pzentner Yes, same exact issue here using IE.

**Comment by freddydk** [comment]
This has been fixed over the weekend. 
Re-pull the image and run.
