### ISSUE TITLE
Clear environment variable 'DatabaseName' prior to Image build

### ISSUE THREAD

**Issue by ptijsma** [Microsoft/nav-docker#12]
I tried creating an container with the following command:

```
docker run --name pv2017-demo-w1 -m 4G -e ACCEPT_EULA=Y -e username=xxx -e password=xxxxxx -e ClickOnce=Y -e bakfile="c:\run\my\mysqlbackupfile.bak" -v c:\myfolder:c:\run\my navdocker.azurecr.io/dynamics-nav:2017-cu1
```

But for some reason it kept using the already installed database.
i then added some debugging code to the scripts and found out that the environment variable was already set in the image and that the scripts check for the existence of this.

I've now added this to my SetupVariables.ps1 to prevent this from happening.

```
if ($databaseName -eq 'CRONUS') {
    Write-Host "Bugfix: Reset databaseName if env:databaseName is CRONUS"
    Write-Host "        (Assumption that the Environment Variable was already set in VM at build time)"
    $databaseName = ''
}
```
Now it's happily restoring my backupfile and using that in the resulting container:

**Output:**

```
Initializing...
** Notice: Custom SetupVariables.ps1 starting **
** DEBUG: PRE env:databaseName: [CRONUS] **
** DEBUG: PRE databaseName    : [] **
** DEBUG: Default Behaviour databaseName    : [CRONUS] **
Bugfix: Reset databaseName if env:databaseName is CRONUS
        (Assumption that the Environment Variable was already set in VM at build time)
** DEBUG: POST databaseName    : [] **
Disabling Password Complexity Requirements
** Notice: Custom SetupVariables.ps1 completed **
Running Specific Image
Starting Local SQL Server
Using NavUserPassword Authentication
Using Database .bak file 'c:\run\my\mysqlbackupfile.bak'
Modify NAV Service Tier Config File for Docker
Hostname is 9f88718660a7
.
.
.

```

**Comment by freddydk** [comment]
Yeah, I can see why this is happening. I will fix this.

**Comment by freddydk** [comment]
I think a better fix to SetupVariables is:

$bakfile = "$env:bakfile"
if ($bakfile -ne "") {
    $databaseServer = "localhost"
    $databaseInstance = ""
    $databaseName = ""
} else {
    $databaseServer = "$env:databaseServer"
    $databaseInstance = "$env:databaseInstance"
    $databaseName = "$env:databaseName"
    if ($databaseServer -eq "") {
        $databaseServer = "localhost"
    }
}

Meaning that if you specify a bakfile, you are running the local Sql Server.
In case you want to use a bakfile and a different SQL Server, you should restore the bakfile manually and specify databaseServer, Instance and Name to the Docker run command.

**Comment by freddydk** [comment]
FIx checked in - specific images will be rebuild over the next days.
