### ISSUE TITLE
No language modules in NAV images

### ISSUE THREAD

**Issue by StevenHit** [Microsoft/nav-docker#120]
Hi,

I downloaded some of the Belgian NAV 2016 & 2017 images. Unfortunately, language modules for NL and BE do not seem to be installed. Only English. Can this be added in the future?

Thx

**Comment by freddydk** [comment]
I can change the langauge to dutch (belgium) and get this:
![image](https://user-images.githubusercontent.com/10775043/33488342-9e63a1d2-d6b0-11e7-8c28-60590e44ed03.png)
Could you be more specific as to where you are missing the language modules?

**Comment by StevenHit** [comment]
Hi Freddy,

Thanks for your quick response.

Very strange. I downloaded & installed as shown below, but the container does not contain language modules. Am I doing something wrong?

[cid:image001.jpg@01D36ABE.D5B89290]

Thx

**Comment by freddydk** [comment]
If you tell me how you run the docker image, add the docker inspect and describe how and why you came to the conclusion that language modules are not included, then I will try to help.

**Comment by StevenHit** [comment]
Hi Freddy,

Here you have a scenario:

As an example, I downloaded an run CU10 for Belgium …

[cid:image002.jpg@01D36B54.8F874C30]

In the web client, I can only select “English” …

[cid:image004.jpg@01D36B54.8F874C30]

In the NAV service folder in the container, there are no language folders …

[cid:image006.jpg@01D36B54.8F874C30]

[cid:image008.jpg@01D36B54.8F874C30]

The same for the web client program folder …

[cid:image010.jpg@01D36B54.8F874C30]

I have attached the output of the inspect command.

Thanks in advance for your help.

Regards,
Steven

**Comment by freddydk** [comment]
I am sorry, but I cannot see the images in your post. Not sure if you can - but I have tried in different browsers and your issue doesn't make much sense without the images.

**Comment by StevenHit** [comment]
Hi Freddy,

Please find images attached.

Thanks

**Comment by freddydk** [comment]
Steven, sorry but you are responding to issues in Github - not by email.
Please go to github and see what your responses looks like.
I really want to help, but it takes a lot of time to decipher things and have to ask for more info.
You cannot attach files, you cannot include images. Open the issue in a browser and type your response.

but... I now did spend some time in trying to figure out what this is and found out that you are right,
It looks like localizations with multiple languages doesn't get their local installers run in 2017 and earlier. NAV 2018 and Dev Preview works.
This means that DK version is OK and f.ex. BE is not.

I will rebuild the images affected over the next days (after fixing the bug) and update them.

**Comment by StevenHit** [comment]
Hi Freddy,

Indeed & sorry, I was just replying to the e-mails. Not directly on the website.

I’m glad you were able to simulate the issue and that the solution is in the pipeline.

Thx,
Steven

**Comment by freddydk** [comment]
No harm done, New versions of BE, CH and NA will be on docker hub sometime monday I think.

**Comment by freddydk** [comment]
All images (2016, 2017 and 2018) NA, BE and CH has been re-deployed with language modules installed

**Comment by StevenHit** [comment]
I tried it and it's ok now.

Thanks for your fast response.
