### ISSUE TITLE
Container availability : '2017-rtm-CZ'

### ISSUE THREAD

**Issue by fvet** [Microsoft/nav-docker#123]
Just tried to pull in the '2017-rtm-CZ' image without success. Seems like the image is not available (yet?), whereas '2017-CZ' (latest = CU13), '2017-cu12-CZ' can be download without any problems?

**Comment by Koubek** [comment]
You are right, the Czech 2017 RTM image is not there. I`ve listed the versions via API, the rest of the images (2017-rtm-??) was generated yesterday.

**Comment by freddydk** [comment]
CZ wasn't included in 2017 RTM as far as i recall.
I think CZ was included a few months after.

**Comment by freddydk** [comment]
Note, btw. that tags are lower case - if the image was there it would be:
docker pull microsoft/dynamics-nav:2017-rtm-cz

**Comment by Koubek** [comment]
Of course, I was trying it using lowercase. So this means that Czech release doesn't have its own RTM?

**Comment by freddydk** [comment]
it would be strange to have the Czech version to be at cu10, based on w1 cu13.
Yes, I could have tagged a specific version of the Czech localization with RTM as well, but my assumption is that people will go for slightly newer versions than RTM at this time.
So the versioning of all images are based on the W1 version and the country localizations will follow.

**Comment by fvet** [comment]
@freddydk Still not clear why the 2017-cz-rtm docker image is not available.

Checking https://mbs.microsoft.com/customersource/Global/NAV/downloads/product-releases/msdnav2017download, it seems like 2017 CZ is available for download (check the exe version ,the build states 13682 = RTM). The DVD is named 'Dynamics.100.CZ.2087101.DVD'.

Checking https://support.microsoft.com/en-us/help/3210255/released-cumulative-updates-for-microsoft-dynamics-nav-2017 and https://support.microsoft.com/en-us/help/3209071, it seems like NAV 2017 CZ was shipped with CU1 as well (although it is not available as docker image)

Reason why I'm looking for the 2017 CZ RTM version is that we need to upgrade a database to 2017 CZ CU15 and I'm using the docker images to download and extract the init/target text files to compare and upgrade (it's much faster than downloading and installing the DVD).

**Comment by freddydk** [comment]
In 2017 CZ shipped a few months later and the naming might be wrong on the docker image – but the first CZ image was:

microsoft/dynamics-nav:2017-cu2-cz

try to compare that with what you have on the DVD.



/Freddy

Fra: Frédéric Vercaemst [mailto:notifications@github.com]
Sendt: 7. februar 2018 14:51
Til: Microsoft/nav-docker <nav-docker@noreply.github.com>
Cc: Freddy Kristiansen <Freddy.Kristiansen@microsoft.com>; Mention <mention@noreply.github.com>
Emne: Re: [Microsoft/nav-docker] Container availability : '2017-rtm-CZ' (#123)


@freddydk<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffreddydk&data=04%7C01%7Cfreddy.kristiansen%40microsoft.com%7Cc5b0193b8d234443093608d56e31cf77%7Cee3303d7fb734b0c8589bcd847f1c277%7C1%7C0%7C636536082567573127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=CtZMy1yjpaB4k9m727YaxzYs28AxSX2DSB9wn4OCzCc%3D&reserved=0> Still not clear why the 2017-cz-rtm docker image is not available.

Checking https://mbs.microsoft.com/customersource/Global/NAV/downloads/product-releases/msdnav2017download<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmbs.microsoft.com%2Fcustomersource%2FGlobal%2FNAV%2Fdownloads%2Fproduct-releases%2Fmsdnav2017download&data=04%7C01%7Cfreddy.kristiansen%40microsoft.com%7Cc5b0193b8d234443093608d56e31cf77%7Cee3303d7fb734b0c8589bcd847f1c277%7C1%7C0%7C636536082567573127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=EREVbySee3oaLe8lhPViQFkKdmXE6%2FULvia66%2F1kFjU%3D&reserved=0>, it seems like 2017 CZ is available for download (check the exe version ,the build states 13682 = RTM). The DVD is named 'Dynamics.100.CZ.2087101.DVD'.

Checking https://support.microsoft.com/en-us/help/3210255/released-cumulative-updates-for-microsoft-dynamics-nav-2017<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.microsoft.com%2Fen-us%2Fhelp%2F3210255%2Freleased-cumulative-updates-for-microsoft-dynamics-nav-2017&data=04%7C01%7Cfreddy.kristiansen%40microsoft.com%7Cc5b0193b8d234443093608d56e31cf77%7Cee3303d7fb734b0c8589bcd847f1c277%7C1%7C0%7C636536082567573127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=mNKYylTl3MjNh8tizIjJDDJyCBbuiQfqrYN56uc0s%2FU%3D&reserved=0> and https://support.microsoft.com/en-us/help/3209071<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.microsoft.com%2Fen-us%2Fhelp%2F3209071&data=04%7C01%7Cfreddy.kristiansen%40microsoft.com%7Cc5b0193b8d234443093608d56e31cf77%7Cee3303d7fb734b0c8589bcd847f1c277%7C1%7C0%7C636536082567573127%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=%2Fp58Wo51KcR%2Fcfz1YYbwIQMwEnl%2FXws13vt6WDGwTnE%3D&reserved=0>, it seems like NAV 2017 CZ was shipped with CU1 as well (although it is not available as docker image)

Reason why I'm looking for the 2017 CZ RTM version is that we need to upgrade a database to 2017 CZ CU15 and I'm using the docker images to download and extract the init/target text files to compare and upgrade (it's much faster than downloading and installing the DVD).

**Comment by fvet** [comment]
Table 18 - 2017_CU0_CZ (DVD) extract

_OBJECT Table 18 Customer
{
  OBJECT-PROPERTIES
  {
    Date=25/10/16;
    Time=12:00:00;
    Version List=NAVW110.00,**NAVCZ10.00;**
  }_
              

Table 18 - 2017_CU2_CZ (Docker) extract

_OBJECT Table 18 Customer
{
  OBJECT-PROPERTIES
  {
    Date=23/01/17;
    Time=12:00:00;
    Version List=NAVW110.00.00.15052,**NAVCZ10.00.00.15052**;
  }_
 
Both versions contain code differences, translation differences, ... as well.
