### ISSUE TITLE
Cannot access WebClient with gMSA enabled

### ISSUE THREAD

**Issue by twityde** [Microsoft/nav-docker#124]
I am running nav-2018-rtm-de as docker container on Windows Server 2016 with transparent network.
A gMSA account with the same name and fqdn as the container hostname is configured.
I can connect from my Workstation with the RTC via Click Once and the local installed C/SIDE Development Client via Windowsauth.

But accessing the Webclient is not possible.

"nltest /query" and "net config workstation" returns the correct values.
Did I miss something?

**Comment by Koubek** [comment]
Hi @twityde! Sorry for coming to you so late.
Have you resolved the problem somehow? If the problem persists just let me know. By the way, have you seen any errors somewhere (browser, logs etc.)?

**Comment by twityde** [comment]
Hi @Koubek! I have still the issue.
The browser logs only "HTTP/1.1 401 Unauthorized".
I cannot find any related event in the eventlog of the container.

**Comment by Koubek** [comment]
Hi, I am back here. One question - did you created properly users in the database? Do you authenticate against an external DB? What is your scenario (especially, where is your database being placed)?

**Comment by twityde** [comment]
hi,
I tried both, with internal and with external database.
User is created.

**Comment by Koubek** [comment]
If you want we can check it remotely (yesterday I resolved another gMSA problems for another partner so if you want we can try it as well). Just drop me an email (you can find my email address on my profile).

**Comment by heidingnvarian** [comment]
Did you guys find a solution to this issue? Having the same problem.
