### ISSUE TITLE
Invoke-NAVCodeunit not working with windows authentication.

### ISSUE THREAD

**Issue by richardrobberse** [Microsoft/nav-docker#126]
I've created a container with windows authentication and the Invoke-NAVCodeunit cmdlet (called from within the container) returns the following error:

invoke-navcodeunit : The server has rejected the client credentials.
    + CategoryInfo          : NotSpecified: (0:Int32) [Invoke-NAVCodeunit], FaultException`1
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$nav,Microsoft.Dynamics.Nav.Management.Cmdlets.InvokeNavCodeunit

Any ideas?

**Comment by freddydk** [comment]
I don't know if gMSA setup will solve the issue. but that would be one way.
Else you can create the container administrator as a NAV user (this is the user you are running in a Container powershell prompt):
New-NAVServerUser NAV -WindowsAccount "user manager\containeradministrator"
New-NAVServerUserPermissionSet NAV -WindowsAccount "user manager\containeradministrator" -PermissionSetId SUPER
and then perform your invoke-navcodeunit - should work - haven't tried.

**Comment by richardrobberse** [comment]
Your second option works fine, thanks a lot 👍
