### ISSUE TITLE
No in-client designer on Docker

### ISSUE THREAD

**Issue by srideout2525** [Microsoft/nav-docker#127]
I have created a local docker container. I can open both web client, C/SIDE and Windows Client. 
But I cannot get it into Design mode. No design button, and when I use F6, then it publish and opens the client, but in normal mode.
Similar to logged issue : https://github.com/Microsoft/AL/issues/1000

**Comment by freddydk** [comment]
If you run the on-prem languages (-dk, -na, -gb etc,) instead of the financials versions (-finus, -fingb), it should work.
The financials localizations will be added later,
