### ISSUE TITLE
Cannot access Windows Client with Windows authentication

### ISSUE THREAD

**Issue by tboudrez** [Microsoft/nav-docker#128]
When I run the following script and enter my windows username and password only the web client works. I can see in the web client that it opens with Windows user NAV2018WIN\TIMOTHY.

However the Windows client isn't able to connect. It tries to connect to NAV2018Win:7046/NAV and gives a connection error.

New-CSideDevContainer `
    -containerName 'NAV2018Win' `
    -imageName microsoft/dynamics-nav:2018 `
    -licenseFile 'C:\mylicense.flf' `
    -memoryLimit 4G `
    -updateHosts `
    -accept_eula `
    -Verbose

**Comment by freddydk** [comment]
When you ping nav2018win on the host, what happens?

**Comment by tboudrez** [comment]
I get replies when I ping nav2018win

**Comment by freddydk** [comment]
And it resolves to the IP number of the container?
Strange.
What kind of machine is this?
Azure VM?
Local?
Could you share Docker logs and docker inspect?

Thanks

**Comment by Koubek** [comment]
@tboudrez You can obtain required information using `Get-NavContainerDebugInfo -containerName NAV2018Win -CopyToClipboard` but you need to update **navcontainerhelper** (this function has been published right today).

**Comment by martonsagi** [comment]
Hi, I have the same issue here.
Actually, I have two NAV containers installed and none of them seem to have Port 7046 opened.

Status:
* Web Client: OK
* RTC: Cannot connect
* CSide: no luck with windows auth., but it works with sa / my windows password
* Command/PowerShell prompt: OK

Environment:
* Physical machine (Lenovo T420)
* Windows 10 Enterprise
* Docker: 17.09.1-ce-win42 (14687)
* Navcontainerhelper: 0.2.2.0 (just updated today)

Containers: 
* microsoft/dynamics-nav:latest
* microsoft/dynamics-nav:2017-cu13

Commands used for creation:
```powershell 
New-NavContainer 
-accept_eula 
-containerName NAV2018-W1-RTM 
-imageName microsoft/dynamics-nav:latest 
-licenseFile "E:\NAV\Install\NAV 2018\NAV2018_dev.flf" 
-memoryLimit 3G 
-updateHosts 
-includeCSide 
-doNotExportObjectsToText 
-Verbose
```

```powershell 
New-NavContainer 
-accept_eula 
-containerName NAV2017-W1-CU13
-imageName microsoft/dynamics-nav:2017-cu13
-memoryLimit 3G 
-includeCSide 
-doNotExportObjectsToText 
-Verbose
```

Get-NavContainerDebugInfo:
* [Docker info for NAV2018-W1-RTM](https://gist.github.com/martonsagi/ef5cf3648b8fe8509233595d0cfb3e7a)
* [Docker info for NAV2017-W1-CU13](https://gist.github.com/martonsagi/b656a0ed61bd4b5a4a92258f1b3053a8)

This was my first try with Docker, so I'm open for any suggestions. Thanks!

**Comment by elweilando** [comment]
matches your password the default password complexity requirements?

**Comment by martonsagi** [comment]
Yes, it does meet the default requirements.

**Comment by Koubek** [comment]
@martonsagi Please, could you try to download this folder (or the whole project but then use the folder) and run NAV on Docker using this example.

**Comment by martonsagi** [comment]
@Koubek 

Thanks, I gave it a try. Container was created but could not be started:

```powershell
PS E:\VSCode\nav-docker-examples-master\local_cside> .\run.ps1
Input the user`s password: ---
Initializing...
AuthorizationManager check failed.
```

I could not let it go and I have found this related issue: [#34](https://github.com/Microsoft/navcontainerhelper/issues/34#issuecomment-348043498). I also happen to have a Microsoft Online account tied to my PC, so I guess that's the main issue in my case as well. 
A newly created container with `NavUserPassword` works almost fine, except for the C/Side Management Port.

Still, I find it extremely impressive! Thanks for your great work, guys.

**Comment by Koubek** [comment]
@martonsagi Hi, if you want, you can contact me via email (my e-mail address can be found on the profile). We can check it together using AnyDesk (or TeamViewer but I prefer AnyDesk).

**Comment by Koubek** [comment]
@freddydk Do you have any idea why in a *standard* example that works everywhere occurs the same error `AuthorizationManager check failed` like in #132? There is no DVD here in this case (I suppose :)).

**Comment by Koubek** [comment]
@martonsagi Please, could you check the following link? 
http://tgnp.me/2011/09/powershell-authorizationmanager-check-failed-resolution/ 

I am not sure how it could be exactly related in this particular case to the example you were trying but the error message is the same (at least when you were trying one of my *nav-docker-examples*.

**Comment by freddydk** [comment]
No idea, sorry
I full day meetings yesterday and today - will look at this tonight/tomorrow

**Comment by Koubek** [comment]
Me the same, since yesterday I haven't stopped yet so I am just watching issues in between other tasks.

**Comment by martonsagi** [comment]
Thanks for the suggestions! I'm full for today as well but I'll try it out some time tomorrow.

**Comment by martonsagi** [comment]
@Koubek 
Thanks, IE has indeed blocked some PS files, hence the AuthorizationManager error. 
I was able to try your "local_cside" example and I got the very same result as in my first [comment](https://github.com/Microsoft/nav-docker/issues/128#issuecomment-351083524).

**Comment by srideout2525** [comment]
I was running into the same issue, unable to access windows client. I had local version installed. I uninstalled the local version and now I am able to access.

**Comment by freddydk** [comment]
Was this issue resolved?

**Comment by srideout2525** [comment]
It was only solved for me by uninstalling my local version of 2018.

**Comment by freddydk** [comment]
Ok, thanks.
That is probably just something we have to accept.
