### ISSUE TITLE
New-NAVEncryptionKey and Import-NAVEncryptionKey not working with 2015 a older

### ISSUE THREAD

**Issue by afromazzoni** [Microsoft/nav-docker#129]
i would like to connect my 2015 on docket to a local DB but i cannot use New-NAVEncryptionKey and Import-NAVEncryptionKey to do so because they are not supported in nav 2015. any advice? thanks.

**Comment by Koubek** [comment]
I am afraid it wouldn't be possible to connect NAV 2015 using SQL credentials. We discussed this limitation with @tfenster when we were working on Dockerfiles for NAV. We internally use **gMSA** so we are OK with this limitation and I have never investigated more...
Let's wait for @freddydk`s response.

**Comment by freddydk** [comment]
Correct, NAV 2015 didn't support this - only Windows Auth, so this will need to be setup using windows Auth, probably gMSA

**Comment by afromazzoni** [comment]
thanks! i will ask my sql guy to set up gMSA
