### ISSUE TITLE
Error when opening C/SIDE Enviroment

### ISSUE THREAD

**Issue by mrabus** [Microsoft/nav-docker#130]
Hi guys,

i found an error when creating a container for a German database. For example using the following command:

New-CSideDevContainer `
    -containerName $containername `
    -ImageName microsoft/dynamics-nav:2017-de `
    -licenseFile "D:\mydevlicense.flf" `
    -Credential $credential `
    -memoryLimit 4G `
    -updateHosts `
    -auth NavUserPassword `
    -accept_eula 

When I try to open the C/SIDE development environment I receive the following error:

---------------------------
Microsoft Dynamics NAV Development Environment
---------------------------
Die Wahlmöglichkeit 'yes' ist nicht vorhanden.

Die Wahlmöglichkeiten sind:

Nein, Ja
---------------------------
OK   
---------------------------

The problem is the created link to the development environment: 

If I check the properties -> target I see the following:
"C:\DEMO\Extensions\nav2017latestcu\Program Files\100\RoleTailored Client\finsql.exe" servername=nav2017latestcu\SQLEXPRESS, Database=CronusDE, ntauthentication=yes

To make this work I have to change ntauthentication=yes to ntauthentication=ja. I guess this behavior also occurs with other languages.

**Comment by richardrobberse** [comment]
I think this has to do with settings in your zup file, try setting your language to English or remove your zup file.

**Comment by freddydk** [comment]
in fact I should be setting ntauthentication to 1 instead of yes - 1 is the same in all countries:-)

**Comment by richardrobberse** [comment]
@freddydk that's even better 👍

**Comment by mrabus** [comment]
@richardrobberse: I had no zup file when the error first occured 

@freddydk: Great idea 🥇

**Comment by freddydk** [comment]
This is fixed in navcontainerhelper 0.2.2.1 - just released
