### ISSUE TITLE
gMSA Error when starting Docker 

### ISSUE THREAD

**Issue by PleachiM** [Microsoft/nav-docker#133]
Hi I can not figure out what I did wrong when I'm trying to start my container with gMSA. 
I configured my gMSA with this guide and the test worked 
[https://blogs.msdn.microsoft.com/markweberblog/2016/05/25/group-managed-service-accounts-gmsa-and-sql-server-2016/]

C:\Users\Admin>docker run -e ACCEPT_EULA=Y -e auth=Windows -e username=demo\admin microsoft/dynamics-nav:2018-rtm-at
Initializing...
Starting Container
Hostname is 731b852474ca
PublicDnsName is 731b852474ca
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore NAV Web Server Instance
Creating http download site
Adding demo\admin to sysadmin
Msg 15401, Level 16, State 1, Server 731B852474CA\SQLEXPRESS, Line 6
Windows NT user or group 'demo\admin' not found. Check the name again.
Msg 15007, Level 16, State 1, Server 731B852474CA\SQLEXPRESS, Procedure sp_addsrvrolemember, Line 33
'demo\admin' is not a valid login or you do not have permission.
Msg 15151, Level 16, State 1, Server 731B852474CA\SQLEXPRESS, Line 10
Cannot alter the login 'demo\admin', because it does not exist or you do not have permission.
Creating NAV user
The Windows account could not be mapped to a valid security identifier (SID).

Any good guide how I can set it up? Configuration: 
server1 (DC)
server2 (docker host)

using local admin to to this

**Comment by tfenster** [comment]
The link you are referencing to only discusses gMSAs for SQL, but you need to look into gMSA for containers. I would suggest to follow [this](https://gist.github.com/PatrickLang/27c743782fca17b19bf94490cbb6f960) from "Create Group Managed Service Account" to "Test a container using the service account" and let us know the outcome

**Comment by PleachiM** [comment]
Thank you for your fast response. Can you explain me the difference between the two documents? One is for SQL Server and one is for IIS. So I guess both could not be done step by step, or? 

But ... I tried it and it's not working. After I deleted all created AdsKeys (to make sure there is only one) and Service Accounts created and started all over again. 

There is a Section on "https://github.com/Microsoft/nav-docker/blob/master/HOWTO.md" 

docker run -e ACCEPT_EULA=Y -e auth=Windows -e username=europe\freddyk navdocker.azurecr.io/dynamics-nav:2017

But how can this work without the credentialspec json? 

I already talked about this with Jakub that I have a lot of problems with so many documentations which are around but all of them need different preferences. 

I guess I'm completely wrong on one part of all. I need to go much deeper into the basics. :(

If you know a good place where I can find a compressed guide I would be thankful.

**Comment by Koubek** [comment]
I'll add [one additional example](https://github.com/Koubek/nav-docker-examples) focused on **gMSA** configuration and usage focused on **NAV** soon.

I hope we will cover also a short demo during the [planned webinar](https://register.gotowebinar.com/register/2635590232096811011).

**Comment by PleachiM** [comment]
Thank you Jakub I know this repo and like it a lot!!! 👍

**Comment by tfenster** [comment]
@PleachiM the main difference between the two documents is not SQL / IIS but that your link has no relation at all to Containers. Did you get to the step of testing the account in a Container? I would suggest to first try it in a plain Windows Server core  Container and if the verification steps work, then move to NAV. Or wait until @Koubek does his example :)

**Comment by PleachiM** [comment]
Hey, I will for sure try it again tomorrow or the next day. I will notice you here how I could manage it. And a big "Thank you" for what you are doing here ... 🥇

**Comment by PleachiM** [comment]
What I did so far ... 
gMSA Setup

Example: 
Two servers in a domain with only one domain controller (demo environment) 

Servers:
cgk-server01-dc		(cgk-server01.cgk-demo.local)
cgk-server02		(cgk-server02.cgk-demo.local)

cgk-server01-dc as domain controlle
cgk-server02 as docker host server with docker EE installed

AD:
==============
Group which hosts the servers who are allowed to use gMSA
"gMSA Computers"
ckg-server02 is added to this group 

Steps done: 

1. Check if there is a KDSRoot-Key
>
$RootKey = Get-KDSRootKey | Out-String
Write-Host "Root $RootKey"
<
if this command brings a result then you can skip step 2 (There should only be one root key per domain) 

2. Add KDSRootKey
>
Add-KdsRootKey –EffectiveImmediately
<
-EffectiveImmediately should only be done in test environments or if you only have one dc which should also only happen in test environments :) 

3. Create a Group which will hold all computers which should be able to use gMSA
>
$group = New-ADGroup -GroupCategory Security -DisplayName "gMSA Computers" -Name 'gMSA Computers' -GroupScope Universal
Add-ADGroupMember -Identity 'gMSA Computers' -Members (Get-ADComputer -Identity 'CGK-SERVER02')
<

4. Create a group managed Service account
>
New-ADServiceAccount -name gMSASvcAccount -DnsHostName 'gMSASvcAccount.cgk-demo.local' -PrincipalsAllowedToRetrieveManagedPassword 'gMSA Computers' -Path "dc=cgk-demo,dc=local"
<
I just added the gMSASvcAccount to the root tree of the domain. Good Idea!? I allowed the before created group to retrieve passwords of this account

5. Test the created Service Account from the Host Computer which was added to the group in step 3
In my case this only worked after restart of the Host Computer to update the AD information??? 
>
Test-ADServiceAccount gMSASvcAccount

If the result = true you can go on with step 6

6. Connect to the host computer cgk-server02 and install the gMSA Service Account
>
Install-AdServiceAccount gMSASvcAccount
<

Just to provide you with information about this. I have not created the credentialSpecc like in other examples. But those examples are also different because they use an external sql server. So I'm not sure if needed. As I have seen in another post... (also for external sql) so the container hostname has to match the json file. 

<<<
 think your container is not domain-joined (SQL errors).

I can see you are missing -e auth=Windows (which is not mandatory but we use it with gMSA as we can authenticate using our windows accounts) and --security-opt "credentialspec=file://[container_hostname].json". --security-opt is a must. Without this flag gMSA does not work.

If the previous is OK and you are still in troubles, I would recommend some internal validations (running the following commands from the container):

Run container with -e ExitOnError=N flag. With this flag, the container will remain active.
After failure goto the container docker exec -it [container_name] powershell and try the following:
ping devnav20181
nltest /query - the result must be the following:
Flags: 0
Connection Status = 0 0x0 NERR_Success
The command completed successfully
>>>

**Comment by PleachiM** [comment]
Docker with gMSA is now working with big help from Jakub. I had a logical problem with the naming of the SvcAccount and the Docker host and also the setup is not that easy when you accidently created multiple KdsRoots. I do not go any deeper in the problems I had because Jakub told me there will be an example on his repo for this. 🥇
