### ISSUE TITLE
ExportToNewSyntax error using ModifiedObjectsAsDeltas and Export-NavContainerObjects

### ISSUE THREAD

**Issue by TimothyWatkins** [Microsoft/nav-docker#134]
I am trying to upgrade nav 2017 code to nav 2018 (Extensions V2) - so my thought was to use 
the following process
Import-ObjectsToNavContainer (modified nav 2017 objects) then simply use the Convert-ModifiedObjectsToAl in order to use in Visual Studio Code and compile.

Unfortunately the Convert-ModifiedObjectsToAl needs the original objects in newsyntax in order to work but when I use either ModifiedObjectsAsDeltas or Export-NavContainerObjects using the export to new syntax (which has recently been changed in Export-NavContainerObjects) I get the same fatal error as shown below - "A parameter cannot be found that matches parameter name 'ExportToNewSyntax'."

Any ideas about what i can do to get past this error? I really need to utilize the  Convert-ModifiedObjectsToAl function for my upgrade.

-------------------------------------------------------------------------------------------------------------------
PS C:\Users\hosadmin> Export-ModifiedObjectsAsDeltas -containerName nav2017cu11 -useNewSyntax -sqlCredential sa
Export Objects with filter 'modified=Yes' (new syntax) to C:\ProgramData\NavContainerHelper\Extensions\nav2017cu11\modified-newsyntax\objects.txt (container path)
A parameter cannot be found that matches parameter name 'ExportToNewSyntax'.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.2.0\ObjectHandling\Export-NavContainerObjects.ps1:42 char:5
+     Invoke-Command -Session $session -ScriptBlock { Param($filter, $o ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Export-NAVApplicationObject], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Export-NAVApplicationObject
    + PSComputerName        : b1e1b9b56e688153ba9ab999faabb07aa8f5fa7f02207218a9239b96177a0615

-------------------------------------------------------------------------------------------------------------------

PS C:\Users\hosadmin> Export-NavContainerObjects -containerName nav2017cu11  -objectsFolder "C:\ProgramData\NavContainerHelper\Extensions\nav2017cu11\my\Objects" -sqlCredential sa -exportTo 'txt file (new syntax)' -filter 'modified=no' -Verbose
Export Objects with filter 'modified=no' (new syntax) to C:\ProgramData\NavContainerHelper\Extensions\nav2017cu11\my\Objects\objects.txt (container path)
A parameter cannot be found that matches parameter name 'ExportToNewSyntax'.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.2.0\ObjectHandling\Export-NavContainerObjects.ps1:42 char:5
+     Invoke-Command -Session $session -ScriptBlock { Param($filter, $o ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Export-NAVApplicationObject], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Export-NAVApplicationObject
    + PSComputerName        : b1e1b9b56e688153ba9ab999faabb07aa8f5fa7f02207218a9239b96177a0615

**Comment by freddydk** [comment]
NAV 2017 does not have the ability to export to new syntax - that is only NAV 2018 (with modern dev).
remove the usenewsyntax flag and you should be good.

Newsyntax is only used when exporting objects in order to convert them into AL - and that must be done from 2018

**Comment by TimothyWatkins** [comment]
Yeps - that would then make sense! :)

**Comment by freddydk** [comment]
Note that the navcontainerhelper issues should be filed in issues under www.github.com/microsoft/navcontainerhelper
Then people have a better chance of finding solved issues.
Thanks
