### ISSUE TITLE
Problem regarding Docker Image "microsoft/dynamics-nav:2018-rtm-de": Unknown Property "ImplicitType"

### ISSUE THREAD

**Issue by dNsl9r** [Microsoft/nav-docker#135]
_This is a cross post from Microsoft Forums, as I do not get any answer there till now.
[Microsoft Forum Link](https://social.msdn.microsoft.com/Forums/en-US/7d5a02ab-646d-4858-a185-7f0769cd1cff/problem-regarding-docker-image-microsoftdynamicsnav2018rtmde-unknown-property-implicittype?forum=windowscontainers)_

Hi,
I created a azure machine and on that machine I created a Docker Container using Nav-ContainerHelper and the Docker Image "**microsoft/dynamics-nav:2018-rtm-de**".
When I'm starting the NAV C/Side Development Environment and export a Page (e.g. Page 10) as Text File every field got a new property: "ImplicitType".
The property contains the table field type declaration, e.g. "ImplicitType=Code10".
When I try to reimport the Text Object I get the following error:
ImplicitType is not an option
I did not change the Object after export.
On a local NAV Installation, done not via docker, I do not get this property when exporting Objects.

I used the following Docker Image:
microsoft/dynamics-nav        2018-rtm-de         bb3e7d98c912        8 days ago          16.3GB
NAV Build Version is: **11.0.19394.0-de**
NAV Container Generic Tag is: **0.0.4.1**
The same happens with the following Docker Image:
microsoft/dynamics-nav        2018-rtm-w1        bc22f9746d41        6 days ago          15.7GB

Any idea what went wrong?

**Comment by freddydk** [comment]
How do you perform the export as text file?

**Comment by dNsl9r** [comment]
Hi Freddy,
I was working the classical way - C/Side Development Environment , Object Designer, Mark Object, Export, select text format.
Attached please find the exported Page 10, as txt.
[P10.txt](https://github.com/Microsoft/nav-docker/files/1558882/P10.txt)

**Comment by Koubek** [comment]
OK, this happens when the export in a new format is enabled. Also, an explicit export (from C/SIDE) exports the object in a new format.

**Comment by Koubek** [comment]
BTW, with `-e enableSymbolLoading=N` the importing back works correctly.

**Comment by dNsl9r** [comment]
@Koubek Thanks for your answer, did not know that! Is there any documentation about this?
Where to set the `-e enableSymbolLoading=N` ? Tried to change the startup parameters of the generated Desktop shortcut, but it is not recognized as a known parameter. Should work somehow for reimporting when using the C/Side DevEnv right?

**Comment by Koubek** [comment]
You can find more details here:
https://docs.microsoft.com/en-us/dynamics-nav/developer/devenv-running-cside-and-al-side-by-side

Then you can see the implementation in the docker image (the flag is active by default and it works only for 2018 images as the setting is valid only for them):
https://github.com/Microsoft/nav-docker/pull/98/files

**Comment by dNsl9r** [comment]
Thank you Jakub, my C/Side DevEnv gets started with "generatesymbolreference=yes". If I remove the parameter the exported Object does not Include the new property "ImplicitType". No matter what, I am not able to **import** the object including the new property via the C/Side DevClient. I'd guess the reason it the finsql.exe, so I'll close this issue here.

**Comment by Koubek** [comment]
@dNsl9r Thanks, actually the described behavior was implemented in my [C/SIDE on Docker example](https://github.com/Koubek/nav-docker-examples/tree/master/local_cside). Check this:
https://github.com/Koubek/nav-docker-examples/blob/7e95b67393e7137ee4a8a95ac86a0113c9c5fd70/local_cside/my/HelperFunctions.ps1#L72
and then:
https://github.com/Koubek/nav-docker-examples/blob/7e95b67393e7137ee4a8a95ac86a0113c9c5fd70/local_cside/my/HelperFunctions.ps1#L82
