### ISSUE TITLE
How do i debug a nav on docker session?

### ISSUE THREAD

**Issue by afromazzoni** [Microsoft/nav-docker#136]
i copied the RTC folder on my folder then ran the dev env. form which i tried to debug an active session, i can see the server instance i want to debug but when i try to access i get this:
![image](https://user-images.githubusercontent.com/29460414/34047564-917aeb9e-e1a8-11e7-8673-c1a35fe56651.png)

i am using NAV user password

**Comment by freddydk** [comment]
How did you create the container? Looks like you are using SSL and have not imported the SSL certificate on the host? with docker logs you can find the url of the certificate for download and install.

Alternatively, you can use the navcontainerhelper with this:

New-NavContainer -accept_eula -containerName test -imageName microsoft/dynamics-nav -auth NavUserPassword -doNotExportObjectsToText -includeCSide

I have just successfully started a debug session.
