### ISSUE TITLE
$databaseName not specified on restart in case restoring own BAK

### ISSUE THREAD

**Issue by Koubek** [Microsoft/nav-docker#137]
I have possibly found an issue. Maybe there is a purpose but I can't see it ;)

Scenario: 
+ I am restoring own BAK file.
+ When I `docker run` everything is OK.
+ `SetupVariables.ps1` leaves, in this case, the value of `$databaseName` empty but it is fine as the variable `$databaseName` is being set later inside `SetupDatabase.ps1` ($databaseName = "mydatabase").
+ I can reference later the variable, in my case within `AdditionalSetup.ps1` file.
+ The situation changes when I restart the container. The container works but I can reference the variable `$databaseName` because it is not being set.
+ This happens because `SetupDatabase.ps1` does nothing while restarting. There is just `# Nothing to do` but I suppose we should at least set the variable to be consistent. Or maybe the variables could be preassigned before, in `SetupVariables.ps1` and then we could remove away their initialization from `SetupDatabase.ps1` and leave just the code that restores the database.

I repeat, maybe I am missing something and this is not a bug or maybe there is some other point I simply do not see. Actually, NAV service works correctly. This is why I haven't done a PR with changes, I prefer to discuss it first.

**Comment by freddydk** [comment]
Clearly a bug. I think my original idea was to set the environment variable databasename to mydatabase, wouldn't that solve the issue?

**Comment by Koubek** [comment]
The idea of presetting the env variable is nice but this change only wouldn't fix the problem right now. Please, check this:
https://github.com/Microsoft/nav-docker/blob/03fd915f7371ecfc8e2ecc7bcf0feef92b00c53c/Run/SetupVariables.ps1#L67-L70

**Comment by freddydk** [comment]
You are right.
Wouldn't a better fix be to remove these lines from setupdatabase:
    $databaseName = "mydatabase"

    # Restore database
    $databaseServer = "localhost"
    $databaseInstance = "SQLEXPRESS"

and add the $databaseName = mydatabase to setupvariables?

**Comment by Koubek** [comment]
Exactly, this was my proposal in the first comment.
> Or maybe the variables could be preassigned before, in SetupVariables.ps1 and then we could remove away their initialization from SetupDatabase.ps1 and leave just the code that restores the database.

**Comment by freddydk** [comment]
Gr8, sorry:-(
Did you try to override the two with this fix - and it worked?

**Comment by Koubek** [comment]
No problem. I have done just some basic check but I prefer to repeat all (docker run, docker stop, docker start). Then I'll create a PR.

**Comment by freddydk** [comment]
PR accepted, thanks Jakub
