### ISSUE TITLE
Docker on vm in my azure domain.

### ISSUE THREAD

**Issue by ShdowX** [Microsoft/nav-docker#139]
Hello,

I can't deploy a docker vm for NAV and put it into my virtual network.
If this is possible i can than use my domain users to login into a terminal server let them run the docker images i provide on the docker VM.

I use: aka.ms/getnav

**Comment by freddydk** [comment]
I guess you can create a Windows Server 2016 with containers and then use docker run or the navcontainerhelper to spin up containers in the VM
getnav is for quickly creating a demo/test VM with special requirements.

**Comment by ShdowX** [comment]
Oke this works now, i had some problems in the past that the virtualization was not enabled on azure servers. Thanks for the info
