### ISSUE TITLE
Setting system locale on docker run

### ISSUE THREAD

**Issue by LaurensT1** [Microsoft/nav-docker#140]
Hello,

Is it possible to change system locale (via an -e variable I assume?) on docker run?

**Comment by freddydk** [comment]
-e locale=en-US

**Comment by LaurensT1** [comment]
I tried -e locale=en-US.UTF-8 for example, because I also want to have this. But this is not supported with this syntax it seems. Any other possible way to do this?

**Comment by freddydk** [comment]
The code handling the locale is in SetupVariables and looks like this:

$locale = "$env:locale"
if ($locale)  {
    $cultureInfo = new-object System.Globalization.CultureInfo $locale
    $regionInfo = new-object System.Globalization.RegionInfo $locale
    Set-WinHomeLocation -GeoId $regionInfo.GeoId
    Set-WinSystemLocale -SystemLocale $cultureInfo
    Set-Culture -CultureInfo $cultureInfo
}

Not sure what the .UTF8 would do, but -e locale=da-DK should work.

**Comment by LaurensT1** [comment]
Alright, thanks!
