### ISSUE TITLE
"No access to Microsoft Dynamics NAV" with external Database

### ISSUE THREAD

**Issue by elweilando** [Microsoft/nav-docker#143]
I use the SetupDatabase Script from the NAV on Docker HOL.pdf to connect my container to an external Microsoft SQL Server. I have two databases they I try to connect. Booth have the same SQL Server credentials. With both databases I can start the images without error and I can open CSIDE and compile objects.

But with one database I can't open the Windows Client. I get always the error 

"You do not have access to Microsoft Dynamics NAV. Verify that you have been set up as a valid user in Microsoft Dynamics NAV."

I try this with several images. I think it is an issue with the database. But I have no idea what it could be. Has anyone an idea?

**Comment by freddydk** [comment]
Which authentication are you using?
Have you added the user you are trying to use as a user in the NAV Database?

**Comment by elweilando** [comment]
I use windows authentication. 
Both database don't contains the windows user in the user table. 
The Windows user has db_owner on both databases in SQL Server.
The SQL Server runs on the host for the docker images.

**Comment by freddydk** [comment]
I would assume that you have to add the Windows user in the user table.

**Comment by elweilando** [comment]
You're right. I use New-ServerUser after the container is running and it works now. Thank you.

In navstart.ps1:151 you call SetupNavUsers.ps1 only if $usingLocalSQLServer is true.
Maybe it's would better to setup the navusers independent from local or external sql-server?

**Comment by freddydk** [comment]
No, typically when using an external SQL Server, it is NOT with the demo database (when using the demo database, there is no real reason to use external SQL Server) - and in this case, it is expected that license, users etc. are in place.
Thanks for letting us know that it works.
