### ISSUE TITLE
Wrong Help Server

### ISSUE THREAD

**Issue by yukonn** [Microsoft/nav-docker#144]
Hi,

I'm using NAV2017-AU version. I notice help url is pointing to localhost instead of Navision running server. This is not so much important but we would like to see full set of Navision is running on docker.

Regards,

**Comment by freddydk** [comment]
Help server has a dependency on Windows Search, which is a desktop service and cannot at this time run on Windows Server Core.
You will have to install help server on a different Server and manually set the help url for now.

**Comment by yukonn** [comment]
Hi @freddydk,

Thanks for your reply. At this moment we will use different server for help.

Regards,
