### ISSUE TITLE
Error message about t2embed.dll

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/nav-docker#145]
Build: microsoft/dynamics-nav:2018-rtm-nl

New-CSideDevContainer -accept_eula -containerName navservernl `
                      -imageName microsoft/dynamics-nav:2018-rtm-nl `
                      -licenseFile https://www.dropbox.com/s/dude/mylicense.flf?dl=1 `
                      -Credential (Get-Credential) `
                      -auth NavUserPassword `
                      -additionalParameters @("--network=tlan","--ip 172.21.31.4")

![image](https://user-images.githubusercontent.com/19155831/34488085-5f56c77c-efd7-11e7-9747-0d96437eb6dd.png)

Host is Windows Server 2016 Core installation [10.0.14393]
Any idea where this comes from?

**Comment by freddydk** [comment]
Yes, the t2embed.dll is not available on Server Core, which is the reason why I copy it to the container (for pdf viewing). I didn't consider the situation where you are running server core as the host.
If you copy the file from the host's host to the host - you should be good.
I will consider what I can do about this.

**Comment by ajkauffmann** [comment]
If the file is needed by the container to render pdf reports, why not include it in the image instead of copying it afterwards?

**Comment by freddydk** [comment]
Will be, but that requires rebuilding all images, which is the reason for (in the time being) I fixed this in navcontainerhelper:-)

**Comment by freddydk** [comment]
generic image 0.0.4.4 has been released and all images are being updated over the next days.
Latest 2016, 2017 and 2018 have been released on 0.0.4.4
