### ISSUE TITLE
Service fail to connect the external database.

### ISSUE THREAD

**Issue by yukonn** [Microsoft/nav-docker#147]
Hi,

I try to connect docker's Navision (2018-AU) service to my local my database using below script. The script is run successful but service fail to start.

`$cred = Get-Credential
New-NavContainer -accept_eula `
                 -containerName nav2018-au `
                 -imageName "microsoft/dynamics-nav:2018-au" `
                 -includeCSide `
                 -auth NavUserPassword `
                 -additionalParameters @("-e databaseServer=XXX-N043","-e databaseName=NAV110-AU_CU0-B19394","-e DatabaseCredential=$cred") `
                 -doNotExportObjectsToText`

**Script Result**

Creating container nav2018-au from image microsoft/dynamics-nav:2018-au
Waiting for container nav2018-au to be ready
Initializing...
Starting Container
Hostname is nav2018-au
PublicDnsName is nav2018-au
**Using NavUserPassword Authentication**
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint CB4B4A15D80AEABF1614CD65571C134B42A7F799
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore NAV Web Server Instance
Creating http download site
Creating Windows user admin
Container IP Address: 172.27.216.228
Container Hostname  : nav2018-au
Container Dns Name  : nav2018-au
Web Client          : http://nav2018-au/NAV/WebClient/
Dev. Server         : http://nav2018-au
Dev. ServerInstance : NAV

Files:
http://nav2018-au:8080/al-0.12.15355.vsix

Initialization took 102 seconds
Ready for connections!
Read CustomSettings.config from nav2018-au
Create Desktop Shortcuts for nav2018-au
Copy C:\windows\System32\t2embed.dll to container nav2018-au (C:\Windows\System32\t2embed.dll)
Nav container nav2018-au successfully created

**Debug Info**
    "container.labels":  {
                             "country":  "au",
                             "created":  "201712090731",
                             "cu":  "rtm",
                             "eula":  "https://go.microsoft.com/fwlink/?linkid=861843",
                             "legal":  "http://go.microsoft.com/fwlink/?LinkId=862604",
                             "maintainer":  "Dynamics SMB",
                             "nav":  "2018",
                             "osversion":  "10.0.14393.1770",
                             "tag":  "0.0.4.3",
                             "version":  "11.0.19394.0"
                         },
    "container.env":  [
                          "username=admin",
                          "databaseInstance=",
                          "removePasswordKeyFile=Y",
                          "auth=**NavUserPassword**",
                          "useSSL=N",
                          "securePassword=\u003cspecified\u003e",
                          "databaseName=NAV110-AU_CU0-B19394",
                          "licenseFile=\u003cspecified\u003e",
                          "passwordKeyFile=c:\\run\\my\\aes.key",
                          "ExitOnError=N",
                          "locale=en-AU",
                          "databaseServer=XXX-N043",
                          "DatabaseCredential=System.Management.Automation.PSCredential",
                          "accept_eula=Y",
                          "VSIXURL=\u003cspecified\u003e",
                          "NAVDVDURL=\u003cspecified\u003e",
                          "COUNTRYURL=\u003cspecified\u003e"
                      ]

**CustomSettings.config**
add key="DatabaseName" value="NAV110-AU_CU0-B19394"
add key="**DatabaseUserName**" value=""
add key="**ProtectedDatabasePassword**" value="" 
add key="EnableSqlConnectionEncryption" value="false"
add key="TrustSQLServerCertificate" value="false"

Is it my script wrong?

**Comment by freddydk** [comment]
Your script is correct, your assumption is wrong.
It is by design that it doesn't create users in external databases.
When connecting to an external database (could be a production database in the future) I cannot just add super users to the user table.

**Comment by yukonn** [comment]
Hi @freddydk,

Thanks for your reply. Now, i understand on your design. But I do not understand why CustomerSettings.config **DatabaseUserName** and **ProtectedDatabasePassword** still blank and service is stopped. Do i need to config manual for this part.

Regards,

**Comment by freddydk** [comment]
Sorry, missed that

When using navcontainerhelper the -databaseServer, -databaseName and -databaseCredential should not be in additionalparameters - they are parameters on new-navcontainer.

New-NavContainer -accept_eula
-containerName nav2018-au -imageName "microsoft/dynamics-nav:2018-au"
-includeCSide -auth NavUserPassword
-databaseServer=XXX-N043
-databaseName=NAV110-AU_CU0-B19394
-DatabaseCredential=$cred
-doNotExportObjectsToText

AdditionalParameters are for parameters not supported by new-navcontainer and you could specify database username and password in additionalparameters but the environment variables for this are different and you would have to encrypt password and other things).

**Comment by freddydk** [comment]
You can inspect the container afterwards to see what environment variables the above command causes.

**Comment by yukonn** [comment]
Hi  @freddydk,

Thanks again. I'll test again and let you know the result.

Regards,

**Comment by yukonn** [comment]
Hi @freddydk,

I got bad luck. I got below error after I run the script.

**Startup script**
```
New-NavContainer -accept_eula `
    -containerName nav2018-au `
    -imageName "microsoft/dynamics-nav:2018-au" `
    -includeCSide -auth NavUserPassword `
    -doNotExportObjectsToText `
    -databaseServer "XXX-N043" `
    -databaseName "NAV110-AU_CU0-B19394" `
    -databaseCredential (Get-Credential)
```

**Result**
Change Database Connection

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
Creating Nav container nav2018-au
Using image microsoft/dynamics-nav:2018-au
NAV Version: 11.0.19394.0-au
Generic Tag: 0.0.4.3
Removing container nav2018-au
Removing Desktop Shortcuts for container nav2018-au
Successfully removed container nav2018-au
Creating container nav2018-au from image microsoft/dynamics-nav:2018-au
Waiting for container nav2018-au to be ready
Initializing...
Starting Container
Hostname is nav2018-au
PublicDnsName is nav2018-au
Using NavUserPassword Authentication
Starting Internet Information Server
Import Encryption Key
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 67
at <ScriptBlock>, C:\Run\navstart.ps1: line 92
at <ScriptBlock>, C:\Run\start.ps1: line 92
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is nav2018-au
PublicDnsName is nav2018-au
Using NavUserPassword Authentication
Starting Internet Information Server
Import Encryption Key
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 67
at <ScriptBlock>, C:\Run\navstart.ps1: line 92
at <ScriptBlock>, C:\Run\start.ps1: line 92
at <ScriptBlock>, <No file>: line 1
Initialization of container nav2018-au failed
At C:\Program
Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.2.2\ContainerHandling\Wait-NavContainerReady.ps1:40 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...v2018-au failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container nav2018-au failed


**Docker Inspect on Container**
            "Env": [
                "username=navuser",
                "useSSL=N",
                "securePassword=76492d1116743f0423413b16050a5345MgB8AFQASwBiAEcANABrAGIATgBEAFgAZwBwAHcAZwBSAE8AYQBPAFUA
ZwA1AFEAPQA9AHwAMQBmAGUAOQBkAGIAYwAwAGEAZQBlAGYAOQBiADYAOAAwADQAOABmADYAMAA2ADYAMQBmAGEAOQBmAGMAYwBlADcAZgA4AGIAYQA4ADcA
YwA0AGMAMwAwADkAMQBjADAAMQBhADAAOABkADYANAAyAGUANgBlADcAZAAzADIAZgA=",
                "passwordKeyFile=c:\\run\\my\\aes.key",
                "auth=NavUserPassword",
                "locale=en-AU",
                "licenseFile=",
                "databaseName=NAV110-AU_CU0-B19394",
                "accept_eula=Y",
                "ExitOnError=N",
                "databaseUsername=NavSvcAc",
                "databaseSecurePassword=76492d1116743f0423413b16050a5345MgB8AHMAZwBRAEwAdAAyAGUARABMAEIAdQB4AFkAUQBvACsA
MQA4AGQAcAB0AFEAPQA9AHwAZgAzAGQAMQAyADQAMAAxAGYAMgBiAGMANQAwAGQAMgA3AGUAMgBkAGYAZgBlAGQAMAA1AGYAOQAxADYANAAzADcAYQAxADcA
YQAzAGIAZAA2AGYAZAAwADAAOABhADIANgA1ADUAOAA0ADIAMwA1AGYAZAA4ADAAMgBlADgAMwA=",
                "databaseServer=XXX-N043",
                "databaseInstance=",
                "removePasswordKeyFile=Y",
                "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-0.12.15355.vsix",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/e44c4618-e859-4ce6-8688-e9057750b8b8",
                "COUNTRYURL=https://nav2016wswe0.blob.core.windows.net/dvd/914bdb84-aa42-40bd-af9a-9c45b867314d"
            ],

Noted: I disabled all firewall on my local pc and sql server/database can browse from another machine.


Regards,

**Comment by freddydk** [comment]
Is the SQL Server another Docker container or is it another machine?

You could try to use

Docker run -it microsoft/windowsservercore powershell

and see if you can ping the database server from within a container and then use

install-module sqlps -force
invoke-sqlcmd xxx

in order to check that you can actually connect to that sql server from a container.

I have seen people having problems when using the docker host as sql server.

**Comment by yukonn** [comment]
Hi @freddydk,

You bring me right direction. 
I didn't get any reply from my local pc (I didn't use docker sql) if I try to ping from nav docker to my local. The thing is I used the host name instead of ip.

Here is result
[NAV2018-AU]: PS C:\run\my> ping xxx-n043

Pinging xxx-n043.xxx.com.sg [**172.88.1.30**] with 32 bytes of data:
Reply from **172.88.1.47**: Destination host unreachable.
Reply from **172.88.1.47**: Destination host unreachable.
Reply from **172.88.1.47**: Destination host unreachable.
Reply from **172.88.1.47**: Destination host unreachable.

Ping statistics for **172.88.1.30**:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss)

Again, I got reply from my local host if I use IP instead of host name.

Here is result

[NAV2018-AU]: PS C:\run> ping 172.88.1.47

Pinging 172.88.1.47 with 32 bytes of data:
Reply from 172.88.1.47: bytes=32 time<1ms TTL=127
Reply from 172.88.1.47: bytes=32 time<1ms TTL=127
Reply from 172.88.1.47: bytes=32 time<1ms TTL=127
Reply from 172.88.1.47: bytes=32 time<1ms TTL=127

Ping statistics for 172.88.1.47:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

Now, I used databaseserver name to IP and can connect to local sql database.

```
New-NavContainer -accept_eula `
    -containerName nav2018-au `
    -imageName "microsoft/dynamics-nav:2018-au" `
    -memoryLimit 3G `
    -includeCSide -auth NavUserPassword `
    -doNotExportObjectsToText `
    -databaseServer "172.88.1.47" `
    -databaseName "NAV110-AU_CU0-B19394" `
    -databaseCredential (Get-Credential)
```

Thanks and Regards,

**Comment by lem81** [comment]
I get the same error but the provided solution doesn't work for me.

This is my command:
New-NavContainer 
    -containerName test 
    -accept_eula 
    -accept_outdated 
    -alwaysPull 
    -auth Windows 
    -Credential (get-credential -credential $env:USERNAME) 
    -databaseCredential (get-credential) 
    -databaseInstance SQL2016 
    -databaseName N720_Main_ROS 
    -databaseServer 172.27.252.186 
    -doNotExportObjectsToText 
    -imageName microsoft/dynamics-nav:2018 
    -includeCSide 
    -memoryLimit 4G 
    -shortcuts Desktop 
    -updateHosts

The strange thing is that when I check the NAVServerConfiguration it uses the defaults for DatabaseServer, Instance and Name and not the ones that I specified.

NetworkProtocol                                                 Default
**DatabaseServer                                                  localhost
DatabaseInstance                                                SQLEXPRESS
DatabaseName                                                    CRONUS**
DatabaseUserName
ProtectedDatabasePassword
EnableSqlConnectionEncryption                                   true
TrustSQLServerCertificate                                       true
ServerInstance                                                  NAV

Regards,

**Comment by freddydk** [comment]
the values are probably not written in the configuration if the connection fails.
You would have to troubleshoot using the same steps provided - spin up another container with windowsservercore and see what it takes to connect to the SQL Server. It can be firewall, docker setup and a lot of other things and is likely not a problem with the NAV container image at all.
