### ISSUE TITLE
Container microsoft/dynamics-nav:generic is not a NAV container

### ISSUE THREAD

**Issue by mrabus** [Microsoft/nav-docker#148]
Hello all, 

i am struggeling at bit trying to run NAV2013 R2 CU50 on docker. I adapted freddy's blogpost to create the container, using this command to create my container: 
New-NavContainer -accept_eula `
                 -containerName nav2013r2_fr `
                 -navDvdPath "D:\BiTeam\Docker\CU 50 NAV 2013 R2 FR\NAV.7.1.49579.FR.DVD\" `
                 -navDvdCountry fr `
                 -updateHosts `
                 -memoryLimit 4G `
                 -doNotExportObjectsToText `
                 -Credential $credential `
                 -licenseFile "D:\BiTeam\Entwicklerlizenzen\nav2013r2.flf" `
                 -includeCSide `
                 -myScripts @("D:\BiTeam\Docker\nav-docker-master\Run\71")

Executing this command I receive an error: 
![grafik](https://user-images.githubusercontent.com/2485163/34662914-30c1ef00-f454-11e7-969c-ad89eeea6404.png)

Has anybody seen this issue before?

**Comment by freddydk** [comment]
Yes, I have seen this before and will be checking in a fix for this later today.
Update navcontainerhelper in a few hours using update-module navcontainerhelper -force

**Comment by mrabus** [comment]
Thanks for the quick feedback. 

I will try again in the afternoon.

**Comment by freddydk** [comment]
Should be updated now.

**Comment by mrabus** [comment]
Seems to work :) 

Now I'm missing .NET framework but that is something I can fixed. 

Issue closed, thank you very much for your help!
