### ISSUE TITLE
Micrrosoft Report Viewer is not installed

### ISSUE THREAD

**Issue by elweilando** [Microsoft/nav-docker#149]
If I try to print oder preview I get this issue

"You cannot print or preview a report when Microsoft Report Viewer is not installed. Microsoft Report Viewer can be installed from the Prequisite Components on the Microsoft Dynamics NAV Installation media. Contact your system administrator.

NAV Version: 10.0.16996.0-de
Generic Tag: 0.0.4.4
Creating container navN4group from image microsoft/dynamics-nav:2017-cu7-de

Docker inspect
[
    {
        "Id": "f57d42aeb8babd07d3524ab2844fb8780106ab345b93920386005494a9879829",
        "Created": "2018-01-12T13:06:57.6996673Z",
        "Path": "powershell",
        "Args": [
            "-Command",
            "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
            ".\\Run\\start.ps1"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 10036,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-01-12T13:07:02.2623924Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2018-01-12T14:24:48.4587732+01:00",
                        "End": "2018-01-12T14:24:48.7657229+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-01-12T14:25:18.7655428+01:00",
                        "End": "2018-01-12T14:25:19.0575307+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-01-12T14:25:49.0589396+01:00",
                        "End": "2018-01-12T14:25:49.3499149+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-01-12T14:26:19.351648+01:00",
                        "End": "2018-01-12T14:26:19.6506152+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-01-12T14:26:49.6531841+01:00",
                        "End": "2018-01-12T14:26:49.9726509+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:fb5ca90bd5c0bba83a858b073fe16855d9f02bb66652095397dc07ef050def54",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\docker\\containers\\f57d42aeb8babd07d3524ab2844fb8780106ab345b93920386005494a987982
9\\f57d42aeb8babd07d3524ab2844fb8780106ab345b93920386005494a9879829-json.log",
        "Name": "/navN4group",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "C:\\Users\\navadmin\\AppData\\Local\\Temp\\n4NavDockerEnvironment\\navN4group\\objects\\tmp-export:c:\\
navobjectexport",
                "C:\\ProgramData\\NavContainerHelper:C:\\ProgramData\\NavContainerHelper",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\navN4group\\my:C:\\Run\\my",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\navN4group\\Program Files:C:\\navpfiles",
                "c:\\windows\\system32\\drivers\\etc:C:\\driversetc",
                "navdata:c:\\navdata",
                "C:\\Users\\navadmin\\AppData\\Local\\Temp\\n4NavDockerEnvironment\\navN4group\\objects\\tmp-import:c:\\
navobjectimport"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "process",
            "CpuShares": 0,
            "Memory": 4294967296,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\docker\\windowsfilter\\f57d42aeb8babd07d3524ab2844fb8780106ab345b93920386005494
a9879829"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\windows\\system32\\drivers\\etc",
                "Destination": "c:\\driversetc",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "navdata",
                "Source": "C:\\ProgramData\\docker\\volumes\\navdata\\_data",
                "Destination": "c:\\navdata",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\users\\navadmin\\appdata\\local\\temp\\n4navdockerenvironment\\navn4group\\objects\\tmp-i
mport",
                "Destination": "c:\\navobjectimport",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\users\\navadmin\\appdata\\local\\temp\\n4navdockerenvironment\\navn4group\\objects\\tmp-e
xport",
                "Destination": "c:\\navobjectexport",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper",
                "Destination": "c:\\programdata\\navcontainerhelper",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\navn4group\\my",
                "Destination": "c:\\run\\my",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\navn4group\\program files",
                "Destination": "c:\\navpfiles",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "navN4group",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "auth=Windows",
                "username=navadmin",
                "ExitOnError=N",
                "locale=de-DE",
                "licenseFile=c:\\run\\my\\license.flf",
                "databaseServer=",
                "databaseInstance=",
                "useSSL=N",
                "securePassword=76492d1116743f0423413b16050a5345MgB8AGwAdgBrAFIAUgBQAGsAegBSAHEAaABRADQAbgB0ADkAMgA4AHQA
UwAzAHcAPQA9AHwAMgBiAGUAOQBjAGMAMQBmADUAMQBlADUAZQBkADcAOQA3ADYAYgA4ADkAYQA0ADAAOAA4ADcAMAA0ADUAOQAzAGEANwAwADQAOABjADkA
ZgA3ADAAYwBlADUAMQBjADMAYwA1AGQAYQAyAGEAYQBmAGMAMwBiAGQANwA4AGMAZgA=",
                "passwordKeyFile=c:\\run\\my\\aes.key",
                "removePasswordKeyFile=Y",
                "webClient=N",
                "accept_eula=Y",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/61548b99-2b95-4e92-9772-20fe0a80b69c",
                "DatabaseName=CronusDE",
                "COUNTRYURL=https://nav2016wswe0.blob.core.windows.net/dvd/4dd69b40-e7d9-4c7c-97f9-c8002ac9ac41"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "microsoft/dynamics-nav:2017-cu7-de",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "de",
                "created": "201801070742",
                "cu": "cu7",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=724017",
                "maintainer": "Dynamics SMB",
                "nav": "2017",
                "osversion": "10.0.14393.1770",
                "tag": "0.0.4.4",
                "version": "10.0.16996.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "379d4dcd1b7fe1c3776786628ade02d0e438339b8c7eb5edc88dc73869a88ec0",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "80/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "379d4dcd1b7f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "69bac41d78783f71437fc915903c4fd533e25839d8d81f7208c6c70fe2f87533",
                    "EndpointID": "974f848029e9d7658217336581e322cdd42b9578291999560be0ea8d89b1cda4",
                    "Gateway": "172.23.112.1",
                    "IPAddress": "172.23.124.190",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:96:75:4d",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by freddydk** [comment]
Is this Web Client or Windows Client?
Click Once or copy deployment?

**Comment by elweilando** [comment]
Windows-Client and copy deployment

**Comment by freddydk** [comment]
When running the Windows Client locally you need to install these pre-requisites on your box - that cannot be done from or in the container (the container is "just" a service tier)
Report Viewer 2014: http://www.microsoft.com/en-us/download/details.aspx?id=45496

**Comment by elweilando** [comment]
It works. Thank you.

**Comment by freddydk** [comment]
>           how to enable the Micrrosoft Report Viewer in web client?
Please open a new issue and describe in detail what version you are running, how you started it and what your experience is. Report Viewer is enabled by default and if something is not working as expected we will need to know a whole lot more.
