### ISSUE TITLE
Suggestion for imporvement (use default path - $myPath - for backup file 

### ISSUE THREAD

**Issue by ptijsma** [Microsoft/nav-docker#15]
When supplying a path for a custom backup file, you now need to specify the full path to the shared folder.

it would be nice to be able to either:
- Just specify the backup filename if it resides directly in the root of the share
- Specify the subfolder(s) + backup filename if it resides in a subfolder of the share

**Currently:**

```
docker run -e ACCEPT_EULA=Y -e bakfile="c:\run\my\mysqlbackupfile.bak" -v c:\myfolder:c:\run\my navdocker.azurecr.io/dynamics-nav:2017-cu8
```

**Suggested:**

```
docker run -e ACCEPT_EULA=Y -e bakfile="mysqlbackupfile.bak" -v c:\myfolder:c:\run\my navdocker.azurecr.io/dynamics-nav:2017-cu8
```

**or when in a subfolder of the share:**

```
docker run -e ACCEPT_EULA=Y -e bakfile="sqlbackup\mysqlbackupfile.bak" -v c:\myfolder:c:\run\my navdocker.azurecr.io/dynamics-nav:2017-cu8
```

**Comment by freddydk** [comment]
The my folder is primarily for scripts and you could easily envision that you would share a different folder with databases to Docker for different purposes.
