### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by Finanicals** [Microsoft/nav-docker#150]
we are currently trying to add a nav container in windows 10, here is the comand= (any assistance would be great)

New-NavContainer -accept_eula -containerName Financials -imageName microsoft/dynamics-nav:2018 -includeCSide -doNotExportObjectsToText -memory 4G

9ad3a1014eaf3074db0089777756a50297b661a1e69434a4955aa02372effed1
docker.exe: Error response from daemon: container 9ad3a1014eaf3074db0089777756a50297b661a1e69434a4955aa02372effed1 encountered an error during Start: failure in a Windows sys
tem call: The operation timed out because a response was not received from the Virtual Machine hosting the Container. (0xc0370109).

Commandline: docker run --name Financials --hostname Financials --env auth=Windows --env username="christopherm" --env ExitOnError=N --env locale=en-US --env licenseFile="" -
-env databaseServer="" --env databaseInstance="" --memory 4G --volume "C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContainerHelper" --volume "C:\ProgramData\NavContai
nerHelper\Extensions\Financials\my:C:\Run\my" --restart unless-stopped --env useSSL=N --volume "C:\ProgramData\NavContainerHelper\Extensions\Financials\Program Files:C:\navpf
iles" --env securePassword=76492d1116743f0423413b16050a5345MgB8ADAAVABnAC8AdQBlAE4AaABzAGYAVgAyAG0AdgA5AEoAZwBzAHUANgAzAFEAPQA9AHwAMgA3ADMANAAwAGEAZAAxADEANAAwAGEAMgAzAGYAMAB
mADEAYwA2ADEAYgBjADUANwBiADcAZgBkAGYAOQBmADAAYwBjADEANAA0ADEAMgBlAGYAOABhADAAYwA3AGYAYQBmAGUAYQA5AGUAOQAzADIAOAAyADgAZgBmAGEAZAA= --env passwordKeyFile="c:\run\my\aes.key" --
env removePasswordKeyFile=Y --env accept_eula=Y --detach microsoft/dynamics-nav:2018

**Comment by yukonn** [comment]
Pls use 2Gb or 3GB memory when you spin the new-navcontainer. As far as i know max memory 3GB is max for windows 10. My office laptop can run with 3Gb but sometime can't run. My personal desktop only can use 2gb when i spin the container. So i always use 2Gb to avoide the error.

New-NavContainer -accept_eula -containerName Financials -imageName microsoft/dynamics-nav:2018 -includeCSide -doNotExportObjectsToText -memory **2G**

**Comment by Finanicals** [comment]
Thank you for the speedy reply.

We receieved the following error:

Initialization of container Financials failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.2.4\ContainerHandling\Wait-NavContainerReady.ps1:40 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...nancials failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container Financials failed

Any thoughts

Cheers

Christopher Mackenzie
Financials for Office 365 | Australia
Solution Specialist & Partner Education Lead
1300 191 222
02 8042 9878
www.o365financials.com

**Comment by yukonn** [comment]
i face same error before but i can't remember how am i solve it and what is root cause. :( Pls try this way.
- remove container 
`docker rm Financials`
- delete container folder under %Programdata%\NavContainerHelper\Extensions" 
- restart docker
`restart-service docker`
- stop all running container if you have it.
`docker ps ## check running container)`
- spin again.

**Comment by NAVspecialist** [comment]
Funny I am also running Windows 10 and I do not have any issues.


install-module "NAVcontainerHelper" -Verbose
Update-Module "NAVcontainerHelper" -Verbose
get-help "NavcontainerHelper" -Verbose

$Licensefile = "C:\Users\Palle\Licensefile\NAV2018.flf"
$ImageName = "microsoft/dynamics-nav:2017-cu14-dk"
$ContainerName = "DEV"
$PlainTextPw = "Passw0rd"
$Credential = New-Object -TypeName PSCredential -ArgumentList $env:USERNAME,(ConvertTo-SecureString -String $PlainTextPw -AsPlainText -Force)


New-NavContainer `
    -containerName $ContainerName `
    -accept_eula `
    -accept_outdated `
    -auth NavUserPassword `
    -Credential $Credential `
    -imageName $ImageName `
    -licenseFile $Licensefile `
    -memoryLimit "4G" `
    -includeCSide `
    -Verbose

Start "http://DEV/nav"

**Comment by NAVspecialist** [comment]
Perhaps it has something to do with how much memory you have installed (I have 16gb) and currently only one container running.
