### ISSUE TITLE
build 20258 - Initialization of container navserver failed

### ISSUE THREAD

**Issue by darench** [Microsoft/nav-docker#153]
I get the following error message when spinning up the container with this new build image. I then tried the previous build and it ran fine. 

PS C:\ProgramData\navcontainerhelper> Replace-NavServerContainer -imageName navdocker.azurecr.io/dynamics-nav:11.0.20258.0-finus
Setup new Nav container
Removing container navserver
Using image navdocker.azurecr.io/dynamics-nav:11.0.20258.0-finus
Country finus
Version 11.0.20258.0
Locale en-US
Running navdocker.azurecr.io/dynamics-nav:11.0.20258.0-finus (this will take a few minutes)
Creating Nav container navserver
Using image navdocker.azurecr.io/dynamics-nav:11.0.20258.0-finus
NAV Version: 11.0.20258.0-finus
Generic Tag: 0.0.4.4
Creating container navserver from image navdocker.azurecr.io/dynamics-nav:11.0.20258.0-finus
Waiting for container navserver to be ready
Initializing...
Starting Container
Hostname is navserver
PublicDnsName is odtd365dev.westus.cloudapp.azure.com
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 994F13C5FEB7A3A9934BF9F884075E0D1E265C6F
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore NAV Web Server Instance
Creating http download site
Creating Windows user odtadmin
Enabling SA
Creating NAV user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\my\SetupNavUsers.ps1: line 1
at <ScriptBlock>, C:\Run\navstart.ps1: line 153
at <ScriptBlock>, C:\Run\start.ps1: line 98
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is navserver
PublicDnsName is odtd365dev.westus.cloudapp.azure.com
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 994F13C5FEB7A3A9934BF9F884075E0D1E265C6F
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore NAV Web Server Instance
Creating http download site
Creating Windows user odtadmin
Enabling SA
Creating NAV user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\my\SetupNavUsers.ps1: line 1
at <ScriptBlock>, C:\Run\navstart.ps1: line 153
at <ScriptBlock>, C:\Run\start.ps1: line 98
at <ScriptBlock>, <No file>: line 1
Initialization of container navserver failed
At C:\Program
Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.2.2\ContainerHandling\Wait-NavContainerReady.ps1:40 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...avserver failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container navserver failed

**Comment by freddydk** [comment]
I will have a look at this right away

**Comment by MikeGlue** [comment]
I just came here to log the same issue.......

**Comment by freddydk** [comment]
Yeah, I can repro this as well

**Comment by freddydk** [comment]
The W1 version works: navdocker.azurecr.io/dynamics-nav:11.0.20258.0 - but it looks like some or all of the local builds are broken. I will see if I can fix this asap, but it might not be today.

**Comment by freddydk** [comment]
New images are being beployed now. The -finus build should be working - the other countries will come over the next hour or so.
Sorry for the inconvenience.

**Comment by MikeGlue** [comment]
works now. Thanks Freddy!! :)
