### ISSUE TITLE
When will NAV 2018 CU1 be available on Docker?

### ISSUE THREAD

**Issue by DanielGoehler** [Microsoft/nav-docker#154]
When will [NAV 2018 CU1](https://support.microsoft.com/de-de/help/4058601/cumulative-update-01-for-microsoft-dynamics-nav-2018-build-19846) be available on [Docker](https://hub.docker.com/r/microsoft/dynamics-nav/)?

**Comment by freddydk** [comment]
It has been available since the day it shipped
docker pull microsoft/dynamics-nav:2018 gives you the latest 2018 CU
or
docker pull microsoft/dynamics-nav:2018-cu1

**Comment by DanielGoehler** [comment]
I try to create a new Azure VM with http://aka.ms/getnav. I get an unspecific error when I use 
**microsoft/dynamics-nav:2018-cu1**

<img width="421" alt="error" src="https://user-images.githubusercontent.com/9556549/35436062-47682070-028d-11e8-8298-633b38504366.png">

Then I had a look at the [Docker Hub](https://hub.docker.com/r/microsoft/dynamics-nav/tags/) and at least 2018-cu1 ist not listed there. Is 2018-cu1 supposed to be in that list? The listed **2018-rtm-de** (microsoft/dynamics-nav:2018-rtm-de) worked.

**Comment by freddydk** [comment]
There are 1000 images in the docker hub - you cannot see them all.

I don't know where the error comes from, haven't seen that before, maybe you can click the link and get more info. A lot of things can fail (too simple passwords, no quota and a lot of other things).

microsoft/dynamics-nav will always give you the latest release, latest cu (you don't have to specify 2018-cu1)
microsoft/dynamics-nav:de will give you latest release, latest cu, de

Remember that tags are case sensitive.

**Comment by DanielGoehler** [comment]
Thanks microsoft/dynamics-nav:de works
