### ISSUE TITLE
NAV Server Event Trace Provider is not Registered During Setup

### ISSUE THREAD

**Issue by wortho** [microsoft/nav-docker#155]
It appears that the NAV Server Event provider is not registered during setup in the latest nav docker image. 

PS C:\Program Files\Microsoft Dynamics NAV\110\Service> Get-WinEvent -ListProvider 'Microsoft-DynamicsNAV-Server'
Get-WinEvent : There is not an event provider on the localhost computer that matches "Microsoft-DynamicsNAV-Server".

https://docs.microsoft.com/en-us/dynamics-nav/microsoft-dynamics-nav-server-trace-events

**Comment by freddydk** [comment]
I will have a look at this and include the necessary in an upcoming update of the images.

**Comment by freddydk** [comment]
Isn't this registered as MicrosoftDynamicsNavServer$NAV?

**Comment by wortho** [comment]
Not according to the docs (see link above) "There are two event trace providers that publish different trace events to the event log: Microsoft-DynamicsNAV-Server and Microsoft-DynamicsNAV-Common. The Microsoft-DynamicsNAV-Common provider is strictly for telemetry trace events. All other events use Microsoft-DynamicsNAV-Server. You typically need to specify the event trace provider in the monitoring tool that you are using."

**Comment by wortho** [comment]
Hi,

Just to be sure I tested it on an On-Prem NAV 2018 installation:
 Get-WinEvent -ListProvider 'Microsoft-DynamicsNAV-Server'

Result:
Name     : Microsoft-DynamicsNAV-Server
LogLinks : {Microsoft-DynamicsNAV-Server/Debug, Microsoft-DynamicsNAV-Server/Operational, Microsoft-DynamicsNAV-Server/
           Admin}
Opcodes  : {win:Start, win:Stop}
Tasks    : {ExecuteScalar, ExecuteNonQuery, ExecuteReader, ReadNextResult...}

These ETW events are used for application profiling so it won't work on NAV Docker installs if the Event Provider is not installed.

**Comment by wortho** [comment]
@freddydk Any progress on this?

**Comment by tfenster** [comment]
@freddydk On the off chance that this might be connected: The performance counters are also still missing, maybe those two topics can be fixed together?
