### ISSUE TITLE
devpreview tags for year 2018

### ISSUE THREAD

**Issue by acyvas** [Microsoft/nav-docker#156]
In year 2017 naming convention for devpreview was microsoft/dynamics-nav:devpreview-<month>-<localization>
What is naming convention for year 2018 as month names are starting to get duplicated?
Thank you!

**Comment by freddydk** [comment]
We will probably only have one or two public preview builds, then Tenerife will be released and will be available.
After this, preview bits will be available through MS Collaborate from a private repository.
and... - even if we would run into name clashes, the new would just overwrite the old.

**Comment by acyvas** [comment]
So what is the name of latest devpreview release image?

**Comment by freddydk** [comment]
it is always microsoft/dynamics-nav:devpreview

**Comment by acyvas** [comment]
What  about naming with month number ? microsoft/dynamics-nav:devpreview-january is unavailable

**Comment by freddydk** [comment]
Because it has not been created yet.
you can specify a specific tag to get an older image.
newest will always be what I wrote.
