### ISSUE TITLE
Option to create nav container with database "Recovery model" = "Simple"?

### ISSUE THREAD

**Issue by pir8-x** [Microsoft/nav-docker#157]
Would it be possible to have a switch to create a Nav container with "Recovery model" = "Simple"? I haven't figured out a way to change this outside of the Nav classic IDE => Database => Alter Database. It would be great if this could be scripted.

**Comment by freddydk** [comment]
W1 and all developer preview docker images will in fact use recovery mode simple.
It is a bug, that all images with localizations uses full recovery mode.
I will fix this when the images are rebuilt next time, until then, you can run this command:

docker exec -it <containerid> sqlcmd -S "localhost\SQLEXPRESS" -Q "USE master; ALTER DATABASE <databasename> SET RECOVERY SIMPLE;"

where containerid is the container id and databasename is the name of the database.
The database names for the localized nav containers are Cronus followed by the country code.
CronusDK is the danish database.

**Comment by Koubek** [comment]
Thanks!!!

**Comment by pir8-x** [comment]
Thanks, Freddy!!

**Comment by freddydk** [comment]
All images should be using simple recovery mode by now.
