### ISSUE TITLE
This tool does not support backup files that contain more than one backup set.

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/nav-docker#158]
Hi,

I am running the below command
docker run -m 3g -v c:\my:c:\run\my -e accept_eula=Y -e usessl=N -e auth=Windows -e username=vmadmin -e password=********** -e bakfile="C:\run\my\SQL2014 Backup GAC TradePlus2018.00 NAV2018NL b19394.bak" --name 2018RTMNLserver microsoft/dynamics-nav:2018-rtm-nl

See below the error i am getting:
![image](https://user-images.githubusercontent.com/26792519/36015483-9ed18362-0d94-11e8-87a4-43b62449621f.png)

The backup file i have provided is a single backup file.

Can you please suggest?

Thanks & Regards
Varun Reddy

**Comment by freddydk** [comment]
You could try to name the .bak file some short name without spaces.

**Comment by bachii1010** [comment]
Hi freddy,

i have short end the .bak file but still the same error 
Can you tell me how we can check the compatibility?

Thanks & Regards
Varun Reddy

**Comment by freddydk** [comment]
Not really - I do not have in depth knowledge about SQL backup.
If the .bak file is created correctly, it should work with New-NavDatabase.

**Comment by Koubek** [comment]
Isn't possible that this feature (multiple backup sets) is not available in **Express edition**?

**Comment by freddydk** [comment]
It is the new-navdatabase tool, which doesn't know what to do if multiple backup sets are in a .bak file.
I just started a W1 container, right clicked the Cronus database and selected backup followed by starting the DK container with the W1 backup as bakfile - works fine.
If I however add another backup to the same .bak file, then I get the exact error you are talking about here.
Please create a backup in a new file and try that.

**Comment by freddydk** [comment]
Starting Local SQL Server
Starting Internet Information Server
Using Database .bak file 'c:\run\my\cronus.bak'
This tool does not support backup files that contain more than one backup set.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 47
at <ScriptBlock>, C:\Run\navstart.ps1: line 92
at <ScriptBlock>, C:\Run\start.ps1: line 102
at <ScriptBlock>, <No file>: line 1


TimeGenerated : 2/11/2018 7:00:00 AM
EntryType     : Warning
Message       : Type: Microsoft.Dynamics.Nav.Management.Exceptions.NavCommandEx
                ception
                SuppressMessage: False
                DiagnosticsSuppress: False
                SuppressExceptionCreatedEvent: False
                FatalityScope: None
                Message: <ii>This tool does not support backup files that 
                contain more than one backup set.</ii>
                StackTrace:
                     at Microsoft.Dynamics.Nav.Management.NavCommand.WriteError
                (Exception exception, ErrorCategory category, Object target, 
                Boolean rethrow)
                     at Microsoft.Dynamics.Nav.Management.Cmdlets.NewNavDatabas
                e.InternalProcessRecord()
                     at 
                Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
                Source: Microsoft.Dynamics.Nav.Management
                HResult: -2146233088

**Comment by bachii1010** [comment]
Hi Freddy,

Thanks for the update

i took the backup again and this error was resolved but i am getting the below error

> **_Invalid object name 'master.dbo.$ndo$srvproperty'._**

![image](https://user-images.githubusercontent.com/26792519/36089993-8e1ff5b8-1004-11e8-8ce3-b4880dbc8970.png)

Thanks & Regards
Varun Reddy

**Comment by freddydk** [comment]
Seems like the new .bak file doesn't contain that table.
I think that table is where the license file is stored - try to add a license file to the container -e license=pathtoflf 
Doesn't it tell you the stack trace of where the error happened?
Then it would be good to include that.

**Comment by bachii1010** [comment]
Hi freddy,

I have put the -e license = tag but i am getting the same error.
Can you tell me where to look for stack trace?

**Comment by bachii1010** [comment]
Hi Freddy,

Here is the stack trace
TimeGenerated : 2/12/2018 5:58:05 PM
EntryType     : Warning
Message       : Type: Microsoft.Dynamics.Nav.Types.NavServerNotFoundException
                SuppressMessage: False
                DiagnosticsSuppress: False
                SuppressExceptionCreatedEvent: False
                FatalityScope: None
                Message:
                  <ii>The following SQL error was unexpected:
                  Invalid object name 'master.dbo.$ndo$srvproperty'.
                  </ii>
                StackTrace:
                     at Microsoft.Dynamics.Nav.Management.ServerInstanceConnect
                ion.DoOpenAdminConnection(IAdminService adminService)
                     at Microsoft.Dynamics.Nav.Management.ServerInstanceConnect
                ion.EstablishAdminConnection()
                     at Microsoft.Dynamics.Nav.Management.ServerInstanceConnect
                ion.InternalValidate()
                     at 
                Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
                Source: Microsoft.Dynamics.Nav.Management
                HResult: -2146233088
                ----------------------------------
                Type: System.ServiceModel.FaultException`1[[Microsoft.Dynamics.
                Nav.Types.ServerFault, Microsoft.Dynamics.Nav.Types, 
                Version=11.0.0.0, Culture=neutral, 
                PublicKeyToken=31bf3856ad364e35]]
                Action: http://www.microsoft.com/Dynamics/NAV/51/ServerFault
                Message:
                  <ii>The following SQL error was unexpected:
                  Invalid object name 'master.dbo.$ndo$srvproperty'.
                  </ii>
                StackTrace:
                  
                  Server stack trace: 
                     at System.ServiceModel.Channels.ServiceChannel.HandleReply
                (ProxyOperationRuntime operation, ProxyRpc& rpc)
                     at 
                System.ServiceModel.Channels.ServiceChannel.Call(String 
                action, Boolean oneway, ProxyOperationRuntime operation, 
                Object[] ins, Object[] outs, TimeSpan timeout)
                     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke
                Service(IMethodCallMessage methodCall, ProxyOperationRuntime 
                operation)
                     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke
                (IMessage message)
                  
                  Exception rethrown at [0]: 
                     at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnM
                essage(IMessage reqMsg, IMessage retMsg)
                     at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke
                (MessageData& msgData, Int32 type)
                     at Microsoft.Dynamics.Nav.Types.IAdminService.OpenAdminCon
                nection(ConnectionRequest connectionRequest)
                     at Microsoft.Dynamics.Nav.Management.ServerInstanceConnect
                ion.DoOpenAdminConnection(IAdminService adminService)
                Source: mscorlib
                HResult: -2146233087
                

TimeGenerated : 2/12/2018 5:58:05 PM
EntryType     : Error
Message       : Server instance: NAV
                Tenant ID: <ii>default</ii>
                <ii>Session type: ManagementClient
                Session ID: 9
                User: User Manager\ContainerAdministrator
                Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavSqlException
                ErrorNumber: 208
                SuppressMessage: False
                DiagnosticsSuppress: False
                SuppressExceptionCreatedEvent: False
                FatalityScope: None
                Message:
                  <ii>The following SQL error was unexpected:
                  Invalid object name 'master.dbo.$ndo$srvproperty'.
                  SQL statement:
                  SELECT license FROM [master].[dbo].[$ndo$srvproperty]
                  StackTrace:
                     at System.Environment.GetStackTrace(Exception e, Boolean 
                needFileInfo)
                     at System.Environment.get_StackTrace()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.ThrowNa
                vSqlException(SqlExceptionAdapter exceptionAdapter, String 
                commandText, Boolean isLastExceptionARollbackCause, Boolean 
                logExceptions)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.<>c__Di
                splayClass104_0`1.<ExecuteFunction>b__0()
                     at Microsoft.Dynamics.Nav.Types.NavThread.RunExternalActio
                n[T](Func`1 action)
                     at Microsoft.Dynamics.Nav.Diagnostic.NavDiagnostics.SendTr
                aceTagOnThreshold[T](String tag, Category category, Verbosity 
                verbosity, Int32 threshold, Func`1 action, String message, 
                Object[] parameters)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.Execute
                FunctionWithTrace[T](EventTask task, Func`1 function, String 
                commandText)
                     at 
                Microsoft.Dynamics.Nav.Runtime.NavSqlCommand.ExecuteReader()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseProperties
                .ReadServerPropertiesIfNotAlreadyRead()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseProperties
                .CheckLicenseExists()
                     at Microsoft.Dynamics.Nav.Runtime.NavDatabaseSecurityAndLi
                cense.get_License()
                     at Microsoft.Dynamics.Nav.Runtime.NavSession.SetAndValidat
                eLicense(Byte[] licenseToUse)
                     at Microsoft.Dynamics.Nav.Runtime.NavSession.Open(Boolean 
                useUserPersonalization, Byte[] licenseToUse, Boolean 
                allowAppsDisabledMode)
                     at Microsoft.Dynamics.Nav.Service.NSAdminService.Microsoft
                .Dynamics.Nav.Types.IAdminService.OpenAdminConnection(Connectio
                nRequest connectionRequest)
                     at SyncInvokeOpenAdminConnection(Object , Object[] , 
                Object[] )
                     at 
                System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object 
                instance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                ErrorMappingCombinator(ServiceOperation innerOperation, 
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[] 
                inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase 
                serviceInstance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                PushPopCombinator(ServiceOperation innerOperation, 
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[] 
                inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase 
                serviceInstance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                CreateNewSessionCombinator(ServiceOperation innerOperation, 
                NSServiceBase serviceInstance, Boolean requireNavUser, 
                Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                CreateNewAdminSessionCombinator(ServiceOperation 
                innerOperation, NSServiceBase serviceInstance, MethodBase 
                syncMethod, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase 
                serviceInstance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass10_0.<PerformanceCounterCombinator>b__0()
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                PerformanceCounterCombinator(ServiceOperation innerOperation, 
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[] 
                inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase 
                serviceInstance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                InitClientTelemetryIdsCombinator(ServiceOperation 
                innerOperation, NSServiceBase serviceInstance, MethodBase 
                syncMethod, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase 
                serviceInstance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                TlsClearCombinator(ServiceOperation innerOperation, 
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[] 
                inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase 
                serviceInstance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                Invoke(Object instance, Object[] inputs, Object[]& outputs)
                     at System.ServiceModel.Dispatcher.DispatchOperationRuntime
                .InvokeBegin(MessageRpc& rpc)
                     at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime
                .ProcessMessage5(MessageRpc& rpc)
                     at 
                System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean 
                isOperationContextSet)
                     at System.ServiceModel.Dispatcher.MessageRpc.Wrapper.Resum
                e(Boolean& alreadyResumedNoLock)
                     at System.ServiceModel.Dispatcher.ThreadBehavior.ResumePro
                cessing(IResumeMessageRpc resume)
                     at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContex
                t.<>c__DisplayClass1_0.<ClearThreadLocalStorageDelegate>b__0(Ob
                ject state)
                     at 
                System.Threading.ExecutionContext.RunInternal(ExecutionContext 
                executionContext, ContextCallback callback, Object state, 
                Boolean preserveSyncCtx)
                     at System.Threading.ExecutionContext.Run(ExecutionContext 
                executionContext, ContextCallback callback, Object state, 
                Boolean preserveSyncCtx)
                     at System.Threading.QueueUserWorkItemCallback.System.Threa
                ding.IThreadPoolWorkItem.ExecuteWorkItem()
                     at System.Threading.ThreadPoolWorkQueue.Dispatch()</ii>
                HResult: -2146233088
                ----------------------------------
                Type: System.Data.SqlClient.SqlException
                ClientConnectionId: 0a665aa2-2f62-4df9-a496-cdf7f5755d1d
                Class: 16
                LineNumber: 1
                Number: 208
                Server: LOCALHOST\SQLEXPRESS
                State: 1
                Source: .Net SqlClient Data Provider
                ErrorCode: -2146232060
                Message: <ii>Invalid object name 
                'master.dbo.$ndo$srvproperty'.</ii>
                StackTrace:
                     at 
                System.Data.SqlClient.SqlConnection.OnError(SqlException 
                exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                     at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarnin
                g(TdsParserStateObject stateObj, Boolean 
                callerHasConnectionLock, Boolean asyncClose)
                     at System.Data.SqlClient.TdsParser.TryRun(RunBehavior 
                runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, 
                BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject 
                stateObj, Boolean& dataReady)
                     at 
                System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
                     at System.Data.SqlClient.SqlDataReader.get_MetaData()
                     at System.Data.SqlClient.SqlCommand.FinishExecuteReader(Sq
                lDataReader ds, RunBehavior runBehavior, String 
                resetOptionsString, Boolean isInternal, Boolean 
                forDescribeParameterEncryption)
                     at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(Co
                mmandBehavior cmdBehavior, RunBehavior runBehavior, Boolean 
                returnStream, Boolean async, Int32 timeout, Task& task, 
                Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean 
                describeParameterEncryptionRequest)
                     at System.Data.SqlClient.SqlCommand.RunExecuteReader(Comma
                ndBehavior cmdBehavior, RunBehavior runBehavior, Boolean 
                returnStream, String method, TaskCompletionSource`1 
                completion, Int32 timeout, Task& task, Boolean& usedCache, 
                Boolean asyncWrite, Boolean inRetry)
                     at System.Data.SqlClient.SqlCommand.RunExecuteReader(Comma
                ndBehavior cmdBehavior, RunBehavior runBehavior, Boolean 
                returnStream, String method)
                     at 
                System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior 
                behavior, String method)
                     at 
                System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior 
                behavior)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlCommand.<ExecuteRe
                ader>b__57_0()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.<>c__Di
                splayClass104_0`1.<ExecuteFunction>b__0()
                HResult: -2146232060
                </ii>

TimeGenerated : 2/12/2018 5:58:05 PM
EntryType     : Error
Message       : Server instance: NAV
                Tenant ID: <ii>default</ii>
                <ii>Session type: ManagementClient
                Session ID: 8
                User: User Manager\ContainerAdministrator
                Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavSqlException
                ErrorNumber: 208
                SuppressMessage: False
                DiagnosticsSuppress: False
                SuppressExceptionCreatedEvent: False
                FatalityScope: None
                Message:
                  <ii>The following SQL error was unexpected:
                  Invalid object name 'master.dbo.$ndo$srvproperty'.
                  SQL statement:
                  SELECT license FROM [master].[dbo].[$ndo$srvproperty]
                  StackTrace:
                     at System.Environment.GetStackTrace(Exception e, Boolean 
                needFileInfo)
                     at System.Environment.get_StackTrace()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.ThrowNa
                vSqlException(SqlExceptionAdapter exceptionAdapter, String 
                commandText, Boolean isLastExceptionARollbackCause, Boolean 
                logExceptions)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.<>c__Di
                splayClass104_0`1.<ExecuteFunction>b__0()
                     at Microsoft.Dynamics.Nav.Types.NavThread.RunExternalActio
                n[T](Func`1 action)
                     at Microsoft.Dynamics.Nav.Diagnostic.NavDiagnostics.SendTr
                aceTagOnThreshold[T](String tag, Category category, Verbosity 
                verbosity, Int32 threshold, Func`1 action, String message, 
                Object[] parameters)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.Execute
                FunctionWithTrace[T](EventTask task, Func`1 function, String 
                commandText)
                     at 
                Microsoft.Dynamics.Nav.Runtime.NavSqlCommand.ExecuteReader()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseProperties
                .ReadServerPropertiesIfNotAlreadyRead()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlDatabaseProperties
                .CheckLicenseExists()
                     at Microsoft.Dynamics.Nav.Runtime.NavDatabaseSecurityAndLi
                cense.get_License()
                     at Microsoft.Dynamics.Nav.Runtime.NavSession.SetAndValidat
                eLicense(Byte[] licenseToUse)
                     at Microsoft.Dynamics.Nav.Runtime.NavSession.Open(Boolean 
                useUserPersonalization, Byte[] licenseToUse, Boolean 
                allowAppsDisabledMode)
                     at Microsoft.Dynamics.Nav.Service.NSAdminService.Microsoft
                .Dynamics.Nav.Types.IAdminService.OpenAdminConnection(Connectio
                nRequest connectionRequest)
                     at SyncInvokeOpenAdminConnection(Object , Object[] , 
                Object[] )
                     at 
                System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object 
                instance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                ErrorMappingCombinator(ServiceOperation innerOperation, 
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[] 
                inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase 
                serviceInstance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                PushPopCombinator(ServiceOperation innerOperation, 
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[] 
                inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase 
                serviceInstance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                CreateNewSessionCombinator(ServiceOperation innerOperation, 
                NSServiceBase serviceInstance, Boolean requireNavUser, 
                Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                CreateNewAdminSessionCombinator(ServiceOperation 
                innerOperation, NSServiceBase serviceInstance, MethodBase 
                syncMethod, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase 
                serviceInstance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass10_0.<PerformanceCounterCombinator>b__0()
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                PerformanceCounterCombinator(ServiceOperation innerOperation, 
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[] 
                inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase 
                serviceInstance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                InitClientTelemetryIdsCombinator(ServiceOperation 
                innerOperation, NSServiceBase serviceInstance, MethodBase 
                syncMethod, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase 
                serviceInstance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                TlsClearCombinator(ServiceOperation innerOperation, 
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[] 
                inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                <>c__DisplayClass25_0.<Combine>b__1(NSServiceBase 
                serviceInstance, Object[] inputs, Object[]& outputs)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                Invoke(Object instance, Object[] inputs, Object[]& outputs)
                     at System.ServiceModel.Dispatcher.DispatchOperationRuntime
                .InvokeBegin(MessageRpc& rpc)
                     at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime
                .ProcessMessage5(MessageRpc& rpc)
                     at 
                System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean 
                isOperationContextSet)
                     at System.ServiceModel.Dispatcher.MessageRpc.Wrapper.Resum
                e(Boolean& alreadyResumedNoLock)
                     at System.ServiceModel.Dispatcher.ThreadBehavior.ResumePro
                cessing(IResumeMessageRpc resume)
                     at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContex
                t.<>c__DisplayClass1_0.<ClearThreadLocalStorageDelegate>b__0(Ob
                ject state)
                     at 
                System.Threading.ExecutionContext.RunInternal(ExecutionContext 
                executionContext, ContextCallback callback, Object state, 
                Boolean preserveSyncCtx)
                     at System.Threading.ExecutionContext.Run(ExecutionContext 
                executionContext, ContextCallback callback, Object state, 
                Boolean preserveSyncCtx)
                     at System.Threading.QueueUserWorkItemCallback.System.Threa
                ding.IThreadPoolWorkItem.ExecuteWorkItem()
                     at System.Threading.ThreadPoolWorkQueue.Dispatch()</ii>
                HResult: -2146233088
                ----------------------------------
                Type: System.Data.SqlClient.SqlException
                ClientConnectionId: 0a665aa2-2f62-4df9-a496-cdf7f5755d1d
                Class: 16
                LineNumber: 1
                Number: 208
                Server: LOCALHOST\SQLEXPRESS
                State: 1
                Source: .Net SqlClient Data Provider
                ErrorCode: -2146232060
                Message: <ii>Invalid object name 
                'master.dbo.$ndo$srvproperty'.</ii>
                StackTrace:
                     at 
                System.Data.SqlClient.SqlConnection.OnError(SqlException 
                exception, Boolean breakConnection, Action`1 wrapCloseInAction)
                     at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarnin
                g(TdsParserStateObject stateObj, Boolean 
                callerHasConnectionLock, Boolean asyncClose)
                     at System.Data.SqlClient.TdsParser.TryRun(RunBehavior 
                runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, 
                BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject 
                stateObj, Boolean& dataReady)
                     at 
                System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
                     at System.Data.SqlClient.SqlDataReader.get_MetaData()
                     at System.Data.SqlClient.SqlCommand.FinishExecuteReader(Sq
                lDataReader ds, RunBehavior runBehavior, String 
                resetOptionsString, Boolean isInternal, Boolean 
                forDescribeParameterEncryption)
                     at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(Co
                mmandBehavior cmdBehavior, RunBehavior runBehavior, Boolean 
                returnStream, Boolean async, Int32 timeout, Task& task, 
                Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean 
                describeParameterEncryptionRequest)
                     at System.Data.SqlClient.SqlCommand.RunExecuteReader(Comma
                ndBehavior cmdBehavior, RunBehavior runBehavior, Boolean 
                returnStream, String method, TaskCompletionSource`1 
                completion, Int32 timeout, Task& task, Boolean& usedCache, 
                Boolean asyncWrite, Boolean inRetry)
                     at System.Data.SqlClient.SqlCommand.RunExecuteReader(Comma
                ndBehavior cmdBehavior, RunBehavior runBehavior, Boolean 
                returnStream, String method)
                     at 
                System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior 
                behavior, String method)
                     at 
                System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior 
                behavior)
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlCommand.<ExecuteRe
                ader>b__57_0()
                     at Microsoft.Dynamics.Nav.Runtime.NavSqlConnection.<>c__Di
                splayClass104_0`1.<ExecuteFunction>b__0()
                HResult: -2146232060
                </ii>

**Comment by freddydk** [comment]
I was looking for the PowerShell stacktrace, but I think I know where it is.
In the end - the problem is in the .bak file and I probably cannot help unless I can download a bak file which is failing - alle the bak files I have tried just works and you are specifying the parameters correctly.

**Comment by bachii1010** [comment]
Hi freddy,

I have searched some forums and indeed it is a licence object and if we make _save in the database_ true in alter database then i think it will be resolved.
am i correct please suggest.
Reg. giving you a backup i will discuss with my company and let you know.

**Comment by Koubek** [comment]
Save in the database before the backup is taken will resolve this. I think I have faced the same problems in one demo I was doing for somebody not using gMSA. I was in rush and needed to solve it quickly so I think I changed the configuration on the source DB and backed it again and then restored... I would say I was OK then.

**Comment by bachii1010** [comment]
As suggested by Koubek it worked when we change the setting and take the backup.

But is there any way without doing this change

**Comment by Koubek** [comment]
AFAIK, this is being done (automatically) in the case you create a new database and do not specify "Save license in Database" option. 

Maybe calling something like `finsql.exe command=createdatabase, servername=localhost\sqlexpress, database="initDb"` before the system fails could help but I haven't tested it and maybe the concept is totally wrong. It's just an idea and I suppose @freddydk will bring us a more sophisticated solution.

**Comment by freddydk** [comment]
I got some time to do a repro this morning and it is actually supported using my first suggestion - adding a license file parameter. The problem is, that I wrote -e license=flffile - the right syntax is -e licensefile=flffile - you should see these lines in the output:

Starting Local SQL Server
Starting Internet Information Server
**Using Database .bak file 'C:\temp\my.bak'**
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 684E105681A0C9E3C49E148BD4E6FD9D0CBABC02
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
**Using license file 'c:\temp\new.flf'
Import NAV License**
...

I was able to repro, and I was able to fix the issue by adding a licensefile.
