### ISSUE TITLE
getnav2 web client not working

### ISSUE THREAD

**Issue by gunnargestsson** [Microsoft/nav-docker#159]
I am not getting 

https://nav2018dev.westeurope.cloudapp.azure.com/nav

to work.  The NAV client works fine and trying the web client with the same user/password fails.

![technicalissues](https://user-images.githubusercontent.com/23558797/36064859-891dc558-0e89-11e8-9c77-adf008f63a35.PNG)

what do you need to know?

**Comment by freddydk** [comment]
Everything seems to be correct.
if you can email me username and password for the VM, then I will have a look.

**Comment by freddydk** [comment]
Did you ever get this to work?
Have you seen the error later?

**Comment by gunnargestsson** [comment]
I have not tried (since I did not need the web client for this project) and have not built another machine since.

**Comment by freddydk** [comment]
Ok, haven't seen this before or after, will close this one.
Please re-open or open another one if you run into issues again.
