### ISSUE TITLE
Creating a docker images with specifc database and image accessible from outiside

### ISSUE THREAD

**Issue by bachii1010** [Microsoft/nav-docker#161]
Hi,

We have created a image in our own pc with name tradeplus2018.00 using the below commands

Docker run -e bakfile = path...
Docker stop
Docker commit containername imagename

And when i run the command docker images it is showing there. 
Now i tried to pull the image from other PC where docker is installed i am getting the below error:

![image](https://user-images.githubusercontent.com/26792519/36198731-6144cfb0-119d-11e8-8a4c-54590922999a.png)

We want to know how to create a image where it can be pulled from anywhere where docker is installed similar to standard NAV images.

Please suggest?

Thanks & Regards
Varun Reddy

**Comment by freddydk** [comment]
As Tobias wrote, you should use your own registry with some level of security. We do not want NAV images to be re-published to the public docker hub, as this makes it impossible for us to update this images.
You can create a container registry on azure using: https://azure.microsoft.com/en-us/services/container-registry/
Also remember, that every time you create your own image based on a NAV image, you head down a blind alley. Your image will become stale and will not have latest updates done to the NAV images without you are rebuilding the image.
A lot of work went into the NAV image to ensure that you can dynamically run and parameterize the image for partners to be able to use them.
