### ISSUE TITLE
Enable strong crypto standards

### ISSUE THREAD

**Issue by tfenster** [Microsoft/nav-docker#162]
If you use the -e folders="..." feature with a https://github.com address, this fails since today because (I think) github has [removed weak cypher support](https://github.com/blog/2507-weak-cryptographic-standards-removed). I can repro this on a regular Windows machine (not inside a Container) where e.g. the following also fails:

```
PS H:\> Invoke-WebRequest https://github.com/tfenster/nav-docker-samples/archive/grant-user-access.zip
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ Invoke-WebRequest https://github.com/tfenster/nav-docker-samples/arch ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommant
```

I can fix this by requesting Tls12 as follows
```
PS H:\> [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
PS H:\> Invoke-WebRequest https://github.com/tfenster/nav-docker-samples/archive/grant-user-access.zip

StatusCode        : 200
StatusDescription : OK
Content           : {80, 75, 3, 4...}
RawContent        : HTTP/1.1 200 OK
                    Access-Control-Allow-Origin: https://render.githubusercontent.com
                    Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
                    Strict-Transport-Security: max-age=...
Headers           : {[Access-Control-Allow-Origin, https://render.githubusercontent.com], [Content-Security-Policy,
                    default-src 'none'; style-src 'unsafe-inline'; sandbox], [Strict-Transport-Security,
                    max-age=31536000], [Vary, Authorization,Accept-Encoding]...}
RawContentLength  : 3312
```

However I can't do this on the NAV containers without changing the image as the download happens so early that no override can be triggered before. Therefore I think the image should be changed to also request Tls12 (maybe with the same SecurityProtocol call as above in start.ps1?). Please let me know if you agree, then I can create a PR

**Comment by freddydk** [comment]
That would restrict us to only support 1.2

I think a better fix would be [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls -bor [System.Net.SecurityProtocolType]::Ssl3 -bor [System.Net.SecurityProtocolType]::Tls12 - very early...

I wasn't paying attention to this change, so this will actually cause multiple scenarios to fail.

**Comment by freddydk** [comment]
Actually, this would be the better fix:

[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12

**Comment by freddydk** [comment]
Images have been rebuild with generic layer version 0.0.5.2.
Use docker pull and docker inspect to validate that you have the right version and tls12 should be supported.
