### ISSUE TITLE
URI Error on ClickOnce start with NAV2018 and ClickOnce

### ISSUE THREAD

**Issue by twityde** [Microsoft/nav-docker#164]
Commit [175c016f5ee6db2f74cb0946fab13f45a7f95366](https://github.com/Microsoft/nav-docker/commit/175c016f5ee6db2f74cb0946fab13f45a7f95366) sets a wrong acsUri in the configuration file, if NavUserPassword is enabled.

**Comment by freddydk** [comment]
Correct, will be fixed when images are rebuilt over the weekend.

**Comment by freddydk** [comment]
Images have been rebuild with generic layer version 0.0.5.2.
Use docker pull and docker inspect to validate that you have the right version and clickonce should work again.
