### ISSUE TITLE
NAV 2017 RTM clickonce issue

### ISSUE THREAD

**Issue by pzentner** [Microsoft/nav-docker#165]
We had the same issue at #119 already. I am getting the same error using IE and Edge trying to install the clickonce client. What's interesting is that I am getting a warning that the container is 85 days old and that i should pull a new one. Well, it was just pulled today, so I am assuming that you didn't have a chance to update this container in a while. 

Tried it also with the latest 2017 build and i am getting the same error.

Could it be that - whatever you did to 2016 also needs to be done to 2017? I might be able to look into it a bit more tonight so that I can narrow it down.

**Comment by freddydk** [comment]
Clickonce broke for 2016, 2017 and 2018 builds with the AAD authentication from last weekend.
Will be fixed this weekend.

**Comment by freddydk** [comment]
Images have been rebuild with generic layer version 0.0.5.2.
Use docker pull and docker inspect to validate that you have the right version and clickonce should work again.
