### ISSUE TITLE
Cannot connect NAV Container

### ISSUE THREAD

**Issue by jaloag** [Microsoft/nav-docker#166]
Hi. I'm trying to run the last NAV image (Windows 10):

docker run -e accept_eula=Y -e usessl=N -m 3G microsoft/dynamics-nav

---------------------------------------------------
Initializing...
Starting Container
Hostname is 98ae0a051449
PublicDnsName is 98ae0a051449
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint C476BF279D3754C749C9A6F8780CCD2FB7485961
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore NAV Web Server Instance
Creating http download site
Creating Windows user admin
Enabling SA
Creating NAV user
Container IP Address: 172.25.9.202
Container Hostname  : 98ae0a051449
Container Dns Name  : 98ae0a051449
Web Client          : http://98ae0a051449/NAV/
NAV Admin Username  : admin
NAV Admin Password  : Tine2274
Dev. Server         : http://98ae0a051449
Dev. ServerInstance : NAV

Files:
http://98ae0a051449:8080/al-0.12.16641.vsix

Initialization took 42 seconds
Ready for connections!
---------------------------------------------------

 1.- Then I try to open webclient --> "ERR_NAME_NOT_RESOLVED"

2.- Then I try to ping:

---------------------------------------------------
ping 172.25.9.202

Haciendo ping a 172.25.9.202 con 32 bytes de datos:
Tiempo de espera agotado para esta solicitud.
Tiempo de espera agotado para esta solicitud.
Tiempo de espera agotado para esta solicitud.
Tiempo de espera agotado para esta solicitud.

Estadísticas de ping para 172.25.9.202:
    Paquetes: enviados = 4, recibidos = 0, perdidos = 4
    (100% perdidos),
---------------------------------------------------

3.- If I make a docker inspect:

---------------------------------------------------
PS C:\WINDOWS\system32> docker inspect 98ae0a051449
[
    {
        "Id": "98ae0a051449f905cf6745227f9740804c839609fe35e5748f403573387d0e97",
        "Created": "2018-02-24T08:26:21.6999043Z",
        "Path": "powershell",
        "Args": [
            "-Command",
            "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
            ".\\Run\\start.ps1"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1984,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-02-24T08:26:35.3407892Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2018-02-24T09:35:25.4834958+01:00",
                        "End": "2018-02-24T09:35:25.937038+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-02-24T09:35:55.9581548+01:00",
                        "End": "2018-02-24T09:35:56.4437403+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-02-24T09:36:26.4628649+01:00",
                        "End": "2018-02-24T09:36:26.8877114+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-02-24T09:36:56.9081353+01:00",
                        "End": "2018-02-24T09:36:57.338671+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-02-24T09:37:27.358236+01:00",
                        "End": "2018-02-24T09:37:27.8123603+01:00",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:cbe32331c68b29178d9109199676f088cc7db6eb9dfde55b7e6703b94036ede0",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\Docker\\containers\\98ae0a051449f905cf6745227f9740804c839609fe35e5748f403573387d0e97\\98ae0a051449f905cf6745227f9740804c839609fe35e5748f403573387d0e97-json.log",
        "Name": "/trusting_volhard",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                57,
                117
            ],
            "Isolation": "hyperv",
            "CpuShares": 0,
            "Memory": 3221225472,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\windowsfilter\\98ae0a051449f905cf6745227f9740804c839609fe35e5748f403573387d0e97"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "98ae0a051449",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "usessl=N",
                "accept_eula=Y",
                "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-0.12.16641.vsix",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/b4d6285a-915c-4a03-b951-c2fc5af096ba",
                "DatabaseServer=localhost",
                "DatabaseInstance=SQLEXPRESS",
                "DatabaseName=CRONUS"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "microsoft/dynamics-nav",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "w1",
                "created": "201802160301",
                "cu": "cu2",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=862604",
                "maintainer": "Dynamics SMB",
                "nav": "2018",
                "osversion": "10.0.14393.1770",
                "tag": "0.0.5.0",
                "version": "11.0.20348.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "cc2a9cb6de96535ec382e416cdfccac8dd5be6c906801a5961b56b5701b8a1e3",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "80/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "cc2a9cb6de96535ec382e416cdfccac8dd5be6c906801a5961b56b5701b8a1e3",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "06a063652a3c3da2a7089e4d210092228d5a5ca6f218c054843dc665f7a7185c",
                    "EndpointID": "b7aa025c1e38756312660bcf94c17f608c769155aea21e65bcfe32805dbcccb9",
                    "Gateway": "172.25.0.1",
                    "IPAddress": "172.25.9.202",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:59:a1:c9",
                    "DriverOpts": null
                }
            }
        }
    }
]
---------------------------------------------------

Any suggestions?? :-(

Thanks a lot. Greetings

**Comment by freddydk** [comment]
It seems like your problem is with Docker network itself - and not the NAV on Docker image.
Check out this https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/ and see if you can find something to solve the problem.

**Comment by freddydk** [comment]
Did you manage to make this work?

**Comment by jaloag** [comment]
Sorry for the delay. Yes, I've tried:

- I've disable firewall.
- I have added an entry to the hosts file.

But I cannot ping the container IP...

Thanks

**Comment by freddydk** [comment]
I will close this issue as it is unrelated to the NAV on Docker images.
If you cannot make Docker work on your Windows 10, maybe you should follow the approach that AJ uses:
https://www.kauffmann.nl/2017/12/02/running-nav-docker-containers-on-a-local-hyper-v-virtual-machine/
or you could spin up an Azure VM for development purposes using http://aka.ms/getnav

**Comment by jaloag** [comment]
Ok. Thanks Freddy. :-)

**Comment by jaloag** [comment]
Hi again.

Finally I found a solution!! 

Searching similar issues in github, I found this issue and it worked for me:

https://github.com/docker/for-win/issues/711

Thanks all.
