### ISSUE TITLE
SQL Report Builder missing in developer preview

### ISSUE THREAD

**Issue by peikba** [Microsoft/nav-docker#168]
Hi Guys,

Just tested the new report snippet in the developer preview, and that works perfectly.
Thank you for that.

However, SQL Report Builder and Visual Studio are both missing in the developers preview.
Can vi get that in there?

Secondly, is there an easier way to open the SQL Server Report Builder than right-clicking the .rdl file and then selecting Reveal in Explorer to use the open with function there?

/Peik

**Comment by Koubek** [comment]
If I am correct, the report builder and visual studio are both the client-side prerequisites. This means you need to install them locally on your machine.

**Comment by freddydk** [comment]
Koubek is right - they cannot be part of the docker image, but are you talking about pre-installing them on the http://aka.ms/navdeveloperpreview Azure VM, then I will put this on the list of things to potentially add to the ARM templates here: https://github.com/microsoft/nav-arm-templates

**Comment by srenders** [comment]
Hi Peik,

A way to run reportbuilder would be to create a task in VSCode.

For example, adding this task:
![reportbuilder](https://user-images.githubusercontent.com/17511254/36967026-e761ed88-205e-11e8-9786-5120bb50c454.jpg)

add a task: OpenWithReportBuilder.

Then you go on your file and run the task:
![runreportbuilder](https://user-images.githubusercontent.com/17511254/36967155-4042b6c6-205f-11e8-9066-38fa79395827.gif)

**Comment by peikba** [comment]
Hi Steven 

I looked into that, but I decided that it was just as easy to right-click the file name select reveal in Explorer and then double-click the file.

Thanks anyway
