### ISSUE TITLE
Question: how do I get my own custom add-ins to the container?

### ISSUE THREAD

**Issue by richardrobberse** [Microsoft/nav-docker#169]
I saw there is a script called SetupAddIns.ps1 which looks in the runpath (c:\run) for a folder called "Add-ins" but how do I get my own dll's in this folder other than overriding the entire script and doing it myself?

**Comment by freddydk** [comment]
-v c:\localfolderwithaddins:c:\run\add-ins (or something like that)

**Comment by richardrobberse** [comment]
Great, forgot about that one.
Thanks!

**Comment by Koubek** [comment]
BTW, there was a problem with the symbolic links in the initial versions of Docker but now you can perfectly use the following approach:
```PowerShell
-v "$sharedMasterFolder\$hostname\Add-ins:C:\Program Files\Microsoft Dynamics NAV\$navVersionDir\Service\Add-ins\Docker-Share"
```
Don't bother you with the variables, you can use a fixed path (we automate some enhancements so this is the reason you can see the variables there, I've just grabbed the line and pasted it here as is. 
The important thing is just to map your local folder as a non-existing subfolder in the client/service *Add-ins* folder.
This provides you a dynamic approach (you can change files in *Add-ins* folder on the host and those will be reflected in the container and vice-versa).

**Comment by richardrobberse** [comment]
Thanks @Koubek
