### ISSUE TITLE
Running Docker failing while creating HTTP download site

### ISSUE THREAD

**Issue by anwar0206** [Microsoft/nav-docker#17]
Hello,

While running the following command.
docker run -e ACCEPT_EULA=Y -e UseSSL=N navdocker.azurecr.io/dynamics-nav:2017

Getting below error.
![docker error](https://user-images.githubusercontent.com/17919266/29243515-8cbfcf6c-7f6e-11e7-8e42-0da50b6a7f94.png)

Did anyone encountered this issue or any process to resolve this.

Setting up Docker on local laptop with Windows 10 Enterprise Edition Version 10.0.15063

Regards.
Mohammed  @@Anwar Shaikh

**Comment by freddydk** [comment]
add a parameter -m 4G to your docker run if you are using Windows 10 - I will add this to the documentation.

**Comment by anwar0206** [comment]
added the parameter like this 
docker run –m 4G -e ACCEPT_EULA=Y -e UseSSL=N navdocker.azurecr.io/dynamics-nav:2017

getting below error.
![image](https://user-images.githubusercontent.com/17919266/29243757-01a7f6fa-7f75-11e7-94fe-63587ed5409c.png)

**Comment by freddydk** [comment]
You probably need to delete whatever containers you have and retry

Docker ps -a
Will show you containers

Docker rm <id> -f
Will remove

/Freddy

**Comment by anwar0206** [comment]
tried deleting all the containers, and executing the command. But getting same error.

**Comment by tfenster** [comment]
Can you run `docker info` and post the output?

**Comment by anwar0206** [comment]
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 17.06.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.902GiB
Name: Anwar
ID: J2DL:4IMC:HVU4:4HEC:MXUI:YWK4:637K:IV5D:HIRQ:DVX6:T6QW:UYME
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 43
 System Time: 2017-08-12T16:27:23.2507591-04:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by tfenster** [comment]
seems like a known issue: https://github.com/docker/for-win/issues/767. Can you retry with -m 3G?

**Comment by anwar0206** [comment]
thanks @tfenster for the information... -m 3G parameter worked....

Now the process has got stuck on
TimeGenerated : 8/12/2017 6:07:54 PM
EntryType     : Warning
Message       : Server instance: NAV
                Category: Sql
                ClientSessionId: 00000000-0000-0000-0000-000000000000
                ClientActivityId: 00000000-0000-0000-0000-000000000000
                ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
                ServerActivityId: 00000000-0000-0000-0000-000000000000
                EventTime: 08/12/2017 22:07:54
                Message <ii>Threshold Trace Tag. Execution Time = 2767
                milliseconds
                    Long Running SQL statement Task ID:8
                    </ii>
                ProcessId: 544
                Tag: 000007S
                ThreadId: 14
                CounterInformation:

Is it normal, the process takes so long.

**Comment by anwar0206** [comment]
The process is still running almost 3 hours.... but showing
TimeGenerated : 8/12/2017 7:53:24 PM
EntryType     : Warning
Message       : Server instance: NAV
                Category: Sql
                ClientSessionId: 00000000-0000-0000-0000-000000000000
                ClientActivityId: 00000000-0000-0000-0000-000000000000
                ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
                ServerActivityId: 00000000-0000-0000-0000-000000000000
                EventTime: 08/12/2017 23:53:24
                Message <ii>Threshold Trace Tag. Execution Time = 2113
                milliseconds
                    Long Running SQL statement Task ID:9
                    </ii>
                ProcessId: 544
                Tag: 000007S
                ThreadId: 19
                CounterInformation:

**Comment by freddydk** [comment]
The Container main loop show all event log entries (Warnings and errors) by NAV and you might see some of these. The Long Running SQL statement will dump any SQL statement taking more time than a certain threshold.
