### ISSUE TITLE
How to run Docker on Windows 10 Pro on Azure ?

### ISSUE THREAD

**Issue by dkatson** [Microsoft/nav-docker#170]
Hi Freddy, 
I tried to create new Azure VM from Windows 10 Pro 1709 image.
Then I installed Docker, changed it to Windows containers mode.
Docker started successfully. 
Docker ps, and Docker images works.

But if i try to run "Docker run hello-world" i get error : No hypervisor is present on this system
I assume this is nested virtualisation problem. However i don't understand how to turn it on on azure vm.
Do you have idea?
Thanks

**Comment by Koubek** [comment]
@dkatson Maybe you could try the following links:
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/nested-virtualization
https://azure.microsoft.com/en-us/blog/nested-virtualization-in-azure/

Be aware that you need to pick a correct VM size to be allowed to enable the nested virtualization mode and I am not sure if this would work for Win10 OS.

Anyway, I really do not understand very well what is actually your point to do so... ;)

**Comment by dkatson** [comment]
Hi @Koubek , thanks for suggestion.
I saw this, and will try now with Dv3 vm size (with Dv2 this failed).
I'm testing IoT Edge with NAV, so Windows 10 Pro 1709 is the only Windows with UI interface which support it

**Comment by Koubek** [comment]
@dkatson OK. Please, just to be able to classify better the issues you should probably register this kind of questions in a different place (as this one actually has nothing to do with NAV-on-Docker).

**Comment by Koubek** [comment]
@dkatson If you want to discuss whatever docker-related, you can reach me using the e-mail address on my github profile. I am open to help anyone using this private channel. Maybe we can find a suitable solution together.

**Comment by dkatson** [comment]
@Koubek thank you! I will, just here is the nearest docker issue topic for such NAV person as me:) And you and Freddy are those on whome I can rely. 
Next time I will write you directly. 
Sorry for inconvenience

**Comment by dkatson** [comment]
By the way, Docker on Dv3 and Ev3 Azure VM works!

**Comment by freddydk** [comment]
Thanks for the info Dmitry

**Comment by shasdas** [comment]
Hi @dkatson ,

I'm facing similar issue on running docker while working on IoT Edge. Here is my VM spect in the screen shot below. Is similar kind of spec of the VM work for you?  Thanks!
![image](https://user-images.githubusercontent.com/16579000/39828134-9ebfa774-537f-11e8-9cbe-f66655bcb28f.png)

**Comment by glenncarr** [comment]
After some initial failures trying to use the Windows Pro image, was able to use it with Windows 10 Enterprise N with D2s v3.  Thanks for the tips @shasdas and @dkatson .
