### ISSUE TITLE
You are trying to run a container which is more than 90 days old.

### ISSUE THREAD

**Issue by fvet** [Microsoft/nav-docker#171]
I can no longer start my container...

**Logs**
Restarting Container
PublicDnsName unchanged
Hostname is xxx
PublicDnsName is xxx
You are trying to run a container which is more than 90 days old.
Microsoft recommends that you always run the latest version of our containers.
Set the environment variable ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.
at <ScriptBlock>, C:\Run\navstart.ps1: line 52
at <ScriptBlock>, C:\Run\start.ps1: line 38
at <ScriptBlock>, <No file>: line 1

**Docker inspect**
ACCEPT_OUTDATED is no part of my env variables

**Trying to update env variable via**
>docker exec xxx -e ACCEPT_OUTDATED=Y

**Error***
container 3e6ac9659247f04d6c061245338c793ba1b90b3e797c9c681490dfce5dda5648 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"ApplicationName":"","CommandLine":"-e ACCEPT_OUTDATED=Y",...

**Comment by freddydk** [comment]
The intention with Accept_outdated was actually that it should be checked when starting the container and not when restarting.
We really do not want people to be running with old containers.
If you started the container using navcontainerhelper, then the c:\run\my folder is shared with the host and you can use docker cp to copy navstart.ps1 to that - and then remove the check.
Else you need to use docker pull and start a new container.
If you have something in the container you need - you can use docker cp to copy it out.

**Comment by fvet** [comment]
The container created contains a database that we don't want to lose.

I managed to export the navstart.ps1 from another container, so I can use this file to import in the current container. However, since the container can't be started, it seems to be blocked during startup, so files might be locked as well ...

docker cp c:/myfolder/navstart.ps1 CONTAINERNAME:/run/navstart.ps1 (or even another destination /run/my folder/...)

Error response from daemon: hcsshim::ActivateLayer failed in Win32: The process cannot access the file because it is being used by another process. (0x20) id=3e6ac9659247f04d6c061245338c793ba1b90b3e797c9c681490dfce5dda5648 flavour=1

How can I get access to the contents (at least the database) of my container when I'm not able to start it?

PS: Will there be an update not to block the restarting of the container once created?

**Comment by fvet** [comment]
Update: I stopped the container and ran the following without error
docker cp c:/myfolder/navstart.ps1 vives2017:/run/my/navstart.ps1

Although now I get following error when starting the container ...

Error response from daemon: container 3e6ac9659247f04d6c061245338c793ba1b90b3e797c9c681490dfce5dda5648 encountered an error during CreateContainer: failure in a Windows system call: The directory is not empty. (0x91) extra info: {"SystemType":"Container","Name":"3e6ac9659247f04d6c061245338c793ba1b90b3e797c9c681490dfce5dda5648","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{c453529a-f183-11e7-98ba-c4e38821c171}","IgnoreFlushesDuringBoot":false,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\3e6ac9659247f04d6c061245338c793ba1b90b3e797c9c681490dfce5dda5648","Layers":[{"ID":"61a472f6-5fc5-5f2d-9b40-e7cbb8f51a5f","Path":"C:\\ProgramData\\docker\\windowsfilter\\3ac9f5b0ce3ed43ae9334fb86993912b38b4212aec6b09e58710b5e606f5e086"},{"ID":"2b10f442-62a4-5ed1-ad9c-885ae5c27a8e","Path":"C:\\ProgramData\\docker\\windowsfilter\\15d0a5d914332582432c241699a862ab34f18076642e16ed89c2b47a6b2b192e"},{"ID":"f4a0b4bc-dc2b-5723-9cc0-2d2be8527886","Path":"C:\\ProgramData\\docker\\windowsfilter\\f94883d92fa4c6719ec83c5fe01884fd0ec59c1eb4c2a5a8159a510a9444d88c"},{"ID":"e1a72cb7-e980-5fcd-9de8-2b4d479c0829","Path":"C:\\ProgramData\\docker\\windowsfilter\\28d3faef96b63fff940d3b06abb28c6d4132780fb95de9f81a64fa84ca19386c"},{"ID":"746fe5fe-cceb-5058-b729-320ea01cb8f1","Path":"C:\\ProgramData\\docker\\windowsfilter\\a3e8453b2c97d02e53124ed1206e40474ed5e1cbaffcf8057fe9b6373d82d636"},{"ID":"4e750792-75db-5281-9dd1-cb42ee7574ad","Path":"C:\\ProgramData\\docker\\windowsfilter\\d8a2a5d4c668f612ba41e2b55e5c488b3dd36b3b31b800816575f71abdb8ed40"},{"ID":"a4ff1c87-17ba-5185-8ca4-6dd26bbfd4a1","Path":"C:\\ProgramData\\docker\\windowsfilter\\38d043ed204b6e4466a44246c1bf0dc96760873fa755066d73a1ea028e26b565"},{"ID":"cfa013a7-3e78-5810-b52f-4119cbbc4852","Path":"C:\\ProgramData\\docker\\windowsfilter\\a6a162065e3d6abf96b6f75fae02ceebd33e1bc43e11a05a6111f94f9c65e13d"},{"ID":"9e593dc2-7609-5d26-974a-8a14307dbef4","Path":"C:\\ProgramData\\docker\\windowsfilter\\0f76d4623e010681d9d5cee040d087242437864ecefda7abaafc076139d72766"},{"ID":"239a6deb-e0a9-5ef6-8890-a6e805ea8569","Path":"C:\\ProgramData\\docker\\windowsfilter\\db00d4ab89fb65867b15c7380d0c06ca9ccba128443986deb4412581f3786a3c"},{"ID":"3750d03d-ac30-5f83-9972-7f46d64ff54e","Path":"C:\\ProgramData\\docker\\windowsfilter\\93f42a6d90f9567ba455b1319f6508cd2fe8c27e6e1c0eb3d816194ab6c027b5"},{"ID":"092415ec-6981-561b-af74-06c608c41d52","Path":"C:\\ProgramData\\docker\\windowsfilter\\fcf2e91cc1e243addbc6cecccde51e696d22b5127c87beb396b5e6130e3c85df"},{"ID":"83cd030d-218b-502b-b890-792820ae0555","Path":"C:\\ProgramData\\docker\\windowsfilter\\76b6adbd6b1562dcb65f6823acf8013d3c90912f646b5a83d6f7783d3d681777"},{"ID":"90a074c0-7dff-5414-b759-decfdf834314","Path":"C:\\ProgramData\\docker\\windowsfilter\\18e3fbaa7252c6ebc301fc48aa5b7b63c16f9d02e63c88bfa83f0ea4f62aca36"},{"ID":"4b40b9f4-dec3-5031-9f8f-c6df8ad02d3f","Path":"C:\\ProgramData\\docker\\windowsfilter\\33bcad49e936c34b5ea1c12fddefefe6ce144ec79aa552777c25cde24ec1fbdc"},{"ID":"03e188c7-89d7-5b96-b994-5c1609a68191","Path":"C:\\ProgramData\\docker\\windowsfilter\\8f28c05713b0446f5c82242bae0b0d55c40a50260c1b9bee442204904e8fbaca"},{"ID":"d65ed84b-ade9-5953-b17c-1e82a0124d94","Path":"C:\\ProgramData\\docker\\windowsfilter\\60d8a9c49510e157c6947d2ab55188836977df9babecc1d9b265592c6ff6b11e"},{"ID":"cd14d8ef-9b9b-59f3-9089-5494d88da5ff","Path":"C:\\ProgramData\\docker\\windowsfilter\\4801dbbb258c2b27f21de946129219e442fd9f75df76fa96e1b798c0966c2da4"},{"ID":"4e9cb09b-8cf5-58ec-9d65-31c11f14f3af","Path":"C:\\ProgramData\\docker\\windowsfilter\\ee6d4d626637f2b1c2265b174ef09b9ba87111b3ad36ff712bf65f937aab57ca"},{"ID":"f8a4d4fc-1fb2-5424-91ca-e16227b84cb6","Path":"C:\\ProgramData\\docker\\windowsfilter\\41faef6c90ffc3d6ad981a450aadb9d8ca8306a700055a94b2b42ede23d0da5c"},{"ID":"21a1885c-ad71-5298-be2f-10e074ae37a2","Path":"C:\\ProgramData\\docker\\windowsfilter\\c788d518b380fb21429c1d16bb25cf7c88664217e2aea1af9e8bc40c2dea4d30"},{"ID":"5cc1f2d7-2f93-500d-b819-d949b5b01f67","Path":"C:\\ProgramData\\docker\\windowsfilter\\17bd31fcb92cf5aa690c6520e1961b44ea053b7ed0fd61059bbc3863848789bb"}],"MemoryMaximumInMB":3072,"HostName":"xxx2017","MappedDirectories":[{"HostPath":"c:\\windows\\system32\\drivers\\etc","ContainerPath":"c:\\driversetc","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0},{"HostPath":"c:\\programdata\\navcontainerhelper\\extensions\\xxx2017\\program files","ContainerPath":"c:\\navpfiles","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0},{"HostPath":"c:\\programdata\\navcontainerhelper\\extensions\\xxx2017\\my","ContainerPath":"c:\\run\\my","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0},{"HostPath":"c:\\programdata\\navcontainerhelper","ContainerPath":"c:\\programdata\\navcontainerhelper","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0}],"HvPartition":false,"EndpointList":["5e088979-c296-4621-a402-24cb9a60aeb9"],"Servicing":false,"AllowUnqualifiedDNSQuery":false}
Error: failed to start containers: xxx2017

**Comment by freddydk** [comment]
I asked wether how you started the container in order to understand if you had a shared my folder.
Based on this, I don’t think you had - and you might have ruined the file system now.
If you didn’t have a my folder you should just override the file in run with docker cp.
Now try to copy mdf and ldf files out with docker cp then you can copy them into another container.


Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fvet** [comment]
I created the container using the standard 'New-CSideDevContainer' commandlet, so I'm ot sure if I actually had a 'my' folder.

When I'm using the docker cp command (when the container is not started, since it can't) to copy the C:\Database\CronusBE mdf and ldf files, I seem to get the standard Cronus files (from the image?), not containing any of the modified objects / data. 

I'm quit blocked in getting my databases back currently :(

**Comment by freddydk** [comment]
If you managed to get the cronusbe files out - then you have the right files. If they dont contain the objects, then the objects wasn't in that container.
(if you indeed are running BE)
docker inspect will tell you about the shared folders.

**Comment by freddydk** [comment]
Next rebuild of images will not check for container age when restarting.
It will disallow you to start new containers which are outdated.
Note, that the containers start writing out warnings after 60 days.
