### ISSUE TITLE
Headline extension is missing in Dynamics365BC images

### ISSUE THREAD

**Issue by dkatson** [Microsoft/nav-docker#173]
Hi team, if you run container from fresh Msdyn365bc images there are only basic greeting headlines. I was told that that there should be headlines extension installed. Can you check and
update Docker conteiner with this headlines extension.

**Comment by freddydk** [comment]
In the container, in c:\extensions, you will find the source for all extensions.
Is that what you are asking for?

**Comment by dkatson** [comment]
Yes! Thank you Freddy.
