### ISSUE TITLE
docker pull same image multiple times always extracting

### ISSUE THREAD

**Issue by PleachiM** [Microsoft/nav-docker#174]
I have a script which is pulling all images from cu1 to cu40. The script does what it should do but when I start this script multiple times (4 times since yesterday) it keeps extracting already pulled images. 
I can't see any point why. sometimes it's extracing cu4 sometimes cu7 ... so not always the same. 

Any idea?

**Comment by freddydk** [comment]
Maybe because I am rebuilding all images as we speak...

**Comment by PleachiM** [comment]
:) 👍

**Comment by PleachiM** [comment]
maybe I should not work on my pull script when it's your rebuild day ;) 

![image](https://user-images.githubusercontent.com/34088506/37874649-2bf298f6-3033-11e8-92c5-57abac8e51a6.png)

**Comment by freddydk** [comment]
Sorry for the inconvenience.
I am curious as to why you would pull all - and not just pull when you need?

**Comment by PleachiM** [comment]
That is just a nice to have for our new dev. concept.
