### ISSUE TITLE
Cannot retrieve the requested user

### ISSUE THREAD

**Issue by elweilando** [Microsoft/nav-docker#175]
Issues raises after downloading the new image.
Container has an external database with SQL Username.
Image is microsoft/dynamics-nav:2018-cu1-de 
Occurs in several images

I haven't access to windows client because my user needs to be an valid user.

If I try to add an user in container powershell I get

`
The user name must be unique.
    + CategoryInfo          : NotSpecified: (0:Int32) [New-NAVServerUser], FaultException`1
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV,Microsoft.Dynamics.Nav.Management.
   r
    + PSComputerName        : e67aa24f9fe7a369ac9ee97fda180d2f5cfe17c5924f2b2ae1fb288722f17e30

Cannot retrieve the requested user.
    + CategoryInfo          : NotSpecified: (0:Int32) [New-NAVServerUserPermissionSet], FaultEx
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV,Microsoft.Dynamics.Nav.Management.
   rPermissionSet
    + PSComputerName        : e67aa24f9fe7a369ac9ee97fda180d2f5cfe17c5924f2b2ae1fb288722f17e30
`

NAV-GetServerUser lists the user, but I haven't access to windows client because my user needs to be an valid user.

If I run 

`
New-NavServerUserPermissionSet -ServerInstance NAV -WindowsAccount navadmin -PermissionSetID SUPER
` 

I get 

`
New-NavServerUserPermissionSet : Cannot retrieve the requested user.
At line:1 char:1
+ New-NavServerUserPermissionSet -ServerInstance NAV -WindowsAccount na ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (0:Int32) [New-NAVServerUserPermissionSet], FaultException`1
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV,Microsoft.Dynamics.Nav.Management.Cmdlets.NewNavServerUse
   rPermissionSet
`

"wmic useraccount" gives me the same SID like "get-navserveruser"

remove-navserveruser -serverinstance NAV -sid (sid from wmic useraccount)

trows the same error 

Remove-NAVServerUser : Cannot retrieve the requested user.
At line:1 char:1
+ Remove-NAVServerUser -ServerInstance nav -sid S-1-5-21-3548567813-265 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (0:Int32) [Remove-NAVServerUser], FaultException`1
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$nav,Microsoft.Dynamics.Nav.Management.Cmdlets.RemoveNavServerUser

**Comment by elweilando** [comment]
Docker Image without configuration of a database has no problems

**Comment by freddydk** [comment]
Did this ever work? (you wrote after downloading the new image)
It looks like you are using Windows Authentication. The container isn't in an AD itself so my guess is that it cannot see the navadmin user.
If you use username/password auth - my guess is that it works.
Windows authentication can be used for running containers on a box for dev/test - if you are using foreign databases you probably need to configure gMSA in order to use Windows Auth.

**Comment by elweilando** [comment]
yes. it works till the images has been downloaded this morning.

"wmic useraccount" gives me the same SID like "get-navserveruser"

remove-navserveruser -serverinstance NAV -sid (sid from wmic useraccount)

trows the same error

Remove-NAVServerUser : Cannot retrieve the requested user.
At line:1 char:1

Remove-NAVServerUser -ServerInstance nav -sid S-1-5-21-3548567813-265 ...
  + CategoryInfo          : NotSpecified: (0:Int32) [Remove-NAVServerUser], FaultException`1
  + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$nav,Microsoft.Dynamics.Nav.Management.Cmdlets.RemoveNavServerUser

**Comment by elweilando** [comment]
without configuration of an external database, it works without problems

**Comment by freddydk** [comment]
What image are you running?
Where is your database located?

**Comment by freddydk** [comment]
Do you have time for a quick Skype call? If you can send me an email to freddyk at microsoft dot com then I will setup a meeting and have a look at this.

**Comment by elweilando** [comment]
I use the "microsoft/dynamics-nav:2018-cu1-de" image. 
It's also on microsoft/dynamics-nav:2017-cu5-de
Database runs on azure with username / password credentials.
Docker runs on azure virtual machine without an active directory domain.

Generic Tag 0.0.5.2
I can add the user with 
New-NavServerUserPermissionSet -ServerInstance NAV -WindowsAccount navadmin -PermissionSetID SUPER

If the user is already in database, login to navision client works


Generic Tag 0.0.5.5
I can't add the user with 
New-NavServerUserPermissionSet -ServerInstance NAV -WindowsAccount navadmin -PermissionSetID SUPER
Error is "Cannot retrieve the requested user."

If the user is already in database, login to navision client failed with no valid user in database.

I switched now to NavUserPassword Authentification and it works for me again.

**Comment by freddydk** [comment]
Was the Azure VM created by aka.ms/something?
the navadmin user is the Windows user of the VM and also the nav admin user?

**Comment by freddydk** [comment]
Very strange.
Did a docker create microsoft/dynamics-nav:generic-0.0.5.2
docker cp <id>:C:\RUN c:\temp\52
Did a docker create microsoft/dynamics-nav:generic-0.0.5.4
docker cp <id>:C:\RUN c:\temp\54
and then compared the two directories - nothing in the scripts that would explain this.
Might be cause by a new WindowsServerCore - will try to setup a repro.

**Comment by elweilando** [comment]
Azure VM was created in Azure Portal. It's a 2016 Datacenter. Docker was installed with the offical tutorial (https://docs.microsoft.com/de-de/virtualization/windowscontainers/quick-start/quick-start-windows-server)

> the navadmin user is the Windows user of the VM and also the nav admin user?
yes.

**Comment by freddydk** [comment]
Could you try to run this on the Azure VM:
http://aka.ms/debug-containerhost.ps1

**Comment by elweilando** [comment]
I sent you an e-mail with the logs.

**Comment by freddydk** [comment]
The logs didn't show any problems.
I have now setup an environment with an Azure VM and an External SQL Server using SQL Auth and I have no issues with Windows Auth nor using NavUserPassword auth.
Are you using docker run or New-NavContainer to create your container? What is the statement used?

**Comment by freddydk** [comment]
Getting back to this - assuming that this has to do with incompatibility between Host and Container - I have worked on a few other issues with that outcome (after installing updates on the host, it worked).
