### ISSUE TITLE
Initialization of container navserver failed

### ISSUE THREAD

**Issue by dkorinets** [Microsoft/nav-docker#177]
Hello,

During run SetupNavCintainer.ps1 error occurs, I believe that the issue is related to my local Win10 environment, because on Win Srv 2016 it works fine. 
Could You help me figure out the problem please?

Cannot find path 'C:\demo\http' because it does not exist.
at <ScriptBlock>, C:\Run\my\AdditionalSetup.ps1: line 3
at <ScriptBlock>, C:\Run\navstart.ps1: line 167
at <ScriptBlock>, C:\Run\start.ps1: line 102
at <ScriptBlock>, <No file>: line 1
Initialization of container navserver failed
At C:\demo\ContainerHandling\Wait-NavContainerReady.ps1:40 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...avserver failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container navserver failed

**Comment by freddydk** [comment]
You would have to share the script you use to run your container with? and what the AdditionalSetup.ps1 contains?
The AdditionalSetup.ps1 in the my folder is something the container gets from the outside and apparently that is where it fails.

**Comment by dkorinets** [comment]
SetupNavContainer:

if (!(Test-Path function:Log)) {
    function Log([string]$line, [string]$color = "Gray") {
        ("<font color=""$color"">" + [DateTime]::Now.ToString([System.Globalization.DateTimeFormatInfo]::CurrentInfo.ShortTimePattern.replace(":mm",":mm:ss")) + " $line</font>") | Add-Content -Path "c:\demo\status.txt"
        Write-Host -ForegroundColor $color $line 
    }
}

Import-Module -name NavContainerHelper -DisableNameChecking

. (Join-Path $PSScriptRoot "settings.ps1")

$imageName = $navDockerImage.Split(',')[0]

docker ps --filter name=$containerName -a -q | % {
    Log "Removing container $containerName"
    docker rm $_ -f | Out-Null
}

$exist = $false
docker images -q --no-trunc | % {
    $inspect = docker inspect $_ | ConvertFrom-Json
    if ($inspect.RepoTags | Where-Object { "$_" -eq "$imageName" -or "$_" -eq "${imageName}:latest"}) { $exist = $true }
}
if (!$exist) {
    Log "Pulling $imageName (this might take ~30 minutes)"
    docker pull $imageName
}

$inspect = docker inspect $imageName | ConvertFrom-Json
$country = $inspect.Config.Labels.country
$navVersion = $inspect.Config.Labels.version
$nav = $inspect.Config.Labels.nav
$cu = $inspect.Config.Labels.cu
$locale = Get-LocaleFromCountry $country

if ($nav -eq "devpreview") {
    $title = "Dynamics 365 ""Tenerife"" Preview Environment"
} elseif ($nav -eq "main") {
    $title = "Dynamics 365 ""Tenerife"" Preview Environment"
} else {
    $title = "Dynamics NAV $nav Demonstration Environment"
}

Log "Using image $imageName"
Log "Country $country"
Log "Version $navVersion"
Log "Locale $locale"

$securePassword = ConvertTo-SecureString -String $adminPassword -Key $passwordKey
$credential = New-Object System.Management.Automation.PSCredential($navAdminUsername, $securePassword)
#$azureSqlCredential = New-Object System.Management.Automation.PSCredential($azureSqlAdminUsername, $securePassword)
$params = @{ "enableSymbolLoading" = $true 
             "licensefile" = "$licensefileuri" }
$additionalParameters = @("--publish  8080:8080",
                          "--publish  443:443", 
                          "--publish  7046-7049:7046-7049", 
                          "--env publicFileSharePort=8080",
                          "--env PublicDnsName=$publicdnsName",
                          "--env RemovePasswordKeyFile=N",
                          "--memory 4G"
                          )
if ("$appBacpacUri" -ne "" -and "$tenantBacpacUri" -ne "") {
    if ("$sqlServerType" -eq "SQLExpress") {
        $additionalParameters += @("--env appbacpac=$appBacpacUri",
                                   "--env tenantbacpac=$tenantBacpacUri")
    } else {
        Log "using $azureSqlServer as database server"
        $params += @{ "databaseServer"     = "$azureSqlServer"
                      "databaseInstance"   = ""
                      "databaseName"       = "App"
                      "databaseCredential" = $azureSqlCredential }
        $multitenant = "Yes"
    }
}
if ("$clickonce" -eq "Yes") {
    $additionalParameters += @("--env clickonce=Y")
}

if ($multitenant -eq "Yes") {
    $params += @{ "multitenant" = $true }
}

$myScripts = @()
Get-ChildItem -Path "c:\myfolder" | % { $myscripts += $_.FullName }

$auth = "NavUserPassword"
if ($Office365UserName -ne "" -and $Office365Password -ne "") {
    $auth = "AAD"
}

Log "Running $imageName (this will take a few minutes)"
New-NavContainer -accept_eula @Params `
                 -containerName $containerName `
                 -useSSL `
                 -auth $Auth `
                 -includeCSide `
                 -doNotExportObjectsToText `
                 -authenticationEMail $Office365UserName `
                 -credential $credential `
                 -additionalParameters $additionalParameters `
                 -myScripts $myscripts `
                 -imageName $imageName


if ($sqlServerType -eq "AzureSQL") {
    if (Test-Path "c:\demo\objects.fob" -PathType Leaf) {
        Log "Importing c:\demo\objects.fob to container"
        Import-ObjectsToNavContainer -containerName $containerName -objectsFile "c:\demo\objects.fob" -sqlCredential $azureSqlCredential
    }
    New-NavContainerTenant -containerName $containerName -tenantId "default" -sqlCredential $azureSqlCredential
    New-NavContainerNavUser -containerName $containerName -tenant "default" -Credential $credential -AuthenticationEmail $Office365UserName -ChangePasswordAtNextLogOn:$false -PermissionSetId "SUPER"
} else {
    if (Test-Path "c:\demo\objects.fob" -PathType Leaf) {
        Log "Importing c:\demo\objects.fob to container"
        $sqlCredential = New-Object System.Management.Automation.PSCredential ( "sa", $credential.Password )
        Import-ObjectsToNavContainer -containerName $containerName -objectsFile "c:\demo\objects.fob" -sqlCredential $sqlCredential
    }
}

if ("$includeappUris".Trim() -ne "") {
    foreach($includeApp in "$includeAppUris".Split(',;')) {
        Publish-NavContainerApp -containerName $containerName -appFile $includeApp -sync -install
    }
}

# Copy .vsix and Certificate to container folder
$containerFolder = "C:\ProgramData\navcontainerhelper\Extensions\$containerName"
Log "Copying .vsix and Certificate to $containerFolder"
docker exec -it $containerName powershell "copy-item -Path 'C:\Run\*.vsix' -Destination '$containerFolder' -force
copy-item -Path 'C:\Run\*.cer' -Destination '$containerFolder' -force
copy-item -Path 'C:\Program Files\Microsoft Dynamics NAV\*\Service\CustomSettings.config' -Destination '$containerFolder' -force
if (Test-Path 'c:\inetpub\wwwroot\http\NAV' -PathType Container) {
    [System.IO.File]::WriteAllText('$containerFolder\clickonce.txt','http://${publicDnsName}:8080/NAV')
}"
[System.IO.File]::WriteAllText("$containerFolder\Version.txt",$navVersion)
[System.IO.File]::WriteAllText("$containerFolder\Cu.txt",$cu)
[System.IO.File]::WriteAllText("$containerFolder\Country.txt", $country)
[System.IO.File]::WriteAllText("$containerFolder\Title.txt",$title)

if ($Office365UserName -ne "" -and $Office365Password -ne "") {
    Log "Creating Aad Apps for Office 365 integration"
    $CustomConfigFile =  Join-Path $containerFolder "CustomSettings.config"
    $CustomConfig = [xml](Get-Content $CustomConfigFile)
    $publicWebBaseUrl = $CustomConfig.SelectSingleNode("//appSettings/add[@key='PublicWebBaseUrl']").Value
    $secureOffice365Password = ConvertTo-SecureString -String $Office365Password -Key $passwordKey
    $Office365Credential = New-Object System.Management.Automation.PSCredential($Office365UserName, $secureOffice365Password)
    Create-AadAppsForNav -AadAdminCredential $Office365Credential -appIdUri $publicWebBaseUrl -IncludeExcelAadApp -IncludePowerBiAadApp
    $auth = "AAD"
}

# Install Certificate on host
$certFile = Get-Item "$containerFolder\*.cer"
if ($certFile) {
    $certFileName = $certFile.FullName
    Log "Importing $certFileName to trusted root"
    $pfx = new-object System.Security.Cryptography.X509Certificates.X509Certificate2 
    $pfx.import($certFileName)
    $store = new-object System.Security.Cryptography.X509Certificates.X509Store([System.Security.Cryptography.X509Certificates.StoreName]::Root,"localmachine")
    $store.open("MaxAllowed") 
    $store.add($pfx) 
    $store.close()
}

Log -color Green "Container output"
docker logs $containerName | % { log $_ }

Log -color Green "Container setup complete!"

**Comment by dkorinets** [comment]
The files don't contain any custom code...

**Comment by freddydk** [comment]
SetupNavContainer should never run on your local windows 10 computer.
SetupNavContainer is designed for the Azure VMs and is not intended for being used anywhere else.
If you want to run NAV containers on Windows 10 - install the navcontainerhelper and use new-navcontainer.

**Comment by dkorinets** [comment]
oh sorry, didn't know  about that. will try to use NAV Container Helper
Thank You
