### ISSUE TITLE
[Question] Docker image for Dynamics 365 Business Central

### ISSUE THREAD

**Issue by hgnamvn** [Microsoft/nav-docker#178]
Hi!

I have a stupid question.
How can I get a docker images for Dynamics 365 Business Central (W1 preview) for local environment if i don't have a permission (AAD global administrator) to get package on Microsoft Collaborate.

I get from microsoft/dynamics-nav (docker pull microsoft/dynamics-nav:devpreview) But it is seem it isn't preview version of Dynamics 365 Business Central.

I need build local version for developing my package.

Beside of that, I also try to get docker image for **March Update**, but they don't exist on microsoft/dynamics-nav hub.

**Comment by freddydk** [comment]
Within the next hour, microsoft/dynamics-nav:devpreview is in fact the Business Central Sandbox.
From within Business Central, you can search for Sandbox Environment (Container) and get an environment with the same version of Business Central as your tenant is running either local or azure hosted.
http://aka.ms/bcsandbox in a browser should also give you the latest.

**Comment by hgnamvn** [comment]
Thank Freddydk!

I see that the docker images is uploading to the hub.

Thank you so much.
