### ISSUE TITLE
Client crashes in 2018 with DK language (virtual table problem?)

### ISSUE THREAD

**Issue by AskeHolst** [Microsoft/nav-docker#180]
I have a client crashing when using Danish language. 

Repro steps:
- Install a container with **microsoft/dynamics-nav:2018-cu3-dk**
- Open the web client
- Switch language to Danish
- Open G/L Budgets ("Finansbudgetter")
- Press Edit Budget ("Rediger Budget")
- Press "Next Set" ("Næste Sæt")
_! The client crashes_
![image](https://user-images.githubusercontent.com/8398485/38405018-13041dbc-396e-11e8-8672-ea76b3b63c8a.png)
![image](https://user-images.githubusercontent.com/8398485/38405026-1958e3d2-396e-11e8-996a-7405a80cf909.png)

The debugger shows the error on a call to SETPOSITION on the virtual Date table. The RecordPosition included the Danish field captions and it looks like the server fails to translate them back to the real field names. So i'm guessing this could be due to translations missing for the virtual Date table.

Testing the same in a **2018-cu2-dk** and **2018-cu3-se** also gives the error, in a **11.0.21063.0-findk** container I get no error.

**Comment by freddydk** [comment]
Thanks for the very detailed repro steps - very easy to repro, very time saving.
I will investigate

**Comment by Petyun** [comment]
GETPOSTIOTION in this case returns captions of the fields (Periodetype=CONST(Date),Periodestart=CONST()), and it causes the crash on SETPOSITION. In the codeunit 9200  - the function GeneratePeriodMatrixData - change RecordPosition := Calendar.GETPOSITION; to RecordPosition := Calendar.GETPOSITION(FALSE);

**Comment by freddydk** [comment]
I cannot repro this on the latest docker image. Please re-open if the issue still persists.
