### ISSUE TITLE
Please publish working sample of importCountry.ps1

### ISSUE THREAD

**Issue by worldofthenavcraft** [Microsoft/nav-docker#183]
I read from NAV Docker Image word document about building a country version of NAV like this:

```
FROM microsoft/dynamics-nav:2017-cu9
ENV COUNTRYURL ”<URL to COUNTRY specific zipfile>”
COPY ./importCountry.ps1 C:/RUN/importCountry.ps1
ENV DatabaseName CronusDK
RUN PowerShell .\Run\importCountry.ps1
```

It would be very helpful when you publish working example of importCountry.ps1 to nav-docker-master. It simplifies things. So far I did not found that ps script from master.

Br,
Indrek

**Comment by Koubek** [comment]
Maybe I don't understand very well of the objective you have but I would recommend using MS images whenever possible.

If this is not possible for any reason you have, then it is very important to understand Docker build process, all internal scripts of NAV Docker images and then I would still suggest you using the specific NAV images for a specific country. This means avoid using this:
```Dockerfile
FROM microsoft/dynamics-nav:2017-cu9
```
And using (for example) this instead:
```Dockerfile
FROM microsoft/dynamics-nav:2017-cu9-dk
```
In this case you won't probably need to implement `importCountry.ps1`, you just add your generic stuff and that's it. You will need recreate the images frequently so you will need your repo, some nightly builds etc. I am not telling that this approach has no sense but you need to have a really good reason to do that and again, understand Docker really well.

And the last option, less recommendable, is to build everything from the scratch. And this is something I don't recommend it at all.

**Comment by worldofthenavcraft** [comment]
Thanks for feedback. That’s right I really need good reasons for that and first we should use docker images provided by Microsoft. 

Unfortunately, not all country versions have currently managed by Microsoft. On this github repo you can find word document called “NAV Docker Image.docx” 
(link: https://github.com/Microsoft/nav-docker/raw/master/NAV%20Docker%20Image.docx)

On this document there are instructions how to create your own Image based on a specific NAV image. Also, there are very good instructions about country specific version building (our country version is not managed by Microsoft). 
Unfortunately, importCountry.ps1 is not available on this GitHub repository yet. Probably Freddy have overloaded for some technical tasks. Hopefully one day he will publish this script. 
I just want to containerize country version what is not managed by Microsoft. That’s It.  To keep up to date my private container repro is not big deal. 
There are very good service available on Azure. It’s called Azure Container Register. Linkt(https://azure.microsoft.com/en-us/services/container-registry/) I made my private docker image available around of 20 minutes.

**Comment by freddydk** [comment]
This is the code. Note that the CountryURL environment variable is set to contain a secure url to a file with the database etc.
This is given as is - the build process is subject to change when we move to delegate the building of our images to an azure service, which also will build 1709 versions and 1803 versions.
`
$ErrorActionPreference = "Stop"
Write-Host "Importing Country"

$serviceTierFolder = (Get-Item "C:\Program Files\Microsoft Dynamics NAV\*\Service").FullName
Import-Module "$serviceTierFolder\Microsoft.Dynamics.Nav.Management.psm1"

. (Join-Path $PSScriptRoot "HelperFunctions.ps1")

$NavServiceName = 'MicrosoftDynamicsNavServer$NAV'
$SqlServiceName = 'MSSQL$SQLEXPRESS'
$SqlWriterServiceName = "SQLWriter"
$SqlBrowserServiceName = "SQLBrowser"

Write-Host "Downloading database"
$countryFile = "C:\COUNTRY.zip"
(New-Object System.Net.WebClient).DownloadFile("$env:COUNTRYURL", $countryFile)
[Reflection.Assembly]::LoadWithPartialName("System.IO.Compression.Filesystem") | Out-Null
$countryFolder = "$PSScriptRoot\Country"
New-Item -Path $countryFolder -ItemType Directory -ErrorAction Ignore | Out-Null
[System.IO.Compression.ZipFile]::ExtractToDirectory($countryFile, $countryFolder)

Write-Host "Starting Local SQL Server"
Start-Service -Name $SqlBrowserServiceName -ErrorAction Ignore
Start-Service -Name $SqlWriterServiceName -ErrorAction Ignore
Start-Service -Name $SqlServiceName -ErrorAction Ignore

# Restore CRONUS Demo database to databases folder

Write-Host "Restore CRONUS Demo Database"
$databaseName = "$env:DatabaseName"
$databaseFolder = "c:\databases\$databaseName"
$databaseServer = "localhost"
$databaseInstance = "SQLEXPRESS"
$bak = (Get-ChildItem -Path "$countryFolder\*.bak")[0]
$databaseFile = $bak.FullName

# Restore database
New-Item -Path $databaseFolder -itemtype Directory | Out-Null
New-NAVDatabase -DatabaseServer $databaseServer `
                -DatabaseInstance $databaseInstance `
                -DatabaseName "$databaseName" `
                -FilePath "$databaseFile" `
                -DestinationPath "$databaseFolder" | Out-Null

# Shrink the demo database log file
& SQLCMD -Q "USE master;
ALTER DATABASE $DatabaseName SET RECOVERY SIMPLE;
GO
USE $DatabaseName;
GO
DBCC SHRINKFILE(2, 1)
GO"

# run local installers if present
if (Test-Path "$countryFolder\Installers" -PathType Container) {
    Get-ChildItem "$countryFolder\Installers" -Recurse | Where-Object { $_.PSIsContainer } | % {
        $dir = $_.FullName
        Get-ChildItem (Join-Path $dir "*.msi") | % {
            $filepath = $_.FullName
            if ($filepath.Contains('\WebHelp\')) {
                Write-Host "Skipping $filepath"
            } else {
                Write-Host "Installing $filepath"
                Start-Process -FilePath $filepath -WorkingDirectory $dir -ArgumentList "/qn /norestart" -Wait
            }
        }
    }
}

"ConfigurationPackages","TestToolKit","UpgradeToolKit","Extensions" | % {
    if (Test-Path "c:\$_"-PathType Container) {
        Write-Host "Remove old $_"
        Remove-Item "c:\$_" -Recurse -Force
    }
    if (Test-Path "$countryFolder\$_" -PathType Container) {
        Write-Host "Copy $_"
        Copy-Item -Path "$countryFolder\$_" -Destination "c:\" -Recurse
    }
}

$CustomConfigFile =  Join-Path $ServiceTierFolder "CustomSettings.config"
$CustomConfig = [xml](Get-Content $CustomConfigFile)
$customConfig.SelectSingleNode("//appSettings/add[@key='DatabaseName']").Value = "$databaseName"
$CustomConfig.Save($CustomConfigFile)

Write-Host "Start NAV Service Tier"
Start-Service -Name $NavServiceName -WarningAction Ignore

Write-Host "Import License file"
$licensefile = Join-Path $countryFolder "Cronus.flf"
Import-NAVServerLicense -LicenseFile $licensefile -ServerInstance 'NAV' -Database NavDatabase -WarningAction SilentlyContinue

Write-Host "Remove CRONUS DB"
$cronusFiles = Get-NavDatabaseFiles -DatabaseName "CRONUS"
& sqlcmd -Q "ALTER DATABASE [CRONUS] SET OFFLINE WITH ROLLBACK IMMEDIATE"
& sqlcmd -Q "DROP DATABASE [CRONUS]"
$cronusFiles | % { remove-item $_.Path }

$serverFile = "$ServiceTierFolder\Microsoft.Dynamics.Nav.Server.exe"
$serverVersion = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($serverFile)
if ($serverVersion.FileMajorPart -ge 11) {
    $roleTailoredClientFolder = (Get-Item "C:\Program Files (x86)\Microsoft Dynamics NAV\*\RoleTailored Client").FullName
    Write-Host "Generating Symbol Reference"
    $pre = (get-process -Name "finsql" -ErrorAction Ignore) | % { $_.Id }
    Start-Process -FilePath "$roleTailoredClientFolder\finsql.exe" -ArgumentList "Command=generatesymbolreference, Database=$databaseName, ServerName=localhost\SQLEXPRESS, ntauthentication=1"
    $procs = get-process -Name "finsql" -ErrorAction Ignore
    $procs | Where-Object { $pre -notcontains $_.Id } | Wait-Process
}

Write-Host "Cleanup"
Remove-Item $countryFile -Force
Remove-Item $countryFolder -Force -Recurse
`
