### ISSUE TITLE
Developer Preview initialization failed

### ISSUE THREAD

**Issue by StanislawStempin** [Microsoft/nav-docker#185]
Moving the issue from AL GitHub:
https://github.com/Microsoft/AL/issues/1979

**Comment by freddydk** [comment]
You should use Docker images as explained here: https://blogs.msdn.microsoft.com/freddyk/2018/04/16/which-docker-image-is-the-right-for-you/
dynamics-nav:devpreview are not being updated - but that isn't the problem here.
I just tried deploying at it works fine - I assume you have a URL wrong.
