### ISSUE TITLE
Cannot run image of older NAV version (71)

### ISSUE THREAD

**Issue by RHaest** [Microsoft/nav-docker#186]
See below the error, any tips how to fix this? Thanks,

PS C:\Windows\system32> docker run --name test01 --hostname test01 -e ACCEPT_EULA=Y navdocker.azurecr.io/dynamics-nav:7.1.35473.0-nl
Initializing...
Hostname is test01
Cannot find path 'C:\Program Files\Microsoft Dynamics NAV\71\Service\CustomSettings.config' because it does not exist.
at <ScriptBlock>, C:\Run\navstart.ps1: line 82
at <ScriptBlock>, C:\Run\start.ps1: line 18
at <ScriptBlock>, <No file>: line 1

**Comment by freddydk** [comment]
navdocker no longer exists - if you have navdocker images on your system, they are very old.
If you want to run versions before NAV 2016 you will need to use the generic image and share a NAVDVD to it.
You will find blog posts on my blog describing how to do this.

**Comment by RHaest** [comment]
Thanks Freddy, didn't know that and will proceed in that direction.
