### ISSUE TITLE
Error when running NAV Docker container

### ISSUE THREAD

**Issue by SergioKelly** [Microsoft/nav-docker#187]
I am getting this error
PS C:\WINDOWS\system32> docker run -m 3G -e ACCEPT_EULA=Y microsoft/dynamics-nav:2018-cu3
Unable to find image 'microsoft/dynamics-nav:2018-cu3' locally
2018-cu3: Pulling from microsoft/dynamics-nav
3889bb8d808b: Pull complete
133e38d368dd: Pull complete
cda823bc6d27: Pull complete
bc848a7c134f: Pull complete
2a7a6140868c: Pull complete
6a7a53476e5e: Pull complete
1b6111e05132: Pull complete
2dd9bcad0f2a: Pull complete
799d3e8cb53f: Pull complete
650cc0266f7e: Pull complete
616743f87555: Pull complete
7b9380a1cd41: Pull complete
bbf05ed60440: Pull complete
0b606e1a38a4: Pull complete
4d04c81353c8: Pull complete
d65366f9601b: Pull complete
Digest: sha256:5cfa1637ceac87ede5f47ada42f7e97bb76689130aed7bd3d20117a94eda7572
Status: Downloaded newer image for microsoft/dynamics-nav:2018-cu3
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container fa0ffbfb3d851180589f7626c16b772dc266b3cac7f777e1b9dc5c6f7f66ec0f encountered an error during CreateContainer: hcsshim: timeout waiting for notification extra info: {"SystemType":"Container","Name":"fa0ffbfb3d851180589f7626c16b772dc266b3cac7f777e1b9dc5c6f7f66ec0f","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\fa0ffbfb3d851180589f7626c16b772dc266b3cac7f777e1b9dc5c6f7f66ec0f","Layers":[{"ID":"cca9ad30-b354-5a8c-b65d-f6407d131a76","Path":"C:\\ProgramData\\Docker\\windowsfilter\\dfdb3dc999e8398db754c01740c6013916f339f982ec90ba487e54e6f1f81b0b"},{"ID":"5bd9a379-d6d7-5476-bae8-7528b71422c3","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a45417dd4147877c994fef7714843eaec922259b3a44038f73bcf2cd15b6d04f"},{"ID":"8e77d00b-3099-5fa2-9f85-0e654fe125d2","Path":"C:\\ProgramData\\Docker\\windowsfilter\\e746a5213febc266667e9215ffe6589b236bd71e4ec55c180e2e5486324e0c46"},{"ID":"3faeeba8-c302-50f4-918c-951fb5addf71","Path":"C:\\ProgramData\\Docker\\windowsfilter\\488bd0e829aaf60641045a3e0bb5468ab0e6b77236e2832104f539b4a4361391"},{"ID":"45eb5f59-637c-548e-80c5-2aee804ea10d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4ab7d8d00c9b33080d34dac15239d139402105c33ac7a0e96fd4b9f131f9d344"},{"ID":"7dc75f9c-6ee1-5bb8-ab7c-1e0fb06f59b4","Path":"C:\\ProgramData\\Docker\\windowsfilter\\9b79debad2af5f1e0afe87aff00383feb61a411809ab2f7cd153d0140bba9951"},{"ID":"a56108f2-2565-578c-afe7-cde25cfd0d7c","Path":"C:\\ProgramData\\Docker\\windowsfilter\\dc442ecbaca586ab0e509e430b40bed543f860315b4681ec04a9f95c1d8f3eed"},{"ID":"4a582ba2-699f-537e-9a71-3853644282fb","Path":"C:\\ProgramData\\Docker\\windowsfilter\\d3cd9e69a3c5ae1561445f1a49f4bdf24d1043ac81417ac902f76d9327fd8c75"},{"ID":"ec9b5d9b-11d1-57c6-b272-33d0e707770b","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f0d96f4c80446e05ad3ae6f3eb8c60b6a9db3227ecfe75873472f891920b634a"},{"ID":"91b6b822-af46-56cd-9059-bd093ea6fbb3","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4ef76674d0f5a106e2a7292e9f1d7a952344f0e21800859af935181a58b883fd"},{"ID":"02b406e1-123e-53b5-a8ff-bd41ef70d369","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3b0165dc910a5087202202a8c3fa790593bfeecfcf56f48895b8a79a610842da"},{"ID":"9c141fb3-8e25-5f2f-8f62-20b092f6101a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\9e4367c07ae31b4f31d0535f632186a91e6020c8526bdde3746631543ee60573"},{"ID":"af6315fb-5ea9-5da7-a415-9baaaa305edf","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6cda8c13aaf26ac79183654bab40c4628b01153da1be5201625cbf0de3d52bec"},{"ID":"f87f862e-e7e5-5991-9da8-5f157f690d2f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6dacbfda5bf47228542ca63c6d9ad4e35f06a2bbae24f34d51c40fd6efbe08da"},{"ID":"06b57fe0-78f0-5f97-895c-2b6a6fc499d6","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ef4c29a0369e4e20acbfcf897c2842e85b670508139e4ef4cf52f7178b60296d"},{"ID":"bb1eebca-9fc6-5ced-badb-bbc879577249","Path":"C:\\ProgramData\\Docker\\windowsfilter\\fbe5930d65374eb928f866571940338f78b8ab0a086acd4b8f019e56c4771dd3"}],"MemoryMaximumInMB":3072,"HostName":"fa0ffbfb3d85","HvPartition":true,"EndpointList":["e13adb93-06f0-43e7-9146-dfcf9ec119e8"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\ef4c29a0369e4e20acbfcf897c2842e85b670508139e4ef4cf52f7178b60296d\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}.
PS C:\WINDOWS\system32>

**Comment by freddydk** [comment]
Looks like there is something wrong with Docker on your machine.
Please test your installation using this: **https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/** or using this script **http://aka.ms/debug-containerhost.ps1**
and see if that can resolve your issue.

**Comment by freddydk** [comment]
I will close the issue. Please re-open with more information if needed.

**Comment by SergioKelly** [comment]
Hi Freddy,
I am getting different issue when I want to create a new container from image microsoft/dynamics-nav:devpreview

PS C:\WINDOWS\system32> New-NavContainer -accept_eula -containerName myBusiCentral -imageName microsoft/dynamics-nav:devpreview
Creating Nav container myBusiCentral
Using image microsoft/dynamics-nav:devpreview
NAV Version: 12.0.21229.0-W1
Generic Tag: 0.0.5.5
Removing container myBusiCentral
Removing C:\ProgramData\NavContainerHelper\Extensions\myBusiCentral
Creating container myBusiCentral from image microsoft/dynamics-nav:devpreview
dabeb9d0cf620f678e7c5f89d0804bb6318a457458975ce1917be601ca9216f3

docker.exe: Error response from daemon: container dabeb9d0cf620f678e7c5f89d0804bb6318a457458975ce1917be601ca9216f3 encountered an error during CreateContainer: failure in a Windows system call
: This operation returned because the timeout period expired. (0x5b4) extra info: {"SystemType":"Container","Name":"dabeb9d0cf620f678e7c5f89d0804bb6318a457458975ce1917be601ca9216f3","Owner":"d
ocker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\dabeb9d0cf620f678e7c5f89d0804bb6318a457458975ce1917be601ca9216f3","Layers":[{"ID":"be70c671-cac
9-552d-8a58-126ba9bf9ce5","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1cbfe201f5fc117adfa1a243a98b66d26c9f3c2f801e4c7344dde0181f6e5413"},{"ID":"62c42648-9dab-5101-987c-dd51793e393c","Path"
:"C:\\ProgramData\\Docker\\windowsfilter\\c27bc76f5beeb9f1266781a17e7ba3f9dd7275ee1150e3b458c27786bcba7e72"},{"ID":"8594ac2b-9650-5526-ae26-f12b4bac3857","Path":"C:\\ProgramData\\Docker\\windo
wsfilter\\1714ad6920498bedacee2978ad6e214787bb8c67eba523a07b3438db26b3d302"},{"ID":"c6de4e81-b5ae-5af1-86ea-dbd7aa5308d6","Path":"C:\\ProgramData\\Docker\\windowsfilter\\42b32174f04c28d229d7ba
e546d9e75221589e22953af450fa6de1901640021b"},{"ID":"d79a63d8-9864-5a50-a505-8828d879b3c8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\2c19cd06b44010e39cfed7e8ebe731fab8b41dfe7209b2f8177cbd
ff3bb0cdc1"},{"ID":"ca9add17-8cfc-528e-a54c-fac7e5fd720c","Path":"C:\\ProgramData\\Docker\\windowsfilter\\913c9f2b5db1cf00f5de1192ee036f0d3cd5c42d4f5fd5acc805753dcc3488d4"},{"ID":"39c96e8e-ce6
3-52c5-9498-89381346cb67","Path":"C:\\ProgramData\\Docker\\windowsfilter\\535c7555fd17b307cf397322fe06f6afd9ea251421b5dc3a68921d5ff9a49c33"},{"ID":"3c95c9ae-f65c-576e-8b7d-e9cab0fb7abf","Path"
:"C:\\ProgramData\\Docker\\windowsfilter\\8d1e04e27741b9cc737bdd06ea56e955617f8d54895cfd8e3e733bc9652e9625"},{"ID":"71650441-b6dd-5bf3-b10f-9e06c7554c40","Path":"C:\\ProgramData\\Docker\\windo
wsfilter\\45e069e9d693fbd1e40bf2bc0d25d1ea4e3035d13f0c0f00327e7bf3fe6b8927"},{"ID":"b7d6b335-26a3-535e-a788-c0f03fa535bf","Path":"C:\\ProgramData\\Docker\\windowsfilter\\08dc48f9874790c34623fd
c92e0c1ad9a5ba48c1faf0dec48ce1af1734ab5df5"},{"ID":"757e5efc-08ec-5947-87fe-b02be21c26a3","Path":"C:\\ProgramData\\Docker\\windowsfilter\\d8e0a48b55c36b1fd9509a88f3263002bda5ba25b8cacd74ef9966
fd065f5c60"},{"ID":"c356b934-0227-52ab-9990-df9a655243b2","Path":"C:\\ProgramData\\Docker\\windowsfilter\\0e35f738c88154ecd8d4f8e3e6ea896296fa7164f555cc6e0a54083a085e68df"},{"ID":"17af8ff0-9f9
c-5398-b9fe-5b79f0a27ae8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cd4c0d062512d2da941fd2c3cb07ad4f9126a699587e285801db55b63b6459b6"},{"ID":"281ae210-9ef6-5fa5-a622-5389480f6177","Path"
:"C:\\ProgramData\\Docker\\windowsfilter\\8662d0bc5b327933c85415d69686383accdb13efecb1a83f5678ab2ac6c0bcda"},{"ID":"fc4c7f01-a89f-54b7-9f3f-6d8513175215","Path":"C:\\ProgramData\\Docker\\windo
wsfilter\\a59fb08fa58b39298c32ecaf5872457c6346a0967eca589693210f8580ba1d25"},{"ID":"bb44a8ee-ff17-54ba-98a3-105d46971a4a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\032fce50d6017e6b45240e
0c55f306c0d9af39280d3705cf494cf6d628c35dfd"}],"MemoryMaximumInMB":4096,"HostName":"myBusiCentral","MappedDirectories":[{"HostPath":"c:\\programdata\\navcontainerhelper","ContainerPath":"c:\\pr
ogramdata\\navcontainerhelper","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\navcontainerhelper\\extensions\\mybusicentral\\my"
,"ContainerPath":"c:\\run\\my","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["739a9ffe-369c-4695-a91c-9c4537852622"],"HvR
untime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\a59fb08fa58b39298c32ecaf5872457c6346a0967eca589693210f8580ba1d25\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}.

Commandline: docker run --name myBusiCentral --hostname myBusiCentral --env auth=Windows --env username="Sergio" --env ExitOnError=N --env locale=en-US --env licenseFile="" --env databaseServe
r="" --env databaseInstance="" --volume "C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContainerHelper" --volume "C:\ProgramData\NavContainerHelper\Extensions\myBusiCentral\my:C:\Run\my"
 --restart unless-stopped --memory 4G --env useSSL=N --env securePassword=76492d1116743f0423413b16050a5345MgB8AGkAZQBZADEAcgBmAGoAcQBOAFoAZwBUAEYAaAAzAGQAcQBNADAASwBpAFEAPQA9AHwANgBiADYAYwAzAG
EAOAA0AGIANwA4AGYAOABiAGUAYwAxADYAYgBhADYAMgA3ADgAMwA1ADIAMwBlAGUANQA0ADQAOQA1ADkANgAxADEAYwA4ADYAMQBmADAAZQAxADgAZAAxAGYANwA3ADQAOQAyADYAMQA4ADYAZgA3AGYANQA= --env passwordKeyFile="c:\run\my\
aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y --detach microsoft/dynamics-nav:devpreview

**Comment by freddydk** [comment]
There is nothing wrong with your new-navcontainer statement, except for you shouldn't use microsoft/dynamics-nav:devpreview - you should use microsoft/bcsandbox:us.

But as stated before there is something wrong with the docker installation on your box. Try to follow the two links described in my earlier mail to troubleshoot your installation.
