### ISSUE TITLE
Set-FieldDataClassificationFromExcelFile needs excel

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/nav-docker#188]
Don't we all love GDPR?

Trying to run `Set-FieldDataClassificationFromExcelFile` fails. First the container was missing the module from the DVD. After copying the psm1 to the container and running `Import-Module WindowsPowerShellScripts\DataClassification\DataClassification.psm1` in the container we clould run the command. Fails though, looks like some excel component is missing in the container. That is no surprise, but what can we do about it?

![set-fielddataclassificationfromexcelfile](https://user-images.githubusercontent.com/25029667/39548118-d96f0142-4e59-11e8-8f81-a44bf8dec204.jpg)

**Comment by freddydk** [comment]
Those cmdlets are clearly not designed to run inside containers.
You should be able to run the cmdlets on your pc using the database in the container or having the database on a seperate database server.
Issue cannot be solved in Docker.
