### ISSUE TITLE
Question: How to create an extra service tier inside the container

### ISSUE THREAD

**Issue by spookymattress** [Microsoft/nav-docker#189]
I have tried to add code to the AdditionalSetup.ps1 to create a new service tier inside the container, but it gives me an error regarding the firewall

My code:
```
write-host "Installing additional service tiers"
New-NAVServerInstance -ManagementServicesPort 7045 -ClientServicesPort 7046 -SOAPServicesPort 7047 -ODataServicesPort 7048 -ServerInstance MyTest
```

And the error:
```
Installing additional service tiers
WARNING: Running the command 'advfirewall firewall add rule 
name="MicrosoftDynamicsNavServer$MyTest" dir=in action=allow localport="7048" 
protocol=tcp localip=any remoteip=any profile=any enable=yes' failed. Output 
message: 'An error occurred while attempting to contact the  Windows Firewall 
service. Make sure that the service is running and try your request again.

'. Error message: ''. Process exit code: '1'.
```

I have tried to do the same in the Powershell promt _after_ creating the environment, but it is the same error.

Has anybody had luck with creating new service tiers inside the container?

**Comment by Koubek** [comment]
Hi, I think it is a very bad idea to create other instances in NAV container. Why you can't just create another container? This is the best and the simplest possibility, IMO.

**Comment by Koubek** [comment]
Using a single instance (including NAS) wouldn't work for demo purposes??? And of course, in the end, you should be able to create the second instance. You have to avoid the port conflicts.

I haven't configured everything but it looks it is just a warning and the service has been created (unfortunately I haven't configured everything necessary, it was a quick test only, so there are certificate related errors in the log):

![image](https://user-images.githubusercontent.com/24265973/39701213-a186e358-5200-11e8-84d5-a133acbe2a84.png)

**Comment by spookymattress** [comment]
No, we need to have two extra instances. I know about the port conflicts...

Same error message I got..

**Comment by Koubek** [comment]
Right now I have configured everything correctly, the same warning msg (the reason of the warning is the Windows Containers and the firewall management - firewall mgt doesn't behave in the same manner like on the standard pcs/servers).

![image](https://user-images.githubusercontent.com/24265973/39701861-11618f82-5203-11e8-9070-91f65b237917.png)

But then you run `Start-Service` and you should be able to successfully start it (if everything has been correctly configured):

![image](https://user-images.githubusercontent.com/24265973/39701920-46f6fb6e-5203-11e8-9d2f-4f2dd02771c2.png)

You can validate like this:   
```PowerShell
Get-EventLog -LogName Application -Newest 10 | FL
```

**Comment by freddydk** [comment]
If you are running process isolation, there is no real difference in running two containers using the SQL database in one as their common DB.
There is no support for multiple service tiers in one container and nothing will be done to make it possible. This means that you might be able to make it work, but it might break later.

**Comment by spookymattress** [comment]
Thanks for info, Freddy and Koubek.

**Comment by mrjeyjey36** [comment]
@Koubek How did you configure it to get rid off the firewall message. As far as i know you cannot run the firewall service in the container

**Comment by freddydk** [comment]
Just heard that Windows 10 fall 2018 update will support process isolation:-)
