### ISSUE TITLE
Cannot create an instance of following .net framework object.....

### ISSUE THREAD

**Issue by shashiBssi** [Microsoft/nav-docker#190]
@freddydk I have my custom dlls, my obects are compiling, but when using them in rtc I m getting error like.

Cannot create an instance of following .net framework object.....

Iam running nav 2018 on docker container.

**Comment by Koubek** [comment]
You can copy them into the container or even better, you can mount a volume and share them (map an existing folder on your host as a non-existing subfolder inside the container, inside the service addins folder). You can see an example for example here:
https://github.com/Koubek/nav-docker-examples/blob/master/share_mount_addins/run.ps1

**Comment by shashiBssi** [comment]
i think by doing this..
---------------------------------------------------------------------------------------------------------
I have put my DLLs on this path
C:\ProgramData\NavContainerHelper\Extensions\Development\Program Files\110\RoleTailored Client\Add-ins
--------------------------------------------------------------------------------------------------------

i have already copy them into the container.
Is there any other way you are trying to say

**Comment by richardrobberse** [comment]
Please be aware that dlls get blocked by windows when you've for example downloaded them from the internet.
Copying those dlls to your add-ins folder will result in the same error (cannot create an instance etc. etc.)
Please verify the dlls are not blocked by going to its properties, you can also unblock it from there.

**Comment by shashiBssi** [comment]
@richardrobberse 
theses are my custom DLLs which i have not downloaded from internet.
However i have checked the properties and couldn't find anything like block.

**Comment by Koubek** [comment]
@shashiBssi Sorry, I don't use NavContainerHelper. Anyway, if you use this approach (NavContainerHelper), next time I would suggest posting the issue there.

@richardrobberse Great, that's true. In this case, you can use again PowerShell:
```PowerShell
Get-ChildItem <parent_folder> -recurse | Unblock-File
```

**Comment by freddydk** [comment]
It sounds like you have placed the DLL's in the add-ins folder of the client - but not on the server.
They need to be placed in the add-ins folder under the service folder as well.
if you have a folder c:\myaddins on the host with the files, you can share that folder to the add-ins folder by adding this parameter to new-navcontainer:
-additionalParameters @('-v "c:\myaddins:c:\program files\microsoft Dynamics NAV\110\Service\Add-ins"')
Haven't tested, but I think this is the right syntax.

**Comment by shashiBssi** [comment]
@freddydk 

i have not installed NAV on my local system. so how can i get this path
c:\program files\microsoft Dynamics NAV\110\Service\Add-ins


I have created a container with from nav image using new-navcontainer with option includecside.
it gave me windows client shortcut, webclient shortcut and cside dev environment shortcut.

**Comment by freddydk** [comment]
The parameter I added above will mount your local folder into the container, meaning that your c\myaddins will almost by magic be shared to myaddins under the service folder in the container.
Read more here:
https://docs.docker.com/storage/volumes/#choose-the--v-or---mount-flag

**Comment by richardrobberse** [comment]
Yes.

**Comment by freddydk** [comment]
As Richard stated - correct.
You can view the container file system by opening the container command prompt or using open-navcontainer <containername> on your host.

**Comment by shashiBssi** [comment]
Thank you so much @Koubek @richardrobberse  @freddydk

**Comment by hasnainali-di** [comment]
Hi @shashiBssi @freddydk 
I'm facing the same issue, I'm using BC18
DLL is placed in Add-in folder,
DLL is unblocked,
DLL is digitally signed.

Still getting the same issue: Cannot create an instance of the following .NET Framework

![image](https://github.com/microsoft/nav-docker/assets/83631379/e6aa7f8f-2cab-4382-801a-e0cf0d5b6f86)


Any help will be really appreciated. Thanks :)
