### ISSUE TITLE
Cannot connect Nav Client

### ISSUE THREAD

**Issue by 420tech** [Microsoft/nav-docker#191]
I followed the instructions on running a local sandbox in Docker on Windows 10. I have tried running the container at 3GB and 4GB. When I try to run the Nav Client, I get the error cannot connect to the server. The web client works just fine - I can log in no problem (with either memory configuration). I note that the script setup the connection to the server as "myGreenForce:7046/NAV". Is that the right port?

**Comment by richardrobberse** [comment]
Are you using the windows client shortcut provided by the navcontainerhelper?
If not - please give it a try.

This shortcut passes in the correct ClientUserSettings.config so that it doesn't take one from one of your other local NAV installations.

**Comment by aproehl79** [comment]
I used the shortcut provided by the navcontainerhelper and have the same problem. WebClient worked, but RTC not. Also Dev-Environment is not able to connect to Management-Port.

**Comment by freddydk** [comment]
Sounds like I will have to find a machine with April Creators Update and test it.
Personally, I run Windows Server - works much better - but Windows 10 needs to work as well.
Give me a few days.

**Comment by 420tech** [comment]
Any update? Still having same issue.

**Comment by freddydk** [comment]
got a machine setup with 1803 - and executed:

New-NavContainer -accept_eula -containerName test -imageName microsoft/bcsandbox:us -includeCSide -doNotExportObjectsToText

works like a charm.
Must be something else

maybe you need some cleanup.
If you still have the problem, please display more information about which command you execute, logs, inspect etc,

**Comment by 420tech** [comment]
I reset my docker instance to "Factory defaults". I ran this script in PS as Admin: 

New-NavContainer -accept_eula -containerName GFMMS -imageName microsoft/bcsandbox:us -includeCSide -doNotExportObjectsToText

It installed fine - no errors. It created 5 short cuts on my desktop: GFMMS Web Client, GFMMS Windows Client, GFMMS CSIDE, GFSMMS Command Prompt, and GFMMS PowerShell.

The GFMMS Windows Client fails with the error message "The Program could not create a connection to the server. Do you want to try again?".  Clicking "Yes" 5-6 times yields the same error message. Clicking No, gives the opportunity to change the server connection information. The server address shown is GFMMS:7046/NAV

The GFMMS CSide shortcut worked only after I switched authentication.

**Comment by freddydk** [comment]
Everything looks correct - did you try to add -auth NavUserPassword to your new-navcontainer and see if that changes things?

**Comment by aproehl79** [comment]
I just have to update the navcontainerhelper to the newest version. After this the RTC have a connection and runs as expected.

@420tech: open the powershell with admin rights an run the following command:
`Get-InstalledModule -Name "navcontainerhelper" -RequiredVersion 0.2.7.5 | Uninstall-Module`

after that run:
`find-module 'navcontainerhelper' | install-module`

If your old version ist not the "0.2.7.5" find out wich version is installed with:
`Get-Module –ListAvailable`

After installation of the newest version of navcontainerhelper you can create new-csidecontainer:
`New-CSideDevContainer -accept_eula -imagename 'microsoft/dynamics-nav:2018-cu3-de' -doNotExportObjectsToText`

**Comment by freddydk** [comment]
Ok, strange, wasn't aware that older navcontainerhelper versions didn't work - but good to know.

Anyway - please note that new-csidedevcontainer is just calling new-navcontainer with -includecside and doesn't have as many options. Personally I never use new-csidedevcontainer.

**Comment by aproehl79** [comment]
maybe only the version `0.2.7.5` in combination with windows 10 version 1803!?

**Comment by freddydk** [comment]
Did you try NavUserPassword - you just re-run the new-navcontainer with -auth NavUserPassword - it will remove the old container and create a new one.

**Comment by 420tech** [comment]
That worked! Thank you!

**Comment by freddydk** [comment]
It looks like the Client cannot see your AD server - this means that Windows Auth towards containers cannot be used unless you setup group managed service accounts.
