### ISSUE TITLE
Cannot acces NAV inside container

### ISSUE THREAD

**Issue by cbape** [Microsoft/nav-docker#193]
After I pulled the microsoft/bcsandbox:dk IMAGE, and created a container for it, I got the webclient link, Dev-client, etc on my desktop. The container was created with acces to my windows user credentials.

Unforunately i cannot acces either of the clients, because it prompts for my windows user credentials.
Fx Internet Explorer prompts me for a logon (se attached picture).
![docker-issue1](https://user-images.githubusercontent.com/39245780/39970824-96bbe4e0-56f2-11e8-85bc-42a35098b890.png)

Please help.

**Comment by freddydk** [comment]
Did you create this using new-navcontainer in the navcontainerhelper - or docker run?
if you used docker run - please specify the full docker run command here (without the username and password)

**Comment by cbape** [comment]
Hi Freddy
It was created using a new-navcontainer, but after at while i couldn't start the container and therefore I ran it manually with docker run.

Could you help with the command?

**Comment by cbape** [comment]
I used this script to pull the image and create the container:

install-module navcontainerhelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true

$containername = 'DYN365BC-CBAPE'
$navdockerimage = 'microsoft/bcsandbox:12.0.21576.0-dk'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth Windows `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
				 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password

**Comment by freddydk** [comment]
You can change to Username/password auth by specifying -auth NavUserPassword (instead of -auth Windows) to the New-NavContainer.
Sounds like the AD has some settings, which disallows the Windows Auth. from working.

**Comment by cbape** [comment]
Hi Freddy
Thank you for your answer. I had success changing the credentialtype to: NavUserPassword.
Suddenly the webclient now shows the "old" webclient design and not the new webdesign!

I used these parameter:

New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth NavUserPassword `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
				 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage2 `
                 -additionalParameters $additionalParameters

**Comment by freddydk** [comment]
You are using $navdockerimage2 - what is the value of that? - you might need to remove the 2

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cbape** [comment]
Hi Freddy
You are right.
My mistake to use this variable.

/ Christian
