### ISSUE TITLE
NAV 2013 RTM DE: "New-NAVDatabase" is not recognized as the name of a cmdlet ...

### ISSUE THREAD

**Issue by wansinby** [Microsoft/nav-docker#194]
Hello to all,
I'm trying to set up NAV 2013 RTM de (DVD fresh from Partnersource) with this great tool and the great instructions from Freddy - but it doesn't work.
NAV2013R2 RTM de, NAV2015 RTM de or CU43 de, all are no problem (with NET3). But NAV2013RTMde doesn't want to install.
I copied NET3-Install to Prerequisite-folder, and copied the folders \Webclient\Inetpub and \WindowsPoswerShellScripts from the NAV2013R2-DVD to the NAV2013-DVD-folder, as the installer/script requires them (and stops if they are missing).
But then the script stops with this error message:
![grafik](https://user-images.githubusercontent.com/39342649/40128761-bc65b18e-5932-11e8-8935-892e643f23c4.png)

I use the following script:

install-module navcontainerhelper -force
Import-Module navcontainerhelper
Update-Module navcontainerhelper -force
$adminPassword = (convertTo-SecureString -String 'xxxxx' -AsPlainText -Force)
$credential = New-Object System.Management.Automation.PSCredential('admin', $adminPassword)
$sqlcredential = New-Object System.Management.Automation.PSCredential('sa', $adminPassword)
$licensepath = 'c:\xxx\Dev-NAV2013.flf'
$containername = 'nav2013test'
New-NavContainer
    -accept_eula
    -containerName $containername
    -navDvdPath "c:\DVD\2013RTMDE"
    -navDvdCountry de
    -includeCSide
    -Credential $credential
    -memoryLimit 4G
    -updateHosts
    -auth NavUserPassword
    -doNotExportObjectsToText
    -licenseFile $licensepath
    -shortcuts Desktop
    -myScripts @("c:\DVD\nav-docker-master\Run\70") (fresh copy from github)

Any ideas what's going wrong?

Best regards,
Wolfram

**Comment by freddydk** [comment]
I think the cmdlets for creating a database was added in some CU of NAV 2013 - and the powershell scripts very much rely on those.

I am sorry, but I will not have time to look into this issue with a version which is long overdue.

You can try to install the DVD and check out whether the powershell cmdlets are available and try to debug the issue yourself - the source for the docker image is available right here.

**Comment by wansinby** [comment]
Dear Freddy,
tnx for your tipp for some CU in NAV2013. I tried to install NAV2013CU58de, and the error above is gone - but I have some other errors (missing directories \WindowsPowerShellScripts, ...). I changed the script 70/navinstall.ps1 for debugging, and solved some problems, but now I got an error I don't know to handle, so I have to stop (The service could not add service principal names ...).
We want to use NAV2013 on docker for an update from 2013 to 2018(R2). I will try the NAV2013-DB to import in NAV2013R2-Docker, because NAV2013R2 works without problems.
If I have some time I will invetigate again in this problem.
Tnx to all for help - also the tipp from richardrobberse helped me to find out wich dlls were missing.

**Comment by freddydk** [comment]
The service principal name thing is just a warning - should not be an issue I think.
If I get some time left over I might give it a shot some day.

**Comment by wansinby** [comment]
Found one problem of NVA2013cu58:
The error is:
Importing CRONUS license file
A Parameter cannot be found that matches parameter name 'LicenseFile'
The cmdlet "Import-NAVServerLicense" of NAV2013cu58 doesn't know the parameter 'LicenseFile', it only accepts 'LicenseData', wich expects System.Byte and not a filename. I'm not very familar with powershell, so the solution is not easy for me. I'll try to find a way to give Import-NAVServerLicense a System.Byte(-Stream).

**Comment by wansinby** [comment]
Found the solution (tnx Internet):
Import-NAVServerLicense -LicenseData ([Byte[]]$(Get-Content -Path $licensefile -Encoding Byte)) -ServerInstance 'NAV' -Database NavDatabase -WarningAction SilentlyContinue
But now another error occurs: Modifying Service Tier Config File
The property 'value' cannot be found in this object.
I will check later / another time and write about the result(s).

**Comment by wansinby** [comment]
Result: some more errors because the settings of NAV2013 are named different than NAV2015 and above - or unknown.
SetupLicense.ps1: see above (LicenseData instead of LicenseFile).
SetupConfiguration.ps1: Keys "DefaultClient", "Multitenant", "PublicSOAPBaseUrl", "PublicODataBaseUrl", "PublicWinBaseUrl" are unknown in NAV2013. "ServicesCertificateThumbprint" and "ServicesCertificateValidationEnabled" has to be "ClientServices...".
SetupNavUsers.ps1: New-NavServerUser does not know "-AuthenticationEMail"

But now I have a problem with AdditionalSetup.ps1. This file is filled by a script or program, and it uses "ServicesCertificateValidationEnabled", but for NAV2013 it has to be "ClientServicesCertificateValidationEnabled". OK, i can make a own AdditionalSetup.ps1 with correct parameter, but the program/script filling AdditionalSetup.ps1 writes all settings at the end, icluding "ServicesCertificateValidationEnabled", so the process is stopped here.

Which program/script filles AdditionalSetup.ps1? Where do I have to change "ServicesCertificateValidationEnabled" in "CleintServicesCertificateValidationEnabled"? If I get the answer, i can continue with testing.

P.S.: I don't know much about Powershell and Docker, so maybe there is an easier way to skip this line, but at the moment I don't know it, and I have only very limited access to internet.

**Comment by wansinby** [comment]
Summary (at the moment): I copy the attached modified scripts "navinstall.ps1", "SetupConfiguration.ps1", "SetupLicense.ps1", "SetupNavUsers.ps1" and "AdditionalSetup.ps1" to c:\myscripts and start "CreateContainer2013-cu58-de.ps1".
It nearly works fine, except any program/script modifies "AdditionalSetup.ps1" and adds the not working settings to the end of "AdditionalSetup.ps1". Then the process stops.
So I need a little help, and then I hope it will be possible to create a NAV2013CU58 docker container.
[NAV2013CU58-Modifications-01.zip](https://github.com/Microsoft/nav-docker/files/2044274/NAV2013CU58-Modifications-01.zip)

**Comment by freddydk** [comment]
Thanks
I am travelling this week, but will have a look at this when I get back (sometime next week probably).

**Comment by freddydk** [comment]
I have created a new version of the generic image, you can test it using the imagename: microsoft/dynamics-nav:generic-0.0.6.0
This should be able to run your NAV 2013 as well.
Thanks for your effort.
Within the next few days, this will become default (meaning that you can remove -0.0.6.0)

**Comment by wansinby** [comment]
Dear Freddy,
tnx for the new generic image 0.0.6.0. It works fine except the last error I described:
I used "New-NavContainer ..." without -myScripts, so I used all scripts from the image. Everythings runs fine till "AdditionalSetup.ps1". This file should be empty, but is has content - and here is the reason for the error. This script tries to set "ServicesCertificateValidationEnabled", but NAV2013 expects "ClientServicesCertificateValidationEnabled". Which program modifies "AdditionalSetup.ps1" - which programm adds lines to this file? If "AdditionalSetup.ps1" would be empty, I think the complete process would run without errors.
![grafik](https://user-images.githubusercontent.com/39342649/40916566-7d6d6dfa-6800-11e8-9391-2598c95479a9.png)
Where does "AdditionalSetup.ps1" come from - I don't use "-myScripts".
![grafik](https://user-images.githubusercontent.com/39342649/40916597-9c012220-6800-11e8-89e1-8db85a787962.png)

**Comment by freddydk** [comment]
The additionalsetup comes from NavContainerhelper, which will be updated tomorrow probably.
For now, you can clone the github repo to your machine, uninstall and remove the module and run navcontainerhelper.ps1 from the cloned folder - then you will have the changes now.

**Comment by wansinby** [comment]
Dear Freddy,
tnx for modifying NavContainerHelper. With cloned folder, install runs without error, and it's possible to connect to the Dev-Environment. Win-Client doen't want to work at the moment, I'm looking for the reason. And after this, I'll try NAV2013RTM (with DLLs from 2013cu58).

**Comment by wansinby** [comment]
Dear Freddy,
with Cronus license NAV2013cu58 works! Great! So I will test NAV2013RTM and, after finishing everything, I'll write a complete solution. Thank you for fast and great support.
