### ISSUE TITLE
Cannot connect to azure function emulator while running business central on docker container

### ISSUE THREAD

**Issue by shashiBssi** [Microsoft/nav-docker#195]
BC is running inside a docker.
Azure function emulator  is running on docker host

 listening on                 http://localhost:7071/api/Function1
the function cant be accessed from BC running inside docker.

error : No connection could be made because the target machine actively refused it

**Comment by freddydk** [comment]
The container is seeing localhost as itself - you will need to expose your host to the network so that you can see it from the container and open firewalls etc.

**Comment by shashiBssi** [comment]
Any way/Suggestion on how to expose my host ?

**Comment by freddydk** [comment]
No, that all depends on your host, your network etc.
Basically the container is just like a different computer - if you can call your azure function from a different computer in the same network - then the same url should work from inside your container.

**Comment by freddydk** [comment]
Easiest thing is probably to put both containers in a .yaml file and use docker-compose up to start both containers - this is the suggested way of running more containers which talks together.
