### ISSUE TITLE
NAV Client will lose connection after SQL database container is restarted 

### ISSUE THREAD

**Issue by liviadinu** [Microsoft/nav-docker#196]
Hello,

I am running NAV on docker with external SQL database, and each time the database
container is restarted, the Web & Windows Clients will not connect anymore. 

**Steps:**
1. Create database container (script bellow)
2. Create NAV container (script bellow)
3. Login to Web & Windows Client (login successful)
3. Stop NAV container
4. Restart SQL cotnainer 
5. Check database is accessible
6. Start NAV container
7. Start NAV Server Instance
8. Connect to Web & Windows Client - failed

![capture](https://user-images.githubusercontent.com/18129118/40253783-51cd27a2-5ae1-11e8-8b95-d90da1cff1b3.JPG)

CSide is connecting without issue after restaring the SQL container (objects can modified, compiled, etc).
Both containers run on the same host. Restarting the NAV container (or NAV server instance inside container) with database container still running works fine.

**Set-up NAV container:**

$hostname = 'test'
$navImageNameTag = 'microsoft/dynamics-nav:2017'
$licenseFile = "C:\run\myfolder\mydevlicense.flf"
$dbcontainername = 'sqldb'
$dbname = 'Sandbox2017'
$AddtionalParam = "--restart unless-stopped"

new-navcontainer `
-accept_eula `
-containername $hostname `
-imageName $navImageNameTag `
-auth NavUserPassword `
-includecside `
-updateHosts `
-licenseFile $licenseFile `
-doNotExportObjectsToText `
-Credential (get-credential) `
-accept_outdated `
-databaseServer $dbcontainername `
-databaseName $dbname `
-databaseCredential (get-credential)`
-AdditionalParameters @($AddtionalParam) 

**Output**

> Initializing...
> Starting Container
> Hostname is test
> PublicDnsName is test
> Using NavUserPassword Authentication
> Starting Internet Information Server
> Import Encryption Key
> Creating Self Signed Certificate
> Self Signed Certificate Thumbprint 10C21D1245EDFF066910AB7200E730953C77249B
> Modifying Service Tier Config File with Instance Specific Settings
> Starting NAV Service Tier
> Using license file 'c:\run\my\license.flf'
> Import License
> Creating Web Site
> Creating Web Server Instance
> Creating http download site
> Creating Windows user sa
> Container IP Address: 172.23.19.3
> Container Hostname  : test
> Container Dns Name  : test
> Web Client          : http://test/NAV/WebClient/
> 
> Files:
> 
> Initialization took 515 seconds
> Ready for connections!

**Set-up SQL container**

$dbcontainername = 'sqldb'
$dbimage = <_private repo image based on microsoft/mssql-server-windows-express_>
$password

docker run -d --hostname=$dbcontainername `
--restart unless-stopped `
-e locale=en-NL `
-e ACCEPT_EULA=Y `
-e sa_password=$password `
-v C:/temp/:C:/temp `
--name $dbcontainername $dbimage

**Log of the NAV container after restarting Database Container**

> docker logs test
> 
> TimeGenerated : 5/18/2018 8:19:51 PM
> EntryType     : Warning
> Message       : Server instance: NAV
>                 Category: Sql
>                 ClientSessionId: 00000000-0000-0000-0000-000000000000
>                 ClientActivityId: 00000000-0000-0000-0000-000000000000
>                 ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
>                 ServerActivityId: 00000000-0000-0000-0000-000000000000
>                 EventTime: 05/18/2018 18:19:51
>                 Message <ii>Threshold Trace Tag. Execution Time = 1367
>                 milliseconds
>                     Long Running SQL statement Task ID:3
>                     exec sp_helptext @objname =
>                 '[dbo].[RemoveOnLogoutActiveSession]'</ii>
>                 ProcessId: 2904
>                 Tag: 000007L
>                 ThreadId: 15
>                 CounterInformation:
> 
> 
> TimeGenerated : 5/18/2018 8:20:14 PM
> EntryType     : Warning
> Message       : Server instance: NAV
>                 Category: Sql
>                 ClientSessionId: 1b014741-416b-4489-b8e7-a3fcf823f816
>                 ClientActivityId: 82e1e969-71c9-4c1e-8da1-578bdd68052c
>                 ServerSessionUniqueId: c6b41ef5-63c2-4a4d-ab46-9de95279b241
>                 ServerActivityId: 97fddd38-6ab9-4e0b-8ce5-c17bff792390
>                 EventTime: 05/18/2018 18:20:14
>                 Message <ii>NavSqlQueryCommand is recreated due to the changed
>                 connection.</ii>
>                 ProcessId: 2904
>                 Tag: 00000BS
>                 ThreadId: 22
>                 CounterInformation:
> 
> 
> **Initializing...
> Cannot find path 'C:\run\my\aes.key' because it does not exist.
> at <ScriptBlock>, C:\Run\SetupVariables.ps1: line 44
> at <ScriptBlock>, C:\Run\navstart.ps1: line 23
> at <ScriptBlock>, C:\Run\start.ps1: line 107
> at <ScriptBlock>, <No file>: line 1**
> 
> 
> TimeGenerated : 5/18/2018 8:31:01 PM
> EntryType     : Warning
> Message       : Server instance: NAV
>                 Tenant:
>                 <ii>SSL/HTTPS has not been configured for ODataV4 Services;
>                 client credentials will be sent over an unsecured transport
>                 (HTTP).</ii>
> 
> TimeGenerated : 5/18/2018 8:31:01 PM
> EntryType     : Warning
> Message       : Server instance: NAV
>                 Tenant:
>                 <ii>The service could not add service principal names because
>                 the service account could not be found in Active Directory.
>                 Account: NT AUTHORITY\SYSTEM
>                 Service principal names:
>                 DynamicsNAV/test:7045
>                 DynamicsNAV/test:7045</ii>
> 
> TimeGenerated : 5/18/2018 8:31:01 PM
> EntryType     : Warning
> Message       : Server instance: NAV
>                 Tenant:
>                 <ii>The service could not add service principal names because
>                 the service account could not be found in Active Directory.
>                 Account: NT AUTHORITY\SYSTEM
>                 Service principal names:
>                 http/test:7048
>                 http/test:7048</ii>
> 
> TimeGenerated : 5/18/2018 8:31:00 PM
> EntryType     : Warning
> Message       : Server instance: NAV
>                 Tenant:
>                 <ii>The service could not add service principal names because
>                 the service account could not be found in Active Directory.
>                 Account: NT AUTHORITY\SYSTEM
>                 Service principal names:
>                 http/test:7047
>                 http/test:7047</ii>
> 
> TimeGenerated : 5/18/2018 8:31:00 PM
> EntryType     : Warning
> Message       : Server instance: NAV
>                 Tenant:
>                 <ii>The service could not add service principal names because
>                 the service account could not be found in Active Directory.
>                 Account: NT AUTHORITY\SYSTEM
>                 Service principal names:
>                 DynamicsNAV/test:7046
>                 DynamicsNAV/test:7046</ii>

**docker version**

> Client:
>  Version:      18.03.1-ce
>  API version:  1.37
>  Go version:   go1.9.5
>  Git commit:   9ee9f40
>  Built:        Thu Apr 26 07:12:48 2018
>  OS/Arch:      windows/amd64
>  Experimental: false
>  Orchestrator: swarm
> 
> Server:
>  Engine:
>   Version:      18.03.1-ce
>   API version:  1.37 (minimum version 1.24)
>   Go version:   go1.9.5
>   Git commit:   9ee9f40
>   Built:        Thu Apr 26 07:21:42 2018
>   OS/Arch:      windows/amd64
>   Experimental: false

  
 **docker inspect test**

> [
>     {
>         "Id": "d10496dc34961db3a11150ed53cef9fd297c456d9870b9bbdc9e8f625c1ba416",
>         "Created": "2018-05-18T17:53:27.2090881Z",
>         "Path": "powershell",
>         "Args": [
>             "-Command",
>             "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
>             ".\\Run\\start.ps1"
>         ],
>         "State": {
>             "Status": "running",
>             "Running": true,
>             "Paused": false,
>             "Restarting": false,
>             "OOMKilled": false,
>             "Dead": false,
>             "Pid": 1872,
>             "ExitCode": 0,
>             "Error": "",
>             "StartedAt": "2018-05-18T18:29:31.1226436Z",
>             "FinishedAt": "2018-05-18T20:26:18.234319+02:00",
>             "Health": {
>                 "Status": "healthy",
>                 "FailingStreak": 0,
>                 "Log": [
>                     {
>                         "Start": "2018-05-18T20:59:24.8678025+02:00",
>                         "End": "2018-05-18T20:59:28.057858+02:00",
>                         "ExitCode": 0,
>                         "Output": ""
>                     },
>                     {
>                         "Start": "2018-05-18T20:59:58.102568+02:00",
>                         "End": "2018-05-18T21:00:00.9400671+02:00",
>                         "ExitCode": 0,
>                         "Output": ""
>                     },
>                     {
>                         "Start": "2018-05-18T21:00:30.9980781+02:00",
>                         "End": "2018-05-18T21:00:34.1258214+02:00",
>                         "ExitCode": 0,
>                         "Output": ""
>                     },
>                     {
>                         "Start": "2018-05-18T21:01:04.213749+02:00",
>                         "End": "2018-05-18T21:01:07.0639918+02:00",
>                         "ExitCode": 0,
>                         "Output": ""
>                     },
>                     {
>                         "Start": "2018-05-18T21:01:37.1139349+02:00",
>                         "End": "2018-05-18T21:01:39.9951533+02:00",
>                         "ExitCode": 0,
>                         "Output": ""
>                     }
>                 ]
>             }
>         },
>         "Image": "sha256:1d7259527bcfb9555cfa2c0e104907af73caa4c178bd9979989759f2013033f2",
>         "ResolvConfPath": "",
>         "HostnamePath": "",
>         "HostsPath": "",
>         "LogPath": "C:\\ProgramData\\Docker\\containers\\d10496dc34961db3a11150ed53cef9fd297c456d9870b9bbdc9e8f625c1ba416\\d10496dc34961db3a11150ed53cef9fd297c456d9870b9bbdc9e8f625c1ba416-json.log",
>         "Name": "/test",
>         "RestartCount": 0,
>         "Driver": "windowsfilter",
>         "Platform": "windows",
>         "MountLabel": "",
>         "ProcessLabel": "",
>         "AppArmorProfile": "",
>         "ExecIDs": [
>             "3fd8d8a811c6a08d28e8b38f27f380d2e499125de8ffaff1c7af9506ec0dcc06"
>         ],
>         "HostConfig": {
>             "Binds": [
>                 "c:\\windows\\system32\\drivers\\etc:C:\\driversetc",
>                 "C:\\ProgramData\\NavContainerHelper:C:\\ProgramData\\NavContainerHelper",
>                 "C:\\ProgramData\\NavContainerHelper\\Extensions\\test\\my:C:\\Run\\my",
>                 "C:\\ProgramData\\NavContainerHelper\\Extensions\\test\\Program Files:C:\\navpfiles"
>             ],
>             "ContainerIDFile": "",
>             "LogConfig": {
>                 "Type": "json-file",
>                 "Config": {}
>             },
>             "NetworkMode": "default",
>             "PortBindings": {},
>             "RestartPolicy": {
>                 "Name": "unless-stopped",
>                 "MaximumRetryCount": 0
>             },
>             "AutoRemove": false,
>             "VolumeDriver": "",
>             "VolumesFrom": null,
>             "CapAdd": null,
>             "CapDrop": null,
>             "Dns": [],
>             "DnsOptions": [],
>             "DnsSearch": [],
>             "ExtraHosts": null,
>             "GroupAdd": null,
>             "IpcMode": "",
>             "Cgroup": "",
>             "Links": null,
>             "OomScoreAdj": 0,
>             "PidMode": "",
>             "Privileged": false,
>             "PublishAllPorts": false,
>             "ReadonlyRootfs": false,
>             "SecurityOpt": null,
>             "UTSMode": "",
>             "UsernsMode": "",
>             "ShmSize": 0,
>             "ConsoleSize": [
>                 0,
>                 0
>             ],
>             "Isolation": "hyperv",
>             "CpuShares": 0,
>             "Memory": 4294967296,
>             "NanoCpus": 0,
>             "CgroupParent": "",
>             "BlkioWeight": 0,
>             "BlkioWeightDevice": [],
>             "BlkioDeviceReadBps": null,
>             "BlkioDeviceWriteBps": null,
>             "BlkioDeviceReadIOps": null,
>             "BlkioDeviceWriteIOps": null,
>             "CpuPeriod": 0,
>             "CpuQuota": 0,
>             "CpuRealtimePeriod": 0,
>             "CpuRealtimeRuntime": 0,
>             "CpusetCpus": "",
>             "CpusetMems": "",
>             "Devices": [],
>             "DeviceCgroupRules": null,
>             "DiskQuota": 0,
>             "KernelMemory": 0,
>             "MemoryReservation": 0,
>             "MemorySwap": 0,
>             "MemorySwappiness": null,
>             "OomKillDisable": false,
>             "PidsLimit": 0,
>             "Ulimits": null,
>             "CpuCount": 0,
>             "CpuPercent": 0,
>             "IOMaximumIOps": 0,
>             "IOMaximumBandwidth": 0
>         },
>         "GraphDriver": {
>             "Data": {
>                 "dir": "C:\\ProgramData\\Docker\\windowsfilter\\d10496dc34961db3a11150ed53cef9fd297c456d9870b9bbdc9e8f625c1ba416"
>             },
>             "Name": "windowsfilter"
>         },
>         "Mounts": [
>             {
>                 "Type": "bind",
>                 "Source": "c:\\windows\\system32\\drivers\\etc",
>                 "Destination": "c:\\driversetc",
>                 "Mode": "",
>                 "RW": true,
>                 "Propagation": ""
>             },
>             {
>                 "Type": "bind",
>                 "Source": "c:\\programdata\\navcontainerhelper",
>                 "Destination": "c:\\programdata\\navcontainerhelper",
>                 "Mode": "",
>                 "RW": true,
>                 "Propagation": ""
>             },
>             {
>                 "Type": "bind",
>                 "Source": "c:\\programdata\\navcontainerhelper\\extensions\\test\\my",
>                 "Destination": "c:\\run\\my",
>                 "Mode": "",
>                 "RW": true,
>                 "Propagation": ""
>             },
>             {
>                 "Type": "bind",
>                 "Source": "c:\\programdata\\navcontainerhelper\\extensions\\test\\program files",
>                 "Destination": "c:\\navpfiles",
>                 "Mode": "",
>                 "RW": true,
>                 "Propagation": ""
>             }
>         ],
>         "Config": {
>             "Hostname": "test",
>             "Domainname": "",
>             "User": "",
>             "AttachStdin": false,
>             "AttachStdout": false,
>             "AttachStderr": false,
>             "ExposedPorts": {
>                 "1433/tcp": {},
>                 "443/tcp": {},
>                 "7045/tcp": {},
>                 "7046/tcp": {},
>                 "7047/tcp": {},
>                 "7048/tcp": {},
>                 "7049/tcp": {},
>                 "80/tcp": {},
>                 "8080/tcp": {}
>             },
>             "Tty": false,
>             "OpenStdin": false,
>             "StdinOnce": false,
>             "Env": [
>                 "locale=en-US",
>                 "databaseSecurePassword=76492d1116743f0423413b16050a5345MgB8AEsAUQBpAGsAVABMADcAUQB0AGIAZwBPACsAbABwAHQAawBTAEQAcwBkAEEAPQA9AHwANAA3AGYAMgA0ADgAMQA0ADIAOABhAGMAZAA4ADkAYQBiAGUAZQBkADYAMAA0ADkAZABkADgANwAzAGIAMwA5ADQANwA2AGIAMQA0AGEANwBhADAAZQAxADMANwA5AGIAOAA2AGMAYgAzAGYAMwA5AGEAYwBlADcAMgA5ADAAMQA=",
>                 "securePassword=76492d1116743f0423413b16050a5345MgB8AEIAWABxAFkALwBPADEAaQBNAFgATQBVADEAaQBuAGwAMwA4ADcAdAAzAGcAPQA9AHwAZQA4ADMAMwAzADIAMAA4AGYAZABkADIANgBjAGUAMwAzADEAMQAwADMAOQA3ADMAZAA0AGYAOABkADkAOQAyADIAZABhADAAOAA0ADQAOQAyADgAYwBlADMAMABkADkAYwA4ADAAMwA1ADAAMABjADQANQA5ADAAOQBiADcAOQA=",
>                 "passwordKeyFile=c:\\run\\my\\aes.key",
>                 "accept_outdated=Y",
>                 "auth=NavUserPassword",
>                 "licenseFile=c:\\run\\my\\license.flf",
>                 "databaseInstance=",
>                 "removePasswordKeyFile=Y",
>                 "encryptionSecurePassword=76492d1116743f0423413b16050a5345MgB8AEsAUQBpAGsAVABMADcAUQB0AGIAZwBPACsAbABwAHQAawBTAEQAcwBkAEEAPQA9AHwANAA3AGYAMgA0ADgAMQA0ADIAOABhAGMAZAA4ADkAYQBiAGUAZQBkADYAMAA0ADkAZABkADgANwAzAGIAMwA5ADQANwA2AGIAMQA0AGEANwBhADAAZQAxADMANwA5AGIAOAA2AGMAYgAzAGYAMwA5AGEAYwBlADcAMgA5ADAAMQA=",
>                 "accept_eula=Y",
>                 "username=sa",
>                 "ExitOnError=N",
>                 "databaseServer=sqldb",
>                 "databaseName=Sandbox2017",
>                 "useSSL=N",
>                 "databaseUsername=sa",
>                 "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/eb2af6d1-082c-4e27-9528-2311b8b17f9f"
>             ],
>             "Cmd": [
>                 "powershell",
>                 "-Command",
>                 "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
>                 ".\\Run\\start.ps1"
>             ],
>             "Healthcheck": {
>                 "Test": [
>                     "CMD",
>                     "powershell",
>                     ".\\Run\\HealthCheck.ps1"
>                 ],
>                 "Interval": 30000000000,
>                 "Timeout": 10000000000
>             },
>             "ArgsEscaped": true,
>             "Image": "microsoft/dynamics-nav:2017",
>             "Volumes": null,
>             "WorkingDir": "",
>             "Entrypoint": null,
>             "OnBuild": null,
>             "Labels": {
>                 "country": "W1",
>                 "created": "201804121144",
>                 "cu": "cu17",
>                 "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
>                 "legal": "http://go.microsoft.com/fwlink/?LinkId=724017",
>                 "maintainer": "Dynamics SMB",
>                 "nav": "2017",
>                 "osversion": "10.0.14393.2125",
>                 "tag": "0.0.5.6",
>                 "version": "10.0.21440.0"
>             }
>         },
>         "NetworkSettings": {
>             "Bridge": "",
>             "SandboxID": "d10496dc34961db3a11150ed53cef9fd297c456d9870b9bbdc9e8f625c1ba416",
>             "HairpinMode": false,
>             "LinkLocalIPv6Address": "",
>             "LinkLocalIPv6PrefixLen": 0,
>             "Ports": {
>                 "1433/tcp": null,
>                 "443/tcp": null,
>                 "7045/tcp": null,
>                 "7046/tcp": null,
>                 "7047/tcp": null,
>                 "7048/tcp": null,
>                 "7049/tcp": null,
>                 "80/tcp": null,
>                 "8080/tcp": null
>             },
>             "SandboxKey": "d10496dc34961db3a11150ed53cef9fd297c456d9870b9bbdc9e8f625c1ba416",
>             "SecondaryIPAddresses": null,
>             "SecondaryIPv6Addresses": null,
>             "EndpointID": "",
>             "Gateway": "",
>             "GlobalIPv6Address": "",
>             "GlobalIPv6PrefixLen": 0,
>             "IPAddress": "",
>             "IPPrefixLen": 0,
>             "IPv6Gateway": "",
>             "MacAddress": "",
>             "Networks": {
>                 "nat": {
>                     "IPAMConfig": null,
>                     "Links": null,
>                     "Aliases": null,
>                     "NetworkID": "7aa9c6d6fcf2782c833780b05a59f868e0375414878b43614cd3d7bf29ce0c0c",
>                     "EndpointID": "91c6f6797d4ec1428c4c4d0799fcef8d490629aa60b6f11eb728ed525dd4f28d",
>                     "Gateway": "172.23.16.1",
>                     "IPAddress": "172.23.29.90",
>                     "IPPrefixLen": 16,
>                     "IPv6Gateway": "",
>                     "GlobalIPv6Address": "",
>                     "GlobalIPv6PrefixLen": 0,
>                     "MacAddress": "00:15:5d:9a:7e:fe",
>                     "DriverOpts": null
>                 }
>             }
>         }
>     }
> ]

**Comment by liviadinu** [comment]
Issue is solved in build 10.0.22286

**Comment by freddydk** [comment]
Correct - 10.0.22286.0 is based on a new generic layer (version 0.0.6.x) which fixes the restart issue with windows auth.

**Comment by Kotygoroh** [comment]
Hi guys, I face the same problem with microsoft/dynamics-nav:2018-cu3-ch. Could you describe the solution for that? What does 10.0.22286.0 relate to? Thanks!

**Comment by freddydk** [comment]
if it is the same problem, you should just pull a new version of the container - and recreate it.
Either add -alwayspull to new-navcontainer or use docker pull microsoft/dynamics-nav:2018-cu3-ch will give you a new.
Docker inspect microsoft/dynamics-nav:2018-cu3-ch should say "tag": "0.0.6.3" under labels.

**Comment by Kotygoroh** [comment]
Hi Freddy, that resolved my issue. Thank you for the explinations!
