### ISSUE TITLE
Creating container

### ISSUE THREAD

**Issue by 420tech** [Microsoft/nav-docker#197]
In a fresh installation on Windows 10 (16 GB memory, 500 GB disk space, I7 processor) - how long should it take for a "create container" to complete? The image being loaded is Microsoft/bcssandbox:us.

The image downloaded just fine - and I can see the image in a different powershell prompt (docker image ls). The PS script that I ran to create the container is: 
New-NavContainer -accept_eula -containerName GFMMS -imageName microsoft/bcsandbox:us -includeCSide -doNotExportObjectsToText -auth NavUserPassword

The last line in the output is "Creating container GFMMS from Microsoft/bcsandbox:us" and has been on that line for over an hour. 

In a different powershell prompt, running "docker container ls" does not list any container names.

**Comment by freddydk** [comment]
Normally 120 seconds - something is wrong with your docker installation.
Have you tried these steps: https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/

**Comment by GerritSo** [comment]
You can try to add `-memoryLimit 3G`
On my Windows 10 Notebook Nav Container can only start with `3G` and not with `4G` what will be used without the memory parameter. It looks exaclty like you. There is just the message "Creating conter ..." and nothing happens for hours,

Problem is also there when running just windowsservercore with `4G` so it's not a nav docker problem ;-)

**Comment by freddydk** [comment]
Did you manage to make this work?

**Comment by anasbeg** [comment]
The last line in the output is "Creating container anas365bc from image microsoft/bcsandbox:us" and has been on that line for over an hour.
Getting same problem

**Comment by anasbeg** [comment]
Anyone please help me what i am missing my. i am using below cmd
**New-NavContainer -containerName anas365bc -accept_eula -alwaysPull -assignPremiumPlan -auth NavUserPassword -doNotExportObjectsToText -enableSymbolLoading -imageName microsoft/bcsandbox:us -includeCSide -memoryLimit 3G -updateHosts -useSSL**

**Comment by freddydk** [comment]
Did you try the troubleshooting steps:  https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/

**Comment by PedroLReis** [comment]
Previously I could create containers without any issue; however, recently I get a response saying "incorrect username or password". Does anyone know why?

![image](https://user-images.githubusercontent.com/29381792/41774070-1ed4af64-7616-11e8-8775-1e556ad41a15.png)

**Comment by freddydk** [comment]
try docker logout - worked for another guy
You must have used docker login at some point in time with some wrong credentials or like.

**Comment by anasbeg** [comment]
Same issue..I tried everything but its not creating the container..

**Comment by freddydk** [comment]
Are you getting the same error - then docker logout is what you need to do
