### ISSUE TITLE
Business Central sandbox is not provisioning after 5 hours for version 12.0.22067.0

### ISSUE THREAD

**Issue by StanislawStempin** [Microsoft/nav-docker#198]
Moving an issue from AL GitHub:
https://github.com/Microsoft/AL/issues/2297

https://user-images.githubusercontent.com/39469150/40301810-54a75b20-5d41-11e8-9980-ad9aab072a72.png

Hi @freddydk,
This is only when I try it from the BC interface, searching for Sandbox (Container) and clicking on the In Azure button.
I realise I should have raised it in nav-docker issues, do let me know if you want me to recreate it there.
Cheers,
Robert

**Comment by freddydk** [comment]
We had some build issues, which should be solved now.
