### ISSUE TITLE
Limit of 100 variants on docker hub

### ISSUE THREAD

**Issue by rdebath** [Microsoft/nav-docker#199]
Thank for all the great version update on https://hub.docker.com/r/microsoft/bcsandbox/tags/

Problem is there are too many to see them any more; for example I can still get 12.0.22067.0-w1 but it's not on the list and I can't see any later versions (if they're there).  Can you list some were the build numbers that are still there. I expect we won't have any problem adding the l10n tag on the end so a full tag list probably isn't needed.

**Comment by GerritSo** [comment]
You can use Powershell to get the full List :-)

`$RegistryEndpoint = "registry.hub.docker.com"`
`$image = "microsoft/bcsandbox"`
`$request = "https://$RegistryEndpoint/v2/repositories/$image/tags"`

`function NewRequest ($req) {`
`    $Resp = Invoke-WebRequest $req | ConvertFrom-Json`
`    $Resp.results.name | foreach { $tag = $_; Write-Host $tag -ForegroundColor Green}`      
`    If ($Resp.next) {`
`        NewRequest $Resp.next    `
`    }`
`}`

**Comment by rdebath** [comment]
Ah, there's an API, 373 entries nice.

Hmmm, "gb" is still pointing at "12.0.21812.0-gb" is that how it's supposed to be?
Looks like "w1" and "latest" are pointing at build 21812 too.

**Comment by freddydk** [comment]
I cannot control the tags list on the docker hub - it just shows the latest 100 images build, which might not at all be the latest 100 versions of bcsandbox.
I would like to understand.
Why are you looking?
Are you looking for a specific build?
Or are you just looking for the newest, which you should use?

**Comment by rdebath** [comment]
The PS fragment has solved my issue.

I was looking for the version related to this:
* "StanislawStempin added **shipped** and removed **ships-in-future-update** labels 4 hours ago"

I didn't really expect it to be available yet, but, when I looked I noticed that every single tag I could see had been created very recently so it was still possible that a new build had been released that I couldn't see.
I tried "latest" and "gb" but they are still far older than the most recent I had downloaded and so irrelevant to this .

The script got me the full list so I could confirm that the latest W1 version was unchanged and "shipped" probably just means "committed to master".
I suppose I should go and see if my problem with bcinsider.azurecr.io is fixed; I assume that's still where the nightly builds are (Not that I understand why they're requiring a login on those in the first place; everybody should understand what "nightlys" means these days).

**Comment by freddydk** [comment]
Please refer to this blog post https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/ to understand what a future update means.
These things are not available on microsoft/bcsandbox - but will be available as insider builds as you mention yourself.
We have had some build problems - but there is a new master build from yesterday on bcinsider.

**Comment by freddydk** [comment]
One more note - even though builds on microsoft/bcsandbox are created very recently - it is from a different branch and only very few fixes from the master branch will be in that branch.

**Comment by rdebath** [comment]
Ok, from your page at https://blogs.msdn.microsoft.com/freddyk/2018/04/16/which-docker-image-is-the-right-for-you/ I somehow got the idea that `microsoft/bcsandbox` was the correct one for developing an extension against. That is it get changes that have had some testing *will* be released in an upcoming version. That is I though it was the replacement for the apparently suspended "developer previews". 

Obviously, if there's no "readahead" on it I'm going to have problems on the next major upgrade. OTOH if I get the login issues sorted (It's probably just that I can't find the right page because it's swamped in the marketing and tools for marketing) on the nightly build I'll likely get a version with partial updates or other issues.

I suppose my best option is to use 2018 and backport and changes that I use from the nightlies.

**Comment by freddydk** [comment]
microsoft/bcsandbox is what people should use to build extensions - that is the stable channel.
things in the insider builds will become available later and are work in progress.
If you have access to collaborate (http://developer.microsoft.com/en-us/dashboard/collaborate) - go to packages and you should find info on how to get insider builds.

**Comment by rdebath** [comment]
Yes, I read your page I've spent a while clicking around in there. That specific page is just a "sign up for all these different programs" advert. There isn't anything labelled "Packages", I assume you mean "programs". There's the program we've registered for, developer agreement is accepted, there a "product" in progress (delayed by the change in the multi-lingual requirements) There's loads of tabs related to marketing an app, but nothing related to anything useful for actually making an "app". 

But this isn't your problem, I'll (or we'll) try talking to the support on <s>Monday</s> (Bank Holiday) Tuesday to see what's broken.

**Comment by rdebath** [comment]
Sorry, for not coming back; other people on training.
Looks like yes, we didn't have the thing called "Microsoft Collaborate" at all, the URL you gave me just dumped us into a random sales page instead. Trying to "join" it in a real user didn't work, adding it to the specially created gmail account did and we're slowing going through some sort of process.

Thankyou.
