### ISSUE TITLE
Add metadata/lables to the images

### ISSUE THREAD

**Issue by Koubek** [Microsoft/nav-docker#2]
This is a small request with a really low importance.

I use tags to identify the containers and images internally with some automatic processes, searches or in Portainer. You have included the date-time of the build and also as the docker standard says you added “Maintainer” label.

My proposal is to add some of the following attributes/labels as well (for standard NAV versions):
- Mayor version
- CU
- Language
- Maybe could add also one label reflecting the image name (dynamics-nav etc.).

All these filters have a sense when handling considerably higher quantities of the containers/images. For example:
```
# search/filter images
docker image ls --filter "label=maintainer=Freddy Kristiansen"
docker image ls --filter "label=nav-mayor=2017"
docker image ls --filter "label=nav-cu=8"

# search/filter containers
docker ps --filter "label=maintainer=Freddy Kristiansen"
docker ps --filter "label=nav-mayor=2017"
docker ps --filter "label=nav-cu=8"
```

**Comment by freddydk** [comment]
Following labels have been added (example):
nav=2017
cu=8
country=dk
version=10.0.70501.0
