### ISSUE TITLE
Serval features not available in DE version

### ISSUE THREAD

**Issue by aproehl79** [Microsoft/nav-docker#203]
When creating a w1 sandbox with `New-NavContainer -accept_eula -assignPremiumPlan -licenseFile Development_Licence.flf -imagename 'microsoft/bcsandbox:latest'` i see several features (like archiving sales orders):

![image](https://user-images.githubusercontent.com/16100797/40906252-8edb7a5c-67e0-11e8-8b43-19d1a8d8f686.png)

![image](https://user-images.githubusercontent.com/16100797/40906115-2648ff28-67e0-11e8-81d2-016091a7a2b4.png)

When creating a de sandbox with `New-NavContainer -accept_eula -assignPremiumPlan -licenseFile Development_Licence.flf -imagename 'microsoft/bcsandbox:de'` i can't find nothing of them:

![image](https://user-images.githubusercontent.com/16100797/40906340-cf6bf18c-67e0-11e8-9070-e344c1fc50d6.png)

![image](https://user-images.githubusercontent.com/16100797/40906363-dd4f6ba8-67e0-11e8-981a-ba8d0de84939.png)

I have the same problem in my live tenant wich is also "de localized".

That's the version of my de-sandbox:
![image](https://user-images.githubusercontent.com/16100797/40906888-7b2e923a-67e2-11e8-90ec-79c5a70a4589.png)

That's the version of my w1-sandbox:

![image](https://user-images.githubusercontent.com/16100797/40906944-9b329888-67e2-11e8-98d6-b9f7acf74acc.png)

**Comment by freddydk** [comment]
Did you enable premium user experience in the company information page?

**Comment by freddydk** [comment]
I don't know, just wanted to make sure it wasn't that before asking somebody.

**Comment by freddydk** [comment]
The pages are there and you can open sales order archive by adding ?page=9349 to your url.
Have no idea why they are not in search.
Is this special to docker? or is this the same in a Business Central online tenant?

**Comment by aproehl79** [comment]
Is the same in the BC online tenant. Neighter the action "Archive Sales Order" in the Sales Order Page, nor in the search it is available. I want to demonstrate the archiving feature at customer site and was wondering :-)

**Comment by freddydk** [comment]
Then it is probably not the right place you have filed this issue.
nav-docker is for things that are related to docker.
You should contact support with this issue.

**Comment by aproehl79** [comment]
Ok, sorry. Did you have a link for me?

**Comment by freddydk** [comment]
Click the smiley and select to engage the community - then ask your question there - you will have a better chance of getting an answer there,

**Comment by aproehl79** [comment]
ok, thx. Have you seen the same behavior within a "DK" tenant?

**Comment by freddydk** [comment]
It is described below why some features are not visible: https://docs.microsoft.com/en-us/dynamics365/business-central/across-faq#why-are-some-ui-elements-that-i-used-in-dynamics-nav-not-visible-in-  W1 docker images contains an on-prem version of the database, which is the reason why you see them there.
