### ISSUE TITLE
Issue with Delete Company

### ISSUE THREAD

**Issue by AlphaGeeKUK** [Microsoft/nav-docker#204]
Set up a container, create a new or copy of Cronus company then delete it.

It is removed from the list of companies in NAV, but the SQL tables are never deleted.

It's probably something to do with the lazy delete being done by some scheduled task that is not running in the container.

Anyone know what the task is and how to start it?

**Comment by freddydk** [comment]
Are you using Windows Auth or NavUserPassword auth?
Reason for asking is, that I know that the task scheduler in NAV doesn't work in Docker when running Windows Auth. We have somebody looking into this.

**Comment by AlphaGeeKUK** [comment]
It's using NavUserPassword auth.

**Comment by freddydk** [comment]
Just tried this using the microsoft/bcsandbox:de container with both Windows and NavUserPassword auth. - works fine.
Need more info.

**Comment by AlphaGeeKUK** [comment]
Hi Freddy,

It's using microsoft/dynamics-nav:2018-gb container. It had CU4 in the image when I deployed it.

**Comment by AlphaGeeKUK** [comment]
I should add it was deployed via the ARM templates (aka.ms/getnav)

**Comment by freddydk** [comment]
Yeah, the more info the less time is wasted:-)
I can repro this with NAV 2018 - but not with bcsandbox.
I will ask around

**Comment by freddydk** [comment]
This should be fixed in Cu6 - which was created on docker a few days ago.
Haven't tested myself yet.

**Comment by AlphaGeeKUK** [comment]
Hi Freddy, thanks. I'll spin a new one up and test it.

**Comment by AlphaGeeKUK** [comment]
Confirmed working ok in NAV 2018 CU6 GB container.

**Comment by AlphaGeeKUK** [comment]
I created a new VM via the ARM templates (aka.ms/getnav) for 2018 CU GB, copied Cronus company to a new one, deleted it, looked in SSMS and the copy company tables are still there.

I'm not sure how long the 'lazy' delete is supposed to take, but I'll look again in the morning.

**Comment by AlphaGeeKUK** [comment]
The company delete via the NAV client still has the tables in the database this morning,

**Comment by freddydk** [comment]
Ok, will have to go back to the team.

**Comment by freddydk** [comment]
I think I know what is wrong here.
The TaskScheduler is disabled by default in NAV 2018 containers and earlier.
You can add this as additionalparameter to new-navcontainer 
`--env CustomNavSettings=EnableTaskScheduler=true`
Which should do the trick.
I will an option to start the task scheduler in the arm templates (aka.ms/getnav)

**Comment by freddydk** [comment]
Just tried this with a NAV 2018 container and it solves the problem.
