### ISSUE TITLE
Need access to 'ConfigurationPackages' folder from DVD

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/nav-docker#205]
Can we get the contents of the 'ConfigurationPackages' folder from the DVD left on the image? Reason behind this is that the default CRONUS company in the US (and probably CA) version of Business Central does not contain the "extended" data, which means over 6000 of the Microsoft tests automatically fail because of the missing data.

If I have access to the Rapidstart Packages that are in this folder, then I can create a script to create a "CRONUS Extended" company and load in the extended data package.

**Comment by freddydk** [comment]
Sounds like a good idea, I will investigate

**Comment by freddydk** [comment]
Will be included in the next update, which is happening over the next days/week

**Comment by freddydk** [comment]
The latest CU of 2017 and 2018 has the folder.
microsoft/bcsandbox will follow later
bcinsider builds as well.
