### ISSUE TITLE
Issue with ReplaceContainer 'RepoTags' cannot be found on this container

### ISSUE THREAD

**Issue by Ancient13** [Microsoft/nav-docker#206]
Image              bcinsider.azurecr.io/bcsandbox:au
Deployment    Azure
Command       Replace-NavServerContainer -AlwaysPull

**Error::**

% : The property 'RepoTags' cannot be found on this object. Verify that the property exists.
At C:\DEMO\SetupNavContainer.ps1:20 char:31
+ docker images -q --no-trunc | % {
+                               ~~~
    + CategoryInfo          : InvalidOperation: (:) [ForEach-Object], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Microsoft.PowerShell.Commands.ForEachObjectCommand

![image](https://user-images.githubusercontent.com/39933562/40950436-13fbc89c-68b6-11e8-9bc5-df5127a65041.png)

**Comment by freddydk** [comment]
The reason for this bug is in the ARM template, more precise in the c:\demo\SetupNavContainer.ps1, which throws if Set-StrictMode is set to v2.0.
If you need to fix this in a running VM, replace this line:

    if ($inspect.RepoTags | Where-Object { "$_" -eq "$imageName" -or "$_" -eq "${imageName}:latest"}) { $exist = $true }

With this line

    if ($inspect | % { $_.RepoTags | Where-Object { "$_" -eq "$imageName" -or "$_" -eq "${imageName}:latest"} } ) { $exist = $true }

in C:\demo\setupNavContainer.ps1
