### ISSUE TITLE
Issue with Dev Env unable to edit objects in container

### ISSUE THREAD

**Issue by AlphaGeeKUK** [Microsoft/nav-docker#207]
I deployed a server via the ARM templates (aka.ms/getnav), NAV GB CU4.

When I try to edit an object, for example adding a new field 50000 in Customer table, after a long wait the Dev Client displays an error -

---------------------------
Microsoft Dynamics NAV Development Environment
---------------------------
Unable to process table changes because the Microsoft Dynamics NAV Development Environment cannot connect to the specified Microsoft Dynamics NAV Server instance:

Server Name: navserver
Server Instance: nav
Management Port: 7045

Microsoft Dynamics NAV Development Environment will detect a running server automatically.

Check that:
1. The Microsoft Dynamics NAV Server is running
2. The management service is configured
3. The firewall is open for the management port if remote
4. The server is running with only one tenant
5. Microsoft Dynamics NAV Development Environment is running as Administrator, or
6. UAC is turned off.
---------------------------
OK   
---------------------------

How do I fix this?

**Comment by freddydk** [comment]
Database modification using the classic development system requires Windows Authentication - it doesn't work with NavUserPassword.
The default container in aka.ms VMs is NavUserPassword.
Doing classic development, you might want to create another container using windows auth,

**Comment by AlphaGeeKUK** [comment]
I just tried this in a 2018 CU6 GB deployment via the ARM templates (aka.ms/getnav), and I can now edit objects with the classic dev client.

**Comment by freddydk** [comment]
But you still cannot modify tables (I assume).
Nothing really I can do about that.

**Comment by AlphaGeeKUK** [comment]
I can modify tables... any objects are modifiable in a 2018 CU6 GB container as long as my license allows.
