### ISSUE TITLE
NAV 2016

### ISSUE THREAD

**Issue by binhtamn** [Microsoft/nav-docker#208]
I tried to use aka.ms/getnav with microsoft/dynamics-nav:2016 as a parameter for NAV docker image and received this error

3:21:26 AM Initialization of container navserver failed
3:19:11 AM Running microsoft/dynamics-nav:2016 (this will take a few minutes)
....

Thanks
TN

**Comment by freddydk** [comment]
Tried the same - works fine
http://fk2016.westeurope.cloudapp.azure.com/status.aspx

Did you retry the operation?
Wasn't there any more information in the log?
If you connect to the VM and use Docker logs navserver - then you might get more info.

**Comment by binhtamn** [comment]
thanks for your reply but I'm still getting the same error
http://nav2016hydro.australiaeast.cloudapp.azure.com/status.aspx

**Comment by binhtamn** [comment]
I tried 3 times with NZ version, W1 version, and W1 CU18, same error
I managed to create W1 2018 but I need 2016 to simulate my client environment.
this is the thing I got from the event log
The description for Event ID 1 from source docker cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Health check for container 290c65aba78acf074184728f386f265ab7c081bf9882c46da636b3f1f44c1768 error: context cancelled

**Comment by freddydk** [comment]
That error is unrelated, if you can send me the username and password for the VM to freddyk at microsoft dot com – then I can have a look what went wrong.


/Freddy

Fra: binhtamn <notifications@github.com>
Sendt: 7. juni 2018 10:11
Til: Microsoft/nav-docker <nav-docker@noreply.github.com>
Cc: Freddy Kristiansen <Freddy.Kristiansen@microsoft.com>; Comment <comment@noreply.github.com>
Emne: Re: [Microsoft/nav-docker] NAV 2016 (#208)


I tried 3 times with NZ version, W1 version, and W1 CU18, same error
I managed to create W1 2018 but I need 2016 to simulate my client environment.
this is the thing I got from the event log
The description for Event ID 1 from source docker cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event:

Health check for container 290c65aba78acf074184728f386f265ab7c081bf9882c46da636b3f1f44c1768 error: context cancelled

**Comment by binhtamn** [comment]
Thanks F, I will fix the flf file
