### ISSUE TITLE
Pulling image issue.

### ISSUE THREAD

**Issue by SUD-D365** [Microsoft/nav-docker#210]
When I m trying to pull image of **microsft/bcsandbox** I m getting **TLS Handshake timeout** error.
Any solution for this.
I also want to how to define memory limit to 3G through the power shell command. As someone suggested me to set memory limit 3G to container for an another issue with creating a Container for BC-Sandbox.
![image](https://user-images.githubusercontent.com/33481576/41272917-dc8db90e-6e34-11e8-8726-35944506d763.png)

**Comment by freddydk** [comment]
Probably something with your firewall, proxy or like.
The parameter for memory limit is -memorylimit xG

**Comment by SUD-D365** [comment]
I didn't define any proxy and turned off firewall also.
What should be the issue?

**Comment by freddydk** [comment]
have you tried:
docker pull microsoft/windowsservercore

**Comment by SUD-D365** [comment]
Yes freddy its working, I mean its pulling.

**Comment by freddydk** [comment]
Not sure whats wrong, but it is something local to your system.
maybe try docker system prune - or reinstall.
![image](https://user-images.githubusercontent.com/10775043/41275673-f3051780-6e21-11e8-9a92-b223da784734.png)

**Comment by SUD-D365** [comment]
Yes freddy , I don't know what is the issue with my system . Now the **Microsoft/bcsandox** also pulling.
One more thing please see the highlighted value in image, this is the way I m defining the memory limit to the container, is it ok?
![image](https://user-images.githubusercontent.com/33481576/41276014-72d5e3e0-6e40-11e8-92c3-6639f66515fb.png)
Thanks you.

**Comment by freddydk** [comment]
Yes, that looks correct

**Comment by SUD-D365** [comment]
Thanks
