### ISSUE TITLE
Container won't start because something wrong in the database

### ISSUE THREAD

**Issue by elweilando** [Microsoft/nav-docker#211]
Container initialization (with https://github.com/Microsoft/navcontainerhelper) failed during startup.
I think there is something wrong with an object in the database. With another database, the container comes up. Is there a way, to find out in which object?

Error message is:

> Microsoft Dynamics NAV Server is currently not ready to serve requests. Try again later, or contact your system administ
> rator.
> at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
> at <ScriptBlock>, C:\Run\navstart.ps1: line 126
> at <ScriptBlock>, C:\Run\start.ps1: line 107
> at <ScriptBlock>, <No file>: line 1
> 
> 
> TimeGenerated : 6/12/2018 8:30:49 AM
> EntryType     : Error
> Message       : Server instance: NAV
>                 Tenant ID:
>                 <ii>User:
>                 Type: System.InvalidOperationException
>                 Message: <ii>There is an error in XML document (1,
>                 140817).</ii>
>                 StackTrace:
>                      at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddT
>                 enant(NavTenantMountingParameters mountingParameters)
>                      at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.Moun
>                 tDefaultTenant(String databaseServerName, String databaseName,
>                 String databaseUserName, ProtectedDatabasePassword
>                 databasePassword, EncryptionProvider encryptionProvider,
>                 AzureKeyVaultSettings azureKeyVaultSettings, Boolean
>                 verifyServerInstanceKey)
>                      at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddS
>                 ingleLegacyTenant(String databaseServerName, String
>                 databaseName, String databaseUserName,
>                 ProtectedDatabasePassword databasePassword, EncryptionProvider
>                 encryptionProvider, AzureKeyVaultSettings
>                 azureKeyVaultSettings)
>                      at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.Conf
>                 igureTenants(ServerUserSettings settings, String encryptionKey)
>                      at Microsoft.Dynamics.Nav.Runtime.NavTaskFactory.<>c__Disp
>                 layClass11_0.<StartNewTask>b__0()
>                      at System.Threading.Tasks.Task.Execute()
>                 Source: Microsoft.Dynamics.Nav.Ncl
>                 HResult: -2146233079
>                 ----------------------------------
>                 Type: System.InvalidOperationException
>                 Message: <ii>Instance validation error: 'Record' is not a
>                 valid value for DataType.</ii>
>                 StackTrace:
>                      at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerial
>                 izationReaderPageDefinition.Read79_DataType(String s)
>                      at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerial
>                 izationReaderPageDefinition.Read81_DataFieldDefinition(Boolean
>                 isNullable, Boolean checkType)
>                      at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerial
>                 izationReaderPageDefinition.Read97_PageDefinition(Boolean
>                 isNullable, Boolean checkType)
>                      at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerial
>                 izationReaderPageDefinition.Read98_PageDefinition()
>                 Source: Microsoft.GeneratedCode
>                 HResult: -2146233079
>                 </ii>
> 
> TimeGenerated : 6/12/2018 8:30:49 AM
> EntryType     : Error
> Message       : Server instance: NAV
>                 Tenant ID:
>                 <ii>User:
>                 Type: System.InvalidOperationException
>                 Message: <ii>There is an error in XML document (1,
>                 140817).</ii>
>                 StackTrace:
>                      at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddT
>                 enant(NavTenantMountingParameters mountingParameters)
>                      at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.Moun
>                 tDefaultTenant(String databaseServerName, String databaseName,
>                 String databaseUserName, ProtectedDatabasePassword
>                 databasePassword, EncryptionProvider encryptionProvider,
>                 AzureKeyVaultSettings azureKeyVaultSettings, Boolean
>                 verifyServerInstanceKey)
>                      at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddS
>                 ingleLegacyTenant(String databaseServerName, String
>                 databaseName, String databaseUserName,
>                 ProtectedDatabasePassword databasePassword, EncryptionProvider
>                 encryptionProvider, AzureKeyVaultSettings
>                 azureKeyVaultSettings)
>                      at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.Conf
>                 igureTenants(ServerUserSettings settings, String encryptionKey)
>                      at Microsoft.Dynamics.Nav.Runtime.NavTaskFactory.<>c__Disp
>                 layClass11_0.<StartNewTask>b__0()
>                      at System.Threading.Tasks.Task.Execute()
>                 Source: Microsoft.Dynamics.Nav.Ncl
>                 HResult: -2146233079
>                 ----------------------------------
>                 Type: System.InvalidOperationException
>                 Message: <ii>Instance validation error: 'Record' is not a
>                 valid value for DataType.</ii>
>                 StackTrace:
>                      at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerial
>                 izationReaderPageDefinition.Read79_DataType(String s)
>                      at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerial
>                 izationReaderPageDefinition.Read81_DataFieldDefinition(Boolean
>                 isNullable, Boolean checkType)
>                      at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerial
>                 izationReaderPageDefinition.Read97_PageDefinition(Boolean
>                 isNullable, Boolean checkType)
>                      at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerial
>                 izationReaderPageDefinition.Read98_PageDefinition()
>                 Source: Microsoft.GeneratedCode
>                 HResult: -2146233079
>                 </ii>
> 
> Initialization of container name failed
> In C:\develop\name\nav-docker-environment\microsoft-navcontainerhelper\ContainerHandling\Wait-NavContainerRead
> y.ps1:45 Zeichen:17
> + ...             throw "Initialization of container $containerName failed" ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (Initialization ...r specht failed:String) [], RuntimeException
>     + FullyQualifiedErrorId : Initialization of container specht failed

**Comment by freddydk** [comment]
What image are you running?
Are you using your own database?
What command are you using?

**Comment by freddydk** [comment]
Are you using multi-tenancy?

**Comment by elweilando** [comment]
No, no multi-tenancy. 
I'm running microsoft/dynamics-nav:2018-cu1-de
Database is an azure SQL Database.
I'm using the New-Navcontainer cmdlet.
If I connect to another azure SQL Database, it works.

**Comment by freddydk** [comment]
Looking at the log - it looks like something is wrong with the default tenant (singlelegacytenant)

**Comment by elweilando** [comment]
I fixed now with an workaround. I start a container with another database, opened the issue-database with C/SIDE and compile all modified objects.
After that, the container comes up without an issue.
