### ISSUE TITLE
ClickOnce WinClient doesn't start for latest BC build

### ISSUE THREAD

**Issue by tfenster** [Microsoft/nav-docker#212]
if I run one of the latest bcsandbox-master images, install the Windows Client through ClickOnce and try to start it, I get
 
```
System.IO.FileNotFoundException
   bei Microsoft.Dynamics.Framework.UI.Windows.Telemetry.Initialize(Microsoft.Dynamics.Framework.UI.Windows.TelemetryInitialization)
   bei Microsoft.Dynamics.Nav.Client.WinClient.StartWinFormsClient.SetupTelemetry()
   bei Microsoft.Dynamics.Nav.Client.WinClient.StartWinFormsClient.PreRun(Boolean ByRef)
   bei Microsoft.Dynamics.Nav.Client.WinClient.StartWinFormsClient.RunCore()
   bei Microsoft.Dynamics.Nav.Client.WinClient.StartWinFormsClient.Run(Boolean)
   bei Microsoft.Dynamics.Nav.Client.Program.Main(System.String[])
```
 
and the client never starts. I tested 13.0.22621.0 and 13.0.22377.0, both get the same error. I use the following command to start the container (I would guess that not using a transparent network doesn't change the result, but haven't tested)

```
docker run -e accept_eula=y -e clickonce=y --network MyTransparentNetwork --name testwinc --hostname testwinc bcinsider.azurecr.io/bcsandbox-master:us
```

**Comment by freddydk** [comment]
The missing DLL is Microsoft.ApplicationInsights.dll. It is on the docker image - but is not included in the SetupClickOnceDirectory.
As a workaround, you can include it in the file and override it in the c:\run\my folder in the ontainer.
I will create a new generic image asap and the next images will include this.

**Comment by tfenster** [comment]
Tested on 13.0.22913.0 and can confirm that this is fixes. Thanks!
