### ISSUE TITLE
Make ClickOnce AssemblyIdentity unique per Container

### ISSUE THREAD

**Issue by ChrisBlankDe** [Microsoft/nav-docker#213]
In the SetupClickOnce.ps1 the DeploymentIdentityName is set to "$publicDnsName ClickOnce".
This is a problem if i have multible containers on a host and access them with different Ports.
In this case I would have multible ClickOnce Deplyoments from different containers which share the same AssemblyIdentity which is very bad. (I hope I do not have to explain why)

Maybe we can add a guid or the public file share port.
I think this is a general topic and should not be solved by overwriting.

**Comment by freddydk** [comment]
Images are being rebuilt with this fix.
