### ISSUE TITLE
[Question] BCSandbox Build No. / Version Tag

### ISSUE THREAD

**Issue by NAVRockClimber** [Microsoft/nav-docker#215]
Hi,

I am not sure if this is the right repo. But the bcsandbox page on hub.docker.com directed me here. I am a little bit confused how the new build no. / version tags are to be interpreted for the bcsandbox. 

Originally the Version Tags looked like this:
`12.0.22067.0` 
So I just pulled the one with biggest number for having the must current release.

Since about 14 days the Version Tags started to look like this:
`12.0.21405.22535`
Still ok, I just pulled the one with the biggest no.

But now there are tow images created on the same day and the first one in the tag list (if I scroll down)
 got a lower number than the next one also both images are created on the same day.

| Tag Name | Compressed Size | Last Updated|
| ----------- | ------------------- | -------------- |
| 12.0.21405.22529-de | 8 GB | 11 days ago |
| ... | 8 GB | 11 days ago |
| 12.0.21405.22529-de | 8 GB | 11 days ago |
| 12.0.21405.22535-de | 8 GB | 11 days ago |

Can somebody explain the Version tagging to me?
Which of the both images is the newest?

**Comment by freddydk** [comment]
microsoft/bcsandbox is the latest (and in fact the latest is called 12.1.22475.22720-de if you download it now - only one hour old)
Sometimes you will find other images available, some that even might be newer, but unless specifically instructed to use those, please don't.
You cannot use the date for anything - it only tells you when the image was built - and if you pull 2016--cu2-de it is only one week old.
We are building images from multiple branches and you should follow this blog post https://blogs.msdn.microsoft.com/freddyk/2018/04/16/which-docker-image-is-the-right-for-you/ to determine which image to go for.

**Comment by NAVRockClimber** [comment]
Thanks for the quick answer, Freddy! 
Shame on me. I actually did read all your blog posts except this one.

**Comment by freddydk** [comment]
Thanks - and shame on nobody:-)
