### ISSUE TITLE
bcinsider.azurecr.io/bcsandbox-master is a week old

### ISSUE THREAD

**Issue by rdebath** [Microsoft/nav-docker#216]
Is the daily `bcinsider.azurecr.io/bcsandbox-master` currently expected to be seven days old?

**Comment by freddydk** [comment]
That might be, we have had some issues with the daily builds that should be fixed now.
Do you have any specific reason to need a newer build?

**Comment by rdebath** [comment]
I only wanted to check the most recent build before I raised a new AL issue and a week behind seems a bit long. I checked the most recent available.

**Comment by freddydk** [comment]
No problem, you cannot rely on builds to be daily - you can rely on the imagename giving you the latest image available on collaborate we want people to use.

**Comment by freddydk** [comment]
Just checked - there is a new build this morning, which indeed is last nights build.
