### ISSUE TITLE
Setup issues

### ISSUE THREAD

**Issue by 420tech** [Microsoft/nav-docker#218]
When I run this PS script:
New-NavContainer -accept_eula -containerName GFMMS -imageName microsoft/bcsandbox:us -includeCSide -doNotExportObjectsToText -auth NavUserPassword

I get the following error:
Pulling docker Image microsoft/bcsandbox:us
docker : Error response from daemon: Get https://registry-1.docker.io/v2/microsoft/bcsandbox/manifests/us: unauthorized: 
incorrect username or password
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.9.5\ContainerHandling\New-NavContainer.ps1:167 char:9
+         docker pull $imageName
+         ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ...ame or password:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by freddydk** [comment]
maybe try

docker logout
docker pull microsoft/bcsandbox:us

in an administrator DOS prompt.

**Comment by 420tech** [comment]
That worked! Thank you Freddy!
