### ISSUE TITLE
Question: How to authenticate against the container's web service APIs? 

### ISSUE THREAD

**Issue by jhorbulyk** [Microsoft/nav-docker#220]
To the best of my knowledge, the following statements are factually true statements:

- [A container doesn't have its own Active Directory and cannot be joined into an AD.](https://github.com/Microsoft/navcontainerhelper/blob/master/NavContainerHelper.md#setup-windows-authentication-with-the-windows-user-on-the-host-computer) (although [this script which creates Azure Active Directory apps](https://github.com/Microsoft/navcontainerhelper/blob/master/AzureAD/Create-AadAppsForNav.ps1) appears to contradict this slightly.)
- [Authentication against NAV API endpoints must be done by Azure Active Directory](https://docs.microsoft.com/en-us/dynamics-nav/endpoints-apis-for-dynamics) 
- It is possible to authenticate against an API endpoint with windows credentials through something simlar to NTLM which operates bellow the HTTP level but this won't be possible in a production environment.

Which leads to the following question: 
**What is the expected way to authenticate against web service APIs (such as OData) that are exposed by a container?**

Would the following work?
1. Created a Windows VM where the windows users were populated by Active Directory
1. Installed Docker and ran the corresponding commands to set up a Business Central Container where the ports on the container are bound to the ports on the OS.
1. Used the powershell commands to create NAV users which are linked by Windows Authentication to users on the Windows OS which are then transitively linked to AD users.
1. Register OAuth Apps in AD.
1. Have users go through the OAuth login flow, where by providing login credentials to AAD they grant access to the transitively linked Business Central user.

**Comment by tfenster** [comment]
I can't comment on your original question, but the statement about AD definitely is wrong. You definitely can connect a container to AD as described here https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/live/windows-server-container-tools/ServiceAccounts
