### ISSUE TITLE
An error occured while sending the request.

### ISSUE THREAD

**Issue by SUD-D365** [Microsoft/nav-docker#221]
Hi all.
I'm getting below error , when trying to publish the App on BC. Even container is running as I can see a green dot in VS code.
![image](https://user-images.githubusercontent.com/33481576/41789465-0243b1ea-766d-11e8-85a5-c2a0bd165397.png)

Thanks

**Comment by SUD-D365** [comment]
Hi @freddydk  please look in to this issue.
The image **Microsoft/bcsandbox** created container behaving very strange one of the above mention issue is occurring .
Generated **WebClient** shortcut also not working **cant connect error** . But when I open it in private browser window it will ask for credentials and works fine. But when I refresh the tab again its cant connect in private window also.
![image](https://user-images.githubusercontent.com/33481576/41891933-fc4d3044-7933-11e8-8b87-d65eaf35a0e4.png)
When I m trying to publish the app through VScode its not publishing. Below error is occurring.
![image](https://user-images.githubusercontent.com/33481576/41892177-cfa4626e-7934-11e8-8c0f-ade715ea4769.png)

Kind Regards
**Sudarshan**

**Comment by freddydk** [comment]
How did you create your container?
Is your container setup for https?

If I should help, you need to post some more info
1. Docker logs from your container (docker logs <containername>
2. command used to spin up the container

**Comment by SUD-D365** [comment]
**How did you create your container?**
--> Created through the downloaded powershell command from business central , sandbox environment page.
**CreateBCSandbox.ps1** ,
**Is your container setup for https?**
No, its setup on Http , as web client running on Http:// (Very first time when I was able to see).

![image](https://user-images.githubusercontent.com/33481576/41893176-79a3958e-7938-11e8-970f-0db17e6a1cc4.png)

**Docker logs from your container (docker logs **
docker logs -f 36197819028df98be51db4d034b9b1e2640a3f2dfb92994ffb9f0a299fb8b328
Initializing...
Starting Container
Hostname is bctest
PublicDnsName is bctest
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user XYZ
Setting SA Password and enabling SA
Creating SUPER user
Assign Premium plan for BCTEST\XYZ
Container IP Address: xxx.yy.zz.ee
Container Hostname  : bctest
Container Dns Name  : bctest
Web Client          : http://bctest/NAV/
Dev. Server         : http://bctest
Dev. ServerInstance : NAV

Files:
http://bctest:8080/al-0.15.18771.vsix

You are running a container which is 78 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 226 seconds
Ready for connections!
Initializing...
Restarting Container
PublicDnsName unchanged
Hostname is bctest
PublicDnsName is bctest
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Starting NAV Service Tier
Container IP Address: xxx.yy.zz.ee
Container Hostname  : bctest
Container Dns Name  : bctest
Web Client          :
Dev. Server         : http://bctest
Dev. ServerInstance : NAV

Files:
http://bctest:8080/al-0.15.18771.vsix

You are running a container which is 78 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 95 seconds
Ready for connections!


TimeGenerated : 6/25/2018 5:33:43 PM
EntryType     : Error
Message       : Error accessing Website
                Raw Url:
                Url:
                Type:
                Microsoft.Dynamics.Nav.Types.Exceptions.NavNCLArgumentException
                Message: Table connection  for table type CRM must be
                registered using RegisterTableConnection or cmdlet
                New-NAVTableConnection before it can be used.
                StackTrace:
                   at Microsoft.Dynamics.Nav.Client.ConnectionStateManager.Call
                Server[T](BeginCallServerMethod beginCallServerMethod,
                EndCallServerMethod`1 endCallServerMethod, ServerCallOptions
                options) in S:\Depot\NAV\Platform\Client\Shared\Prod.Client.Ser
                viceConnection\ConnectionStateManager.cs:line 151
                   at Microsoft.Dynamics.Nav.Client.ServiceConnection.CallServe
                r[T](BeginCallServerMethod beginCallServerMethod,
                EndCallServerMethod`1 endCallServerMethod) in S:\Depot\NAV\Plat
                form\Client\Shared\Prod.Client.ServiceConnection\ServiceConnect
                ion.cs:line 2012
                   at Microsoft.Dynamics.Nav.Client.ServiceConnectionBase.OpenF
                orm(NavOpenFormArguments& mainForm, NavOpenFormArguments[]&
                subForms) in S:\Depot\NAV\Platform\ClientServerShared\Prod.Type
                s\ServiceConnection\ServiceConnectionBase.cs:line 0
                   at Microsoft.Dynamics.Nav.Client.DataBinder.NstDataAccess.Op
                enForm(LogicalForm mainForm, Collection`1 subForms) in S:\Depot
                \NAV\Platform\Client\Shared\Prod.Client.UI\Databinder\NSTDataAc
                cess.cs:line 1065
                   at Microsoft.Dynamics.Nav.Client.UIPatterns.OnFormOpeningPat
                tern.OpenForm(LogicalForm form) in S:\Depot\NAV\Platform\Client
                \Shared\Prod.Client.UI\UIPatterns\OnFormOpeningPattern.cs:line
                56
                   at System.EventHandler.Invoke(Object sender, EventArgs e)
                   at
                Microsoft.Dynamics.Framework.UI.LogicalForm.BuildForm(Action
                customBuild) in S:\Depot\NAV\Platform\Client\Shared\Prod.Client
                Fwk\Forms\LogicalForm.cs:line 1024
                   at Microsoft.Dynamics.Nav.Client.Builder.NavSessionHelper.Bu
                ildForm(LogicalForm form, Action customBuild) in S:\Depot\NAV\P
                latform\Client\Shared\Prod.Client.UI\Builder\NavSessionHelper.c
                s:line 732
                   at Microsoft.Dynamics.Nav.Client.FormBuilder.PageBuilder.Bui
                ld(MasterPage definition, BindingManager bindingManager,
                UIBuilderContext context) in S:\Depot\NAV\Platform\Client\Share
                d\Prod.Client.Builder\Framework\PageBuilder.cs:line 149
                   at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.
                CreateLogicalForm(MasterPage metadata, FormState formState) in
                S:\Depot\NAV\Platform\Client\Shared\Prod.Client.Builder\Builder
                Session\BuilderSession.cs:line 329
                   at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.
                CreateLogicalForm(Int32 formId, FormState formState, Int32
                retryCounter) in S:\Depot\NAV\Platform\Client\Shared\Prod.Clien
                t.Builder\BuilderSession\BuilderSession.cs:line 276
                   at Microsoft.Dynamics.Nav.Client.NavRunPagePropertyBagInvoke
                dAction.InvokePropertyBagAction(UISession uiSession) in S:\Depo
                t\NAV\Platform\Client\Shared\Prod.Client.UI\NavRunPagePropertyB
                agInvokedAction.cs:line 340
                   at Microsoft.Dynamics.Nav.Client.NavPropertyBagInvokedAction
                Base.InvokeCore(LogicalControl logicalControl, Object state,
                UISession uiSession) in S:\Depot\NAV\Platform\Client\Shared\Pro
                d.Client.UI\NavPropertyBagInvokedActionBase.cs:line 72
                Source: Microsoft.Dynamics.Nav.Client.ServiceConnection--------
                --------------------------
                Type:
                Microsoft.Dynamics.Nav.Types.Exceptions.NavNCLArgumentException
                Message: Table connection  for table type CRM must be
                registered using RegisterTableConnection or cmdlet
                New-NAVTableConnection before it can be used.
                StackTrace:
                   at Microsoft.Dynamics.Nav.Runtime.TableConnectionManager.Get
                CurrentTableConnection[T](TableConnectionType connectionType)
                   at Microsoft.Dynamics.Nav.Runtime.DataAccessSource.GetDataAc
                cessForTable(NCLMetaTable table, Boolean isTemp)
                   at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.Initi
                alizeImpl(Int32 companyToken, TableState sharedTableState,
                SecurityFiltering filtering)
                   at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.Initi
                alize(String companyName, SecurityFiltering filtering)
                   at
                Microsoft.Dynamics.Nav.Runtime.NavRecord..ctor(ITreeObject
                parent, Int32 tableId, NCLMetaTable metaTable, Boolean
                isTemporary, NavRecord sharedTable, String companyName,
                SecurityFiltering securityFiltering)
                   at Microsoft.Dynamics.Nav.BusinessApplication.Record50103.__
                Construct(ITreeObject parent, NCLMetaTable metaTable, Boolean
                isTemporary, NavRecord sharedTable, String companyName,
                SecurityFiltering securityFiltering)
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetaTable.CreateObjectI
                nstance(ITreeObject parent, Boolean isTemporary, NavRecord
                sharedTable, String companyName, SecurityFiltering
                securityFiltering)
                   at
                Microsoft.Dynamics.Nav.Runtime.NavForm.InitializeFromMetadata()
                   at
                Microsoft.Dynamics.Nav.Runtime.NavForm.EnsureMetadataLoaded()
                   at
                Microsoft.Dynamics.Nav.Runtime.NavCompany.RegisterForm(NavForm
                form)
                   at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.Registrate
                DataAccess()
                   at
                Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.Open(NavSession
                session)
                   at Microsoft.Dynamics.Nav.Service.NSService.OpenForm(OpenFor
                mRequest form)
                   at SyncInvokeOpenForm(Object , Object[] , Object[] )
                   at
                System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object
                instance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Ru
                nInTransactionCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Tr
                ansientErrorRetryCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Er
                rorMappingCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                Source: Microsoft.Dynamics.Nav.Ncl





TimeGenerated : 6/25/2018 11:30:09 PM
EntryType     : Error
Message       : Error accessing Website
                Raw Url:
                Url:
                Type:
                Microsoft.Dynamics.Nav.Types.Exceptions.NavNCLArgumentException
                Message: Table connection  for table type CRM must be
                registered using RegisterTableConnection or cmdlet
                New-NAVTableConnection before it can be used.
                StackTrace:
                   at Microsoft.Dynamics.Nav.Client.ConnectionStateManager.Call
                Server[T](BeginCallServerMethod beginCallServerMethod,
                EndCallServerMethod`1 endCallServerMethod, ServerCallOptions
                options) in S:\Depot\NAV\Platform\Client\Shared\Prod.Client.Ser
                viceConnection\ConnectionStateManager.cs:line 151
                   at Microsoft.Dynamics.Nav.Client.ServiceConnection.CallServe
                r[T](BeginCallServerMethod beginCallServerMethod,
                EndCallServerMethod`1 endCallServerMethod) in S:\Depot\NAV\Plat
                form\Client\Shared\Prod.Client.ServiceConnection\ServiceConnect
                ion.cs:line 2012
                   at Microsoft.Dynamics.Nav.Client.ServiceConnectionBase.OpenF
                orm(NavOpenFormArguments& mainForm, NavOpenFormArguments[]&
                subForms) in S:\Depot\NAV\Platform\ClientServerShared\Prod.Type
                s\ServiceConnection\ServiceConnectionBase.cs:line 0
                   at Microsoft.Dynamics.Nav.Client.DataBinder.NstDataAccess.Op
                enForm(LogicalForm mainForm, Collection`1 subForms) in S:\Depot
                \NAV\Platform\Client\Shared\Prod.Client.UI\Databinder\NSTDataAc
                cess.cs:line 1065
                   at Microsoft.Dynamics.Nav.Client.UIPatterns.OnFormOpeningPat
                tern.OpenForm(LogicalForm form) in S:\Depot\NAV\Platform\Client
                \Shared\Prod.Client.UI\UIPatterns\OnFormOpeningPattern.cs:line
                56
                   at System.EventHandler.Invoke(Object sender, EventArgs e)
                   at
                Microsoft.Dynamics.Framework.UI.LogicalForm.BuildForm(Action
                customBuild) in S:\Depot\NAV\Platform\Client\Shared\Prod.Client
                Fwk\Forms\LogicalForm.cs:line 1024
                   at Microsoft.Dynamics.Nav.Client.Builder.NavSessionHelper.Bu
                ildForm(LogicalForm form, Action customBuild) in S:\Depot\NAV\P
                latform\Client\Shared\Prod.Client.UI\Builder\NavSessionHelper.c
                s:line 732
                   at Microsoft.Dynamics.Nav.Client.FormBuilder.PageBuilder.Bui
                ld(MasterPage definition, BindingManager bindingManager,
                UIBuilderContext context) in S:\Depot\NAV\Platform\Client\Share
                d\Prod.Client.Builder\Framework\PageBuilder.cs:line 149
                   at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.
                CreateLogicalForm(MasterPage metadata, FormState formState) in
                S:\Depot\NAV\Platform\Client\Shared\Prod.Client.Builder\Builder
                Session\BuilderSession.cs:line 329
                   at Microsoft.Dynamics.Nav.Client.FormBuilder.BuilderSession.
                CreateLogicalForm(Int32 formId, FormState formState, Int32
                retryCounter) in S:\Depot\NAV\Platform\Client\Shared\Prod.Clien
                t.Builder\BuilderSession\BuilderSession.cs:line 276
                   at Microsoft.Dynamics.Nav.Client.Actions.NavOpenTaskPageActi
                on.CreateForm(UISession uiSession, NavBindingManager
                parentBindingManager, FormState formState) in S:\Depot\NAV\Plat
                form\Client\Shared\Prod.Client.UI\Actions\FormActions\NavOpenTa
                skPageAction.cs:line 475
                   at Microsoft.Dynamics.Nav.Client.Actions.NavOpenTaskPageActi
                on.InvokeCore(LogicalControl logicalControl, Object state,
                UISession uiSession) in S:\Depot\NAV\Platform\Client\Shared\Pro
                d.Client.UI\Actions\FormActions\NavOpenTaskPageAction.cs:line
                366
                   at Microsoft.Dynamics.Framework.UI.LogicalAction.DoInvoke(Lo
                gicalControl logicalControl, IDictionary state, UISession
                uiSession) in S:\Depot\NAV\Platform\Client\Shared\Prod.ClientFw
                k\Actions\LogicalAction.cs:line 497
                   at Microsoft.Dynamics.Framework.UI.UX2006.NavigationService.
                NavigateToNode(LogicalControl logicalControl, NavigationNode
                node) in S:\Depot\NAV\Platform\Client\Shared\Prod.Client.UX2006
                \NavigationService.cs:line 190
                   at Microsoft.Dynamics.Framework.UI.LogicalAction.DoInvoke(Lo
                gicalControl logicalControl, IDictionary state, UISession
                uiSession) in S:\Depot\NAV\Platform\Client\Shared\Prod.ClientFw
                k\Actions\LogicalAction.cs:line 497
                   at Microsoft.Dynamics.Framework.UI.InvokeActionInteraction.I
                nvokeCore(InvokeActionInteractionInput
                invokeActionInteractionInput) in S:\Depot\NAV\Platform\Client\S
                hared\Prod.ClientFwk\Interactions\LogicalInteractions\InvokeAct
                ionInteraction.cs:line 89
                   at Microsoft.Dynamics.Framework.UI.InteractionInvoker.Invoke
                [T](String interactionName, Action`1 invokeMethod, T input) in
                S:\Depot\NAV\Platform\Client\Shared\Prod.ClientFwk\Interactions
                \InteractionInvoker.cs:line 42
                   at
                Microsoft.Dynamics.Framework.UI.LogicalInteraction`1.Invoke(T
                logicalInteractionInput) in S:\Depot\NAV\Platform\Client\Shared
                \Prod.ClientFwk\Interactions\LogicalInteraction.cs:line 40
                   at Microsoft.Dynamics.Framework.UI.InteractionManager.<>c__D
                isplayClass8_0.<InvokeInteractions>b__3() in S:\Depot\NAV\Platf
                orm\Client\Shared\Prod.ClientFwk\Interactions\InteractionManage
                r.cs:line 125
                Source: Microsoft.Dynamics.Nav.Client.ServiceConnection--------
                --------------------------
                Type:
                Microsoft.Dynamics.Nav.Types.Exceptions.NavNCLArgumentException
                Message: Table connection  for table type CRM must be
                registered using RegisterTableConnection or cmdlet
                New-NAVTableConnection before it can be used.
                StackTrace:
                   at Microsoft.Dynamics.Nav.Runtime.TableConnectionManager.Get
                CurrentTableConnection[T](TableConnectionType connectionType)
                   at Microsoft.Dynamics.Nav.Runtime.DataAccessSource.GetDataAc
                cessForTable(NCLMetaTable table, Boolean isTemp)
                   at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.Initi
                alizeImpl(Int32 companyToken, TableState sharedTableState,
                SecurityFiltering filtering)
                   at Microsoft.Dynamics.Nav.Runtime.RecordImplementation.Initi
                alize(String companyName, SecurityFiltering filtering)
                   at
                Microsoft.Dynamics.Nav.Runtime.NavRecord..ctor(ITreeObject
                parent, Int32 tableId, NCLMetaTable metaTable, Boolean
                isTemporary, NavRecord sharedTable, String companyName,
                SecurityFiltering securityFiltering)
                   at Microsoft.Dynamics.Nav.BusinessApplication.Record50101.__
                Construct(ITreeObject parent, NCLMetaTable metaTable, Boolean
                isTemporary, NavRecord sharedTable, String companyName,
                SecurityFiltering securityFiltering)
                   at Microsoft.Dynamics.Nav.Runtime.NCLMetaTable.CreateObjectI
                nstance(ITreeObject parent, Boolean isTemporary, NavRecord
                sharedTable, String companyName, SecurityFiltering
                securityFiltering)
                   at
                Microsoft.Dynamics.Nav.Runtime.NavForm.InitializeFromMetadata()
                   at
                Microsoft.Dynamics.Nav.Runtime.NavForm.EnsureMetadataLoaded()
                   at
                Microsoft.Dynamics.Nav.Runtime.NavCompany.RegisterForm(NavForm
                form)
                   at Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.Registrate
                DataAccess()
                   at
                Microsoft.Dynamics.Nav.Service.NSFormBatchOpen.Open(NavSession
                session)
                   at Microsoft.Dynamics.Nav.Service.NSService.OpenForm(OpenFor
                mRequest form)
                   at SyncInvokeOpenForm(Object , Object[] , Object[] )
                   at
                System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object
                instance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Ru
                nInTransactionCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Tr
                ansientErrorRetryCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.<>
                c__DisplayClass25_0.<Combine>b__1(NSServiceBase
                serviceInstance, Object[] inputs, Object[]& outputs)
                   at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.Er
                rorMappingCombinator(ServiceOperation innerOperation,
                NSServiceBase serviceInstance, MethodBase syncMethod, Object[]
                inputs, Object[]& outputs)
                Source: Microsoft.Dynamics.Nav.Ncl





TimeGenerated : 6/26/2018 2:54:50 AM
EntryType     : Error
Message       : Server instance: NAV
                Tenant: nav-systemapplication
                <ii>Tenant ID: nav-systemapplication
                The connection to SQL server could not be established
                Database server: LOCALHOST\SQLEXPRESS
                Database name: FinancialsUS.</ii>



Initializing...
Restarting Container
PublicDnsName unchanged
Hostname is bctest
PublicDnsName is bctest
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Starting NAV Service Tier
Container IP Address: xxx.yy.zz.ee
Container Hostname  : bctest
Container Dns Name  : bctest
Web Client          :
Dev. Server         : http://bctest
Dev. ServerInstance : NAV

Files:
http://bctest:8080/al-0.15.18771.vsix

You are running a container which is 79 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 89 seconds
Ready for connections!

**command used to spin up the container**
I m spinning up it through **Kitematic**.
And through **docker start container** command.

Please let me know if u want any other detail.

Thanks

**Comment by freddydk** [comment]
It seems like something is wrong with a CRM connection in BC - did you try to setup CRM connection or like?

In the CreateBcSandbox.ps1 script, please remove the version number in the imagename, so that you use:

`$imagename = "microsoft/bcsandbox:<country>"
`
Then run again (it will delete the container and re-create it).

**Comment by SUD-D365** [comment]
**It seems like something is wrong with a CRM connection in BC - did you try to setup CRM connection or like?**
Yes I have integrated BC with D365 for sales, and validate settings also. its was working fine.

**In the CreateBcSandbox.ps1 script, please remove the version number in the imagename, so that you use:
$imagename = "microsoft/bcsandbox:<country>"**

will it download latest image of BCsandbox? then why the downloaded powershell command mention the version number in it?

**Comment by freddydk** [comment]
The downloaded powershell script will create an image with the same version number as your online tenant, removing the version number will get the latest (maybe your online tenant is already updated as well).
On the logs I can also see that you restarted the container - so maybe your CRM connection fails when the container is restarted (longshot, but worth trying).

**Comment by SUD-D365** [comment]
@freddydk  okkk. It will download the latest image.
See!!! What I found 

I just run the RTC client from the location **C:\ProgramData\NavContainerHelper\Extensions\bctest\Program Files\120\RoleTailored Client**
and then I click on **Select Server** from Role center, I got an error message stating like this.
**Microsoft Dynamics NAV
---------------------------

Access to the configuration file at C:\ProgramData\NavContainerHelper\Extensions\bctest\Program Files\120\RoleTailored Client\ClientUserSettings.config returns an unauthorized access error.
---------------------------
OK
---------------------------**
It is similar to the issue I am getting when publishing the app.

Then I go to the given path in error and then add my current user with permission on the folder.
What next!! I just click on Web client link and it is working ,also able to publish the app.

What was the exact issue still confuse!!!
Can you relate this solution with the issue?

**Comment by freddydk** [comment]
Are you not an administrator on your box?

**Comment by SUD-D365** [comment]
Yes, I m administrator on my box.

Now again getting error. 
![image](https://user-images.githubusercontent.com/33481576/41911512-7c3707ea-796a-11e8-92d6-664a1d8cf06d.png)
I couldn't understand what is actual issue. :(

**Comment by freddydk** [comment]
When using Windows Authentication you need to be able to contact the domain controller - cached credentials doesn't work with Docker.
You can also use gMSA with Windows Auth.
If you are not on the network (either direct or using VPN), you should use NavUserPassword authentication.
add -auth NavUserPassword to your new-navcontainer - and change authentication in VS Code to UserPassword.

**Comment by SUD-D365** [comment]
So, final solution is to create new container again. Ok I will.
Should I define auth NavUserPassword here?
![image](https://user-images.githubusercontent.com/33481576/41911881-882f4232-796b-11e8-92de-297e63ceb7ce.png)
Any thing else need to define in command?

**Comment by freddydk** [comment]
Your get-credential could have a different text - but no, I think that should be sufficient.

**Comment by SUD-D365** [comment]
Okk @freddydk  will get back to you, let me reinitiate the creation of new container.
Thanks

**Comment by SUD-D365** [comment]
@freddydk  Yes. The NavUserPassword auth is working for me for now. No issue yet.

What is about this message?
![image](https://user-images.githubusercontent.com/33481576/41963814-22870f40-7a16-11e8-9631-e289e9685ede.png)
 
Thanks

**Comment by freddydk** [comment]
Don't know - probably some message because you importest test users.
Try: Choose refresh all User Groups action in the Users Window.

**Comment by SUD-D365** [comment]
Okk @freddydk  Thanks.
