### ISSUE TITLE
Windows Client won't start up inside Azure VM (and other finicky behavior)

### ISSUE THREAD

**Issue by ajansari** [Microsoft/nav-docker#222]
After completing a successful deployment of NAV 2018 CU6 NA using the dev branch of aka.ms/getnav, I imported our NAV license (using the NavContainerHelper to copy the license file, and then the navserver PowerShell to import the license to the NAV server instance. Then I proceeded to download and install SQL Management Studio on the Azure VM. After it installed, a restart was required.

After the restart, the VM was working fine, but the NAV Windows Client shortcut, the Web Client and the ClickOnce client refused to work. I would be taken to the O365 login prompt and after authenticating, I got a failure to connect message. I restarted the NST from navserver PowerShell and ran IISRESET, but that didn't help. I ran Test-Navcontainer in the NavContainerHelper, and it returned a TRUE result.

I shut down and restarted the entire Azure VM, and now the Web Client and the ClickOnce client are working. But the Windows Client inside the Azure VM still refuses to launch. I double-click and nothing happens. The Event log shows two errors and one information entry on each failed attempt.

I had this issue some months ago on another NAV on Docker instance, and at that time, I had been active poking and prodding, so I thought I'd messed something up. But this time, as described above, I haven't done anything out of the ordinary, so I am surprised why the image is being so finicky. 

Event log files for the failed launch of the Windows Client inside the Azure VM are attached below.

<img width="769" alt="001" src="https://user-images.githubusercontent.com/26412023/41802809-57903ff2-7649-11e8-8e51-c216ae773fc7.PNG">

<img width="771" alt="002" src="https://user-images.githubusercontent.com/26412023/41802817-5ec850de-7649-11e8-97a6-b8fdc58dda5c.PNG">

<img width="766" alt="003-01" src="https://user-images.githubusercontent.com/26412023/41802820-654d9acc-7649-11e8-8d63-6891d54da95f.PNG">

<img width="793" alt="003-02" src="https://user-images.githubusercontent.com/26412023/41802821-68b95778-7649-11e8-8824-0c6b4851f4ee.PNG">

**Comment by ajansari** [comment]
I'll try it now.

**Comment by ajansari** [comment]
Running Windows updates. I've been wondering: Is it possible that installing SQL Management Studio 17.8 may have had anything to do with it? It seems unlikely, but worth asking.

**Comment by freddydk** [comment]
Unlikely.
The images are recently built on a new WindowsServerCore and since we are running process isolation then it will share pieces of the OS with the host and if the host (the Azure VM) isn't updated (as the container) it could cause some strange things.

**Comment by freddydk** [comment]
A few things (and a bug)
The best way to import a license to an Azure VM created by aka.ms/getnav is to specify the license file as a secure URL in the license field in the template (dropbox or azure storage are great for secure urls - see https://blogs.msdn.microsoft.com/freddyk/2017/02/26/create-a-secure-url-to-a-file/)
If you forget that, start the navcontainerhelper powershell prompt and use Import-NavContainerLicense, it should do things correctly.
Back to the bug
If you have a container using AAD authentication and you have used -includecside to copy client bits to the host, then clientusersettings.config is updated upon container restart and the ACSUri field is cleared - meaning that you cannot authenticate.
I will fix the bug, but in the meantime, you can edit the file (C:\ProgramData\NavContainerHelper\Extensions\navserver\Program Files\110\RoleTailored Client\ClientUserSettings.config)and set ACSUri to 

`https://login.windows.net/Common/wsfed?wa=wsignin1.0%26wtrealm=https://<publicdnsname>/NAV/%26wreply=https://<publicdnsname>/NAV/`

where <publicdnsname> is the dnsname of your VM.
That should make it work until your next reboot.

**Comment by freddydk** [comment]
fixed in navcontainerhelper 0.2.9.7
https://www.powershellgallery.com/packages/navcontainerhelper/0.2.9.7
testing the fix on http://aka.ms/getnav2 now.

**Comment by freddydk** [comment]
BTW - I will also update the long list of commands when you start navcontainerhelper in the near future.

**Comment by freddydk** [comment]
https://aka.ms/getnav updated with this fix as well.
Note that getnav also has an option to Create all users in your Aad as users in NAV now (for demo purposes) and the LetsEncrypt option is now only one field - if you specify an email address, you automatically say yes.
