### ISSUE TITLE
Installing Apps from APP STORE onto Docker Image in Azure

### ISSUE THREAD

**Issue by Ancient13** [Microsoft/nav-docker#223]
Hi

Can I check if this is supported as I could imagine customers wanting to test app installation on a sandbox before going to production plus partners need to test there extensions.

The AU image - bcinsider.azurecr.io/bcsandbox:au  
build        AU Dynamics NAV 12.2 (22782)

Errors out.

Could not load file or assembly 'Microsoft.Dynamics.Nav.ExtensionProxySvc.Client, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

**Comment by freddydk** [comment]
You cannot install apps from appsource in a container - you need to have the app file and publish/install the app using powershell or you can deploy directly from VS Code.
This way you can setup daily automated deployments using containers.
