### ISSUE TITLE
Could not load type 'MockTest.MockAzureKeyVaultSecret.MockAzureKeyVaultSecretProvider.'MockTest, Version=1 2.2.0.0, Culture=neutral, PublicKeyToken=null''

### ISSUE THREAD

**Issue by kine** [Microsoft/nav-docker#225]
Hello,
I am using the insider bcpreview image and I am not able to compile the Test toolkit objects after the container is created.

I am getting this:

````
Could not load type 'MockTest.MockAzureKeyVaultSecret.MockAzureKeyVaultSecretProvider.'MockTest, Version=1
2.2.0.0, Culture=neutral, PublicKeyToken=null''. -- Object: Codeunit 131021 Library - Azure KV Mock Mgmt.
[23462397] You have specified an unknown variable.
MockAzureKeyVaultSecretProvider
Define the variable under 'Global C/AL symbols'. -- Object: Codeunit 131021 Library - Azure KV Mock Mgmt.
````

I am using this command to compile the objects to be able to download symbols including the toolkit:
````
    Compile-ObjectsInNavContainer -containerName $ContainerName -filter "Version List=*Test*" 
````

**Comment by tfenster** [comment]
If it just is about getting the symbols, I am downloading from 

`https://hostname:7049/NAV/dev/packages?publisher=Microsoft&appName=Test&versionText=12.0.0.0`

Or do you specifically need to compile?

**Comment by kine** [comment]
Yes, I need symbols for the Test Toolkit. And they are not part of the symbols until you compile the objects with the parameter to generate symbols.

**Comment by tfenster** [comment]
Are you sure? I just import the fobs and the download the .app file through the URL above without needing to compile

**Comment by freddydk** [comment]
if you use navcontainerhelper - start the container with -enableSymbolLoading and -includeCside - then it automatically will create symbols when importing

**Comment by freddydk** [comment]
And if you don't use navcontainerhelper, you can add the generatesymbols parameter to your import, no need to compile.

**Comment by tfenster** [comment]
For me the following works without compiling or generatesymbols

```
Get-ChildItem -Path "C:\TestToolKit\*.fob" | foreach { 
    $objectsFile = $_.FullName
    Import-NAVApplicationObject -Path $objectsFile `
                                -DatabaseName $databaseName `
                                -DatabaseServer $databaseServer `
                                -ImportAction Overwrite `
                                -SynchronizeSchemaChanges Force `
                                -NavServerName localhost `
                                -NavServerInstance NAV `
                                -NavServerManagementPort 7045 `
                                -Confirm:$false
}
 
$testURL = 'https://'+$hostname+':7049/NAV/dev/packages?publisher=Microsoft&appName=Test&versionText='+$release
Invoke-RestMethod -Method Get  `
                  -Uri ($testURL)  `
                  -Headers $headers  `
                  -OutFile 'c:\ForBuildStage\symbols\Test.app'
```

Am I missing something?

**Comment by freddydk** [comment]
I don't think you get symbols from the objects you import - do you?

**Comment by tfenster** [comment]
I do get a Test.app file and was assuming that it is from the TestToolKit fobs. I'll check what exactly is in there

**Comment by freddydk** [comment]
Check whether you have the assert codeunit in VSCode?

**Comment by kine** [comment]
I am using enableSymbolLoading when creating the container but the toolkit objects imported through includeTestToolkit are not available in the symbols. Thus I am recompiling them to get them.

**Comment by kine** [comment]
May be old version used? Right now having NavContainerHelper version 0.2.8.5

**Comment by freddydk** [comment]
I fixed this in 0.2.9.5 - https://www.powershellgallery.com/packages/navcontainerhelper/0.2.9.5

**Comment by kine** [comment]
Ok, do not need to recompile now... but still, is the dll missing?

**Comment by freddydk** [comment]
There are objects using .net DLLs that cannot compile in docker. For this particular one - I am not sure what is missing or whether it is something we should have in there - I don't think so but I will ask around.

**Comment by tfenster** [comment]
Ok, here is my test:

1. Create a plain NAV Container, just docker run with no scripts or anything. Windows auth to avoid any username/password stuff
```
docker run -e accept_eula=y -e auth=Windows -e username=tfenster -e password=xxx --name testtfe --hostname testtfe microsoft/bcsandbox
```
result
```
Initializing...
Starting Container
Hostname is testtfe
PublicDnsName is testtfe
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user tfenster
Setting SA Password and enabling SA
Creating SUPER user
Container IP Address: 172.29.185.105
Container Hostname  : testtfe
Container Dns Name  : testtfe
Web Client          : http://testtfe/NAV/
Dev. Server         : http://testtfe
Dev. ServerInstance : NAV

Files:
http://testtfe:8080/al-0.16.16948.vsix

Initialization took 83 seconds
Ready for connections!
```

2. Try to download test symbols
```
iwr -uri "http://testtfe:7049/NAV/dev/packages?publisher=Microsoft&appName=Test&versionText=12.0.0.0" -usebasicparsing -outfile test.app -UseDefaultCredentials
```
This gives me a test.app file, so it seems something is already there?

3. Connect a hello world project against it and configure test support in app.json
```
{
  ...
  "test": "12.0.0.0"
}
``` 

4. Download symbols and then try to use Assert
```
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        Assert: Codeunit Assert;
    begin
        Assert.Fail('This does not work');
    end;
}
```
Compiling works, so it seems to be part of the symbols file. But running this results in the following error:
```
Das Objekt vom Typ CodeUnit mit der ID 130000 wurde nicht gefunden.
--> translation is something like "The object of type Codeunit with ID 130000 was not found"
Page Customers has to close
```

If I use C/SIDE to look into the database I see that Codeunit 130000 indeed isn't there. So maybe because of the test objects which are already in the Cronus database (130400..) the symbols are there?

**Comment by tfenster** [comment]
And of course if I then import the test toolkit fobs, it works for me. The symbols already were available before the import and the objects after the import are also available

**Comment by freddydk** [comment]
So apparently, there is a bug, which saves you (you are lucky:-))
The symbols generated from the build process leaves these things there.
In order to do hybrid development you need to add -e enableSymbolLoading=Y to your docker run.
Now the symbols probably disappear - but this is needed if you change other things in C/AL.
When you import objects you need to set generatesymbols=1 for finsql.
Import-NavApplicationObject unfortunately do not have a generatesymbols, so you need to use finsql directly (or use the same hack as I did here https://github.com/Microsoft/navcontainerhelper/blob/dev/ObjectHandling/Import-TestToolkitToNavContainer.ps1 while waiting for a bugfix).

**Comment by tfenster** [comment]
ok, lesson learned :) Thanks

**Comment by gintuoklis** [comment]
> There are objects using .net DLLs that cannot compile in docker. For this particular one - I am not sure what is missing or whether it is something we should have in there - I don't think so but I will ask around.

Did you find out what DLLs is needed for compiling those AutoTest objects?
