### ISSUE TITLE
NAV local container - webclient works, windows client doesn't, nor AL:GO, download symbols

### ISSUE THREAD

**Issue by robertosb** [Microsoft/nav-docker#227]
Hello,

   Has anyone had any issues on a local machine with docker/business central containers?
   If not, what would you suggest around how I can investigate this one. To me it looks like some ports are blocked for all my containers, except 8080 for web client. How could I resolve this?

   I know the script to download a image works fine in an azure VM, also allowing me to connect to download symbols from VS Code, but when I do it in my local machine, I can only access the web client, while windows client is not accessible, nor the Symbols download where it fails with:
"[2018-07-03 12:56:59.52] Using reference symbols cache path: c:\Users\RobertB\Documents\AL\ALProject6\./.alpackages
[2018-07-03 12:56:59.52] Sending request to http://server3:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=12.0.0.0
[2018-07-03 12:56:59.52] Sending request to http://server3:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=12.0.0.0
[2018-07-03 12:56:59.70] Error: An error occurred while sending the request.
The remote server returned an error: (401) Unauthorized.
The system cannot contact a domain controller to service the authentication request. Please try again later

[2018-07-03 12:56:59.70] Error: An error occurred while sending the request.
The remote server returned an error: (401) Unauthorized.
The system cannot contact a domain controller to service the authentication request. Please try again later"
Further details:

![image](https://user-images.githubusercontent.com/39469150/42192844-85a284bc-7ebf-11e8-8a76-7256c0c3ac25.png)

Script to install container which is running successfully on 7045-7049 ports:
"install-module navcontainerhelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true

$containername = 'Server3'
$navdockerimage = 'microsoft/bcsandbox:us'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth Windows `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
				 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password"

![image](https://user-images.githubusercontent.com/39469150/42193013-5dba9876-7ec0-11e8-8c02-feced8f7c1a2.png)

Thank you in advance,
Robert

**Comment by freddydk** [comment]
VS Code actually tells you very clearly what the problem is.
Cannot contact the domain controller. Windows Auth doesn't work with cached credentials.
You can try to change authentication to NavUserPassword in the script (and UserPassword in VSCode).
When you re-run the script it will remove and re-create the container.

**Comment by robertosb** [comment]
HI Freddy, what I did I re-ran the script and used my exact windows password, which then worked running the windows client as well, but not connecting my app.
I will do as you say, I think it's also a good idea.

**Comment by freddydk** [comment]
VSCode also might have cached credentials - you can try AL: Clear Credentials Cache

**Comment by robertosb** [comment]
thank you, I tried that already both before and after using the same password as in Windows.

**Comment by robertosb** [comment]
would this do, so I don't get it wrong? "install-module navcontainerhelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true

$containername = 'Server4'
$navdockerimage = 'microsoft/bcsandbox:us'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using NavUserPassword. Please enter your credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth NavUserPassword `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
				 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password
"

**Comment by robertosb** [comment]
Yes this worked, thank you Freddy, we can close this one.
