### ISSUE TITLE
microsoft/bcsandbox missing data

### ISSUE THREAD

**Issue by ernestasju** [Microsoft/nav-docker#228]
I have noticed that Docker image for Business Central has no data in it.
Is this intended?

Docker image version: 12.2.22932.23097.

Database: FinancialsW1.
Company: My Company.

Command for creating the container:
```
docker run -it --name mytest -h mytest -m 4g -e accept_eula=Y microsoft/bcsandbox
```

**Comment by lhtan-dev** [comment]
Creating a new company starting with CRONUS name and selecting sample data seems to do the trick. However it installs the GB evaluation data. Anyone knows how to select other country evaluation data?

**Comment by f4nx** [comment]
I have the same problem as @ernestasju and tried your suggested trick but it didn't work because the rapidstart packages weren't provided. Could you please explain? Thank you @lhtan-dev

**Comment by lhtan-dev** [comment]
Hi @f4nx , sharing the screenshots of the steps I took. Is it similar? 
![demo data issue - 1](https://user-images.githubusercontent.com/17727792/43049371-c4636b94-8dab-11e8-9641-8a0d1c0aa977.PNG)
![demo data issue - 2](https://user-images.githubusercontent.com/17727792/43049372-c47b381e-8dab-11e8-97ec-e43645c6c5b1.PNG)
![demo data issue - 3](https://user-images.githubusercontent.com/17727792/43049373-c48d0026-8dab-11e8-8663-1dc1e91e52a2.PNG)

**Comment by f4nx** [comment]
Hi, I guess the language in the settings on the web client was an issue. The package has been imported successfully. It is like you said the GB version. Thank you.

**Comment by freddydk** [comment]
If you use microsoft/bcsandbox:base, then you will get w1 demo data.
base is the foundation of all languages and will contain the on-prem w1 db.
master insider builds with :w1 will contain the saas demo data.

**Comment by naveksa** [comment]
Sorry, did not observe that this issue was closed.
Comments above moved to new issue #288
