### ISSUE TITLE
microsoft/bcsandbox internal error

### ISSUE THREAD

**Issue by josnelissen** [Microsoft/nav-docker#229]
After running extension (F5) from Visual Studio Code I get an internal error.
But when opening the web client I see the extension is published and working

Docker image version: 12.2.22932.23097-NL
Database: FinancialsNL
Visual Studio Code Version: 1.25.0
AL Language version: 0.16.19969
![alcode error](https://user-images.githubusercontent.com/30867508/42453783-1550c948-838e-11e8-9dc3-523c7e185623.png)

**Comment by imranebs** [comment]
We have the same issue with the latest image.

**Comment by mitrov** [comment]
Same here

Using Build 12.2.22932.23097 (CH)

**Comment by freddydk** [comment]
This is a problem with the debugger. If you use Ctrl+F5 it will deploy and run.
This is being looked on - but it is unrelated to docker.

**Comment by freddydk** [comment]
This should be fixed with the latest images.
