### ISSUE TITLE
Untrusted domain when accessing CSIDE

### ISSUE THREAD

**Issue by TheDenSter** [microsoft/nav-docker#230]
According to [this issue](https://github.com/Microsoft/nav-docker/issues/207) the only way to make CSIDE available for modifying objects is to use Windows authentication in your containers. From a local VM I created a container with Windows authentication, here's the script:
![image](https://user-images.githubusercontent.com/23434319/42478812-fa3aed62-838a-11e8-815b-9dae6a668d26.png)

When I try to open CSIDE, it gives me an 'untrusted domain' error:
![image](https://user-images.githubusercontent.com/23434319/42478594-1b5b5cd0-838a-11e8-8b76-570d0184055c.png)
I used the same script to create the same container on an Azure VM (created with the aka.ms/bcsandbox template), and in there it does work. What do I need to change to make this work on a local VM?

For me personally it's not relevant because I don't have any CSIDE work at the moment but asking for a friend ;) I swear I've always been able to modify objects in CSIDE, and I generally only use UserPassword containers. I was totally surprised by this, so now I have to know :)

As an aside - I would like to know why I can use the object cmdlets in navcontainerhelper on a UserPassword container, but it does not let me modify objects from CSIDE. I'm confused how the Cmdlets don't seem to need Windows authentication but CSIDE does?

**Comment by freddydk** [comment]
The problem is Windows authentication, since containers are not joined to the domain, the host needs to be able to connect to the AD server, containers cannot live of cached credentials. I need to VPN to corpnet in order for Windows auth to work on my laptop.
Azure VMs are not connected to an AD server (they have their own AD you can say) and as such always works.

**Comment by TheDoubleH** [comment]
@freddydk - Before I go ahead and do this, are You saying that if I make my Server 2016 Hyper-V a Domain Controller it would work? Or am I missing something?

**Comment by TheDenSter** [comment]
As a test I just created a new UserPassword container, added a field to the Customer table in CSIDE, and saved the object without compiling. Then I used the PowerShell compile Cmdlet and that completed successfully. Here's the script that worked for me:
![image](https://user-images.githubusercontent.com/23434319/42526012-7f50faac-8429-11e8-8334-5e534da3514a.png)

I still don't understand though, why one thing does and another thing does not work in UserPassword container. Both my local VM and my laptop are in a workgroup, not a domain. If the Azure VM works because they are not connected to an AD server then my setup should also work. Am I getting it backward?

**Comment by tfenster** [comment]
@TheDenSter I think compiling is not the problem, but syncing the changes. As far as I know, when C/SIDE needs to sync tables, it connects to the mgmt service (7045). That service however is only able to handle Win Auth, so if you just try to connect with NavUserPassword, that fails (see https://www.axians-infoma.de/navblog/using-ad-accounts-in-containerized-nav-and-what-i-learned-on-the-way/ for an old but on that part probably still correct log analysis). You have three ways around that:

1. Use gMSAs to do something similar to a domain join for your container. Afterwards Win Auth works
1. Use the same username and password on both host and container. With that setup Win Auth also works as the container is not in a domain, so it only looks at username and password during authentication without caring about the domain.
1. Get a session into your container and call compile-navapplicationobjects there which in turn also calls sync-navtenant. As all this is happening inside the container and with a local container user, WinAuth also works. This is what compile-objectsinnavcontainer does and why it always works

I hope that a) this makes sense and b) I am correct :) @freddydk am I missing something?

**Comment by TheDenSter** [comment]
I think the navcontainerhelper's compile Cmdlet calls the regular NAV Cmdlet, which would mean that my script has the same effect as your suggestion 3 without having to open a session, and it works without Windows auth. This is why this confuses me so much because 'normal' (meaning locally installed) CSIDE does not need Windows auth to save/compile objects, and effectively by saving without compile and then issuing a PowerShell compile command, that all does work without Windows auth. 

The only thing that appears to be an issue is the compile step when saving in CSIDE. Even more confusing, that DOES work in an Azure VM but not locally, and I can't find a difference in setup between the two. I know next to nothing about this though, so I am probably looking in all the wrong places :)

Then to make it even more confusing, Windows auth does work in Azure vm but not in my local vm, even though neither one is connected to any domain controller... The workaround does work, but I still don't understand why this is happening

**Comment by freddydk** [comment]
Tobias is right on all points - CSIDE tries to connect to 7045 which fails. He also states that Compile-ObjectsInNavContainer does exactly open a session and call compile-navapplicationobject.
And FYI - Windows Auth works locally for me (when I am VPN'ed into corpnet).

**Comment by tfenster** [comment]
compile-objectsinnavcontainer does open a session, see [here](https://github.com/Microsoft/navcontainerhelper/blob/master/ObjectHandling/Compile-ObjectsInNavContainer.ps1#L27-L28). If you set up the Azure VM through one of Freddys templates, then you have the same Windows user in the VM and in the container, so this works because of 2).
