### ISSUE TITLE
How to pull docker developer-preview for June

### ISSUE THREAD

**Issue by alanb999** [Microsoft/nav-docker#231]
I am unable to pull the recent docker image for June NAV developer-preview using either of the following image names (error messages indicate file not found).
docker pull "bcinsider.azurecr.io/dynamics-nav:13.0.22895.0-us"
docker pull "bcinsider.azurecr.io/dynamics-nav:13.0.22895.0"
docker pull "bcinsider.azurecr.io/dynamics-nav:devpreview-finus" 
docker pull "bcinsider.azurecr.io/bcsandbox:13.0.22895.0-us"

I am able to pull docker -image "bcinsider.azurecr.io/bcsandbox-master:us" which is build 13.0.23231.0
(unclear if this BC build contains the developer preview changes from June)?

Is the navdocker.azurecr.io repository still active?  Is so, can you provide the login -u -p parameters.

I am referencing the document  from Microsoft Collaborate to obtain docker builds,
Please advise.

Login Succeeded
docker : Error response from daemon: manifest for bcinsider.azurecr.io/dynamics-nav:13.0.22895.0-us not found
At line:3 char:1
+ docker pull "bcinsider.azurecr.io/dynamics-nav:13.0.22895.0-us"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ....0-us not found:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Login Succeeded
docker : Error response from daemon: manifest for bcinsider.azurecr.io/dynamics-nav:devpreview-finus not found
At line:3 char:1
+ docker pull "bcinsider.azurecr.io/dynamics-nav:devpreview-finus"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ...finus not found:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Login Succeeded
docker : Error response from daemon: manifest for bcinsider.azurecr.io/bcsandbox:13.0.22895.0-us not found
At line:3 char:1
+ docker pull "bcinsider.azurecr.io/bcsandbox:13.0.22895.0-us"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ....0-us not found:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by freddydk** [comment]
navinsider doesn't exist anymore - NAV is on public docker hub and only cumulative updates are released here.

Locations for Docker images are explained here: https://blogs.msdn.microsoft.com/freddyk/2018/04/16/which-docker-image-is-the-right-for-you/
Don't try anything else unless specifically instructed to go for a specific build number.

Our branching strategy is described here: https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/

This means that bcinsider.azurecr.io/bcsandbox-master:<country> contains our daily build and will (as the only one) contain the feature set explained in the June developer preview blog post.

**Comment by alanb999** [comment]
Can you please clarify terminology being used in the build strategy ...

Is the Main Branch equivalent to the "Daily Builds - Developing for a future release of Dynamics 365 Business Central" published on Microsoft Collaborate? 
bcinsider.azurecr.io/bcsandbox-master:us

Or is the Main Branch equivalent to "Daily Builds - Maintaining an app in AppSource for Dynamics 365 Business Central"?
bcinsider.azurecr.io/bcsandbox:us

**Comment by freddydk** [comment]
Main is master - that is where our development happens.
