### ISSUE TITLE
SQL Server version on NAV images

### ISSUE THREAD

**Issue by fvet** [Microsoft/nav-docker#232]
Using the microsoft/dynamics-nav:2018-cu6 image, I'd like to restore a bak file of our DEV database which was taken on SQL Server 2017. When restoring, this error occurs:

> The database was backed up on a server running version 14.00.3023. That version is incompatible with this server, which is running version 13.00.4001. Either restore the database on a server that supports the backup, or use a backup that is compatible with this server.

Apparently, docker images still use SQL Server 2016? Any plans to upgrade the docker images to a later SQL Server version?

**Comment by freddydk** [comment]
Images will be rebuilt every 2-3 months - next round is probably 2 months out - which might include 2017.
Else you can spin up a seperate 2017 sql server container, restore the database and point to that from nav.

**Comment by freddydk** [comment]
If you use the NavContainerhelper then you can follow these steps:

https://blogs.msdn.microsoft.com/freddyk/2018/03/20/navcontainerhelper-create-a-sql-server-container-and-restore-a-bak-file/

https://blogs.msdn.microsoft.com/freddyk/2018/03/20/navcontainerhelper-use-an-external-sql-server-as-database-connection-in-a-nav-container/

You will also be able to see what the parameters are for docker run: --env databaseserver=servername --env databaseinstance=SQLEXPRESS ...

**Comment by rdebath** [comment]
Of course upgrading the SQL version has it's own set of issues, especially as the navdata export is currently broken.

**Comment by freddydk** [comment]
I will close this one.
The SQL Server will get updated some day, when the time is right.
