### ISSUE TITLE
The 'New-NavContainer' command was found in the module 'navcontainerhelper', but...

### ISSUE THREAD

**Issue by SUD-D365** [Microsoft/nav-docker#233]
Hello @freddydk ,

I came up with another issue related to container.
I just executing the PS command from power shell as administrator. But getting the below mention error.
 Error:
**New-NavContainer : The 'New-NavContainer' command was found in the module 'navcontainerhelper', but the module could not be loaded. 
For more information, run 'Import-Module navcontainerhelper'.
At line:17 char:1
+ New-NavContainer -accept_eula:$accept_eula `
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-NavContainer:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
 
Setup-NavContainerTestUsers : The 'Setup-NavContainerTestUsers' command was found in the module 'navcontainerhelper', but the module 
could not be loaded. For more information, run 'Import-Module navcontainerhelper'.
At line:32 char:1
+ Setup-NavContainerTestUsers -containerName $containername -password $ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Setup-NavContainerTestUsers:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule**

And the command that I m running is below.
Command:
**install-module navcontainerhelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true

$containername = 'deepikatest'
$navdockerimage = 'microsoft/dynamicsnav'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -memoryLimit 3G `
                 -containername $containername `
                 -auth Windows `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password**

As I have already installed both the required module **Container** and **Hyper-V**. But still getting error.
![image](https://user-images.githubusercontent.com/33481576/42615479-0e97554a-85c8-11e8-9957-bdbf0805be38.png)
 Docker is running well without any error.

What is the issue ? Can you please have a look on this issue?

Thanks

**Comment by GerritSo** [comment]
Have you tried to use  `New-NavContainer -accept_eula ...` instead of `New-NavContainer -accept_eula:$accept_eula ...` ?

**Comment by SUD-D365** [comment]
Yes I have tried, but no success.
Command : 
**install-module navcontainerhelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true

$containername = 'deepikatest'
$navdockerimage = 'microsoft/bcsandbox'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula `
                 -memoryLimit 3G `
                 -containername $containername `
                 -auth Windows `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password**

Result/Error:
**New-NavContainer : The 'New-NavContainer' command was found in the module 'navcontainerhelper', but the module could not be loaded. 
For more information, run 'Import-Module navcontainerhelper'.
At line:17 char:1
+ New-NavContainer -accept_eula `
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-NavContainer:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
 
Setup-NavContainerTestUsers : The 'Setup-NavContainerTestUsers' command was found in the module 'navcontainerhelper', but the module 
could not be loaded. For more information, run 'Import-Module navcontainerhelper'.
At line:32 char:1
+ Setup-NavContainerTestUsers -containerName $containername -password $ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~**

**Comment by freddydk** [comment]
I do not know why you cannot load the navcontainerhelper on your machine. It suggest that you run imprt-module navcontainerhelper to get more information, did you try that?

**Comment by SUD-D365** [comment]
Yes I tried this , and getting below error.
**import-module : File C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.3.0.2\NavContainerHelper.psm1
cannot be loaded because running scripts is disabled on this system. For more information, see
about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ import-module navcontainerhelper
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [Import-Module], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess,Microsoft.PowerShell.Commands.ImportModuleCommand
**

**Comment by SUD-D365** [comment]
Thanks @freddydk  and @GerritSo  for your prompt Revert.
I have managed to remove this error by simply set **SetExecutionPolicy** for the command.
 **Set-Executionpolicy -RemoteSigned**
Thanks
