### ISSUE TITLE
Changing License file

### ISSUE THREAD

**Issue by armela1981** [Microsoft/nav-docker#234]
I am running Dynamics 365 BC on docker locally.
I opened up the Developer's environment and I created a new page 50000. I received an error about the license. I changed the license and was able to successfully create the page.
I later uploaded the license on my Developer's environment.
I added it to the menu and when using RTC and calling the page, it displays a blank page.
When I call that page via the Web Client, it works fine.
I think this is a license issue.
How do I restart the service tier for my Dynamics 365 BC  RTC environment ??  Or how do I get my Service Tier to recognize the new uploaded license ?
Thanks

**Comment by freddydk** [comment]
If it works in WebClient and not in Windows Client, I don't think it is a license issue.
but - docker restart container should do the trick
or open-navcontainer (navcontainerhelper) to open a powershell prompt inside the container and use set-navserverinstance NAV -restart

**Comment by armela1981** [comment]
That did it.
The powershell Prompt worked.

Thanks
