### ISSUE TITLE
NAV Container goes "Unhealthy" while running ATT

### ISSUE THREAD

**Issue by AmandaTest** [Microsoft/nav-docker#235]
Hi, I have been trying to run the automated test tool in docker container for NAV2017, NAV2018 and Business Central.  There are about 20,000 tests and I am running them via the CAL Test Tool page. The application dies after running about 6000 tests.  I have checked the docker logs and it is showing the container is unhealthy.  The last error which appears is 
EntryType     : Error
Message       : There is insufficient system memory in resource pool 
                'internal' to run this query.
The container shows the following: 
CONTAINER ID        IMAGE                                                   COMMAND                  CREAT
ED             STATUS                             PORTS                                                NAM
ES
b02c9b133196        microsoft/dynamics-nav:2018-cu4-na                      "powershell -Commandâ€¦"   2 d
ays ago          Up 2 hours (unhealthy)             80/tcp, 443/tcp, 1433/tcp, 7045-7049/tcp, 8080/tcp 

To workaround this, I have had to stop the container and restart it then continue the test run from the point where it failed.  Is there a better way?  I have been watching my memory usage and looks like I have some room but not much.

**Comment by freddydk** [comment]
How much memory have you given the container?
Are you running Windows 10 or Windows 2016?
How much memory on the host?

**Comment by AmandaTest** [comment]
I’m using windows 10 with 12g. I pull the container with 4g.

On Jul 16, 2018, at 11:37 AM, Freddy Kristiansen <notifications@github.com<mailto:notifications@github.com>> wrote:


How much memory have you given the container?
Are you running Windows 10 or Windows 2016?
How much memory on the host?

**Comment by freddydk** [comment]
4g isn't enough for everything and I expect this to simply be because the container is running out of memory. You could start this with more memory, or you could run process isolation (only on Windows Server) which would allow the container to share the memory pool from the host without pre-allocating.
