### ISSUE TITLE
Docker Image for Microsoft Great Plains

### ISSUE THREAD

**Issue by gerardng** [Microsoft/nav-docker#237]
Hi,

Sorry if this isn't the best place to ask. I was just wondering if there are any resources out there in order to get/create an image of Microsoft Great Plains . 

Looking at hub.docker.com, it seems like there isn't a pre-defined image. How feasible would it be to create a docker image for Microsoft Great Plains (I'm assuming the components would be Microsoft Great Plains software and SQL Server Express)  on top of a windows OS host?

**Comment by gerardng** [comment]
Hi freddydk,

Thanks for the response.

**Comment by Koubek** [comment]
Hi @gerardng, [Tim Wappat](http://timwappat.info/) is working on something. Actually, we have been in contact right today for this specific reason, GP on Docker.

**Comment by Koubek** [comment]
Hi @gerardng, ok. Please, just close the issue as this has nothing to do with this project. Thanks.
