### ISSUE TITLE
microsoft/bcsandbox: Import FOB, Synchronize Schema dialog

### ISSUE THREAD

**Issue by mitrov** [Microsoft/nav-docker#239]
Hi 

I pulled the latest docker image on Azure based on http://aka.ms/bcsandbox 
Build is 12.2.22932.23097 (CH).

When I try to import a FOB with tables, the dialog with 'Synchronize Schema' option (Now/Later/Force) pops up for every table. So it somehow looses this information after every object.
Quite annoying as you can imagine :-)

**Comment by mitrov** [comment]
Yes, the powershell cmdlet worked (there was no prompt at all about 'Schema Synchronization')

It's been a while ago that I tested with an older build of Business Central and didn't see this issue there.

**Comment by freddydk** [comment]
You must have used a different authentication mechanism (Windows works) or you haven't had any table changes.

**Comment by mitrov** [comment]
Ok, so if I understood correctly, this happens only if you use Docker in combination with NavUserPassword Authentication and importing FOBs with the traditional C/Side environment.
Workaround is to use the the powershell cmdlets in navcontainerhelper (Import-ObjectsToNavContainer).

**Comment by mitrov** [comment]
I saw exactly this same behaviour with the newest "Business Central OnPremise" preview 01 for partners.

- not using docker
- using windows authentication

**Comment by mitrov** [comment]
According to the feedback from the collaborate program it should be fixed in the future.
