### ISSUE TITLE
Server cannot be found - D365BU

### ISSUE THREAD

**Issue by srikar1405** [microsoft/nav-docker#240]
Hi 

I am new to docker, I have installed docker in windows server 2016 and I have setup Dynamics 365 Business central. It had created the shortcuts fo NAV Development, Client and the web client.
But when i'm trying to open those shortcuts facing following issue "The NAVMSDYNBC\SQLEXPRESS server cannot be found. Try again later or contact your system administrator."

Can anyone help me in solving it?

Thanks, 

![web client](https://user-images.githubusercontent.com/41794626/43326630-f2d5ccc2-91d6-11e8-80a5-488f3c2827ef.png)
![development](https://user-images.githubusercontent.com/41794626/43326646-0183c3aa-91d7-11e8-863b-3db67ece6a6b.png)
![client](https://user-images.githubusercontent.com/41794626/43326648-01ac6e0e-91d7-11e8-9ae0-f8fd045e458a.png)

**Comment by srikar1405** [comment]
Hi Freddy,

Thanks for the reply.

I have used the following command "install-module navcontainerhelper -force"

**Comment by srikar1405** [comment]
i have removed the container and created a new container.

Now at the time of login now i'm facing following issue.

![new error](https://user-images.githubusercontent.com/41794626/43396413-1162e77a-941f-11e8-8f95-10998fe205ef.png)

**Comment by freddydk** [comment]
the install-module command is use for installing the navcontainerhelper module - not for creating the container. Creating the container is probably done by new-navcontainer.
You need to give us some more info on how you create the container (the script) and what response you got when creating the container.
You can use
Get-NavContainerDebugInfo <containername> -IncludeSensitiveInformation -CopyToClipboard 
to get debug info to the clipboard which you can attach here.

**Comment by srikar1405** [comment]
Script to create nav container : "New-NavContainer -containerName sriNEWMSDYNBC -accept_eula -alwaysPull -assignPremiumPlan -auth NavUserPassword -doNotExportObjectsToText -enableSymbolLoading -imageName microsoft/bcsandbox:us -includeCSide -memoryLimit 3G -shortcuts Desktop -updateHosts"

Debuginfo

PS C:\Windows\system32> Get-NavContainerDebugInfo
cmdlet Get-NavContainerDebugInfo at command pipeline position 1
Supply values for the following parameters:
containerName: sriNEWMSDYNBC
{
    "container.logs":  [
                           "Initializing...",
                           "Starting Container",
                           "Hostname is sriNEWMSDYNBC",
                           "PublicDnsName is sriNEWMSDYNBC",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Creating Self Signed Certificate",
                           "Self Signed Certificate Thumbprint AD6B6CF1B42B47213F8304557110ADBCF5BE934E",
                           "Modifying Service Tier Configa File with Instance Specific Settings",
                           "Starting NAV Service Tier",
                           "Creating DotNetCore Web Server Instance",
                           "Enabling Financials User Experience",
                           "Creating http download site",
                           "Creating Windows user srikar",
                           "Setting SA Password and enabling SA",
                           "Creating srikar as SQL User and add to sysadmin",
                           "Creating SUPER user",
                           "Assign Premium plan for SRIKAR",
                           "Container IP Address: 172.18.224.211",
                           "Container Hostname  : sriNEWMSDYNBC",
                           "Container Dns Name  : sriNEWMSDYNBC",
                           "Web Client          : http://sriNEWMSDYNBC/NAV/",
                           "Dev. Server         : http://sriNEWMSDYNBC",
                           "Dev. ServerInstance : NAV",
                           "",
                           "Files:",
                           "http://sriNEWMSDYNBC:8080/al-0.16.19969.vsix",
                           "",
                           "Initialization took 298 seconds",
                           "Ready for connections!",
                           "",
                           "",
                           "TimeGenerated : 7/30/2018 4:59:06 PM",
                           "EntryType     : Error",
                           "Message       : Server instance: NAV",
                           "                Tenant ID: ",
                           "                \u003cii\u003eUser: ",
                           "                Type: System.OutOfMemoryException",
                           "                Source: Microsoft.Dynamics.Nav.Types",
                           "                HResult: -2147024882",
                           "                StackTrace:",
                           "                     at Microsoft.Dynamics.Nav.Diagnostic.NavDiagnostics.Compos",
                           "                eAndSendExceptionTraceTag(String tag, Category category, ",
                           "                Exception exception, DiagnosticParameter message, Verbosity ",
                           "                verbosity, Guid clientSessionId, Guid clientActivityId, Func`1 ",
                           "                diagnosticsContext, Boolean forceLog)",
                           "                     at Microsoft.Dynamics.Nav.Diagnostic.NavDiagnostics.SendEx",
                           "                ceptionTag(String tag, Category category, Exception exception, ",
                           "                Verbosity verbosity, DiagnosticParameter message, Func`1 ",
                           "                diagnosticsContext, Boolean forceLog)",
                           "                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.",
                           "                ErrorMappingCombinator(ServiceOperation innerOperation, ",
                           "                NSServiceBase serviceInstance, MethodBase syncMethod, Object[] ",
                           "                inputs, Object[]\u0026 outputs)",
                           "                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.",
                           "                \u003c\u003ec__DisplayClass24_0.\u003cCombine\u003eb__1(NSServiceBase ",
                           "                serviceInstance, Object[] inputs, Object[]\u0026 outputs)",
                           "                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.",
                           "                PushPopCombinator(ServiceOperation innerOperation, ",
                           "                NSServiceBase serviceInstance, MethodBase syncMethod, Object[] ",
                           "                inputs, Object[]\u0026 outputs)",
                           "                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.",
                           "                \u003c\u003ec__DisplayClass24_0.\u003cCombine\u003eb__1(NSServiceBase ",
                           "                serviceInstance, Object[] inputs, Object[]\u0026 outputs)",
                           "                     at Microsoft.Dynamics.Nav.Service.ServiceOperationTracer.T",
                           "                raceScopeCombinator(Category telemetryCategory, ",
                           "                ServiceOperation innerOperation, NSServiceBase ",
                           "                serviceInstance, MethodBase syncMethod, Object[] inputs, ",
                           "                Object[]\u0026 outputs)",
                           "                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.",
                           "                \u003c\u003ec__DisplayClass24_0.\u003cCombine\u003eb__1(NSServiceBase ",
                           "                serviceInstance, Object[] inputs, Object[]\u0026 outputs)",
                           "                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.",
                           "                \u003c\u003ec__DisplayClass9_0.\u003cPerformanceCounterCombinator\u003eb__0()",
                           "                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.",
                           "                PerformanceCounterCombinator(ServiceOperation innerOperation, ",
                           "                NSServiceBase serviceInstance, MethodBase syncMethod, Object[] ",
                           "                inputs, Object[]\u0026 outputs)",
                           "                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.",
                           "                \u003c\u003ec__DisplayClass24_0.\u003cCombine\u003eb__1(NSServiceBase ",
                           "                serviceInstance, Object[] inputs, Object[]\u0026 outputs)",
                           "                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.",
                           "                InitClientTelemetryIdsCombinator(ServiceOperation ",
                           "                innerOperation, NSServiceBase serviceInstance, MethodBase ",
                           "                syncMethod, Object[] inputs, Object[]\u0026 outputs)",
                           "                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.",
                           "                \u003c\u003ec__DisplayClass24_0.\u003cCombine\u003eb__1(NSServiceBase ",
                           "                serviceInstance, Object[] inputs, Object[]\u0026 outputs)",
                           "                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.",
                           "                TlsClearCombinator(ServiceOperation innerOperation, ",
                           "                NSServiceBase serviceInstance, MethodBase syncMethod, Object[] ",
                           "                inputs, Object[]\u0026 outputs)",
                           "                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.",
                           "                \u003c\u003ec__DisplayClass24_0.\u003cCombine\u003eb__1(NSServiceBase ",
                           "                serviceInstance, Object[] inputs, Object[]\u0026 outputs)",
                           "                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.",
                           "                Invoke(Object instance, Object[] inputs, Object[]\u0026 outputs)",
                           "                     at System.ServiceModel.Dispatcher.DispatchOperationRuntime",
                           "                .InvokeBegin(MessageRpc\u0026 rpc)",
                           "                     at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime",
                           "                .ProcessMessage5(MessageRpc\u0026 rpc)",
                           "                     at ",
                           "                System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean ",
                           "                isOperationContextSet)",
                           "                     at System.ServiceModel.Dispatcher.MessageRpc.Wrapper.Resum",
                           "                e(Boolean\u0026 alreadyResumedNoLock)",
                           "                     at System.ServiceModel.Dispatcher.ThreadBehavior.ResumePro",
                           "                cessing(IResumeMessageRpc resume)",
                           "                     at Microsoft.Dynamics.Nav.Runtime.NavSynchronizationContex",
                           "                t.\u003c\u003ec__DisplayClass1_0.\u003cClearThreadLocalStorageDelegate\u003eb__0(Ob",
                           "                ject state)",
                           "                     at ",
                           "                System.Threading.ExecutionContext.RunInternal(ExecutionContext ",
                           "                executionContext, ContextCallback callback, Object state, ",
                           "                Boolean preserveSyncCtx)",
                           "                     at System.Threading.ExecutionContext.Run(ExecutionContext ",
                           "                executionContext, ContextCallback callback, Object state, ",
                           "                Boolean preserveSyncCtx)",
                           "                     at System.Threading.QueueUserWorkItemCallback.System.Threa",
                           "                ding.IThreadPoolWorkItem.ExecuteWorkItem()",
                           "                     at System.Threading.ThreadPoolWorkQueue.Dispatch()",
                           "                \u003c/ii\u003e",
                           "",
                           "",
                           ""
                       ],
    "docker.info":  [
                        "Containers: 2",
                        " Running: 2",
                        " Paused: 0",
                        " Stopped: 0",
                        "Images: 1",
                        "Server Version: 18.03.1-ce",
                        "Storage Driver: windowsfilter",
                        " Windows: ",
                        "Logging Driver: json-file",
                        "Plugins:",
                        " Volume: local",
                        " Network: ics l2bridge l2tunnel nat null overlay transparent",
                        " Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog",
                        "Swarm: inactive",
                        "Default Isolation: process",
                        "Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)",
                        "Operating System: Windows Server 2016 Standard",
                        "OSType: windows",
                        "Architecture: x86_64",
                        "CPUs: 16",
                        "Total Memory: 16GiB",
                        "Name: b2bsrv-35",
                        "ID: AMU7:4RTZ:RWAF:P2TW:H3HU:DNKG:4YQ2:V7K2:K5DN:AJZN:6ZNG:VFE7",
                        "Docker Root Dir: C:\\ProgramData\\Docker",
                        "Debug Mode (client): false",
                        "Debug Mode (server): true",
                        " File Descriptors: -1",
                        " Goroutines: 41",
                        " System Time: 2018-07-30T19:21:27.2908605+05:30",
                        " EventsListeners: 1",
                        "Registry: https://index.docker.io/v1/",
                        "Labels:",
                        "Experimental: false",
                        "Insecure Registries:",
                        " 127.0.0.0/8",
                        "Live Restore Enabled: false",
                        ""
                    ],
    "container.labels":  {
                             "country":  "US",
                             "created":  "201807051143",
                             "cu":  "",
                             "eula":  "https://go.microsoft.com/fwlink/?linkid=861843",
                             "legal":  "http://go.microsoft.com/fwlink/?LinkId=837447",
                             "maintainer":  "Dynamics SMB",
                             "nav":  "",
                             "osversion":  "10.0.14393.2312",
                             "tag":  "0.0.6.3",
                             "version":  "12.2.22932.23097"
                         },
    "container.ping":  [
                           "",
                           "Pinging srinewmsdynbc [172.18.224.211] with 32 bytes of data:",
                           "Reply from 172.18.224.211: bytes=32 time\u003c1ms TTL=128",
                           "Reply from 172.18.224.211: bytes=32 time\u003c1ms TTL=128",
                           "Reply from 172.18.224.211: bytes=32 time\u003c1ms TTL=128",
                           "Reply from 172.18.224.211: bytes=32 time\u003c1ms TTL=128",
                           "",
                           "Ping statistics for 172.18.224.211:",
                           "    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),",
                           "Approximate round trip times in milli-seconds:",
                           "    Minimum = 0ms, Maximum = 0ms, Average = 0ms"
                       ],
    "container.env":  [
                          "licenseFile=\u003cspecified\u003e",
                          "databaseInstance=",
                          "securePassword=\u003cspecified\u003e",
                          "accept_eula=Y",
                          "auth=NavUserPassword",
                          "enableSymbolLoading=Y",
                          "passwordKeyFile=c:\\run\\my\\aes.key",
                          "ExitOnError=N",
                          "enableApiServices=Y",
                          "useSSL=N",
                          "removePasswordKeyFile=Y",
                          "username=srikar",
                          "locale=en-US",
                          "databaseServer=",
                          "COMPLUS_NGenProtectedProcess_FeatureEnabled=0",
                          "NAVDVDURL=\u003cspecified\u003e",
                          "VSIXURL=\u003cspecified\u003e",
                          "IsBcSandbox=Y",
                          "DatabaseName=FinancialsUS",
                          "DEVPREVIEWURL=https://nav2016wswe0.blob.core.windows.net/dvd/450b770c-c5fd-49e8-b13f-13acdf5fd9a0"
                      ]
}

**Comment by freddydk** [comment]
"TimeGenerated : 7/30/2018 4:59:06 PM",
"EntryType : Error",
"Message : Server instance: NAV",
" Tenant ID: ",
" \u003cii\u003eUser: ",
" Type: System.OutOfMemoryException",

Remove the -memorylimit 3g it is automatically handled by navcontainerhelper and when running process isolatoin you don't need the memory limit.
