### ISSUE TITLE
Debugger issue on NAV2018 container due to protocol conflict

### ISSUE THREAD

**Issue by Kotygoroh** [Microsoft/nav-docker#243]
When starting the debugger from the C/Side on my NAV2018 container I get an error due to a protocol conflict possibly caused by incompatible authentication settings (ClientServicesCredentialType). My NAV container has been created using NavContainerHelper with NavUserPassword authentication.

Is there any solution for that? 
Thanks in advance.

**Comment by rdebath** [comment]
Um, Client user settings.
For the dev env to find them they have to be in the default location.
Or you can start the debugger with the client executable and a URL.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
<appSettings>
<add key="Server" value="navserver" />
<add key="ServerInstance" value="NAV" />
<add key="ClientServicesPort" value="7046" />
<add key="TenantId" value="" />
<add key="ClientServicesCredentialType" value="NavUserPassword" />
<add key="DnsIdentity" value="navserver" />
</appSettings>
</configuration>
```

**Comment by freddydk** [comment]
Do you have a clientusersettings under your roaming profile (from a version installed on the machine)?

**Comment by Kotygoroh** [comment]
Bingo, Freddy! The ClientServicesCredentialType in the clientusersettings under the roaming profile had been set to "Windows". Changing it to "NavUserPassword" and adding the certificate to the trusted persons resolved the issue. Thank you, guys!

**Comment by freddydk** [comment]
You should delete the clientusersettings under the roaming profile when using docker.
Windows Client looks there first (unfortunately) and this will mean that all docker images will end up using that.

**Comment by Kotygoroh** [comment]
Thanks, that worked out for me.
