### ISSUE TITLE
Creating container stuck or timeout period expired

### ISSUE THREAD

**Issue by SergioKelly** [Microsoft/nav-docker#244]
PowerShell ISE Using navcontainerhelper (container stuck)
![container-issue](https://user-images.githubusercontent.com/22604702/43745625-63e0537e-99cf-11e8-994c-dd023cf15a87.png)

PowerShell using docker commands 
![docker-timeout](https://user-images.githubusercontent.com/22604702/43745859-84f1fb02-99d0-11e8-8c87-eb4db7709709.png)

**Comment by freddydk** [comment]
This problem seems related to the docker installation on your machine.
Try to follow the tests in this list:
https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/
and see if that helps.

**Comment by SergioKelly** [comment]
Hi Freddy,
I download Docker from https://docs.docker.com/docker-for-windows/install/ and it is working now.
Thx.
