### ISSUE TITLE
Pull new docker image

### ISSUE THREAD

**Issue by armela1981** [Microsoft/nav-docker#245]
Hello there.
I am running NAV on docker.
I accomplished this by creating  a sandbox PS1 file from the Live NAV 365 business central and using the Windows ISE command to pull in that image.  Works great.
There were some updates to the BC 365 and I want to pull those in to my docker image. I found this link https://blogs.msdn.microsoft.com/freddyk/2018/04/16/which-docker-image-is-the-right-for-you/
but I don't know where to run the commands mentioned in the link.
So I would like to know what is the best way to refresh my NAV running on docker with the latest updates ? 
Also question on AL
The following suggestion was made 
   You should make sure that you're using AL Language that comes as part of the Docker image. 
   Otherwise you run into the risk of incompatibilities between non-released versions.

How do I check that my AL language is in sync with the  Docker  image one ?

**Comment by sssolammm** [comment]
You can know If the AL language is sync with docker when you are able to download symbols in visual studio code.

**Comment by freddydk** [comment]
The docker image displays a download URL for the VSIX which maches the docker image.
You need to ensure that the version number is the same. Things might work for downloading symbols and other things, but there might be things which doesn't work.

**Comment by armela1981** [comment]
Thank you for your reply.

I am a little confused.
Where can I find the download URL on the docker image ??
Which version number do I compare to which  ?
On the AL Language extension I have version 0.16.19969.
Thanks

**Comment by freddydk** [comment]
when you use docker run or new-navcontainer it will display the url.
You can also use docker logs <containername> to re-display the url.

**Comment by freddydk** [comment]
The script will output a number of things when running it.
If you didn't see it - use docker logs <containername> afterwards and you will see the line.
Feel free to post docker logs output here and I will highlight the line.

**Comment by armela1981** [comment]
Ok found it on the output.
Files:  http://MyBizCentralApp:8080/al-0.16.19969.vsix 

so the above and my AL extension match which is great.


So my other issue was

There were some updates to the BC 365 and I want to pull those in to my docker image. I found this link https://blogs.msdn.microsoft.com/freddyk/2018/04/16/which-docker-image-is-the-right-for-you/
but I don't know where to run the commands mentioned in the link.
So I would like to know what is the best way to refresh my NAV running on docker with the latest updates to BC 365 ?

**Comment by freddydk** [comment]
in the script above - you reference microsoft/bcsandbox:us - which references the latest public Business Central Sandbox environment and since you have -alwaysPull, you will refresh the container with the latest image every time you run the script.

**Comment by armela1981** [comment]
OK, appreciate the responses.
The issue that I am having is that some of the things that were supposed to be fixed on a July release of BC 365 are not fixed and I was trying to figure out why I am not seeing those fixes.
One of which was the Search on a new page extension that I created. The page does not display on the search although I have it setup 
UsageCategory = Lists;
and all the fields are marked as
ApplicationArea = All;

**Comment by freddydk** [comment]
When you say July release - where did you find that info?
If that is the July Preview - then that is only available as an insider build for people with access to Microsoft Collaborate.

**Comment by armela1981** [comment]
Yes that is what I am referring to.
I did not realize that the July Preview was only available to a certain group of people.
Since I am not in that group, how can get these updates ?
We have quite a few customers that signed up for BC 365 and I have a lot of development to do.
Sorry for bombarding you with all of these questions.

Thanks

**Comment by freddydk** [comment]
https://blogs.msdn.microsoft.com/nav/2018/05/03/al-developer-previews-multiple-releases-and-github/
combined with the blog post from me and this:
http://aka.ms/businesscentralapps
can probably help you.

**Comment by armela1981** [comment]
Here is where I got the info
https://github.com/Microsoft/AL/issues/2977

Towards the middle of the thread the person that answered is Stanislaw Stempin.

Sorry to bombard you with all these issues/questions but we have quite  a few customers that signed up with BC365 and I am working on several extensions.

**Comment by freddydk** [comment]
In case you need access to insider builds, please reach out to dyn365bep@microsoft.com with your request and they will direct you to sign the necessary documents to get early access.
