### ISSUE TITLE
How to setup support for Automated Data Capture System (ADCS) using Docker?

### ISSUE THREAD

**Issue by astroseinarsdottir** [Microsoft/nav-docker#246]
Is there any documentation available on how to setup ADCS using Docker containers?

It would be great if it could be done without having to setup NAV.

**Comment by freddydk** [comment]
ADCS is not installed by default in Docker. You would have to grab ADCS from a DVD, copy it to the container and install it. I have no idea whether it will work - or whether it uses things, that are unsupported in a container.
We have no plans of installing ADCS by default.
