### ISSUE TITLE
[Question] Is there a US localized NAV 2018 image?

### ISSUE THREAD

**Issue by kostenko** [Microsoft/nav-docker#247]
Hello, I've tried to pull `microsoft/dynamics-nav:2018-us` but apparently it doesn't exist. Is there a way I could get a US localized version of Cronus USA with dev/test data for the US? Thanks.

**Comment by freddydk** [comment]
NAV images are following the country codes NAV
2018-na would be the image to pull

**Comment by kostenko** [comment]
Thanks!
