### ISSUE TITLE
failure in a Windows system call: The resource loader failed to find MUI file

### ISSUE THREAD

**Issue by rendmath** [Microsoft/nav-docker#248]
When running the `docker run -e accept_eula=Y -m 4G microsoft/bcsandbox` command mentionned on the microsoft/bcsandbox Docker Hub page, I consistently get this error message :

`
docker: Error response from daemon: container 0dccdbf470630dafb1830b15ed906aa1ca85eaff8dcbfc68817c598337948607 encountered an error during CreateContainer: failure in a Windows system call: The resource loader failed to find MUI file. (0x3afc) extra info: {"SystemType":"Container","Name":"0dccdbf470630dafb1830b15ed906aa1ca85eaff8dcbfc68817c598337948607","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\0dccdbf470630dafb1830b15ed906aa1ca85eaff8dcbfc68817c598337948607","Layers":[{"ID":"2210c90a-7574-5039-ae5b-0060eb5b268b","Path":"C:\\ProgramData\\Docker\\windowsfilter\\68ad28c0d74c3020e0a90e8ec7f755b46bbe58d89d55fcf3c3e0f3a12e318a08"},{"ID":"c1e71f9e-71f6-5b9c-be69-6ec1a4b3acf7","Path":"C:\\ProgramData\\Docker\\windowsfilter\\5e83c50ccfde1eef84dda668ee04f18db5c6e1603768dd5a2d511251693900e0"},{"ID":"c555bb9e-03c9-5b57-beba-3e431296a081","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f90db74348e0191b43d8ad4d640290f749e7d2de910cd7f26193b0cda5108788"},{"ID":"c8b25811-fb0d-539f-9f87-71b54d7ab940","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a3d014fd8842e8db5808b07ffcbb23f91fc0084867ca5a7f448ef60fdeea8bc7"},{"ID":"8f3786cf-5ab8-54d1-bc58-14c5f5f4e400","Path":"C:\\ProgramData\\Docker\\windowsfilter\\da20861e3d754eacbb74bef4c7bc73d7cab563fa2cf22a3bbf67ffa130bc73c5"},{"ID":"6dbebcd5-f72c-502b-a791-7a3963a8b480","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ceb24552ab56d730eb8fcf2e1b4e478468c612f7a70e3642125fb9abb547809a"},{"ID":"74078955-d1fd-5977-af76-e7bf8b6bc859","Path":"C:\\ProgramData\\Docker\\windowsfilter\\78e07a5da704f2e890687d12fe7e72dbc7fd0a329cb3830c88ea5c990b5f7219"},{"ID":"b2b58196-3ea0-55d7-b330-a969286b635c","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3d30fa027f83bebdd276d71b914a5ed112607cc4800e0dd01696fcefa4b12e2d"},{"ID":"1d924f90-4239-510d-8085-995fce0937fb","Path":"C:\\ProgramData\\Docker\\windowsfilter\\2a2c8e0819f04e59b3c2c826831c58d04139c0d70c1dba33782a16a7a5932cba"},{"ID":"24d59a1d-5887-5f73-93c7-f1a07b0c794e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\fd811dde7cfa6428cf8b57c046911756f59e72429e5c5bc232d995e671aa3947"},{"ID":"ec1225ee-361e-5a3d-93eb-d5bd0fce6cbd","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f55d30582fc97a5b6c311c38c6785edbc7461623389064deb655b020a94a0b9b"},{"ID":"7daff7b3-3dc4-5035-ac96-62878a6876cd","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6795df6086b4600e177496717339225a32af86bdb93be1670e48d7e597510ac7"},{"ID":"3fec1a53-954b-533b-a580-949c482f665d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3f5a624359fcabb1f085577cf2ce2b190043487f405535f299a1af8ef436bd5d"},{"ID":"a71a1e2e-8e10-5d7b-abb6-a6a62ec26d33","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7aa2edeada28638b66052d3a7082bdb9704e264333c705066afec8b591398094"},{"ID":"0d7f56aa-8758-5dad-a63a-bda8b2b7a5bd","Path":"C:\\ProgramData\\Docker\\windowsfilter\\5fcd9838fbbf65c6cc24bdea283345c30d4ce6163f50f8b84e9b02cf34e57cbf"},{"ID":"2bd8a798-6c43-5bb1-b929-bcbea7d104a3","Path":"C:\\ProgramData\\Docker\\windowsfilter\\8dcd734bf0069e893f14aa61459597e6f6f58b12467ae9f5e59822c35874314d"},{"ID":"907765be-ffd3-5ab7-942e-cdd8e6b41fb2","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3f93c824a67ea208f6efb0d2e52a76fe1e62ec854bc0a777e76b29d6c225fb98"},{"ID":"b5c492f3-2ceb-5078-98f6-40b8ba978696","Path":"C:\\ProgramData\\Docker\\windowsfilter\\d5a4be5e5e76005d48861838b4ad0ee13a44fdc3a14f17247931664d9212dd25"},{"ID":"3bf43ce5-0963-561f-91f1-74726ed25321","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1765191527d2bf9b05579fe8f3be5d4f094e2ca271d975823a54388ab1dd3a2b"},{"ID":"abb54099-2c12-5b88-a7bb-2bbc4d95664d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3a0e6841a3206987833768a76411b2ccc314b7f7b166efd22d649798c6a3bccf"},{"ID":"960572ff-78f1-5f98-82c0-cc0c7bf1b754","Path":"C:\\ProgramData\\Docker\\windowsfilter\\51e19c5e431fcdb05c4c80150fbc17df7da9ebfdf939e7f33b64f2171f81b75b"},{"ID":"9deb654e-3220-56ea-a3dc-4598c37f0baf","Path":"C:\\ProgramData\\Docker\\windowsfilter\\727a04580b641b82645e8126c9bf5551967ceeb25b11be40a4923835d7e27f77"}],"MemoryMaximumInMB":4096,"HostName":"0dccdbf47063","HvPartition":true,"EndpointList":["6f30a5f0-e614-4360-95a6-562f8a9faa36"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\51e19c5e431fcdb05c4c80150fbc17df7da9ebfdf939e7f33b64f2171f81b75b\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}.
`

Here are the outputs of `docker version` and `docker info` :
```
C:\WINDOWS\system32>docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.06.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 17134 (17134.1.amd64fre.rs4_release.180410-1804)
Operating System: Windows 10 Pro Version 1803 (OS Build 17134.228)
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 15.7GiB
Name: RENDMATH-T530-2
ID: KCBE:RAA2:UUD7:GPDX:DZK6:B5ZQ:BULY:FEUG:UZIZ:BXIE:BMEW:XVZR
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 30
 System Time: 2018-08-18T09:08:17.027461+02:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
```
C:\WINDOWS\system32>docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:23:19 2018
  OS/Arch:          windows/amd64
  Experimental:     false
```
Other docker containers on the same machine are running fine.

**Comment by freddydk** [comment]
I do not know what is wrong here. I have seen people have problems with assigning 4G and it then works when they use 3G.
Have you tried following the steps here: https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/
or maybe re-installing docker on the machine.

**Comment by rendmath** [comment]
We tried reinstalling Docker, 3G and 6G, elevated or not, joined and unjoined to the domain, with and without AV. Everything we could think of at this point.

**Comment by rendmath** [comment]
It doesn't work with New-NavContainer either.

```
PS C:\WINDOWS\system32> New-NavContainer -containerName my -imageName microsoft/bcsandbox -accept_eula
Creating Nav container my
Using image microsoft/bcsandbox:latest
NAV Version: 12.3.23590.23828-W1
Generic Tag: 0.0.6.4
Creating container my from image microsoft/bcsandbox:latest
```

It hangs indefinitely on the last line, and `docker stats` never shows any container.

**Comment by freddydk** [comment]
What is the output of 

Invoke-WebRequest https://aka.ms/Debug-ContainerHost.ps1 -UseBasicParsing | Invoke-Expression

On the machine?

**Comment by igorchpbc** [comment]
I have the same error and the similar errors mentioned in https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/ .

I would like to know if any CPU models/stepping or supported cpu flags(Ex: "PAGE1GB   -    Supports 1 GB large pages") is required to run [this](https://hub.docker.com/r/microsoft/dynamics-nav/) **nav** container? 
Older (2009) models of Intel CPUs are supported?

 I am running docker on Microsoft Windows 10 Enterprise edition  
Microsoft Windows [Version 10.0.17134.228]
Coreinfo v3.31 - Dump information on system CPU and memory topology
Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz
Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
...
PAGE1GB         -       Supports 1 GB large pages(***means not supported**)
...
Error:(docker output)
container 3e96235ae4a80d403.... encountered an error during CreateContainer: 
failure in a Windows system call: The locale specific resource for the desired message is not present.(0x3ab9)extra info: {
...
**"MemoryMaximumInMB": 4096**, (*means -m 4G, physical memory 12Gb , available 8Gb)

Windows log:
The guest operating system reported that it failed with the following error codes: 
ErrorCode0: 0x1A,ErrorCode1: 0x61941, ErrorCode2: 0xFFFFA6FE40000000, ErrorCode3: 0xB, ErrorCode4: 0xFFFF970154F286E0. 

According my understanding and reading [this link](https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x1a--memory-management) these are memory issues:
ErrorCode0: 0x1A, The MEMORY_MANAGEMENT bug check has a value of 0x0000001A. This indicates that a severe memory management error occurred. https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x1a--memory-management 
ErrorCode1: 0x61941, The paging hierarchy is corrupt. Parameter 2 is a pointer to the virtual address which caused the fault.

**Comment by freddydk** [comment]
Thanks, Igor

**Comment by rendmath** [comment]
Unfortunately, `-e locale=en-us` didn't change anything for any of our developers.

**Comment by freddydk** [comment]
Could you post the output of
Invoke-WebRequest https://aka.ms/Debug-ContainerHost.ps1 -UseBasicParsing | Invoke-Expression
On the machine?

**Comment by rendmath** [comment]
Here is the failing test: 

[-] A Windows NAT is configured if a Docker NAT network exists 4.1s
   Expected {0} to be greater than or equal to {1}
   226:        $winnatCount | Should Not BeLessThan $natCount
   at <ScriptBlock>, C:\Users\rendmath\Desktop\Untitled3.ps1: line 226

**Comment by rendmath** [comment]
The machines have been completely reinstalled, and the problem persists.

**Comment by freddydk** [comment]
You could try to uninstall docker and run Docker inside a server vm like AJ describes here:

https://www.kauffmann.nl/2017/12/02/running-nav-docker-containers-on-a-local-hyper-v-virtual-machine/

**Comment by freddydk** [comment]
I think -usebestcontaineros will help on this problem
https://blogs.msdn.microsoft.com/freddyk/2018/10/24/windows-10-and-docker-images-for-business-central-nav/
