### ISSUE TITLE
Unable to use the Job Queue in Container

### ISSUE THREAD

**Issue by mtaanquist** [Microsoft/nav-docker#249]
I am unable to use the Job Queue functionality in Dynamics NAV 2018 when using a Docker container.

My host machine is running Windows 10 (Version 1803 (OS Build 17134.228)), connected to a work account (Office 365/Azure AD).

I have pulled the latest `microsoft/dynamics-nav:2018-dk` image from Docker Hub, and used NavContainerHelper with the following command to build my container:

```
New-NavContainer 
	-containerName nav2018dk 
	-imageName microsoft/dynamics-nav:2018-dk
	-accept_eula 
	-includeCSide 
	-auth NavUserPassword 
	-licenseFile "C:\Users\mt\licence.flf" 
	-doNotExportObjectsToText
	-updateHosts
```

The default job queue entries that are created with the User ID `EUROPE\NAVBUILD` run fine. If I edit them, or create a new job, it gets my own user ID `MT` which remains on the `Ready` state indefinitely, even though the `Earliest Start Date/Time` has been passed.

Am I missing something in my initialisation of the new NAV container, or is this intended to not be usable?

**Comment by freddydk** [comment]
I think this is related to NavUserPassword authentication.
It should work if you use Windows authentication.
I am aware that you cannot always use windows auth, we will investigate whether we can find a solution.

**Comment by mtaanquist** [comment]
Hi @freddydk,

Thank you for the reply. I just attempted to spin up a container using Windows authentication, and tried out the same steps as I did for the NavUserPassword container I had. This gives me the same result as mentioned above.

Existing jobs created by EUROPE\NAVBUILD run alright (verified by checking the log entries for each job queue entry), whereas ones I create, do not.

Using Windows authentication also has the downside of not allowing me to log in to the old development environment, and for some reason, the desktop client doesn't find the server (but the web client works). I think this is related to my PC being connected to an O365/Azure AD account instead of a personal account.

Let me know if I can provide any information here that can help you further.

**Comment by freddydk** [comment]
In that case, Windows auth doesn't work - meaning that you still have to login to the WebClient right?
I will investigate, but it might take some time:-(

**Comment by freddydk** [comment]
Windows Auth (without gMSA) doesn't work with cached credentials - are you connected to the network with the AD Server?

**Comment by mtaanquist** [comment]
My apologies, I would have thought any Windows auth would work, and decided to test how it worked at home--to see if I got the same results as O365 creds. No, my home PC is not connected to the AD server.

**Comment by freddydk** [comment]
No worries. Containers cannot join a domain, meaning that Windows auth without gMSA lives off the "feature" introduced in WFW (Windows For Workgroups = long time ago) that if you have the same name and password on two machines in a workgroup - you are the same. When running under an AD, it needs to validate these towards the AD server.
gMSA solves this, but you need to be an AD administrator in order to set it up.
