### ISSUE TITLE
WebClient Authentication problems with specific Hostname (e.g. -h nav_dev)

### ISSUE THREAD

**Issue by megel** [Microsoft/nav-docker#25]
`docker run --rm -h nav_dev -e ACCEPT_EULA=Y -e username=$username -e password=$password -d -e WindowsAuth=N -e UseSSL=N -d -m 3G -e ClickOnce=Y navdocker.azurecr.io/dynamics-nav:devpreview
`  (Image was pulled this morning)

I have some problems with the authentication in the WebClient, when i use a defined hostname **nav_dev**. After entering my User/Pass into the following screen:
![grafik](https://user-images.githubusercontent.com/15800069/29357561-44dc7a12-8278-11e7-8543-3ee4fce80fbe.png)

It returns into: 
![grafik](https://user-images.githubusercontent.com/15800069/29357639-8ccd8406-8278-11e7-8c6a-8e090a443376.png)

When I use the IP of the container it works well:
![grafik](https://user-images.githubusercontent.com/15800069/29357532-307a20b0-8278-11e7-88df-4f9274b6e0fa.png)
![grafik](https://user-images.githubusercontent.com/15800069/29357765-f9a46e14-8278-11e7-85a0-c8240feb42de.png)

RTC / FinSQL works also correct with **nav_dev**

Docker-Log:
```
Initializing...
Running Specific Image
Starting Local SQL Server
Using NavUserPassword Authentication
Using Database Connection localhost/ [CRONUS]
Modify NAV Service Tier Config File for Docker
Hostname is nav_dev
Create Self Signed Certificate
Self Signed Certificate Thumbprint E54FE8FAE1D8779D4261E7B3B4BD7972E9FFF826
Modify NAV Service Tier Config File with Instance Specific Settings
Restart NAV Service Tier
WARNING: Waiting for service '"Microsoft Dynamics NAV Server [NAV]
(MicrosoftDynamicsNavServer$NAV)' to stop...
Using existing license file
Create Web Site
Create NAV Web Server Instance
Create http download site
Create ClickOnce Manifest
Container IP Address: 172.27.224.112
Container Hostname  : nav_dev
Web Client          : http://nav_dev/NAV/WebClient/
Dev. Server         : http://nav_dev
Dev. ServerInstance : NAV
ClickOnce Manifest  : http://nav_dev:8080/NAV

Files:
http://nav_dev:8080/al-0.8.11706.vsix

Ready for connections!
```

**Comment by tfenster** [comment]
One of the weirdest things I have met and it took me parts of two days to figure it out: in IE end Edge cookies don't work if the hostname contains a _ (see https://support.microsoft.com/en-us/help/316112/prb-session-variables-do-not-persist-between-requests-after-you-install-internet-explorer-security-patch-ms01-055)

**Comment by megel** [comment]
OMG!
Yes - changed the hostname and it works:
![grafik](https://user-images.githubusercontent.com/15800069/29359566-73ad38a2-827f-11e7-82c5-defd71708f6a.png)
