### ISSUE TITLE
FileShare and ClickOnce on Port 80

### ISSUE THREAD

**Issue by MaxBelohoubek** [Microsoft/nav-docker#250]
I would like to move the FileShare and ClickOnce to port 80 because of the port limitations given with Azure Container Instances, can't get it to work though.
Looking at the navstart.ps1 it seems like it will always be located at port 8080, no matter which port i specify with --env publicFileSharePort. Is that intentional?

**Comment by freddydk** [comment]
Yes, the ports inside the container are always the same. The publicFileSharePort (like publicWebClientPort) will not change settings in the container, but just indicate to the container, that the public port for reaching this container is different.
This really only affects urls.
You can disable the fileshare and copy the content to a different folder which is accessible differently.

**Comment by MaxBelohoubek** [comment]
Thanks for your help, I`ve found a way that fits my needs.
