### ISSUE TITLE
Hard limit on number of AAD users?

### ISSUE THREAD

**Issue by AlphaGeeKUK** [Microsoft/nav-docker#251]
I have a BC sandbox that I enabled synching of AAD users in. There are a lot of users in my tenant but the users synched to BC seem to stop around those starting with L.

Take out the DELEGATEDADMIN, ESSENTIAL users etc. and it looks like it's only synching the first 100 users or so.

Is this a template/script limit or is something broken in my AAD?

**Comment by freddydk** [comment]
This is a bug in navcontainerhelper.
The Create-AadUsersInNavContainer function uses the Get-AzureADUser cmdlet, which only returns the first 100 users.
I have fixed this by adding -all $true - and it will be included in the next navcontainerhelper (automatically grabbed by BC sandboxes in a few days.
