### ISSUE TITLE
Enabling access to containers outside localhost

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/nav-docker#252]
Hi,

I'm trying to enable access to container outside localhost inside the network. I'm doing this for our development and testing environment since we need more people to access business central but also other applications using web service to be able to target our solution.

Can you advice what would be the best option to accomplish this? 

I am currently trying to do port mapping for container but without success. The script I'm using looks like this:

````
$imageName = 'bcinsider.azurecr.io/bcsandbox-master:13.0.23638.0-ca'
$cred = Get-Credential -UserName $env:USERNAME -Message "Enter your Credentials"
$containerName = 'mycontainer'

New-NavContainer -containerName $containerName `
-imageName $imageName `
-accept_eula `
-Credential $cred `
-auth NavUserPassword `
-licensefile "C:\myfolder\mylicense.flf" `
-includecside `
-multitenant `
-restart always `
-enableSymbolLoading `
-doNotExportObjectsToText `
-additionalParameters "--env PublicDnsName=$containerName --publish 8081:8080 --publish 444:443 --publish 7146-7149:7046-7049"
````

**Comment by Koubek** [comment]
I would suggest using Transparent network instead of NAT.
https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/architecture

**Comment by ivandjordjevic** [comment]
@Koubek Thanks for reply. 

Sorry for my lack of expertise in networks but I'm not sure to what exact solution you are referring from this article or where to start actually. Can you please provide more detailed steps?

Is there any simple and out-of-the-box solution we can use without having to do lots of network configurations?

**Comment by ivandjordjevic** [comment]
This seems like a common scenario where you would want your Business Central solution available across network and not just locally. We also considered installing NAV 2018 / Business Central as a standalone application since we could easily make clients available throughout network but the build we are working on is only available as docker image... So we need a way to make our containers available just the same.

**Comment by Koubek** [comment]
Using static IP - the example is coming from here: https://docs.microsoft.com/en-us/virtualization/windowscontainers/container-networking/advanced
```
# Example: Create a transparent network using static IP assignment
# A network create command for a transparent container network corresponding to the physical network with IP prefix 10.123.174.0/23
C:\> docker network create -d transparent --subnet=10.123.174.0/23 --gateway=10.123.174.1 MyTransparentNet
# Run a container attached to MyTransparentNet
C:\> docker run -it --network=MyTransparentNet --ip=10.123.174.105 windowsservercore cmd
```

And for example here you can find also DHCP enabled network example (it's actually easier to start with but I had some problems when quickly rotating containers with the same names):
https://www.ntweekly.com/2017/03/30/how-to-create-a-transparent-network-with-windows-containers/

**Comment by ivandjordjevic** [comment]
With static IP I should:

1. First, create a transparent network using static IP assignment
````
docker network create -d transparent --subnet=10.123.174.0/23 --gateway=10.123.174.1 MyTransparentNet
````
2. Second step: Run a container attached to MyTransparentNet - and this is actually my nav container? So I can run command:
````
$imageName = 'bcinsider.azurecr.io/bcsandbox-master:13.0.23638.0-ca'
$cred = Get-Credential -UserName $env:USERNAME -Message "Enter your Credentials"
$containerName = 'mycontainer'

New-NavContainer -containerName $containerName `
-imageName $imageName `
-accept_eula `
-Credential $cred `
-auth NavUserPassword `
-licensefile "C:\myfolder\mylicense.flf" `
-includecside `
-multitenant `
-restart always `
-enableSymbolLoading `
-doNotExportObjectsToText `
-additionalParameters "-it --network=MyTransparentNet --ip=10.123.174.105"
````

Or do I still need to run container from windowsservercore and then run my nav container?
````
docker run -it --network=MyTransparentNet --ip=10.123.174.105 windowsservercore cmd
````

**Comment by Koubek** [comment]
I don't use NavContainerHelper but I think you should be fine calling New-NavContainer and passing
```
-additionalParameters "--network=MyTransparentNet --ip=[free_ip_from_the_subnet]"
```

I was using a cmdlet that was automatically adjusting DNS registers so I was able to access containers using their hostname.

**Comment by anwar0206** [comment]
Hi ivandjordjevic,

We are also trying to setup similar environment at our end.
1st container created through Mrs. Freddy's script which is working fine and accessible outside the host too.

cannot create 2nd container as it keep "Error response from daemon: failed to create endpoint DEMO on network nat: HNS failed with"

**Comment by freddydk** [comment]
Networking with docker containers is very powerful and allows you to do everything really. With NAV containers you can any of the network settings.
Any use of networking must be compatible/integrated with your infrastructure. In Microsoft we cannot use transparent networking as our infrastructure won't allow a new unknown machine access.
Only out-of-the-box solution is NAT - if you need other network settings, you will need to read about networking and docker. Just like setting up NAV from a DVD doesn't really include any network settings on the server.
So, I cannot describe how to setup a second container on a machine that just always works. For that, the infrastructure and settings are simply too different.
I can explain how to setup a second container on an Azure VM (created by http://aka.ms/getnav) as this is a known starting point. I will do that and post the script/necessary steps here and in a blog post.

**Comment by Koubek** [comment]
I fully agree with @freddydk, everything really depends on your needs and there so many combinations that one that fits one company doesn't work for others.

Usually, the best way is to involve your sysadmin/network admin.

**Comment by freddydk** [comment]
I have added a script and sample on how to do this on azure vms here:
https://github.com/Microsoft/nav-docker/issues/254
