### ISSUE TITLE
How can I make visible make in my local network my docker?

### ISSUE THREAD

**Issue by sssolammm** [Microsoft/nav-docker#253]
Hello, 

How I can make it visible for all other users of the network, now Im the only allow to see it beacause is in my internal network. Theres anyway to change docker ip ?

Regards,

**Comment by Koubek** [comment]
Probably a duplicity of https://github.com/Microsoft/nav-docker/issues/252

**Comment by sssolammm** [comment]
I read the article before post mine but with the answer posted is not the solution that I need. I would like an example or something more clearly to work with

**Comment by Koubek** [comment]
I really love Transparent network, it allows you to share all containers efficiently in your company.

You can find probably some good examples like:
https://www.ntweekly.com/2017/03/30/how-to-create-a-transparent-network-with-windows-containers/
https://4sysops.com/archives/windows-docker-networking-part-2-custom-network-types/
https://www.microsoftpressstore.com/articles/article.aspx?p=2756487&seqNum=2

**Comment by sssolammm** [comment]
Thanks for your time and your answer I will try it and I will give you my feedback.

**Comment by freddydk** [comment]
Transparent networks runs really well unless you are in a corporate network, where IP adresse allocation and network access is limited to specific/trusted machines.
