### ISSUE TITLE
Issues for two docker on same VM

### ISSUE THREAD

**Issue by anwar0206** [Microsoft/nav-docker#254]
Hi, Everyone!

We had installed nav bc on one docker which runs perfectly fine. The consultants can access it through web.

We created another container for our consultants on NAV 2018 CU3 with name DEMO in the same Azure VM.

The problem is another container provides the web address which works only in the localhost (Azure VM).

if we try to access the 2nd container outside the VM it throws error the web address we are trying is https://azurevmname.cloudapp.azure.com/DEMO

"**404 - File or directory not found.**"

Webaddress for 1st container is working fine https://azurevmname.cloudapp.azure.com/nav

I feel like the issue is around with PublicDNS name and the ports but do not have expertise to resolve it.

Below is the docker inspect for both the containers
container 1 navserver

[
    {
        "Id": "a5e71d7f09b2af76d6ca6d6561fd512a07b1e26f0cc07633bbea00c700ef1d5d",
        "Created": "2018-08-21T15:59:21.1664131Z",
        "Path": "powershell",
        "Args": [
            "-Command",
            "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
            ".\\Run\\start.ps1"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 6312,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-08-24T03:07:12.2365137Z",
            "FinishedAt": "2018-08-24T03:06:26.3685541Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2018-08-25T01:07:05.9552559+07:00",
                        "End": "2018-08-25T01:07:09.2512762+07:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-08-25T01:07:39.2643193+07:00",
                        "End": "2018-08-25T01:07:41.9942821+07:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-08-25T01:08:11.9939109+07:00",
                        "End": "2018-08-25T01:08:15.6688615+07:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-08-25T01:08:45.6702206+07:00",
                        "End": "2018-08-25T01:08:49.419195+07:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-08-25T01:09:19.4209675+07:00",
                        "End": "2018-08-25T01:09:22.2979465+07:00",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:240f9c4775f2845540df3407005d4d47dde8b0eb120d4b469b1b7967f8e85b34",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\docker\\containers\\a5e71d7f09b2af76d6ca6d6561fd512a07b1e26f0cc07633bbea00c700ef1d5d\\a5e71d7f09b2af76d6ca6d6561fd512a07b1e26f0cc07633bbea00c700ef1d5d-json.log",
        "Name": "/navserver",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "C:\\ProgramData\\NavContainerHelper:C:\\ProgramData\\NavContainerHelper",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\navserver\\my:C:\\Run\\my",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\navserver\\Program Files:C:\\navpfiles"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "443/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "443"
                    }
                ],
                "7046/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "7046"
                    }
                ],
                "7047/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "7047"
                    }
                ],
                "7048/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "7048"
                    }
                ],
                "7049/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "7049"
                    }
                ],
                "8080/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8080"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "process",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\docker\\windowsfilter\\a5e71d7f09b2af76d6ca6d6561fd512a07b1e26f0cc07633bbea00c700ef1d5d"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\navserver\\program files",
                "Destination": "c:\\navpfiles",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper",
                "Destination": "c:\\programdata\\navcontainerhelper",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\navserver\\my",
                "Destination": "c:\\run\\my",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "navserver",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "auth=NavUserPassword",
                "username=testuser",
                "ExitOnError=N",
                "locale=en-US",
                "licenseFile=",
                "databaseServer=",
                "databaseInstance=",
                "enableApiServices=Y",
                "enableSymbolLoading=Y",
                "useSSL=Y",
                "securePassword=AZQBiADcANwA3ADQAMAA0AGMANAA0ADcANwAxADUAZgBiAGEANgA5AGQAZABjAGYAMQA0ADIAZQAxAGEAYgBiADgAMgAyADAANAA2AGEAYQA=",
                "passwordKeyFile=c:\\run\\my\\aes.key",
                "removePasswordKeyFile=Y",
                "publicFileSharePort=8080",
                "PublicDnsName=xxx.xxxxx.cloudapp.azure.com",
                "RemovePasswordKeyFile=N",
                "clickonce=Y",
                "CustomNavSettings=EnableTaskScheduler=true",
                "accept_eula=Y",
                "COMPLUS_NGenProtectedProcess_FeatureEnabled=0",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/cf4fc037-5c90-4787-9a75-68f7b03696da",
                "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-0.16.19969.vsix",
                "IsBcSandbox=Y",
                "DatabaseName=FinancialsW1",
                "DEVPREVIEWURL=https://nav2016wswe0.blob.core.windows.net/dvd/1870421c-d88e-4cf8-bde7-5c73559571bb"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "microsoft/bcsandbox:latest-w1",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "W1",
                "created": "201807051154",
                "cu": "",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Dynamics SMB",
                "nav": "",
                "osversion": "10.0.14393.2312",
                "tag": "0.0.6.3",
                "version": "12.2.22932.23097"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "a6a1afd347cb62171a76a6d5af64b06e96bbec4e39a01124c8cca0155b90c4cb",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "443"
                    }
                ],
                "7045/tcp": null,
                "7046/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "7046"
                    }
                ],
                "7047/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "7047"
                    }
                ],
                "7048/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "7048"
                    }
                ],
                "7049/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "7049"
                    }
                ],
                "80/tcp": null,
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8080"
                    }
                ]
            },
            "SandboxKey": "a6a1afd347cb",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "708b148d6a4f5b14b764aac17f4e992c298f7348c790a06f13fbd29033348655",
                    "EndpointID": "c968fb6dffe7cb9f1e33c76fe83dd0cb706c2be1815552a9619764a71cc91d32",
                    "Gateway": "172.22.208.1",
                    "IPAddress": "172.22.212.23",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:6e:04:74",
                    "DriverOpts": null
                }
            }
        }
    }
]

Container 2 demo
[
    {
        "Id": "742c3dbe82bf717f3149f2e17d1b4c32d4a1ea23d4b0cf219d796e1952642821",
        "Created": "2018-08-24T17:43:01.2290966Z",
        "Path": "powershell",
        "Args": [
            "-Command",
            "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
            ".\\Run\\start.ps1"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 4900,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-08-24T17:43:04.8501912Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2018-08-25T01:10:59.2343614+07:00",
                        "End": "2018-08-25T01:11:03.2543603+07:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-08-25T01:11:33.2675463+07:00",
                        "End": "2018-08-25T01:11:34.4775458+07:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-08-25T01:12:04.5923292+07:00",
                        "End": "2018-08-25T01:12:07.333331+07:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-08-25T01:12:37.3956148+07:00",
                        "End": "2018-08-25T01:12:38.9356134+07:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-08-25T01:13:08.9593881+07:00",
                        "End": "2018-08-25T01:13:12.780388+07:00",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:581f89d7d2e971af31222c4637ede4ba4d1ae96660deee0c1e1b1db8fcddf805",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\docker\\containers\\742c3dbe82bf717f3149f2e17d1b4c32d4a1ea23d4b0cf219d796e1952642821\\742c3dbe82bf717f3149f2e17d1b4c32d4a1ea23d4b0cf219d796e1952642821-json.log",
        "Name": "/DEMO",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "C:\\ProgramData\\NavContainerHelper:C:\\ProgramData\\NavContainerHelper",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\DEMO\\my:C:\\Run\\my",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\DEMO\\Program Files:C:\\navpfiles",
                "c:\\windows\\system32\\drivers\\etc:C:\\driversetc"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "process",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\docker\\windowsfilter\\742c3dbe82bf717f3149f2e17d1b4c32d4a1ea23d4b0cf219d796e1952642821"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\windows\\system32\\drivers\\etc",
                "Destination": "c:\\driversetc",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper",
                "Destination": "c:\\programdata\\navcontainerhelper",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\demo\\my",
                "Destination": "c:\\run\\my",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\demo\\program files",
                "Destination": "c:\\navpfiles",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "DEMO",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "auth=NavUserPassword",
                "username=testuser",
                "ExitOnError=N",
                "locale=en-US",
                "licenseFile=",
                "databaseServer=",
                "databaseInstance=",
                "authenticationEMail=user@hotmail.com",
                "useSSL=Y",
                "securePassword=gAMwAxADgAZgBjAGQAZgA0ADEAMgBiADMANQBkAGUAZAAwAGYAZgBjADcAMwAyADYANQBiAGIANwBkADEANABkADMANgBiADMANQA2ADEANAA=",
                "passwordKeyFile=c:\\run\\my\\aes.key",
                "removePasswordKeyFile=Y",
                "bakfile=c:\\run\\my\\demo.bak",
                "accept_eula=Y",
                "COMPLUS_NGenProtectedProcess_FeatureEnabled=0",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/e61d47a7-3bb4-418f-9487-91044afd8c79",
                "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-0.12.17720.vsix",
                "DatabaseName=CRONUS"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "microsoft/dynamics-nav:2018-cu3-w1",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "W1",
                "created": "201806141104",
                "cu": "cu3",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=826604",
                "maintainer": "Dynamics SMB",
                "nav": "2018",
                "osversion": "10.0.14393.2312",
                "tag": "0.0.6.3",
                "version": "11.0.20783.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "63d739129f101eb280a320fd81aa861940e10ce180ee95971f90908277f153c1",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "80/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "63d739129f10",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "708b148d6a4f5b14b764aac17f4e992c298f7348c790a06f13fbd29033348655",
                    "EndpointID": "4f3121c9bc8fefd21704aa46298d3a5929976d2093104e8d21a03368b47bd4e6",
                    "Gateway": "172.22.208.1",
                    "IPAddress": "172.22.212.115",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:6e:0d:e8",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by freddydk** [comment]
I think you misunderstood something.
You can only forward ports from the public dns to a container, you cannot direct traffic to containers based on /nav or /demo.
This means that you can create a container and map another port (like 8443) to 443 inside the container and through that get to web client on the demo container.
You still use nav as instance name, nav is hardcoded as instance name.
Remember to se publicWebClientPort to 8443 if you map that port to 443.

**Comment by anwar0206** [comment]
Hi Freddy,

Thanks for providing the details,

I tried with your suggestion and getting the following error

Script
$publicdnsName = "xxxx.xxxx.cloudapp.azure.com"

New-NavContainer -containerName demo -accept_eula  -additionalParameters @('--env bakfile="c:\run\my\demo.bak"','--publish  9080:8080','--publish  1026:443',
'--publish  7146-7149:7046-7049','--env publicFileSharePort=9080','--env PublicDnsName=$publicdnsName',
'--env "c:\myfolder:c\run\my"','--env bakfile="c:\temp\demo.bak"','--env publicWebClientPort=1026') 
-auth NavUserPassword 
-authenticationEMail user@hotmail.com 
-Credential testuser 
-doNotExportObjectsToText 
-imageName microsoft/dynamics-nav:2018-cu3-w1 
-includeCSide -isolation process 
-myScripts "C:\myfolder"
-restart unless-stopped 
-shortcuts Desktop 
-updateHosts 
-useSSL

Error
Creating Nav container DEMO
Using image microsoft/bcsandbox:latest-w1
NAV Version: 12.2.22932.23097-W1
Generic Tag: 0.0.6.3
Removing container DEMO
Removing C:\ProgramData\NavContainerHelper\Extensions\DEMO
Creating container DEMO from image microsoft/bcsandbox:latest-w1
befb992072a7582c45fe8e5a95f48c085117cf736f71597a046306d3e719c70a

DockerDo : docker.exe: Error response from daemon: failed to create endpoint DEMO on network nat: HNS failed with 
error : Unspecified error.
Commandline: docker run --name DEMO --hostname DEMO --env auth=Windows --env username="testuser" --env ExitOnError=N 
--env locale=en-US --env licenseFile="" --env databaseServer="" --env databaseInstance="" --volume 
"C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContainerHelper" --volume 
"C:\ProgramData\NavContainerHelper\Extensions\DEMO\my:C:\Run\my" --restart unless-stopped --env enableApiServices=Y 
--env useSSL=N --env securePassword=7649AVYQBjADQANwBhAGUAMQAwAGIAOQA= --env 
passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env bakfile="c:\run\my\demo.bak" --publish  
9080:8080 --publish  1026:443 --publish  7146-7149:7046-7049 --env publicFileSharePort=9080 --env 
PublicDnsName=$publicdnsName --env "c:\myfolder:c\run\my" --env bakfile="c:\temp\demo.bak" --env 
publicWebClientPort=1026 --env accept_eula=Y --detach microsoft/bcsandbox:latest-w1
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.3.0.2\ContainerHandling\New-NavContainer.ps1:462 
char:19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

Any suggestion why my script is generating error

Thanking you in advance

**Comment by freddydk** [comment]
In your script, where you specify $publicdnsname, that should be in double quotes (“) in order to be replaced with the value in your variable. Not sure that is the reason, but it could be.

Få Outlook til iOS<https://aka.ms/o0ukef>

________________________________
Fra: anwar0206 <notifications@github.com>
Sendt: fredag, august 24, 2018 11:15 PM
Til: Microsoft/nav-docker
Cc: Freddy Kristiansen; Comment
Emne: Re: [Microsoft/nav-docker] Issues for two docker on same VM (#254)


Hi Freddy,

Thanks for providing the details,

I tried with your suggestion and getting the following error

Script
$publicdnsName = "xxxx.xxxx.cloudapp.azure.com"

New-NavContainer -containerName demo -accept_eula -additionalParameters @('--env bakfile="c:\run\my\demo.bak"','--publish 9080:8080','--publish 1026:443',
'--publish 7146-7149:7046-7049','--env publicFileSharePort=9080','--env PublicDnsName=$publicdnsName',
'--env "c:\myfolder:c\run\my"','--env bakfile="c:\temp\demo.bak"','--env publicWebClientPort=1026')
-auth NavUserPassword
-authenticationEMail user@hotmail.com<mailto:user@hotmail.com>
-Credential testuser
-doNotExportObjectsToText
-imageName microsoft/dynamics-nav:2018-cu3-w1
-includeCSide -isolation process
-myScripts "C:\myfolder"
-restart unless-stopped
-shortcuts Desktop
-updateHosts
-useSSL

Error
Creating Nav container DEMO
Using image microsoft/bcsandbox:latest-w1
NAV Version: 12.2.22932.23097-W1
Generic Tag: 0.0.6.3
Removing container DEMO
Removing C:\ProgramData\NavContainerHelper\Extensions\DEMO
Creating container DEMO from image microsoft/bcsandbox:latest-w1
befb992072a7582c45fe8e5a95f48c085117cf736f71597a046306d3e719c70a

DockerDo : docker.exe: Error response from daemon: failed to create endpoint DEMO on network nat: HNS failed with
error : Unspecified error.
Commandline: docker run --name DEMO --hostname DEMO --env auth=Windows --env username="testuser" --env ExitOnError=N
--env locale=en-US --env licenseFile="" --env databaseServer="" --env databaseInstance="" --volume
"C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContainerHelper" --volume
"C:\ProgramData\NavContainerHelper\Extensions\DEMO\my:C:\Run\my" --restart unless-stopped --env enableApiServices=Y
--env useSSL=N --env securePassword=7649AVYQBjADQANwBhAGUAMQAwAGIAOQA= --env
passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env bakfile="c:\run\my\demo.bak" --publish
9080:8080 --publish 1026:443 --publish 7146-7149:7046-7049 --env publicFileSharePort=9080 --env
PublicDnsName=$publicdnsName --env "c:\myfolder:c\run\my" --env bakfile="c:\temp\demo.bak" --env
publicWebClientPort=1026 --env accept_eula=Y --detach microsoft/bcsandbox:latest-w1
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.3.0.2\ContainerHandling\New-NavContainer.ps1:462
char:19

  *   ... if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
  *

            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


     *   CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
     *   FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

Any suggestion why my script is generating error

Thanking you in advance

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fnav-docker%2Fissues%2F254%23issuecomment-415884412&data=02%7C01%7Cfreddy.kristiansen%40microsoft.com%7C23f0b81bc7344f67af1f08d60a06ab61%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636707421091046877&sdata=1%2FXTLG9vOIEe1dW15nKsNIAnWdYSUgEAY3VpTcSivX0%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKRqA_1espVqM-4R9I4wWO8d_f6aZwLyks5uUGzbgaJpZM4WLyWT&data=02%7C01%7Cfreddy.kristiansen%40microsoft.com%7C23f0b81bc7344f67af1f08d60a06ab61%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636707421091056886&sdata=QPV39htXohYJb1nYRqrpDTlhyF5ah0D70h6m5QWP5uo%3D&reserved=0>.

**Comment by anwar0206** [comment]
Hi,

Tried with double quotes too, but getting same error.

**Comment by anwar0206** [comment]
Hi Freddy,

You are an Rock Star :)

Thanks for your inputs and script, much appreciated.

Your script worked very well and was able to have second VM without issues.

Only one glitch was that, when tried to access the second VM in EDGE it didn't worked but the first VMof BC was working fine.

The Second VM was able to access in Chrome.

Thanks a lot for giving us support and ideas

**Comment by freddydk** [comment]
Not sure why, but you are right that you cannot access two different instances of NAV on different ports this way with the same browser. It seems like a browser gets "tied" to an instance.
(Both Edge and Chrome)
This seems like a problem - you only have so many different browsers - let me investigate.

**Comment by freddydk** [comment]
InPrivate is your friend.
![image](https://user-images.githubusercontent.com/10775043/44643160-c8622600-a9cf-11e8-866e-1b740adea253.png)
Apparently Web Client sessions are stored on the domain name. If you want to avoid this, you would need a star certificate and a number of DNS records pointing to the same VM, potentially with multiple IP addresses to avoid different ports etc. - it can be done, but requires more setup.

**Comment by freddydk** [comment]
Images are being rebuilt now with new endpoint port environment variables created.
