### ISSUE TITLE
Failed to register layer

### ISSUE THREAD

**Issue by robertosb** [Microsoft/nav-docker#255]
Hi team, 

   I wonder if anyone got this error before when installing a new docker container and after all the packages complete download: "
![image](https://user-images.githubusercontent.com/39469150/44702306-e66e7a00-aae6-11e8-90a7-e989f6ef42b1.png)
"
Interesting enough, everything else completes after this and docker is running successfully, but something failed it seems.
Could this be related to another container running on the machine?

**Comment by Koubek** [comment]
Docker is normally consistent (transactional) during all these operations. I haven't seen it before. 

Have you been trying to do manual adjustments in the docker data folders? 
Do you use any experimental/edge version of Docker?
Do you run the container on Win10 or on WinServer2016?

Please, can you provide any relevant details?

**Comment by robertosb** [comment]
No manual adjustments done in any docker data folders.
Docker for Windows, writing from my mobile but I will come back tomorrow with a version.
Windows 10 but I did see a note from Waldo that he prefers to run docker in winServer2016 because of docker memory performance. I suppose I can spin up a vm to run docker inside...don't know if that's overkill or standard practice, what do you use?

**Comment by robertosb** [comment]
Thank you for your reply, it does make sense. 
I will provide my docker version and I will also stop all containers and download this one again before my update tomorrow.
- I only have Nav containers installed.
- there are more that I've installed over a longer period of time and all were fine before and are still running.

I wonder if there is some sort of reset...I guess I can always remove and install docker for Windows again which should in theory resolve anything that any docker update and/or container would break. 
At least it's logged here in case any of these work we can always refer back to it, cause there was no similar error logged.

**Comment by Koubek** [comment]
Yes, you can reset your docker environment - GUI (it will prune all your Docker containers and images AFAIK). You can, of course, run some commands to do the same using CLI.

**Comment by robertosb** [comment]
Hi Jakub, I will close this one as installing the container again sorted the issue.
Steps taken: 
- a computer restart
- manual starting of docker as administrator (which I believe I've done last time too)
- stopping all the other containers

I am also pasting below the printscreen with my docker version in case anyone experiences this error in the future:
![image](https://user-images.githubusercontent.com/39469150/44758122-c1c9df00-ab86-11e8-895e-d8819856f038.png)
