### ISSUE TITLE
latest image bcsandbox:us container  

### ISSUE THREAD

**Issue by shashiBssi** [Microsoft/nav-docker#256]
latest image bcsandbox:us container  . can't open business on  chrome but on can open on edge.

not able to download sysmbols.

**Comment by freddydk** [comment]
You will have to provide some more info if you want somebody to help

Like:
What is the full name of the image? (public or insider)
Are you using SSL or not?
How do you create the image?
What does docker inspect say?
What authentication do you use?

Just as much info as possible to allow us to help you figure out what is wrong on your machine.

**Comment by shashiBssi** [comment]
I pulled the image using
docker pull microsoft/bcsandbox:us

created container using new-navcontainer. didn't chose useSSL.

Authentication used : navUserPassword

docker inspect>>
[
    {
        "Id": "4c0a2a71cb9fa8cc00a95f93db66fea025e2fa7161be1c5687ae32321b10df5d",
        "Created": "2018-08-30T05:41:30.2166188Z",
        "Path": "powershell",
        "Args": [
            "-Command",
            "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
            ".\\Run\\start.ps1"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1952,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-08-30T07:43:09.4166223Z",
            "FinishedAt": "2018-08-30T12:42:14.1062025+05:30",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2018-08-30T14:15:49.5755426+05:30",
                        "End": "2018-08-30T14:15:50.4598711+05:30",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-08-30T14:16:20.503299+05:30",
                        "End": "2018-08-30T14:16:21.0642598+05:30",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-08-30T14:16:51.1275677+05:30",
                        "End": "2018-08-30T14:16:51.7309038+05:30",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-08-30T14:17:21.7676367+05:30",
                        "End": "2018-08-30T14:17:22.6417698+05:30",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2018-08-30T14:17:52.6930223+05:30",
                        "End": "2018-08-30T14:17:53.3060246+05:30",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:9b8eed4d233a7447d1ce2b4571ef7c30f518a92bcc8631bed4226022870548fd",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\Docker\\containers\\4c0a2a71cb9fa8cc00a95f93db66fea025e2fa7161be1c5687ae32321b10df5d\\4c0a2a71cb9fa8cc00a95f93db66fea025e2fa7161be1c5687ae32321b10df5d-jso
n.log",
        "Name": "/dev",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": [
            "4b19bf2ae09f28163c5f937908ea00b0bcda8e206916c4e825819cfd9ac28475",
            "2a8fd09ed9393be06dbffa24b34751abdbc7f3bdaa74d8c07ac7670f40e847fc"
        ],
        "HostConfig": {
            "Binds": [
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\dev\\Program Files:C:\\navpfiles",
                "C:\\ProgramData\\NavContainerHelper:C:\\ProgramData\\NavContainerHelper",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\dev\\my:C:\\Run\\my"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "hyperv",
            "CpuShares": 0,
            "Memory": 4294967296,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\windowsfilter\\4c0a2a71cb9fa8cc00a95f93db66fea025e2fa7161be1c5687ae32321b10df5d"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\dev\\my",
                "Destination": "c:\\run\\my",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\dev\\program files",
                "Destination": "c:\\navpfiles",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper",
                "Destination": "c:\\programdata\\navcontainerhelper",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "dev",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "accept_eula=Y",
                "auth=NavUserPassword",
                "locale=en-US",
                "licenseFile=c:\\run\\my\\license.flf",
                "databaseServer=",
                "enableApiServices=Y",
                "useSSL=N",
                "securePassword=76492d1116743f0423413b16050a5345MgB8AEwAZwBRAFEAKwBlAFUAQQBSAFgAdAB4AGkAVABRAFUAYgAvAEQAQgBOAHcAPQA9AHwAYQAxADMANgAxAGUANwAxADIAMQA1AGYAYgBiAGUAMQAzADQAMgA2ADU
ANQBmAGYAMABlAGEAZgBhAGQAMgA4AGEANQAyADUAZAA1AGYANABhADIAYgA2ADgAMAAxADAAZQBhADIAMwAwAGIAYwAzADEANQA3ADcAZAAzADMAOAA=",
                "username=shashi",
                "ExitOnError=N",
                "databaseInstance=",
                "passwordKeyFile=c:\\run\\my\\aes.key",
                "removePasswordKeyFile=Y",
                "COMPLUS_NGenProtectedProcess_FeatureEnabled=0",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/fca3a4c6-727a-4b3d-b1b5-eb7e4c5a1378",
                "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-0.16.26913.vsix",
                "IsBcSandbox=Y",
                "DatabaseName=FinancialsUS",
                "DEVPREVIEWURL=https://nav2016wswe0.blob.core.windows.net/dvd/b420116a-86f7-4921-a243-4b6ae26baade"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "microsoft/bcsandbox:us",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "US",
                "created": "201808281321",
                "cu": "",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Dynamics SMB",
                "nav": "",
                "osversion": "10.0.14393.2430",
                "tag": "0.0.6.5",
                "version": "12.3.23590.23945"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "4c0a2a71cb9fa8cc00a95f93db66fea025e2fa7161be1c5687ae32321b10df5d",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "80/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "4c0a2a71cb9fa8cc00a95f93db66fea025e2fa7161be1c5687ae32321b10df5d",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "bdd9f95d49c1cb85590726b1cc43393db97e44ee78c56b96e97e63e906be8ecf",
                    "EndpointID": "59b69068286de3b2f4961e4bba4eb4546ec335bea24864c8efe84461a71a876c",
                    "Gateway": "172.23.144.1",
                    "IPAddress": "172.23.154.153",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:e2:80:73",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by freddydk** [comment]
did you try to clear cached credentials in VS Code?
and remove passwords etc. from Chrome (+restart Chrome)?
I am using that exact image here (with Chrome)

**Comment by shashiBssi** [comment]
I cleared cached credentials in VS Code.
no saved password in chrome.
cleared everything

**Comment by freddydk** [comment]
Did you restart chrome?
Did you name the container the same as an earlier container?

**Comment by shashiBssi** [comment]
restarted chrome multiple times.
no i created entire new container with new name.

**Comment by freddydk** [comment]
What error is Chrome displaying?
Can you ping the container?

**Comment by shashiBssi** [comment]
i can ping the container.


chrome ::



![image](https://user-images.githubusercontent.com/38439762/44843319-ad104880-ac65-11e8-8b39-e0d810c0068b.png)

**Comment by shashiBssi** [comment]
Created another container with same image and ..... its working fine.
