### ISSUE TITLE
Docker version for BC On-Prem available?

### ISSUE THREAD

**Issue by elweilando** [Microsoft/nav-docker#257]
I don't know if this is the right place for this question, but is there also a docker container for the latest released Business Central On-Premise Partner Preview 02?

**Comment by freddydk** [comment]
On-Prem docker images will be there very soon

**Comment by sssolammm** [comment]
Hi,

It has been realsed where can I find docker version to test it? @freddydk 

Thanks,

**Comment by freddydk** [comment]
More info available here: https://hub.docker.com/r/microsoft/bconprem/
