### ISSUE TITLE
Permission Error on CodeUnit Create Demonstration Data with template bcsandbox-master:base

### ISSUE THREAD

**Issue by xgaronnat** [Microsoft/nav-docker#258]
Hi,

With a fresh new VM created with template `bcinsider.azurecr.io/bcsandbox-master:base`, the web/nav client report the same error on first connexion with admin account : 

> You do not have the following permissions on CodeUnit Create Demonstration Data: Execute.

Thanks for your help,
Xavier.

**Comment by freddydk** [comment]
This is because the default license on the base docker images isn't up to date.
You should specify your partner license when starting the container, then the problem should go away.
Will try to get it fixed asap.

**Comment by xgaronnat** [comment]
Thanks Freddy.
Dummy question : does I have a possibility to upgrade the license inside the container/docker ? (instead of recreating the VM from scratch)

**Comment by xgaronnat** [comment]
It's ok ; license upgraded with CSide client and container restarted.

**Comment by freddydk** [comment]
You also have the NavContainerHelper PowerShell prompt, which where you will find a function called Import-NavContainerLicense.
