### ISSUE TITLE
ClickOnce: CommandLine.dll not found

### ISSUE THREAD

**Issue by lippertmarkus** [Microsoft/nav-docker#26]
When using a NAV-DVD before NAV 2018 CTP 09 the CommandLine.dll is not present what results in following error:
```
Copy-Item : Cannot find path 'C:\Program Files (x86)\Microsoft Dynamics NAV\100\RoleTailored Client\Commandline.dll' because it does not exist.
At C:\Run\SetupClickOnceDirectory.ps1:41 char:1
+ Copy-Item "$roleTailoredClientFolder\Commandline.dll"                 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...Commandline.dll:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
```

For supporting older NAV-Versions there should be a `Test-Path` or just an `-ErrorAction SilentlyContinue` for this line:
https://github.com/Microsoft/nav-docker/blob/9e52d4cf7c6e6e0538f6e79490db3e311fd7e8bd/Run/SetupClickOnceDirectory.ps1#L41

**Comment by freddydk** [comment]
Yes, you are right.
This will be fixed and new images rebuilt in a few days.
If you need to run an image before the fix, you can fix the file and share it into c:\run\my, then it will override the original file in c:\run as described in the how-to.

**Comment by freddydk** [comment]
This is fixed, images not rebuild yet, but will be within the next days
