### ISSUE TITLE
LetsEncrypt RenewCertificate.ps1 throws error

### ISSUE THREAD

**Issue by AlphaGeeKUK** [Microsoft/nav-docker#260]
I am trying the procedure for renewing a LetsEncrypt certificate (as per https://github.com/Microsoft/nav-docker/issues/217) and it is throwing the error shown below. The container is basically broken at this point.

`PS C:\demo> C:\DEMO\RenewCertificate.ps1
Requesting certificate

Id                       : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f
Alias                    : *****.westeurope.cloudapp.azure.com-2018-09-17--14-50
Label                    : 
Memo                     : 
IdentifierRef            : 097701a6-602f-45ea-b847-91596eac405f
IdentifierDns            : *****.westeurope.cloudapp.azure.com
AlternativeIdentifierDns : 
KeyPemFile               : 
CsrPemFile               : 
GenerateDetailsFile      : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-gen.json
CertificateRequest       : 
CrtPemFile               : 
CrtDerFile               : 
IssuerSerialNumber       : 
SerialNumber             : 
Thumbprint               : 
Signature                : 
SignatureAlgorithm       : 
RevokedAt                : 

Id                       : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f
Alias                    : ******.westeurope.cloudapp.azure.com-2018-09-17--14-50
Label                    : 
Memo                     : 
IdentifierRef            : 097701a6-602f-45ea-b847-91596eac405f
IdentifierDns            : ******.westeurope.cloudapp.azure.com
AlternativeIdentifierDns : 
KeyPemFile               : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-key.pem
CsrPemFile               : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-csr.pem
GenerateDetailsFile      : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-gen.json
CertificateRequest       : ACMESharp.CertificateRequest
CrtPemFile               : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-crt.pem
CrtDerFile               : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-crt.der
IssuerSerialNumber       : 
SerialNumber             : 0349570D18AF4EA30B5C5F97765EA4FB1C74
Thumbprint               : BFE6E9ACF4D793F026A1416977E078A1ECCDCFBF
Signature                : BFE6E9ACF4D793F026A1416977E078A1ECCDCFBF
SignatureAlgorithm       : sha256RSA
RevokedAt                : 

Id                       : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f
Alias                    : *****.westeurope.cloudapp.azure.com-2018-09-17--14-50
Label                    : 
Memo                     : 
IdentifierRef            : 097701a6-602f-45ea-b847-91596eac405f
IdentifierDns            : ******.westeurope.cloudapp.azure.com
AlternativeIdentifierDns : 
KeyPemFile               : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-key.pem
CsrPemFile               : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-csr.pem
GenerateDetailsFile      : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-gen.json
CertificateRequest       : ACMESharp.CertificateRequest
CrtPemFile               : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-crt.pem
CrtDerFile               : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-crt.der
IssuerSerialNumber       : 0A0141420000015385736A0B85ECA708
SerialNumber             : 0349570D18AF4EA30B5C5F97765EA4FB1C74
Thumbprint               : BFE6E9ACF4D793F026A1416977E078A1ECCDCFBF
Signature                : BFE6E9ACF4D793F026A1416977E078A1ECCDCFBF
SignatureAlgorithm       : sha256RSA
RevokedAt                : 

Downloading c:\ProgramData\navcontainerhelper\certificate.pfx
Id                       : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f
Alias                    : *****.westeurope.cloudapp.azure.com-2018-09-17--14-50
Label                    : 
Memo                     : 
IdentifierRef            : 097701a6-602f-45ea-b847-91596eac405f
IdentifierDns            : ******.westeurope.cloudapp.azure.com
AlternativeIdentifierDns : 
KeyPemFile               : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-key.pem
CsrPemFile               : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-csr.pem
GenerateDetailsFile      : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-gen.json
CertificateRequest       : ACMESharp.CertificateRequest
CrtPemFile               : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-crt.pem
CrtDerFile               : 02ad42e9-431d-4117-8d7c-8e9c73b90c9f-crt.der
IssuerSerialNumber       : 0A0141420000015385736A0B85ECA708
SerialNumber             : 0349570D18AF4EA30B5C5F97765EA4FB1C74
Thumbprint               : BFE6E9ACF4D793F026A1416977E078A1ECCDCFBF
Signature                : BFE6E9ACF4D793F026A1416977E078A1ECCDCFBF
SignatureAlgorithm       : sha256RSA
RevokedAt                : 

Waiting for container navserver to be ready

Initializing...
Restarting Container
Hostname is navserver
PublicDnsName is *****.westeurope.cloudapp.azure.com
Using AccessControlService Authentication
Starting Local SQL Server
Starting Internet Information Server
Certificate File Thumbprint BFE6E9ACF4D793F026A1416977E078A1ECCDCFBF
Import Certificate to LocalMachine\my
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to true
Changing Server config to NavUserPassword to enable basic web services
Starting NAV Service Tier
Creating DotNetCore Web Server Instance
Access to the path 'libuv.dll' is denied.
at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\123\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: 
line 543
at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\123\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagem
ent.psm1: line 483
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 18
at <ScriptBlock>, C:\Run\navstart.ps1: line 137
at <ScriptBlock>, C:\Run\start.ps1: line 107
at <ScriptBlock>, <No file>: line 1Error

Initializing...
Restarting Container
Hostname is navserver
PublicDnsName is *****.westeurope.cloudapp.azure.com
Using AccessControlService Authentication
Starting Local SQL Server
Starting Internet Information Server
Certificate File Thumbprint BFE6E9ACF4D793F026A1416977E078A1ECCDCFBF
Import Certificate to LocalMachine\my
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to true
Changing Server config to NavUserPassword to enable basic web services
Starting NAV Service Tier
Creating DotNetCore Web Server Instance
Access to the path 'libuv.dll' is denied.
at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\123\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: 
line 543
at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\123\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagem
ent.psm1: line 483
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 18
at <ScriptBlock>, C:\Run\navstart.ps1: line 137
at <ScriptBlock>, C:\Run\start.ps1: line 107
at <ScriptBlock>, <No file>: line 1
Initialization of container navserver failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.3.1.1\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...avserver failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container navserver failed
 

PS C:\demo> `

**Comment by freddydk** [comment]
Not sure what went wrong here - I will investigate.
In the meantime, I think you can remove the letsencrypt email value in the c:\demo\settings.ps1 file and run replace-navservercontainer - then I think it will create a self-signed cert.

**Comment by AlphaGeeKUK** [comment]
![2018-09-17 15_34_16-certificate viewer_ server westeurope cloudapp azure com](https://user-images.githubusercontent.com/38461848/45629943-7e7cd500-ba8f-11e8-8858-60084d973c81.png)
Thanks Freddy. I removed the letsencrypt email value and ran replace-navservercontainer and it has come back to life. However, look at the SSL cert in a browser it's still the letsencrypt one.

**Comment by freddydk** [comment]
You might need to remove Setup-Certificate.ps1 from c:\myfolder (or rename it to .old)

**Comment by AlphaGeeKUK** [comment]
Ok, I will just leave it as is for now. The October release is not too far away so won't need this VM for long.
