### ISSUE TITLE
Edit in Excel - not in Sandbox?

### ISSUE THREAD

**Issue by AlphaGeeKUK** [Microsoft/nav-docker#261]
I created a new machine following the directions here - https://blogs.msdn.microsoft.com/freddyk/2018/06/29/aad-authentication/

- using image microsoft/bcsandbox:gb

When I try to test the Edit in Excel function, I am told "The Excel Add-in is currently not available in sandbox environments.'

**Comment by freddydk** [comment]
If you use the on-prem image instead (https://hub.docker.com/r/microsoft/bconprem/) you should be able to use edit-in-excel.
