### ISSUE TITLE
Environment variable ManagementServicesPort isn't properly implemented in nav-docker

### ISSUE THREAD

**Issue by atlastfree** [Microsoft/nav-docker#262]
Environment variable ManagementServicesPort isn't properly implemented in nav-docker

Regarding “Microsoft Dynamics Nav” or “Microsoft Business Central” docker images based on generic build 0.0.6.5 (maybe also generic build 0.0.6.6).

When using the ManagementServicesPort environment variable with “DOCKER RUN” or “New-NavContainer”, the Nav Web Server Instance isn't properly setup, the Management Service Port isn't set accordingly the ManagementServicesPort environment variable, so the website always tries to communicate with the Nav Management Service using standard port 7045…

Can be fixed after the container is created, remark that the container name varies with your implementation (of “DOCKER RUN” or “New-NavContainer”) (change NL69-DBC10 accordingly), remark also that the path to the “NavAdminTool.ps1” file varies with the “Microsoft Dynamics Nav” or “Microsoft Business Central” version, remark further that the Management Service port number varies with your implementation, execute from your ISE PowerShell prompt:

PS C:\WINDOWS\system32> $CntrPrps = docker container inspect NL69-DBC10 --format '{{json .}}' | ConvertFrom-Json

PS C:\WINDOWS\system32> Enter-PSSession -ContainerId $CntrPrps.Id -RunAsAdministrator

[b08f585102c3...]: PS C:\Users\ContainerAdministrator\Documents> Invoke-Expression -command "& 'C:\Program Files\Microsoft Dynamics NAV\110\service\NavAdminTool.ps1'"

Welcome to the Server Admin Tool Shell!
For a complete list of Server cmdlets type

Get-Command -Module Microsoft.Dynamics.Nav.Management, Microsoft.Dynamics.Nav.Apps.Management

[b08f585102c3...]: PS C:\Users\ContainerAdministrator\Documents> Get-NAVWebServerInstanceConfiguration -WebServerInstance NAV -KeyName ManagementServicesPort
7045

[b08f585102c3...]: PS C:\Users\ContainerAdministrator\Documents> Set-NAVWebServerInstanceConfiguration -WebServerInstance NAV -KeyName ManagementServicesPort -KeyValue '50145'

[b08f585102c3...]: PS C:\Users\ContainerAdministrator\Documents> Get-NAVWebServerInstanceConfiguration -WebServerInstance NAV -KeyName ManagementServicesPort
50145

[b08f585102c3...]: PS C:\Users\ContainerAdministrator\Documents> Exit-PSSession

**Comment by freddydk** [comment]
Thanks for the detailed explanation and sorry for the long delay.
This will be fixed in 0.0.8.1

**Comment by freddydk** [comment]
Generic 0.0.8.1 has been created and the latest insider builds are using this.
examples:
bcinsider.azurecr.io/bcsandbox:us-ltsc2019
and
bcinsider.azurecr.io/bcsandbox-master:us-ltsc2019
Please try them out.
Another round of full rebuilds is scheduled to next week.

**Comment by freddydk** [comment]
Everything has been rebuilt
