### ISSUE TITLE
Error while running bcinsider.azurecr.io/bconprem:13.0.24573.0

### ISSUE THREAD

**Issue by gintuoklis** [Microsoft/nav-docker#264]
Hey Guys, 

I get following error while trying to run BC RC3 docker image: 
`docker run -e accept_eula=Y bcinsider.azurecr.io/bconprem:13.0.24573.0 -m 3G`

`C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 35a1fa300bc955e2d7a6daf21702c7ae5862028985b54d29d79c0faee05109a1 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"-m 3G","WorkingDirectory":"C:\\","Environment":{"COMPLUS_NGenProtectedProcess_FeatureEnabled":"0","DatabaseInstance":"SQLEXPRESS","DatabaseName":"CRONUS","DatabaseServer":"localhost","NAVDVDURL":"https://nav2016wswe0.blob.core.windows.net/dvd/e561bfde-19bd-4242-b44e-77699ccd2879","VSIXURL":"https://nav2016wswe0.blob.core.windows.net/dvd/al-2.0.43900.vsix","accept_eula":"Y"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}.`

Any advice?

Best Regards, 
Gintautas

**Comment by freddydk** [comment]
Just tried this using the navcontainerhelper
`New-NavContainer -accept_eula -containerName test -imageName bcinsider.azurecr.io/bconprem
`Works fine here - it looks like something with your setup.
Have you been able to run other Business Central containers?

**Comment by gintuoklis** [comment]
I got the same error while running another image (bconprem:latest)
If i use navcontainerhelper script everything works fine. Any hint what could be wrong with my setup?

**Comment by freddydk** [comment]
Just noticed the problem.
All parameters needs to be before the imagename. Try:
docker run -e accept_eula=Y -m 3G bcinsider.azurecr.io/bconprem:13.0.24573.0

**Comment by gintuoklis** [comment]
Thanks, 
It' solved the problem.
