### ISSUE TITLE
Issue when pulling image from bcinsider.azurecr.io

### ISSUE THREAD

**Issue by SUD-D365** [Microsoft/nav-docker#265]
Hi @freddydk 
I am getting below error , when creating a new container.
Even I turned off the firewall also.

![image](https://user-images.githubusercontent.com/33481576/46002039-91645a80-c0ca-11e8-8db4-777aaf0a9beb.png)
 
Kindly help
Sudarshan

**Comment by freddydk** [comment]
Unauthorized doesn't sound like a firewall problem, it sounds like you haven't logged into the bcinsider registry.
Username and Password are available on Microsoft Collaborate under NDA.

**Comment by SUD-D365** [comment]
Okk @freddydk  thanks
Let me check with it.

**Comment by SUD-D365** [comment]
Hi @freddydk 
Where it should be?
![image](https://user-images.githubusercontent.com/33481576/46003757-e609d480-c0ce-11e8-9a05-733c608b808b.png)

**Comment by freddydk** [comment]
docker login allows you to authenticate to a registry.
You need to be part of the Ready for Business Central Engagement.
You can reach out to dyn365bep@microsoft.com in order to get access.

**Comment by SUD-D365** [comment]
Thanks @freddydk  for your help.
