### ISSUE TITLE
Idea to improve Dev Environment ClickOnce

### ISSUE THREAD

**Issue by ChrisBlankDe** [Microsoft/nav-docker#266]
If the Development Client was installed via ClickOnce it will always connect to the last used database. This is annoying when working with multiple containers based on different NAV major releases.
Its technically not possible to give the required parameters to finsql.exe.

How about if we generate an executable when creating the container which executes the Development Client with the required parameters. 
This new executable is then defined as entry point in the Click Once.

Useful parameters would be servername, database and id.
Maybe some else?

What do you think of that?

**Comment by freddydk** [comment]
Building executables on the fly doesn't seem like something I want to pursue.
Maybe a CMD file can do this?
I would consider a PR with a solution like this.

Personally, I don't use the clickonce deployment, I use (and recommend people use) navcontainerhelper, which create shortcuts on the desktop with exactly these parameters.

**Comment by ChrisBlankDe** [comment]
A CMD or BAT file can't be the Entry Point of an ClickOnce Application.
I will create a pull request in the next weeks, then you can consider if you want to include this in the module or if we have to work with an overwrite script.
