### ISSUE TITLE
Docker image for Business Central OnPrem

### ISSUE THREAD

**Issue by sssolammm** [Microsoft/nav-docker#269]
Hi,

I read few days ago that BC OnPrem was release past 1Oct. Where I can find image docker to test it? I didn't find it in BC docker documentation.

Thanks,

**Comment by freddydk** [comment]
Read about how to pull it here: https://hub.docker.com/r/microsoft/bconprem/ - but we have some license problems in this, which is one of the reasons that we haven't blogged about the presence yet.

**Comment by sssolammm** [comment]
Ok I will read it.

Thanks,

**Comment by shashiBssi** [comment]
@freddydk
What's the difference between bcsandbox and mcr.microsoftcom/businesscentral/onprem

Which one should be used as an ISV ?

**Comment by freddydk** [comment]
Spelling mistake in some of the samples (a missing dot) - has been fixed 

docker pull mcr.microsoft.com/businesscentral/onprem

/Freddy
