### ISSUE TITLE
How can I Share a folder from container to the host system?

### ISSUE THREAD

**Issue by megel** [Microsoft/nav-docker#27]
I want to share the RTC / NST Folders of the docker container to access the right powershell scripts (e.g. ...Model.Tools).
 
In AdditionalSetup.ps1I have added some lines to share the folder(s):
```
Write-Host "-- ADDITIONAL SETUP : START --"
$serviceTierFolder = (Get-Item "C:\Program Files\Microsoft Dynamics NAV\*\Service").FullName
$roleTailoredClientFolder = (Get-Item "C:\Program Files (x86)\Microsoft Dynamics NAV\*\RoleTailored Client").FullName
    
Write-Host "Add share  for RTC: $roleTailoredClientFolder"
New-SmbShare -Name RTC -Path "$roleTailoredClientFolder" -ReadAccess Everyone -ErrorAction Continue
# ...
```

But I get the following error message:
```
Add share  for RTC: C:\Program Files (x86)\Microsoft Dynamics NAV\100\RoleTailored Client
New-SmbShare : The Server service is not started.
At C:\Run\my\AdditionalSetup.ps1:15 char:5
+     New-SmbShare -Name RTC -Path "$roleTailoredClientFolder" -ReadAcc ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_SMBShare:ROOT/Microsoft/Wind
   ows/SMB/MSFT_SMBShare) [New-SmbShare], CimException
    + FullyQualifiedErrorId : Windows System Error 2114,New-SmbShare
```

The reason is, I want to have a well defined location to access the CU-Specific NAV PowerShell scripts (e.g. Export-NAVApplicationObject, Import-NAVApplicationObject, ...) in the host environment (Container-Host name is 'nav-dev'):
```
$RTC = '\\nav-dev\RTC'
$ModelToolsPS = (Join-Path $RTC  "Microsoft.Dynamics.Nav.Model.Tools.psd1")
Import-Module $ModelToolsPS -Force -DisableNameChecking -ErrorAction Stop
```

Does anyone have a good idea?

**Comment by freddydk** [comment]
I was heading down the same path, but WindowsServerCore doesn't support file sharing as far as I found out.
This is why i created the port 8080 file share for the .vsix file in dev preview, for clickonce manifests and for the .cer file when using self signed.
You could also .zip other files together there, but you would have to download the .zip file and unpack it.

Other good ideas are welcome...

**Comment by Koubek** [comment]
@megel - And you want to access those scripts from docker hosts or from the container (sorry, I don\`t understand well your intentions).

I install and import Waldo`s powershell modules automatically and thanks to the modification I added you can just import all NAV modules automatically.

I have sth. like this:
- `run\my\AdditionalSetup.ps1`:
```PowerShell
# Invoke default behavior
. (Join-Path $runPath $MyInvocation.MyCommand.Name)


if (!$restartingInstance) {
    . (Join-Path $PSScriptRoot 'CustomScripts\InstallModules.ps1')
}
```
- `run\my\CustomScripts\InstallModules.ps1`
```PowerShell
Import-Module ServerManager
Add-WindowsFeature RSAT-AD-PowerShell

Install-PackageProvider -Name NuGet -Force

Find-Module | where Author -eq waldo | Install-Module -Force
Import-Module Cloud.Ready.Software.NAV
Import-NAVModules
```

Then you just run (or can be done on the global level as well) `Import-NAVModules` and you have access to all NAV Powershell modules.

I understand that does not solve the problem of the shares but maybe it could help you somehow. Of course, this also works locally (in the container) but you could use Import-PSSession to bring your commands down on the docker host.

**Comment by Koubek** [comment]
I also use this flag to share my add-ins with the container:
```PowerShell
    -v $PSScriptRoot\Add-ins:'C:\Program Files\Microsoft Dynamics NAV\100\Service\Add-ins\Docker-Share' `
```

This could be done more efficiently using the second parameter but... This works for now.

**Comment by megel** [comment]
@Koubek 
I tried a similar approach but had some new problems.

1) I have mounted an external directory with my PS-Scripts and my Cofiguration-Files (Environment) into the container
(SubFolders of my host system which are created by MKLINK don't work :( -> so I copied my scripts)
![grafik](https://user-images.githubusercontent.com/15800069/29418510-cd11a962-836c-11e7-941e-1ed8805500d5.png)

2) After entering the session and starting my script I found out, it fails during Import of the modules - so I have retried it direct PS:
`Import-Module   Microsoft.Dynamics.Nav.Ide.psm1`
![grafik](https://user-images.githubusercontent.com/15800069/29418194-f9471450-836b-11e7-9437-4bfc7393992a.png)

**Comment by Koubek** [comment]
About Docker and symlinks (maybe this could help you somehow): 
https://blog.sixeyed.com/docker-volumes-on-windows-the-case-of-the-g-drive/?utm_source=t.co&utm_medium=referral

**Comment by Koubek** [comment]
About the symbolic links and Docker - there are some changes in Insider preview:
https://stefanscherer.github.io/exploring-new-nanoserver-insider-images/#dockervolumes

**Comment by Koubek** [comment]
Maybe publishing via IIS and webdav could be a working way. I have tried several workarounds based on *smb* sharing but nothing is working well. For example you can see `Get-Volume` inside a container returns nothing.

**Comment by freddydk** [comment]
I have also described a way to do this in the latest version of the document - but that copies the files to a share from the host on start.

**Comment by Koubek** [comment]
@freddydk This means that the files and subfolders don\`t propagate dynamically, am I right? I suppose using webdav you could enable real sharing in both directions.

**Comment by freddydk** [comment]
Correct, you could copy the files to a directory with the version number if the folder doesn't exist - it isn't a perfect solution, but in the end, I think I would rather create a number of cmdlets to run on the host, which opens a sessions and executes the corresponding powershell cmdlet inside the container. Kind of like the NAV remote CmdLets on the DVD. Make sense?
