### ISSUE TITLE
Registry entries from NAV installation missing

### ISSUE THREAD

**Issue by rasmusskov** [Microsoft/nav-docker#270]
I am trying to run an unattended installer in my docker image. The installer is trying to copy files to the Add-in folder for both the Client and the Service.

Previously, to find the path, the installer have been checking the registry for the installation path by the following registry value

'HKLM\SOFTWARE\Microsoft\Microsoft Dynamics NAV\110\RoleTailored Client', 'Path',

But looking at the registry, then it only seems like we have registry entries for the Service part of the installer, not the client.

We could also go by the default installation folders, but im trying to have an installer that is more generic, regardles of NAV version installed.

Suggestions appreciated.

**Comment by freddydk** [comment]
As you know, the product is no longer called Microsoft Dynamics NAV, so there might be changes coming on that, but the variables will be updated in new versions of the docker images.
I assume you launch the setup.exe somewhere? Are you connecting to the container after launch to run it - or do you do this in a script override? in script overrides the variables are available and you could set them in the registry or transfer them as parameters to setup.

**Comment by rasmusskov** [comment]
Yes, that is my planned workaround.. To create the missing registry entries while in the powershell scripts.
