### ISSUE TITLE
Accesing to the WebClient outside the host machine

### ISSUE THREAD

**Issue by aetxebarria** [Microsoft/nav-docker#271]
Hi everyone,
First of all, I must say I'm quite a rookie in NAV world, and of course, more if we are talking about dockers, and all this new things.
I've created a docker with NavBC on it, in a host machine we have, with this command, and the following result:

`PS C:\Users\betea> New-CSideDevContainer -containerName BeteaBC -accept_eula -auth NavUserPassword -imageName "microsoft/bcsandbox:es" -licenseFile "C:\6045219-desa2018.flf"
Creating Nav container BeteaBC
Using image microsoft/bcsandbox:es
Using license file C:\6045219-desa2018.flf
NAV Version: 12.3.23590.23945-ES
Generic Tag: 0.0.6.5
Container OS Version: 10.0.14393.2430
Host OS Version: 10.0.14393.0
Creating container BeteaBC from image microsoft/bcsandbox:es
Waiting for container BeteaBC to be ready
Initializing...
Starting Container
Hostname is BeteaBC
PublicDnsName is BeteaBC
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 51431E5C47B0B92F1463B8BD718EB81772AC36E3
Modifying Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Using license file 'c:\run\my\license.flf'
Import License
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user betea
Setting SA Password and enabling SA
Creating betea as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: XXX.YY.ZZZ.6
Container Hostname  : BeteaBC
Container Dns Name  : BeteaBC
Web Client          : http://BeteaBC/NAV/
Dev. Server         : http://BeteaBC
Dev. ServerInstance : NAV

Files:
http://BeteaBC:8080/al-0.16.26913.vsix

Initialization took 203 seconds
Ready for connections!
Set TimeZone in Container to Romance Standard Time
Reading CustomSettings.config from BeteaBC
Creating Desktop Shortcuts for BeteaBC
Nav container BeteaBC successfully created`

Everything works correctly, but now, I must connecto to the WebClient outside the host. I've read I should do soem port mapping, or allowing to the container to use the host's configuration, but I don't know where I should do those changes...
Any hint about this issue?
Really appreciate your help

**Comment by freddydk** [comment]
Publishing ports is really a docker issue and requires you to open your firewall and have your machine setup with public access to these numbers as well. Typically this doesn't work on laptops at all.
Our ARM templates (Azure VMs - http://aka.ms/getbc) does this automatically and the script for setting up the NAV on the VM is here: https://github.com/Microsoft/nav-arm-templates/blob/master/SetupNavContainer.ps1
Especially this section:
$additionalParameters = @("--publish  8080:8080",
                          "--publish  443:443", 
                          "--publish  7046-7049:7046-7049", 
                          "--env publicFileSharePort=8080",
                          "--env PublicDnsName=$publicdnsName",
                          "--env RemovePasswordKeyFile=N"
                          )
and then transfer these parameters to new-navcontainer.
Don't use New-CSideDevContainer that function is deprecated - use New-NavContainer and add -includeCSide and potentially -doNotExportObjectsToText

**Comment by aetxebarria** [comment]
Thanks Freddy, not jsut for this answer, for every work you are doing with all this dockers issue, really helpful.
As I've said befotre, I am a rookie with all this, and I'm finding a few issues to understand your explanation.
Where should I run that script?
I'm running it on my host VM, and I see the next error:
![imagen](https://user-images.githubusercontent.com/41778563/46612673-87eae180-cb11-11e8-9626-ce0e603aeaf8.png)

What do you mean with transfer thsoe parameters to the new container?
When you say that the function for creating the container is deprecated, will you reccommend to me to remove the container, and create a new one?
Thank you very much again

**Comment by freddydk** [comment]
when you create a new container with the same name, it will automatically delete the old one.
You should not run the script, that script is targettet the Azure VMs and shouldn't run outside that environment.
Docker is a steep learning curve and in order to do advanced stuff like this yourself, you need to have deep understaning of PowerShell, networking and more.

What I mean was:

```
$additionalParameters = @("--publish 8080:8080",
"--publish 443:443",
"--publish 7046-7049:7046-7049",
"--env publicFileSharePort=8080",
"--env PublicDnsName=$publicdnsName",
"--env RemovePasswordKeyFile=N"
)
New-NavContainer @additionalParameters -accept-eula <rest of parameters>
```
/Freddy

**Comment by aetxebarria** [comment]
Sorry, I'm trying to run this:

`$additionalParameters = @("--publish 8080:8080",
"--publish 443:443",
"--publish 7046-7049:7046-7049",
"--env publicFileSharePort=8080",
"--env PublicDnsName=$publicdnsName",
"--env RemovePasswordKeyFile=N"
)
New-NavContainer BeteaBC @additionalParameters -accept_eula -auth NavUserPassword -imageName "microsoft/bcsandbox:es"`

But I see the next error..

![imagen](https://user-images.githubusercontent.com/41778563/46614160-6ab81200-cb15-11e8-87fe-3fdc86357536.png)
Seems that does'nt like that parameter... Doesn't exist any way to create the container, and after, publixh against it?

**Comment by freddydk** [comment]
My bad, I think the syntax is:

new-navcontainer -additionalParameters $additionalparameters (and all the other parameters)

A lot of the other things with Nav on Docker are documentet on my blog (also how to use additional parameters)

**Comment by aetxebarria** [comment]
No worries Fredy, the change you've just expose, I've already found it on your blog and github, looking at the main script itself. Seemes that port 8080 it's ok, but I found an issue with the second parameter. May be an issue with the sintax of the enumeration?

![imagen](https://user-images.githubusercontent.com/41778563/46616000-e5832c00-cb19-11e8-9235-9a65c0f0afce.png)

**Comment by freddydk** [comment]
In my example i use a dollar sign instead of an and sign

**Comment by aetxebarria** [comment]
Thanks Freddy, it ahsg worked. So, with this script, the docker that has been created, as already the "port mapping" (note the quotes), and it's accesible from outside the host? THat will be using the IP instead of the DNS, am I right??

Thnak you very much!!

**Comment by tfenster** [comment]
I'll let Freddy answer but I want to give you the hint, that this https://www.youtube.com/watch?v=9c5Yl51yXb8 now is a year old and quit a bit has happened since, but it still should give you a nice starting point for Docker in general and NAV on Docker especially. I think those 90 minutes will give you a lot of background and help when working with NAV on Docker

**Comment by aetxebarria** [comment]
Thanks @tfenster , I already got it on my favourites, it has been he first video I saw when I started to work with the dockers issue, that's why I talk about port mapping, I saw it on that video

Thank you anyway, really appreciate your interest on helping!

![imagen](https://user-images.githubusercontent.com/41778563/46618823-c76cfa00-cb20-11e8-8350-713e2bcece9f.png)

**Comment by freddydk** [comment]
When I publish ports on the host I always use SSL and I always use the dns name - you cannot use certificates on ip numbers.
But as stated earlier - I never do that from my laptop.
When I publish containers on the internet it is ALWAYS Azure VMs or Azure Container Instances.

**Comment by aetxebarria** [comment]
Thank you Freddy, 
I'm installing that Dockers in our server, an Azure VM as you say

**Comment by freddydk** [comment]
The easiest way to get Business Central on azure VMs is http://aka.ms/getbc - then everything is done for you.

**Comment by aetxebarria** [comment]
Hi Freddy,
I'm not sure if that is what I'm looking for. 
We have a server hosted on azure, and my idea is to install a docker on it, for testing diferent developments on it. The issue of making it accesible outside the host, it's just for testing. 
The page with the template you've sent to me, seems to be to add a BC to a resources group, to a known
subscription. Am I right? So, if it that, I think we should pay for that implementation, that it's not our interest.
As I've said before, pur idea for the docker is just for testing, so the issue of making it accesible outside the host, is not mandatory at all.

Thank you for all your tips

**Comment by freddydk** [comment]
Thats fine - just wanted to let you know that there are a lot of stuff out there which can help you out
