### ISSUE TITLE
Spin-up fails: The Microsoft Dynamics 365 Business Central server is currently not ready to serve requests. 

### ISSUE THREAD

**Issue by Kowa63** [Microsoft/nav-docker#272]
With the current master sandboxes (and a new licence pulled last Friday) I'm suddenly getting an error during the spin-up which I've seen with on-premises when the db_owner was not configured correctly, but up to now never when employing containers . 

![importlicenseerror](https://user-images.githubusercontent.com/16236672/46607221-849b2a00-cb00-11e8-9d94-7aec290afdb1.png)
The text in German stands for:
The Microsoft Dynamics 365 Business Central server is currently not ready to serve requests. Try again later or contact your system administrator.

**Comment by freddydk** [comment]
It seems like the master builds are broken currently - will investigate

**Comment by freddydk** [comment]
The latest working master build is bcinsider.azurecr.io/bcsandbox-master:13.0.24862.0 as far as I can see.

**Comment by freddydk** [comment]
This was fixed shortly after and is working again

**Comment by ChawkiBOUMALLOUGA** [comment]
Must update SQL server and/or windows server
I resolved that !
