### ISSUE TITLE
CacheSynchronisation error

### ISSUE THREAD

**Issue by DunshineNL** [Microsoft/nav-docker#274]
Running microsoft/bcsandbox:nl in Docker gives me this warning/error. Tried deleting all containers/images and redownload them already. Same happend with :latest version. I'm using Windows 10. Any ideas what causes this and how to solve?

![image](https://user-images.githubusercontent.com/11821355/46822892-fc7d8480-cd8c-11e8-8477-6fb1e2cf6666.png)

**Comment by freddydk** [comment]
Just ignore it - it is just stating that it initializes the cache (which of course shouldnt give an error)
