### ISSUE TITLE
Bug when using Action "Send As Email" in BC RTM - All localizations??

### ISSUE THREAD

**Issue by DagPilaro** [Microsoft/nav-docker#276]
I think this is a Bug that «all» localizations will have?

When Running Norwegian Language – Send as Email:
![bc send as 1](https://user-images.githubusercontent.com/43909687/46866530-0e5d3700-ce22-11e8-94ea-efd1bf3b5803.jpg)

 

When running English language – no problem…

Looks like there is a change between 2018 CU 8 and BC RTM? Look below:

Table 77, Field 1, Usage

In BC NO
![bc send as 2](https://user-images.githubusercontent.com/43909687/46866595-5c723a80-ce22-11e8-821e-c53cf1f6b32a.jpg)

 

In Dynamics NAV 2018 CU8 NO 
![bc send as 3](https://user-images.githubusercontent.com/43909687/46866611-6c8a1a00-ce22-11e8-8452-a6d8b7264fb6.jpg)

When i change this to how it is shown over here, it runs without problems in BC.

**Comment by DagPilaro** [comment]
This now Works in BC OnPrem cu1 no 👍 Do not think the app team has informed about this fix? I have ran the table 77, Field 1 usage -  and checked the prefs - they have changed the Multilanguage Caption "back" to use the "English" values.

**Comment by freddydk** [comment]
great, thanks
