### ISSUE TITLE
BC onprem localizations - PowerBi Factboxes

### ISSUE THREAD

**Issue by DagPilaro** [Microsoft/nav-docker#277]
Not shure if this bug is related to Docker ore if it is a localization problem. If related to localizations i assume this bug will be the same for all??

When running RTC in English(United States) everything regarding Power-BI Factboxes and in rolecenter is ok.
When running Norwegian there is a bug… something about the width…

I can see there is a new control addin in BC for Power-Bi – is there some kind of missing translation ore, as in my last message, something that shold not have captions??

![bc powerbi factbox](https://user-images.githubusercontent.com/43909687/46866762-f3d78d80-ce22-11e8-839f-b006ef9719a2.jpg)

**Comment by freddydk** [comment]
Have talked to the team, it is a bug, which should be fixed in the insider builds and will be fixed in one of the next updates on docker.

**Comment by DagPilaro** [comment]
Confirm, this Works fine With BC OnPrem cu1 no.

**Comment by freddydk** [comment]
gr8 thanks
