### ISSUE TITLE
Import-Module error

### ISSUE THREAD

**Issue by lmarconato** [Microsoft/nav-docker#28]
Hi,

after building wihout problem docker image on my Win 10 + Docker CE (17.06.0-ce-win19) I try to create a new container with following command:

PS C:\install\nav-docker-master> docker run --hostname navdemo --name navdemo -e username=admin -e password=Pa$$w0rd -e ExitOnError=N -v C:\install\NAVDVD:C:\NAVDVD -e ACCEPT_EULA=Y -p 8080:8080 -p 80:80 -p 443:443 -p 7045-7049:7045-7049 dynamicsnav

The process fails importing Microsoft management module:

Initializing...
Hostname is navdemo
Running Generic Image
Starting Local SQL Server
Using NavUserPassword Authentication
Installing Url Rewrite
Installing ReportViewer
Installing OpenXML
Copy Service Tier
Copy Web Client
Copy RTC Files
AuthorizationManager check failed.
at <ScriptBlock>, C:\Run\navstart.ps1: line 172
at <ScriptBlock>, C:\Run\start.ps1: line 18
at <ScriptBlock>, <No file>: line 1

opening a second poweshell session with following command:

docker exec -it navdemo powershell

and trying to manually import module I receive following message:

PS C:\> Import-Module '.\Program Files\Microsoft Dynamics NAV\100\Service\Microsoft.Dynamics.Nav.Management.psm1'

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run C:\Program Files\Microsoft Dynamics NAV\100\Service\Microsoft.Dynamics.Nav.Management.psm1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"): r
Import-Module : Could not load file or assembly 'file:///C:\Program Files\Microsoft Dynamics
NAV\100\Service\Microsoft.Dynamics.Nav.Management.dll' or one of its dependencies. Operation is not supported.
(Exception from HRESULT: 0x80131515)
At C:\Program Files\Microsoft Dynamics NAV\100\Service\Microsoft.Dynamics.Nav.Management.psm1:1 char:1
+ Import-Module (Join-Path $PSScriptRoot 'Microsoft.Dynamics.Nav.Manage ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

redoing with Set-ExecutionPolicy Unrestricted command, I get same error.

Any suggestion?

Thank you in advance for your attention.

/lm

**Comment by Koubek** [comment]
I understand you build your own image. It looks like the files you copied within the build process are being blocked.

Try to run the following in the folders being affected (those including the files being blocked):
```PowerShell
Get-ChildItem -Recurse | Unblock-File
```

**Comment by freddydk** [comment]
You can also unblock the .zip file on the host (or the content of C:\INSTALL\NAVDVD)
Why did you build your own Docker Image - did you add anything to the generic image?

**Comment by lmarconato** [comment]
Hi, 

container work fine! Great job.

Many thanks to all.
