### ISSUE TITLE
BC OnPrem - Cannot index into a null array

### ISSUE THREAD

**Issue by pm-biteam** [Microsoft/nav-docker#281]
Hello,

I have a problem spinning up new containers (via docker run and new-navcontainer). Can anyone help me what's the actual problem? As far as I understand it, the script can't find navinstall.ps1, because that's the line in start.ps1 (though at line 108 and not 107).
During the initialization step I get this error:

Cannot index into a null array.
at <ScriptBlock>, C:\Run\navstart.ps1: line 172
at <ScriptBlock>, C:\Run\start.ps1: line 107
at <ScriptBlock>, <No file>: line 1
Initialization of container bc failed
At C:\Program
Files\WindowsPowerShell\Modules\navcontainerhelper\0.3.1.4\ContainerHandling\Wait-NavContainerReady.ps1:45
char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container bc failed:String) [], RuntimeExcep
   tion
    + FullyQualifiedErrorId : Initialization of container bc failed

Full trace of container:

Creating Nav container bc
Using image mcr.microsoft.com/businesscentral/onprem:de
Using license file C:\biteam\Lizenzen\Entwicklerlizenz_Business_Central.flf
NAV Version: 13.0.24630.0-de
Generic Tag: 0.0.6.6
Container OS Version: 10.0.14393.2430
Host OS Version: 10.0.14393.0
Creating container bc from image mcr.microsoft.com/businesscentral/onprem:de
Waiting for container bc to be ready
Initializing...
Starting Container
Hostname is bc
PublicDnsName is bc
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint A96BD6CF6AEA856D38D402EE5903742272A42ABC
Modifying Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Using license file 'c:\run\my\license.flf'
Import License
Creating DotNetCore Web Server Instance
Creating http download site
Creating Windows user admin
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Cannot index into a null array.
at <ScriptBlock>, C:\Run\navstart.ps1: line 172
at <ScriptBlock>, C:\Run\start.ps1: line 107
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is bc
PublicDnsName is bc
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint A96BD6CF6AEA856D38D402EE5903742272A42ABC
Modifying Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Using license file 'c:\run\my\license.flf'
Import License
Creating DotNetCore Web Server Instance
Creating http download site
Creating Windows user admin
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Cannot index into a null array.
at <ScriptBlock>, C:\Run\navstart.ps1: line 172
at <ScriptBlock>, C:\Run\start.ps1: line 107
at <ScriptBlock>, <No file>: line 1
Initialization of container bc failed
At C:\Program
Files\WindowsPowerShell\Modules\navcontainerhelper\0.3.1.4\ContainerHandling\Wait-NavContainerReady.ps1:45
char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container bc failed:String) [], RuntimeExcep
   tion
    + FullyQualifiedErrorId : Initialization of container bc failed

If someone needs additional information please let me now. I am using a new server here, never had any issue like this on my other servers. Interestingly this happens with every image I use (NAV 2018, BC OnPrem, etc.)
Thanks in advance for the help :-)

**Comment by rdebath** [comment]
Thank you, I just got this error when "transparent networking" wasn't working.
All fixed now.
