### ISSUE TITLE
Cannot download Symbol

### ISSUE THREAD

**Issue by anwar0206** [Microsoft/nav-docker#282]
Hi,

We have two container running of BC on prem on Azure VM

The VM was created with http://aka.ms/debug-containerhost.ps1
The container1 which was created with the script works fine.
Created new container with the new-navcontainer, with different port numbers.

Container1 - Developer Port is 7049
Container2 - Developer Port is 5050
Both the container are accessible from WebClient and Developer Environment.
In AL symbols can be downloaded from container1

In AL when pointing to Container2 with port 5050, it gives below error.
launch.json file
{
"version": "0.2.0",
"configurations": [
{
"type": "al",
"request": "launch",
"name": "Your own server",
"server": "https://bc2app.southeastasia.cloudapp.azure.com",
"port": 5050,
"serverInstance": "NAV",
"authentication": "UserPassword",
"startupObjectId": 22,
"startupObjectType": "Page"
}
]
}
Sending request to https://bc2app.southeastasia.cloudapp.azure.com:5050/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=12.0.0.0
[2018-10-17 23:32:32.71] Error: An error occurred while sending the request.
Unable to connect to the remote server
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 13.76.6.42:5050

**Comment by freddydk** [comment]
If I create a VM using aka.ms/getbc - and create a second container using:

New-NavContainer -accept_eula -containerName test -DeveloperServicesPort 5050 -auth NavUserPassword

Then I can download symbols on the VM itself:
![image](https://user-images.githubusercontent.com/10775043/47427847-db0b9800-d791-11e8-933d-48cfeb0f7eb4.png)

If I want to connect from the "outside" - I will have to
1. add port 5050 to the incoming ports in the security group on azure
2. Open port 5050 in the VMs firewall
3. Make sure that your certificate for the new container is setup correctly:
3.a. If you are using no certificate, then the url you specify in launch.json should be http and not https
3.b. If you use the same certificate as the existing navserver container - it should just work
3.c. If you use a self-signed certificate you need to download the certificate from the container and install that in the trusted root authorities on the machine with which you connect with VS Code.

Your problem lies probably herein.

**Comment by anwar0206** [comment]
Hello Freddy,
We are trying to connect within the Azure VM.
We tried opening the ports in VM firewall and also added the incoming port in Azure but same issue.

Below is the steps we performed.
1. Created a New VM from aka.ms/getbc
2. Configured new folder in AL, and downloaded the symbols, no issue works perfectly fine.
3. We can access the Webclient within and outside the VM
4. Created new VM with following commands in POWershell
"c:\demo\settings.ps1"
$publicdnsName = "bcapp1.southeastasia.cloudapp.azure.com"
New-NavContainer -containerName bcApp1 `
                 -accept_eula `
                 -auth NavUserPassword `
                 -imageName mcr.microsoft.com/businesscentral/onprem `
                 -Credential $credential `
                 -DeveloperServicesPort 5049 `
                 -includeCSide `
                 -doNotExportObjectsToText `
                 -myScripts "C:\myfolder" `
                 -updateHosts `
                 -useSSL `
                 -additionalParameters @("--publish 8181:8080",
                                         "--publish 5443:443",
                                         "--publish 5046-5049:7046-7049",
                                         "--env publicFileSharePort=8181",
                                         "--env publicODataPort=5048",
                                         "--env publicSoapPort=5047",
                                         "--env publicWebClientPort=5443",
                                         "--env PublicDnsName=$publicdnsName")

Required ports are opened in VM firewalls and Azure.
We can access the Webclient of new container within and outside the VM
Below is the Server Configuration
ContainerName                                   : bcApp1
NetworkProtocol                                 : Default
DatabaseServer                                  : localhost
DatabaseInstance                                : SQLEXPRESS
DatabaseName                                    : CRONUS
EnableSqlConnectionEncryption                   : false
TrustSQLServerCertificate                       : false
ServerInstance                                  : NAV
ClientServicesPort                              : 7046
SOAPServicesPort                                : 7047
ODataServicesPort                               : 7048
ManagementServicesPort                          : 7045
ManagementServicesEnabled                       : true
ClientServicesEnabled                           : true
DeveloperServicesPort                           : 5049
DeveloperServicesEnabled                        : true
DeveloperServicesSSLEnabled                     : true
ExtensionAllowedTargetLevel                     : Internal
ReportPDFFontEmbedding                          : true
ReportAppDomainIsolation                        : true
EnableSaveToWordForRdlcReports                  : true
EnableSaveToExcelForRdlcReports                 : true
EnableSaveFromReportPreview                     : true
CompileBusinessApplicationAtStartup             : true
SOAPServicesEnabled                             : true
ODataServicesEnabled                            : true
ODataServicesV3EndpointEnabled                  : true
ODataServicesV4EndpointEnabled                  : true
SOAPServicesSSLEnabled                          : true
ODataServicesSSLEnabled                         : true
ODataMaxConnections                             : 0
PublicODataBaseUrl                              : https://bcApp1.southeastasia.cloudapp.azure.com:5048/NAV/OData
PublicSOAPBaseUrl                               : https://bcApp1.southeastasia.cloudapp.azure.com:5047/NAV/WS
PublicWebBaseUrl                                : https://bcApp1.southeastasia.cloudapp.azure.com:5443/NAV/
PublicWinBaseUrl                                : DynamicsNAV://bcApp1.southeastasia.cloudapp.azure.com:7046/NAV/
DefaultClient                                   : Web
ServicesOptionFormat                            : OptionCaption
ServicesLanguage                                : en-US
CalendarTwoDigitYearMax                         : -1
SOAPServicesMaxMsgSize                          : 1024
ServicesUseNTLMAuthentication                   : false
ServicesDefaultTimeZone                         : UTC
ServicesDefaultCompany                          : 
ODataServicesMaxPageSize                        : 1000
ClientServicesOperationTimeout                  : MaxValue
ClientServicesProtectionLevel                   : EncryptAndSign
MaxConcurrentCalls                              : 1000
ClientServicesMaxConcurrentConnections          : 500
ClientServicesReconnectPeriod                   : 00:10:00
ClientServicesMaxNumberOfOrphanedConnections    : 20
ClientServicesCompressionThreshold              : 64
ClientServicesMaxUploadSize                     : 30
EnableDebugging                                 : false
DebuggingAllowed                                : true
ClientServicesMaxItemsInObjectGraph             : 512
ClientServicesChunkSize                         : 28
ClientServicesProhibitedFileTypes               : ade;adp;asp;bas;bat;chm;cmd;com;cpl;csh;exe;fxp;gadget;hlp;hta;inf;ins;isp;its;js;jse;ksh;lnk;mad;maf;mag;mam;maq
                                                  ;mar;mas;mat;mau;mav;maw;mda;mdb;mde;mdt;mdw;mdz;msc;msi;msp;mst;ops;pcd;pif;prf;prg;pst;reg;scf;scr;sct;shb;shs;
                                                  url;vb;vbe;vbs;vsmacros;vss;vst;vsw;ws;wsc;wsf;wsh
NASServicesStartupCodeunit                      : 
NASServicesRunWithAdminRights                   : false
EnableDeadlockMonitoring                        : true
NASServicesStartupMethod                        : 
NASServicesStartupArgument                      : 
NASServicesEnableDebugging                      : false
ClientServicesCredentialType                    : NavUserPassword
UIElementRemovalOption                          : LicenseFileAndUserPermissions
ClientServicesTokenSigningKey                   : 
ClientServicesFederationMetadataLocation        : 
ServicesCertificateThumbprint                   : B9B6C2CC1688A0ADDA03EE6C8524E73FDAD4895A
ServicesCertificateValidationEnabled            : false
DisableTokenSigningCertificateValidation        : false
DataCacheSize                                   : 9
SessionEventTableRetainInterval                 : 90.00:00:00
NonInteractiveSessionsLogRetainInterval         : 5.00:00:00
SqlCommandTimeout                               : 00:30:00
BufferedInsertEnabled                           : true
DisableSmartSql                                 : false
EnableFullALFunctionTracing                     : false
Multitenant                                     : False
SqlConnectionIdleTimeout                        : 00:05:00
EnableALServerFileAccess                        : true
EnableApplicationChannelLog                     : true
EncryptionProvider                              : LocalKeyFile
ExchangeAuthenticationMetadataLocation          : 
AppIdUri                                        : 
WSFederationLoginEndpoint                       : 
AzureActiveDirectoryClientId                    : 
AzureActiveDirectoryClientSecret                : 
AzureActiveDirectoryClientCertificateThumbprint : 
EnableMembershipEntitlement                     : 
MaxRowsToExportToExcel                          : MaxValue
EnableTaskScheduler                             : false
TaskSchedulerMaximumConcurrentRunningTasks      : 10
ClientServicesKeepAliveInterval                 : 00:02:00
UseSimplifiedFilters                            : false
ExcelAddInAzureActiveDirectoryClientId          : 
ExtendedSecurityTokenLifetime                   : 0
ClientServicesIdleClientTimeout                 : MaxValue
ODataEnableExcelAddInAnnotations                : true
NavHttpClientMaxResponseContentSize             : 15
NavHttpClientMaxTimeout                         : 00:05:00
SqlParametersByOrdinal                          : true
ClientBuildRestriction                          : WarnClient
TraceLevel                                      : Normal
ExternalTraceLevel                              : Error
EnableDataExportImport                          : true
MaxStreamReadSize                               : 1000000
ValidAudiences                                  : 
DefaultLanguage                                 : 
SupportedLanguages                              : 
ApiServicesEnabled                              : True
EnableSymbolLoadingAtServerStartup              : False
SqlLongRunningThreshold                         : 1000
SqlBulkImportBatchSize                          : 448
UseIncrementalCompanyDelete                     : true
TaskSchedulerSystemTaskStartTime                : 00:00:00
TaskSchedulerSystemTaskEndTime                  : 23:59:59
AllowSessionWhileSyncAndDataUpgrade             : false
SearchTimeout                                   : 00:00:10
OverwriteExistingTranslations                   : true
AzureKeyVaultClientId                           : 00000000-0000-0000-0000-000000000000
AzureKeyVaultClientCertificateStoreLocation     : LocalMachine
AzureKeyVaultClientCertificateStoreName         : My
AzureKeyVaultClientCertificateThumbprint        : 
AzureKeyVaultKeyUri                             :

**Comment by freddydk** [comment]
--publish is used to publish a port from a container on the host (so that it is accessible from outside the host).
Best (and simplest) is to use the new way of changing the port in the container and then you can just publish that port on the host if you want the container accessible on the outside.
No portmapping - and additionalParameters is the way for that (at this time)

**Comment by anwar0206** [comment]
Thanks for the details, will keep in mind, next time creating the container.
