### ISSUE TITLE
Cronus workdate and job queue

### ISSUE THREAD

**Issue by NAVFreak** [Microsoft/nav-docker#285]
I have two problems, first my container uses a "cronus workdate" and then I can't get the job queu to work which I suspect is due to problem 1.

I have created a container:
`new-navcontainer 
            -accept_eula
            -containername $ContainerName 
            -imageName "microsoft/dynamics-nav:2018-cu10-se" 
            -includecside 
            -licenseFile $LicenseFile 
            -Credential $Credential 
            -auth NavUserPassword 
            -verbose 
            -enableSymbolLoading    `

Even thouh I have uploaded our developer license and created a new company it still gives we a "cronus wordate" 2020-01-23.  

When it comes to the job queue i have changed the settings (see below) in the custom settings but nothing happens.

`<add key="NASServicesStartupCodeunit" value="1" />
  <add key="NASServicesRunWithAdminRights" value="true" />
  <add key="NASServicesStartupMethod" value="" />
  <add key="NASServicesStartupArgument" value="60" />`

**Comment by freddydk** [comment]
I think the reason for the job queue not working is the authentication.
What auth. are you using (how do you create the container)

**Comment by y0m0** [comment]
I am facing the same issue here and this problem was also discussed in issue #249 from 2018 but nothing came out of it. Any way around the auth problem?
I guess it's not top priority but it will be nice to be able to test queue entries.

**Comment by freddydk** [comment]
If you create a new issue with explanation, script and everything to repro the problem, I will have a look.
