### ISSUE TITLE
Questions about BC Version and Docker Tags Images

### ISSUE THREAD

**Issue by xgaronnat** [Microsoft/nav-docker#286]
HI,

I created a Docker on a an Azure VM on 26th of October issued from microsoft/bcsandbox:base and version installed is exactly "13.0.24623.24800"

Questions (may be dummy but...) :
- I was not able to find this exact release on https://hub.docker.com/r/microsoft/bcsandbox/tags : any reason why ? 
- how can I be sure to provision the same docker locally, even after next/spring release...? (tried to pull microsoft/bcsandbox:13.0.24623.24800 but not working for me)
- bonus question : what is the meaning of ".24800" exactly in the version ?

Thanks,
Xavier.

**Comment by xgaronnat** [comment]
Hi Freddy,
I know that you were quite busy with all the builds to do but can I get answers as I'm still confused about BC version... :-(

Another point : I can create a docker for `microsoft/bcsandbox:13.0.24630.24844-w1-ltsc2019` but not with `microsoft/bcsandbox:13.0.24630.24844-w1-ltsc2019:base` ? (Error DockerDo : invalid reference format).
Does-it mean that flag `:base` is obsolete ?

Thanks, Xavier.

**Comment by freddydk** [comment]
base is instead of the language - meaning that you replace w1 with base in the tag - not append another tag.
The list of tags on docker hub only shows the latest x tags created - and I might have updated dynamics-nav images since.
Have you read this: https://blogs.msdn.microsoft.com/freddyk/2018/04/16/which-docker-image-is-the-right-for-you/
I think that answers your questions - let me know if not.

**Comment by xgaronnat** [comment]
- So base flag is only valable for w1 version. Assuming that country versions are shipped with Cronus data.
- can you explain how to retrieve the image from version 13.0.24623.24800 and/or explain what are the meaning of 24623 and 24800 ('cause we can't simply use only the "last" version)

And yes I read almost (all) your articles ;-)
Thanks again and congrat for this amazing work.

**Comment by NAVspecialist** [comment]
The numbers you are refering to is a the number you find if you in NAV20XX type HELP, About. Or in Business Central type System Information. For instance if you see the number .24623 it is the RTM release of BC.

For NAV 2018 you can see this list:

https://support.microsoft.com/en-us/help/4072483/released-cumulative-updates-for-microsoft-dynamics-nav-2018

So if you want build 23572 - then you can see it is update 8 

You can then do a docker pull microsoft/dynamics-nav:2018-cu8-XX where you can replace the XX with one of the following: AT, AU, BE, CH, CZ, DE, DK, ES, FI, FR, IS, IT, NA, NL, NO, NZ, RU, SE, UK

**Comment by freddydk** [comment]
I think BC RTM was 24630 (at least that is that I get).
I am writing up a blog post to de-mystiphy version numbers as we speak. Will be out today.

**Comment by NAVspecialist** [comment]
ahh there is actually a little bit of confusion with the RTM version. 

The Development Client (Classic) says 24623 and System Information says 24630

**Comment by Koubek** [comment]
Exactly, I have the same problem:
![image](https://user-images.githubusercontent.com/24265973/49502642-c8e34600-f875-11e8-835f-79ad8c042ee8.png)

Then I am not able to get the image for this version (based on build number of NST).

**Comment by freddydk** [comment]
What you are looking at there is the platform version, which differs from the build version.
Traditionally these have been the same, with Business Central this changes.
We can have multiple releases with the same platform, that we want to give different build numbers.
I hope my blog post will shed light over this.

**Comment by Koubek** [comment]
Ufff, a lot of things have changed, lot of broken stuff on our side. 

@freddydk, please, don't understand me wrong, but the effort to automate looks a bit pointless when I consider all changes coming down with the BC images.

- New endpoint (ACR instead of Docker Hub).
- Missing HTTP API (I know that HTTP API of Azure Container Registry has nothing to do with D365BC images but it's just next complication - Docker Hub was perfect, it allowed to use Docker Image Mirrors etc.; why do we change something that works perfectly fine and looks like a nice standard including features not available today in ACR???).
- New naming conventions (I am fine with it, the product name has changed so OK then).
- Build numbering has change (a new info for me and now I can understand why something that worked doesn't work anymore - and again, the bad thing is we can't see the list of images via HTTP API).

I know the world changes but I can see too many new changes that make it harder to get further (you want to solve one problem and will find next two new issues).

I hope you understand my point ;)

**Comment by freddydk** [comment]
I understand, but none of these things have anything to do with NAV/BC on Docker.

The version numbering is driven by the build team. The reason for this is that we need more frequent updates of the app without changing the platform for online.

The move to mcr was driven by Microsoft - I simply wasn't allowed to create another repo on docker hub by the time we released Business Central.

As far as I know, the mcr guys are working on an API, having said that - I still don't understand why you would need to query the docker hub and search for releases.

In the end - nothing we can do about it, I hope the upcoming blog post will shed some light on the version numbering and that you find a way.

Remember you are always free to shoot me an email or file an issue here if you find things that looks strange - then you maybe can avoid redoing too many things.

**Comment by NAVspecialist** [comment]
@Koubek  in short your get-item in powershell from now on is usesless. You have to go into your client and type System Information if you really need that information. 

I think it is only a matter of 3-9 months then the numbers are "useless".  For instance my BC has a AL.vsix file with version 0.15.18771 - and I have no idea of what version that is linked to into BC. So unless MS makes a sheet of links with what version that works with what - then all the versioning knowledge is useless for most people.

if you pull the daily builds from insiders...then you will also se the numbers changes daily. 

...And the versioning is totally out of @freddydks hands. It is in the dev-teams hands.

Versioning ends up being a matter is "how old is my installation" :) Would be nice though to get an update list for BC, VSIX files etc.

**Comment by Koubek** [comment]
OK, thanks for the feedback. As I told before, don't understand me wrong. I don't blame @freddydk at all. He does a great job for us. I would say he really tries hard to support us (community) and makes our life easier.

I am waiting for a blog post about the build numbers... ;)

And btw, why for example do we need API? Well, one of the things we do is we build a Git repo to see changes between all NAV versions, countries etc. We do it automatically and it's easy to do it up to NAV 2018. We use images and just using naming patterns we know if there is a new release or not. This isn't possible now for BC. As we trying to move all C/SIDE code to BC and convert then switch to AL, we of course still need C/SIDE code base. This repository makes it easier but now we need to update it manually for BC as we can't identify easily whether there is a new release (CU) or not.

**Comment by freddydk** [comment]
Thanks,
For that - wouldn't you just go for:
businesscentral/onprem:cu1
and later cu2, cu3 etc.
Blog post in review right now.

**Comment by Koubek** [comment]
Yes, this is, in fact, the only option I have now. But I need to change the implementation. I was waiting for changes here: https://github.com/AzureCR/specs/issues/3

**Comment by freddydk** [comment]
https://blogs.msdn.microsoft.com/freddyk/2018/12/05/business-central-build-numbers/
