### ISSUE TITLE
microsoft/bcsandbox missing data

### ISSUE THREAD

**Issue by naveksa** [Microsoft/nav-docker#288]
Maybe related to closed Issue #228 (?)

We have an issue on missing Manufacturing data.
We are using an Azure-server with bcsandbox and build a docker sandbox with the following ps-code:
install-module navcontainerhelper -force
$accept_eula = $true
$containername = 'NAVEKSA'
$navdockerimage = 'microsoft/bcsandbox:dk'
$appbacpacuri = ''
$tenantbacpacuri = ''
$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
$additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}
$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula -containername $containername
-auth Windows -Credential $credential
-includeCSide -alwaysPull
-doNotExportObjectsToText -usessl:$false
-updateHosts -assignPremiumPlan
-shortcuts Desktop -imageName $navdockerimage
-additionalParameters $additionalParameters `
-licenseFile 'C:\Naveksa\nav_2018_licens_nov2018.flf'
Setup-NavContainerTestUsers -containerName $containername -password $credential.Password
We get a full environment with basic Cronus demo-data (Customers, items etc.) but no manufacturing data.
No Work Centers, no routings, no prod.BOMs.
The Azure-server was created with Assign Premium Plan = Yes
The New-NavContainer includes the parameter -assignPremiumPlan
and we have selected the UserExperience = Premium.
We have tried with the us-version as well, that is
$navdockerimage = 'microsoft/bcsandbox:us'
but with same result.
Please advice.

**Comment by rdebath** [comment]
There are rapidstart packages with extra data inside the image.
Also if it's a v14 (maybe late v13) there's an extra button on the "Rapidstart Packages" page labelled "Import Predefined Package" which can load these. Be sure to load them into an empty company not on-top of any existing data.

Unfortunately, I can't see any posted data or data for bulk posting anywhere. 😞 
That would be my next request.

**Comment by naveksa** [comment]
Thanks.
I created a new company and loaded a Configuration Package.
The update failed for some reason, but at least I can see some manufacturing data have been created, so this seems to be the "road" forward.
I will investigate further and maybe be back with a new issue.

**Comment by freddydk** [comment]
Alternative is to use the :base image (which will give you W1 demo data).
or use the on-prem images, which contains the on-prem demo data.

**Comment by naveksa** [comment]
We have tried the :base package as suggested, and that works without any RapidStart as data are already there.

Thanks Freddy.
We can now continue our app-development with a common testbase :-)

However, to our opinion, it should be possible to get a dk-environment up running with manufacturing data. Either as part of the image or through RapidStart.
Mayby this is the not the right forum for issuing the errors, we have encountered, but below a short description of our experiences.

We can't get the RapidStart for the :dk image to work.
Everything is being done on Azure with our primary Azure-user which is being created as a super-user in the new environment.
We create the new docker-environment by pulling the :dk image.
From the Windows client we create a new company and select "Advanced Evaluation - Complete Sample Data"
We disable the ESSENTIAL user, as this causes an error that we can not mix essential and premium users.
We set user experience in the new company to Premium.
We go to RapidStart configuration packages and run the Apply package.
The error we get is:
"The operation could not complete because a record in the Config. Package Table table was locked by another user. Please retry the activity."
(During this proces we are only 1 user logged into the Azure server, and therefore only 1 user in this environment)
If we try the operation again we get the following error:
"The metadata object Table 101905 was not found."

We have tried exactly the same proces on a :us package.
There we get the RapidStart package run and all data setup (apparently) correct.
However, for some reason we can not access the us-environment through the Web Client, only through the Window Client.
Error message in Web Client is:
"403 - Forbidden: Access is denied."

**Comment by freddydk** [comment]
The 403 error is tracked by #287 
There is a general description on version numbers, countries etc. here: https://blogs.msdn.microsoft.com/freddyk/2018/12/05/business-central-build-numbers/
I will close this issue

**Comment by rdebath** [comment]
Thanks Freddy, that blog post is very helpful.
