### ISSUE TITLE
How to keep the docker Upgraded

### ISSUE THREAD

**Issue by aetxebarria** [Microsoft/nav-docker#290]
Hy everyone,

I have dynamics NAV BC installed on a docker into a server. Wiht NavContainerHelper functions, I can see this version:
![imagen](https://user-images.githubusercontent.com/41778563/49028441-b6487d00-f1a2-11e8-8b26-4b616f856f48.png)

How can I know wich is the last image, and where can I find it? And which should be the correct way to pull the latest version?

Thank you very much

**Comment by NAVspecialist** [comment]
Just do a normal docker pull of the version you need without cu-xx as a parameter..

**Comment by aetxebarria** [comment]
Thank both for your answers.
@freddydk, if I create a container with -alwayspull, it will always be updated?
Now, I've executed "Docker pull microsoft/bcsandbox:es", and ended like this:
![imagen](https://user-images.githubusercontent.com/41778563/49069340-53e68f80-f229-11e8-852d-d8509cbf0e28.png)

The version is the same. May be this means that it was already upgraded to the latest version?

Thank you again

**Comment by freddydk** [comment]
-alwayspull will check if there is a newer version and pull that if that is the case.
the microsoft/bcsandbox will be updated within the next days.

**Comment by NAVspecialist** [comment]
yes alwayspull works quite nicely too.. I prefer though to do it by hand when needed as I now twice have had an experience where a demo had to wait for an update to finish (with 14 participants)

**Comment by aetxebarria** [comment]
Really appreciated your comments, thank you!!!!

**Comment by freddydk** [comment]
Yeah - the demo is not good, I have actually run into that myself and I don't have a -alwaysPullUnlessDoingADemo switch:-)

**Comment by aetxebarria** [comment]
Sorry for writing here again. I tried to publish an extension, but I saw I was getting an error. Yesterday I pulled the new version, so I thought that I should restart again the docker. But I see this error:

![image](https://user-images.githubusercontent.com/41778563/49151704-fc235380-f310-11e8-83f7-889edf33ca3d.png)
Shouldn't be updated already? I don't understand this issue..

Thank you very much

**Comment by freddydk** [comment]
What docker image did you pull?

**Comment by aetxebarria** [comment]
Thanks Freddy.
As you can see in my previous message, I execute the "Docker pull microsoft/bcsandbox:es" comando, so I used microsoft/bcsandox:es image.

**Comment by freddydk** [comment]
Yesterday, I wrote that the microsoft/bcsandbox will be updated within the next days - that hasn't changed.
For now, you will have to use -accept_outdated
