### ISSUE TITLE
navserver\SQLEXPRESS server cannot be found

### ISSUE THREAD

**Issue by lhtan-dev** [Microsoft/nav-docker#293]
Environment setup
- Fresh installation of aka.ms/bcsandbox
- mcr.microsoft.com/businesscentral/sandbox:w1-ltsc2019

Steps to replicate
1. Setup environment as above.
2. Connect to VM thru rdp and open navserver CSID shortcut on desktop
3. Use credentials to login.
4. navserver/sqlexpress 

![image](https://user-images.githubusercontent.com/17727792/49434984-7dd31f80-f7f0-11e8-82c4-73fe2570c6c9.png)

**Comment by TweetImrank** [comment]
Have you done as NavUSerPassword as auth?

**Comment by freddydk** [comment]
This is the ARM templates and I just discovered that when running Windows 2019 - I need to add -updatehosts to new-navcontainer.
You can modify c:\demo\setupnavcontainer.ps1 and add this parameter and then run replace-navservercontainer - or you can create a new VM.
Then it should work.

**Comment by lhtan-dev** [comment]
>           This is the ARM templates and I just discovered that when running Windows 2019 - I need to add -updatehosts to new-navcontainer.
> You can modify c:\demo\setupnavcontainer.ps1 and add this parameter and then run replace-navservercontainer - or you can create a new VM.
> Then it should work.

This fixed it. Thanks a lot Freddy! 👍
