### ISSUE TITLE
No problems just a confusion regarding container for BC onpremise

### ISSUE THREAD

**Issue by TweetImrank** [Microsoft/nav-docker#294]
I have pulled BC on premise -ltsc2016  image and created a container and all is good and its working all fine.
But when I do > docker container ls
 (lists all containers)

Then I see the container ID and the image that container is associated with but the image is showing as 'Microsoft/dynamics-nav with tag generic-1803, should not the image name be mcr.microsoft.com/businesscentral/onprem ??

Thanks

**Comment by freddydk** [comment]
When you have started your container using -usebestcontaineros, then navcontainerhelper will re-platform the container on-the-fly (in order to maximize compatibility).
Once you update your computer to Windows 10 1809 - you should just run -image mcr.microsoft.com/businesscentral/onprem and it will automatically grab -ltsc2019.

**Comment by TweetImrank** [comment]
ok got it thanks Freddy

**Comment by TweetImrank** [comment]
I thought I would get a VM with ltsc 2016 on it with BC on it but is that possible? does it matter which host is on container because its just create  shortcuts on the desktop and BC would work same no matter what the host is right?

**Comment by freddydk** [comment]
How did you create your VM?
On Azure you can use http://aka.ms/getbc to spin up a VM (2016 or 2019).
2019 is much faster than 2016 because of smaller containers - else it is pretty similar.

**Comment by TweetImrank** [comment]
I have not created VM, I thought new-navcontainer using image ltsc-2016 would create for me, obviously I thought wrong :)

Thanks Freddy your help very much appreciated.

**Comment by freddydk** [comment]
New-NavContainer spins up a container - not a VM.

**Comment by TweetImrank** [comment]
yes - silly me!
