### ISSUE TITLE
Portainer.io not supported in Windows Server 2019 with containers

### ISSUE THREAD

**Issue by lhtan-dev** [Microsoft/nav-docker#295]
///Environment
- aka.ms/bcsandbox
- mcr.microsoft.com/businesscentral/sandbox:latest
- Windows Server 2019 with containers

Upon running the script to install portainer.io in the vm

///-----------------------snippet start------------------------///
''{     "hosts": ["tcp://0.0.0.0:2375", "npipe://"] }' | Set-Content "C:\ProgramData\docker\config\daemon.json" 
restart-service docker 

netsh advfirewall firewall add rule name="Docker" dir=in action=allow protocol=TCP localport=2375 
 
new-item -Path "C:\Portainer" -ItemType Directory 
$ipAddress = (get-netadapter | Select-Object -First 1 | get-netipaddress | ? addressfamily -eq 'IPv4').ipaddress 
 
docker run -d -v C:\Portainer:C:\data --name portainer --hostname portainer portainer/portainer -H tcp://${ipAddress}:2375'
///-----------------------snippet end-------------------------///

Was given this error 

The container operating system does not match the host operating system. (0xc0370101)

**Comment by NAVspecialist** [comment]
Yes you're right. I am running like this in W 2016

docker run -d -p 9000:9000 --name portainer -h portainer --restart=always -v  C:\ProgramData\Docker\Containers\Portainer:C:\Data portainer/portainer --no-auth 

(I have created the portainer folder ;-) )
Same command in Win 2019 gives a very long errormessage.

But the problem is not portainer.. You have to address this somewhere at portainer.io

**Comment by tfenster** [comment]
Absolutely not a nav-docker issue but here is the explanation:

It seems like Portainer doesn't (yet?) have a Windows Server 2019 image. By just pulling and running you got the Server 2016 image. As you can't run a Windows Server 2019 image directly on Windows Server 2016 you get the error. You can ask Portainer to provide a Windows Server 2019 image, create one yourselve or it might work to run it using hyper-v isolation

**Comment by freddydk** [comment]
Couldn't you start portainer with --isolation hyperv?

**Comment by lhtan-dev** [comment]
'{  "hosts": ["tcp://0.0.0.0:2375", "npipe://"] }' | Set-Content "C:\ProgramData\docker\config\daemon.json" 
restart-service docker 

netsh advfirewall firewall add rule name="DockerPortainer" dir=in action=allow protocol=TCP localport=2375 
 
new-item -Path "C:\Portainer" -ItemType Directory 

$ipAddress = (get-netadapter | Select-Object -First 1 | get-netipaddress | ? addressfamily -eq 'IPv4').ipaddress 

docker run -d -v C:\Portainer:C:\data --isolation hyperv --name portainer --hostname portainer portainer/portainer -H tcp://${ipAddress}:2375 

##add portainer ip:host mapping to host file
$ipadd = docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' portainer
Add-Content -Value "${ipadd} portainer" -Path "$env:windir\System32\Drivers\etc\hosts"


===========

Added isolation hyperv and update the host file to map the hostname so portainer is now accessible at http://portainer:9000 instead of <ipv4>:9000 .

**Comment by NAVspecialist** [comment]
I am pretty much doing it the same way (now) but with a few changes:

'{ "hosts": ["tcp://0.0.0.0:2375", "npipe://"] }' | Set-Content "C:\ProgramData\docker\config\daemon.json"
restart-service docker

netsh advfirewall firewall add rule name="DockerPortainer" dir=in action=allow protocol=TCP localport=2375

new-item -Path "C:\Docker\Portainer" -ItemType Directory

$ipAddress = (get-netadapter | Select-Object -First 1 | get-netipaddress | ? addressfamily -eq 'IPv4').ipaddress
docker run -d -p 9000:9000 --name portainer -h portainer --restart=always -v C:\Docker\Portainer:C:\Data portainer/portainer  --no-auth -H tcp://${ipAddress}:2375

# Remove existing portainer line
Set-Content -Path "c:\windows\system32\drivers\etc\hosts" -Value (get-content -Path "c:\windows\system32\drivers\etc\hosts" | Select-String -Pattern 'portainer' -NotMatch)

##add portainer ip:host mapping to host file
$ipadd = docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' portainer
Add-Content -Value "${ipadd} portainer" -Path "$env:windir\System32\Drivers\etc\hosts"

So you can see I start Portainer differently and before I add the line to the hosts file I remove the existing line with the word portainer.

**Comment by itsmebhavin** [comment]
> @freddydk Hyper-V isolation worked for me.
> 
> ` docker run -d -p 9000:9000 --name portainer --restart always -v '\\.\pipe\docker_engine:\\.\pipe\docker_engine' --isolation hyperv -v portainer_data:C:\data portainer/portainer`

This works for me. Thanks @freddydk
