### ISSUE TITLE
Modify C/Side report builder missing

### ISSUE THREAD

**Issue by kevindstanley1988** [Microsoft/nav-docker#296]
We are building out our ISV and preparing it for Full AL implementation, however that isn't fully possible for us at the moment, so we still have the requirement of developing in CSide while preparing our solution. I am using aka.ms/getbc with the new Windows Server 2019 with Containers image for development. However when I go to modify a report layout I get the error "An error ccurred when opening the report designer. A supported version of Report Builder could not be found."

I read through [this](https://github.com/Microsoft/nav-docker/issues/51#issuecomment-370850143) which makes it sound like installing report builder on the VM should fix the problem, but it does not. I have tried installing Report Builder 3.0 as well as the newest report builder Report Builder in SQL 2016 and neither resolve the issue.

**Comment by freddydk** [comment]
Not sure what you are doing or whether I have misunderstood everything. I just created a VM and installed Visual Studio 2017 Community (by running the installer script in C:\demo) and then installed the rdlc designer for Visual Studio here: https://marketplace.visualstudio.com/items?itemName=ProBITools.MicrosoftRdlcReportDesignerforVisualStudio-18001#review-details
When I say View Layout in the report designer, I get this:
![image](https://user-images.githubusercontent.com/10775043/49575689-97d14700-f943-11e8-9972-7f50407a5f88.png)

**Comment by NAVspecialist** [comment]
I think your solution is to go into C/Side Development, Choose Functions, and then set Use Report Builder = Yes, Click OK and restart the CSide Development Environment.

**Comment by freddydk** [comment]
Works fine as well
![image](https://user-images.githubusercontent.com/10775043/49584330-403ed580-f95b-11e8-875d-85f36bb67e27.png)
I think there are multiple versions of ReportBuilder and you need to make sure that you take the right one.
Grab the one from the DVD prerequisite components - works.

**Comment by kevindstanley1988** [comment]
Aha! That was it, the version I had was newer than what NAV was expecting, I uninstalled the version I had and installed the file from pre-requisite components and it worked.  I didn't even think to pull it from the DVD. Thanks for your quick response!
