### ISSUE TITLE
using bcinsider.azurecr.io/bcsandbox:base with version tag

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/nav-docker#297]
I can pull a docker image with:
"docker pull bcinsider.azurecr.io/bcsandbox:base", which holds Cronus Data. 
But can I also pull a base image from a certain version, like this:
"docker pull bcinsider.azurecr.io/bcsandbox:base-w1-13.2.26542.0-ltsc2019".
This doesn't work. Tried several variants. 

Is it the syntax or isn't this supported? 
And can I somehow see a list of available images (with some webrequest)?

**Comment by freddydk** [comment]
[version][-country][-os]
and base is a country.

so..

13.2.26542.0-base-ltsc2019

would be my guess

**Comment by mheijkant** [comment]
Thanks, it worked. 
I didn't realize that :base represented -country

**Comment by freddydk** [comment]
https://blogs.msdn.microsoft.com/freddyk/2018/12/05/business-central-build-numbers/ - also states exactly what base is
