### ISSUE TITLE
Typos on Docker Hub

### ISSUE THREAD

**Issue by RasmusTidselbak** [Microsoft/nav-docker#299]
There is a couple of typos in the description on:
https://hub.docker.com/r/microsoft/bcsandbox/

In the examples of "Supported tags", "How to use this image" and "NavContainerHelper" the path to the image is missing a ".".
From "mcr.microsoftcom" to "mcr.microsoft.com"

**Comment by freddydk** [comment]
Thanks - I have submitted a Pull Request to mcr with this fix.

**Comment by freddydk** [comment]
Fixed
