### ISSUE TITLE
Default/empty license (Cronus.flf)

### ISSUE THREAD

**Issue by Koubek** [Microsoft/nav-docker#3]
In case of an external SQL server and an existing DB we need to avoid to uploading any license file. We can upload one using Docker (using the parameter to upload a license) but this is not usually requiered as we normally use the license in the master DB.

There is no way right now to do it as `licensefile` parameter replace the empty value by *Cronus.flf*. Ok, there is a way - we can override `SetupLicense.ps1` but would be better to solve it directly in the image.

**Comment by freddydk** [comment]
Yes, I discovered that one yesterday myself.
I will fix this.

/Freddy

**Comment by Koubek** [comment]
I could have fixed it by myself but don`t know what would be the best way for you.

**Comment by freddydk** [comment]
Fixed, new images will be generated
