### ISSUE TITLE
How can I remotely debug an additional container on the same server?

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/nav-docker#301]
I am trying to create multiple containers on the same server. The intention is to provide developers with their own instances to test against. This all seems to work but I am stuck on how to debug additional containers remotely. 

I deploy the first: 
```
docker login "insiderrepo" -u "username" -p "pass"

$additionalParameters = @("--publish 8080:8080",
"--publish 80:80"
"--publish 7046-7049:7046-7049",
"--env publicFileSharePort=8080"
)

New-NavContainer -accept_eula -alwaysPull -imageName "next minor" -containerName "somename1" -auth NavUserPassword -licenseFile "ourlicense" -includeCSide -additionalParameters $additionalParameters 
```

In VS Code from I can set the following in launch.json and deploy the debugger from a remote location(using F5)
```
"server": "http://hostserver",
"port": 7049
```

This works. 

Now I make another container
```
docker login "indsiderrepo" -u "username" -p "pass"

$additionalParameters = @("--publish 8081:8080",
"--publish 81:80"
"--publish 7056-7059:7046-7049",
"--env publicFileSharePort=8180"
)

New-NavContainer -accept_eula -alwaysPull -imageName "next minor" -containerName "somename2" -auth NavUserPassword -licenseFile "ourlicense" -includeCSide -additionalParameters $additionalParameters 
```

In VS Code I set the following in launch.json and can not connect from a remote location. To be clear the extension publishes, the error comes when the debugger should start and launch the web client. 
```
"server": "http://hostserver",
"port": 7059
```

also tried 
```
"server": "http://hostserver:81",
"port": 7059
```

In VS Code the error is 
`Error: An internal error has occurred`

In the container's event viewer the warning is: 
```
The description for Event ID 202 from source MicrosoftDynamicsNavServer$NAV cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Server instance: NAV
Tenant: default
Session type: WebServiceClient
Session ID: 173
This license is not compatible with this version of Business Central.
```

Is there a way to make this work?

**Comment by freddydk** [comment]
You also need to tell the container which port you map publicly to the container (PublicWebClientPort, … )
I don't know which version of the NavContainerHelper and Docker images you are running, but since 0.3.1.0 you can do like described here: https://blogs.msdn.microsoft.com/freddyk/2018/09/03/navcontainerhelper-0-3-1-0-and-a-new-docker-generic-build-0-0-6-6/

So update the containerhelper to the newest and follow that.
