### ISSUE TITLE
Not sure what to make of this

### ISSUE THREAD

**Issue by TheDenSter** [Microsoft/nav-docker#303]
My laptop is Windows 10 Pro, I have a VM with Windows Server 2016. I've used this setup for about 18 months now, and as I was doing development, all of a sudden my container was no longer responding. What I usually do is recreate my container. This particular container I've been using for about a week, recreated it 2-3 times to run through my install process, and now when I tried to recreate it, I get this message:
![image](https://user-images.githubusercontent.com/23434319/50058307-936f1000-0133-11e9-88fb-0c47ef45dcdc.png)
Re-installed Docker, updated navcontainerhelper, still getting this error message. I'm not sure what to look for or how to troubleshoot this.

**Comment by freddydk** [comment]
Restart powershell - then it works.
Updating NavContainerHelper requires you to restart PowerShell.
You have 0.4.2.4 - which is the version, where I accidently defaulted isolation wrongly (beginning of your error it says: No hypervisor present meaning that it defaults to hyperv)
0.4.2.4 was only out there for ~8 hours or so.
You are the first person I hear running into this, my sincere appologies.
