### ISSUE TITLE
Problems with rendering reports in Webclient / missing fonts

### ISSUE THREAD

**Issue by PatrickGrabensteiner** [Microsoft/nav-docker#304]
When i want to preview a report in webclient, the report just uses a Standard font because the Fonts in the container are missing.

Please provide the Windows Standardfonts in the Image.

Best Regards
Patrick

**Comment by freddydk** [comment]
In NavContainerHelper there is a function called Add-FontsToNavContainer - which will copy fonts from the host, please use that, I cannot add the fonts up front.

**Comment by freddydk** [comment]
Assuming that this resolved the issue
Please reopen if necessary
