### ISSUE TITLE
You do not have the following permissions on Page CAL Test Tool: Execute.

### ISSUE THREAD

**Issue by lhtan-dev** [Microsoft/nav-docker#308]
Using Business Central container sandbox W1 13.2 (26556). 

After importing testtoolkit and opening page 130401 was given no execute permission on the page. Log in user is super admin. 

![image](https://user-images.githubusercontent.com/17727792/50581410-668d5d80-0e94-11e9-8a41-385db119c614.png)

**Comment by lhtan-dev** [comment]
Hi @NAVspecialist , it's a fresh instance with demo license. Is it a must to have a partner license to run the test tool kit?

**Comment by richardrobberse** [comment]
As far as I know, the test toolkit only works with a development license, not sure if this is still the case.

**Comment by lhtan-dev** [comment]
Yeah. A partnerlicense is mandatory. After importing the partner license, it works.
