### ISSUE TITLE
Web Client error 502

### ISSUE THREAD

**Issue by DragonMrak** [Microsoft/nav-docker#309]
Hello,

We are using latest docker build (cannot find exact build number from web client) for business central. Everything seems to be OK, but after certain amount of time after starting a container (and it does not depend if you're doing any high loads or just keeping one web page with BC page open) it faults with error that "Network is unavailable" and after full refresh (Ctrl+F5) you get the following message from IIS:

502 - Web server received an invalid response while acting as a gateway or proxy server.
There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

After that any connections to any services becomes unavailable until you restart docker container.

Container itself is created with the following command line:
docker run -e accept_eula=Y -m=4G bcinsider.azurecr.io/bcsandbox-master:us

Is it something we do wrong?

**Comment by freddydk** [comment]
I think the memory should be specified with -m 4G and not with a = sign
Don't think that is the reason though.
Have you tried this with the shipped images: mcr.microsoft.com/businesscentral/onprem:w1 
Could you paste the output from docker run here?
I always recommend people to use new-navcontainer from navcontainerhelper to spin up containers, as that will apply some restart settings and the right memory settings.

**Comment by LoanVision** [comment]
Looks like this error is not related to docker. It's global to BC (Screenshots from event log with standalone BC installed). 
<img width="1414" alt="screen shot 2019-01-15 at 9 09 08 pm" src="https://user-images.githubusercontent.com/45673357/51222041-e4784c80-1909-11e9-8450-9a07667b59c9.png">
<img width="746" alt="screen shot 2019-01-15 at 9 09 15 pm" src="https://user-images.githubusercontent.com/45673357/51222042-e4784c80-1909-11e9-9a26-ba16db250d1f.png">

Igor

**Comment by freddydk** [comment]
Have you checked that vs code hasn’t caught a breakpoint? In that case you should just press F5 to continue execution

Få Outlook til iOS<https://aka.ms/o0ukef>

________________________________
Fra: LoanVision <notifications@github.com>
Sendt: onsdag, januar 16, 2019 3:42 AM
Til: Microsoft/nav-docker
Cc: Freddy Kristiansen; Comment
Emne: Re: [Microsoft/nav-docker] Web Client error 502 (#309)


And it looks like only happens during session debug.

**Comment by freddydk** [comment]
And it didn't run into an error in vs code?

**Comment by freddydk** [comment]
Is this still an issue?

**Comment by DragonMrak** [comment]
Freddy,

Thank you very much, it seems like as of Customer Preview #3 it is fixed and works as intended!

**Comment by freddydk** [comment]
Thanks
