### ISSUE TITLE
Creating an Azure bcsandbox Container with template from private registry

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/nav-docker#310]
A while ago you posted this blog:
https://blogs.msdn.microsoft.com/freddyk/2018/04/12/enabling-premium-experience-in-business-central-sandbox-containers/
which had a link "http://aka.ms/bcsandbox" to a template to create a bcsandbox container inside an Azure Windows VM.

I'm having an issue to create this VM when using a private registry to pull the image: "bcinsider.azurecr.io/bcsandbox:w1-ltsc2019".
I've extended the template.json with registryUsername and registryPassword like this:

        "registryUsername": {
            "type": "string",
            "defaultValue": "<private user name>",
            "metadata": {
                "Description": "Specify Username when using a Private Registry"
            }
        },
        "registryPassword": {
            "type": "securestring",
            "defaultValue": "<private user password>",
            "metadata": {
                "Description": "Specify Password when using a Private Registry"
            }
        },

which failed with error:

9:08:06 PM at , C:\demo\setupVm.ps1: line 191
9:08:06 PM at , C:\demo\setupVm.ps1: line 201
9:08:06 PM at DockerDo, C:\demo\setupVm.ps1: line 102
9:08:06 PM Cannot convert value to type System.String.
9:08:03 PM Pulling bcinsider.azurecr.io/bcsandbox:w1-ltsc2019 (this might take ~30 minutes)

also tried to modify this part, from securestring to string:

        "registryPassword": {
            "type": "string",
            "defaultValue": "<private user password>",
            "metadata": {
                "Description": "Specify Password when using a Private Registry"
            }
        },

with the same error:

9:41:32 PM at , C:\demo\setupVm.ps1: line 191
9:41:32 PM at , C:\demo\setupVm.ps1: line 201
9:41:32 PM at DockerDo, C:\demo\setupVm.ps1: line 102
9:41:32 PM Cannot convert value to type System.String.
9:41:26 PM Pulling bcinsider.azurecr.io/bcsandbox:w1-ltsc2019 (this might take ~30 minutes)

Looked into the setupVm.ps1 file, and it looks like the script expects that somewhere a loging to the private registry happens. But I'm at a loss here. Where and How can I do this login to "bcinsider.azurecr.io". I do have a login and password available.

**Comment by freddydk** [comment]
If you use http://aka.ms/bcsandboxext - then you will have these fields and then provide bcinsider.azurecr.io/bcsandbox-master:us as docker image - that should work.
In the packages on collaborate, it refers to http://aka.ms/bcdeveloperpreviewext - should be the same.

**Comment by mheijkant** [comment]
Thanks, this worked.
