### ISSUE TITLE
Difference bcsandbox and bconprem

### ISSUE THREAD

**Issue by MJECloud** [Microsoft/nav-docker#311]
Hello Freddy, 

can you tell me in detail, if there are fundamental differences between bcsandbox and bconprem?

Thank you. 

Greetings, 
Maurice

**Comment by NAVspecialist** [comment]
You could actually start telling why you are asking? And secondly are we talking about Application differencies or configuration-differencies in OS-setup?

Thanks.

**Comment by MJECloud** [comment]
I'm asking because the company i work for start a build pipeline to compile install and test Extensions. 
We tried both images bcsandbox and bconprem but we've got different results executing the Microsoft tests.

First we used mcr.microsoft.com/businesscentral/onprem and could compile install and successfully test our extension. 
Then we tried mcr.microsoft.com/businesscentral/onprem:de and got this error during compilation

> error AL0185: Codeunit 'Assert' is missing

After some [research ](https://github.com/Microsoft/AL/issues/4327)we've added this to the app.json of our test extension.

> "test": "12.0.0.0"

Now we got the following error message: 

> test/Cod50005.TestCodeunit.al(8,17): error AL0265: Reference to object Assert is ambiguous. Make sure you are not referencing packages containing objects with the same names.

All this works fine with the microsoft/bcsandbox:de image. 

Now we're very curious why this works with bcsandbox and not with bconprem. 

Primary we're talking about application differencies.

**Comment by NAVspecialist** [comment]
Allright, This your question is not supposed to be here. This is purely docker releated. 

If you want a fast answer, and are a Microsoft Partner.. Then use Yammer. The Yammer Group is called: Dynamics 365 Business Central Develop and the sub group is App Development.

**Comment by MJECloud** [comment]
Could you please explain why this is purely docker related? I'm having specific issue with NAV inside the different images, while docker itself seems to be working fine. So my question was how those differences can be explained. From my expectation bconprem should not behave differently than bconprem:de

**Comment by NAVspecialist** [comment]
Perhaps you misunderstood me (I almost misunderstood myself :D  ) When I said this is purely docker related - then I meant this group. 

You have  having som issues with some code that works in docker but not in another and the only difference is the "languageversion""  - 

mcr.microsoft.com/businesscentral/onprem vs.  mcr.microsoft.com/businesscentral/onprem:de

Your text is a little bit confusing because what you probably are talking about is 

mcr.microsoft.com/businesscentral/onprem:xx vs. bcinsider.azurecr.io/bcsandbox-master:xx  vs bcinsider.azurecr.io/bcsandbox:xx  - and the difference here is AL-code and the "exe/dll"-files and not as such purely docker-related.

I hope I made myself clear now, sorry for the misunderstanding.

**Comment by MJECloud** [comment]
Ok, thanks for the information :)

**Comment by freddydk** [comment]
Differences between business central on premises and online is something you will need to ask elsewhere. As navspecialist said, this has nothing to do with docker.

Få Outlook til iOS<https://aka.ms/o0ukef>

________________________________
Fra: MJECloud <notifications@github.com>
Sendt: torsdag, januar 10, 2019 2:06 PM
Til: Microsoft/nav-docker
Cc: Freddy Kristiansen; Comment
Emne: Re: [Microsoft/nav-docker] Difference bcsandbox and bconprem (#311)


Closed #311<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fnav-docker%2Fissues%2F311&data=02%7C01%7Cfreddy.kristiansen%40microsoft.com%7C586af00b5ebe4bbe0d3708d676fc6aa3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636827223826751079&sdata=PZcary%2Fu0XuBS5uWHi1P4YmuL8Yr1F0QBGSEHghyqIc%3D&reserved=0>.
