### ISSUE TITLE
BC On-Prem tags available?

### ISSUE THREAD

**Issue by ABA95** [Microsoft/nav-docker#312]
I don't know if this is the right place for this question is there a particular reason why the "tags" section on https://hub.docker.com/r/microsoft/bconprem/ is empty?

**Comment by NAVspecialist** [comment]
You mean why not a bconprem:something ?? 

If you leave out something then you get the W1 (Worldwide) version which is without  national functionatity. If you get the bconprem:dk - then you get the  W1 version with eg. danish Tax, VAT, Payment objects/extensions.

**Comment by ABA95** [comment]
i mean more like this https://registry.hub.docker.com/v1/repositories/microsoft/bcsandbox/tags

**Comment by NAVspecialist** [comment]
Ahh, ok You are new at Dynamics NAV/ 365 BC ?

A short explanation. Currently Microsoft supports several version of Dynamiccs NAV and Business Central - They are countryspecific hence you can pull a :xx (languagecode). But for every language there a number of updates.

For Dynamics NAV 2018 you can see this:

https://support.microsoft.com/da-dk/help/4072483/released-cumulative-updates-for-microsoft-dynamics-nav-2018

Notice that is says Cu1 to cu13 but also a build no. So you can either pull the CU-number or the build no.

If you want the latest danish version then you can pull  2018:dk and if you want update 2018 update 10 danish version you pull 2018:cu10-dk

For onpremise versions  you can pull the build no as you can see on the tags page that you linked to.

Generally you only need the latest version so you can just use blank tagname for latest W1 version or eg DK to get the latest danish version.

Hope that makes sense

If not then bring on an example of why you asked the question 

You can also read this one:

https://blogs.msdn.microsoft.com/freddyk/2018/04/16/which-docker-image-is-the-right-for-you/

Thanks

**Comment by Koubek** [comment]
Btw, if you are interested in the listing of tags via HTTP API, unfortunately, this isn't possible right now as MS migrates their content to Azure Container Registry (BC was the first one for Dynamics product, NAV was and still is placed in the standard Docker Hub). And ACR doesn't have API available yet.

You can find more here:
https://github.com/AzureCR/specs/issues/3
https://github.com/Microsoft/nav-docker/issues/286

**Comment by NAVspecialist** [comment]
Instead you can do it like this 

$ResultingObject = @()
 
$result = Invoke-WebRequest -Uri "https://registry.hub.docker.com/v2/repositories/microsoft/dynamics-nav/tags/?page_size=250" 
$JsonObject = ConvertFrom-Json -InputObject $result.Content
$ResultingObject = $JsonObject.results
$ParentId = 1
 
while ($JsonObject.next) {
    $result = Invoke-WebRequest -Uri $JsonObject.next 
    $JsonObject = ConvertFrom-Json -InputObject $result.Content
    $ResultingObject += $JsonObject.results    
    
    $percCompleted = [Math]::Round($ResultingObject.Count / $JsonObject.count, 4) * 100
    Write-Progress -Activity "Processing tags" -PercentComplete $percCompleted -ParentId $ParentId 
}

# $ResultingObject | where name -like '*dk' | select name or
$ResultingObject | where name -like '*2018*dk' | select name

just copy the code to a .ps1 file :)

**Comment by Koubek** [comment]
@NAVspecialist I think @ABA95 was interested in BC on prem tags. And I am afraid your script won't be able to get tags for BC.

**Comment by mheijkant** [comment]
I'm also interested which tags for OnPrem are available, because I would like to know what exact tag I should pull, to have the same version compared to a DVD version. And not only pull the latest version. 
So can I pull a specific (older) CU or 13.x.xx version.
I'm also using the mentioned script from "navspecialist", which work for dynamics-nav and bcsandbox.
If it's possible please add the missing tags for OnPrem.

**Comment by freddydk** [comment]
if you need an onprem cu - then use the cu
mcr.microsoft.com/businesscentral/onprem:rtm-de-ltsc2019
mcr.microsoft.com/businesscentral/onprem:cu1-de-ltsc2019
mcr.microsoft.com/businesscentral/onprem:cu2-de-ltsc2019
...
It won't really help you to get the tag list IMO.
You will not see the tags list in the docker hub, but I might create some PowerShell command in NavContainerHelper to help.
