### ISSUE TITLE
docker pull mcr.microsoft.com/businesscentral/onprem-ltsc2019 Using default tag: latest Error response from daemon: manifest for mcr.microsoft.com/businesscentral/onprem-ltsc2019:latest not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by shashiBssi** [Microsoft/nav-docker#313]
docker pull mcr.microsoft.com/businesscentral/onprem-ltsc2019
Using default tag: latest
Error response from daemon: manifest for mcr.microsoft.com/businesscentral/onprem-ltsc2019:latest not found: manifest unknown: manifest unknown

**Comment by tfenster** [comment]
docker pull mcr.microsoft.com/businesscentral/onprem:ltsc2019

**Comment by shashiBssi** [comment]
Thank you @tfenster 
how about "US" ?

**Comment by shashiBssi** [comment]
Thank you @tfenster
