### ISSUE TITLE
No access to NAV even though user exists with SUPER permission

### ISSUE THREAD

**Issue by MatDDev** [Microsoft/nav-docker#316]
Hello Guys,
I encountered a problem with connection to NAV. When trying to open NAV (2018) client, installed on docker I get such error:

_You do not have access to Microsoft Dynamics NAV. Verify that you have been set up as a valid user in Microsoft Dynamics NAV._

User with my credentials exists with SUPER permission:

`UserSecurityID           : 0940979c-7be9-413f-aab9-52356030062d
UserName                 : NAV2018-CU8SE\XX***
FullName                 :
State                    : Enabled
ExpiryDate               : 0001-01-01 00:00:00
WindowsSecurityID        : S-1-5-21-1637059168-3680415861-3648700197-1001
ChangePassword           : False
LicenseType              : FullUser
AuthenticationEmail      :
ContactEmail             :
ExchangeIdentifier       :
ApplicationID            : 00000000-0000-0000-0000-000000000000
Password                 :
NameIdentifier           :
AuthenticationKey        :
WebServicesKey           :
WebServicesKeyExpiryDate : 0001-01-01 00:00:00
AuthenticationObjectID   :
DirectoryPermissionSetID :
ProfileID                :
Company                  : CRONUS Sverige AB
LanguageID               : en-US

PS C:\run> Get-NAVServerUserPermissionSet -ServerInstance nav -UserName 'NAV2018-CU8SE\XX***'

UserSecurityID    : 0940979c-7be9-413f-aab9-52356030062d
PermissionSetID   : SUPER
CompanyName       :
Scope             : System
AppID             : 00000000-0000-0000-0000-000000000000
UserName          : NAV2018-CU8SE\XX***
PermissionSetName : This role has all permissions.
AppName           :
`

Has anyone encountered similar problem? I had the same with BC On Premise a couple of days ago.

**Comment by MatDDev** [comment]
Yes, I use the Windows authentication and the password is the same for both container and host. It worked like yesterday and today it doesn't.

**Comment by freddydk** [comment]
Are you connected to the AD server? or are you using cached credentials?
(the latter doesn't work with the way docker and windows auth without gmsa works)

**Comment by PleachiM** [comment]
Or even worse. Is your account or computer connected to your Office 365 or Azure Domain?

**Comment by MatDDev** [comment]
Yeap, it is connected to Office 365. What about that…?

**Comment by PleachiM** [comment]
I really can't tell you much about this. But I also had big issues with connected accounts. If it's just your account create a local user with the same name and same password. 
Then try it again. 
If it's still not working use Start-as with this new local user.

**Comment by MatDDev** [comment]
OK I will try that, because I do not see any other solutions right now… Eventually I will just created new docker :/ Thanks guys, topic can be closed.
