### ISSUE TITLE
How do I export the database?

### ISSUE THREAD

**Issue by rdebath** [Microsoft/nav-docker#317]
The only way I can successfully export a database from one of these docker images is to do an SQL backup and restore. But this no longer works because SQL refuses to downgrade the backup file.

There is no pre-existing *.BAK file within the container, neither is the install image.

I have attempted to use Export-Data/Import-Data but this is still failing. 
Initially I got the error `database access is unsupported when extensions are installed` despite this message I was able to create a "navdata" file.

However, it seems that it's still not possible to restore this backup, when I try I get the error below just before Powershell  segfaults with the popup "powershell has stopped working".

```
PS C:\NAV\14.0.27306> Import-NAVData -DatabaseServer navsql2016 -DatabaseName 'FinancialsGB-14-27306' -AllCompanies -Inc
ludeApplication -IncludeApplicationData -IncludeGlobalData -FilePath C:\temp\FinancialsGB-14-27306.navdata
WARNING: UnhandledErrorMessage
Import-NAVData : Could not load file or assembly 'Microsoft.Dynamics.Nav.Xrm, Version=14.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
At line:1 char:1
+ Import-NAVData -DatabaseServer navsql2016 -DatabaseName 'FinancialsGB ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-NAVData], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.Dynamics.Nav.Management.Cmdlets.ImportNavData

PS C:\NAV\14.0.27306>
```

**Comment by freddydk** [comment]
What are you trying to achieve?
Why do you want to export the database?

**Comment by rdebath** [comment]
I need to put the database onto a machine that's a member of the domain for an internal extension. 
(NB I don't care that it's a Saas database as that's trivial to change)

**Comment by marknitek** [comment]
Yeah if i want to store database on an external sql server i cannot backup/restore the internal db unless the server is sql 2017. i would need to use a bak from the dvd which is not easy to automate... 
But i dont see how it could be done better other than microsoft should provide a clean interface/api to get dvds just like we have now with docker
But that would only work for nav/onprem bc anyway...

**Comment by freddydk** [comment]
You can copy the .mdf and .ldf files and attach them on your local machine.
Use Extract-FilesFromNavContainer with -extract set to database then you should get the files.

**Comment by marknitek** [comment]
Still downgrade to an older sql server version would not be possible with attach but yes that way you get the db files. 
Since we use gMSA and transparent network i can backup/restore to the desired machine anyway.

**Comment by freddydk** [comment]
You could potentially also use the bacpac format and export databases as bacpac.
In the end, this is not something I will fix in the containers, sorry.

**Comment by rdebath** [comment]
Downgrade to SQL2016 successful, thanks.
