### ISSUE TITLE
2019 server with containers error when deploying BC

### ISSUE THREAD

**Issue by tbedk** [Microsoft/nav-docker#322]
I get this error if I run the following script

Initialization of container D365BCNY failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.4.3.2\ContainerHandling\Wait-NavContainerReady.ps1:45 cha
r:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...D365BCNY failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container D365BCNY failed

New-NavContainer -containerName $ContainerName `
-licenseFile "c:\bredana\license.flf" `
-myScripts  @("C:\bredana\scripts\AdditionalSetup.ps1", "C:\bredana\scripts\setupDevDbAccess.ps1", "C:\bredana\scripts\setupDevNavUsers.ps1") `
-accept_eula `
-accept_outdated `
-shortcuts Desktop `
-includeCSide `
-enableSymbolLoading `
-doNotExportObjectsToText `
-auth Windows `
-Credential $Credential `
-updateHosts `
-restart unless-stopped `
-additionalParameters @('--security-opt credentialspec=file://d365bcny.json','-e DevDomain=bredev','-e DevGroup=ContainerUser','-v c:\temp') `
-imageName ${imagename}

**Comment by freddydk** [comment]
You probably need to provide some more information for anybody to be able to help you here.
The output of new-navcontainer is valuable - and if that doesn't give anything - then the output of docker logs d365bcny).
Also you could try to remove some of your parameters to see which parameters causes the issues.

**Comment by freddydk** [comment]
I will close this one with insufficient info provided.
