### ISSUE TITLE
mcr.microsoft.com/businesscentral/onprem:ch gets you cu1-ch instead of latest (cu3-ch at the time)

### ISSUE THREAD

**Issue by CptBlaubart** [Microsoft/nav-docker#323]
Yesterday (29. Jan, 2019) I wanted to pull the latest swiss onprem image by using the image name.
mcr.microsoft.com/businesscentral/onprem:ch
Just now, i realized that this is build 13.0.25924 - CU1. Please update your tags' destinations.

**Comment by freddydk** [comment]
Use -alwayspull on new-navcontainer to be sure to get the latest.

**Comment by CptBlaubart** [comment]
C:\> docker images
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
mcr.microsoft.com/businesscentral/onprem   rtm-ch              5a4ddd40c1b4        2 months ago        18.1GB
mcr.microsoft.com/businesscentral/onprem   latest              44be28bafc61        2 months ago        16.8GB
mcr.microsoft.com/businesscentral/onprem   ch                  8e3d3abefdf8        2 months ago        17.9GB
microsoft/bcsandbox                        ch                  6b5d460e99ef        2 months ago        18.3GB
C:\>

While i was trying to update now, i noticed that my script stopped after pulling. - maybe there IS a problem.
I'll try "-alwayspull" but it's also possible that my harddrive is at it's limit and i have to free up some space again. - these docker images are really quite some load on your local drives.

**Comment by freddydk** [comment]
If you are running 1809 (fall update of windows 10) you should clean up you images and switch to use ltsc2019 images (1/3 in size).
You can read a lot about this on my blog.

**Comment by freddydk** [comment]
and btw - the images likely do not take up the amount it states as they will be sharing quite a lot of layers.
I also blogged about a cleanup script last month, which cleans up after docker so that you can start fresh.

**Comment by CptBlaubart** [comment]
tbh. when MS turned to docker i was hoping to have more flexible, and easily maintainable work environments. What i actually got, was a chore to stay up to date with another technology, maintaining my machine way more often and getting confused with new image tags or even worse, get no decent notice about depreciated ones. I Just researched your blog, 2nd post from the top is about cleaning up docker. 
Third chapter is about another new tool and a huge disclaimer that this might wreck my machine. - I have work to do. - Which company is supposed to stay feasable while losing half of their dev-team

**Comment by NAVspecialist** [comment]
I totally disagree.. The Docker images are VERY cool help. Compared to earlier I was struggling issues like

- installing the same version but different CUs on same machine
- Running 10-15 Hyper-V OS images with FULL Office+NAV (each image taking up 60gig plus
- Constant Windows updates of my hyper-v Images.
- Destroying databases because i accidentially open a database with the wrong version and saying yes to "upgrade" it.

To ME docker is an angel from heaven

**Comment by CptBlaubart** [comment]
That's what i was hoping for. But right now, all i get to do is watching the navcontainerhelper pulling a new image and then returning to the prompt instead of spinning up the machine. - Not giving me any hints why it stopped, so i'll probably spend the next few hours trying to figure out what went wrong. (my bet is on the drivespace but there is barely anything of big space usage left for me to delete except for that 96 GB docker-folder.)

**Comment by freddydk** [comment]
Sorry that you feel that way, but remember that you are not forced to use Docker.
Business Central on prem releases as DVDs as well.

NavContainerHelper is also just an open source tool, which is aiming at allowing people without deep Docker knowledge to use Docker.
Docker does have a learning curve, but 99% of the people I talk to do get huge savings in time and effort by using Docker.
With the latest version of Docker (18.09.1) and Windows 1809 - we have a very good package.
Images are small, they support process isolation and works very smooth.
