### ISSUE TITLE
Error during restore with generic image and mapped dvd (NAV2015)

### ISSUE THREAD

**Issue by marknitek** [Microsoft/nav-docker#324]
When i try to run a container with the generic image i get the following error:
```
Database restore operation failed due to the following error returned by SQL Server:
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
at <ScriptBlock>, C:\Run\navinstall.ps1: line 126
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1
```
I'am using `NAV.8.0.50527.CH.DVD` to start the image.
Here is my command:
```
docker run -e accept_eula=Y --volume "C:\temp\NAV.8.0.50527.CH.DVD:C:\NAVDVD" --name nav2015 --security-opt "credentialspec=file://LOGContHosts.json" --network=LAN --env ExitOnError=N  microsoft/dynamics-nav:generic-ltsc2019
```
When i connect to the container i can see that the sql server service stops during the restore

What am i doing wrong?

**Comment by marknitek** [comment]
Ok seems to be a problem with the gMSA or Transparent Network... if i remove them it works. 
Any Ideas?

**Comment by freddydk** [comment]
Unfortunately not - NAV 2015 images are not really supported. I have tested that you can do the most basic stuff with NAV 2015.
Lets see if anybody else have experiences with NAV 2015 and gMSA?

**Comment by marknitek** [comment]
If i try to create my own image by using the build scripts in this repo, i get the same error during the last build step `RUN \Run\buildimage.ps1`

When i stopped some other containers running and some other processes on my machine, it worked. So i guess it could be realted to the timeout of 300 seconds in `navinstall.ps1`? Would that throw such an error message?
```
New-NAVDatabase -DatabaseServer $databaseServer `
                -DatabaseInstance $databaseInstance `
                -DatabaseName "$databaseName" `
                -FilePath "$databaseFile" `
                -DestinationPath "$databaseFolder" `
                -Timeout 300 | Out-Null
```

**Comment by freddydk** [comment]
Yeah, I guess this could very well be a perf. issue during build. If you are cloning the project to do your own build, you can also override the navinstall.ps1 with a new version changing this.
