### ISSUE TITLE
Can't generate symbols (onprem:se/13.3.27233.0|13.3.27233.0)

### ISSUE THREAD

**Issue by NAVFreak** [Microsoft/nav-docker#325]
I have now tried to generate symbols to several onprem SE containers:
mcr.microsoft.com/businesscentral/onprem:se  
mcr.microsoft.com/businesscentral/onprem:13.2.26556.0-se
mcr.microsoft.com/businesscentral/onprem:13.3.27233.0-se-ltsc2016

When I do it with the sandboxes it works.
microsoft/bcsandbox:se
microsoft/bcsandbox:13.2.26556.0-se

It also works with:
mcr.microsoft.com/businesscentral/onprem

All the containers have been generated in the same way:
```
new-navcontainer `
           -accept_eula `
           -containername $ContainerName `
           -imageName $ImageName `
           -includecside `
           -licenseFile $LicenseFile `
           -Credential $Credential `
           -auth NavUserPassword `
           -verbose `
           -enableSymbolLoading        

#Import CSIDE
        Import-ObjectsToNavContainer `
            -objectsFile "$FullFilePath" `
            -containerName $containername `
            -sqlCredential $SQLcredential

    Compile-ObjectsInNavContainer `
        -containername $containername `
        -sqlCredential $sqlcredential 

    Generate-SymbolsInNavContainer -containerName $containername
```
After that I go to the app folder, delete the apps in the .alpackages folder, then download symbols.
The CSIDE objects don't get included in the downloaded symbols. I have verified via "AL Code outline" extension to VS Code.

**Comment by freddydk** [comment]
If you have -enableSymbolLoading, then Compile-ObjectsInNavContainer should generate symbols and the Generate-Symbols should not be needed - but it shouldn't harm.

I have tried to repro using your code - and your images - using this (very simple CSIDE codeunit): https://www.dropbox.com/s/616diqx1w7pg2d6/cod50100.txt?dl=1
In VS Code, I have modified the hello world trigger to
```
    trigger OnOpenPage();
    var
        c: Codeunit freddy;
    begin
        Message('App published: Hello world' + FORMAT(c.Test(5, 6)));
    end;
```
I don't use AL Code Outline - I simply download symbols in VS Code and build the project.
Seems to work just fine.
I am using ltsc2019 containers - but that shouldn't cause any difference...
Could you verify that this works with this very simple codeunit for you - then we can try to figure out what makes it fail? (something in the objects maybe - or object ids?)

**Comment by NAVFreak** [comment]
Well if you haven't updated the images this becomes embarrasing...
Because now I can't reproduce the error either. It works like a charm. 
I had tried this several times and I even asked a colleague to try it on his computer and he had the same thing. 

For the record, I tried to download the symbols and build the project, AL Code outline was more a verification to see that the objects weren't included in the symbols.

**Comment by NAVFreak** [comment]
Now I have managed to find out what went wrong. It was a mix between the app version number and downloading the symbols. 

If I set the app version to 13.0.0.0 it will download the symbols that contains my CSIDE objekts with 
_http://ContainerName:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0_ 
which gives me the file _Microsoft_Application_**113.0.27183.0**1.app_

But if I set the app version to the same as the  applicatoin version (13.3.27233.0), I get a different resultat. 
The url
 _http://ContainerName:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=13.3.27233.0_
 gives me the file Microsoft_Application_**13.3.27233.0**.app

If I compare this two one contains my partner cside objects (App version 13.0.0.0, symbolfile Microsoft_Application_13.0.27183.0.app) but the other one doesn´t.
The size of the file differs between 2-3 MB
 
The weird thing is that both symbol files contains the test toolkit which was imported as cside. 

The reason to I found this was that I tried to use the powershell function Compile-AppInNAVContainer. After a while I noticed that it downloads different symbols then if I have tried to build the package from VS Code (CTRL+F5). In that function it looks at what apps are installed and then download each of them as symbols. The app Microsoft_Application_113.0.27183.0 doesn't even exist in the list given from Get-NavAppInfo.

$publishedApps = Invoke-ScriptInNavContainer -containerName $containerName -ScriptBlock { Param($tenant)
        Get-NavAppInfo -ServerInstance NAV -tenant $tenant
        Get-NavAppInfo -ServerInstance NAV -symbolsOnly
    } -ArgumentList $tenant

**Comment by freddydk** [comment]
I have fixed this in NavContainerHelper by removeing the Application and the Test symbols if you are running hybrid (enableSymbolLoading).
Furthermore - I have filed a bug on the team responsible for the application version number in the database to get fixed - and I will write up a blog post on how to work with Symbols.
