### ISSUE TITLE
Windows Authentication with Port mapping (NAT) not working

### ISSUE THREAD

**Issue by marknitek** [microsoft/nav-docker#326]
I tried to use port mapping for the first time with nav/bc and i'am having issues with windows authentication. 
When i create a container with the following command (sensible data removed): 
```
& docker run `
  --name natcont1 `
  --hostname natcont1 `
  --network nat `
  --dns=xx.xx.xx.xx `
  --security-opt "credentialspec=file://XXX.json" `
  -e auth=Windows `
  -e username=XX `
  -e usessl=n `
  -e accept_eula=y `
  --publish 10000:80 `
  --publish 10001:8080 `
  --publish 10006-10009:7046-7049 `
  -e publicWebClientPort=10000 `
  -e publicFileSharePort=10001 `
  -e publicWinClientPort=10006 `
  -e publicSoapPort=10007 `
  -e publicODataPort=10008 `
  microsoft/dynamics-nav:2018-ch-ltsc2019
```
I can connect to the container when using container ip/name on the host, but as soon as i try to connect by using localhost:10000/nav or from an other machine i get an authorization error (401). 

If i try to use the same configuration but with UserPassword authentication it works just fine. 
Am i missing something? Does Windows Auth not work over NAT or something?

In the past i used transparent network but we currently do not have enough ip numbers left for the amount of containers i intend to create.

**Comment by lippertmarkus** [comment]
This is a general problem and also doesn't work for me with normal ASP.NET core apps running in a container with port mappings. Hadn't time to investigate if that's a problem of Docker and the port mapping or a problem of the authentication handshake. I actually don't know if Kerberos/NTLM also checks hostnames or something similar which could cause this issue.

**Comment by freddydk** [comment]
Instead of using port mapping, you can also use WebClientPort, SoapServicesPort, oDataServicesPort, DeveloperServicesPort, ClientServicesPort and FileSharePort. This will make the container listen to these ports directly without port mapping. I don't know if that makes a difference.

**Comment by lippertmarkus** [comment]
@marknitek I now saw that you're running on Server 2019 and I had above mentioned problems only on 2016.

Running the following did work for me without a problem:
```
docker run --rm -p 8080:80 --network=nat --name=cde --hostname=cde --security-opt "credentialspec=file://cont4.json" -e auth=Windows -e usessl=n -e accept_eula=y microsoft/dynamics-nav:2018-ch-ltsc2019
```

I can connect via the hostname of the docker host on port 8080 after making sure the port is opened in the hosts firewall.

From your docker run command I can see that you confused the order of the ports specified in `--publish`. It should be `--publish portOnDockerHost:portInContainer`, so for the webclient (as you set it to listen on 10000) it would be `--publish 80:10000`.

**Comment by marknitek** [comment]
@lippertmarkus I can not confirm that it is working. I tried it with only port mapping and not changing `publicWebClientPort`.
Yes you are right the config i tried could not work, i mixed port mapping with actually changing the ports like @freddydk suggested. 
But it does not work with only mapping the standard ports eighter:
```
& docker run `
  --name natcont1 `
  --hostname natcont1 `
  --network nat `
  --dns=xx.xx.xx.xx `
  --security-opt "credentialspec=file://XXX.json" `
  -e auth=Windows `
  -e username=XX `
  -e usessl=n `
  -e accept_eula=y `
  --publish 10000:80 `
  --publish 10001:8080 `
  --publish 10006-10009:7046-7049 `
  microsoft/dynamics-nav:2018-ch-ltsc2019
```
I can see the download site on port 10001 (with the vsix) so it is not a general connection issue, its just a authentication issue over port mapping from another machine then the docker host.

**Comment by freddydk** [comment]
If you use port mapping, you need to set the publicxxxport variables - else the container won't know which URL is the right one.
The "new" way is to use -e WebClientPort=10000 (which reconfigures instead of mapping).

**Comment by marknitek** [comment]
@freddydk thanks for clarification. I tried it this way:
```
& docker run `
  --name natcont2 `
  --hostname natcont2 `
  --network nat `
  --dns=x.x.x.x `
  --security-opt "credentialspec=file://XX.json" `
  -e auth=Windows `
  -e username=XX `
  -e usessl=n `
  -e accept_eula=y `
  -e WebClientPort=10000 `
  -e FileSharePort=10001 `
  -e ClientServicesPort=10006 `
  -e SoapServicesPort=10007 `
  -e oDataServicesPort=10008 `
  -e DeveloperServicesPort=10009 `
  -p 10000-10009:10000-10009 `
  microsoft/dynamics-nav:2018-ch-ltsc2019
```
Still getting a 403 when trying to connect from another machine. Http download site works.
