### ISSUE TITLE
How to increase the container space when it runs out?

### ISSUE THREAD

**Issue by jeffgit** [Microsoft/nav-docker#328]
Hello,

I used Azure Template and provisioned the Azure VM Container Sandbox for development. Now the space has run out, but the VM still has lots of room . How do I allocate more storage for the container?

Thanks,

**Comment by jeffgit** [comment]
Interesting enough, when I checked the storage usage with the command below, it shows zero bytes.
![image](https://user-images.githubusercontent.com/2955741/53374527-7150f580-390d-11e9-841c-9c7b7150c5f6.png)

**Comment by freddydk** [comment]
https://twitter.com/freddydk/status/1072789978340560896

**Comment by freddydk** [comment]
New Azure VMs set this value to 100GB - I would delete your VM and create a new one.
Or modify SetupNavContainer on your VM and recreate the container - you cannot extend the content of existing containers.

**Comment by freddydk** [comment]
In the new SetupNavContainer you will find these lines:
```
...
$params = @{ "enableSymbolLoading" = $true 
             "licensefile" = "$licensefileuri"
             "publishPorts" = @(8080,443,7046,7047,7048,7049)
             "publicDnsName" = $publicDnsName }

$additionalParameters = @("--env RemovePasswordKeyFile=N",
                          "--storage-opt size=100GB")

if ("$appBacpacUri" -ne "" -and "$tenantBacpacUri" -ne "") {
    if ("$sqlServerType" -eq "SQLExpress") {
...
```
where the storage-opt is the new setting

**Comment by jeffgit** [comment]
Thanks for the quick response Freddy! Did you mean to add the additionalParameters when running New-NavContainer? I don't see there is command 'SetupNavContainer'. I wonder if there is a way to just change the container startup parameter. Where is in the host VM that specifies the docker container startup parameters?

**Comment by freddydk** [comment]
SetupNavContainer is a script in c:\demo

You would have to modify that and run Replace-navservercontainer – which will remove your container and create a new one.
I don’t think you can get around re-creating the container.

/Freddy

**Comment by jeffgit** [comment]
Got it, thank you! How do I verify the space allocated for the container and how much has been used? According to my screenshot above, it doesn't seem to make sense to me.

**Comment by freddydk** [comment]
docker exec -it fkdev cmd to open a command prompt and write DIR.
There might be other ways, but I never have containers running for more than a few days, so they normally never run over.
you can also run
docker exec fkdev powershell Get-WmiObject -Class Win32_logicaldisk

**Comment by jeffgit** [comment]
Both ways work, thanks!
