### ISSUE TITLE
nav2018-cu15 isn't yet available?

### ISSUE THREAD

**Issue by elweilando** [Microsoft/nav-docker#331]
I have tried with microsoft/dynamics-nav:2018-cu15-de and microsoft/dynamics-nav:2018-cu15-fi trough navcontainerhelper.

`DockerDo : Error response from daemon: manifest for microsoft/dynamics-nav:2018-cu15-de not found`

**Comment by freddydk** [comment]
They are there now

microsoft/dynamics-nav:2018-cu15-de

or

mcr,microsoft.com/dynamicsnav:2018-cu15-de
