### ISSUE TITLE
Container can't be reached 

### ISSUE THREAD

**Issue by doozu** [microsoft/nav-docker#332]
I have created a NAV container, the connection to the external SQL database works fine.
However, when I try to connect to the container with the client I always get the message 
"Unable to connect to the server". 
The same problem exists when I try to connect to the web client. 
If i try to ping the container this works without any problems (no matter which device).

**The command that im using:**

docker run -e ACCEPT_EULA=Y --hostname Docker-NAV2017 --name NAV2017 -e auth=Windows -e doNotExportObjectsToText --security-opt "credentialspec=file://gMSA.json" -e clickonce=y  --network tlan -e DatabaseServer=SQL2016 -e DatabaseInstance="" -e DatabaseName="avitea NAV100"  microsoft/dynamics-nav:2017-cu4-de

Unfortunately, I have no idea how I can solve this problem.

**Comment by freddydk** [comment]
Try to switch to navuserpassword authentication

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: doozu <notifications@github.com>
Sendt: Wednesday, March 13, 2019 9:56:17 AM
Til: Microsoft/nav-docker
Cc: Subscribed
Emne: [Microsoft/nav-docker] Container can't be reached (#332)


I have created a NAV container, the connection to the external SQL database works fine.
However, when I try to connect to the container with the client I always get the message
"Unable to connect to the server".
The same problem exists when I try to connect to the web client.
If i try to ping the container this works without any problems (no matter which device).

The command that im using:

docker run -e ACCEPT_EULA=Y --hostname Docker-NAV2017 --name NAV2017 -e auth=Windows -e doNotExportObjectsToText --security-opt "credentialspec=file://gMSA.json" -e clickonce=y --network tlan -e DatabaseServer=SQL2016 -e DatabaseInstance="" -e DatabaseName="avitea NAV100" microsoft/dynamics-nav:2017-cu4-de

Unfortunately, I have no idea how I can solve this problem.

**Comment by doozu** [comment]
Since I am in a domain, I would like to register with my domain account.

**Comment by doozu** [comment]
Unfortunately that did not help.
What I forgot to write, I am in a domain network and would like to log in with my domain user

**Comment by freddydk** [comment]
Are you trying with the Windows Client or the Web Client?
Are you trying from the same machine on which the container is running?
try to add -updatehosts to new-navcontainer and maybe try to use ipconfig /flushdns after running the command.

**Comment by doozu** [comment]
> Are you trying with the Windows Client or the Web Client? 

I tried both

> Are you trying from the same machine on which the container is running?

No, the container is running on an extra Windows server and I try to connect from my laptop


> try to add -updatehosts to new-navcontainer and maybe try to use ipconfig /flushdns after running the command.

I tested it, but I still can not connect to the container

**Comment by freddydk** [comment]
I didn't look close enough on your new-navcontainer - then I could see you are using tlan and gmsa and that updatehosts wouldn't make a difference.

You say you can ping the server - what dns name do you use to ping the server?
is that ping docker-nav2017?

**Comment by doozu** [comment]
I can only ping the container via the IP, it does not work with the name.

In the nav windows client I tried to connect to the IP address and not the host name.

**Comment by freddydk** [comment]
on your laptop - edit c:\windows\system32\drivers\etc\hosts - add the IP number and host name - and try

**Comment by doozu** [comment]
A ping with the container name works now, but I still can not connect to the container

**Comment by freddydk** [comment]
Can you navigate to http://host:8080 in a browser?

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: doozu <notifications@github.com>
Sendt: Wednesday, March 13, 2019 2:31:21 PM
Til: Microsoft/nav-docker
Cc: Freddy Kristiansen; Comment
Emne: Re: [Microsoft/nav-docker] Container can't be reached (#332)


A ping with the container name works now, but I still can not connect to the container

**Comment by doozu** [comment]
When I try to connect I get an error message "ERR_CONNECTION_TIMED_OUT"

**Comment by doozu** [comment]
Would you still have an idea?

**Comment by freddydk** [comment]
Not really - I don't think the IP address you have is really the container.

**Comment by doozu** [comment]
I looked again, but the IP address I use is the right one

**Comment by freddydk** [comment]
I am out of suggestions - I don't think this problem is in any way connected to NAV/BC Containers - but seems to be something in your network.
