### ISSUE TITLE
Latest version gave me the first version ?!

### ISSUE THREAD

**Issue by TheGreatBorg** [Microsoft/nav-docker#333]
I have just "pulled" the latest image version of NAV/BC but it turn out to be NAV2016 and not NAV2018 or BC?

I used this command: docker pull microsoft/dynamics-nav

**Comment by freddydk** [comment]
If I do run:

get-navcontainerimagelabels -imageName microsoft/dynamics-nav

I get

```
country    : W1
created    : 201903121220
cu         : cu15
eula       : https://go.microsoft.com/fwlink/?linkid=861843
legal      : 
maintainer : Dynamics SMB
nav        : 2018
osversion  : 10.0.14393.2791
tag        : 0.0.9.2
version    : 11.0.28629.0
```

and if I do

docker pull microsoft/dynamics-nav
and
docker inspect microsoft/dynamics-nav

I get the same - nav 2018 cu15

How do you determine that you have nav 2016 - is it by running a container?
How do you run the container?

**Comment by TheGreatBorg** [comment]
Well I must have expected that the latest NAV should be BC and seeing the Web Client UI I panicked and thought OMG I just got an old version based on this (see my question below - witch must be the Windows Server version):

![image](https://user-images.githubusercontent.com/31419036/54808282-11d1d580-4c80-11e9-860b-32dbc340d9f1.png)
 
Another question: Where in a NAV/BC Web Client can you determine witch version you are running? 

If I didn't have OMA installed on my On Premise NAV2018 I would never have found "System Information" 

_"You really need to know what you need to search for in new the NAV/BC Web Client - If you don't know - you will never know"_

**Comment by freddydk** [comment]
ltsc2016 stands for Long Term Servicing Channel 2016 - which is the term used.
If you are using Windows 10 1809 or Windows Server 2019 you can use ltsc2019 to get smaller and more performant images.
There is a lot of info about this on my blog (freddysblog.com)
