### ISSUE TITLE
Platform Label missing on BC CU3 CH Image

### ISSUE THREAD

**Issue by marknitek** [Microsoft/nav-docker#339]
It seems like the platform label is missing at least on the bconprem:cu3-ch-ltsc2019 image. 
Is there a reason for that? 
My self-provisioning application uses that label to know the correct major/minor version of the platform so i can map a volume to the service tier folder.

**Comment by freddydk** [comment]
Something must have gone wrong with the latest builds , will investigate

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Marco <notifications@github.com>
Sendt: Wednesday, April 3, 2019 2:20:50 PM
Til: Microsoft/nav-docker
Cc: Subscribed
Emne: [Microsoft/nav-docker] Platform Label missing on BC CU3 CH Image (#339)


It seems like the platform label is missing at least on the bconprem:cu3-ch-ltsc2019 image.
Is there a reason for that?
My self-provisioning application uses that label to know the correct major/minor version of the platform so i can map a volume to the service tier folder.

**Comment by freddydk** [comment]
The images created yesterday is missing this - all will be overwritten within the next hours...

**Comment by freddydk** [comment]
Images have been rebuilt

**Comment by marknitek** [comment]
Well there still seems to be some issues.

```
docker pull mcr.microsoft.com/businesscentral/onprem:ch-ltsc2019
ch-ltsc2019: Pulling from businesscentral/onprem
Digest: sha256:4c48f0c6668f6ef712c1faf707f1d6e8191790e06857504b229b7defaa23bfd3
Status: Image is up to date for mcr.microsoft.com/businesscentral/onprem:ch-ltsc2019
```
result of docker inspect:
```
"Labels": {
                "country": "ch",
                "created": "201904030848",
                "cu": "rtm",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Dynamics SMB",
                "nav": "1904",
                "osversion": "10.0.17763.379",
                "tag": "0.0.9.3",
                "version": "14.0.29537.0"
            },
```
Platform tag is missing...

**Comment by freddydk** [comment]
Very strange, will investigate again

**Comment by freddydk** [comment]
It looks like only w1 images was fixed:-(

**Comment by freddydk** [comment]
I have rebuilt the local images and the platform label should now be present

**Comment by marknitek** [comment]
onprem:ch now works and has the label. 
But CU3-CH still misses the label:
```
"Labels": {
                "country": "ch",
                "created": "201904020319",
                "cu": "cu3",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Dynamics SMB",
                "nav": "1810",
                "osversion": "10.0.17763.379",
                "tag": "0.0.9.3",
                "version": "13.3.27233.0"
            },
```
Not sure about other images

**Comment by freddydk** [comment]
WOW - stupid me:-(
Yes, I know why, these images was rebuild as 1810-cu3-ch-ltsc2019 - that is a lasting name.
The new are 1904-rtm-ch-ltsc2019
I will rebuild the latest tags.

sorry about this.

**Comment by marknitek** [comment]
Ah i see. That makes sense. 

To be honest it gets a bit confusing now that we have 1810 and 1904 to differentiate and CUs for both of them. 

Thanks for fixing this

**Comment by freddydk** [comment]
To be honest, I didn't know that we would have 1810 and 1904 half a year ago:-(
