### ISSUE TITLE
Unable to Compile / Force Table Schemas

### ISSUE THREAD

**Issue by megel** [Microsoft/nav-docker#34]
The ClickOnce of C/Side is now running and an import of objects works too, but I have still problems to compile and synchronize the imported tables. Any ideas?

Compile Objects:
![grafik](https://user-images.githubusercontent.com/15800069/29782196-ee9cb876-8c1b-11e7-9cdf-60f440175183.png)

Synchronize Table Schemas
![grafik](https://user-images.githubusercontent.com/15800069/29782168-d298cb06-8c1b-11e7-9878-5db970622aaa.png)

Container (from today): 
```
docker run --rm -h nav-dev -v "$volume" -e licensefile=$licFile -e ACCEPT_EULA=Y -e username=$username -e password=$password -d -e WindowsAuth=N -e UseSSL=N -d -m 3G -e ClickOnce=Y navdocker.azurecr.io/dynamics-nav:devpreview
```

```
Initializing...
Hostname is nav-dev
Running Specific Image
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (MSSQLSERVER) (MSSQLSERVER)' to
start...
WARNING: Waiting for service 'SQL Server (MSSQLSERVER) (MSSQLSERVER)' to
start...
WARNING: Waiting for service 'SQL Server (MSSQLSERVER) (MSSQLSERVER)' to
start...
Using NavUserPassword Authentication
Using Database Connection localhost/ [CRONUS]
Modify NAV Service Tier Config File for Docker
Create Self Signed Certificate
Self Signed Certificate Thumbprint B0161C21AFB2E4FAE13D1E2850203D8670567F09
Modify NAV Service Tier Config File with Instance Specific Settings
Start NAV Service Tier
Using license file 'c:\run\my\GERMAN NAV2017 Developer License.flf'
Import NAV License
Create Web Site
Create NAV Web Server Instance
Create http download site
Create ClickOnce Manifest
-- ADDITIONAL SETUP : START --
In-Client Visual Designer has not been activated as C:\inetpub\wwwroot\web.config does not exist
-- ADDITIONAL SETUP : END --
Container IP Address: 172.27.239.165
Container Hostname  : nav-dev
Web Client          : http://nav-dev/NAV/WebClient/
Dev. Server         : http://nav-dev
Dev. ServerInstance : NAV
ClickOnce Manifest  : http://nav-dev:8080/NAV

Files:
http://nav-dev:8080/al-0.8.11706.vsix

Ready for connections!
```
![grafik](https://user-images.githubusercontent.com/15800069/29782410-c70f31c0-8c1c-11e7-8585-51d52cd0c5e6.png)

**Comment by richardrobberse** [comment]
Maybe multi tenancy is enabled and tenant default is not mounted?

**Comment by tfenster** [comment]
In my experience you need to use gMSAs, see https://www.axians-infoma.de/navblog/using-ad-accounts-in-containerized-nav-and-what-i-learned-on-the-way/

**Comment by mcoaggie** [comment]
Not sure about how to go about this in the docker environment but "Run as Administrator" may also cure this issue.

**Comment by Koubek** [comment]
I agree with @tfenster. We solved the same problems (same error messages) using gMSA. And now we are working with NAV on Docker only in gMSA-enabled environment and everything is fine.

**Comment by freddydk** [comment]
I found the same thing - Windows authentication solves the issue. gMSA or the "hack".
The "hack" being where you use same username/password in docker as on the host and set auth=Windows. I updated the NAV Docker Image.docx document here on github (will become a whitepaper when done) and it also explains how to make this work.

**Comment by Koubek** [comment]
Just to confirm the schema synchronization problems and solutions:

I have tested locally without gMSA and there are two scenarios using the WinAuth hack:
- Accessing via ClickOnce distributed C/SIDE doesn\`t work for me (the syncing).
- Using local C/SIDE (local copy) works correctly.

The script mentioned in the documentation (should be placed in `AdditionalSetup.ps1`):
```PowerShell
if (!(Test-Path "$myPath\RoleTailored Client" -PathType Container)) {
    Write-Host "Copy RoleTailoted Client files"
    Copy-Item -path $roleTailoredClientFolder -destination $myPath -force -Recurse -ErrorAction Ignore
}
```

**Comment by wortho** [comment]
An alternative solution I found was to first save the table in Finsql using the Synchronize Schema "Later" option and then create a remote PS Session using:
"Enter-PSSession -ContainerId <ID> -RunAsAdministrator"
From that PS Session I could then run Sync-NAVTenant to sync the table.
