### ISSUE TITLE
Error with last image in BCSANDBOX

### ISSUE THREAD

**Issue by aetxebarria** [Microsoft/nav-docker#340]
Hi everyone,
I've just created a new docker with the last version pulled from bcsandbox. Looks that everything has been allright, but when I open the windowsClient, I see this error:
![imagen](https://user-images.githubusercontent.com/41778563/55489018-718d9080-5631-11e9-889d-fb5e414ab832.png)

Any hint about his issue?

**Comment by freddydk** [comment]
How are you creating the container?
Do you use clickonce?

**Comment by aetxebarria** [comment]
I've created with this command:

`New-CSideDevContainer -containerName BeteaBC  -accept_eula -auth NavUserPassword -imageName "microsoft/bcsandbox:es" -licensefile "C:\6045219-desa2018.flf" -alwayspull -accept_outdated`

**Comment by freddydk** [comment]
You are using a very old version of NavContainerHelper.
New-CsideDevContainer has been removed for several months.
Update NavContainerHelper and use New-NavContainer - use -includecside if you need cside.

**Comment by aetxebarria** [comment]
Hi Fredy,
I have the 0.5.0.11 version. according to your blog, the last one, am I right? I've removed the container, and created a new one with:
`New-NAVContainer -containerName BeteaBC  -accept_eula -auth NavUserPassword -imageName "microsoft/bcsandbox:es" -licensefile "C:\6045219-desa2018.flf" -alwayspull -accept_outdated -includecside`
And I still have the problem. The error message jsut appears in the home landing page, if I go to another page, I don't see the error...
Appart from this issue, I have another dpubt. According to the last changes sghown in dierctions Asia, in where can I get the image version for 2019 fall? 

Thanks for everything

**Comment by freddydk** [comment]
We will start building fall images later - not sure when yet.
0.5.0.11 is the latest - what do you mean when referring to the home landing page - do you mean the new-navcontainer output? what error do you get?

**Comment by aetxebarria** [comment]
When I log into the cliente, is the first I see:

![imagen](https://user-images.githubusercontent.com/41778563/55544597-b6660580-56cb-11e9-826b-dc7e96c1a0fe.png)

If I chaneg to any other page, customer list for example, I don't see the error again.  
i activated the debugger, retunr to the home page, and the debugger stops here:
![imagen](https://user-images.githubusercontent.com/41778563/55544749-05139f80-56cc-11e9-8794-bd374225a9f1.png)

Seems to be a problem with the O365 integration.

**Comment by freddydk** [comment]
This of course shouldn't happen but in general, the sandbox images thinks they are an online saas service and as such thinks that they are connected to AAD, we have seen this give problems a number of times.
You could consider using the onprem images instead, they won't have this problem.

**Comment by aetxebarria** [comment]
So, instead of pulling the bcsandbos image, pulling a different one? Which would you recommend?

Thank you very much

**Comment by freddydk** [comment]
Just tried to run the exact same line as you - I do not get an error:

![image](https://user-images.githubusercontent.com/10775043/55545496-9c2d2700-56cd-11e9-84b3-fe4e31301d33.png)

use mcr.microsoft.com/businesscentral/onprem:es that is spring release.

/Freddy

**Comment by aetxebarria** [comment]
Ok, Thank you as always!

**Comment by aetxebarria** [comment]
Hi Freddy,
Sorry for disturbing. I have tried to install the new image, but I don't have enough space. I read your article about cleaning the docker. So, i tried to delete all the content from "C:\ProgramData\docker". The content was very large, and at one time, I stopped the process, thinking that I will lose data for other developments. And when I try to deploy the image, I found errors like:
![imagen](https://user-images.githubusercontent.com/41778563/55548339-891d5580-56d3-11e9-9960-693e08c35790.png)
After, with the aim of cleanning the content in a controlled way, I downloaded the script and I get this error:
![imagen](https://user-images.githubusercontent.com/41778563/55548407-ab16d800-56d3-11e9-9658-8cbcc75cce38.png)

What should I do? SHould I delete all the content from the docker folder? Did I broke something? Can I restore the missing folders?

Thank you very much

**Comment by freddydk** [comment]
It says: Type yes to continue.
You typed y
Type **yes** - then it should clean your docker installation and navcontainerhelper folder.

**Comment by aetxebarria** [comment]
I have had to restore all the docker feature in the server, and pull again the image.
Now I don't get the error, but in the role center:

![imagen](https://user-images.githubusercontent.com/41778563/55554636-90e4f600-56e3-11e9-8a67-84139d801e2d.png)

Anyway, it's not a big issue, it's just for developing so doesn't seem to be a problem

**Comment by freddydk** [comment]
Very strange - it almost seems like the files are blocked so that the service tier cannot load the DLL's

**Comment by aetxebarria** [comment]
I don't think so, it's an azure machine, I don't have any antivirus installed. The previos container didn't have this problem, seems to have relation wih the version....

**Comment by freddydk** [comment]
Windows server 2016 or 2019?

**Comment by aetxebarria** [comment]
Windows server 2016 datacenter

**Comment by freddydk** [comment]
Ok, I am running 2019 - will try 2016.

**Comment by freddydk** [comment]
Just tried with a new 2016 - works fine - cannot repro this.

**Comment by aetxebarria** [comment]
Ok Freddy, really appreciate your help and view
