### ISSUE TITLE
The Windows account could not be mapped to a valid security identifier (SID)

### ISSUE THREAD

**Issue by sirhc101** [Microsoft/nav-docker#341]
Hello,

I've some trouble with docker image for NAV/BC. When I create a new container, using navcontainerhelper, with NavUserPassword authentication everything works fine, except sync schema. Ok, I found several posts regarding this and finally got the answer "works as designed" or it simply doesn't work with NavUserPassword and I should switch to Windows Auth.
I tried to do this but this also doesn't work!

When I create a new container, using navcontainerhelper, and using Windows auth. I got the following output (error):
```
[...]
Creating SUPER user
The Windows account could not be mapped to a valid security identifier (SID).
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 13
at <ScriptBlock>, C:\Run\my\SetupNavUsers.ps1: line 2
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container bc-onprem failed
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.11\ContainerHandling\Wait-NavContainerReady.ps1:45 Zeichen:17
...             throw "Initialization of container $containerName failed" ...

CategoryInfo          : OperationStopped: (Initialization ...c-onprem failed:String) [], RuntimeException
FullyQualifiedErrorId : Initialization of container bc-onprem failed
```

So the problem occurs somewhere in here:
https://github.com/Microsoft/nav-docker/blob/0976a81b525969abd64c97bbd991a529cfa0cdae/generic/Run/SetupNavUsers.ps1#L13

I simply do not have any idea what's the problem...

Thanks for your help

**Comment by freddydk** [comment]
If you use navuserpassword, the workaround is to save the object and call compile-objectsinnavcontainer afterwards.

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Christoph Krieg <notifications@github.com>
Sendt: Thursday, April 4, 2019 4:34:40 PM
Til: Microsoft/nav-docker
Cc: Subscribed
Emne: [Microsoft/nav-docker] The Windows account could not be mapped to a valid security identifier (SID) (#341)


Hello,

I've some trouble with docker image for NAV/BC. When I create a new container, using navcontainerhelper, with NavUserPassword authentication everything works fine, except sync schema. Ok, I found several posts regarding this and finally got the answer "works as designed" or it simply doesn't work with NavUserPassword and I should switch to Windows Auth.
I tried to do this but this also doesn't work!

When I create a new container, using navcontainerhelper, and using Windows auth. I got the following output (error):

[...]
Creating SUPER user
The Windows account could not be mapped to a valid security identifier (SID).
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 13
at <ScriptBlock>, C:\Run\my\SetupNavUsers.ps1: line 2
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container bc-onprem failed
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.11\ContainerHandling\Wait-NavContainerReady.ps1:45 Zeichen:17
...             throw "Initialization of container $containerName failed" ...

CategoryInfo          : OperationStopped: (Initialization ...c-onprem failed:String) [], RuntimeException
FullyQualifiedErrorId : Initialization of container bc-onprem failed


So the problem occurs somewhere in here:
https://github.com/Microsoft/nav-docker/blob/0976a81b525969abd64c97bbd991a529cfa0cdae/generic/Run/SetupNavUsers.ps1#L13<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fnav-docker%2Fblob%2F0976a81b525969abd64c97bbd991a529cfa0cdae%2Fgeneric%2FRun%2FSetupNavUsers.ps1%23L13&data=02%7C01%7Cfreddy.kristiansen%40microsoft.com%7Cb02e34bb185248d054a808d6b90aac3c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636899852829629758&sdata=LO99FiICSycEpGOIVa2%2BhNI6B2UOmfAw6zZqM84k5Kk%3D&reserved=0>

I simply do not have any idea what's the problem...

Thanks for your help

**Comment by sirhc101** [comment]
> If you use navuserpassword, the workaround is to save the object and call compile-objectsinnavcontainer afterwards. Få Outlook til iOS<https://aka.ms/o0ukef>

Yes, I know but It would be really nice to figure out why Windows auth isn't working.

**Comment by mmenninghaus** [comment]
Had the same problem. Overwrote ```SetupWindowsUsers.ps1``` and removed the ```-ErrorAction Ignore``` option which unveiled the following error:
```
unable to update the password. The value provided for the new password does not meet the length, complexity, or history requirements of the Domain
```
Once I changed my password such that it fits the requirements, it worked. (e.g. the password does not contain a digit)

**Comment by freddydk** [comment]
Thanks a million for this insight - will remove the erroraction ignore to capture the reason. I have had a number of people with this problem, but never been able to figure out why this happens.
Maybe this is the reason.
Thanks

**Comment by sirhc101** [comment]
Thank you very much @mmenninghaus 

I changed my password to a more complex one and now everything works fine!!

**Comment by FSharpCSharp** [comment]
These changes now result in very strict password policies being checked, even when working with NAV authentication. Previously, the complexity didn't matter, but now the script aborts during creation if the password is insufficient. This is not so good, because if I use NAV's own authentication, I don't necessarily want to use an incredibly complex password.

**Comment by freddydk** [comment]
I thought that using NavUserPassword, the Windows User would not be created... - but I see that it does.
For now, you should be able to use -myscripts @( @{ "SetupWindowsUsers.ps1" = "" } ) which will override the SetupWindowsUsers script with an empty file, and thus will not create the user. I will investigate whether I can modify the script to only create the user when using Windows Auth.

**Comment by bijoykumar-b** [comment]
Hi,
I am new to BC. Creating a new container, using navcontainerhelper, and using Windows auth. My password contain mix of cases, alphabet and number, hope this match with password policies. Still facing the same issue, please help.

PS C:\WINDOWS\system32> New-NavContainer -accept_eula -containerName "test" -auth Windows -imageName "microsoft/dynamics-nav"
NavContainerHelper is version 0.6.5.11
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 1909
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
Using image microsoft/dynamics-nav:latest-ltsc2019
Removing container test
Removing C:\ProgramData\NavContainerHelper\Extensions\test
Creating Container test
Version: 11.0.29745.0-W1
Style: onprem
Generic Tag: 0.0.9.3
Container OS Version: 10.0.17763.379 (ltsc2019)
Host OS Version: 10.0.18363.836 (1909)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-US
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\test\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupWebClient.ps1
Creating container test from image microsoft/dynamics-nav:latest-ltsc2019
672c3058e6967442f4bd6d8426ed0eeb0737a04fa71cb3711eebe81bc1eca223
Waiting for container test to be ready
Initializing...
Starting Container
Hostname is test
PublicDnsName is test
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Creating Windows user Bijoy
Setting SA Password and enabling SA
Creating SUPER user
The Windows account could not be mapped to a valid security identifier (SID).
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 13
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is test
PublicDnsName is test
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Creating Windows user Bijoy
Setting SA Password and enabling SA
Creating SUPER user
The Windows account could not be mapped to a valid security identifier (SID).
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 13
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container test failed
At C:\Program 
Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.11\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container test failed:String) [], RuntimeExceptio 
   n
    + FullyQualifiedErrorId : Initialization of container test failed

**Comment by freddydk** [comment]
This is probably a good starting point: 
https://freddysblog.com/2019/08/20/business-central-on-docker-for-non-experts/

Which explains where the images are today and maybe you need to use userpassword auth.
