### ISSUE TITLE
Can connect to NAV C.side Client or Web Client

### ISSUE THREAD

**Issue by Ancient13** [Microsoft/nav-docker#342]
After setting up images we are unable to connect.

Container was created successfully, but when we try to  open
•	Web client
•	Windows client
•	C/SIDE environment
They are not working, something server is not found
The C/SIDE has the message the server tempdev\SQLEXPRESS is not found or something similar

**Replicated on 2 partner machines and my machine.**

**Navcontainerhelper 0.5.0.1**

**Images tried**

microsoft/bcsandbox:13.5.29483.0-au-ltsc2019
microsoft/bcsandbox:13.5.29483.0-au-ltsc2016

**Command we are using**

New-NavContainer -accept_eula -alwaysPull -imageName "microsoft/bcsandbox:13.5.29483.0-au-ltsc2019" -containerName AUSB1 -includeCSide -assignPremiumPlan –doNotExportObjectsToText

[Docker inspect and logs.docx](https://github.com/Microsoft/nav-docker/files/3046969/Docker.inspect.and.logs.docx)

**Comment by freddydk** [comment]
add -updatehosts to your new-navcontainer statement.

**Comment by freddydk** [comment]
Did this solve the issue?
