### ISSUE TITLE
Failed to start BC service

### ISSUE THREAD

**Issue by tomasevicstefan** [Microsoft/nav-docker#344]
When building environment on docker, I´m getting this error, that service instance can´t be started.

I updated object to CU05, and think that that cause this error. Docker image is mcr.microsoft.com/businesscentral/onprem:is-ltsc2019, NavContainerHelper version is 0.5.0.6

![1](https://user-images.githubusercontent.com/31925856/55631102-872cc280-57b7-11e9-932d-dba34e7d805a.png)

Can I somehow look in details of this error?

**Comment by freddydk** [comment]
You can use Get-NavContainerEventLog to get the event log.
It is likely your bak file, which has a wrong version

**Comment by tomasevicstefan** [comment]
Thanks for the prompt response. I will check version on bak file.

**Comment by tomasevicstefan** [comment]
This showed event log

![1](https://user-images.githubusercontent.com/31925856/55632932-9c0b5500-57bb-11e9-87f4-dccad2500068.png)

**Comment by freddydk** [comment]
Isn't there more info in the details tab? or in the other error?

**Comment by tomasevicstefan** [comment]
Yes, sorry

![1](https://user-images.githubusercontent.com/31925856/55633393-97936c00-57bc-11e9-855f-953dd3c44cf8.png)

**Comment by tomasevicstefan** [comment]
Also, get this error

![2](https://user-images.githubusercontent.com/31925856/55633554-eb9e5080-57bc-11e9-8138-fd743afb1895.png)

**Comment by freddydk** [comment]
If you remove the bak parameter, I am pretty sure the container will just start.
Then you can use SSMS to restore the bak file, convert the database with the classic dev environment and then create a new bak file.
The container will try to upgrade the database automatically using this code

```
    if (!$multitenant) {
        New-NAVDatabase -DatabaseServer $databaseServer `
                        -DatabaseInstance $databaseInstance `
                        -DatabaseName "$databaseName" `
                        -FilePath "$databaseFile" `
                        -DestinationPath "$databaseFolder" `
                        -Timeout $SqlTimeout | Out-Null
        Start-Process -FilePath "$roleTailoredClientFolder\finsql.exe" -ArgumentList "Command=upgradedatabase, Database=$databaseName, ServerName=$databaseServer\$databaseInstance, ntauthentication=1" -Wait
```
But apparently something goes wrong - you can see the error by redoing this manually.

**Comment by tomasevicstefan** [comment]
Thank Freddy for your response. I will try that and let you know.
