### ISSUE TITLE
Problem with las AL extension and docker

### ISSUE THREAD

**Issue by aetxebarria** [Microsoft/nav-docker#345]
Hello,
Since I've downloaded the last version to a docker, I'm finding a problem after another. 
I have to change a report extension created weeks ago. 
I've installed into VisualStudioCode the last version of AL extension, and I got this error:
![imagen](https://user-images.githubusercontent.com/41778563/55792941-0412b180-5ac2-11e9-849b-f79a2c75e576.png)
I've solved it installing an earlir version of the extension.  (https://github.com/Microsoft/AL/issues/4301)
This provoked the next error:
![imagen](https://user-images.githubusercontent.com/41778563/55793438-2eb13a00-5ac3-11e9-9152-7d341d4708b6.png)

So i changed the runtime to 2.0, and I see this:
![imagen](https://user-images.githubusercontent.com/41778563/55793502-5a342480-5ac3-11e9-8d34-74780c758b30.png)

Anyway, the app file is cerated, and I can upload it as a extension into a cloud BC, but, which should be the correcto way to proceed with this problem?
Thank you very much

**Comment by freddydk** [comment]
This has nothing to do with Docker.
On every container, there is a .vsix that matches this container.
Newer .vsix'es can typically talk to service tiers that are a few versions earlier (I don't know the details), but when I get this error, I typically replace the .vsix with what is in the container.
If you want more info, you should create an issue on the microsoft/AL github issues list, they know the details.

**Comment by marknitek** [comment]
The first error can be solved by installing dotnet framework 4.7.2
Do not use old AL Compiler versions!

**Comment by NAVspecialist** [comment]
@aetxebarria the reason you get this error is that you are running Visual Studio Code with the wrong VSIX-file. 

So what you have to do is to copy the VSIX file from you docker image and inport into Visual Studio Code and then it works nicely.

You can download the vsis-file from your docker container. Just run an elevated command prompt and type 
docker logs spring (where spring is the name of your container)

You'll get something like this:

Initializing...
Restarting Container
PublicDnsName unchanged
Hostname is spring
PublicDnsName is spring
WARNING: DNS resolution not working from within the container.
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Starting Service Tier
Container IP Address: 172.25.201.94
Container Hostname  : spring
Container Dns Name  : spring
Web Client          :
Dev. Server         : http://spring
Dev. ServerInstance : NAV

**Files:
http://spring:8080/al-3.0.106655.vsix**

Initialization took 13 seconds
Ready for connections!

**Comment by aetxebarria** [comment]
Thank you all!
I've downloaded and installed "al-3.0.106655.vsix", installed the 4.7.2 framework, and problem solved.
Thanks again, really appreciated!!!!
