### ISSUE TITLE
No published package matches the provided arguments. [2019-04-13 12:37:24.14]  Not able to download sysmbol

### ISSUE THREAD

**Issue by NavTechAnas** [microsoft/nav-docker#347]

**Comment by NavTechAnas** [comment]
https://api.businesscentral.dynamics.com/v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0
[2019-04-13 12:37:24.09] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=Application&versionText=14.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2019-04-13 12:37:24.14] The request for path /v1.0/sandbox/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2019-04-13 12:37:24.14] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.

**Comment by NavTechAnas** [comment]
@freddydk Not able to download symbol

**Comment by NavTechAnas** [comment]
@freddydk  My app. jason file is i am trying to connect with sandbox

{
  "id": "19d5c2d6-ec66-46aa-b947-4df5724e5cd7",
  "name": "ALProject12",
  "publisher": "Default publisher",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [],
  "screenshots": [],
  "platform": "14.0.0.0",
  "application": "14.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "contextSensitiveHelpUrl": "https://ALProject12.com/help/",
  "showMyCode": true,
  "runtime": "3.0"
}

**Comment by freddydk** [comment]
It looks like you are trying to download symbols from an online sandbox - why are you posting this in the Docker forum?
If you are trying to use Docker, you need a configuration in launch.json pointing to your container (your own server and the information provided by the container when running it)

**Comment by SUD-D365** [comment]
Hi @NavTechAnas ,
Seems this is related to BC online sandbox, you should post this in **https://github.com/Microsoft/AL/issues** forum.

For quick solution , you can check your AL extension version, and do modify your App.json file accordingly. It seems your App.json file does not matching with AL extension version.

Thanks
