### ISSUE TITLE
Unable to load symbols, login to dev server repeats without anything happens

### ISSUE THREAD

**Issue by BaltzerLogicpartner** [Microsoft/nav-docker#348]
Hi,
using a docker container with -auth NavUserPassword
In VS Code i get promted for login when running AL:Download Symbols, and when i use my UserPassword it repeats asking.
I can start the webclient with same NavUserPassword without any problems.

I've added D365 EXTENSION MGT to the navuser permissionset
I run Windows 10 1809 on my machine.
The image I've created the docker container from is bcsandbox:dk

Platform and application is 14.0.0.0
Get-NavContainerNavVersion -containerOrImageName bcsandboxDK
14.0.29537.31313-DK
I've created the al extiontion from the vrix file suggested by docker while creating the container.
http://bcsandboxDK:8080/al-3.0.106655.vsix

What did i miss?

**Comment by freddydk** [comment]
did you check that you have http or https right?

**Comment by BaltzerLogicpartner** [comment]
I'm using http.
I'm also using Kaspersky, it was paused during creating New-Container..
I retried the hole proces this morning and it worked fine, without Kaspersky.
Sorry for wasting your time.

**Comment by freddydk** [comment]
No problem, thanks for letting us know,
