### ISSUE TITLE
Metadata enhancement - link image with GitHub repo version

### ISSUE THREAD

**Issue by Koubek** [Microsoft/nav-docker#35]
I use "created" meta data and I really like it. I was thinking if you could change the build process to include also an attribute reflecting the relation between the GitHub repository state (perhaps Commit Number ???) and the image version.

I suppose we could identify better the version we are running currently.

**Comment by freddydk** [comment]
Good idea
We will try to find an automated way of doing this when we lift the build into our build system.

**Comment by Koubek** [comment]
I hope this could minimize questions like: "Has been included this fix or feature in the version I am currently running on?"

**Comment by freddydk** [comment]
Maybe add a URL to a TAG like
https://github.com/Microsoft/nav-docker/tree/0.0.1.0

**Comment by Koubek** [comment]
Yes, this is far better than using the commit number. Of course, you need to start tagging. But I suppose this shouldn\`t be a problem.

**Comment by Koubek** [comment]
Confirmed. The tag labels appear in currently pulled images. For example:

```
docker inspect --format "{{ index .Config.Labels }}" navdocker.azurecr.io/dynamics-nav:devpreview-finus
```

```
tag:0.0.2.0 version:11.0.18246.0 country:finus created:201708312013 cu:september legal:http://go.microsoft.com/fwlink/?LinkId=837447 maintainer:Freddy Kristiansen nav:devpreview
```
