### ISSUE TITLE
cannot personalize page in the tenant created from image 14.0.29537.31313-us

### ISSUE THREAD

**Issue by jeffgit** [microsoft/nav-docker#350]
Hello,

There is an issue to personalize any page in the tenant created from image: 
mcr.microsoft.com/businesscentral/sandbox:14.0.29537.31313-us

Please see below error. Can this be fixed as soon as possible?
![image](https://user-images.githubusercontent.com/2955741/56381877-e97bbf00-61ca-11e9-9754-330fc73a8e90.png)

**Comment by freddydk** [comment]
Just tried the exact same image - works just fine.
You probably need to share some more information about how you created this container and the output from running the container.

I did it like this:
```
$containerName = "temp"
$imageName = "mcr.microsoft.com/businesscentral/sandbox:14.0.29537.31313-us"
$auth = "NavUserPassword"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
New-NavContainer -accept_eula -containerName $containerName -imageName $imageName -updateHosts -auth $auth -Credential $credential
```

**Comment by jeffgit** [comment]
Hi Freddy,

I pulled the image and used the following powershell to create the container and default tenant.

docker pull mcr.microsoft.com/businesscentral/sandbox:14.0.29537.31313-us

once the image pull was completed, I ran the following:
$publicdnsName = 'mybcsandbox01.southcentralus.cloudapp.azure.com'
$additionalParameters = @("--publish  8080:8080",
                          "--publish  443:443", 
                          "--publish  7046-7049:7046-7049", 
                          "--env publicFileSharePort=8080",
                          "--env PublicDnsName=$publicdnsName",
                          "--env RemovePasswordKeyFile=N",
                          "--storage-opt size=100GB",
			  "-v c:\temp:c:\temp"
			)
New-NavContainer -containerName "navserver" `
-imageName "microsoft/bcsandbox:14.0.29537.31313-us" `
-accept_eula `
-additionalParameters $additionalParameters `
-multitenant `
-useSSL `
-includeCSide `
-updateHosts `
-enableSymbolLoading `
-includeTestToolkit `
-assignPremiumPlan `
-auth NavUserPassword ` 
-licenseFile "c:\temp\nav2018.flf"


Let me know if you can reproduce or need any other info.

Thanks!

**Comment by jeffgit** [comment]
New finding on this. I noticed that if I exclude -enableSymbolLoading, it works just fine. As soon as I have -enableSymbolLoading in the command New-NavContainer, the tenant created will have the personalization issue.

**Comment by freddydk** [comment]
I found the same - it is a bug in the platform, which should be fixed in CU1 hopefully.

**Comment by jeffgit** [comment]
Thank you Freddy.
