### ISSUE TITLE
Certificate issue?

### ISSUE THREAD

**Issue by SUD-D365** [Microsoft/nav-docker#351]
Hi @freddydk , came back to you again for seeking help on below issue.

I am trying to download BC latest image (Spring release) through docker. But getting below error.

DockerDo : x509: certificate signed by unknown authority
ExitCode: 1
Commandline: docker pull  microsoft/bcsandbox:w1
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.0.9\ContainerHandling\New-NavContainer.ps1:302 char:13
+             DockerDo -command pull -imageName $imageName | Out-Null
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

I do not have any idea, that how to resolve this issue.

Below is the script i am running.
install-module navcontainerhelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true

$containername = 'ConCalma'
$navdockerimage = 'microsoft/bcsandbox:w1'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -memoryLimit 3G `
                 -containername $containername `
                 -auth NavUserPassword `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
				 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password

Kindest regards

**Comment by freddydk** [comment]
Seems like you for some reason cannot download from the docker hub (I just tried your script and it works fine here).

Try to use

mcr.microsoft.com/businesscentral/sandbox:w1

as docker image instead - it is the same image.

**Comment by SUD-D365** [comment]
Hi @freddydk , Thanks for your prompt revert.
I just tried download images from **mcr.microsoft.com/businesscentral/sandbox:w1** , but did not succeeded.

Now getting below error.
S C:\WINDOWS\system32> 
install-module navcontainerhelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true

$containername = 'ConCalma'
$navdockerimage = 'mcr.microsoft.com/businesscentral/sandbox:w1'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -memoryLimit 3G `
                 -containername $containername `
                 -auth NavUserPassword `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
				 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password

NavContainerHelper is version 0.6.0.9
Host is Microsoft Windows 10 Pro - 1703
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Pulling image mcr.microsoft.com/businesscentral/sandbox:w1-ltsc2016
w1-ltsc2016: Pulling from businesscentral/sandbox
Pulling image mcr.microsoft.com/businesscentral/sandbox:w1
w1: Pulling from businesscentral/sandbox
DockerDo : error pulling image configuration: Get https://mcrea0.cdn.mscr.io/b29889755b1f4e46b6b44eb3182530c5-0joxcrfl25//docker/registry/v2/blobs/sha256/a6/a64335870bc83aacee589c1b
d0f62f51ffe3b904284aabb842a9c4b6f325ca00/data?P1=1555660771&P2=1&P3=1&P4=UXKJTM2AMMQNCk1hlZYpiht%2B7ydaZTkqxft%2FcBOfGIs%3D&se=2019-04-19T07%3A59%3A31Z&sig=Pi0S%2FpBB5WBd5LvGdqE5%2B
C6mDkfKp5bHITl%2BGpuk%2FkA%3D&sp=r&sr=b&sv=2016-05-31&regid=b29889755b1f4e46b6b44eb3182530c5: x509: certificate signed by unknown authority
ExitCode: 1
Commandline: docker pull  mcr.microsoft.com/businesscentral/sandbox:w1
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.0.9\ContainerHandling\New-NavContainer.ps1:302 char:13
+             DockerDo -command pull -imageName $imageName | Out-Null
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by freddydk** [comment]
I think the error is on your machine.
try
docker pull microsoft/bcsandbox:w1
and I guess you will get the same error.
Maybe a virus scanner problem?

**Comment by SUD-D365** [comment]
Yes may be.
Because on my system an antivirus is installed and managed by organization.

**Comment by freddydk** [comment]
Powershell is using docker pull internally - no difference.
And most antivirus software works just fine with this - but I have heard some having issues with Kaspersky (hence the reason for suggesting antivirus).

Strange that some images are downloading - business central containers?

Not much I can do about this - the images you try are downloaded 100's of times every day by other partners.

**Comment by SUD-D365** [comment]
Hi @freddydk 
I just checked event log on my local system. What i found is, that docker is trying to download images from a URL, and that URL i tried to run in browser , and the browser did not allowed me to access that URL.
And this is probably due to the anti virus.
![image](https://user-images.githubusercontent.com/33481576/56415427-58304980-62ab-11e9-8d2a-23db1618dfdb.png)
![image](https://user-images.githubusercontent.com/33481576/56415462-67af9280-62ab-11e9-8dec-25d57a15d6e2.png)

**Comment by SUD-D365** [comment]
Hi @freddydk 
After allowing this URL, its working like charm.

Thanks

**Comment by SUD-D365** [comment]
Hi @freddydk 
Reopened this issue, due to related problem.
Somehow, i have managed to download the images of BC after unblocking the URL's from Antivirus.
All things happened as expected, but this last error is causing issue.
I think this is the one, as i cant access the Web client from this container.
![image](https://user-images.githubusercontent.com/33481576/56576127-3275ae00-65e5-11e9-8d8d-356c23599b33.png)

Below is the error while accessing the web client from created shortcut.
![image](https://user-images.githubusercontent.com/33481576/56576180-4f11e600-65e5-11e9-9b17-08b7209031a7.png)

Kindly help.

**Comment by NAVspecialist** [comment]
Freddy has ealier mentioned that the image(s) you try to pull have works for 100s of others, and the problem relates on your machine solely, so it is only possible to give you a few advices.

Run your powershell script ad administrator.  If you cannot do that or you get the same error - then use Azure to run your docker images.

If you do not have access to Azure or don't want to go down that road, then you have to get some help from your IT department about your Antivirus software. 

If that is not possible, then you have to download your Images (DVD) and run your installations in Hyper-V 

Unfortunately there is not magic (and thank-you-for-that) loopholes around the antivirus system - unless the the antivirus company takes docker seriously.

Best of luck.

**Comment by freddydk** [comment]
Yeah, it seems like your machine is shutting down a number of things and it is hard for us to tell you what you need to change. The script you are running works - the problem is on your machine and not somehting we have seen before.

**Comment by SUD-D365** [comment]
Ok Thanks guys.
Now i am pretty sure, that this issue is due to Antivirus.

**Comment by NAVspecialist** [comment]
Sorry.. I am writing again... You could try to run MSCONFIG from a command prompt as admin and the remove the antivirus program from the boot sequence to see if that is the problem...
