### ISSUE TITLE
Missing Image for Cumulative Update 06 for Microsoft Dynamics 365 Business Central on-premises

### ISSUE THREAD

**Issue by FrankNeeckx** [microsoft/nav-docker#353]
hi,
Just searched on :

You can retrieve a list of all available tags for businesscentral/sandbox at https://mcr.microsoft.com/v2/businesscentral/sandbox/tags/list

But didn't find any tags related to this CU.

thx for an answer

**Comment by freddydk** [comment]
sandbox containers have updates
onprem containers have cu's

**Comment by freddydk** [comment]
docker pull mcr.microsoft.com/businesscentral/onprem:1810-cu6-w1-ltsc2019

**Comment by FrankNeeckx** [comment]
Great, thx Freddy.

Met vriendelijke groeten,

Sincères salutations,

With kind regards,


Frank



________________________________

Frank Neeckx | project team

t: +32 9 296 31 14

[astena logo - website]<https://www.astena.be/nl/erp-software/>




[8 inspiratiesessies voor het bouwbedrijf van de toekomst]<https://www.astena.be/nl/event/12-unieke-inzichten-voor-het-bouwbedrijf-van-de-toekomst/?utm_source=Mail&utm_medium=Signature&utm_campaign=8sessies>



Van: Freddy Kristiansen <notifications@github.com>
Verzonden: donderdag 25 april 2019 13:48
Aan: Microsoft/nav-docker <nav-docker@noreply.github.com>
CC: Frank Neeckx <fn@astena.be>; Author <author@noreply.github.com>
Onderwerp: Re: [Microsoft/nav-docker] Missing Image for Cumulative Update 06 for Microsoft Dynamics 365 Business Central on-premises (#353)


docker pull mcr.microsoft.com/businesscentral/onprem:1810-cu6-w1-ltsc2019

**Comment by PleachiM** [comment]
Can we have any hint how to determine which version is what? As example 1810, 13.3.27908.29339, 14.0.29537.31923.

**Comment by freddydk** [comment]
docker inspect of an image or a container will give you a labels section with all the info about what's inside.
Spring release looks like:
```
            "Labels": {
                "country": "W1",
                "created": "201904241403",
                "cu": "",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Dynamics SMB",
                "nav": "",
                "osversion": "10.0.17763.437",
                "platform": "14.0.29530.0",
                "tag": "0.0.9.5",
                "version": "14.0.29537.0"
            }
```

**Comment by freddydk** [comment]
You can get the same without downloading the image with navcontainerhelper
Get-NavContainerImageLabels mcr.microsoft.com/businesscentral/onprem:1810-cu6-w1-ltsc2019

**Comment by PleachiM** [comment]
Thank you that helps me a lot!
