### ISSUE TITLE
Serve dynamics-nav images from MCR instead of Docker Hub

### ISSUE THREAD

**Issue by iMicknl** [microsoft/nav-docker#356]
_However, newer Microsoft images and tags are available directly from the Microsoft Container Registry (MCR) at mcr.microsoft.com. Search and discoverability of the images are available through Docker Hub, however docker pull, run and build statements should reference mcr.microsoft.com. For example, pulling the windows-servercore image:
docker pull mcr.microsoft.com/windows/servercore_
[source](https://azure.microsoft.com/en-us/blog/microsoft-container-registry-unaffected-by-the-recent-docker-hub-data-exposure/)

The [README for `microsoft/dynamics-nav`](https://hub.docker.com/r/microsoft/dynamics-nav/) still references the Docker Hub instead of MCR by using `docker pull microsoft/dynamics-nav:2017`.

**Comment by freddydk** [comment]
I will update the readme.
NAV images are available on mcr.microsoft.com/dynamicsnav:<tag>

**Comment by iMicknl** [comment]
Thanks for your quick response, @freddydk.
