### ISSUE TITLE
Problem when creating a local user in a NAV Container

### ISSUE THREAD

**Issue by ThierryPermentier** [microsoft/nav-docker#358]
Hi all,

When we create a NAV Container using New-NavContainer, we specify a username and password. This user is created as local user in the container as well as Nav user with the appropriate rights. So far so good. But if we want to add the same user, with the same password to a container (where the user does not exist), we receive an error saying "Unable to update the password. The value provided for the new password does not meet the length, complexity, or history requirements of the domain." when we use the command New-LocalUser in the container. This problem is for some users, not for all.

Any suggestions on how to fix this? Thx!

**Comment by NAVspecialist** [comment]
The answer is as the system says.. Your password is not good enough.

**Comment by freddydk** [comment]
Yes, in the latest generic image (meaning all future containers), the local user is only created when running Windows auth - but for now - you need to create a better password - example: P@ssword1
