### ISSUE TITLE
Increase SOAP Max Message Size in Docker BC W1 image

### ISSUE THREAD

**Issue by Rachit14** [microsoft/nav-docker#359]
Hi,

We are working on the development of an integrator which integrates NAV/BC with a third party Retail Software. This integration is done by using SOAP services and exchanging and parsing the XML files. Everything works fine when incoming XML size is small but we are facing issue when XML file is large. Our Event viewer logs throws the message **"XML file is too large."**
Earlier in onpremises version we could increase the SOAP Max Size. So I just want to know if same can be done on BC Docker Sandbox by using any powershell commands?

**Comment by freddydk** [comment]
You can modify customsettings.config in the container. If you use navcontainerhelper you will have shortcuts on the desktop to open a powershell prompt in the container and you can use Set-NAVServerConfiguration to modify the config.

If you are not using NavContainerHelper, you can use
docker exec -it temp powershell
and then use
\run\prompt.ps1
to load all Nav/BC cmdlets.

you can also specify settings when starting the container - either by setting the environment variable CustomNavSettings to the container or by overriding the AdditionalSetup.ps1 file with a Set-NavServerConfiguration line.

**Comment by Rachit14** [comment]
Thanks @freddydk . I will definitely give it a try and let you know.
