### ISSUE TITLE
Download symbols Docker container created with .bak

### ISSUE THREAD

**Issue by HenryVerheij** [microsoft/nav-docker#360]
I tried to create a docker container using a .bak file.
The .bak contains also an addon created in C/AL.

This is what I used to create the container:
$credential = New-Object pscredential 'HV', (ConvertTo-SecureString -String '<password>' -AsPlainText -Force)
$containerName = "AgriBC365"
$imageName = "mcr.microsoft.com/businesscentral/onprem:cu4-nl"
$attachedAddInscript = "c:\overridescripts\SetupAddins.ps1"
New-NavContainer -accept_eula `
                 -imageName $imageName `
                 -containerName $containerName `
                 -enableSymbolLoading `
                 -auth "NavUserPassword" `
                 -Credential $credential `
                 -updateHosts `
                 -includeCSide `
                 -licensefile "C:\Licenties\D365BC - Henry.flf" `
                 -memoryLimit 4G `
                 -useBestContainerOS `
                 -additionalParameters @('--volume "C:\agridb\agriaddins:c:\run\agriaddins"', '--volume "c:\agridb:c:\agridb"', '--env bakfile="c:\agridb\BC365_W1_HV.bak"') `
                 -myScripts @($attachedAddInscript)

When I want to download symbols I am getting the following error:

[2019-05-06 15:01:26.74] The request for path /NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.

My launc.json file contains the following:
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://AGRIBC365",
            "serverInstance": "NAV",
            "authentication": "UserPassword"   ,
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true
        }
    ]
}

The app.json file is as follows:
{
  "id": "8da273e8-f0d4-4fd3-b351-940522feaa33",
  "name": "dockertestje",
  "publisher": "Default publisher",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "13.0.0.0",
  "application": "13.0.0.0",
  "idRange": {
    "from": 50100,
    "to": 50149
  },
  "runtime": "2.1",
  "target": "Internal"
}

Is it possible to use a .bak file with c/al changes?
If so what am I doing wrong that causes this failure.

**Comment by freddydk** [comment]
Could you try to run this without -enableSymbolLoading?

**Comment by HenryVerheij** [comment]
I tried, but it had the same result.

**Comment by HenryVerheij** [comment]
Possibly the missing step is compiling the objects. 
I'll try that tomorrow.

**Comment by freddydk** [comment]
Just tried this script

```
$containerName = "temp"
$imageName = "mcr.microsoft.com/businesscentral/onprem:w1-ltsc2019"
$auth = "NavUserPassword"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$licenseFile = "C:\temp\license.flf"

New-NavContainer -accept_eula -imageName $imageName -containerName $containerName -auth NavUserPassword -Credential $credential -licenseFile $licenseFile -includeCSide -enableSymbolLoading -updateHosts

$solution = "C:\ProgramData\NavContainerHelper\DemoSolution2.txt"
Import-ObjectsToNavContainer -containerName $containerName -objectsFile $solution -SynchronizeSchemaChanges Force
Compile-ObjectsInNavContainer -containerName $containerName -filter "modified=1"

$bakfile = "c:\programdata\navcontainerhelper\database.bak"
Remove-Item $bakfile -Force
Backup-NavContainerDatabases -containerName $containerName -sqlCredential $credential -bakFolder "c:\programdata\navcontainerhelper"

New-NavContainer -accept_eula -imageName $imageName -containerName $containerName -auth NavUserPassword -Credential $credential -includeCSide -licenseFile $licenseFile -enableSymbolLoading -updateHosts -additionalParameters @( "--env bakFile=$bakfile" )
```

Works fine.
If I don't add -enablesymbolloading, then My app symbols will not be availble.

**Comment by HenryVerheij** [comment]
Hi Freddy,
Thanks a lot for your effort so far.
I tested it myself with creating some customizations in C/AL and used the bak of that database and that also worked fine. So the problem must be something in the database that I have used.
I'll close the issue.
Regards, Henry
