### ISSUE TITLE
New Nav Container Installation Issue for Business Central Image

### ISSUE THREAD

**Issue by tjaitly1986** [microsoft/nav-docker#361]
Hi Freddy,

Apologies for the late response but this issue is still not resolved, so I have created a new issue.

Event Viewer Error Log while installing the Docker Container-

"exec's CreateProcess() failed [namespace=moby container=3f3aad281191392dd1d68df0718141269f470919d3b75d1781ee02187f7169b9 exec=0b7f36da25be98317f3bf85c303e50a176e7eb1d424cedce63038a559a8a14eb error=container 3f3aad281191392dd1d68df0718141269f470919d3b75d1781ee02187f7169b9 encountered an error during CreateProcess: failure in a Windows system call: A virtual machine or container with the specified identifier does not exist. (0xc037010e) extra info: {"CommandLine":"powershell .\\Run\\HealthCheck.ps1","WorkingDirectory":"/","Environment":{"CountryCode":"W1","DEVPREVIEWURL":"https://nav2016wswe0.blob.core.windows.net/dvd/c5dad940-0e99-4a88-818a-5d88bdcdd454","DatabaseName":"FinancialsW1","ExitOnError":"N","IsBcSandbox":"Y","NAVDVDURL":"https://nav2016wswe0.blob.core.windows.net/dvd/9943db87-021e-4f8e-8f0b-b4c74de27a91","VSIXURL":"https://nav2016wswe0.blob.core.windows.net/dvd/al-3.0.106655.vsix","accept_eula":"Y","auth":"NavUserPassword","databaseInstance":"","databaseServer":"","enableApiServices":"Y","enableSymbolLoading":"Y","licenseFile":"","locale":"en-US","passwordKeyFile":"c:\\run\\my\\aes.key","removePasswordKeyFile":"Y","securePassword":"76492d1116743f0423413b16050a5345MgB8AEsAdABOAHEANwBwAC8AcwA2AG8ASQBGAG0ATABHAGwAUABWAHoAawA2AHcAPQA9AHwAYgA1AGYAYgAzADYANwA2AGUAZAAzAGEAOABmAGMANAAxADEAMwA0AGMAYgBjAGQANAA1ADcANgAwAGUAOQA5ADgAOABmADAANQBmAGIANgBjAGIANwA0AGYAZQBjADUAZgBkADIAZAA1AGYAYwBjADcANwA4ADkAMQBjADkAMgA=","useSSL":"N","username":"tushar@jaitly.in"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]} module=libcontainerd]"

Command that I am executing-

"$MyImageName = "mcr.microsoft.com/businesscentral/sandbox:latest-ltsc2019"
$MyContainer = "bc356N"

if ($credential -eq $null -or $credential -eq
[System.Management.Automation.PSCredential]::Empty) {
$credential= get-credential -UserName $env:USERNAME
-Message "Please Enter your Windows Credential."
}
New-NavContainer -accept_eula
    -containerName $MyContainer
    -imageName $MyImageName
    -credential $credential
    -auth Windows
    -includeCside
    -doNotEcportObjectsToText
"

Also tried with this command - 

"New-NavContainer -containerName bc365n -accept_eula -assignPremiumPlan -auth NavUserPassword -doNotExportObjectsToText -enableSymbolLoading -imageName mcr.microsoft.com/businesscentral/sandbox -isolation hyperv -memoryLimit 4G -updateHosts -useBestContainerOS"

Thanks
TJ

**Comment by freddydk** [comment]
Are you referring to another issue when you say "this issue is still not resolved"???
What issue is that?

**Comment by tjaitly1986** [comment]
![image](https://user-images.githubusercontent.com/26621684/57566151-933a1e80-740c-11e9-8d47-374bd18284f0.png)

**Comment by freddydk** [comment]
Ok - cannot see the issue number (better to post a link to the issue) - but I think I remember.
It looks like you are specifying an email address as username - that will not work.
Please try to use NavUserPassword authentication and a simple username/password:

Set $imagename and $containername and run this:
```
$auth = "NavUserPassword"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$licenseFile = "C:\temp\license.flf"
New-NavContainer -accept_eula `
                 -containerName $containerName `
                 -imageName $imageName `
                 -updateHosts `
                 -auth $auth `
                 -Credential $credential
```

**Comment by tjaitly1986** [comment]
https://github.com/Microsoft/nav-docker/issues/4

Thanks, will try and let you know in few minutes.

**Comment by tjaitly1986** [comment]
Hi Freddy,

Still the same error - 

"
$auth = "NavUserPassword"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$licenseFile = "C:\temp\license.flf"
New-NavContainer -accept_eula `
                 -containerName $MyContainer `
                 -imageName $MyImageName `
                 -updateHosts `
                 -auth $auth `
                 -Credential $credential
ExitOnError=N


NavContainerHelper is version 0.6.0.9
Host is Microsoft Windows 10 Enterprise - ltsc2019
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Using image microsoft/bcsandbox:latest-ltsc2019
Removing container bc356N
Removing bc356N from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\bc356N
Creating Nav container bc356N
Version: 14.0.29537.31430-W1
Platform: 14.0.29530.31296
Generic Tag: 0.0.9.3
Container OS Version: 10.0.17763.379 (ltsc2019)
Host OS Version: 10.0.17763.437 (ltsc2019)
Using process isolation
Creating container bc356N from image microsoft/bcsandbox:latest-ltsc2019
d2d9f7487527a0f8a8d2b36e5dd92db7ea73c7a3608df5d160a306eaa150deb3
Waiting for container bc356N to be ready
Initializing...
Starting Container
Hostname is bc356N
PublicDnsName is bc356N
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint C1BF1DB44F0536E458910DA464B1249724E92EF9
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user admin
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is bc356N
PublicDnsName is bc356N
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint C1BF1DB44F0536E458910DA464B1249724E92EF9
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user admin
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container bc356N failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.0.9\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...r bc356N failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container bc356N failed"


Event Vwr Logs - 

"
exec's CreateProcess() failed [namespace=moby module=libcontainerd container=3f3aad281191392dd1d68df0718141269f470919d3b75d1781ee02187f7169b9 exec=2dfbe1d47e803e51e054b2eed8cac9db88d6ee8aa7aa03c1b6eb4343d0335c09 error=container 3f3aad281191392dd1d68df0718141269f470919d3b75d1781ee02187f7169b9 encountered an error during CreateProcess: failure in a Windows system call: A virtual machine or container with the specified identifier does not exist. (0xc037010e) extra info: {"CommandLine":"powershell .\\Run\\HealthCheck.ps1","WorkingDirectory":"/","Environment":{"CountryCode":"W1","DEVPREVIEWURL":"https://nav2016wswe0.blob.core.windows.net/dvd/c5dad940-0e99-4a88-818a-5d88bdcdd454","DatabaseName":"FinancialsW1","ExitOnError":"N","IsBcSandbox":"Y","NAVDVDURL":"https://nav2016wswe0.blob.core.windows.net/dvd/9943db87-021e-4f8e-8f0b-b4c74de27a91","VSIXURL":"https://nav2016wswe0.blob.core.windows.net/dvd/al-3.0.106655.vsix","accept_eula":"Y","auth":"NavUserPassword","databaseInstance":"","databaseServer":"","enableApiServices":"Y","enableSymbolLoading":"Y","licenseFile":"","locale":"en-US","passwordKeyFile":"c:\\run\\my\\aes.key","removePasswordKeyFile":"Y","securePassword":"76492d1116743f0423413b16050a5345MgB8AEsAdABOAHEANwBwAC8AcwA2AG8ASQBGAG0ATABHAGwAUABWAHoAawA2AHcAPQA9AHwAYgA1AGYAYgAzADYANwA2AGUAZAAzAGEAOABmAGMANAAxADEAMwA0AGMAYgBjAGQANAA1ADcANgAwAGUAOQA5ADgAOABmADAANQBmAGIANgBjAGIANwA0AGYAZQBjADUAZgBkADIAZAA1AGYAYwBjADcANwA4ADkAMQBjADkAMgA=","useSSL":"N","username":"tushar@jaitly.in"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}]
"

**Comment by freddydk** [comment]
Could you try to add 

-isolation hyperv

to the command?

**Comment by tjaitly1986** [comment]
Still the same..

Is there any prerequisite for installing this because every time its failing at below line

"ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1"

**Comment by freddydk** [comment]
You are not installing anything - you are running a container and if Docker is installed correctly then it should just work.
The location where it fails is just the first place, where it needs the service tier and the service tier isn't running.
What I can see above is that your OS is Version: 10.0.17763.437 and the container is Version 10.0.17763.379. I just had another partner with exactly the same and when he shifted to hyperv isolation it worked for him.
I will create a fix for the containerhelper to default to hyperv isolation if the release # is different, but you can do this yourself with -isolation hyperv.
If you could include the full output of the new-navcontainer with -isolation hyperv - then I can see whether it is the same error.

**Comment by tjaitly1986** [comment]
Output - 

"$MyImageName = "microsoft/bcsandbox:latest-ltsc2019"
$MyContainer = "bc356N"

$auth = "NavUserPassword"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$licenseFile = "C:\temp\license.flf"
New-NavContainer -accept_eula `
                 -containerName $MyContainer `
                 -imageName $MyImageName `
                 -updateHosts `
                 -auth $auth `
                 -Credential $credential
                 -isolation hyperv
                 -ExitOnError=N


NavContainerHelper is version 0.6.0.9
Host is Microsoft Windows 10 Enterprise - ltsc2019
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Using image microsoft/bcsandbox:latest-ltsc2019
Removing container bc356N
Removing bc356N from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\bc356N
Creating Nav container bc356N
Version: 14.0.29537.31430-W1
Platform: 14.0.29530.31296
Generic Tag: 0.0.9.3
Container OS Version: 10.0.17763.379 (ltsc2019)
Host OS Version: 10.0.17763.437 (ltsc2019)
Using process isolation
Creating container bc356N from image microsoft/bcsandbox:latest-ltsc2019
458fd88782f12bcd41cf365ddd2154f6a84de03726b54a8e25b6c32f49e994b4
Waiting for container bc356N to be ready
Initializing...
Starting Container
Hostname is bc356N
PublicDnsName is bc356N
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 6D12DC0C76CE4F5500DBE3D1A0C018E043033E1E
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user admin
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is bc356N
PublicDnsName is bc356N
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 6D12DC0C76CE4F5500DBE3D1A0C018E043033E1E
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user admin
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container bc356N failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.0.9\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...r bc356N failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container bc356N failed
 
"

**Comment by freddydk** [comment]
Your -isolation hyperv line is not part of the command.
In order for the parameter to be included, you need to have a ` character after the line before - or you need to add it to the line before...
Your output also still says using process isolation

**Comment by tjaitly1986** [comment]
Same error but this time it took long time to process -

"$MyImageName = "microsoft/bcsandbox:latest-ltsc2019"
$MyContainer = "bc356N"

$auth = "NavUserPassword"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$licenseFile = "C:\temp\license.flf"
New-NavContainer -accept_eula `
                 -containerName $MyContainer `
                 -imageName $MyImageName `
                 -updateHosts `
                 -auth $auth `
                 -Credential $credential `
                 -isolation hyperv
                 -ExitOnError=N 


NavContainerHelper is version 0.6.0.9
Host is Microsoft Windows 10 Enterprise - ltsc2019
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Using image microsoft/bcsandbox:latest-ltsc2019
Removing container bc356N
Removing bc356N from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\bc356N
Creating Nav container bc356N
Version: 14.0.29537.31430-W1
Platform: 14.0.29530.31296
Generic Tag: 0.0.9.3
Container OS Version: 10.0.17763.379 (ltsc2019)
Host OS Version: 10.0.17763.437 (ltsc2019)
Using hyperv isolation
Creating container bc356N from image microsoft/bcsandbox:latest-ltsc2019
f31d7a994267837c11d41b9d819db3ad8896c286c449bc044ad5da43871877b9
Waiting for container bc356N to be ready
Initializing...
Starting Container
Hostname is bc356N
PublicDnsName is bc356N
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint B01D42D48267F96446610AD03BB5DD3D42D6CFD7
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user admin
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is bc356N
PublicDnsName is bc356N
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint B01D42D48267F96446610AD03BB5DD3D42D6CFD7
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user admin
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container bc356N failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.0.9\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...r bc356N failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container bc356N failed
 "

**Comment by freddydk** [comment]
I tried to run the exact same command - works perfectly here.
I also tried to install the same navcontainerhelper - works fine.
Only difference now is that the container you are using is generic 0.0.9.3 - mine is 0.0.9.6 - meaning that there is a newer image available.
Try to add -alwaysPull to new-navcontainer to pull a new image.
if this still fails, then please run 

Get-NavContainerEventLog <containername> to download the event log from the container - and attach that here in the thread or email it to freddyk at microsoft dot com.

**Comment by tjaitly1986** [comment]
Same error - Log attached.

Get-NavContainerEventLog also attached after the statements log

"
PS C:\> $MyImageName = "microsoft/bcsandbox:latest-ltsc2019"
$MyContainer = "bc356N"

$auth = "NavUserPassword"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$licenseFile = "C:\temp\license.flf"
New-NavContainer -accept_eula `
                 -alwaysPull `
                 -containerName $MyContainer `
                 -imageName $MyImageName `
                 -updateHosts `
                 -auth $auth `
                 -Credential $credential `
                 -isolation hyperv
                 -ExitOnError=N 


NavContainerHelper is version 0.6.0.9
Host is Microsoft Windows 10 Enterprise - ltsc2019
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Pulling image microsoft/bcsandbox:latest-ltsc2019
latest-ltsc2019: Pulling from microsoft/bcsandbox
65014b3c3121: Already exists
0e787b79aad1: Already exists
b6a0c53242a1: Already exists
cbc7474b9120: Already exists
ab835c4f541a: Already exists
09e247aae908: Already exists
bae3a2566ccb: Already exists
2fe8b5aa0f66: Already exists
c583c23a6bbc: Already exists
9839d99910ff: Already exists
5d8fcc592654: Already exists
f4f20505128c: Already exists
c8b67bf40389: Already exists
a2be6d8158c1: Already exists
1924266dc1e7: Already exists
703633fbae27: Already exists
1c2315915827: Already exists
b9b918ef1392: Already exists
da870e4bcd1d: Already exists
94b07d2bbc22: Already exists
2a1a6707c9b9: Pulling fs layer
92ddaa9c3e08: Pulling fs layer
4b3c0d6aa2c5: Pulling fs layer
2f732261496f: Pulling fs layer
5a22c5c794d9: Pulling fs layer
e10b59c9f26e: Pulling fs layer
5543250b8216: Pulling fs layer
c930f7ba46d2: Pulling fs layer
ebb0cf22d7f7: Pulling fs layer
932353c7cc61: Pulling fs layer
ee7f870902a6: Pulling fs layer
e10b59c9f26e: Waiting
5543250b8216: Waiting
c930f7ba46d2: Waiting
ebb0cf22d7f7: Waiting
932353c7cc61: Waiting
ee7f870902a6: Waiting
2f732261496f: Waiting
5a22c5c794d9: Waiting
2a1a6707c9b9: Verifying Checksum
2a1a6707c9b9: Download complete
92ddaa9c3e08: Download complete
2f732261496f: Verifying Checksum
2f732261496f: Download complete
5a22c5c794d9: Download complete
2a1a6707c9b9: Pull complete
5543250b8216: Verifying Checksum
5543250b8216: Download complete
92ddaa9c3e08: Pull complete
e10b59c9f26e: Verifying Checksum
e10b59c9f26e: Download complete
c930f7ba46d2: Verifying Checksum
c930f7ba46d2: Download complete
ebb0cf22d7f7: Verifying Checksum
ebb0cf22d7f7: Download complete
ee7f870902a6: Verifying Checksum
ee7f870902a6: Download complete
932353c7cc61: Verifying Checksum
932353c7cc61: Download complete
4b3c0d6aa2c5: Verifying Checksum
4b3c0d6aa2c5: Download complete
4b3c0d6aa2c5: Pull complete
2f732261496f: Pull complete
5a22c5c794d9: Pull complete
e10b59c9f26e: Pull complete
5543250b8216: Pull complete
c930f7ba46d2: Pull complete
ebb0cf22d7f7: Pull complete
932353c7cc61: Pull complete
ee7f870902a6: Pull complete
Digest: sha256:8ced881277c50214dd1ea659098e582f9e0a04c1e2ae9d43e7efb7532bd3f6bd
Status: Downloaded newer image for microsoft/bcsandbox:latest-ltsc2019
Using image microsoft/bcsandbox:latest-ltsc2019
Removing container bc356N
Removing bc356N from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\bc356N
Creating Nav container bc356N
Version: 14.0.29537.31808-W1
Platform: 14.0.29530.31705
Generic Tag: 0.0.9.6
Container OS Version: 10.0.17763.437 (ltsc2019)
Host OS Version: 10.0.17763.437 (ltsc2019)
Using hyperv isolation
Creating container bc356N from image microsoft/bcsandbox:latest-ltsc2019
5917fb0b3df8260dc4a446542aed54a6fbff0d177f87c5e175fe6c3f08ade2f1
Waiting for container bc356N to be ready
Initializing...
Starting Container
Hostname is bc356N
PublicDnsName is bc356N
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 5B2293A5B10AE3859D23FB0830B172FAC1AA94C2
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is bc356N
PublicDnsName is bc356N
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 5B2293A5B10AE3859D23FB0830B172FAC1AA94C2
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container bc356N failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.0.9\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...r bc356N failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container bc356N failed
 "


**Get-NavContainerEventLog result -** 

"PS C:\> Get-NavContainerEventLog
cmdlet Get-NavContainerEventLog at command pipeline position 1
Supply values for the following parameters:
containerName: bc365N
Getting event log for bc365N
docker : Error: No such object: bc365N
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.0.9\ContainerInfo\Get-NavContainerSharedFolders.ps1:25 char:20
+         $inspect = docker inspect $containerName | ConvertFrom-Json
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: No such object: bc365N:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError"

**Comment by freddydk** [comment]
It looks like the container was removed before getting the event log.
Get-NavContainerEventLog should export the event log (.evtx file) to the host and open it.

**Comment by tjaitly1986** [comment]
Hi Freddy,

Please find attached the diagnostic logs from docker for your reference.
[diagnostics[1].log](https://github.com/microsoft/nav-docker/files/3193469/diagnostics.1.log)

**Comment by tjaitly1986** [comment]
I have re-installed the docker and now errors are different.
[log[1].txt](https://github.com/microsoft/nav-docker/files/3193470/log.1.txt)

**Comment by freddydk** [comment]
Not sure what this log file is? what we need is the output from new-navcontainer and the eventlog (as evtx) from inside the container (after it has been created)

**Comment by freddydk** [comment]
Did this problem ever get resolved?

**Comment by tjaitly1986** [comment]
nope

**Comment by freddydk** [comment]
If you want to pursue a solution, please retry and attach a event log from the container .evtx file to troubleshoot why the service tier doesn't start. You can do this by running this script:

```
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
New-NavContainer -accept_eula -containerName test -auth NavUserPassword -credential $credential -ErrorAction SilentlyContinue
Get-NavContainerEventLog -containerName test -doNotOpen
```

and then attach the .evtx file from C:\ProgramData\NavContainerHelper\Extensions\test\my

If you do not want to pursue a solution, please close the issue.

Thanks
