### ISSUE TITLE
Missing image for Business Central Version:14.0.29530.31800 

### ISSUE THREAD

**Issue by kemandengu** [microsoft/nav-docker#362]
Hi, 

I am unable to find this sandbox container version update 14.0.29530.31800. Any ideas?

**Comment by freddydk** [comment]
We do not build all versions as docker images - not sure from where you got that version number - nor what you need it for?

but, I can see that it is a platform version number.

`(Get-NavContainerImageTags -imageName mcr.microsoft.com/businesscentral/sandbox).Tags | Where-Object { $_.startswith("14.0") -and $_.endswith("-w1") }`

you get

14.0.29537.0-w1
14.0.29537.31061-w1
14.0.29537.31154-w1
14.0.29537.31259-w1
14.0.29537.31313-w1
14.0.29537.31430-w1
14.0.29537.31611-w1
14.0.29537.31728-w1
14.0.29537.31761-w1
14.0.29537.31808-w1
14.0.29537.31888-w1
14.0.29537.31923-w1
14.0.29537.32081-w1
14.0.29537.32224-w1
14.0.29537.32323-w1

which are all the 14.0 builds that exists publicly.

Then you can run

`Get-NavContainerImageLabels -imageName mcr.microsoft.com/businesscentral/sandbox:14.0.29537.31888-w1 `

and you get

```
country    : W1
created    : 201904301439
cu         : 
eula       : https://go.microsoft.com/fwlink/?linkid=861843
legal      : http://go.microsoft.com/fwlink/?LinkId=837447
maintainer : Dynamics SMB
nav        : 
osversion  : 10.0.14393.2906
platform   : 14.0.29530.31800
tag        : 0.0.9.6
version    : 14.0.29537.31888
```

There you have your platform version number.
Note, that there might be multiple versions, which are using the same platform.

**Comment by kemandengu** [comment]
Yes you are right I had the  platform version and I was after the version information. Thank you, this helps!
