### ISSUE TITLE
System.Net.WebException The operation has timed out.

### ISSUE THREAD

**Issue by tomasevicstefan** [microsoft/nav-docker#363]
After some time using BC in container, I'm always get into this issue, and I'm unable to start Web Client, Client, or open Finsql. Is there any common solution for this exception?

**Comment by freddydk** [comment]
I haven't seen this myself, so you might need to tell us a little more about how you create your container and whether you are running process or hyperv isolation.
Maybe the container is running out of memory?
Maybe there is something in the event log - navcontainerhelper has a function called get-navcontainereventlog, which can extract the event log from the container.

**Comment by tomasevicstefan** [comment]
Hi Freddy,
we are creating container with this command:
_New-NavContainer -accept_eula -accept_outdated  -imageName $imageName -containerName $DockerContainerName -Credential $DockerCredentials @params -alwaysPull -includeCSide -restart no -updateHosts_

@params are some additional parameters(env,dns,licence)
Docker Client and Server Version 18.09.3
NavContainerHelper version is _0.5.0.11_
DockerImage: _mcr.microsoft.com/businesscentral/onprem:13.5.29483.0-is-ltsc2019_
Using process isolation

I can't get now event log, bacause I've already remove and build environment again, so I can continue to work.

**Comment by freddydk** [comment]
Ok, if this happens again, please get the event log.
Your NavContainerHelper is fairly old. I did discover an error where the event source isn't registered correctly. This is fixed in a later version of the containerhelper or later images.
This means that if the web client for some reason tries to add something to the event log - it will die.
That could be the reason

**Comment by tomasevicstefan** [comment]
Yes, I saw that you wrote about that on your blog, but didn't connect that with this issue.
I will update my navcontainerhelper.
