### ISSUE TITLE
Image nav2015-cu22-ch not availabe? 

### ISSUE THREAD

**Issue by mckasp** [microsoft/nav-docker#365]
I have tried to download the image microsoft/dynamics-nav:2015-cu22-ch through navcontainerhelper.

I get the following error:

**DockerDo : Error response from daemon: manifest for microsoft/dynamics-nav:2015-cu22-ch not found**

**Comment by dNsl9r** [comment]
NAV 2015 was never hosted on docker as far as I know..

**Comment by freddydk** [comment]
Correct - NAV 2015 must be run using the generic image and a DVD image.
https://freddysblog.com/2017/11/29/can-i-run-nav-2015-and-earlier-on-docker/
