### ISSUE TITLE
Current DE CU Releases not available

### ISSUE THREAD

**Issue by dNsl9r** [microsoft/nav-docker#366]
Hi,
I'm missing the docker images for:
NAV 2018 CU17 DE
NAV 2017 CU30 DE
NAV 2016 CU43 DE

When will they be available?

**Comment by dNsl9r** [comment]
@freddydk some Info on this?

**Comment by freddydk** [comment]
mcr.microsoft.com/dynamicsnav:2018-cu17-de

I will write up a blog post on new location of images (have mentioned it a few times, but not final)

**Comment by dNsl9r** [comment]
Ah, perfect. Was always trying "mcr.microsoft.com/dynamics-nav". Stupid me 😅
