### ISSUE TITLE
Download symbols does not work 

### ISSUE THREAD

**Issue by dkorinets** [Microsoft/nav-docker#37]
"type": "al",
            "request": "publish",
            "name": "ExtName",
            "server": "https://4d60XXX961",
            "serverInstance": "NAV",
            "tenant": "default",
            "authentication": "UserPassword"

Error: An error occurred while sending the request.
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
The remote certificate is invalid according to the validation procedure.

**Comment by freddydk** [comment]
If you are using SSL, you need to install the SSL certificate (which you can download from the containers files area) in the trusted certificate authorities on the host machine.
or you can use -e UseSSL=N in your Docker run command and then use http in the launch.json server name

**Comment by dkorinets** [comment]
Thx, solved
