### ISSUE TITLE
Error when creating new container on New-DesktopShortcut

### ISSUE THREAD

**Issue by JonFjolnirAlbertsson** [microsoft/nav-docker#370]
I get the following error when creating new docker for the image mcr.microsoft.com/businesscentral/onprem:no (14.0.29537.0) on Windows 10 1803
New-DesktopShortcut : Kan ikke lagre snarveien C:\Users\JónFjölnirAlbertsson\Desktop\BCSpring01 Web Client.lnk.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.1.1\ContainerHandling\New-NavContainer.ps1:1023 char:13
+             New-DesktopShortcut -Name "$containerName Web Client" -Ta ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [New-DesktopShortcut], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,New-DesktopShortcut

**Comment by freddydk** [comment]
The cmdlet is using [Environment]::GetFolderPath("Desktop") does this folder not exist?
You can specify -shortcuts none to avoid shortcuts or -shortcuts StartMenu to add them to the startmenu instead of the desktop.

**Comment by NAVspecialist** [comment]
You probably have the parameter **-shortcuts Desktop** added to your NewNavContainer - try removing it and run your image again. If it works... Either to desktop folder does not exist or you dont have permissions to create files on the desktop.

**Comment by freddydk** [comment]
-shortcuts Desktop is the default.
