### ISSUE TITLE
Daily builds are supposed to be older than 1 day?

### ISSUE THREAD

**Issue by frivadulla** [microsoft/nav-docker#372]
In _bcinsider.azurecr.io/bcsandbox-master_ , which is supossed to be updated regularly, we still dont have new event definitions that are marked to ship-in-next-update.

Is this normal? When we can expect this docker to be updated?

We are in lot of development that need those events and it would be nice to have a docker updated.

**Comment by freddydk** [comment]
https://freddysblog.com/2019/05/29/business-central-fall-2019-preview-availability
I expect bcsandbox-master to restart within a week.

**Comment by frivadulla** [comment]
Thx for the info.

I´m closing the issue.

Kind regards.
