### ISSUE TITLE
Database related env variables have defaults potentially leading to problems

### ISSUE THREAD

**Issue by tfenster** [microsoft/nav-docker#373]
The env variables for databaseServer, databaseInstance and databaseName have "defaults" because the are set in the W1 Dockerfiles (see e.g. https://github.com/microsoft/nav-docker/blob/master/bc-w1/DOCKERFILE#L15). To verify, run e.g. the following command and you get values for those variables although nothing was specified at docker run

```
docker run mcr.microsoft.com/dynamicsnav:2017-cu22-de-ltsc2016 powershell -command Write-Host $env:databaseinstance $env:databasename $env:databaseserver
SQLEXPRESS Cronusde localhost
```

If you do something like the following expecting the container to connect to the default SQL instance, it fails because it tries to connect to SQLEXPRESS:

```
docker run -e accept_eula=y -e "databasePassword=DontThinkSo" -e "databaseServer=mydb.database.cloudapi.de" -e databaseName=test -e "databaseUserName=DBVerwalter" mcr.microsoft.com/dynamicsnav:2017-cu22-de-ltsc2016
```

The workaround is to set the env variable to nothing on docker run (`-e "databaseInstance="`) but I think it would be better to reset the env in the Dockerfile. PR to follow :)

**Comment by tfenster** [comment]
To validate without the whole build process, you can create a Dockerfile like this

```
FROM mcr.microsoft.com/dynamicsnav:2017-cu22-de-ltsc2016
ENV DatabaseServer="" DatabaseInstance="" DatabaseName=""
```

Then do a docker build, e.g. `docker build -t test .` and run that one with a check of the env params, which only returns an empty line:

```
docker run test powershell -command Write-Host $env:databaseinstance $env:databasename $env:databaseserver

```

**Comment by freddydk** [comment]
I agree that this is wrong - but to be honest, I cannot calculate the consequences of a fix like this.
Other things that might live of this might start failing - especially in the ContainerHelper.

**Comment by tfenster** [comment]
Understood. I think this should be mentioned somewhere as it seems to me like something people new to the container usage might find very confusing. I'll probably also write a quick blog post

**Comment by freddydk** [comment]
Yeah, so basically, if you run a container connecting to a foreign SQL Server - you need to set server, instance AND name - you cannot use only server and name

**Comment by tfenster** [comment]
Just FYI: https://www.axians-infoma.com/techblog/caveat-when-connecting-your-bc-container-to-a-default-sql-instance-or-why-does-importing-the-encryption-key-fail/
