### ISSUE TITLE
2018-cu17-na doesn't seem to be available

### ISSUE THREAD

**Issue by pir8-x** [microsoft/nav-docker#376]
Hi, when I try to pull 2018-cu17-na, I get:
docker : Error response from daemon: manifest for **microsoft/dynamics-nav:2018-cu17-na** not found

I did notice in #366 that the path may have changed to dynamicsnav (no hyphen), but if I try '**microsoft/dynamicsnav:2018-cu17-na**' I get:
docker : Error response from daemon: pull access denied for microsoft/dynamicsnav, repository does not exist or may require 'docker login'

Please let me know if I'm missing something, or if/when 2018-cu17-na will be available.

Thanks!
-Andrew

**Comment by freddydk** [comment]
mcr.microsoft.com/dynamicsnav:2018-cu17-na

**Comment by pir8-x** [comment]
Thanks @freddydk ! I assume https://hub.docker.com/r/microsoft/dynamics-nav is going to be updated at some point?

**Comment by freddydk** [comment]
Yes:-)
