### ISSUE TITLE
Publish-NavContainerApp -useDevEndpoint

### ISSUE THREAD

**Issue by kylehardin6** [microsoft/nav-docker#377]
Using the new -useDevEndpoint parameter for Publish-NavContainerApp, I get the following error:

Publish-NavContainerApp : Exception calling ".ctor" with "2" argument(s): "Could not find file
'C:\Windows\ArcherPoint_CKSPackaging_1.0.0.0.app'."

Script to reproduce:
Update-Module navcontainerhelper
$containerName = 'CKS'
$navdockerimage = 'mcr.microsoft.com/businesscentral/onprem:14.0.29537.0-na-ltsc2019'
$companyName = "CKS Packaging"
$navApp = "..\ArcherPoint_CKSPackaging_1.0.0.0.app"
Remove-NavContainer $containername
docker pull $navdockerimage
New-NavContainer `
  -accept_eula:$true `
  -containername $containerName `
  -imageName $navdockerimage `
  -auth Windows `
  -includeCSide `
  -doNotExportObjectsToText `
  -enableSymbolLoading `
  -usessl:$false `
  -updateHosts `
  -assignPremiumPlan `
  -shortcuts Desktop `
  -licensefile "..\Licenses\bc.flf" `
  -additionalParameters @('--volume c:\share:c:\share')
Publish-NavContainerApp `
  -useDevEndpoint `
  -containerName $containerName `
  -appFile $navApp `
  -skipVerification `
  -sync Add `
  -install `
  -tenant default

**Comment by freddydk** [comment]
I think the error tells you what is wrong.
You should specify a full path to your app - I don't expect that you put it in C;\Windows
Relative paths like ..\ should never be used
In PowerShell - the relative path is relative to the current directory - not to the directory of the script.
Use $psscriptroot if you need relative to the script (Join-path $psscriptroot "..\myapp.app") is fine.

**Comment by kylehardin6** [comment]
I would agree with this assessment, except it works if I remove the -useDevEndpoint parameter. I made no other changes to the script, and left my path as relative.

**Comment by freddydk** [comment]
That might be - the script is following two different paths to publish the app, and the error clearly states that it tries to find it at c:\windows\app.app - which indicates that it resolves .. wrongly.
