### ISSUE TITLE
docker generic for 2013R2 - Initialization of container n2013r2cu51at failed

### ISSUE THREAD

**Issue by PleachiM** [microsoft/nav-docker#379]
Today I tried to create a 2013R2 CU51 AT Docker Container. 

`
New-NavContainer -accept_eula -accept_outdated -containerName n2013r2cu51at -navDvdPath "S:\999999 tmp\2013R2CU51" -navDvdCountry At -updateHosts -auth Windows -doNotExportObjectsToText -Credential (Get-Credential) -licenseFile "D:\license.flf" -includeCSide -isolation hyperv
`

Init

`
Cmdlet Get-Credential an der Befehlspipelineposition 1
Geben Sie Werte für die folgenden Parameter an:
NavContainerHelper is version 0.6.1.1
Host is Microsoft Windows 10 Pro - ltsc2019
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Using image microsoft/dynamics-nav:generic-ltsc2019
Removing container n2013r2cu51at
Removing n2013r2cu51at from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\n2013r2cu51at
Creating Nav container n2013r2cu51at
Using license file D:\license.flf
Version: 7.1.49751.0-At
Generic Tag: 0.0.9.6
Container OS Version: 10.0.17763.437 (ltsc2019)
Host OS Version: 10.0.17763.503 (ltsc2019)
Using hyperv isolation
Creating container n2013r2cu51at from image microsoft/dynamics-nav:generic-ltsc2019
e45e294ce55e0491267919198a25181420c112186247cf65b143ee4d514d584b
Waiting for container n2013r2cu51at to be ready
Installing NAV
Installing .NET 3
Installing VC Redist
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Installing Url Rewrite
Installing Report Viewer
Installing OpenXML
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying UpgradeToolKit
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Changing Database Server Collation to Latin1_General_100_CS_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more about SQL Server 2017 data proc
essing and privacy controls, please see the Privacy Statement.
Installing C:\NAVDVD\Installers\AT\OlAddin\OutlookAddIn.Local.At.msi
Installing C:\NAVDVD\Installers\AT\RTC\RoleTailoredClient.Local.At.msi
Installing C:\NAVDVD\Installers\AT\Server\Server.Local.At.msi
Installing C:\NAVDVD\Installers\AT\WebClient\WebClient.Local.At.msi
Skipping C:\NAVDVD\Installers\AT\WebHelp\WebHelp.Local.At.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Starting NAV Service Tier
Importing CRONUS license file
The Microsoft Dynamics NAV server is currently not ready to serve requests. Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\navinstall.ps1: line 187
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1Error
Installing NAV
Installing .NET 3
Installing VC Redist
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Installing Url Rewrite
Installing Report Viewer
Installing OpenXML
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying UpgradeToolKit
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Changing Database Server Collation to Latin1_General_100_CS_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more about SQL Server 2017 data proc
essing and privacy controls, please see the Privacy Statement.
Installing C:\NAVDVD\Installers\AT\OlAddin\OutlookAddIn.Local.At.msi
Installing C:\NAVDVD\Installers\AT\RTC\RoleTailoredClient.Local.At.msi
Installing C:\NAVDVD\Installers\AT\Server\Server.Local.At.msi
Installing C:\NAVDVD\Installers\AT\WebClient\WebClient.Local.At.msi
Skipping C:\NAVDVD\Installers\AT\WebHelp\WebHelp.Local.At.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Starting NAV Service Tier
Importing CRONUS license file
The Microsoft Dynamics NAV server is currently not ready to serve requests. Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\navinstall.ps1: line 187
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1
Initialization of container n2013r2cu51at failed
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.1.1\ContainerHandling\Wait-NavContainerReady.ps1:45 Zeichen:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...r2cu51at failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container n2013r2cu51at failed
`

Inspect:

`
[
    {
        "Id": "e45e294ce55e0491267919198a25181420c112186247cf65b143ee4d514d584b",
        "Created": "2019-06-12T10:43:32.7012948Z",
        "Path": "powershell",
        "Args": [
            "-Command",
            "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
            ".\\Run\\start.ps1"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1392,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-06-12T10:43:44.8685861Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2019-06-12T12:51:33.2620264+02:00",
                        "End": "2019-06-12T12:51:35.8620147+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-06-12T12:52:05.8696613+02:00",
                        "End": "2019-06-12T12:52:08.9730406+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-06-12T12:52:38.9828607+02:00",
                        "End": "2019-06-12T12:52:41.8851452+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-06-12T12:53:11.8957294+02:00",
                        "End": "2019-06-12T12:53:14.3090682+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-06-12T12:53:44.3178713+02:00",
                        "End": "2019-06-12T12:53:46.653915+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:efa76537e9f67112db27934ee8dcd8cace4e677d1a33a3dafde8667030618d11",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\Docker\\containers\\e45e294ce55e0491267919198a25181420c112186247cf65b143ee4d514d584b\\e45e294ce55e0491267919198a25181420c112186247cf65b143ee4d514d584b-json.log",
        "Name": "/n2013r2cu51at",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\n2013r2cu51at\\my:C:\\Run\\my",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\n2013r2cu51at\\Program Files:C:\\navpfiles",
                "S:\\999999 tmp\\2013R2CU51:c:\\NAVDVD",
                "c:\\windows\\system32\\drivers\\etc:C:\\driversetc",
                "C:\\ProgramData\\NavContainerHelper:C:\\ProgramData\\NavContainerHelper"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "hyperv",
            "CpuShares": 0,
            "Memory": 4294967296,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\windowsfilter\\e45e294ce55e0491267919198a25181420c112186247cf65b143ee4d514d584b"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\windows\\system32\\drivers\\etc",
                "Destination": "c:\\driversetc",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper",
                "Destination": "c:\\programdata\\navcontainerhelper",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\n2013r2cu51at\\my",
                "Destination": "c:\\run\\my",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\n2013r2cu51at\\program files",
                "Destination": "c:\\navpfiles",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "s:\\999999 tmp\\2013r2cu51",
                "Destination": "c:\\navdvd",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "n2013r2cu51at",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "locale=de-AT",
                "passwordKeyFile=c:\\run\\my\\aes.key",
                "auth=Windows",
                "username=michael.platl",
                "ExitOnError=N",
                "licenseFile=c:\\run\\my\\license.flf",
                "databaseServer=",
                "databaseInstance=",
                "useSSL=N",
                "securePassword=76492d1116743f0423413b16050a5345MgB8AHMAaQAyAHYANgAvAEUAWQBKAGMANQBGAGYAcwBUAEYAUQBYAGEAVQBpAEEAPQA9AHwAYwBmAGQAYgAxADQAMwA2ADkANQA1AGEAOAAzAGMANAAxADkANwAwADYAMwA3AGQAYQBiAD
QAZQBkAGMAZQA4ADkANgAwAGQAZgA0ADcAMQA4AGMAMABkADAAMAA3ADYANAA0ADEAZQA2AGEAMQAwADkAMAA1ADMAYwBkADgANAA=",
                "removePasswordKeyFile=Y",
                "accept_eula=Y",
                "accept_outdated=Y"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "microsoft/dynamics-nav:generic-ltsc2019",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "At",
                "created": "",
                "cu": "",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "maintainer": "Dynamics SMB",
                "nav": "2013r2",
                "osversion": "10.0.17763.437",
                "tag": "0.0.9.6",
                "version": "7.1.49751.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "e45e294ce55e0491267919198a25181420c112186247cf65b143ee4d514d584b",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "80/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "e45e294ce55e0491267919198a25181420c112186247cf65b143ee4d514d584b",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "7ecb61e9156917dbbab1a7713807609478a3614e6ae6d15e5e75ddf80d2f6e4c",
                    "EndpointID": "90a076f6f49d1e5540d24216ff2721ff933b2e1589fcf5ec4b0a8258032e3c59",
                    "Gateway": "172.22.192.1",
                    "IPAddress": "172.22.202.0",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:a5:34:fe",
                    "DriverOpts": null
                }
            }
        }
    }
]
`

**Comment by NAVspecialist** [comment]
You could try a few fast things:

n2013r2cu51at <-- Shorten the containername 
"S:\999999 tmp\2013R2CU51" <-- Rename the folder not to contain spaces.

**Comment by PleachiM** [comment]
Same problem. That makes no difference.

**Comment by freddydk** [comment]
You could try to use get-navcontainereventlog to see what the event log says ? (Why the service tier wont start)

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: PleachiM <notifications@github.com>
Sendt: Wednesday, June 12, 2019 1:45:51 PM
Til: microsoft/nav-docker
Cc: Subscribed
Emne: Re: [microsoft/nav-docker] docker generic for 2013R2 - Initialization of container n2013r2cu51at failed (#379)


Same problem. That makes no difference.

**Comment by PleachiM** [comment]
I did this now. 
So the error is .. .

`

Server instance: NAV
User: 
Type: System.IO.DirectoryNotFoundException
Message: The path to Windows Communication Foundation was not found on the service tier. It was expected to be in folder 'C:\Windows\Microsoft.NET\Framework64\v3.0\Windows Communication Foundation'. Have you installed the .NET Framework 3.0?
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.CSharpCompiler..ctor()
     at Microsoft.Dynamics.Nav.Runtime.AssemblyGetter..ctor()
     at Microsoft.Dynamics.Nav.Runtime.NCLCodeLoader..ctor()
     at Microsoft.Dynamics.Nav.Runtime.NCLMetadata..ctor(NavDatabase ownerDatabase)
     at Microsoft.Dynamics.Nav.Runtime.NavSystemTenant..ctor(String appDatabaseServerName, String appDatabaseName)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSystemTenant(String appDatabaseServerName, String appDatabaseName, Boolean verifyConnection)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSingleLegacyTenant(String databaseServerName, String databaseUserName, String databaseUserPassword, String databaseName, Boolean verifySystemTenantConnection)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.ConfigureTenants(ServerUserSettings settings)
     at System.Threading.Tasks.Task.Execute()
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2147024893

`

I have seen this error before long time ago. 

I placed the microsoft-windows-netfx3-ondemand-package.cab in the prerequisites folder.

**Comment by itsamarok** [comment]
i used the this script to create container
# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true

$containername = 'msbc365box'
$navdockerimage = 'microsoft/bcsandbox:us'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth Windows `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password

although got same error message
![image](https://user-images.githubusercontent.com/51352958/59406527-5e9ae900-8d63-11e9-8e53-f517195e5d5f.png)

as advised by freddydk, while on event log got one error and repeating warning message in event log.
![image](https://user-images.githubusercontent.com/51352958/59406400-e2a0a100-8d62-11e9-8e6c-c7903bd3b99f.png)

![image](https://user-images.githubusercontent.com/51352958/59406423-095ed780-8d63-11e9-9836-0113a4dfb674.png)

**Comment by freddydk** [comment]
Could you try to open a powershell prompt in the container (enter-navcontainter) and run

Dism /online /enable-feature /all /featurename:NetFX3 /Source:"C:\NAVDVD\Prerequisite Components"

What does that say?

**Comment by freddydk** [comment]
I can see that it defaults to Server 2019.
I have no idea whether .net 3 can be installed on Server 2019.
In case it can - you need the .net3 cab file from windows server 2019 media (I don't know if it is different)

or you can specify that you want to use Windows Server 2016 container OS. Add this

-useGenericImage mcr.microsoft.com/dynamicsnav:generic-ltsc2016

**Comment by PleachiM** [comment]
> I can see that it defaults to Server 2019.
> I have no idea whether .net 3 can be installed on Server 2019.
> In case it can - you need the .net3 cab file from windows server 2019 media (I don't know if it is different)
> 
> or you can specify that you want to use Windows Server 2016 container OS. Add this
> 
> -useGenericImage mcr.microsoft.com/dynamicsnav:generic-ltsc2016

that's the trick. Thank you
