### ISSUE TITLE
BUG/Typo in navstart.ps1

### ISSUE THREAD

**Issue by gregoral** [microsoft/nav-docker#380]
Using image: **mcr.microsoft.com/businesscentral/sandbox:14.1.32615.0**
The bug/typo is present on all docker images we have seen to date.

The script sets this variable: **$restartingInstance**
But the script later tests for a different one: **$restartingImage**
I believe this is a typo and that the 90 day warning was never intended to trigger during container restart.

This is the abbreviated code from the script:
**$restartingInstance** = Test-Path -Path $publicDnsNameFile -PathType Leaf
...
if (!**$restartingImage**) {
    $containerAge = [System.DateTime]::Now.Subtract((Get-Item "C:\RUN").CreationTime).Days
    if ($containerAge -gt 90) {
        if ($Accept_outdated -ne "Y") {

To work around this issue you can put the below into a C:\Run\my\navstart.ps1:

```
$restartingImage = Test-Path -Path $publicDnsNameFile -PathType Leaf
. (Join-Path $runPath "navstart.ps1")
return
```

**Comment by freddydk** [comment]
You are right:-(

**Comment by freddydk** [comment]
Bug has been fixed in latest generic images
