### ISSUE TITLE
Unable to connect to remote server

### ISSUE THREAD

**Issue by tomasevicstefan** [microsoft/nav-docker#382]
I successfully build BC on container sandbox without any errors, but I'm not able to start finsql, desktop or web client. Also I'm not able to download symbols.

image: mcr.microsoft.com/businesscentral/onprem:13.6.29777.0-is-ltsc2019

Event log from container does not show any errors related to BC instance
We are using process isolation.
Windows version 1809
Docker EE 18.09.6
navcontainerhelper 0.6.2.2

Do I missed something?

**Comment by freddydk** [comment]
You would have to provide the command you use and the full output of the command

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: tomasevicstefan <notifications@github.com>
Sendt: Friday, June 28, 2019 3:36:44 PM
Til: microsoft/nav-docker
Cc: Subscribed
Emne: [microsoft/nav-docker] Unable to connect to remote server (#382)


I successfully build BC on container sandbox without any errors, but I'm not able to start finsql, desktop or web client. Also I'm not able to download symbols.

image: mcr.microsoft.com/businesscentral/onprem:13.6.29777.0-is-ltsc2019

Event log from container does not show any errors related to BC instance
We are using process isolation.
Windows version 1809
Docker EE 18.09.6
navcontainerhelper 0.6.2.2

Do I missed something?

**Comment by tomasevicstefan** [comment]
Problem was in vpn client. I missed allow local access when using VPN to be checked.
