### ISSUE TITLE
Install microsoft/bcsandbox:us-ltsc2016 error

### ISSUE THREAD

**Issue by robertzengcn** [microsoft/nav-docker#383]
Hello, I try to install dynamic365 sandbox in my docker machine, but after I full the images success, I got following error:

DockerDo : docker.exe: Error response from daemon: Windows client operating systems earlier than version 1809 can only run Hyper-V c
ontainers.
See 'docker.exe run --help'.
ExitCode: 125
Commandline: docker run --name MyBizCentralApp --hostname MyBizCentralApp --env auth=Windows --env username="jianze_zeng" --env Exit
OnError=N --env locale=en-US --env licenseFile="" --env databaseServer="" --env databaseInstance="" --volume "C:\ProgramData\NavCont
ainerHelper:C:\ProgramData\NavContainerHelper" --volume "C:\ProgramData\NavContainerHelper\Extensions\MyBizCentralApp\my:C:\Run\my" 
--isolation process --restart unless-stopped --env enableApiServices=Y --env useSSL=N --volume "C:\ProgramData\NavContainerHelper\Ex
tensions\MyBizCentralApp\Program Files:C:\navpfiles" --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=7
6492d1116743f0423413b16050a5345MgB8AFoAMwBXADcATQBqAEMAZgBaAEMAMQB6ADcARgBkAEwASAB1AHIAOQBvAGcAPQA9AHwAOQBhADUAYgA3ADYAOQA3AGMAYwBlA
DkAZAAxADIANAA2ADYAOQA2ADMAMAAxAGIAMQBjAGIAZQA3ADUAZgBjADAANQAyADQAMwAxAGMAZgA2ADcAOABiADQAOAA3AGQANQBlADIAZQBmAGMAZABkADEANABhADAAO
AAyAGEANgA= --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y --detach microsoft/bcsandbox
:us-ltsc2016
所在位置 C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.1\ContainerHandling\New-NavContainer.ps1:998 字符: 19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

May I know how to solve, my docker version is: 2.0.0.3 (31259) with engine 18.09.2 build in

**Comment by freddydk** [comment]
Exactly, we need the command you use and the full output.
This will tell us everything about OS etc. which is needed for troubleshooting,

**Comment by freddydk** [comment]
Didn't mean to close:-)

**Comment by robertzengcn** [comment]
Hello @freddydk @dNsl9r  following is the code I use to install sandbox:
install-module navcontainerhelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true

$containername = 'MyBizCentralApp'
$navdockerimage = 'microsoft/bcsandbox:us'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth Windows `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers  -containerName $containername -password $credential.Password

**Comment by dNsl9r** [comment]
So this is the part where you create the container: 
`New-NavContainer -accept_eula:$accept_eula -containername $containername
-auth Windows -Credential $credential
-includeCSide -alwaysPull
-doNotExportObjectsToText -usessl:$false
-updateHosts -assignPremiumPlan
-shortcuts Desktop -imageName $navdockerimage
-additionalParameters $additionalParameters`

Please try to add `-isolation hyperv` after the additionalParameters

**Comment by robertzengcn** [comment]
Thank you , I will try

**Comment by robertzengcn** [comment]
still the same error, now my command is:
install-module navcontainerhelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true

$containername = 'MyBizCentralApp'
$navdockerimage = 'microsoft/bcsandbox:us'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth Windows `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters
                 -isolation hyperv

Setup-NavContainerTestUsers  -containerName $containername -password $credential.Password

I still get the error:
DockerDo : docker.exe: Error response from daemon: Windows client operating systems earlier than version 1809 can only run Hyper-V c
ontainers.
See 'docker.exe run --help'.
ExitCode: 125
Commandline: docker run --name MyBizCentralApp --hostname MyBizCentralApp --env auth=Windows --env username="jianze_zeng" --env Exit
OnError=N --env locale=en-US --env licenseFile="" --env databaseServer="" --env databaseInstance="" --volume "C:\ProgramData\NavCont
ainerHelper:C:\ProgramData\NavContainerHelper" --volume "C:\ProgramData\NavContainerHelper\Extensions\MyBizCentralApp\my:C:\Run\my" 
--isolation process --restart unless-stopped --env enableApiServices=Y --env useSSL=N --volume "C:\ProgramData\NavContainerHelper\Ex
tensions\MyBizCentralApp\Program Files:C:\navpfiles" --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=7
6492d1116743f0423413b16050a5345MgB8ADEAdwBIAEYAcQBrAE8AUAAvAHcANQB3AFIAcwBBAFAANABGAEkAagBLAGcAPQA9AHwAYwA5AGQAMwA5AGQAYwA4ADYAMQBmA
DAAOAA0ADQANQAwAGYAYwA2ADUAMgA2ADUANQAwAGMANgBkAGEANgA2ADYAMQA2AGUAMwAwADcAMAA1ADAAOAA5ADEANgBlADcAZQBkAGMAOQA5ADkAMAAxAGMANAA2ADIAZ
gBlADYAMQA= --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y --detach microsoft/bcsandbox
:us-ltsc2016
所在位置 C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.1\ContainerHandling\New-NavContainer.ps1:998 字符: 19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by robertzengcn** [comment]
attached is the code I run with
[CreateBCSandbox.zip](https://github.com/microsoft/nav-docker/files/3345049/CreateBCSandbox.zip)

**Comment by freddydk** [comment]
I need the full output of the new-navcontainer command (not in a .zip file - I don't download .zip files:-))

**Comment by robertzengcn** [comment]
Hello the full out put is:
PS C:\Users\jianze_zeng> E:\dyntest\CreateBCSandbox.ps1
NavContainerHelper is version 0.6.2.1
Host is Microsoft Windows 10 专业版 - ltsc2016
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Pulling image microsoft/bcsandbox:us-ltsc2016
us-ltsc2016: Pulling from microsoft/bcsandbox
Using image microsoft/bcsandbox:us-ltsc2016
Removing MyBizCentralApp from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\MyBizCentralApp
Creating Container MyBizCentralApp
Version: 14.0.29537.31808-US
Platform: 14.0.29530.31705
Generic Tag: 0.0.9.6
Container OS Version: 10.0.14393.2906 (ltsc2016)
Host OS Version: 10.0.14393.2214 (ltsc2016)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using process isolation
Creating container MyBizCentralApp from image microsoft/bcsandbox:us-ltsc2016
DockerDo : docker.exe: Error response from daemon: Windows client operating systems earlier than version 1809 can only run Hyper-V containers.
See 'docker.exe run --help'.
ExitCode: 125
Commandline: docker run --name MyBizCentralApp --hostname MyBizCentralApp --env auth=Windows --env username="jianze_zeng" --env ExitOnError=N --env lo
cale=en-US --env licenseFile="" --env databaseServer="" --env databaseInstance="" --volume "C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContai
nerHelper" --volume "C:\ProgramData\NavContainerHelper\Extensions\MyBizCentralApp\my:C:\Run\my" --isolation process --restart unless-stopped --env ena
bleApiServices=Y --env useSSL=N --volume "C:\ProgramData\NavContainerHelper\Extensions\MyBizCentralApp\Program Files:C:\navpfiles" --volume "c:\window
s\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b16050a5345MgB8AHgAZABiAHoASQB6AGkAOQB6AG4AYQBNAGgAMQBrAHoAaABXAEgATQB
vAHcAPQA9AHwAOAA2ADMAYwAzAGIAZgBkADEAMgBiAGMANQA2ADQAZAA1ADUAOAA4ADEAZQA1ADkAMwA0AGEAMgA4ADQAYQAwADgANQAxADQAMgBiAGIAYgA3AGYAYgA1ADkAMgAzADcAMAA3AGEAZ
gBhADUAYwA5ADEAYwA0ADAAMgBhADkAMQA= --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y --detach microsoft/bcs
andbox:us-ltsc2016
所在位置 C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.1\ContainerHandling\New-NavContainer.ps1:998 字符: 19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by freddydk** [comment]
In the output it states:
```
Container OS Version: 10.0.14393.2906 (ltsc2016)
Host OS Version: 10.0.14393.2214 (ltsc2016)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using process isolation
```
As Danis said - add -isolation hyperv to the new-navcontainer command - it needs to be on the same line as the other parameters or there needs to be a ` character to indicate that the line continues.

**Comment by robertzengcn** [comment]
Hello all , it works after I add ` , But now I encount another error, may I know how to solve:

DockerDo : docker.exe: Error response from daemon: CreateComputeSystem 53705a69565f831ed770e598afc1efd63b73fde6f8208edb27e32a7d76424183: The paging fi
le is too small for this operation to complete.
[Event Detail: 鏃犳硶涓?Hyper-V 瀹瑰櫒鈥?3705a69565f831ed770e598afc1efd63b73fde6f8208edb27e32a7d76424183鈥濆垱寤鸿櫄鎷熸満: 椤甸潰鏂囦欢澶皬锛屾棤娉曞畬鎴愭搷浣溿€?(0x800705AF)銆?Provide
r: 17103e3f-3c6e-4677-bb17-3b267eb5be57 EventID: 12000]
(extra info: {"SystemType":"Container","Name":"53705a69565f831ed770e598afc1efd63b73fde6f8208edb27e32a7d76424183","Owner":"docker","IgnoreFlushesDuring
Boot":true,"LayerFolderPath":"F:\\Docker\\image\\windowsfilter\\53705a69565f831ed770e598afc1efd63b73fde6f8208edb27e32a7d76424183","Layers":[{"ID":"30a
303ea-d434-51ab-a815-1e9ed4c100f7","Path":"F:\\Docker\\image\\windowsfilter\\5ca30d60687bfc43fcf0f1536388be0df680ce848284283ba873b47751635b75"},{"ID":
"e098c864-bfb3-54dd-96eb-b0257b266630","Path":"F:\\Docker\\image\\windowsfilter\\64064764a79b0c22bb1520a5465bad50eab296ecfd9423f4a3610916bf6c45fd"},{"
ID":"12c8884f-9ace-5534-930b-cff3911b6d39","Path":"F:\\Docker\\image\\windowsfilter\\92f389f62b2bdc8edd764abaa7b6dafb50b6a9851a20a8ec162cb617513f55fb"
},{"ID":"3baaf0af-3555-55c9-96c8-b79fdec29811","Path":"F:\\Docker\\image\\windowsfilter\\e92898406f13cb396d43eb7725cb1da4dafe5eda1618a0c0c2274fe48a99e
946"},{"ID":"1a978197-d958-5b2c-9969-e73b53ee4848","Path":"F:\\Docker\\image\\windowsfilter\\6a098d7f03f099e16c7bebda79e03d31deb64d8ab61f2ee5b8578d230
080f659"},{"ID":"8f607d49-389f-5ffd-bff3-8e87ed402482","Path":"F:\\Docker\\image\\windowsfilter\\0fd34e516e0676816e6c8d5f986c69a23d83a33d9c5418f01af1e
19f73745a6f"},{"ID":"f9723199-de01-5c6e-8094-2895fc5eb743","Path":"F:\\Docker\\image\\windowsfilter\\ce6ae0a443bc46cb51753064298c7587866a31e0ecba5dffb
5374cd28119a427"},{"ID":"25a694ba-5b7d-5e64-af9d-37b5fd90c03c","Path":"F:\\Docker\\image\\windowsfilter\\a80b08de22feb665773c7ef89333ccb248dd7f4fb4ab9
e17a69dc60309422f5c"},{"ID":"dc3d4f17-c190-5348-be83-d81461d89763","Path":"F:\\Docker\\image\\windowsfilter\\f4c5549ca7b02f1ad0ed285195a3cab51bb55d65c
b90b2d76daf6ad7048759b2"},{"ID":"80facf9d-80b0-55fb-8a27-52261e4d6e91","Path":"F:\\Docker\\image\\windowsfilter\\90ce41803feaee4ac2eaddb88d693750a014f
5ff4d2ab849ebcbd3748c87ac0e"},{"ID":"f6b984bf-50a6-5b52-8c34-0f253b30b7e9","Path":"F:\\Docker\\image\\windowsfilter\\9873912d18a9836733016b696192ab33b
1874886623ef877a0ee80b5fbc05dfc"},{"ID":"55d3fecf-b35b-5583-93b0-3fa15f8aed67","Path":"F:\\Docker\\image\\windowsfilter\\8f22d914d6ab046e3538de2af0c7f
1b46c259e3741e6c6d029c274d41cf40f69"},{"ID":"00eee0c3-9901-59fc-8550-9cb7bceb2082","Path":"F:\\Docker\\image\\windowsfilter\\93e6c59b7acb3178dfd544437
222ef21b3cd09e62f36f19eff9b32e2e4225168"},{"ID":"49a14dff-8292-5b4e-aafc-4947a42a4c5e","Path":"F:\\Docker\\image\\windowsfilter\\3834b6870706496477f94
09d44dc7249b614ea334a1e12966c4568c7e63a3d5d"},{"ID":"f96ce789-7ae1-5152-9efc-0f0c599663bf","Path":"F:\\Docker\\image\\windowsfilter\\dd2218adb39917468
5708aa770d122a95b540a896582edc2c04c18c5e61d8a29"},{"ID":"eef7fecc-72a2-582d-b7f4-b114a5bed1de","Path":"F:\\Docker\\image\\windowsfilter\\1a813b21d94b1
06d293d6fe106a4124a7a321acdb8adae308e23a4d6907c7426"},{"ID":"79341d29-2b58-594e-be14-da340d515f37","Path":"F:\\Docker\\image\\windowsfilter\\ef613e764
e1bd114433addae0d9d691e2407e6259795cb14511ceb40acf1224c"},{"ID":"49df1160-7d05-5db9-baf2-20b68a18286a","Path":"F:\\Docker\\image\\windowsfilter\\98c85
a962ee9c0a769e1acac836037dd17d86a91a5d7ef3815a1f28614049917"},{"ID":"d8d2e43b-0777-52c0-8d8b-b188ba2684ca","Path":"F:\\Docker\\image\\windowsfilter\\7
6427f4699b98b79c4fa1b036bbbcfb4f5f5528f87a0a2cb3928a34485242397"},{"ID":"afeda643-b8f5-5a7d-b648-e7befd818718","Path":"F:\\Docker\\image\\windowsfilte
r\\0daf663308026094f5b6d0deb30baaa8b4fbe2ce2a048e896926e9feed6a73cd"},{"ID":"9c63f5ae-d27d-556c-b5f1-997b0c2a1543","Path":"F:\\Docker\\image\\windowsf
ilter\\244ee927560f8c25e1c60f4905a234493326de38a0fba9740b5a3c85f696ec88"},{"ID":"27a0847a-6dbd-5e54-94b7-13a8a60e9766","Path":"F:\\Docker\\image\\wind
owsfilter\\0a70a879d39d980d99d7d5a944f0d41ad5b017704b8c246aef92b3ebabaa18f8"},{"ID":"66514d7f-2bcf-5562-8bf4-2433e101204b","Path":"F:\\Docker\\image\\
windowsfilter\\62fbf8ed4a85caa050270f1ad2ce670d73d98cede0e384b6f78937b8c2bb6ade"},{"ID":"06fcb456-a615-59f2-9c7e-b24c04269f92","Path":"F:\\Docker\\ima
ge\\windowsfilter\\88bf4e673101706af0409e71826dcd51e41f52c1fcc2de6c3c486d470c486a15"},{"ID":"e79bca01-ec05-574f-be52-93f480e06a8f","Path":"F:\\Docker\
\image\\windowsfilter\\8cf0ffd61627079333dc4c4bd83cdaba69245e9a35caf7b3c9bc02ba0a6409cc"},{"ID":"5c20251f-f887-57bb-a113-24b0c26130ce","Path":"F:\\Doc
ker\\image\\windowsfilter\\a0f2df35ef6f6f5d9e3f4c06aa8d916fab066ff1cb70b4eff5645687027feb67"},{"ID":"c660e8c2-f6b5-5740-90e6-922e42f8e194","Path":"F:\
\Docker\\image\\windowsfilter\\8551af26b8d71172c54f5cba4196b7768ce8685764021b2db98c5726a2fe4c15"},{"ID":"964b6599-89bf-5d41-8c3d-0341537324db","Path":
"F:\\Docker\\image\\windowsfilter\\5947d6c2e63c188f16d22f1bcd781650cf452e806452dcdf96063036359f0b31"},{"ID":"792ce3d9-9edd-552c-a79b-2c7a937a6f42","Pa
th":"F:\\Docker\\image\\windowsfilter\\ea8956c19ffb8a9db3889c3fe5f4d050fa477dff478aa9f6d6816689fc018c20"},{"ID":"ac94fa98-f3d8-572f-a662-bedb160ab5e0"
,"Path":"F:\\Docker\\image\\windowsfilter\\846b3a66594c54b459135f7607d657da38e4db30d6588c8d464710e64be561ab"},{"ID":"8da7e439-8542-5ba3-ad96-4e3fadf79
2b8","Path":"F:\\Docker\\image\\windowsfilter\\0c4165025036b9807cbbf2af3096d61eba165259e34ffcafd23c8e8550f582f3"},{"ID":"7ee23809-f2b5-5e31-971c-81358
40cdb75","Path":"F:\\Docker\\image\\windowsfilter\\3c897eecf040b4c53089675b6e6c049f03f15c07c8e6cfd9cbb0d67345be67e6"},{"ID":"5256f79e-7dff-53d2-8727-5
cda003621ac","Path":"F:\\Docker\\image\\windowsfilter\\c8e7722b503ce8045818edbe0275dd9ca1aa84cc3528b905b5f36def89482a0d"},{"ID":"eed669cd-99b2-5245-83
f7-e6cb66e306eb","Path":"F:\\Docker\\image\\windowsfilter\\c7d7702982684793830c54508833881647685cde4a9c1356253378fbd576e1a9"},{"ID":"24d7c79e-23d2-5d4
1-81ab-612362376b23","Path":"F:\\Docker\\image\\windowsfilter\\88057e962f6edfdb8830f0224ba7dd1cc3c0ece2de68e959f3de7b9cf2389f1b"}],"MemoryMaximumInMB"
:4096,"HostName":"MyBizCentralApp","MappedDirectories":[{"HostPath":"c:\\programdata\\navcontainerhelper\\extensions\\mybizcentralapp\\program files",
"ContainerPath":"c:\\navpfiles","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\windows\\system32\\d
rivers\\etc","ContainerPath":"c:\\driversetc","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\progra
mdata\\navcontainerhelper","ContainerPath":"c:\\programdata\\navcontainerhelper","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilit
yVM":false},{"HostPath":"c:\\programdata\\navcontainerhelper\\extensions\\mybizcentralapp\\my","ContainerPath":"c:\\run\\my","ReadOnly":false,"Bandwid
thMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["260fb628-afc6-4761-988f-22c5ff828962"],"HvRuntime":{"Imag
ePath":"F:\\Docker\\image\\windowsfilter\\c7d7702982684793830c54508833881647685cde4a9c1356253378fbd576e1a9\\UtilityVM"},"AllowUnqualifiedDNSQuery":tru
e}).
ExitCode: 125
Commandline: docker run --name MyBizCentralApp --hostname MyBizCentralApp --env auth=Windows --env username="jianze_zeng" --env ExitOnError=N --env lo
cale=en-US --env licenseFile="" --env databaseServer="" --env databaseInstance="" --volume "C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContai
nerHelper" --volume "C:\ProgramData\NavContainerHelper\Extensions\MyBizCentralApp\my:C:\Run\my" --isolation hyperv --restart unless-stopped --memory 4
G --env enableApiServices=Y --env useSSL=N --volume "C:\ProgramData\NavContainerHelper\Extensions\MyBizCentralApp\Program Files:C:\navpfiles" --volume
 "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b16050a5345MgB8AEgAWABCAGcAdwBnAHgASgBkAGkAawBGAHEAUQB2AHgA
ZgA1AHYAYwBaAFEAPQA9AHwAZgBiADIAMABlADIAZgBkADkAYQBmAGMAYwA1ADMANABhADYAOQBhADUAZAAxADAAOQBiADQAYgBkADQAMQA4AGEANwA3ADAAOQAxAGMAYQA5ADEAMAAwADAAMQBjAD
gAYwBlADMAZQA3ADkANwA1AGEANwAyAGMAZgBlADcAZgA= --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y --detach mi
crosoft/bcsandbox:us-ltsc2016
所在位置 C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.1\ContainerHandling\New-NavContainer.ps1:998 字符: 19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by dNsl9r** [comment]
Looks like this one: https://github.com/microsoft/navcontainerhelper/issues/227
