### ISSUE TITLE
Accessing Container from seperate machine

### ISSUE THREAD

**Issue by tawimberly** [microsoft/nav-docker#384]
I do not believe this is a duplication of issue #252  but rather...an extension of it. i am not sure if this is a bug or i have set something up incorrectly. The below function creates a container successfully...and i can ping the ip as well the hostname. We can connect using our domain users as this is setup using gmsa. 

I can connect to this from the Webclient, windows client, and development environment....but not using what NAV THINKS is the correct address.for example, the listing in the "server Instances" of the developer environment  will display container.domain.local which never works while trying to run an object. i have to manually remove the .domain.local portion and then it will connect. This also means that if i already have the client running, i can't run an object after making changes without it opening an entirely new instance of the windows client which is the main frustration. 

`New-NavContainer 
-containerName $ContainerName 
-accept_eula 
-accept_outdated 
-additionalParameters $additionalParameters 
-memoryLimit 12g 
-auth Windows 
-databaseCredential $databasecredential 
-databaseInstance $databaseInstance 
-databaseName $databaseName 
-databaseServer $databaseServer 
-doNotExportObjectsToText 
-imageName microsoft/dynamics-nav:2018-cu4-na 
-updateHosts 
-PublicDnsName $dnsName`

my Additional parameters are listed below. the $dnsName variable  is [containerName].domain.local and i have also tried just using the $ContainerName without domain.local attached to the end.

`$additionalParameters = @("--publish 8080:8080",
"--publish 443:443",
"--publish 7046-7049:7046-7049",
"--env publicFileSharePort=8080",
"--env PublicDnsName=$dnsName",
"--security-opt credentialspec=file://$ContainerName.json",
"--network=tlan"`

if any information about my network (it's a transparent one i believe) setup is needed please let me know. i followed instructions someone posted in either #252 or similar issue report that i can no longer locate.

**Comment by freddydk** [comment]
It would help if you paste the output of new-navcontainer here as well?

**Comment by tawimberly** [comment]
so sorry this took so long @freddydk ! here is the output you requested


`NavContainerHelper is version 0.6.1.0
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 18.09.6
Docker Server Version is 18.09.6
Using image microsoft/dynamics-nav:2018-cu4-na-ltsc2019
Creating Nav container githubtest
Version: 11.0.21441.0-na
Generic Tag: 0.0.9.2
Container OS Version: 10.0.17763.316 (ltsc2019)
Host OS Version: 10.0.17763.529 (ltsc2019)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using hyperv isolation
Creating container githubtest from image microsoft/dynamics-nav:2018-cu4-na-ltsc2019
c89a14b71ddd41491e0909e07713aabf6a8672092258c49b01da7c7eced3eaba
Waiting for container githubtest to be ready
Initializing...
Starting Container
Hostname is githubtest
PublicDnsName is githubtest
Using Windows Authentication
Starting Internet Information Server
Import Encryption Key
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating DotNetCore Web Server Instance
Creating http download site
Creating Windows user tawimberly
Registering event sources
Container IP Address: 192.168.22.78
Container Hostname  : githubtest
Container Dns Name  : githubtest
Web Client          : http://githubtest/NAV/
Dev. Server         : http://githubtest
Dev. ServerInstance : NAV

Files:
http://githubtest:8080/al-0.12.17720.vsix

WARNING: You are running a container which is 113 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 63 seconds
Ready for connections!
Reading CustomSettings.config from githubtest
Creating Desktop Shortcuts for githubtest
Nav container githubtest successfully created
Name            Path                                                 
`

**Comment by freddydk** [comment]
Did you ever manage to make this work?

**Comment by tawimberly** [comment]
Not 100%, no. It “works”, but i have to manually change the service address when running things from the developer. I’m beginning to wonder if this would work on someone else’s domain, and maybe our DC/DNS is set up incorrectly.  

 

Thanks,

 

Taylor Wimberly

The CSG Group, Inc.

770.923.7144

**Comment by freddydk** [comment]
Assuming it was resolved long ago.
