### ISSUE TITLE
BC Sandbox API

### ISSUE THREAD

**Issue by MaxBelohoubek** [microsoft/nav-docker#385]
Hey freddy, don't know if this is the correct repository but I'm a bit confused by the Business Central API(s). So my goal is to deploy configurationPackages in sandbox containers. The microsoft docs only show how to do that with production tenants or demo tenants, not how to do it on docker. Is this by design or have I just not found the documentation I need?

So far I've accomplished to get the companyInformation using this url and basic auth:
https://{myPublishedContainer}:7048/nav/api/v1.0/companyInformation?company=CRONUS DE

To do this I also had to use the actual password of the user, not the Web Service Access Key which intrigued me a little.

I feel like I am doing something very wrong, please let me know if that is the case.

**Comment by henrikwh** [comment]
Hi @MaxBelohoubek 
You can use web service access key for on prem.
GET http://{container}:7048/bc/api/v1.0/$metadata
GET http://{container}:7048/bc/api/v1.0/items
GET http://{container}:7048/bc/api/microsoft/automation/v1.0/$metadata
GET http://{container}:7048/bc/api/microsoft/automation/v1.0/configurationPackages
When prompted for credentials you can use the BC username and web access key. 

If you're just trying through the browser, you could also try a tool like Postman. Choose Basic Auth, use the web access key as password.

/Henrik

**Comment by MaxBelohoubek** [comment]
Hey @henrikwh,
thanks for your help. Now I can get the configurationPackage which is what I need.

The problem I have now is that the WebService Access Key is rejected, no matter which client I use (PowerShell / Postman) to send the request. 
Only using the password for the user (SUPER permissions) is accepted when sending a request with Basic Auth. I also have to specify the company (which is CRONUS DE in my case).

Is this expected behaviour?

**Comment by henrikwh** [comment]
hi @MaxBelohoubek 
No, this is not normal. I think you web access key might be wrong. Please ensure that it ends with an = sign. 
Sometimes the cut&past does not get the full key.

**Comment by MaxBelohoubek** [comment]
It was wrong. Copy&Paste excluded the last character. Thanks so much!
