### ISSUE TITLE
MainLoop.ps1: Possible high CPU Usage due to constant event log check?

### ISSUE THREAD

**Issue by marknitek** [microsoft/nav-docker#386]
### Background
We use a self service portal for spinning up local dev/test containers that are hosted on dedicated docker host machines (windows server 2019).

### Problem
When the Containers run for a long (or not so long) time the event log (application) will be populated with many entries (i had an example with aprox. 7000 entries). 

Due to these entries we saw very high cpu usage on thes docker host that was not entirly clear where they came from. It turned out they came from svchost which in turn was hosting several services which included also the eventlog service (and others: lmhosts, eventlog, dhcp). 
After i had found hints about clearing out the event log here could solve the high cpu usage:
https://social.technet.microsoft.com/Forums/azure/en-US/eee36815-7be8-438b-bd60-8cc809f940ba/svchostexe-lmhosts-eventlog-dhcp-high-cpu-usage?forum=winservergen

I tested it on the host which was at that time running 11 Containers and hat an avg. cpu usage of **80-100%** before the log cleanup.

when i look at `MainLoop.ps1` i see that it constantly looks for event logs in the application log (every 2 seconds). 
=> I think this causes the high cpu usage. 
>I have **not** tested with a custom MainLoop.ps1 if the problem disappears

### Workaround
Then i cleared the logs on every running container with: 
```
docker exec <container> powershell "Clear-EventLog System,Security,Application"
```
After that the cpu usage dropped to around **10%**! 
We could notice the drop to 0% on almost every container when using `docker stats`

### Solution
I know the MainLoop is used to show errors in the docker logs but it is causing very bad performance.

Possible Solutions:
1. Remove the `Get-EventLog`
  =>We will not do this obviously
2. Make an Environment Variable to control if the Get-EventLog will be executed
3. Make an Environment Variable to control the max. Log Length for the EventLog
  https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/limit-eventlog?view=powershell-5.1
  And set the default to something low like 20kb instead of the default 20mb

For me Option 2 would be sufficient.

**Comment by freddydk** [comment]
Thanks for the very detailed problem description.

The mainloop was made this way to allow docker run to show event logs in the display and in docker logs.

I described how to override scripts in this blog post: https://freddysblog.com/2018/03/20/navcontainerhelper-overriding-scripts-in-nav-containers
and the very last section is about mainloop.

If you use the following construct on your new-navcontainer:
-myscripts @(@{"mainloop.ps1" = "start-sleep -seconds 3153600000"})
then you will in fact override mainloop.ps1 and wait for sleep for 100 years.

Considering the performance impact (and that we have other and better ways to check event log today with navcontainerhelper) I might turn the behavior around on new-navcontainer and add a parameter called -doCheckEventLog to enable the old behavior.

**Comment by freddydk** [comment]
Thanks for the very detailed problem description.

The mainloop was made this way to allow docker run to show event logs in the display and in docker logs.

I described how to override scripts in this blog post: https://freddysblog.com/2018/03/20/navcontainerhelper-overriding-scripts-in-nav-containers
and the very last section is about mainloop.
(you shouldn't sleep for 100 years though - then you cannot create a pssession in the container)

If you use the following construct on your new-navcontainer:
`-myscripts @(@{"mainloop.ps1" = 'while ($true) { start-sleep -seconds 1 }'})`
then you will in fact override mainloop.ps1 and sleep for 100 years.

Considering the performance impact (and that we have other and better ways to check event log today with navcontainerhelper) I might turn the behavior around on new-navcontainer and add a parameter called -doCheckEventLog to enable the old behavior.

**Comment by Koubek** [comment]
I can confirm the idea as we overrode also the default behavior because we noticed high CPU usage related to the mainloop.ps1 behavior. 

And the benefits are really significant, especially very welcomed in environments where running containers with high density is a really important factor.

**Comment by freddydk** [comment]
Next NavContainerHelper will introduce a parameter called dumpEventLog, which is required to get the eventlog in the output.

**Comment by freddydk** [comment]
Also next NavContainerHelper will have a parameter called doNotCheckHealth, which will cause the container to always report healthy. This will cause the CPU usage from a container to be at its absolute minimum when not used.

**Comment by marknitek** [comment]
Thats great news.
We already disable healthcheck currently because of the performance impact

**Comment by freddydk** [comment]
https://freddysblog.com/2019/07/06/cpu-usage-in-business-central-containers/

**Comment by marknitek** [comment]
I have some hints about your blogpost
To disable healthcheck `--no-healthcheck` on docker run does the trick.

Unfortunatly healthcheck only realy works with docker swarm as of my knowledge:
https://stackoverflow.com/questions/47088261/restarting-an-unhealthy-docker-container-based-on-healthcheck
So restarting of unhealthy containers is not supported out of the box...

**Comment by freddydk** [comment]
Thanks for the info - I will change the implementation to use --no-healthcheck

**Comment by freddydk** [comment]
Done
