### ISSUE TITLE
Missing 1810-cu9-at-ltsc2019

### ISSUE THREAD

**Issue by PleachiM** [microsoft/nav-docker#387]
Is there a reason that there is no cu9-ltsc2019 for AT?

>     "1810-cu9",
>     "1810-cu9-at",
>     "1810-cu9-at-ltsc2016",
>     "1810-cu9-au",
>     "1810-cu9-au-ltsc2016",
>     "1810-cu9-au-ltsc2019",
>     "1810-cu9-be",
>     "1810-cu9-be-ltsc2016",
>     "1810-cu9-be-ltsc2019",
>     "1810-cu9-ch",
>     "1810-cu9-ch-ltsc2016",
>     "1810-cu9-ch-ltsc2019",
>     "1810-cu9-cz",
>     "1810-cu9-cz-ltsc2016",
>     "1810-cu9-cz-ltsc2019",
>     "1810-cu9-de",
>     "1810-cu9-de-ltsc2016",
>     "1810-cu9-de-ltsc2019",

**Comment by freddydk** [comment]
No, something must have gone wrong in the build process.
Will check

**Comment by freddydk** [comment]
should be there now
