### ISSUE TITLE
OnPrem:CU3-de gets a weird image

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/nav-docker#390]
I've used "mcr.microsoft.com/businesscentral/onprem:cu3-de" because I mistakenly thought BC14 CU3 had already been released. 

When I realised my mistake I thought it was a BC13 (because, you know, CU3 is not available for BC14) container, but instead it gave me "14.1.32615.0-de"

To confuse Things even more, the "download Symbol" gives me differing System & Application alpackages
![image](https://user-images.githubusercontent.com/35929603/61705466-14cff600-ad46-11e9-997d-ddd459b47f72.png)

sames Thing on the Client

![image](https://user-images.githubusercontent.com/35929603/61705521-316c2e00-ad46-11e9-8016-199d06efdd5a.png)

what is Happening here?

**Comment by freddydk** [comment]
this is 1810 cu3 - fall 2018 cu3 - at that time, I had no idea that we would start from scratch at spring 2019...:-(
If you want to be sure, you need 1904-cu3 - but that isn't released yet

**Comment by JulianTillmann** [comment]
that's what I would have thought and one of my colleagues did just get this Image today. 

but I created my container last Friday and got 1904-cu1. Did anybody Change the Definition in the meantime?

**Comment by freddydk** [comment]
Nothing has changed - mcr.microsoft.com/businesscentral/onprem:cu3-de has given the same image for a long time. mcr.microsoft.com/businesscentral/onprem:de would give you cu1 (which is latest today)

**Comment by JulianTillmann** [comment]
hmm okay, then I don't know what happend. 

can you explain the thing with the differing system & application alpackages?

**Comment by freddydk** [comment]
I guess that is just how CU1 looks - if you download the onprem cu1 dvd and install that - you get the same,.

**Comment by JulianTillmann** [comment]
k, thanks
