### ISSUE TITLE
Image nav2018-cu19 not availabe

### ISSUE THREAD

**Issue by mikemsx** [microsoft/nav-docker#391]
Hi,

When will nav2018-cu19 will be available as a docker image?
I'm trying microsoft/dynamics-nav:2018-cu19-de, but it isn't working...

_DockerDo : Error response from daemon: manifest for microsoft/dynamics-nav:2018-cu19 not found: manifest unknown: manifest unknown_

Thanks!

**Comment by freddydk** [comment]
https://freddysblog.com/2019/07/14/nav-and-business-central-docker-images-moved-to-microsoft-container-registry/

**Comment by mikemsx** [comment]
Thank you! I missed this blog post...

**Comment by freddydk** [comment]
No problem - some issues are easier to answer than others...:-)
