### ISSUE TITLE
D365 BC Docker v14.3 - Classic development environment?

### ISSUE THREAD

**Issue by CarlosAndreuLlaneras** [microsoft/nav-docker#392]
Hello everybody,
I am provisioning new dockers in v14.3 for different locations, and these are being created without a classic development environment.
This is a problem in order to check Dynamics 365 Business Central code that has not yet been migrated to AL.

Is it a mistake? Or will the classic development environment never be available again?
Should we select any option in the docker creation template?
Is there any powershell command from the NavHelper to surface the classic development environment?

Thank you

**Comment by freddydk** [comment]
-includeCSIDE will cause the classic development environment to be included (for all containers before 15.x)

**Comment by CarlosAndreuLlaneras** [comment]
Thanks Freddy,
I am using following template to provisioning dockers, but I don't find this parameter.
Until last week, the classic development environment was included with this same template, without selecting that parameter.
Maybe the template has been updated?
Should I edit the template to include a new parameter or it should be applied by default?
http://aka.ms/bcdeveloperpreviewext
Thanks

**Comment by freddydk** [comment]
Ahh - yes, the templates have been cleaned up - I have a blog post coming out today.

use
http://aka.ms/getnav or http://aka.ms/getnavext if you need CSIDE (both for NAV and Business Central CSIDE development)
use
http://aka.ms/getbc and http://aka.ms/getbcext will be Business Central and AL development only

bcdeveloperpreviewext is an "old" shortlink and will point to one of the above (probably getbcext).

Sorry for the confusion.

**Comment by CarlosAndreuLlaneras** [comment]
Thanks Freddy.
I have been able to create new dockers including CSIDE without problems.
