### ISSUE TITLE
downloading symbols

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/nav-docker#393]
I just download the new daily build for fall 2019.  I'm having some issues downloading symbols, it's taking over 30 minutes and still hasn't downloaded.  Is that normal or did I mess something up in my setup?

**Comment by freddydk** [comment]
Definitely not normal
Did you install the new .vsix?
Did you setup the app.json with the right dependencies and platform as described in the blog post?

**Comment by MatthewMcCarthy7** [comment]
Yes installed new .vsix

![image](https://user-images.githubusercontent.com/32099690/62223968-b5d43780-b36a-11e9-9ef0-41824a32945c.png)

Used the dependencies from the base AL:GO Install
![image](https://user-images.githubusercontent.com/32099690/62224064-e4eaa900-b36a-11e9-902c-4a88fba08fa4.png)

**Comment by freddydk** [comment]
and what command did you use to create the container with?

**Comment by MatthewMcCarthy7** [comment]
New-NavContainer -containerName SWBC -accept_eula -auth NavUserPassword -Credential $credential -alwaysPull -includeAL -imageName bcinsider.azurecr.io/bcsandbox-master:us -memoryLimit 8g -licenseFile "C:\License\SWNAVBC.flf" -updateHosts

**Comment by freddydk** [comment]
That should just work - and definitely not take long.

**Comment by MatthewMcCarthy7** [comment]
Should I remove the image and download it again?

**Comment by MatthewMcCarthy7** [comment]
I Deleted the images and redownloaded it and having the same issue

**Comment by MatthewMcCarthy7** [comment]
Got it working.  I was missing the forward slash after the server name

Before "server": "http://SWBC",
After "server": "http://SWBC/",

**Comment by freddydk** [comment]
Thanks a million for this info - pretty sure I will see that again...
