### ISSUE TITLE
Wave 2 preview Invoke-NAVDatabaseConversion

### ISSUE THREAD

**Issue by tfenster** [microsoft/nav-docker#394]
Hello,

I tried to call Invoke-NAVDatabaseConversion on the latest insider image but this leads to the following error:

The term 'Invoke-NAVDatabaseConversion' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Image labels
"osversion": "10.0.14393.3085",
"platform": "15.0.34689.0",
"tag": "0.0.9.91",
"version": "15.0.34731.0"

Repro steps:
1. `docker run -e accept_eula=y --name tst bcinsider.azurecr.io/bcsandbox-master:w1` and wait until it is ready
2. `docker exec -ti tst powershell -noexit c:\run\prompt.ps1`
3. `Invoke-NAVDatabaseConversion`

Result:
```Invoke-NAVDatabaseConversion : The term 'Invoke-NAVDatabaseConversion' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was      included, verify that the path is correct and try again.                                                                                                                                                            At line:1 char:1                                                                                                                                                                                                    + Invoke-NAVDatabaseConversion                                                                                                                                                                                      + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                          + CategoryInfo          : ObjectNotFound: (Invoke-NAVDatabaseConversion:String) [], CommandNotFoundException                                                                                                        + FullyQualifiedErrorId : CommandNotFoundException```

Expected result:
cmdlet works

Is that by design or is something wrong in the image?

**Comment by Koubek** [comment]
Hi @tfenster!!! Maybe the modules are not there - it's IDE module. So maybe it's due to changes related to RTC removal. My estimation but maybe I am wrong. I haven't been testing the new version yet ;)

**Comment by freddydk** [comment]
Modules are not there.
finsql is still used, but the PowerShell modules was removed - these are the things we are working on replacing.
In setupDatabase I use: 
Start-Process -FilePath "$roleTailoredClientFolder\finsql.exe" -ArgumentList "Command=upgradedatabase, Database=$databaseName, ServerName=$databaseServerInstance, ntauthentication=1, logFile=c:\run\errorlog.txt" -Wait
That will still work, but break as soon as they remove this.
When they remove finsql, I expect there will be a different solution.

**Comment by tfenster** [comment]
@Koubek @freddydk thanks!
