### ISSUE TITLE
While calling API getting error msg

### ISSUE THREAD

**Issue by jyotivarade** [microsoft/nav-docker#397]
![image](https://user-images.githubusercontent.com/50901499/63002861-89eda180-be94-11e9-9a2a-728832bad404.png)

  begin
        ReadLicencesdetails();
        RequestMessage.SetRequestUri(url);
        RequestMessage.Method := 'POST';
        BodyParameter := ('{' +
            '"headerParam": {' +
            '"user_Key": "' + User_Key + '",' +
            '"license_key":"' + license_key + '"' +
           ' },' +
            '"state": "' + State + '",' +
            '"methodName": "GetAllInventoryTransfer",' +
            '"methodType": "GET"' +
     
        ' }');
        HttpContent.WriteFrom(BodyParameter);
        RequestMessage.Content(HttpContent);
        HttpClient.Send(RequestMessage, ResponseMessage);
        HttpContent := ResponseMessage.Content;
        HttpContent.ReadAs(ResponseInReadibleFormat);
        if ResponseInReadibleFormat = '{"Response":"Success"}' then begin
        end;

**Comment by freddydk** [comment]
@henrikwh - can you see anything from the above?
I cannot imagine that this is related to docker.
