### ISSUE TITLE
How to display info?

### ISSUE THREAD

**Issue by dkorinets** [Microsoft/nav-docker#40]
How to display info about again: 

NAV Admin Username  : ???
NAV Admin Password  : ???
Container IP Address: ??
Container Hostname  : ???
Web Client          : ???
Dev. Server         : ???
Dev. ServerInstance : ???

Files:
?????
?????http://4d6047c27961:8080/certificate.cer

**Comment by freddydk** [comment]
You cannot get the container to display these things again.
Typically you have given these things to docker as parameters, so the display is only for convenience if you didn't give the parameter.

you can see container IP address and hostname with docker ps
dev. server is http://hostname (or https depending on whether or not you use SSL)
dev. server instance is always NAV
files can be viewed by opening http://hostname:8080

**Comment by ajkauffmann** [comment]
try `docker logs <container id>`

At least this works then you start the container with -d parameter, don't know if it works when you start it without -d.

**Comment by Koubek** [comment]
Yes, this one works always and you can see all data being logged.

**Comment by dkorinets** [comment]
Sorry for maybe obvious questions, but I'm new in docker.
Thank You all guys.
