### ISSUE TITLE
After Creating container it is working 2 or 3 days then web client is not working so we have to again create container 

### ISSUE THREAD

**Issue by jyotivarade** [microsoft/nav-docker#401]

**Comment by freddydk** [comment]
Please provide more information. At least:
- How do you create the container (command)?
- Full output from the command above?
- What happens after 2-3 days?
- What does docker ps -a say - is the container still running?

**Comment by freddydk** [comment]
Please reopen with more information if the issue needs attention.

**Comment by GaneshVarahade** [comment]
**How do you create the container (command)?**
using following command i am creating container and using 'Windows Powershell ISE' as Administrator.
New-NavContainer -accept_eula -ACCEPT_OUTDATED -containerName GFMMDN -imageName microsoft/bcsandbox:us -includeCSide -doNotExportObjectsToText -auth NavUserPassword

**Full output from the command above?**
PS C:\Windows\system32> New-NavContainer -accept_eula -ACCEPT_OUTDATED -containerName GFMMDN -imageName microsoft/bcsandbox:us -includeCSide -doNotExportObjectsToText -auth NavUserPassword
NavContainerHelper is version 0.6.2.91
Host is Microsoft Windows 10 Pro - 1703
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Using image microsoft/bcsandbox:us-ltsc2016
Removing C:\ProgramData\NavContainerHelper\Extensions\GFMMDN
Creating Container GFMMDN
Version: 14.0.29537.31808-US
Platform: 14.0.29530.31705
Generic Tag: 0.0.9.6
Container OS Version: 10.0.14393.2906 (ltsc2016)
Host OS Version: 10.0.15063.1418 (1703)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-US
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\GFMMDN\my:
- AdditionalSetup.ps1
- MainLoop.ps1
Creating container GFMMDN from image microsoft/bcsandbox:us-ltsc2016
661aab4ac8d610d8be6f269e71f6ef7f6b235aef1f86305a27fc27d4d3252c92
Waiting for container GFMMDN to be ready
Initializing...
Starting Container
Hostname is GFMMDN
PublicDnsName is GFMMDN
WARNING: DNS resolution not working from within the container.
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 4990E9A853CF5F3007FAEC8B6E7AB4E322017B42
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements. 
It should be at least 8 characters long and contain at least one uppercase 
letter, one lowercase letter, and one number.
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Container IP Address: 172.24.229.36
Container Hostname  : GFMMDN
Container Dns Name  : GFMMDN
Web Client          : http://GFMMDN/NAV/
Dev. Server         : http://GFMMDN
Dev. ServerInstance : NAV

Files:
http://GFMMDN:8080/al-3.0.106655.vsix

WARNING: You are running a container which is 122 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 436 seconds
Ready for connections!
Reading CustomSettings.config from GFMMDN
Creating Desktop Shortcuts for GFMMDN
Container GFMMDN successfully created

**What happens after 2-3 days?**
Web client is not working  and getting mesg **The program could not create a connection to the server. Do you want to try again**

**What does docker ps -a say - is the container still running?**
container is not running.
**docker ps -a** 
faa7a79d7f00        microsoft/bcsandbox:us-ltsc2016                    "powershell -Commandâ€¦"   2 days ago          Up 2 days (unhealthy)             80/tcp, 443/tcp, 1433/tcp, 7045-7049/tcp, 8080/tcp   
GFMMDJ
60acfe4ef80b        microsoft/bcsandbox:us-ltsc2016                    "powershell -Commandâ€¦"   3 days ago          Exited (4294967295) 3 days ago                                                         
GFMMDN

**Comment by freddydk** [comment]
Thanks, and if you start the container again, using: docker start GFMMDN
Does it start up working again?

BTW Maybe you need to add -updatehosts to your new-navcontainer

**Comment by GaneshVarahade** [comment]
Yes, now it is working but after 3 and 4 days it is giving  this  error msg "The program could not create a connection to the server. Do you want to try again" .

**Comment by freddydk** [comment]
It is probably because your computer has restarted and docker doesn't start your containers automatically (I think there is a bug in Docker around this).
Until that is fixed, you would have to start your containers manually again.
Note that you want to avoid the version here: https://freddysblog.com/2019/08/07/zombie-containers-skip-this-build/ which tries to fix that problem, but makes zombie containers out of the containers.

**Comment by GaneshVarahade** [comment]
Thanks for update, I will start containers manually before running web client.

**Comment by GaneshVarahade** [comment]
Thanks for update, I will start containers manually before running web client.
