### ISSUE TITLE
NavContainer can't connect to database in another container

### ISSUE THREAD

**Issue by krregg** [microsoft/nav-docker#402]
Hi, 

I am writing build script and I want to have two containers, one for Navision and one for SQL server.
When I want to build my solution I would like to create container with SQL server, where I restore my .bak file. Then I want to create Navision container using command New-NavContainer and parameters to connect to another container database.

My problem is that the connection from NAV Container can't be establish. I was also reading this blog: [https://blogs.msdn.microsoft.com/freddyk/2018/03/20/navcontainerhelper-use-an-external-sql-server-as-database-connection-in-a-nav-container/](https://blogs.msdn.microsoft.com/freddyk/2018/03/20/navcontainerhelper-use-an-external-sql-server-as-database-connection-in-a-nav-container/) and I though I can come trough, but I can't.

When running New-NavContainer I get error:

```
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 126
at <ScriptBlock>, C:\Run\navstart.ps1: line 113
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
```

If I try to connect to database trough SQL Manag. Studio the connection works. Container is also running and it's healthy. The restore of my bak file is successful also.

I used these additional parameters when running New-NavContainer (as described in Freddy's blog):

```
-databaseServer mySqlServer`
-databaseName myDatabase `
-databaseCredential $databaseCredential
```
"mySqlServer" is acctual name of the container which is running SQL server.
"myDatabase " is acctual name of the database on SQL server.

Here blow is my whole script. It creates SQL server and try to make Nav Container but it fails.

Can anyone please help me to set parameters for New-NavContainer to connect to external database? 

What is about permissions, what can I do with that?

```
##########################   SQL Server Container      ##############################

# create sql server
Write-Host "Creating SQL Server..."

$hostFolder = "c:\temp\navdbfiles"
$databaseCredential = New-Object System.Management.Automation.PSCredential -argumentList "sa", (ConvertTo-SecureString -String "P@ssword1" -AsPlainText -Force)
$dbPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($databaseCredential.Password))
Write-Host "Preparing container for SQL Server..."

$dbserverid = docker run --name mySqlServer-d -e sa_password="$dbPassword" -p 3306 -e ACCEPT_EULA=Y -v "${hostFolder}:C:/temp" microsoft/mssql-server-windows-developer

$containerid = docker inspect -f '{{.Name}}' mySqlServer
Write-Host "Container ID: " $containerid

$databaseServer = $dbserverid.SubString(0,12)
Write-Host "Database Server: " $containerid

$databaseInstance = ""

# stop container
Write-Host "Stopping container MySqlBrother..."
docker container stop mySqlServer

# copy files to container
Write-Host "Copying .bak file to container mySqlServer..."
docker cp 'C:\temp\navdbfiles\BC-maia365-D0-2019-07-30.bak' $containerid':C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\Backup\backup.bak'

# start container
Write-Host "Starting container MySqlBrother..."
docker container start mySqlServer

$containerIp = docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mySqlServer
Write-Host "Container IP: " $containerIp

# restore database
$databaseName2 = "myDatabase"
$databaseServerInstance = @{ $true = "$databaseServer\$databaseInstance"; $false = "$databaseServer"}["$databaseInstance" -ne ""]
Write-Host "Preparing files for database..."
$RelocateData = New-Object Microsoft.SqlServer.Management.Smo.RelocateFile("DemoDatabaseNAV14_New_Data", "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\${databaseName2}_Data.mdf")
$RelocateLog = New-Object Microsoft.SqlServer.Management.Smo.RelocateFile("DemoDatabaseNAV14_New_Log", "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\${databaseName2}_Log.ldf")

Write-Host "Restoring database..."
Restore-SqlDatabase -ServerInstance $databaseServerInstance -Database $databaseName2 -Credential $databaseCredential -RelocateFile @($RelocateData,$RelocateLog)

Write-Host "Container with SQL Server and restored database is prepared."

##########################   NAV Container      ##############################

Write-Host "Loading NavContainerHelper..."
Import-Module "C:\Program Files (x86)\Microsoft Dynamics 365 Business Central\140\RoleTailored Client\Microsoft.Dynamics.Nav.Model.Tools.psd1" -force
Import-Module -name "C:\Program Files\Microsoft Dynamics 365 Business Central\140\Service\NavAdminTool.ps1"
cls 

Write-Host "Creating NAV Container with connection to external database..."
New-NavContainer -containerName myNavContainer `
                 -imageName mcr.microsoft.com/businesscentral/onprem:w1 `
                 -auth Windows `
                 -accept_eula  `
                 -updateHosts `
                 -memoryLimit 5G `
                 -useSSL `
                 -includeCSide `
                 -doNotExportObjectsToText `
                 -enableSymbolLoading `
                 -shortcuts $shortcuts `
                 -licenseFile 'C:\Users\gregor.soln\Documents\AL Extra\licence for NAV DEVEL\6866676-20190625.FLF' `
                 -databaseServer mySqlServer  `
                 -databaseName $databaseName2  `
                 -databaseCredential $databaseCredential
```

**Comment by freddydk** [comment]
And do you have the output of this script as well?
If looks like your database container is called mysqlserver-d (space missing)
You might also have to specify database instance (default database instance is SQLEXPRESS and the sql server developer is MSSQLSERVER I think)

**Comment by krregg** [comment]
Hi, thank you for your answer. 

The container named called 'mysqlserver-d' is my copy-paste mistake, '-d' should be a parameter, so this part is OK. 

I set the additional parameter for NAV container, -databaseInstance as 'MSSQLSERVER', and for -databaseServer I set container IP. Creation of NAV container Will fail. And this is the output (before it fails the script is stopped for a long time on step "Import Encryption Key":

```
Creating SQL Server...
Preparing container for SQL Server...
Container ID:  /mySqlServer
Database Server:  /mySqlServer
Stopping container mySqlServer...
mySqlServer
Copying .bak file to container mySqlServer...
Starting container mySqlServer...
mySqlServer
Container IP:  172.29.166.16
Preparing files for database...
Restoring database...
Container with SQL Server and restored database is prepared.
Loading NavContainerHelper...
WARNING: The names of some imported commands from the module 'Microsoft.Dynamics.Nav.Model.Tools' inc
lude unapproved verbs that might make them less discoverable. To find the commands with unapproved ve
rbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, ty
pe Get-Verb.
Creating NAV Container with connection to external database...
NavContainerHelper is version 0.6.2.95
Host is Microsoft Windows 10 Enterprise - 1803
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Using image mcr.microsoft.com/businesscentral/onprem:w1-ltsc2016
Removing MainApp from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\MainApp
Creating Container MainApp
Using license file C:\Users\gregor.soln\Documents\AL Extra\licence for NAV DEVEL\6866676-20190625-Mai
a365-Dev_LS_2.FLF
Version: 14.3.34444.0-W1
Platform: 14.0.34251.0
Generic Tag: 0.0.9.9
Container OS Version: 10.0.14393.3025 (ltsc2016)
Host OS Version: 10.0.17134.885 (1803)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-US
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\MainApp\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- updatehosts.ps1
Creating container MainApp from image mcr.microsoft.com/businesscentral/onprem:w1-ltsc2016
65c56baeaf316f48f3eafc31312fd190d3a2a45f18551fd504debe437ffa1389
Waiting for container MainApp to be ready
Initializing...
Starting Container
Hostname is MainApp
PublicDnsName is MainApp
Using Windows Authentication
Starting Internet Information Server
Import Encryption Key
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 126
at <ScriptBlock>, C:\Run\navstart.ps1: line 113
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is MainApp
PublicDnsName is MainApp
Using Windows Authentication
Starting Internet Information Server
Import Encryption Key
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 126
at <ScriptBlock>, C:\Run\navstart.ps1: line 113
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container MainApp failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.95\ContainerHandling\Wait-Nav
ContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ... MainApp failed:String) [], Runt 
   imeException
    + FullyQualifiedErrorId : Initialization of container MainApp failed
```

Connection to SSMS works trough the IP, so even if I use IP for -databaseServer for NAV Container it doesn't work. I am not sure anymore what am I missing. So, for example, my latest version of command for NAV container is:

```
$databaseCredential = New-Object System.Management.Automation.PSCredential -argumentList "sa", (ConvertTo-SecureString -String "P@ssword1" -AsPlainText -Force)
$dbPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($databaseCredential.Password))

New-NavContainer -containerName MainApp `
                 -imageName mcr.microsoft.com/businesscentral/onprem:w1 `
                 -auth Windows `
                 -accept_eula  `
                 -updateHosts `
                 -memoryLimit 5G `
                 -useSSL `
                 -includeCSide `
                 -doNotExportObjectsToText `
                 -enableSymbolLoading `
                 -licenseFile 'C:\Users\gregor.soln\Documents\AL Extra\licence for NAV DEVEL\6866676-20190625.FLF' `
                 -databaseServer 172.29.166.37 ` # container IP adderess
                 -databaseName myDatabaseName ` # the name is real
                 -databaseInstance MSSQLSERVER ` 
                 -databaseCredential $databaseCredential
```

Output for $databaseCredential is:
```
PS C:\WINDOWS\system32> $databaseCredential

UserName                     Password
--------                     --------
sa       System.Security.SecureString
```
Password for db works when connecting through SSMS.

**Comment by marknitek** [comment]
I had similar issues multiple times. 
If it hangs while importing encryption key its mostly a network error.
Use Enter-navcontainer and test the connection to your sql server instance. If you cant query "select name from sys.databases" then no connection is possible from the nav container to sql server. ( use invoke-sqlcmd to check)


Use ip address instead of hostname for the sql server.
I use sql server on the host instead of in a container. I needed to ad firewall rules for instance and sql browser and sometimes tcp protocol was not enabled for the instance.

**Comment by krregg** [comment]
@marknitek thank you for your answer! I have to say that I managed to establish a connection so it works, just wanted to reply and I saw your message. :)

But now I have another weird problem. When creating New-NavContainer I get an error:

> The XXXXXXX database on the 978387A91834 server must be converted by Microsoft Dynamics NAV Development Environment before you can use it with this version of Dynamics 365 Business Central.

It is strange to me because the database is taken from the same version that I am installing (version 14). So my container has this information:

> Platform: 14.0.34251.0
> Generic Tag: 0.0.9.9
> Container OS Version: 10.0.14393.3025 (ltsc2016)
> Host OS Version: 10.0.17134.885 (1803)

I am using image: mcr.microsoft.com/businesscentral/onprem:ltsc2016

If I try to use image mcr.microsoft.com/businesscentral/onprem:ltsc2019 I get this error:
> DockerDo : a Windows version 10.0.17763-based image is incompatible with a 10.0.17134 host

Any ideas what to do with the database? @freddydk any idea? :)

**Comment by freddydk** [comment]
ltsc2016 is windows server 2016
ltsc2019 is windows server 2019
you cannot run windows server 2019 images on windows 10 earlier then 1809 - that's the reason for that error.
The error you get is due to a database version number mismatch, meaning that database must be from a different version of NAV - all numbers in the version number counts.

**Comment by krregg** [comment]
I realized that about image versions. 

I am kinda stuck now with this database. Is there any option to force converting the database?

I also tried to run command New-NAVContainer where I use the parameter -bakFile, but I get errors and container fails every time. I used this command:

```
New-NavContainer -accept_eula `
                 -imageName mcr.microsoft.com/businesscentral/onprem:ltsc2016 `
                 -containerName MainNavApp `
                 -Auth NavUserPassword `
                 -Credential $navcredential `
                 -isolation hyperv `
                 -myScripts @("C:\temp\navdbfiles\backup.bak") `
                 -additionalParameters @('--env bakfile="c:\run\my\backup.bak"') `
                 -clickonce
```

AFter a while I get this as error:

```
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\navstart.ps1: line 179
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container MainNavApp failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.95\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...inNavApp failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container MainNavApp failed
```

If I run New-NAVContainer without -bakFile then the creation of container works well. I am not sure why am I getting this error as well.

**Comment by freddydk** [comment]
You can force convert the database with CSIDE - create a container with -includecside (and maybe -donotexportobjectstotext), open CSIDE and connect to the database.
It is the same with the .BAK file - it restores the database and tries to start with that.
If you use Get-NavContainerEventLog to extract the eventlog from the container you will probably see that that is the same.

**Comment by krregg** [comment]
Thank you @freddydk, I know this and this doesn't help me much. I want an automated process to build containers, install the app, test and remove containers. Converting database doesn't work for me.

Then I found this: New-BCContainer, honestly I didn't know that exist and I tried it as creating new BC container which will be connected to another external DB from another container, same as before.

If before when I used New-NAVContainer I got an error to convert database, now when I use New-BCCContainer the connection doesn't work anymore. Same error:

```
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.
```

I have a feeling I should use New-BCContainer because I am working with Business Central on-prem. Am I right? 

Are there any other special parameters for New-BCContainer in comparison with New-NAVContainer for connection to external DB? I guess it should work very similar but I have problems. This is my code for container:

```
$navcredential = New-Object System.Management.Automation.PSCredential -argumentList "admin", (ConvertTo-SecureString -String "P@ssword1" -AsPlainText -Force)
New-BCContainer -accept_eula `
                 -imageName mcr.microsoft.com/businesscentral/onprem:ltsc2016 `
                 -containerName MainNavApp `
                 -clickonce `
                 -Auth NavUserPassword `
                 -Credential $navcredential `
                 -isolation hyperv `
                 -licenseFile "C:\Users\gregor.soln\Documents\AL Extra\licence for NAV DEVEL\6866676-20190625-Maia365-Dev_LS_2.FLF"  `
                 -databaseServer 172.29.169.208 `
                 -databaseInstance MSSQLSERVER `
                 -databaseName BC-maia365-D0-2019-07-30 `
                 -databaseCredential $databaseCredential
```

**Comment by freddydk** [comment]
New-BCContainer is an alias for New-NavContainer - no change in functionality.
The issue is likely that you cannot make a technical upgrade if there are apps installed in the database.
These apps needs to be rolled off, upgraded and then back on.
I am working on a blogpost and a script, which can do this - but this might take a few weeks before I am done with that.

**Comment by krregg** [comment]
Thank you for that info, I will take some time to read more about it, because before I didn't have enough time.

I think I realized now, I took a new copy of the database which doesn't have any extensions installed yet (I uninstalled everything before). I used New-NAVContainer with parameters to copy the .bak file directly to the container. After that, I did Shema Sync and it worked. 

I knew that converting the database is possible only without extensions but in my case, the database was already converted to the newer version (I am working on the latest version of BC), that is why I was confused when it said that it needs to be converted. 

This is the code I used to do all that I need (to prepare a container with my own database):

```
New-NAVContainer -accept_eula `
                 -imageName mcr.microsoft.com/businesscentral/onprem:ltsc2016 `
                 -containerName NavApp `
                 -clickonce `
                 -Auth NavUserPassword `
                 -Credential $navcredential `
                 -isolation hyperv `
                 -licenseFile "C:\licence for NAV DEVEL\6866676-20190625.FLF"  `
                 -myScripts @("c:\temp\navdbfiles\backup.bak") `
                 -additionalParameters @('--env bakfile="c:\run\my\backup.bak"')

Invoke-ScriptInNavContainer -containerName NavApp -ScriptBlock {        
    Get-NAVTenant NAV | Sync-NavTenant -Mode Sync -Force 
}
```

This will work for me now and my build script I am preparing. But I have to say it took me forever today to solve this situation. (Monday) :)

Thank you for your help & patience, @freddydk

**Comment by marioolleshi** [comment]
This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 152
at <ScriptBlock>, C:\Run\navstart.ps1: line 138
at <ScriptBlock>, C:\Run\start.ps1: line 377
at <ScriptBlock>, <No file>: line 1
New-BcContainer Telemetry Correlation Id: d243fbac-7d2b-49d7-a04a-b44e09695038
Initialization of container ff failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.12\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container ff failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container ff failed

can you help me to solve this problem ?
