### ISSUE TITLE
Determine Compatible Sandbox Image Database Version

### ISSUE THREAD

**Issue by paulditerwich** [microsoft/nav-docker#403]
Is it possible to determine the compatible database version for a sandbox image? Our development partner provided a backup with DB version 1250 - 13.0.26556 (Cumulative Update 02 for Microsoft Dynamics 365 Business Central). Is there a way to determine the compatible sandbox image from Docker? (Provided there is one).

**Comment by paulditerwich** [comment]
We'll try to build a container with New-NavContainer using the provided DVD and DB backup.

**Comment by freddydk** [comment]
Yes, if you have the DVD that would be an easy approach.

**Comment by paulditerwich** [comment]
FYI -> Adding -navDvdPath and -UseBestContainerOS worked like a charm to build the dev container. You're legend @freddydk
