### ISSUE TITLE
BC Application objects compile doesn't work well after importing changed objects

### ISSUE THREAD

**Issue by krregg** [microsoft/nav-docker#404]
I have a case where I create a docker container with image for Business Central. When I create container I pass parameters to use existing database .bak file to restore it. This is the code for my container:

```
$myCoulture = Get-Culture
$myCoulture = $myCoulture.Name
$myscripts = @("c:\temp\navdbfiles\backup.bak")
$additionalParameters = @("--env bakfile=""c:\run\my\backup.bak""", "-e locale=""$($myCoulture)""")

New-NAVContainer -accept_eula `
                 -imageName mcr.microsoft.com/businesscentral/onprem:latest-ltsc2016 `
                 -containerName MainNavApp `
                 -clickonce `
                 -memoryLimit 5G `
                 -alwaysPull `
                 -includeCSide `
                 -Auth NavUserPassword `
                 -Credential $navcredential `
                 -isolation hyperv `
                 -licenseFile "C:\temp\6866676-20190625.FLF"  `
                 -myScripts $myscripts `
                 -additionalParameters $additionalParameters
```

After restoring the database in container I do NAV Tenant Sync, with code:

```
$containerName = "MainNavApp"
Invoke-ScriptInNavContainer -containerName $containerName -ScriptBlock {        
    Get-NAVTenant NAV | Sync-NavTenant -Mode Sync -Force 
}
```

At this point, container works as expected. 

Also, at this point I try to import changed .cal objects using command:

`Import-ObjectsToNavContainer -containerName $containerName -objectsFile $changedObjectsPath1 -sqlCredential $credential`

Import works well also. 

After that If I want to publish app to container I need to generate symbols and compile all application objects, I use this command: 

```
$Session = Get-NavContainerSession -containerName MainNavApp
Invoke-Command -Session $Session -ScriptBlock {
Compile-NAVApplicationObject -DatabaseName mydatabase -DatabaseServer MainNavApp\SQLEXPRESS -Recompile -SynchronizeSchemaChanges Force -GenerateSymbolReference
}
```

But here is where the code breaks. After a while I get the next error:

```
: [23462397] You have specified an unknown variable.
GetUserRoles
Define the variable under 'Global C/AL symbols'. -- Object: Codeunit 9010 Azure AD User Management.GetGraphUserPlans line 16
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Compile-NAVApplicationObject
    + PSComputerName        : 511b39edcb6a09ae3039c1bb6eb0b154290bbf20c48f07d5b9832f4dfe875ee2
```

This error at compile application objects happens only if I import objects before compiling. 

I made research what doest that error mean and on MS page it says:
link: [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/resolve-compile-errors-when-converting-dynamics-nav-2018-database](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/resolve-compile-errors-when-converting-dynamics-nav-2018-database)

The resolution of these problems is also mentioned here: [https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/resolve-cu-9010-error-converting-database](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/resolve-cu-9010-error-converting-database)

I tried to do as it says but no different result. I tried because I have no idea anymore what to do in that case and why that happens. I also read that when you choose to use your own database for NAV container some converting happens on the database as well. 

- This behavior is possible only in the container. 
- If I try to repeat that on a local installation of BC it works without any errors like that. 
- I also tried to import changed objects to the container using CSide and perform a compile, I got the same error as mentioned above.

Did anyone had similar situation wtih Business Central and Docker?

**Comment by freddydk** [comment]
If you open CSIDE and try to compile codeunit 9010 - what happens then?

There is probably no way, where I can reproduce the error without a .bak file and a .fob file which shows the error.

**Comment by krregg** [comment]
It happens the same if I try to compile in CSIDE, I get an error: "Define the variable under 'Global C/AL symbols'. Object: Codeunit 9010 Azure."

I tried to use CRONUS database demo, I imported changed .fob and the compile worked well in this case.

I have no idea what could be wrong with the database in my case. Also, I didn't work much on the actual database yet because it's still in the development process. There are few (5) companies on it already some setup and not much data at all. The only modification I did is on records ID 7002 and 7004 which I am trying to import and compile after. But as I said if I use CRONUS and if I import these two records and recompile I get no error.

I can't get any idea what else I could check...

**Comment by freddydk** [comment]
I don't think this has anything to do with docker.
If I am to help troubleshoot this, I would need the database bak file and the exact steps you use to reproduce the issue.

**Comment by krregg** [comment]
I think something happens with the database after import. Maybe converting? How can I check this what happens to the database? 

Here on this link, I can't find anything about that: [https://blogs.msdn.microsoft.com/freddyk/2018/03/20/navcontainerhelper-specify-your-own-database-backup-file-to-use-with-a-nav-container/](https://blogs.msdn.microsoft.com/freddyk/2018/03/20/navcontainerhelper-specify-your-own-database-backup-file-to-use-with-a-nav-container/)

I think it has to be something with the version of the database and image I am using in container regarding the actual database and Business Central. 

I have to check with my people how much I can share the database.

**Comment by freddydk** [comment]
When using a .bak file - this happens:

        New-NAVDatabase -DatabaseServer $databaseServer `
                        -DatabaseInstance $databaseInstance `
                        -DatabaseName "$databaseName" `
                        -FilePath "$databaseFile" `
                        -DestinationPath "$databaseFolder" `
                        -Timeout $SqlTimeout | Out-Null
        Start-Process -FilePath "$roleTailoredClientFolder\finsql.exe" -ArgumentList "Command=upgradedatabase, Database=$databaseName, ServerName=$databaseServerInstance, ntauthentication=1, logFile=c:\run\errorlog.txt" -Wait

so yes, the upgrade is run.

You can also decide to override setupdatabase.ps1 and write your own New-NavDatabase with your shared .bak file.
Remember when overriding to check whether the container is restarting.

**Comment by freddydk** [comment]
You can see the original setupdatabase.ps1 here: https://github.com/microsoft/nav-docker/blob/master/generic/Run/SetupDatabase.ps1
basically, save the PS script (as SetupDatabase.ps1) - modify it - and specify the file as -myscript @("c:\mypath\setupdatabase.ps1")

**Comment by krregg** [comment]
That doesn't help, your script works well as it is. I tried to use image mcr.microsoft.com/businesscentral/sandbox and now it works as expected. No problem while compiling.


I am not sure if I understand it right. I used image mcr.microsoft.com/businesscentral/onprem because in my case we are using on-prem version of BC. But now for my build solution I have to use sandbox version? I have to read about that all over again…

**Comment by freddydk** [comment]
the only difference between sandbox and onprem containers is the database  and if you are overriding that, there shouldn't be a difference.

**Comment by krregg** [comment]
I noticed something and I don't have an explanation. When I run script `scripts/Create-Container.ps1` (your script for BC build pipeline) from TFS trough Build Pipeline, the content in container folder (C:\ProgramData\NavContainerHelper\Extensions\myApp\) is different if I run this script from local PowerShell.

If I run the script from TFS, there is only one folder `\my\` in `C:\ProgramData\NavContainerHelper\Extensions\myApp\`. 

If I run the script locally, there are two folder `\my\` and `\Program Files\`

In both cases I run this part of the code:

```
New-NavContainer @parameters `
                 -containerName $containerName `
                 -imageName $imageversion.containerImage `
                 -auth NAVUserPassword `
                 -Credential $credential `
                 -accept_outdated `
                 -updateHosts `
                 -memoryLimit 6G `
                 -useSSL `
                 -doNotExportObjectsToText `
                 -enableSymbolLoading `
                 -shortcuts $shortcuts `
                 -licenseFile $licenseFile `
                 -additionalParameters $additionalParameters `
                 -myScripts $myscripts
```

Why folder `\Program Files\` is missing?

**Comment by freddydk** [comment]
program files will only be created if you use -includeCSIDE (where you share C/SIDE and Windows Client from the folder to the host)

**Comment by krregg** [comment]
Ok that could be, yes. Anyway I solved the case, when I choose container image with the same version as we are developing on, it works all well and no issues.

This is my solution: `"containerImage": "mcr.microsoft.com/businesscentral/onprem:14.0.29537.0",`
