### ISSUE TITLE
Initialization of container failed

### ISSUE THREAD

**Issue by prat1800** [microsoft/nav-docker#405]
I am running the following script  in Powershell 

_New-NavContainer -accept_eula -accept_outdated -containerName NAVDEMO -useGenericImage mcr.microsoft.com/dynamicsnav:generic-ltsc2016 -licenseFile C:\temp\MyLic.flf -isolation hyperv -includeAL -useBestContainerOS -auth Windows_

However, I run into this error everytime i have tried creating a new nav container:
_Initialization of container NAVDEMO failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.3.3\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ... throw "Initialization of container $containerName failed" ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : OperationStopped: (Initialization ... NAVDEMO failed:String) [], RuntimeException
+ FullyQualifiedErrorId : Initialization of container NAVDEMO failed_

More details If this could help:
![1](https://user-images.githubusercontent.com/28594745/64101138-7afc5f80-cd6d-11e9-8e11-d77f3342cf49.png)

![2](https://user-images.githubusercontent.com/28594745/64101230-a8e1a400-cd6d-11e9-8836-166d05571e63.png)

Any kind Help/Suggestions ??

**Comment by freddydk** [comment]
The command above is running the generic image - not a specific image, meaning that you would need to specify a DVD folder in order for it to work.
If you are trying to run a specific image, then this blog post: https://freddysblog.com/2019/08/20/business-central-on-docker-for-non-experts/
takes you through the basics.

**Comment by prat1800** [comment]
Thanks Freddy! But my original code was without -usegenericimage tag. i used it coz I was browsing one of the threads that mentioned the same error and saw this as a suggested solution. Earlier I used the normal code with -image for eg: New-NAVContainer -accept_eula -accept_outdated -updateHosts -containerName BCDemo -imageName 'mcr.microsoft.com/businesscentral/sandbox:ltsc2016' -licenseFile 'C:\MyLic.flf' -isolation hyperv -auth Windows

However, with -imagename also it ends up in the same error unfortunately...

**Comment by freddydk** [comment]
Run this:

New-BCContainer -accept_eula -containerName 'bcdemo'

and display the full output here

**Comment by prat1800** [comment]
PS C:\Windows\system32> #Import-Module navcontainerhelper -force
New-BCContainer -accept_eula -containerName 'bcdemo'
NavContainerHelper is version 0.6.3.3
Host is Microsoft Windows 10 Pro - 1803
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Pulling image mcr.microsoft.com/businesscentral/onprem:latest-ltsc2016
latest-ltsc2016: Pulling from businesscentral/onprem
Digest: sha256:6a80cd4eb1e775a235f26c08447b8d06e93119b93194daff90477334b47426bb
Using image mcr.microsoft.com/businesscentral/onprem:latest-ltsc2016
Removing container bcdemo
Removing bcdemo from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\bcdemo
Creating Container bcdemo
Version: 14.4.35602.0-W1
Platform: 14.0.35570.0
Generic Tag: 0.0.9.92
Container OS Version: 10.0.14393.3144 (ltsc2016)
Host OS Version: 10.0.17134.950 (1803)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-US
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\bcdemo\my:
- MainLoop.ps1
Creating container bcdemo from image mcr.microsoft.com/businesscentral/onprem:latest-ltsc2016
3d2397d0577f86a78ee74cdcddd7eb0066e6433087ec377c50e022e314b2ef68
Waiting for container bcdemo to be ready
Initializing...
Starting Container
Hostname is bcdemo
PublicDnsName is bcdemo
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Creating Windows user Pratyusha
Setting SA Password and enabling SA
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Container IP Address: 172.26.245.240
Container Hostname  : bcdemo
Container Dns Name  : bcdemo
Web Client          : http://bcdemo/NAV/
Dev. Server         : http://bcdemo
Dev. ServerInstance : NAV

Files:
http://bcdemo:8080/al-3.0.154634.vsix

Initialization took 107 seconds
Ready for connections!
Reading CustomSettings.config from bcdemo
Creating Desktop Shortcuts for bcdemo
Container bcdemo successfully created

This created the Web Client successfully. How can I access the AL ? Using the Dev server details? (Because I get the package cache error when I do that)

**Comment by freddydk** [comment]
Just wanted to see if the most basic new-navcontainer works - it does.
Please follow this blog post: https://freddysblog.com/2019/08/20/business-central-on-docker-for-non-experts/ - it describes which options to add.
-updateHosts is probably the one you need to access the web client and download the .vsix.

**Comment by freddydk** [comment]
Assuming that this issue is resolved.
