### ISSUE TITLE
Error Creating NAV 2015 on Docker

### ISSUE THREAD

**Issue by StephenDoherty** [microsoft/nav-docker#407]
Hello,
I am running into an error trying to create a docker container from a NAV2015 DVD.
I have followed this article https://blogs.msdn.microsoft.com/freddyk/2017/11/29/can-i-run-nav-2015-and-earlier-on-docker/ on how to create the container but it fails before completing successfully with the error below. I am using Nav-ContainerHelper and docker ver 2.1.0.1 (37199).

I have included the script I am running and the output.
Any help is appreciated.

ERROR
Initialization of container NAV2015test failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.3.2\ContainerHandling\Wait-NavContainerReady.ps1:45 
char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...2015test failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container NAV2015test failed

`New-NAVContainer `
    -accept_eula `
    -containerName 'NAV2015test' `
    -navDvdPath "C:\temp\nav2015" `
    -navDvdCountry w1 `
    -updateHosts `    
    -shortcuts Desktop `
    -accept_outdated `
    -auth Windows `
    -memoryLimit 4G `
    -Verbose `
    -includeCSide`

PS H:\> C:\temp\NewNAVContainerScriptNAV2015v1.ps1
NavContainerHelper is version 0.6.3.2
Host is Microsoft Windows 10 Pro - ltsc2019
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Using image mcr.microsoft.com/dynamicsnav:generic-ltsc2019
Removing C:\ProgramData\NavContainerHelper\Extensions\NAV2015test
Creating Container NAV2015test
Version: 8.0.40459.0-w1
Generic Tag: 0.0.9.92
Container OS Version: 10.0.17763.678 (ltsc2019)
Host OS Version: 10.0.17763.720 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\NAV2015test\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- updatehosts.ps1
Creating container NAV2015test from image mcr.microsoft.com/dynamicsnav:generic-ltsc2019
05af9c6add88376e19fde5af842f56fba18c6bfccae408a60011d4a6bac651c9
Waiting for container NAV2015test to be ready
Installing NAV
Installing .NET 3
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Installing Url Rewrite
Installing Report Viewer
Installing OpenXML
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying UpgradeToolKit
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Changing Database Server Collation to Latin1_General_100_CS_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to M
icrosoft to help improve the product. To learn more about SQL Server 2017 data processing and privacy controls, please see 
the Privacy Statement.
Installing C:\NAVDVD\Installers\CA.en\OlAddin\OutlookAddIn.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.en\RTC\RoleTailoredClient.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.en\Server\Server.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.en\WebClient\WebClient.Local.CA.en.msi
Skipping C:\NAVDVD\Installers\CA.en\WebHelp\WebHelp.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.fr\OlAddin\OutlookAddIn.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\CA.fr\RTC\RoleTailoredClient.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\CA.fr\Server\Server.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\CA.fr\WebClient\WebClient.Local.CA.fr.msi
Skipping C:\NAVDVD\Installers\CA.fr\WebHelp\WebHelp.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\MX.es\OlAddin\OutlookAddIn.Local.MX.es.msi
Installing C:\NAVDVD\Installers\MX.es\RTC\RoleTailoredClient.Local.MX.es.msi
Installing C:\NAVDVD\Installers\MX.es\Server\Server.Local.MX.es.msi
Installing C:\NAVDVD\Installers\MX.es\WebClient\WebClient.Local.MX.es.msi
Skipping C:\NAVDVD\Installers\MX.es\WebHelp\WebHelp.Local.MX.es.msi
Installing C:\NAVDVD\Installers\US.en\OlAddin\OutlookAddIn.Local.US.en.msi
Installing C:\NAVDVD\Installers\US.en\RTC\RoleTailoredClient.Local.US.en.msi
Installing C:\NAVDVD\Installers\US.en\Server\Server.Local.US.en.msi
Installing C:\NAVDVD\Installers\US.en\WebClient\WebClient.Local.US.en.msi
Skipping C:\NAVDVD\Installers\US.en\WebHelp\WebHelp.Local.US.en.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Starting NAV Service Tier
Importing CRONUS license file
The Microsoft Dynamics NAV server is currently not ready to serve requests. Try again later or contact your system administ
rator.
at <ScriptBlock>, C:\Run\navinstall.ps1: line 188
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1Error
Installing NAV
Installing .NET 3
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Installing Url Rewrite
Installing Report Viewer
Installing OpenXML
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying UpgradeToolKit
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Changing Database Server Collation to Latin1_General_100_CS_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to M
icrosoft to help improve the product. To learn more about SQL Server 2017 data processing and privacy controls, please see 
the Privacy Statement.
Installing C:\NAVDVD\Installers\CA.en\OlAddin\OutlookAddIn.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.en\RTC\RoleTailoredClient.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.en\Server\Server.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.en\WebClient\WebClient.Local.CA.en.msi
Skipping C:\NAVDVD\Installers\CA.en\WebHelp\WebHelp.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.fr\OlAddin\OutlookAddIn.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\CA.fr\RTC\RoleTailoredClient.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\CA.fr\Server\Server.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\CA.fr\WebClient\WebClient.Local.CA.fr.msi
Skipping C:\NAVDVD\Installers\CA.fr\WebHelp\WebHelp.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\MX.es\OlAddin\OutlookAddIn.Local.MX.es.msi
Installing C:\NAVDVD\Installers\MX.es\RTC\RoleTailoredClient.Local.MX.es.msi
Installing C:\NAVDVD\Installers\MX.es\Server\Server.Local.MX.es.msi
Installing C:\NAVDVD\Installers\MX.es\WebClient\WebClient.Local.MX.es.msi
Skipping C:\NAVDVD\Installers\MX.es\WebHelp\WebHelp.Local.MX.es.msi
Installing C:\NAVDVD\Installers\US.en\OlAddin\OutlookAddIn.Local.US.en.msi
Installing C:\NAVDVD\Installers\US.en\RTC\RoleTailoredClient.Local.US.en.msi
Installing C:\NAVDVD\Installers\US.en\Server\Server.Local.US.en.msi
Installing C:\NAVDVD\Installers\US.en\WebClient\WebClient.Local.US.en.msi
Skipping C:\NAVDVD\Installers\US.en\WebHelp\WebHelp.Local.US.en.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Starting NAV Service Tier
Importing CRONUS license file
The Microsoft Dynamics NAV server is currently not ready to serve requests. Try again later or contact your system administ
rator.
at <ScriptBlock>, C:\Run\navinstall.ps1: line 188
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1
Initialization of container NAV2015test failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.3.2\ContainerHandling\Wait-NavContainerReady.ps1:45 
char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...2015test failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container NAV2015test failed

**Comment by freddydk** [comment]
Your command looks correct.
Can you run other NAV or Business Central containers?

During initialization, it says:
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv

Did you try that?
Which NAV 2015 DVD are you using?

**Comment by StephenDoherty** [comment]
First, thank you for helping me out on this. 
To answer your questions:
Yes, I am able to run other NAV and BC containers although this is the only one I am trying from an extracted DVD.

I changed my script with the -isolation hyperv switch and it produced the same error.

NAV version is US Dynamics NAV 8.0 - 8.0.40459.0


Here is the latest output I tried with the previous docker version and then tried with the latest version just to see if anything was added.

PS H:\> C:\temp\NewNAVContainerScriptNAV2015v1.ps1
NavContainerHelper is version 0.6.3.2
Host is Microsoft Windows 10 Pro - ltsc2019
Docker Client Version is 19.03.2
Docker Server Version is 19.03.2
Using image mcr.microsoft.com/dynamicsnav:generic-ltsc2019
Removing container NAV2015test
Removing NAV2015test from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\NAV2015test
Creating Container NAV2015test
Version: 8.0.40459.0-w1
Generic Tag: 0.0.9.92
Container OS Version: 10.0.17763.678 (ltsc2019)
Host OS Version: 10.0.17763.720 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\NAV2015test\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- updatehosts.ps1
Creating container NAV2015test from image mcr.microsoft.com/dynamicsnav:generic-ltsc2019
0edad957f35198f4c7e77ebcbec8d5f8fc1e6e4bae39126b1f733daa8309097c
Waiting for container NAV2015test to be ready
Installing NAV
Installing .NET 3
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Installing Url Rewrite
Installing Report Viewer
Installing OpenXML
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying UpgradeToolKit
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Changing Database Server Collation to Latin1_General_100_CS_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and perfor
mance data, to Microsoft to help improve the product. To learn more about SQL Server 2017 data processing a
nd privacy controls, please see the Privacy Statement.
Installing C:\NAVDVD\Installers\CA.en\OlAddin\OutlookAddIn.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.en\RTC\RoleTailoredClient.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.en\Server\Server.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.en\WebClient\WebClient.Local.CA.en.msi
Skipping C:\NAVDVD\Installers\CA.en\WebHelp\WebHelp.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.fr\OlAddin\OutlookAddIn.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\CA.fr\RTC\RoleTailoredClient.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\CA.fr\Server\Server.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\CA.fr\WebClient\WebClient.Local.CA.fr.msi
Skipping C:\NAVDVD\Installers\CA.fr\WebHelp\WebHelp.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\MX.es\OlAddin\OutlookAddIn.Local.MX.es.msi
Installing C:\NAVDVD\Installers\MX.es\RTC\RoleTailoredClient.Local.MX.es.msi
Installing C:\NAVDVD\Installers\MX.es\Server\Server.Local.MX.es.msi
Installing C:\NAVDVD\Installers\MX.es\WebClient\WebClient.Local.MX.es.msi
Skipping C:\NAVDVD\Installers\MX.es\WebHelp\WebHelp.Local.MX.es.msi
Installing C:\NAVDVD\Installers\US.en\OlAddin\OutlookAddIn.Local.US.en.msi
Installing C:\NAVDVD\Installers\US.en\RTC\RoleTailoredClient.Local.US.en.msi
Installing C:\NAVDVD\Installers\US.en\Server\Server.Local.US.en.msi
Installing C:\NAVDVD\Installers\US.en\WebClient\WebClient.Local.US.en.msi
Skipping C:\NAVDVD\Installers\US.en\WebHelp\WebHelp.Local.US.en.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Starting NAV Service Tier
Importing CRONUS license file
The Microsoft Dynamics NAV server is currently not ready to serve requests. Try again later or contact your
 system administrator.
at <ScriptBlock>, C:\Run\navinstall.ps1: line 188
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1Error
Installing NAV
Installing .NET 3
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Installing Url Rewrite
Installing Report Viewer
Installing OpenXML
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying UpgradeToolKit
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Changing Database Server Collation to Latin1_General_100_CS_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and perfor
mance data, to Microsoft to help improve the product. To learn more about SQL Server 2017 data processing a
nd privacy controls, please see the Privacy Statement.
Installing C:\NAVDVD\Installers\CA.en\OlAddin\OutlookAddIn.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.en\RTC\RoleTailoredClient.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.en\Server\Server.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.en\WebClient\WebClient.Local.CA.en.msi
Skipping C:\NAVDVD\Installers\CA.en\WebHelp\WebHelp.Local.CA.en.msi
Installing C:\NAVDVD\Installers\CA.fr\OlAddin\OutlookAddIn.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\CA.fr\RTC\RoleTailoredClient.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\CA.fr\Server\Server.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\CA.fr\WebClient\WebClient.Local.CA.fr.msi
Skipping C:\NAVDVD\Installers\CA.fr\WebHelp\WebHelp.Local.CA.fr.msi
Installing C:\NAVDVD\Installers\MX.es\OlAddin\OutlookAddIn.Local.MX.es.msi
Installing C:\NAVDVD\Installers\MX.es\RTC\RoleTailoredClient.Local.MX.es.msi
Installing C:\NAVDVD\Installers\MX.es\Server\Server.Local.MX.es.msi
Installing C:\NAVDVD\Installers\MX.es\WebClient\WebClient.Local.MX.es.msi
Skipping C:\NAVDVD\Installers\MX.es\WebHelp\WebHelp.Local.MX.es.msi
Installing C:\NAVDVD\Installers\US.en\OlAddin\OutlookAddIn.Local.US.en.msi
Installing C:\NAVDVD\Installers\US.en\RTC\RoleTailoredClient.Local.US.en.msi
Installing C:\NAVDVD\Installers\US.en\Server\Server.Local.US.en.msi
Installing C:\NAVDVD\Installers\US.en\WebClient\WebClient.Local.US.en.msi
Skipping C:\NAVDVD\Installers\US.en\WebHelp\WebHelp.Local.US.en.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Starting NAV Service Tier
Importing CRONUS license file
The Microsoft Dynamics NAV server is currently not ready to serve requests. Try again later or contact your
 system administrator.
at <ScriptBlock>, C:\Run\navinstall.ps1: line 188
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1
Initialization of container NAV2015test failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.3.2\ContainerHandling\Wait-NavContain
erReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...2015test failed:String) [], RuntimeExc 
   eption
    + FullyQualifiedErrorId : Initialization of container NAV2015test failed

**Comment by freddydk** [comment]
The version you are trying is NAV 2015 cu6 - requires .net 3
I haven't tried this on server 2019 (and I wont have the chance to do so) - might be the problem.
I am sorry, but that is probably the best I can do .

**Comment by StephenDoherty** [comment]
No worries.
I do have one question though. When you say "tried this on server 2019" what does that mean?
This machine is a Windows 10 build. Is there a way to control the server version say telling it to build a 2016 server and not a 2019? 
Also, as a side note I did place the .net 3 "microsoft-windows-netfx3-ondemand-package.cab" executable in the prerequisites folder.

**Comment by freddydk** [comment]
you can try to specify -usegenericimage mcr.microsoft.com/dynamicsnav:generic-ltsc2016 - then it will run the server 2016 image as hyperv. (remove -usebestcontaineros then)

**Comment by freddydk** [comment]
Yes, you are running Windows 10 17763 (which is compatible with windows server 2019)

**Comment by StephenDoherty** [comment]
Ok I will try that next and let you know how it works out.

Thanks again.

**Comment by StephenDoherty** [comment]
Using the 2016 generic image seemed to work.
I was able to create the container but there is one issue with exporting the objects (which I need)
I have opened a separate ticket for this under navcontainerhelper. [https://github.com/microsoft/navcontainerhelper/issues/616](url)

Thanks again for the help on this one.

**Comment by StephenDoherty** [comment]
just to help anyone else out my navcontainerhelper scripts that worked is below.
```

New-NAVContainer `
    -accept_eula `
    -containerName 'NAV2015test' `
    -usegenericimage mcr.microsoft.com/dynamicsnav:generic-ltsc2016 `
    -navDvdPath "C:\temp\nav2015" `
    -navDvdCountry w1 `
    -updateHosts `
    -shortcuts Desktop `
    -accept_outdated `
    -auth NavUserPassword `
    -memoryLimit 4G `
    -isolation hyperv `
    -Verbose `
    -licenseFile "C:\temp\PRE_2015.flf" `
    -includeCSide
```
