### ISSUE TITLE
Initialization of container "XXXX" failed in NAV 2018

### ISSUE THREAD

**Issue by mplze** [microsoft/nav-docker#409]
While Creating 2018 Docker Container getting below error message 

Script 

![Script](https://user-images.githubusercontent.com/32490642/64533462-26d71980-d331-11e9-8d4d-f2ec0bc312bc.jpg)

Error Message

![Full Error](https://user-images.githubusercontent.com/32490642/64533597-6c93e200-d331-11e9-8284-69082aaf0a1e.jpg)

**Comment by freddydk** [comment]
You need to specify -accept_outdated to the command.
And please note, that -licensefile and -shortcuts have a different color, indicating that you have a space after the grave symbol on the line before. See more here:
https://freddysblog.com/2019/08/04/powershell-for-non-experts/
https://freddysblog.com/2019/08/20/business-central-on-docker-for-non-experts/

**Comment by mplze** [comment]
Yes, their s same unwanted space on parameter list, after removing "space" still same error showed. Then I change the license file now it working.

Thank you Freddydk
