### ISSUE TITLE
ClickOnce C/SIDE Deployment: Default options for ZUP-File

### ISSUE THREAD

**Issue by lippertmarkus** [Microsoft/nav-docker#41]
When deploying C/SIDE environment via ClickOnce it would be nice if the database server and database name would be predefined to quickly open the database without manually specifing these settings (just like with the ClientUserSettings for the windows client). 

As running the default setup to create the ZUP file while build is no option and opening the C/SIDE environment with parameters and closing it again to save the ZUP while building the image is not possible in the container, is there any other way to achieve this? I also tried using URL parameters with ClickOnce deployment without success.

**Comment by Koubek** [comment]
I am wondering if we could use lnk (shortcut) file as an entry point. We could pass the parameters easily as well as **id** to avoid problems of the overwriting *zup* files.

I haven\`t tried it yet with ClickOnce but I am sending an example of **lnk** file. Of course, this should be created dynamically via PowerShell. This is one possibility:
```PowerShell
$WshShell = New-Object -comObject WScript.Shell

$Shortcut = $WshShell.CreateShortcut("FinSql.lnk")
$Shortcut.TargetPath = "%COMSPEC% /C .\finsql.exe servername=MYSQLSERVER, database=MYDB, ntauthentication=yes, id=testshortcut"
$Shortcut.RelativePath = '%CD%'
$Shortcut.Save()
```

And this is the result of the previous script (a bit different as the script being included is slightly different but you can run the script and create your own link):

[finsql.lnk.zip](https://github.com/Microsoft/nav-docker/files/1275540/finsql.lnk.zip)

**Comment by Koubek** [comment]
My previous post is pointless as the **ClickOnce\`s entrypoint** must be a valid and managed code-based EXE. Sorry, don\`t know ClickOnce so...

But I have another option and looks promising (I am going to test it but mage.exe accept the output of the following):

https://gallery.technet.microsoft.com/PS2EXE-Convert-PowerShell-9e4e07f1

This tool allows you to convert a `ps1` file into an `exe` file. So you can have a simple PowerShell script that will launch `finsql.exe` with requiered parameters. This file can be converted into the exe file using the script so you can simply convert it using required parameters during the startup process.

Maybe this form won`t work or won`t fit your ideas but I will test it.

**Comment by Koubek** [comment]
@freddydk The approach mentioned before work fine but not from ClickOnce. It works only in the case you copy the content of the ClickOnce folder out of the container and you run it from your environment directly.

There are two problems I can see right now:
- The **manifest** file has different **entrypoint** than expected (remains `finsql.exe` but I want to be included my `runfinsql.exe` which all parameters already included and internally runs `finsql.exe`). I don\`t know how to change the **entrypoint**.
- I suppose there will also be a problem with the signatures of the `exe` file etc. Some identity problems in general. Am I right? 

Are we able to overcome the issues somehow? My conversion process works fine, I use a temp folder, create `ps1` file that internally runs 
```PowerShell
Set-Content "$buildFolder\$fileName.ps1" "Start-Process 'finsql.exe' -ArgumentList ""servername=$SqlServerName, database=$DbName, ntauthentication=$useNtAuth, id=$Id""" -Force
```
This `ps1` file is converted into the `exe` file, this is copied into the ClickOnce folder and the temporary outputs are deleted.

**Comment by freddydk** [comment]
using navcontainerhelper with -includecside will give you shortcuts which works fluently - especially when running windows authentication.
No plans of adding more to clickonce.
