### ISSUE TITLE
Issue creating Business Central container  Version: Platform 14.0.35875.0 

### ISSUE THREAD

**Issue by kemandengu** [microsoft/nav-docker#410]
Hi,

I am trying to create a BC container for Version: Platform 14.0.35875.0  and I get the message that 'not found' see the results from the script that I have run. Can someone please help?

Specify the required Version of Dynamics NAV (2016, 2017, 2018, Business Central (Enter: 2019)): 2019
is this a Business Central On Premises instance (y/n)?: n
Specify the required Version of Dynamics NAV/Business Central localisation (empty = gb): 
Specify the required Business Central Version (e.g.: 13.1.25940.0), leave blank for latest: 14.0.35875.0
is this a SandBox standalone Container (y/n)?: y
Specify Container Prefix: M0132
Do you need to create a new NAV User? (y/n)?: Y
Specify NAV User Name: ACORANAV
Specify NAV User Password: 123456
Do you want to create Shortcuts? [0, None, 1: Desktop, 2: Start Menu, 3 Common Start Menu]: 1
Are you Sure You Want To Proceed pulling image mcr.microsoft.com/businesscentral/sandbox:14.0.35875.0-gb and created container M0132-BC?: Y
docker : Error response from daemon: manifest for mcr.microsoft.com/businesscentral/sandbox:14.0.35875.0-gb not found
At M:\Tools\Docker\NAV Related\Final Scripts\Container Creation and Management.ps1:383 char:9
+         docker pull $NAVImageName
+         ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ....0-gb not found:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 18.09.0
Docker Server Version is 18.09.0
Pulling image mcr.microsoft.com/businesscentral/sandbox:14.0.35875.0-gb-ltsc2019
Pulling image mcr.microsoft.com/businesscentral/sandbox:14.0.35875.0-gb
DockerDo : Error response from daemon: manifest for mcr.microsoft.com/businesscentral/sandbox:14.0.35875.0-gb not found
ExitCode: 1
Commandline: docker pull  mcr.microsoft.com/businesscentral/sandbox:14.0.35875.0-gb
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.4.2.6\ContainerHandling\New-NavContainer.ps1:282 char:13
+             DockerDo -command pull -imageName $imageName | Out-Null
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo
 

PS C:\Windows\system32> 
 I have included the script I am running and the output.
 Any help is appreciated.

ERROR
 Initialization of container NAV2015test failed
 At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.3.2\ContainerHandling\Wait-NavContainerReady.ps1:45
 char:17
•... throw "Initialization of container $containerName failed" ...
•             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

◦CategoryInfo : OperationStopped: (Initialization ...2015test failed:String) [], RuntimeException
◦FullyQualifiedErrorId : Initialization of container NAV2015test failed

New-NAVContainer 
 -accept_eula -containerName 'NAV2015test'
 -navDvdPath "C:\temp\nav2015" -navDvdCountry w1
 -updateHosts  -shortcuts Desktop
 -accept_outdated -auth Windows
 -memoryLimit 4G -Verbose
 -includeCSide`

PS H:> C:\temp\NewNAVContainerScriptNAV2015v1.ps1
 NavContainerHelper is version 0.6.3.2
 Host is Microsoft Windows 10 Pro - ltsc2019
 Docker Client Version is 19.03.1
 Docker Server Version is 19.03.1
 Using image mcr.microsoft.com/dynamicsnav:generic-ltsc2019
 Removing C:\ProgramData\NavContainerHelper\Extensions\NAV2015test
 Creating Container NAV2015test
 Version: 8.0.40459.0-w1
 Generic Tag: 0.0.9.92
 Container OS Version: 10.0.17763.678 (ltsc2019)
 Host OS Version: 10.0.17763.720 (ltsc2019)
 WARNING: The container operating system matches the host operating system, but the revision is different.
 If you encounter issues, you might want to specify -isolation hyperv
 Using locale en-US
 Using process isolation
 Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
 Files in C:\ProgramData\NavContainerHelper\Extensions\NAV2015test\my:
•AdditionalOutput.ps1
•MainLoop.ps1
•updatehosts.ps1
 Creating container NAV2015test from image mcr.microsoft.com/dynamicsnav:generic-ltsc2019
 05af9c6add88376e19fde5af842f56fba18c6bfccae408a60011d4a6bac651c9
 Waiting for container NAV2015test to be ready
 Installing NAV
 Installing .NET 3
 Starting Local SQL Server
 WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
 start...
 WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
 start...
 WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
 start...
 WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
 start...
 Starting Internet Information Server
 Installing Url Rewrite
 Installing Report Viewer
 Installing OpenXML
 Copying Service Tier Files
 Copying Web Client Files
 Copying Windows Client Files
 Copying PowerShell Scripts
 Copying UpgradeToolKit
 Copying ClientUserSettings
 Copying ReportBuilder
 Restoring CRONUS Demo Database
 Changing Database Server Collation to Latin1_General_100_CS_AS
 SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to M
 icrosoft to help improve the product. To learn more about SQL Server 2017 data processing and privacy controls, please see
 the Privacy Statement.
 Installing C:\NAVDVD\Installers\CA.en\OlAddin\OutlookAddIn.Local.CA.en.msi
 Installing C:\NAVDVD\Installers\CA.en\RTC\RoleTailoredClient.Local.CA.en.msi
 Installing C:\NAVDVD\Installers\CA.en\Server\Server.Local.CA.en.msi
 Installing C:\NAVDVD\Installers\CA.en\WebClient\WebClient.Local.CA.en.msi
 Skipping C:\NAVDVD\Installers\CA.en\WebHelp\WebHelp.Local.CA.en.msi
 Installing C:\NAVDVD\Installers\CA.fr\OlAddin\OutlookAddIn.Local.CA.fr.msi
 Installing C:\NAVDVD\Installers\CA.fr\RTC\RoleTailoredClient.Local.CA.fr.msi
 Installing C:\NAVDVD\Installers\CA.fr\Server\Server.Local.CA.fr.msi
 Installing C:\NAVDVD\Installers\CA.fr\WebClient\WebClient.Local.CA.fr.msi
 Skipping C:\NAVDVD\Installers\CA.fr\WebHelp\WebHelp.Local.CA.fr.msi
 Installing C:\NAVDVD\Installers\MX.es\OlAddin\OutlookAddIn.Local.MX.es.msi
 Installing C:\NAVDVD\Installers\MX.es\RTC\RoleTailoredClient.Local.MX.es.msi
 Installing C:\NAVDVD\Installers\MX.es\Server\Server.Local.MX.es.msi
 Installing C:\NAVDVD\Installers\MX.es\WebClient\WebClient.Local.MX.es.msi
 Skipping C:\NAVDVD\Installers\MX.es\WebHelp\WebHelp.Local.MX.es.msi
 Installing C:\NAVDVD\Installers\US.en\OlAddin\OutlookAddIn.Local.US.en.msi
 Installing C:\NAVDVD\Installers\US.en\RTC\RoleTailoredClient.Local.US.en.msi
 Installing C:\NAVDVD\Installers\US.en\Server\Server.Local.US.en.msi
 Installing C:\NAVDVD\Installers\US.en\WebClient\WebClient.Local.US.en.msi
 Skipping C:\NAVDVD\Installers\US.en\WebHelp\WebHelp.Local.US.en.msi
 Modifying NAV Service Tier Config File for Docker
 Creating NAV Service Tier
 Starting NAV Service Tier
 Importing CRONUS license file
 The Microsoft Dynamics NAV server is currently not ready to serve requests. Try again later or contact your system administ
 rator.
 at , C:\Run\navinstall.ps1: line 188
 at , C:\Run\start.ps1: line 114
 at , : line 1Error
 Installing NAV
 Installing .NET 3
 Starting Local SQL Server
 WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
 start...
 WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
 start...
 WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
 start...
 WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
 start...
 Starting Internet Information Server
 Installing Url Rewrite
 Installing Report Viewer
 Installing OpenXML
 Copying Service Tier Files
 Copying Web Client Files
 Copying Windows Client Files
 Copying PowerShell Scripts
 Copying UpgradeToolKit
 Copying ClientUserSettings
 Copying ReportBuilder
 Restoring CRONUS Demo Database
 Changing Database Server Collation to Latin1_General_100_CS_AS
 SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to M
 icrosoft to help improve the product. To learn more about SQL Server 2017 data processing and privacy controls, please see
 the Privacy Statement.
 Installing C:\NAVDVD\Installers\CA.en\OlAddin\OutlookAddIn.Local.CA.en.msi
 Installing C:\NAVDVD\Installers\CA.en\RTC\RoleTailoredClient.Local.CA.en.msi
 Installing C:\NAVDVD\Installers\CA.en\Server\Server.Local.CA.en.msi
 Installing C:\NAVDVD\Installers\CA.en\WebClient\WebClient.Local.CA.en.msi
 Skipping C:\NAVDVD\Installers\CA.en\WebHelp\WebHelp.Local.CA.en.msi
 Installing C:\NAVDVD\Installers\CA.fr\OlAddin\OutlookAddIn.Local.CA.fr.msi
 Installing C:\NAVDVD\Installers\CA.fr\RTC\RoleTailoredClient.Local.CA.fr.msi
 Installing C:\NAVDVD\Installers\CA.fr\Server\Server.Local.CA.fr.msi
 Installing C:\NAVDVD\Installers\CA.fr\WebClient\WebClient.Local.CA.fr.msi
 Skipping C:\NAVDVD\Installers\CA.fr\WebHelp\WebHelp.Local.CA.fr.msi
 Installing C:\NAVDVD\Installers\MX.es\OlAddin\OutlookAddIn.Local.MX.es.msi
 Installing C:\NAVDVD\Installers\MX.es\RTC\RoleTailoredClient.Local.MX.es.msi
 Installing C:\NAVDVD\Installers\MX.es\Server\Server.Local.MX.es.msi
 Installing C:\NAVDVD\Installers\MX.es\WebClient\WebClient.Local.MX.es.msi
 Skipping C:\NAVDVD\Installers\MX.es\WebHelp\WebHelp.Local.MX.es.msi
 Installing C:\NAVDVD\Installers\US.en\OlAddin\OutlookAddIn.Local.US.en.msi
 Installing C:\NAVDVD\Installers\US.en\RTC\RoleTailoredClient.Local.US.en.msi
 Installing C:\NAVDVD\Installers\US.en\Server\Server.Local.US.en.msi
 Installing C:\NAVDVD\Installers\US.en\WebClient\WebClient.Local.US.en.msi
 Skipping C:\NAVDVD\Installers\US.en\WebHelp\WebHelp.Local.US.en.msi
 Modifying NAV Service Tier Config File for Docker
 Creating NAV Service Tier
 Starting NAV Service Tier
 Importing CRONUS license file
 The Microsoft Dynamics NAV server is currently not ready to serve requests. Try again later or contact your system administ
 rator.
 at , C:\Run\navinstall.ps1: line 188
 at , C:\Run\start.ps1: line 114
 at , : line 1
 Initialization of container NAV2015test failed
 At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.3.2\ContainerHandling\Wait-NavContainerReady.ps1:45
 char:17
•... throw "Initialization of container $containerName failed" ...
•             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

◦CategoryInfo : OperationStopped: (Initialization ...2015test failed:String) [], RuntimeException
◦FullyQualifiedErrorId : Initialization of container NAV2015test failed
*******************************************************************************************************
See script below...

Clear-Host

$IsBusinessCentral = $False

# 1 - Selects the NAV Version
# ------------------------
switch(Read-Host 'Specify the required Version of Dynamics NAV (2016, 2017, 2018, Business Central (Enter: 2019))'){
    2016 {$NAVVersion = '2016'}
    2017 {$NAVVersion = '2017'}
    2018 {$NAVVersion = '2018'}
    2019 {$IsBusinessCentral = $True} #Business Central                         
    default 
        {
            write-host('The selected version is invalid')
            exit
        }
}

# It asks the user whether is On Premises since On Premises requires different "image link" and different logic when finding localisation
if ($IsBusinessCentral)
    {
        $IsOnPrem = Show-ConfirmBox('is this a Business Central On Premises instance (y/n)?')
    }
else
    {
        # The variable is used below so it is always True for NAV
        $IsOnPrem = $True 
    } 

# 2 - Selects the NAV Localisation (default gb)
# ------------------------
$NAVLocalisation    = Read-Host -Prompt 'Specify the required Version of Dynamics NAV/Business Central localisation (empty = gb)'

# 3 - it specifies the Comulative update
If (-not $IsBusinessCentral)
    {
        $NAVCU              = Read-Host -Prompt 'Specify the required Dynamics NAV Comulative Update'
    }
else
    {
        if (-not $IsOnPrem)
            {
                $NAVCU              = Read-Host -Prompt 'Specify the required Business Central Version (e.g.: 13.1.25940.0), leave blank for latest'
                $NAVVersion         = $NAVCU 
   
            }
        else
            {
                $NAVCU              = Read-Host -Prompt 'Specify the required Business Central On Premises Comulative Update'
            }

    }

# It only checks the structure of the enter comulative update if the version is NAV
if (($NAVCU.Length -gt 0) -and ($IsOnPrem))
    {
        $IsNumericResult = ($NAVCU | IsNumeric -Boolean) ;
        if ($IsNumericResult)
            {
               # NOP
            }
        else
            {
                Write-Host('The specified Comulative Update is invalid')
                exit
            }
    }

if ($IsBusinessCentral)
    {
        if ($IsOnPrem)
            {
                #It only changes the version if a Comulative update has been specified
                if ($NAVCU.Length -gt 0)
                {
                    $NAVVersion = 'cu' + $NAVCU.ToString()
                }
            }
    }

if (-not $IsBusinessCentral)
    {
        $IsCronusContainer = Show-ConfirmBox('is this a Cronus Demo standalone Container (y/n)?')
    }
else
    {
        #Different wording for Business Central
        $IsCronusContainer = Show-ConfirmBox('is this a SandBox standalone Container (y/n)?')
    }

if (-not $IsCronusContainer)
    {
        $DatabaseServer     = Read-Host -Prompt 'Specify Database Server'
        $DatabaseInstance   = Read-Host -Prompt 'Specify Database Instance'
        $DatabaseName       = Read-Host -Prompt 'Specify Database Name'
    }

$ContainerPrefix    = Read-Host -Prompt 'Specify Container Prefix' 

if ($ContainerPrefix.Length -eq 0)
    {
        Write-Host('The specified container prefix is invalid')
        exit
    }

if (-not $IsBusinessCentral)
    {
        $ContainerName      = $ContainerPrefix +'-NAV'
    }
else
    {
        $ContainerName      = $ContainerPrefix +'-BC'
    }

$ContainerName      = $ContainerName.ToUpper() 

#Parameter as NAV Container Helper requirement
$MaxContainerNameLength = 15

if ($ContainerName.Length -gt $MaxContainerNameLength)
    {
        Write-Host($ContainerName + 'length exceeds the allowed maximum length (' + $MaxContainerNameLength + ')')
    }

if (Show-ConfirmBox('Do you need to create a new NAV User? (y/n)?'))
{
    $navusername        = Read-Host -Prompt 'Specify NAV User Name'
    $navuserpwd         = Read-Host -Prompt 'Specify NAV User Password'
    $MustCreateUser     = $True
}
else
{
    $MustCreateUser     = $False
}

#It validates the required localisation
If ($NAVLocalisation.Length -eq 0) 
{
    $NAVLocalisation = 'gb'
}

#Business Central on Premise requires localisation to be changed
if (($IsBusinessCentral) -and ($IsOnPrem))
    {
        $NAVLocalisation = $NAVLocalisation + '-ltsc2019'
    }

if (-not $IsBusinessCentral) # It generates the Image name for a NAV image
    {

        If ($NAVCU.Length -eq 0) 
        {
            $NAVImageName  = 'microsoft/dynamics-nav:' + $NAVVersion + '-' + $NAVLocalisation
        } 
        else
        {
            if (-not ($NAVCU.StartsWith('cu')))
            {
                $NAVCU = 'cu' + $NAVCU.ToString()
            }

            $NAVImageName = 'microsoft/dynamics-nav:' + $NAVVersion + '-' + $NAVCU.ToString() + '-' + $NAVLocalisation
        }
    }
else
    {
        if ($NAVVersion.Length -gt 0)
            {
                if (-not $IsOnPrem)
                    {
                        $NAVImageName = 'mcr.microsoft.com/businesscentral/sandbox:' + $NAVVersion + '-' + $NAVLocalisation
                    }
                else
                    {
                        #For Business Central NAV Version contains the comulative update
                        if ($NAVVersion.Length -gt 0)
                            {
                                $NAVImageName = 'mcr.microsoft.com/businesscentral/onprem:1810-' + $NAVVersion + '-' + $NAVLocalisation
                            }
                        else
                            {
                                $NAVImageName = 'mcr.microsoft.com/businesscentral/onprem:1810-' + $NAVLocalisation
                            }
                    }
            }
        else
            {
                if (-not $IsOnPrem)
                    {
                        $NAVImageName = 'mcr.microsoft.com/businesscentral/sandbox:' + $NAVLocalisation   
                    }
                else
                    {
                        $NAVImageName = 'mcr.microsoft.com/businesscentral/onprem:' + $NAVLocalisation   
                    }
            }

    }

switch(Read-Host 'Do you want to create Shortcuts? [0, None, 1: Desktop, 2: Start Menu, 3 Common Start Menu]'){
    0 {$ShortcutsPos = 'None'}
    1 {$ShortcutsPos = 'Desktop'}
    2 {$ShortcutsPos = 'StartMenu'}
    3 {$ShortcutsPos = 'CommonStartMenu'}
    default 
        {
            write-host('The selected shortcut option is invalid')
            exit
        }
}

if (Show-ConfirmBox('Are you Sure You Want To Proceed pulling image '+ $NAVImageName + ' and created container ' + $ContainerName + '?')) 
    {
        #Docker pulls the required NAV/BC Image
        docker pull $NAVImageName
        #It runs NAVContainerHelper to create the instance
        if ($IsCronusContainer)
            {
                # The license is to be used for NAV and not business Central
                if ($IsBusinessCentral)
                {
                    $LicenseFile = '' # License is not needed for Business Central SandBox (it will load the standard BC license)
                }
                else
                {
                    if (Show-ConfirmBox('Do you plan to use the FULL developer license on this CRONUS environment?'))
                    {
                        $LicenseFile = 'M:\Tools\License\Acora NAV 2018 Dev License 2019-07-12.flf' # If is not CRONUS license is Acora License is load
                    }
                    else
                    {
                        $LicenseFile = '' # It leaves it empty (it will load the CRONUS License)
                    }
                }
            }
        else
            {
                $LicenseFile = 'M:\Tools\License\Acora NAV 2018 Dev License 2019-07-12.flf' # If is not CRONUS license is Acora License is load
            }

        $navServicecredential       = New-Object System.Management.Automation.PSCredential -argumentList "admin", (ConvertTo-SecureString -String "P@ssword1" -AsPlainText -Force)
    
        if (-not $IsCronusContainer)
            {
                $databasecredential         = New-Object System.Management.Automation.PSCredential -argumentList "dockeruser", (ConvertTo-SecureString -String "dockeruser" -AsPlainText -Force)
            }
  
        if ($IsCronusContainer)
            {
                New-NavContainer -containerName $ContainerName -accept_eula -additionalParameters @('--net nat --hostname ' + $ContainerName) -auth NavUserPassword -Credential $navServicecredential -imageName $NAVImageName -includeCSide -licenseFile $LicenseFile -shortcuts $ShortcutsPos -useBestContainerOS -updateHosts -doNotExportObjectsToText -enableSymbolLoading -accept_outdated           
            }
        else
            {
                if ($DatabaseInstance.Length > 0)
                    {
                        New-NavContainer -containerName $ContainerName -accept_eula -additionalParameters @('--net nat --hostname ' + $ContainerName)  -auth NavUserPassword -Credential $navServicecredential -databaseCredential $databasecredential -databaseInstance $databaseInstance -databaseName $DatabaseName -databaseServer $DatabaseServer -imageName $NAVImageName -includeCSide -licenseFile $LicenseFile -shortcuts $ShortcutsPos -useBestContainerOS -updateHosts -doNotExportObjectsToText -enableSymbolLoading -accept_outdated               
                    }  
                else
                    {
                        New-NavContainer -containerName $ContainerName -accept_eula -additionalParameters @('--net nat --hostname ' + $ContainerName)  -auth NavUserPassword -Credential $navServicecredential -databaseCredential $databasecredential -databaseName $DatabaseName -databaseServer $DatabaseServer -imageName $NAVImageName -includeCSide -licenseFile $LicenseFile -shortcuts $ShortcutsPos -useBestContainerOS -updateHosts -doNotExportObjectsToText -enableSymbolLoading -accept_outdated                   
                    }
            } #End Else

        #Creates a new User with SUPER permission
        if ($MustCreateUser)
            {
                $userCredential  = New-Object System.Management.Automation.PSCredential -argumentList $navusername, (ConvertTo-SecureString -String $navuserpwd -AsPlainText -Force)
                New-NavContainerNavUser -Credential $userCredential -containerName $ContainerName -PermissionSetId SUPER           
            }
 

}

**Comment by freddydk** [comment]
I don't know the script or where it comes from.
I also don't know where the build number comes from. Docker images are named after the application version and not after the platform version as one platform can be used for multiple application builds.
I recommend reading this: https://freddysblog.com/2019/08/20/business-central-on-docker-for-non-experts/

**Comment by freddydk** [comment]
Closing this issue as I haven't heard back. Please reopen with additional information if the problem persists.
