### ISSUE TITLE
You do not have the following permissions on Page CAL Test Tool: Execute.

### ISSUE THREAD

**Issue by syssolmarketing** [microsoft/nav-docker#412]
Our Developer is running into this error when trying to access the BC testtoolkit in the Business Central Sandbox.  He informed me it is a license error. What is causing this and how can it be fixed? Thanks
![bc connection error](https://user-images.githubusercontent.com/54630609/64630739-b927fd80-d3c3-11e9-9ea7-3cc5a3cdc69f.png)

**Comment by marknitek** [comment]
I think you need a developer license to use the test toolkit. If you have one then specify the license file when creating the container or import it with the import-bccontainerlicense function

**Comment by syssolmarketing** [comment]
thanks @marknitek 
How can I find the license file and then import it?

**Comment by NAVspecialist** [comment]
Hello
In order to get a developer license file you have to either be a Microsoft Partner or buy the license. If you are a partner then you can create it on voice, if you don't know what that is - then one of your colleagues must know.
