### ISSUE TITLE
Script does not find the folder D 

### ISSUE THREAD

**Issue by Steven-Bale** [microsoft/nav-docker#414]
Hi,

here is the powershell script that i have created and launched :

    $SetupDatabaseScript = @'
    if ($restartingInstance) {
        # Do nothing on restart
    } else {
        $databaseFolder = "D:\Database"
        Write-Host "Using $databaseFolder as new location for database files"

        $mdfName = Join-Path $databaseFolder "$DatabaseName.mdf"
        $ldfName = Join-Path $databaseFolder "$DatabaseName.ldf"
        $filesExists = (Test-Path $mdfName -PathType Leaf) -and (Test-Path $ldfName -PathType Leaf)

        Write-Host "Take database [$DatabaseName] offline"
        Invoke-SqlCmd -Query "ALTER DATABASE [$DatabaseName] SET OFFLINE WITH ROLLBACK IMMEDIATE"

        if ($filesExists) {
            Write-Host "Database files for [$DatabaseName] already exists"
        } else {
            Write-Host "Move database files for [$DatabaseName]"
            (Invoke-SqlCmd -Query "SELECT Physical_Name as filename FROM sys.master_files WHERE DB_NAME(database_id) = '$DatabaseName'").filename | ForEach-Object {
                $FileInfo = Get-Item -Path $_
                $DestinationFile = "{0}\{1}{2}" -f $databaseFolder, $DatabaseName, $FileInfo.Extension
                if (($DestinationFile -ne $mdfName) -and ($destinationFile -ne $ldfName)) { throw "Unexpected filename: $DestinationFile" }
                Copy-Item -Path $FileInfo.FullName -Destination $DestinationFile -Force
            }
        }

        Write-Host "Drop database [$DatabaseName]"
        Invoke-SqlCmd -Query "DROP DATABASE [$DatabaseName]"

        $Files = "(FILENAME = N'$mdfName'), (FILENAME = N'$ldfName')"
        Write-Host "Attach files as new Database [$DatabaseName]"
        Invoke-SqlCmd -Query "CREATE DATABASE [$DatabaseName] ON (FILENAME = N'$mdfName'), (FILENAME = N'$ldfName') FOR ATTACH"
    }
    '@

    #$additionalParameters = @("-v c:\temp\navdbfiles:c:\navdbfiles")
    #New-NavContainer #-accept_eula `
                     #"-containerName "test" `
                     #-auth NavUserPassword `
                     #-imageName "microsoft/dynamics-nav" `
                     #-additionalParameters $additionalParameters `
                     #-myScripts @{"SetupDatabase.ps1" = $SetupDatabaseScript }
                 
                    New-NavContainer -accept_eula `
                     -accept_outdated `
                     -enableSymbolLoading `
                     -includeCSide ServerName `
                     -licenseFile "C:\Users\vmadmin\Documents\Licence 2018.flf" `
                     -doNotExportObjectsToText `
                     -bakFile "C:\Users\vmadmin\Downloads\Name_backup_2019_09_04_032117_4876990\Name_backup_2019_09_04_032117_4876990.bak" `
                     -myScripts @{"SetupDatabase.ps1" = $SetupDatabaseScript}

and the error : 

NavContainerHelper is version 0.6.3.4
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Using image mcr.microsoft.com/dynamicsnav:2018-cu6-fr-ltsc2019
Removing container BCSAAS
Removing C:\ProgramData\NavContainerHelper\Extensions\BCSAAS
Creating Container BCSAAS
Using license file C:\Users\vmadmin\Documents\Licence 2018.flf
Version: 11.0.22292.0-fr
Generic Tag: 0.0.9.2
Container OS Version: 10.0.17763.316 (ltsc2019)
Host OS Version: 10.0.17763.737 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale fr-FR
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\BCSAAS\my:
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupDatabase.ps1
- SetupWebClient.ps1
Creating container BCSAAS from image mcr.microsoft.com/dynamicsnav:2018-cu6-fr-ltsc2019
da1f8b32b587c701b7ab839abc97267d119ce7bc03caae48a778427106c158e6
Waiting for container BCSAAS to be ready
Initializing...
Starting Container
Hostname is BCSAAS
PublicDnsName is BCSAAS
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Using D:\Database as new location for database files
Cannot find drive. A drive with the name 'D' does not exist.
at <ScriptBlock>, C:\Run\my\SetupDatabase.ps1: line 7
at <ScriptBlock>, C:\Run\navstart.ps1: line 108
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is BCSAAS
PublicDnsName is BCSAAS
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Using D:\Database as new location for database files
Cannot find drive. A drive with the name 'D' does not exist.
at <ScriptBlock>, C:\Run\my\SetupDatabase.ps1: line 7
at <ScriptBlock>, C:\Run\navstart.ps1: line 108
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container BCSAAS failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.3.4\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...INBCSAAS failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BCSAAS failed

Thanx for help.

**Comment by freddydk** [comment]
When running the setupdatabase.ps1 - it executes inside the container and cannot see the host.
In the container, there is nothing called d:\databases.

**Comment by Steven-Bale** [comment]
ok clear.
My initial issue was that i have no more space in c:\ folder to restore a 60 Gb customer database. So i can't restore the backup file

How can i change the folder where the database is created when the container is created ?
Or how can i do something else to do this ?

**Comment by freddydk** [comment]
I think you can share d:\somefolder to a folder in the container and use that.

**Comment by marknitek** [comment]
You cannot restore a DB larger then 10gb since the image uses sqlexpress.

For this reason we use sql server instances on the host in our team. It works great but you have to do some configuration to make it reliable. For example you have to tell docker to use a fixed ip range for its nat network since hostname resolution does not work (at least i did not get it working). So you can use the gateway ip address (which is your host) as sql server name.

Btw i would suggest to use sql server developer edition in the image. That would give us more flexibility

**Comment by Steven-Bale** [comment]
Ok thanks for your feedback.

I tried to add this to the above ²script : 
    $additionalParameters = @("-v d:database:c:\navdbfiles")
                        New-NavContainer -accept_eula `
                     -accept_outdated `
                     -enableSymbolLoading `
                     -includeCSide `
                     -doNotExportObjectsToText `
                     -bakFile "C:\Users\vmadmin\Downloads\backup_2019_09_04_032117_4876990\backup_2019_09_04_032117_4876990.bak" `
                     -additionalParameters $additionalParameters `
                     -myScripts @{"SetupDatabase.ps1" = $SetupDatabaseScript}

And i have the following error message :
cmdlet New-NavContainer at command pipeline position 1
Supply values for the following parameters:
containerName: STEVEN
NavContainerHelper is version 0.6.3.4
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Using image mcr.microsoft.com/dynamicsnav:2018-cu6-fr-ltsc2019
Creating Container STEVEN
Version: 11.0.22292.0-fr
Generic Tag: 0.0.9.2
Container OS Version: 10.0.17763.316 (ltsc2019)
Host OS Version: 10.0.17763.737 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale fr-FR
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\STEVEN\my:
- AdditionalSetup.ps1
- MainLoop.ps1
- SetupDatabase.ps1
- SetupWebClient.ps1
Creating container STEVEN from image mcr.microsoft.com/dynamicsnav:2018-cu6-fr-ltsc2019
ce004859581a62fbea9b4ad918187b4b7a51367bc2c1d2dc3a530994f9e23d1f
Waiting for container STEVEN to be ready
Initializing...
Starting Container
Hostname is STEVEN
PublicDnsName is STEVEN
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Creating Windows user vmadmin
Setting SA Password and enabling SA
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 13
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is STEVEN
PublicDnsName is STEVEN
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Creating Windows user vmadmin
Setting SA Password and enabling SA
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 13
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container STEVEN failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.3.4\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...r STEVEN failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container STEVEN failed
 
I did not understand the error message.
Please Help

**Comment by Steven-Bale** [comment]
Any idea ?

**Comment by freddydk** [comment]
If your database has the size you mentioned - then I guess i wont work as Marknitek states.
Why don't you restore the database to a SQL server and just run the container using that database.
That would be much easier - and easier for you to troubleshoot.
Or if your database is less than 10G - start the container standard (no script overrides) and restore the database afterwards, either using restore-databaseinNavcontainer or SQL Server Management Studio.
The error you get is that the service tier doesn't start - and that can be caused by a million things, by manually restoring and mounting you might have a better chance to troubleshoot..

**Comment by Steven-Bale** [comment]
I tried to restore the SQL database on the database server of my VM => it works !
but when i ran the following script to test the SQL Connection from docker, i have the following message : 
- script :
docker run -it --name sqlconnectiontest mcr.microsoft.com/dynamicsnav:2018-cu6-fr-ltsc2019 powershell -command "Invoke-Sqlcmd -ServerInstance '$databaseServerInstance' -Username '$($databaseCredential.Username)' -Password '$dbPassword' -Database '$databaseName' -Query 'SELECT COUNT(*) FROM [dbo].[User]'"

Error message : 
[H]0;C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe [?25h [H]0;Administrator: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe [?25l[91mInvoke-
Sqlcmd : A network-related or instance-specific error occurred while [m [?25h[?25l[91m
establishing a connection to SQL Server. The server was not found or was not [m   [91m
accessible. Verify that the instance name is correct and that SQL Server is [m    [91m
configured to allow remote connections. (provider: Named Pipes Provider, [m       [91m
error: 40 - Could not open a connection to SQL Server)[m[26X[26C[91m
At line:1 char:1[m[64X[64C[91m
+ Invoke-Sqlcmd -ServerInstance 'NAV2018CU6' -Username 'sbale' -Passwor ...[m     [91m
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[m[9X[9C[91m
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlExcept [m [91m
   ion[m[74X[74C
[?25h[?25l[91m    + FullyQualifiedErrorId : SqlExectionError,Microsoft.SqlServer.Management. [m [91m
   PowerShell.GetScriptCommand[m[50X[50C[91m
 [m[79X[79C
[?25h[?25l[91mInvoke-Sqlcmd : [m [?25h[?25l[91m
At line:1 char:1[m[64X[64C[91m
+ Invoke-Sqlcmd -ServerInstance 'NAV2018CU6' -Username 'sbale' -Passwor ...[m     [91m
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[m[9X[9C[91m
    + CategoryInfo          : ParserError: (:) [Invoke-Sqlcmd], ParserExceptio [m [91m
   n[m[76X[76C[91m
    + FullyQualifiedErrorId : ExecutionFailureException,Microsoft.SqlServer.Ma [m [91m
   nagement.PowerShell.GetScriptCommand[m[41X[41C[91m
 [m[79X[79C
[?25h[91m[HI[23;1H

And finally when i tried to create a new container using new-navcontainer for this database, i have the following error message : 
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 122
at <ScriptBlock>, C:\Run\navstart.ps1: line 108
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container test failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.3.4\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container test failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container test failed
 
Script : 
New-NavContainer -accept_eula `
                 -containerName "test" `
                 -Auth NavUserPassword `
                 -imageName $imageName `
                 -Credential $navcredential `
                 -databaseServer $databaseServer `
                 -databaseInstance $databaseInstance `
                 -databaseName $databaseName `
                 -databaseCredential $databaseCredential `
                 -accept_outdated

**Comment by Steven-Bale** [comment]
Or I tried to use the navserver container and change the server configuration to connect to my database but the service run but i cannot connect to windows client or web client.

Someone can help ?

**Comment by freddydk** [comment]
Is this a different problem then what this thread started out with?
Instead of trying to do everything during startup - why not start the container with the standard database - and then use Invoke-ScriptInBCContainer to restore and setup the second database - and then switch config settings + restart service tier at the end.

**Comment by Steven-Bale** [comment]
ok.

What script do i suppose to use in this command ? 
The script I use in my comments .

my database has a siez of 60 gb.

**Comment by freddydk** [comment]
It's confusing because you are hijacking one issue and continue with a second issue - it is hard to figure out what is the issue now.
but... - If you have restored your database to a SQL Server somewhere - then you should be able to configure the service tier in the container in exactly the same way as you would do if you are running an onprem installation.

**Comment by freddydk** [comment]
SQL EXPRESS inside the container can maximum be 10GB - you would need to restore your database to a "real" SQL Server and then connect a container to that SQL Server when using docker.

**Comment by Steven-Bale** [comment]
I tried it but I cannot start the nav Server because the navserver in the container cannot see the sql database.

Do you have some procedures or walkthrough ?

**Comment by freddydk** [comment]
Placing the database on the host isn't easy - the container cannot see the host. Either you need to place it on another database server or you need to make the host visible from docker.

**Comment by Steven-Bale** [comment]
ok. For the moment, i place it on another database server. But How do i made the host visible from docker ?

**Comment by freddydk** [comment]
For docker - the host is just like any other computer in the network.
So if your host can be reached (like the foreign database server) - then docker should also be able to see it.

**Comment by Steven-Bale** [comment]
ok. thank you for your help
