### ISSUE TITLE
missing image for Spanish localizacion of Business Central sandbox 14.5.35970.0

### ISSUE THREAD

**Issue by mariafores** [microsoft/nav-docker#415]
Hi,
I can't find the tags for downloading the 14.5 version for Spanish localization, in:
https://mcr.microsoft.com/v2/businesscentral/sandbox/tags/list

I tried inspecting with Get-NavContainerImageLabels the update28-es and the latest, to see if we could work with that, but both are pointing to version 14.4:

```
PS C:\WINDOWS\system32> Get-NavContainerImageLabels mcr.microsoft.com/businesscentral/sandbox:update28-es

country    : ES
created    : 201909130917
cu         : update28
eula       : https://go.microsoft.com/fwlink/?linkid=861843
legal      : http://go.microsoft.com/fwlink/?LinkId=837447
maintainer : Dynamics SMB
nav        : 
osversion  : 10.0.14393.3204
platform   : 14.0.36066.0
tag        : 0.0.9.95
version    : **14.4.35602.36102**
```

We need this in order to patch a customer extension that failed upgrade in saas to version 14.5.35970

On-prem images are correctly tagged.

Any help is appreciated.

Thanks

**Comment by freddydk** [comment]
Just requested a rebuild of the latest builds, will monitor progress.
14.5 should also be marked update29 (some was wrongfully tagges as update28)
14.4 is update28 as seen above

**Comment by freddydk** [comment]
mcr.microsoft.com/businesscentral/sandbox:update29-es-ltsc2019 should be there now
