### ISSUE TITLE
Could not able create user in Azure BC docker

### ISSUE THREAD

**Issue by sainath654** [microsoft/nav-docker#416]
Hello,

I have downloaded power-shell script to create sandbox container from the BC online, after executing the script, it installed BC Docker, it is not able to create the users.

Getting this below error.

App successfully published
Invoke GET on http://172.26.26.53:7048/NAV/api/beta/companies?$filter=name%20eq%20%27CRONUS%20UK%20Ltd.%27&tenant=default
Invoke POST on http://172.26.26.53:7048/NAV/api/Microsoft/Setup/beta/companies(b145ef70-e92d-437e-be23-39b865f70e22)/testUsers?tenant=
default
Invoke-RestMethod : {"error":{"code":"Internal_ServerError","message":"The new users do not meet the terms of the current license.
The current license allows 2 full users and 0 limited users. CorrelationId: 12530956-dd8f-40c0-8805-819ab6dfef6c."}}
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.1\Api\Invoke-NavContainerApi.ps1:139 char:5

Invoke-RestMethod -Method $Method -uri "$url" -Headers $headers @ ...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Thanks,
Sainath

**Comment by freddydk** [comment]
You can remove the Setup Test Users line - or you can use a license, which has more than 2 users.
The default CRONUS license only allows for 2 users today.
I will probably fix the script to give a better warning/description.

**Comment by lhtan-dev** [comment]
@freddydk Just FYI, i'm seeing this issue when executing the "Replace-NavServerContainer" command as well.

**Comment by freddydk** [comment]
I know. On the azure VM - you have set
![image](https://user-images.githubusercontent.com/10775043/65218034-de98c380-dab5-11e9-8114-330041612a70.png)
to Yes, which means that it will try to create test users.
The the license doesn't permit this, then I cannot do anything about that.
The behavior in Business Central, that you cannot create the users is new in the platform - we used to be able to create the users.

**Comment by abison007** [comment]
I am getting the exact same error for the Docker local container as well. Please suggest how to resolve the issue.

**Comment by freddydk** [comment]
If you dont have a licensefile you can use, then don't use the Setup Test Users command - you cannot install users if you don't have the license - nothing I can do about that.

**Comment by abison007** [comment]
I am trying to set up for the trial business central online account. can you help me to find the license file for the trial? Also, if I skip the setup test user account will not be an issue for development? I am a beginner, so the question might be not valid. Please help
