### ISSUE TITLE
Versioning of generic tags - question

### ISSUE THREAD

**Issue by liviadinu** [microsoft/nav-docker#417]
Hi,

Is there any possibility to retrieve a generic nav image with a specific GenericTag?

For example image mcr.microsoft.com/dynamicsnav:generic-1903: 
- used to be labeled as tag=0.0.9.94   / osversion=10.0.18362.295
- since 12/09/2019 is labeled as tag=0.0.9.95 / osversion=10.0.18362.356

Is there any possibility to retrieve the older version somehow? 
For example : docker pull mcr.microsoft.com/dynamicsnav:generic-0.0.9.94  (now this results in an error).

I've combed through all the relevant blog posts about tagging and versioning but I'm still facing issue with this. 

Thank you in advance.

**Comment by freddydk** [comment]
Not sure the old generic was tagged with version numbers - do you run into issues with the new version?

**Comment by liviadinu** [comment]
Yes, I'm having problems with starting up containers based on the newer generic image, in process isolation. I'm guessing the os revision might be to blame, but I cannot revert to hyperv at the moment to test that. 

The image labeled with 0.0.9.94 and osversion=10.0.18362.295 was working well, and I was just wondering if there is an easy way to revert to it again. Otherwise I will just rebuild it from the main repo, as my own generic image.

**Comment by freddydk** [comment]
Just looked in the code - it is actually tagged - but only including the os

docker pull mcr.microsoft.com/dynamicsnav:generic-0.0.9.94-ltsc2019

works.

**Comment by liviadinu** [comment]
Indeed this one works, thank you!
