### ISSUE TITLE
Codeunit 99000755 CalendarManagement missing

### ISSUE THREAD

**Issue by naveksa** [microsoft/nav-docker#419]
In one of our Apps we are using functions from base codeunit 99000755 CalendarManagement.
Apparently this codeunit no longer exists in Fall 2019 Release (version 15).
We assume, that the functions have been moved to some other codeunit
(not 7600 Calendar Management, as we first thought).
Can anyone point at where to find the functions.

Error:
Codeunit 'CalendarManagement' is missing AL(AL0185)

**Comment by naveksa** [comment]
Ups.
Sorry.
Wrong Git

**Comment by freddydk** [comment]
I assume you need to look into the impact of all the things that where moved to the System Application
