### ISSUE TITLE
webclient doesn't run from VSCode

### ISSUE THREAD

**Issue by pzentner** [Microsoft/nav-docker#42]
I am actually wondering, if this is a VSCode or a docker issue, but here is what is happening. I have the docker image running with UseSSL=N. When I try to debug from VSCode, I am first getting this output from docker:

`TimeGenerated : 9/1/2017 2:39:56 PM
EntryType     : Error
Message       : Server instance: NAV
                Category: Development
                ClientSessionId: 00000000-0000-0000-0000-000000000000
                ClientActivityId: 00000000-0000-0000-0000-000000000000
                ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
                ServerActivityId: 00000000-0000-0000-0000-000000000000
                EventTime: 09/01/2017 18:39:56
                Message <ii>Failed request -- Method:GET; Url:<ii>http://navser
                ver:7049/NAV/dev/signalr/negotiate?clientProtocol=1.4&connectio
                nData=[{"Name":"DebuggerHub"}]&Authentication=Basic
                Y2Zic2FkbWluOkNmYnMhIzAw</ii>; StatusCode:NotFound;
                ReasonPhrase:Not Found; ResponseBody: <pi>{"Message":"No HTTP
                resource was found that matches the request URI 'http://navserv
                er:7049/NAV/dev/signalr/negotiate?clientProtocol=1.4&connection
                Data=[{\"Name\":\"DebuggerHub\"}]&Authentication=Basic
                Y2Zic2FkbWluOkNmYnMhIzAw'."}</pi></ii>
                ProcessId: 2828
                Tag: 00000LY
                ThreadId: 3
                CounterInformation:`

Then, the NAV WebClient opens and after entering user credentials (NavUserPassword auth), I am getting the error ERR_TOO_MANY_REDIRECTS. This error also happens when I publish without debugging and then the web client is opened.

If I copy the URL into a new browser window (without the debugging context), it works. With debugging context I run into the same issue on chrome, but it works on Edge.

**Comment by Koubek** [comment]
I can see an error in your URL: http://navserv er:7049/NAV

**Comment by pzentner** [comment]
This must be from copying and pasting it from the PowerShell output to here. There is no " " in the url (not in launch.json and also not when I actually look at it in the browser). If that's not the issue, then I would wonder where this is coming from, since I don't have it specified with a " " anywhere.

**Comment by freddydk** [comment]
Try to remove the tenant name, so that it says tenant="".
There is a bug in the september update, which will be fixed start next week when the september update gets officially released.

**Comment by pzentner** [comment]
Thank you, Freddy! That fixes it.

**Comment by freddydk** [comment]
The reason why we need to fix the bug is, that you cannot download symbols with tenant="" - but once you have symbols, you can continue.
