### ISSUE TITLE
Problem downloading symbols

### ISSUE THREAD

**Issue by aetxebarria** [microsoft/nav-docker#420]
Hi everyone,
I've just created a docker with the last releas of BC, with this command:
`New-BCContainer -accept_eula -containerName BeteaBC -auth NavUserPassword -imageName "mcr.microsoft.com/businesscentral/onprem:es" -UpdateHosts -includeAL`
.Seems that everything is correct, but when I create a new project, and try to download the symbols, I get this error:

![imagen](https://user-images.githubusercontent.com/41778563/66033841-5cbe8680-e508-11e9-9441-9b1696e92639.png)

I'm quite lost with all this changes...
Any hint? May be I should cvreate the Container in another way??

Thank you all

**Comment by freddydk** [comment]
did you install the new .vsix in VS Code?

**Comment by freddydk** [comment]
Also you are requesting symbols on localhost / BC150
localhost is not a docker container and BC150 is not the serverinstance on docker.
You would have to specify BeteaBC as server name and BC as serverinstance in launch.json

**Comment by aetxebarria** [comment]
Sorry Freddy, I forgot to change the launch.json.... Thank you!!
