### ISSUE TITLE
Cannot download Base Application symbols from Docker

### ISSUE THREAD

**Issue by auzhhv** [microsoft/nav-docker#421]
Hi.

I am having trouble downloading Base Application symbols from docker container with BC 15. It manages to download System Application. When it tries to download the Base Application it does nothing:
![image](https://user-images.githubusercontent.com/46031720/66482881-38345280-eaa4-11e9-9e92-b007160c79a3.png)
Have waited for about 30 minutes, still the same.

I downloaded the vsix file from http: // bcno: 8080 / al-4.0.176004.vsix (which takes about 30 minutes for some reason). Installed it and uninstalled other AL extensions fra VS Code.
![image](https://user-images.githubusercontent.com/46031720/66482279-e6d79380-eaa2-11e9-93e9-8865e8ae7820.png)

I'm running the first part of the script I found here:
https://freddysblog.com/2019/09/19/publishing-a-new-base-application/

But I also tried to run the whole thing and change dependencies to the new base app.
I have tested with NO and W1 version.
Still the same issue.

![image](https://user-images.githubusercontent.com/46031720/66483038-8c3f3700-eaa4-11e9-9add-09eeb4427382.png)

Script:
```
install-module navcontainerhelper -force

$imageName = "mcr.microsoft.com/businesscentral/sandbox:w1-ltsc2019"
$containerName = "bcno"
$auth = "UserPassword"
$credential = New-Object PSCredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$licenseFile = "C:\Temp\License.flf"
$alProjectFolder = "C:\ProgramData\NavContainerHelper\BCNOBaseApp"

New-BCContainer -accept_eula `
                -imageName $imageName `
                -containerName $containerName `
                -auth $auth `
                -Credential $credential `
                -licenseFile $licenseFile `
                -updateHosts `
                -includeAL
```
Launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://bcno",
            "serverInstance": "BC",
            "authentication": "UserPassword",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true
        }
    ]
}
```
App.json:
```
{
  "id": "3d6db9ab-51ba-4f1b-b1f3-cb895c4b1c60",
  "name": "ALProject3",
  "publisher": "Default publisher",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [
    {
      "appId": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
      "publisher": "Microsoft",
      "name": "System Application",
      "version": "15.0.0.0"
    },
    {
      "appId": "437dbf0e-84ff-417a-965d-ed2bb9650972",
      "publisher": "Microsoft",
      "name": "Base Application",
      "version": "15.0.0.0"
    }
  ],
  "screenshots": [],
  "platform": "15.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "contextSensitiveHelpUrl": "https://ALProject3.com/help/",
  "showMyCode": true,
  "runtime": "4.0"
}
```

**Comment by NAVspecialist** [comment]
Hello 
Try changing

$auth = "UserPassword" to
$auth = "NavUserPassword" 

And then try again

Regards
Palle

**Comment by auzhhv** [comment]
Still same issue. Any other suggestions?

**Comment by freddydk** [comment]
Something is wrong on the machine - system seems overloaded. If downloading happens at 19Kb per second - then downloading the base app will take a very very long time.
maybe try to spin up an azure VM with aka.ms/getbc and try on that one.

**Comment by auzhhv** [comment]
It is probably correct that I cannot download the Base Application symbols due to the same issue when downloading VSIX file. But I do not understand why it is so slow. I have reset docker to factory settings, and still the same issue. The computer I use is my work computer, and it is running fine.
And I have checked that there is only one container running.

I have now tried to download BC 14 and it looks like C/Side is also slow. Is there any way to check what might be the cause, in the container? Or could it be something with a docker?

![image](https://user-images.githubusercontent.com/46031720/66488161-c8c36080-eaad-11e9-9909-2275319799d7.png)

**Comment by auzhhv** [comment]
After some searching, I discovered that several others have had problems with docks and VPN clients. I tried to disable some network adapters that belong to VPN clients. I uninstalled Global Protect VPN as I no longer use it. Looks like this solved the problem. I'm not sure if it was Global Protect VPN or any of the others that created the problem. Thanks for the help :)
