### ISSUE TITLE
Unable to find container for Nav 2016 CU 42 India

### ISSUE THREAD

**Issue by CloudViking86** [microsoft/nav-docker#423]
Steps tried / to reproduce:
https://hub.docker.com/r/microsoft/dynamics-nav/tags > (Filter Tags) > "2016-cu42-in" (No match)

Hi,

Trying to find the container for Nav 2016 CU42 with the India localization and I am unable to do so.
Is it released  and it's just me that is searching for it wrong and if not will it be released (and when)?

Thanks a bunch for all your work / Karl

**Comment by freddydk** [comment]
We don't build images for IN.
You would have to download the DVD and run the generic image with the DVD as DVDPATH in order to run IN in docker.
