### ISSUE TITLE
myScripts parameter failing for custom SetupVariables.ps1 file

### ISSUE THREAD

**Issue by MBK75** [microsoft/nav-docker#426]
I am trying to restore a client database into a Docker NAV Container (BC on-prem), and the SQL restore is timing out since the database is larger.  I have specified the following in my SetupVariables.ps1 file (the last line was added):

`if ($SqlTimeout -eq "") {
    $SqlTimeout = "300"
}
$SqlTimeout = 0`

When I run New-NavContainer and specify this file under the -myScripts parameter, I get the following error:

`Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Input string was not in a correct format.
at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
at <ScriptBlock>, C:\Run\navstart.ps1: line 156
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container XYZ failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.2\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...r XYZ failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container XYZ failed`

I have also tried other license files with the same problem.  If I remove the option for the -myScripts parameter, it works fine.  The SetupVariables.ps1 file is a copy from Git other than my timeout change.

**Comment by freddydk** [comment]
You need to cut this down to one failing New-NavContainer, and copy/paste that command + the full output here (including the full output of SetupVariables.ps1)

**Comment by freddydk** [comment]
On the other hand - if you are just trying to set sqlTimeout to 0, then you should not specify a -myscript, but instead use:

`-additionalParameters @( "-e sqlTimeout=0")
`
This should take care of that.

**Comment by MBK75** [comment]
Thank you Freddy - I will give that a shot

**Comment by MBK75** [comment]
That did the trick, thanks Freddy!  The customnavsettings were from some time back when the debugger would "disappear" when stepping through code.  I can remove it going forward.
