### ISSUE TITLE
Missing Extensions Folder in v15 OnPrem Images

### ISSUE THREAD

**Issue by marknitek** [microsoft/nav-docker#427]
I'am missing the Extensions Folders in a v15 OnPrem Image comapred to a sandbox V15 or OnPrem V14 Image. 

### V15 OnPrem (mcr.microsoft.com/businesscentral/onprem:15.0.36560.0-ch-ltsc2019)
![image](https://user-images.githubusercontent.com/2346803/67840024-3e42af80-faf5-11e9-8703-b29c4184ee2c.png)

### V14 OnPrem (mcr.microsoft.com/businesscentral/onprem:14.0.29537.0-ch-ltsc2019)
![image](https://user-images.githubusercontent.com/2346803/67840170-86fa6880-faf5-11e9-94cd-c088ff1d3c80.png)

### V15 Sandbox (mcr.microsoft.com/businesscentral/sandbox:15.0.36560.0-ch-ltsc2019)
![image](https://user-images.githubusercontent.com/2346803/67840394-156eea00-faf6-11e9-847d-9091534a09d0.png)

---
BTW it would be nice if `copy-filetonavcontainer` from navcontainerhelper could create the destination directory/path if it does not exist.

**Comment by freddydk** [comment]
The Extensions folder doesn't exist on the DVD on 15.x anymore.
On 15.x - it is called Applications and contains all apps and app sources.
On local sandbox containers there is also an applications.ch (as you see) which is the local versions of the apps and additional local apps.
For on-prem - these have been merged (as they are on the DVD)
