### ISSUE TITLE
List of environment variables when running in Docker?

### ISSUE THREAD

**Issue by CloudViking86** [microsoft/nav-docker#428]
Hello,

Highly probably that this is just lack of knowledge on my part since I'm not that experienced with Docker however we are trying to find out a list of all possible environment variables you can specify when launching a image, we've been using this as a reference;
https://github.com/microsoft/navcontainerhelper/blob/master/ContainerHandling/New-NavContainer.ps1

Are there any way to get all the possible environment variables you can specify if you decide not to use "navcontainerhelper" and run the "actual" docker-commands to launch a container?

Best Regards and thanks for your great work - CloudViking86

**Comment by freddydk** [comment]
https://github.com/microsoft/nav-docker/blob/master/generic/Run/SetupVariables.ps1

**Comment by freddydk** [comment]
With containerhelper - you specify
    -databaseServer 'server' `
    -databaseInstance 'instance' `
    -databaseName 'dbname' `
    -databaseCredential $dbcredentials

they are transferred to docker using the parameters in setupvariables - I don't remember the details.
I am working on making it easier to connect to a db server on the host - that is currently difficult.

**Comment by CloudViking86** [comment]
Think this might be the solution;
```
$databaseCredential = New-Object System.Management.Automation.PSCredential -argumentList "JanBanan", (ConvertTo-SecureString -String "P@ssword1" -AsPlainText -Force)
$dbPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($databaseCredential.Password))

docker run -e ACCEPT_EULA=Y -e ACCEPT_OUTDATED=Y -e databaseUserName=$databaseCredential.UserName -e databasePassword=$dbPassword --memory 4G -P microsoft/dynamics-nav:2017-cu3-se
```

What is weird is that if I check which datatype $dbPassword is I get "String".
So I create the password in plain text, convert it to a secure string and then decrypt it once again which should (unless I'm not thinking about something) be the same thing as giving a plaintext string directly in the beginning.

Will report back if this was the solution.

**Comment by CloudViking86** [comment]
Thanks again for your reply and sorry for my late reply.

I might be really stupid but I can't get it to work (Using SQL-auth from a NAV-container to another database).

What I've done;

1. Verified that the container can reach the other container running MSSQL:
From the NAV-container I tested with the following command;
`SQLCMD -S <mySQLserverIp>-U <SQLUsername> -P <SQLpasswordInPlaintext>`
and it works fine

2. Started the container with the following parameters;
```
$Credential = (New-Object PSCredential -ArgumentList '<SQLUsername>',(ConvertTo-SecureString -AsPlainText -Force ';<SQLpasswordInPlaintext>'))
docker run -e ACCEPT_EULA=Y -e ACCEPT_OUTDATED=Y -e databaseServer="<mySQLserverIp>" -e databaseInstance="" -e databaseName="Demo Database NAV(10-0)" -e databaseUserName="<SQLUsername>" -e databasePassword="$($Credential.Password)" -e ExitOnError=N -v C:\SharedWithVM:C:\SharedWithHost\ --memory 4G -P microsoft/dynamics-nav:2017-cu3-se
```

So if I understand your last reply correctly since the "SecureString" that is the $Credential.Password can only be decrypted and used in the context of the host and NOT decrypted while in the container you then need to use;

```
$Secure = Read-Host -AsSecureString
New-NAVEncryptionKey -KeyPath C:\sharedwithhost\nav_enc_key_2017-cu3-se\nav.key -Password $Secure

$databaseCredential = New-Object System.Management.Automation.PSCredential -argumentList "<SQLUsername>",(ConvertTo-SecureString -String "<SQLpasswordInPlaintext>" -AsPlainText -Force)

Import-NAVEncryptionKey -ServerInstance NAV -KeyPath C:\sharedwithhost\nav_enc_key\nav2017cu3se\nav.key -Password $Secure -ApplicationDatabaseServer 172.22.254.79 -ApplicationDatabaseName "Demo Database NAV(10-0)" -ApplicationDatabaseCredentials $databaseCredential -Force

```
But it still won't connect to the SQL-server.

Any obvious errors I am doing?

**Comment by tfenster** [comment]
Freddy was referring to the encryption key for secure strings (I think) not to the NAV encryption key. Anyways, this should work if you are fine with providing the password as plain text:

```
docker run -e ACCEPT_EULA=Y -e ACCEPT_OUTDATED=Y -e databaseServer="<mySQLserverIp>" -e databaseInstance="" -e databaseName="Demo Database NAV(10-0)" -e databaseUserName="<SQLUsername>" -e databasePassword="<SQLpasswordInPlaintext>" -e ExitOnError=N -v C:\SharedWithVM:C:\SharedWithHost\ --memory 4G -P microsoft/dynamics-nav:2017-cu3-se
```

If not, do you see anything in the SQL log? A failed auth attempt should appear there, if I remember correctly

**Comment by CloudViking86** [comment]
@tfenster Thank you for your reply.

When I try to launch the container using the snippet you provided I get this;
```
Initializing...
Starting Container
Hostname is a0f031280a42
PublicDnsName is a0f031280a42
Using NavUserPassword Authentication
Starting Internet Information Server
Import Encryption Key
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 122
at <ScriptBlock>, C:\Run\navstart.ps1: line 108
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
```

If I check the SQL Logs I can see that the <SQLUsername>-user is trying to authenticate against the database and I get this error;
`Login failed for user '<SQLUsername>'. Reason: Failed to open the explicitly specified database 'Demo Database NAV(10-0)'. [CLIENT: <myNAVserverIp>]`
and
`Error: 18456, Severity: 14, State: 38.`

Ok so that error is;
Failed to open the explicitly specified database
but if I PowerShell into the container I can run this command and get the query results:
```
SQLCMD -S <mySQLserverIp> -U <SQLUsername> -P <SQLpasswordInPlaintext>
1. SELECT
2. *
3. FROM
4. [Demo Database NAV (10-0)].[dbo].[Active Session]
5. GO
```

So the above command works and the login works and is the same user I used when it failed to initialize a connection with the database when I created the container.

**Comment by tfenster** [comment]
Hm, maybe a typo? Or is this by chance SQL Express? Other than that, I don't know what could still be wrong

**Comment by CloudViking86** [comment]
> Hm, maybe a typo? Or is this by chance SQL Express? Other than that, I don't know what could still be wrong

It's the latest MS SQL Developer Edition which is also running in a Docker-container (microsoft/mssql-server-windows-developer). Tried multiple times and I still get the same error, when creating the container it can't access the database and when I try connecting to the DB from the NAV-container it works flawlessly.

I'll continue troubleshooting, thanks for your help :)

**Comment by freddydk** [comment]
Maybe you have some special characters in the password, which works differently when given to the container as an environment variable than using SQLCMD password.
With docker inspect you can see all the environment variables given to the container.

**Comment by CloudViking86** [comment]
I really start to doubt my sanity;

```
$databaseServer="<MSSQLcontainerIP>"
$databaseInstance=""
$databaseName="DemoDBNav2017CU3"
$databaseCredential=Get-Credential

$dbPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($databaseCredential.Password))
$databaseServerInstance = @{ $true = "$databaseServer\$databaseInstance"; $false = "$databaseServer"}["$databaseInstance" -ne ""]
docker run -it --name sqlconnectiontest microsoft/mssql-server-windows-developer powershell -command "Invoke-Sqlcmd -ServerInstance '$databaseServerInstance' -Username '$($databaseCredential.Username)' -Password '$dbPassword' -Database '$databaseName' -Query 'SELECT * FROM [DemoDBNav2017CU3].[dbo].[Active Session]'"
```
Above works, I get the results from the query but below does not work;
```
docker run -e ACCEPT_EULA=Y -e ACCEPT_OUTDATED=Y -e databaseServer="<MSSQLcontainerIP>" -e databaseInstance="MSSQLSERVER" -e databaseName="DemoDBNav2017CU3" -e databaseUserName="NavOwner" -e databasePassword="<NavOwner_SQLpasswordPlaintext>" -e ExitOnError=N -v C:\SharedWithVM:C:\SharedWithHost\ --memory 4G -P microsoft/dynamics-nav:2017-cu3-se
```
which results in;
```
Initializing...
Starting Container
Hostname is 3bbe6bd810f1
PublicDnsName is 3bbe6bd810f1
Using NavUserPassword Authentication
Starting Internet Information Server
Import Encryption Key
Cannot establish a connection to the SQL Server/Database. 
  
This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 122
at <ScriptBlock>, C:\Run\navstart.ps1: line 108
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
```
I created a new SQL-account with a password that contains no special characters at all when trying the commands above.

Thanks again for your time and help guys, I'll continue trying to solve this on Monday.

**Comment by tfenster** [comment]
My guess would be that the direct connection (the docker run with Invoke-Sqlcmd) tries to connect without an instance name but auto-resolves to SQLEXPRESS while you set the Database Instance to MSSQLSERVER when running the NAV image

**Comment by CloudViking86** [comment]
Thanks for all the help, will create another question which I hope isn't related to the user behind the keyboard but this is how we solved it;

```
$sqldev_ip=Invoke-Expression "docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' sqldev"
docker run -P -e ACCEPT_EULA=Y -e ACCEPT_OUTDATED=Y -e databaseServer="$sqldev_ip" -e databaseInstance="" -e databaseName="Nav2017CU3W1DemoDB" -e databaseUserName="NavDBOwner" -e databasePassword="<NavOwner_SQLpasswordPlaintext>" -e username="admin" -e password="Dk2KHUvu5c9uaaaE" -e licenseFile="C:/SharedWithHost/DemoDB_NAV2017CU3W1/Cronus.flf" -e ExitOnError=N -v C:\SharedWithContainer:C:\SharedWithHost\ --memory 4G --name nav2017cu3se microsoft/dynamics-nav:2017-cu3-se
```
```
docker run -e ACCEPT_EULA=Y -e ACCEPT_OUTDATED=Y -e databaseServer="<MSSQLcontainerIP>" -e databaseInstance="MSSQLSERVER" -e databaseName="DemoDBNav2017CU3" -e databaseUserName="NavOwner" -e databasePassword="<NavOwner_SQLpasswordPlaintext>" -e ExitOnError=N -v C:\SharedWithVM:C:\SharedWithHost\ --memory 4G -P microsoft/dynamics-nav:2017-cu3-se
```

The changes being (working at the top and not working at the bottom);
* The order the environment variables were referenced in (unsure if this makes a difference?)
* Leaving "databaseInstance" as-is instead of specifying something there

Thats it, other then that there are some other environment variables we added at a later stage but that shouldn't impact the original issue.

Thanks again for your patience and assistance in this!

I'll leave this open if anyone wants to comment otherwise I'll close this tomorrow.

**Comment by freddydk** [comment]
Inspired by issues like this, I have created a way to have our containers use the SQL Server on the docker host - decribed here: https://freddysblog.com/2019/11/04/using-sql-server-on-the-host/
It runs a small code snippet in updatehosts on every restart:
```
        $gateway = (ipconfig | where-object { $_ –match "Default Gateway" } | foreach-object{ $_.Split(":")[1] } | Where-Object { $_.Trim() -ne "" } )
        if ($gateway -and ($gateway -is [string])) {
            Write-Host "Setting host.containerhelper.internal to $($gateway.Trim()) in container hosts file"
            UpdateHostsFile -hostsFile $myhostsFile -ipAddress $gateway.Trim() -hostname "host.containerhelper.internal" | Out-Null
        }
```
Which basically allows you to use host.containerhelper.internal as your database server.
http://aka.ms/getbcext has support for setting SQL Server to SQLDeveloper and use this mechanism.

Behind the scene, all boils down to a docker run like what you have above, but the sql server is just the host.

**Comment by tfenster** [comment]
@CloudViking86 maybe checking #373 also helps to understand the behavior

**Comment by freddydk** [comment]
There are a number of blog posts on https://freddysblog.com (since November 4th) which deals with this issue. Assuming that this (together with Tobias' answers) have given you the necessary info to proceed.
