### ISSUE TITLE
New NavContainer find path error docker

### ISSUE THREAD

**Issue by santhanak1** [microsoft/nav-docker#429]
Hi All,

the below is my script and i get into Cannot find path error

install-module navcontainerhelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $false

$containername = ''
$navdockerimage = 'microsoft/bcsandbox:mx'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula true `
                 -containername SGMX `
                 -imageName "mcr.microsoft.com/businesscentral/sandbox:15.0.36626.37711-mx-ltsc2016" `
                 -auth Windows `
                 -memoryLimit 3G `
                 -licenseFile "F:\Backup\Dynamics NAV\AllLicenses\KEYS DYN 365 BC ON PREMISE\BC.flf" `
                 -Credential ssan `
                 -includeCSide `
                 -updateHosts `
                 -usessl:$false `
                 -doNotExportObjectsToText `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -enableSymbolLoading `
                 -alwaysPull `
                 
Setup-NavContainerTestUsers -containerName SGMX -password 2019Nove

![image](https://user-images.githubusercontent.com/33077559/67949984-cec0e300-fc0e-11e9-8d2e-0cf4ef47991e.png)

**Comment by freddydk** [comment]
You should not have true after accept_eula
And then for -credential you specify ssanth... - shouldn't that be $credential

https://freddysblog.com/2019/08/20/business-central-on-docker-for-non-experts/

**Comment by santhanak1** [comment]
ok thanks Freddy. let me try and get back to you. 
Meanwhile, i have my own Sandbox environment. is it possible to pull my ownsandbox image? instead of Microsoft default? if yes, how the image name should be for own sandbox

**Comment by freddydk** [comment]
Are you talking about your own online sandbox environment?
And you want the same on docker?

**Comment by santhanak1** [comment]
yes my own online sandbox on local docker.

**Comment by freddydk** [comment]
mcr.microsoft.com/businesscentral/sandbox:<country>-ltsc2019 should be the version we are currently rolling out to new tenants. Your online sandbox or tenant might be behind this, then you can grab the application version number from system information and try with that (as above), but in the end - you will probably get upgraded to the latest version soon.
You can find a list of all tags (versions of containers) here: https://mcr.microsoft.com/v2/businesscentral/sandbox/tags/list
and find the one that matches your application version number best - note that this is NOT the platform version number.
