### ISSUE TITLE
Unknown manifest for ID image

### ISSUE THREAD

**Issue by lhtan-dev** [microsoft/nav-docker#431]
Docker pull mcr.microsoft.com/businesscentral/sandbox:id

docker : Error response from daemon: manifest for mcr.microsoft.com/businesscentral/sandbox:id not found: manifest unknown: manifest unknown
At line:1 char:1
+ docker pull mcr.microsoft.com/businesscentral/sandbox:id
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ...anifest unknown:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by freddydk** [comment]
Indonesia is using w1 - no special image there.
We will be adding a tag for id, but the image will be the same as w1.

**Comment by lhtan-dev** [comment]
understood most of apac is w1. The tag is already added in the current build ready to go package hence assumption it's working. Will there be any specific with ID tag and w1 going forward?

**Comment by freddydk** [comment]
I stand corrected. For the images, which uses w1 without any special collation or other things, you will have to go for the w1 image.
Sorry
