### ISSUE TITLE
Initialization of container $containerName failed 

### ISSUE THREAD

**Issue by akoliya01** [microsoft/nav-docker#432]
I am facing an below issue while I am trying to create a  business central container.

Below is the  command which I am using.

**New-BCContainer -accept_eula `
                 -alwaysPull `
                 -memoryLimit 4G `
                 -auth NavUserPassword `
                  -containerName "BC15" `
                                -PublicDnsName "BC15.local" `
                                -imageName "mcr.microsoft.com/businesscentral/sandbox" `
                                -myScripts @("https://raw.githubusercontent.com/Microsoft/nav-docker/master/generic/Run/SetupConfiguration.ps1","C:\SetupCertificate.ps1")`**

Initializing...
Starting Container
Hostname is BC5
PublicDnsName is BC15.local
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
testbcdocker.cl.local
Exception calling ".ctor" with "2" argument(s): "The system cannot find the path specified.
"
at <ScriptBlock>, C:\Run\my\SetupCertificate.ps1: line 8
at <ScriptBlock>, C:\Run\navstart.ps1: line 128
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
**Initialization of container testbcdocker failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.18\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...**
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...bcdocker failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container testbcdocker failed

**Comment by freddydk** [comment]
It is failing in your setupcertificate.ps1 script, line 8 - there is no way I can tell you what is wrong in that script.
Also why are you overriding the SetupConfiguration.ps1 with a file from the online repo (which is likely to be the same as already in the container)?

**Comment by akoliya01** [comment]
Right!
I want to bind a custome SSL certifcate with container URL.

Below is  the cdoe of SetupConfiguration.ps1



    $cert = New-SelfSignedCertificate -DnsName BC15.local -CertStoreLocation "cert:\CurrentUser\My"
    $pwd = ConvertTo-SecureString -String "KKe2U[PB#[ho8ND/" -Force -AsPlainText
    Export-PfxCertificate -Cert $cert -FilePath C:\BC15.local.pfx -Password $pwd
    $certPfxFile = "C:\BC15.local.pfx"
    $certPfxPassword = "KKe2U[PB#[ho8ND/"
    $certPfxSecurePassword = ConvertTo-SecureString -String $certPfxPassword -AsPlainText -Force
    Import-PfxCertificate -FilePath $certPfxFile -CertStoreLocation "cert:\CurrentUser\my" -Password $certPfxSecurePassword | Out-Null
    Import-PfxCertificate -FilePath $certPfxFile -CertStoreLocation "cert:\CurrentUser\root" -Password $certPfxSecurePassword | Out-Null

**Comment by freddydk** [comment]
Maybe you shouldn't share your certificate password here.

**Comment by freddydk** [comment]
I don't know whether the script works - but the certificate is placed on c:\ on the host - thus when the script is run inside the container - it is not existent.
If you add the certificate to -myscripts - it will be copied to c:\run\my inside the container (same folder as setupcertificate.ps1 and other files in myscripts)

**Comment by akoliya01** [comment]
> Maybe you shouldn't share your certificate password here.

Yeah right, Thnkas,
But that is dummy one.

**Comment by akoliya01** [comment]
Okay, 

I tried with below command.

New-NavContainer -accept_eula  `
                 -alwaysPull `
                 -memoryLimit 4G ``
                 -auth NavUserPassword `
                  -containerName "BC15" `
                                -PublicDnsName "BC15" `
                                -imageName "mcr.microsoft.com/businesscentral/sandbox" `
                                -myScripts @("C:\SetupCertificate.ps1")`




And I got below error.


Initializing...
Starting Container
Hostname is BC15
PublicDnsName is BC15.local
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
The system cannot find the path specified. (Exception from HRESULT: 0x80070003)
at <ScriptBlock>, C:\Run\my\SetupCertificate.ps1: line 3
at <ScriptBlock>, C:\Run\navstart.ps1: line 128
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container BC15 failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.18\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...bcdocker failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container testbcdocker failed

**Comment by freddydk** [comment]
add the certificate to -myscripts

-myscripts @("C:\BC15.local.pfx","c:\setupcertificate.ps1")

**Comment by freddydk** [comment]
Any luck?

**Comment by akoliya01** [comment]
No, Hard Luck.

I tried with above solution, but that didn't work.

**Comment by akoliya01** [comment]
_I use below command to create BC15 container_

**New-NavContainer -accept_eula  `
                 -alwaysPull `
                 -memoryLimit 4G `
                 -licensefile "c:\bcdocker\DEMOBC15.flf" `
                 -auth NavUserPassword `
                  -containerName "BC15" `
                  -PublicDnsName "BC15.local" `
                  -imageName "mcr.microsoft.com/businesscentral/sandbox::latest-ltsc2016" ``
                  -myScripts @("C:\BC15.local.pfx","C:\SetupCertificate.ps1")`
                  -useSSL**  


_Content of SetupCertificate.ps1 is below._

    **##$cert = New-SelfSignedCertificate -DnsName testbcdocker.cl.local -CertStoreLocation "cert:\CurrentUser\My"
    ##$pwd = ConvertTo-SecureString -String "password" -Force -AsPlainText
    ##Export-PfxCertificate -Cert $cert -FilePath C:\BC15.local.pfx -Password $pwd**

    $certPfxFile = "C:\BC15.local.pfx"
    $certPfxPassword = "password"
    $certPfxSecurePassword = ConvertTo-SecureString -String $certPfxPassword -AsPlainText -Force
    Import-PfxCertificate -FilePath $certPfxFile -CertStoreLocation "cert:\CurrentUser\my" -Password $certPfxSecurePassword | Out-Null


**After ruuning above command I facing an error.**

Files in C:\ProgramData\NavContainerHelper\Extensions\BC15\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupCertificate.ps1
- SetupWebClient.ps1
- testbcdocker.cl.local.pfx
Creating container BC15 from image mcr.microsoft.com/businesscentral/sandbox:latest-ltsc2016
Waiting for container BC15 to be ready
Initializing...
Starting Container
Hostname is BC15
PublicDnsName is BC15.locla
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
The PFX file could not be found.
at <ScriptBlock>, C:\Run\my\SetupCertificate.ps1: line 7
at <ScriptBlock>, C:\Run\navstart.ps1: line 128
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is BC15
PublicDnsName is BC15.local
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
The PFX file could not be found.
at <ScriptBlock>, C:\Run\my\SetupCertificate.ps1: line 7
at <ScriptBlock>, C:\Run\navstart.ps1: line 128
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container BC15 failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.18\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...bcdocker failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC15 failed

**Comment by freddydk** [comment]
As I already wrote in the command yesterday - when you place the file in myscripts, it will be placed in c:\run\my in the container - thus your script needs to read the certificate from there.

...
$certPfxFile = "C:\run\my\BC15.local.pfx"
...

**Comment by akoliya01** [comment]
I tried with that also, But Hard luck.

I put PFX file in folder "C:\run\my\", Still error is same as previous.

I think container is creating under below path
Files in C:\ProgramData\NavContainerHelper\Extensions\BC15\my:
-
Below all files are present in on that path.

 AdditionalOutput.ps1
- MainLoop.ps1
- SetupCertificate.ps1
- SetupWebClient.ps1
- testbcdocker.cl.local.pfx

**Comment by freddydk** [comment]
Yes, that folder on the host is mapped to c:\run\my inside the contianer and your script above (which runs inside the container) tries to load the file from c:\ - you need to modify your script.


You need to understand that the filesystem in the container is different from the filesystem on the host.
You need to understand that your script (setupcertificate.ps1) is running inside the container in the filesystem there.
Inside the container it is like a VM without a desktop - try 

enter-navcontainer containername

then you will enter the container and see the filesystem

Maybe you should read the long list of blog posts I posted March 20th 2018.

**Comment by NAVspecialist** [comment]
You should actually not have a problem with this but I noticed one thing - in one of your lines the it says

PublicDnsName is BC15.locla (the first time the container starts, the second time it seems correct)

Notice the spelling error locla vs local

**Comment by akoliya01** [comment]
Thanks!
Working now
I tried with some changes in script and it's working fine now.

What do I is, I copied .cer file from container to HOST system, after that , with the help of powershell command I installed that certificate  into ROOT directory and it's working fine.

SSL certificate is installed and now I can browse my BC sandbox container with HTTPS  and green pad lock. Now I don't need to manually download  .Cer file and than install it into ROOT directory.


 Below is the command to copy file from container to HOST system.


**PS C:\> docker cp containername:/"C:\run\certificate.cer" .\

Note : .\ means .cer file will copy to your current directory, In my case it will copy to C drive**

Thanks Freddy for your valuable suggestion regarding "You need to understand that the filesystem in the container is different from the file system on the host."

**Comment by freddydk** [comment]
gr8 - yeah it's a learning curve.
Please note that docker cp doesn't work on running hyperv containers (there is a function called copy-filetonavcontainer which works)
