### ISSUE TITLE
Issue with SSL certificate in local network.

### ISSUE THREAD

**Issue by akoliya01** [microsoft/nav-docker#433]
I created a BC container in VM with HTTPS and Self assigned certificate.

https://BC15/BC

BC container is working fine within local system, I can browse container with HTTPS from local system.

But, Whenever I tried to access BC container from another system (this system is in same local network) I am not able to browse URL with HTTPS.

It shows me an error "your connection to this site is not secure".

How I can overcome this issue.

**Comment by freddydk** [comment]
Certificate 101 - nobody trusts your self signed certificate.
On my blog there are a number of blog posts about certificates.
Please read those and you will find all the answers you need.

If the other issue you had was on order to use a self-signed certificate, then you could just have use -usessl - then you would have a self signed certificate AND a fileshare where you could download and install the certificate on machines which needs to connect.
