### ISSUE TITLE
Please update the description on Docker

### ISSUE THREAD

**Issue by sweikelt** [microsoft/nav-docker#436]
please update the description how to get bc 13 or bc 14 images.
we just tried to download BC14-CU5 but get BC13-CU5 ....
after reading
https://freddysblog.com/2019/07/14/nav-and-business-central-docker-images-moved-to-microsoft-container-registry/

i realized that i have to put a "1904" into my taglist -.-

![2020-01-07 13_39_52-● Docker_NAV-ContainerWithExtSQL-Connection_StandAlone ps1 - Scripte - Visual St](https://user-images.githubusercontent.com/2639000/71896180-4e10ec80-3153-11ea-8c9d-c7cd203eba9c.png)

why is this not written on the official docker hub page?

and which magicNumber is for BC15?

would be easier, when we could use the bc-short-version (bc130 / bc140 / bc150 or something else) for pulling some docker images

**Comment by freddydk** [comment]
I actually thought the microsoft repo on docker hub was deleted - will investigate.
BC15 is 1910

**Comment by sweikelt** [comment]
hi freddy ....deleted? hmmm that would be terrible!
you mean this 
https://hub.docker.com/r/microsoft/dynamics-nav/
and this
https://hub.docker.com/_/microsoft-businesscentral-onprem
??
where should we get the official info for the syntax, when this pages where deleted?

don't make me cry :)

**Comment by freddydk** [comment]
Official info should be in documentation - docker hub hasn't been updated for a very very long time.

**Comment by sweikelt** [comment]
> 
> 
> Official info should be in documentation - docker hub hasn't been updated for a very very long time.

roger - then i try to investigate the docs for the infos

**Comment by freddydk** [comment]
Sorry, they are not there yet.
Should have written: Official info will be in documentation.
Today - most is just on my blog.

**Comment by sweikelt** [comment]
> 
> 
> Sorry, they are not there yet.
> Should have written: Official info will be in documentation.
> Today - most is just on my blog.

i understand - i'll read your blog now more often :D - one last question:
where can i find the "magicNumbers" like 1810 / 1904 / 1910 or could it be possible to make the image-pulling more comfortable by using the "short-numbers" like BC13,BC14,BC15?

**Comment by freddydk** [comment]
They are following release months, like WindowsServer and other images.
Cannot remember the reasoning behind this.
