### ISSUE TITLE
Report Layouts Not Rendering To PDF Properly

### ISSUE THREAD

**Issue by jiraffex** [microsoft/nav-docker#437]
So I've run into an issue where report layouts are not creating identical PDF's from the web client between environment setups. Running the exact same container image (tried versions from 14.1 up to the most recent mcr.microsoft.com/businesscentral/onprem (and sandbox), with the ltsc2019 branches. The problem environment is running server core 2019 (ltsc) 17763.737.1909062324 as the docker host. With mcr.microsoft.com/businesscentral/onprem:ltsc2019 the Cronus Customer/Item report is being sent from the web client like [THIS](https://github.com/microsoft/nav-docker/files/4032807/custitem-15.pdf).

I am not using navcontainerhelper for any of this, and with minimal script changes to test this. I have read through all I can find and know that fonts must be installed on server core as they can't be part of the image. The only change to the scripts is in navstart.ps1 my file starts with:

`Invoke-Expression -Command 'c:\run\my\Fonts.ps1'`

And then Fonts.ps1 has:

`$SourceDir   = "C:\run\my\fonts\"`
`$Source      = "C:\run\my\fonts\*"`
`$Destination = (New-Object -ComObject Shell.Application).Namespace(0x14)`
`$TempFolder  = "C:\Windows\Temp\Fonts"`
`New-Item -ItemType Directory -Force -Path $SourceDir`
`New-Item $TempFolder -Type Directory -Force | Out-Null`
`Get-ChildItem -Path $Source -Include '*.ttf','*.ttc','*.otf' -Recurse | ForEach {`
`    If (-not(Test-Path "C:\Windows\Fonts\$($_.Name)")) {`
`        $Font = "$TempFolder\$($_.Name)"`
`        Copy-Item $($_.FullName) -Destination $TempFolder`
`        $Destination.CopyHere($Font,0x10)`
`        Remove-Item $Font -Force`
`    }`
`}`

I have only included Arial at this point in the fonts folder, and fonts are rendering in reports like in the link above. I add the fonts at the beginning of navstart.ps1 as I think that is the first script the container initiates and hopefully makes sure they are installed prior to the BC service starting. In our dev I like to think that a container is temporal and if it runs into an issue it should be replaced (normally we connect them to existing db's vs SQL in the container). I have read that after installing fonts the whole container must be restarted. If a container is temporal a full restart of the container while retaining settings is an issue as that implies recreating it. If it was a full Windows install with a UI restarting explorer and maybe shell32 would refresh fonts for everything. Typically this is why a restart is suggested after installing things. I am hoping the order things occur is all that is needed within server core. Maybe fonts are being added in the reports, but the report renderer is loaded before that? Fonts maybe get added but spacing and resizing things become broken? Are there services I should restart in server core?

Containers shouldn't inherit any dependencies from their hosts, should they? Having server core as the container host is the big difference here vs where it works. I am also using kubernetes via AKS to orchestrate the cluster, however I'm quite sure the docker engine (19.03.3) is still utilized to run the actual container in that setup and hopefully things run the same.

Using a container orchestrator is obviously something different from the normal nav-docker setup, but a RDL(C) report is rendered to a PDF via a standard .net dll shipped with the product. A container takes the concept of standardization of a product, and standardizes how it is hosted. 

Maybe my issue is how that is hosted, maybe it is something with how reports are rendered, or maybe it is with something navcontainerhelper does that I am not doing, but any help would be appreciated in troubleshooting it. I would have assumed the functions to create a pdf would be the same experience between containers, and unless I'm missing some setup for the containers, there is some maybe environment difference effecting the container.

From what I see, the right half of the page probably has all the report elements right aligned to the page. In those the alignments from left to right become messed up in places. Vertically (and horizonally), it looks like the element size was determined prior to rendering the fonts (maybe) and wrapping leads to things being cut off. I am hoping I'm just missing something with my font install as the best case.

**Comment by freddydk** [comment]
I didn't think it was enough to just copy the files to the fonts folder.
In my function, I also install the font:
https://github.com/microsoft/navcontainerhelper/blob/master/Misc/Add-FontsToNavContainer.ps1
You could try that

**Comment by jiraffex** [comment]
Thanks Freddy,

I for some reason had assumed that the `$Destination = (New-Object -ComObject Shell.Application).Namespace(0x14)` and `$Destination.CopyHere($Font,0x10)` were doing the same thing as the gdi32.dll import in your script, however [looking it up](https://docs.microsoft.com/en-us/previous-versions/tn-archive/ee176633(v=technet.10)?redirectedfrom=MSDN) this morning showed that wasn't the case.

Using gdi32.dll to register them and the registry changes you had in your script seems to have resolved this. I'm actually very glad it was such a simple mistake by me.

> $SourceDir   = "C:\run\my\fonts\"
$Source      = "C:\run\my\fonts\*"
$Destination = (New-Object -ComObject Shell.Application).Namespace(0x14)
$TempFolder  = "C:\Windows\Temp\Fonts"
#*******************************************************************
#*  Load C# code
#*******************************************************************
$fontCSharpCode = @'
using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.InteropServices;
namespace FontResource
{
    public class AddRemoveFonts
    {
        [DllImport("gdi32.dll")]
        static extern int AddFontResource(string lpFilename);
        public static int AddFont(string fontFilePath) {
            try 
            {
                return AddFontResource(fontFilePath);
            }
            catch
            {
                return 0;
            }
        }
    }
}
'@
Add-Type $fontCSharpCode
#* Create hashtable containing valid font file extensions and text to append to Registry entry name.
$hashFontFileTypes = @{}
$hashFontFileTypes.Add(".fon", "")
$hashFontFileTypes.Add(".fnt", "")
$hashFontFileTypes.Add(".ttf", " (TrueType)")
$hashFontFileTypes.Add(".ttc", " (TrueType)")
$hashFontFileTypes.Add(".otf", " (OpenType)")
$fontRegistryPath = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts"
#* Create the source directory if it doesn't already exist
New-Item -ItemType Directory -Force -Path $SourceDir
New-Item $TempFolder -Type Directory -Force | Out-Null
Get-ChildItem -Path $Source -Include '*.ttf','*.ttc','*.otf' -Recurse | ForEach {
    If (-not(Test-Path "C:\Windows\Fonts\$($_.Name)")) {
        $Font = "$TempFolder\$($_.Name)"
        #* Copy font to local temporary folder
        Copy-Item $($_.FullName) -Destination $TempFolder
        #* Install font
        $Destination.CopyHere($Font,0x10)
        $path = "C:\Windows\Fonts\$($_.Name)"
        $fileDir  = split-path $path
        $fileName = split-path $path -leaf
        $fileExt = (Get-Item $path).extension
        $fileBaseName = $fileName -replace($fileExt ,"")
        $shell = new-object -com shell.application
        $myFolder = $shell.Namespace($fileDir)
        $fileobj = $myFolder.Items().Item($fileName)
        $fontName = $myFolder.GetDetailsOf($fileobj,21)
        if ($fontName -eq "") { $fontName = $fileBaseName }
        $retVal = [FontResource.AddRemoveFonts]::AddFont($path)
        if ($retVal -eq 0) {
            Write-Host -ForegroundColor Red "Font `'$($path)`'`' installation failed"
        } else {
            Write-Host -ForegroundColor Green "Font `'$($path)`' installed successfully"
            Set-ItemProperty -path "$($fontRegistryPath)" -name "$($fontName)$($hashFontFileTypes.item($fileExt))" -value "$($fileName)" -type STRING
        }
        #* Delete temporary copy of font
        Remove-Item $Font -Force
    }
}

**Comment by jiraffex** [comment]
@freddydk With MICR support in MS cloud BC coming with 15.3, is it a reasonable request for nav-docker images to automatically install fonts located in maybe c:\run\my\fonts automatically when starting? I know navcontainerhelper has this functionality, and you can't include fonts in the image, but are there restrictions or issues on including font installing within the docker image?

**Comment by freddydk** [comment]
I will add this idea to the idea list. If I do this, the functionality would be in the generic layer and will only be available in new images created after the update.

If you put the above script in AdditionalSetup.ps1 in a folder you share to the my folder together with your fonts, then that will automatically get called and installed and since you need to share a my folder anyway, it seems like an easy approach.

(Like containerhelper is sharing a my folder as well:-))
