### ISSUE TITLE
Initialization of container * failed (DB Backup)

### ISSUE THREAD

**Issue by pjaubassa** [microsoft/nav-docker#438]
Im trying to run a bc docker container with a db backup.

Inspired from freddysblog (https://freddysblog.com/2018/03/20/navcontainerhelper-specify-your-own-database-backup-file-to-use-with-a-nav-container/) i wrote some Powershell scripts to do the job.

Here is one of my scripts:
`$imageName = "mcr.microsoft.com/businesscentral/onprem:1810-cu1-de-ltsc2016"
$navcredential = New-Object System.Management.Automation.PSCredential -argumentList "admin", (ConvertTo-SecureString -String "P@ssword1" -AsPlainText -Force)
New-BCContainer -accept_eula `
 -updateHost `
 -containerName test `
 -ACCEPT_OUTDATED `
 -auth NavUserPassword `
 -credential $navcredential `
 -imageName $imageName `
 -additionalParameters @('--volume c:\temp\navdbfiles:c:\temp', '--env bakfile="c:\temp\bcDev.bak"')`

I tryed so much different things (container versions, NAVContainerHelper versions and parameter like -isolation hyperv, with and without licence file, backup from device or dropbox link) but it ends everytime in this Error:

Initialization of container test failed
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.24\ContainerHandling\Wait-NavContainerReady.ps1:44 Zeichen:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container test failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container test failed

Here is the complete output:
NavContainerHelper is version 0.6.4.24
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 1903
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Using image mcr.microsoft.com/businesscentral/onprem:1810-cu1-de-ltsc2016
Removing container test
Removing test from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\test
Creating Container test
Version: 13.1.25940.0-de
Style: onprem
Platform: 13.0.25924.0
Generic Tag: 0.0.9.5
Container OS Version: 10.0.14393.2906 (ltsc2016)
Host OS Version: 10.0.18362.535 (1903)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale de-DE
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\test\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- SetupWebClient.ps1
- updatehosts.ps1
Creating container test from image mcr.microsoft.com/businesscentral/onprem:1810-cu1-de-ltsc2016
232f798e3bef4e3dd44a74520a270297483af70d50203fb460cae6df9735eba5
Waiting for container test to be ready
Initializing...
Setting host.docker.internal to 172.31.2.221 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 172.31.2.221 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.28.32.1 in container hosts file
Starting Container
Hostname is test
PublicDnsName is test
WARNING: Container starts with TimeZone = MitteleuropÃ¤ische Zeit, which is not recognized in the list of TimeZones.
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Using Database .bak file 'c:\temp\bcDev.bak'
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 7A589DEB69061F61C688669EF2BCE783098FE86A
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Setting host.docker.internal to 172.31.2.221 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 172.31.2.221 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.28.32.1 in container hosts file
Starting Container
Hostname is test
PublicDnsName is test
WARNING: Container starts with TimeZone = MitteleuropÃ¤ische Zeit, which is not recognized in the list of TimeZones.
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Using Database .bak file 'c:\temp\bcDev.bak'
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 7A589DEB69061F61C688669EF2BCE783098FE86A
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container test failed
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.24\ContainerHandling\Wait-NavContainerReady.ps1:44 Zeichen:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container test failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container test failed

I can ran any container without backup.

Docker is running on Win10 on device D:\
Deamon settings:
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "experimental": false,
  "graph": "D:\\Docker"
}

Any suggestions?

**Comment by freddydk** [comment]
After trying to start the container, you can run

Get-NavContainerEventLog -containername <name>

to download the event log.
That should give you an indication of why it didn't start.
Typically this is because the .bak file isn't the same version as the container.

**Comment by pjaubassa** [comment]
Solved!
Get-NavContainerEventLog -containername helped me alot.
I had the wrong license file and the wrong container version.
Thanks alot for your help
