### ISSUE TITLE
Entitlements in :Base Image

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/nav-docker#439]
In the past, a w1 image did not contain any data. instead there was the base image which contained some data for testing. I have gotten into the habit of always using the base image when I want to develop something for several countries or appsource.

But now I found out that there are no entitlements in the base image.
Tested with mcr.microsoft.com/businesscentral/sandbox:base-ltsc2019

Is this on purpose and there a special reason?

**Comment by freddydk** [comment]
the base image is really onprem w1 image - and the local images are then replacements of the databases (which is why we have a w1 vs. base).
It has always been like this and it isn't anything I can change.

**Comment by ChrisBlankDe** [comment]
I think it's a pity that there is no image that doesn't include country customizations, but still behaves like SaaS. So we always need the symbols of w1 or base when we are developing and for testing we have to use a localized image.

Thanks for the clarification.

**Comment by freddydk** [comment]
Yeah, I tried for pushing to have demo data in the w1 image - but that has been declined.
Only option really is w1 + a rapidstart package
