### ISSUE TITLE
The remote name could not be resolved

### ISSUE THREAD

**Issue by dkorinets** [Microsoft/nav-docker#44]
During publish my extension the error is occurred. 
 
[2017-09-04 11:52:43.38] Error: An error occurred while sending the request.
The remote name could not be resolved: 'docker_id'

[2017-09-04 11:52:44.19] Error: An internal error has occurred

**Comment by freddydk** [comment]
Could you provide some more info?
Is this VSCode?
How does launch.json and app.json look?
What is the name of your container?
And maybe a screenshot of VSCode?

**Comment by dkorinets** [comment]
the error is shown in VSCode Debug Console 
![111](https://user-images.githubusercontent.com/31474116/30025916-6762941c-9183-11e7-8766-2700215ff7a3.jpg)

**Comment by freddydk** [comment]
Try to ping 4d6047c27961 - and see if it resolves - if not then that is a docker specific problem, not sure why this doesn't work. You can fix this by adding your container to the hosts file in c:\windows\system32\drivers\etc - but it shouldn't be necessary, docker should handle this if correctly installed.

A few comments:

I typically do docker run --name navserver --hostname navserver .... - then my instance is navserver and I don't have to modify launch.json if i redeploy docker container.
I also typically use -e usessl=N - to avoid https with a self-signed certificate, which might cause problems.

**Comment by freddydk** [comment]
If this is the september pre-preview, then you also need to set tenant = "" in order to debug.
Note, that tenant needs to be "default" to download symbols.

**Comment by dkorinets** [comment]
works, thank You
