### ISSUE TITLE
insider bconprem-master gone?

### ISSUE THREAD

**Issue by cmuris** [microsoft/nav-docker#441]
Hi,

may be i missed something, but there used to be a bconprem-master in the insider registry, which I can't find anymore. Is that intentional?

**Comment by freddydk** [comment]
Yes.
We haven't been updating that for the last half year and the repo was deleted during cleanup.

**Comment by yrest** [comment]
Is it some sort of indication that onprem is neglected and / or deprecating or there are plans to resurrect those images?

**Comment by freddydk** [comment]
I guess people can come to any conclusion they want, but I do have a hard time seeing how anybody can conclude that.
Our internal daily builds for onprem are 2-5 days delayed (compared to sandbox) and it was very confusing that the versions on these two was never the same.
Also, I actually didn't build onprem images for 4 months before I deleted the repo - and nobody gave any feedback.
if you grab the :base image you will get onprem w1 - but thats it.

**Comment by cmuris** [comment]
I guess it was ahead of its time :) 
We'd like to move our OnPrem vertical to BC16 before it is RTM, which isn't w1. Can I simply change the extension target level in the sandbox container and then I basically have a OnPrem version?

**Comment by freddydk** [comment]
I think you can add these parameters to a new-bccontainer on a sandbox image to make it behave like an onprem image. You would still have Saas demo data and the default apps installed in saas - not sure what the difference is there.

```
    -additionalParameters @('--env IsBcSandbox=N') `
    -myscripts @(@{'SetupDatabase.ps1' = @'
. "c:\run\SetupDatabase.ps1"
if (!$restartingInstance) { 
    "Membership Entitlement","Entitlement Set","Entitlement","User Plan`$63ca2fa4-4f03-4f2b-a480-172fef340d3f","Plan`$63ca2fa4-4f03-4f2b-a480-172fef340d3f" | % {
        Write-Host "Remove Data from $_"
        Invoke-sqlcmd -serverinstance $databaseServerInstance -Database $databaseName -query "DELETE FROM dbo.[$_]"
    }
}
'@})
```

Note, that I haven't tested this in detail.

**Comment by cmuris** [comment]
Ok, thanks! I will check

**Comment by yrest** [comment]
What’s the exact address for base image?

Pulling image bcinsider.azurecr.io/bconprem-master:base-ltsc2019
DockerDo : Error response from daemon: manifest for bcinsider.azurecr.io/bconprem-master:base-ltsc2019 not found: manifest unknown: manifest unknown

**Comment by freddydk** [comment]
bcsandbox-master

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Yury Rest <notifications@github.com>
Sendt: Monday, January 13, 2020 10:20:58 PM
Til: microsoft/nav-docker <nav-docker@noreply.github.com>
Cc: Freddy Kristiansen <Freddy.Kristiansen@microsoft.com>; State change <state_change@noreply.github.com>
Emne: Re: [microsoft/nav-docker] insider bconprem-master gone? (#441)


What’s the exact address for base image?

Pulling image bcinsider.azurecr.io/bconprem-master:base-ltsc2019
DockerDo : Error response from daemon: manifest for bcinsider.azurecr.io/bconprem-master:base-ltsc2019 not found: manifest unknown: manifest unknown

**Comment by yrest** [comment]
Great thanks Freddy, that seems to be ok.
No plans for country onprem insider images?

**Comment by freddydk** [comment]
At this time, no plans to do insider onprem images.
