### ISSUE TITLE
How to change a parameter ok NAV Server Config in NAV Container

### ISSUE THREAD

**Issue by Steven-Bale** [microsoft/nav-docker#443]
Hello,

I tried to find the similar cmdlet as set-navserverconfiguration in a container.
Is there any similar cmdlet?

**Comment by freddydk** [comment]
Invoke-ScriptInNavContainer -containername <name> -scriptblock {
    Set-NavServerConfiguration -InstanceName BC/NAV -...
    Set-NavServerInstance -InstanceName BC/NAV -restart
}

(or docker exec if you don't use navcontainerhelper).
for docker exec you might need to run c:\run\prompt.ps1 to import all NAV PS modules.

**Comment by Steven-Bale** [comment]
ok thanks it is useful.

the windows client and web client only works with the IP Address as database server in my container. So I change the parameter with this solution that you give.

is there any tips to avoid this ?

**Comment by freddydk** [comment]
Are you using the NavContainerHelper to create your container?

**Comment by Steven-Bale** [comment]
Yes. But i dont want to create a new one.
I want to modify a parameter : the ip address for instance because i cant access to NAV windows or web client with the container name.
For example, containername = test, i cant access to http://test/NAV, i have to replace test by the IP Address if i want that it works;

**Comment by Steven-Bale** [comment]
and the problem is that the ip address change after a restart...

**Comment by freddydk** [comment]
If you specify -updatehosts when creating the container, navcontainerhelper will update the hosts file to allow you to use container name (and will update upon restart).
https://freddysblog.com/2019/08/20/business-central-on-docker-for-non-experts/
The database configuration inside the container is localhost - and normally you don't need to change that.

**Comment by freddydk** [comment]
In general, my recommendation is not to try and keep a container running.
Keep the script, which generates the container.
If you need to keep a database, you should consider placing the database on a sql server (possibly on the host)

**Comment by freddydk** [comment]
Closing this as it seems to be resolved

**Comment by jiraffex** [comment]
as an alternative, you can also make use of static IP's for containers and start them using that specific IP, but this case is more for when you want a container accessible beyond the docker host and accessible to your local network. Versus using the docker network settings, you can create a docker network with 'transparent' as the network type (an overlay vs a bridge), and containers can be configured on the same network as the container host.

After this you can make a DNS entry to point a hostname at your container which is accessible on your local domain. As Freddy mentioned, databases can be kept on external SQL servers, this setup would let your containers access SQL servers beyond the container host in your network easier.

By default I believe docker uses a bridge network, which lets containers share the host IP address for external things in a non default world, but by default the network created by docker after install does not allow external access as per https://docs.docker.com/network/bridge/ .
