### ISSUE TITLE
Initialization of container failed (BC15.02)

### ISSUE THREAD

**Issue by tomasevicstefan** [microsoft/nav-docker#444]
Hi, 

I'm having a problem building environment for business central 15.2, and i don't get any errors in event log for initializing container. What do I missing?

```
Starting Service Tier
Service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)' cannot be started due to the following error: Cannot start service MicrosoftDynamicsNavServer$BC on computer '.'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 142
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
System.Management.Automation.RuntimeException Initialization of container IcelandCloud failed
```

Image: _mcr.microsoft.com/businesscentral/onprem:15.2.39040.0-is-ltsc2019_
Docker Server Version is 18.09.3
Using process isolation
Winver 1809

**Comment by freddydk** [comment]
Sounds like a duplicate of this: https://github.com/microsoft/navcontainerhelper/issues/836
Could you try the same workaround (hyperv isolation)

**Comment by freddydk** [comment]
and https://github.com/microsoft/navcontainerhelper/issues/771

**Comment by tomasevicstefan** [comment]
> Sounds like a duplicate of this: [microsoft/navcontainerhelper#836](https://github.com/microsoft/navcontainerhelper/issues/836)
> Could you try the same workaround (hyperv isolation)

Thanks, hyperv solve problem.
