### ISSUE TITLE
Can't sign into navserver\sqlexpress in MS SSMS on Docker Azure VM

### ISSUE THREAD

**Issue by garnilsen** [microsoft/nav-docker#446]
Hello,
I am having trouble trying to login to navserver\sqlexpress on Sql Server Management Studio using Windows Authentication.  I've been able to connect previously on this VM but all of a sudden I can't anymore.  I'm using a VM that I created on portal.azure.com.  The Docker version that I'm using is: "mcr.microsoft.com/businesscentral/sandbox:15.0.36626.39709-us" 
It gives me this error when I try to login to SQL:
![image](https://user-images.githubusercontent.com/36202460/74559240-87decb00-4f29-11ea-98d1-76a610380a44.png)
On this machine I am developing extensions in AL and publishing by hitting F5.  Business Central launches just fine and I can debug the code just fine.  So the SQL server is running and attaching the code to the database.  I've tried to login to the SQL server using SQL Server Authentication and it gives me the same error.
I have stopped the docker image and started it and ran "docker logs navserver" and it says it started the Local SQL Server and no errors are present.  
Is there anything else that I can do to be able to log into the SQL Server database?

Thanks,

Gary

**Comment by freddydk** [comment]
I think this is due to this: https://freddysblog.com/2020/02/14/hyperv-isolation-to-the-rescue/
If you uninstall the February Security Update or use hyperv you should be back to normal

**Comment by freddydk** [comment]
Haven't heard anything on this issue, please reopen with more info if the problem persists.
