### ISSUE TITLE
Visual Studio Code: Username Authentication

### ISSUE THREAD

**Issue by MathijsSchols** [Microsoft/nav-docker#45]
Is it possible to connect visual studio code to a docker container using username authentication?
I've setup a docker container without SSL, and no windows authentication, but i'm failing to connect Visual Studio Code to it.

When i set "windowsAuthentication" to false in launch.json, it seems that it's trying to use O365-authentication (?):
![image](https://user-images.githubusercontent.com/31645516/30048129-02c2a230-9215-11e7-9b65-5fa31623e348.png)

**Comment by tfenster** [comment]
Yes, just change it to
```
"authentication": "UserPassword",
```

**Comment by freddydk** [comment]
Tobias is right. This seems like an old launch.json. You should try AL GO! to see what changes has happened to launch and app.json

**Comment by MathijsSchols** [comment]
You are both correct Tobias and Freddy.
I was using the wrong version of the AL Extension.
After i installed the correct version from the vsix, i was able to set it to "authentication": "UserPassword" and download the symbols.
Thanks for your fast feedback!
