### ISSUE TITLE
Availability of Nav2016 images

### ISSUE THREAD

**Issue by elweilando** [microsoft/nav-docker#451]
The latest nav2016 images seems to be CU42 from April 2019 (Release 51234). [https://hub.docker.com/r/microsoft/dynamics-nav/tags?name=9.0](https://hub.docker.com/r/microsoft/dynamics-nav/tags?name=9.0)

Is there a difference between the product life cycle and the availability of docker images?

**Comment by freddydk** [comment]
https://freddysblog.com/2019/07/14/nav-and-business-central-docker-images-moved-to-microsoft-container-registry/

Will try to get docker hub updated
