### ISSUE TITLE
Error while export objects as text "[17367042] The type '5056' was not defined for the function."

### ISSUE THREAD

**Issue by elweilando** [microsoft/nav-docker#452]
If I try to export objects as text I get this error.

Image is mcr.microsoft.com/dynamicsnav:2016-cu12-de

```
PS C:\run> Export-NAVApplicationObject -Username test -Password test -DatabaseName test -Path c:\test.txt -DatabaseServer test.database.windows.net
Export-NAVApplicationObject : : [17367042] The type '5056' was not defined for the function.
At line:1 char:1
+ Export-NAVApplicationObject -Username n4devvm -Password Java6667 -Dat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Export-NAVApplicationObject
```

**Comment by freddydk** [comment]
Are you trying to use the export-navapplicationobject to export objecs from an Azure SQL Server?
I don't know whether that is supported - but it has likely nothing to do with docker.
I think you would find the same behavior if you download the DVD, install it and try, right?

**Comment by elweilando** [comment]
> Are you trying to use the export-navapplicationobject to export objecs from an Azure SQL Server?
> I don't know whether that is supported - but it has likely nothing to do with docker.

Yes. It worked definitely from an azure sql server until last week very well.
It still works with these images
mcr.microsoft.com/dynamicsnav:2017-cu14-de-ltsc2019
mcr.microsoft.com/dynamicsnav:2018-cu12-fi-ltsc2019

It's the same azure database server with same credentials, just another database.

**Comment by freddydk** [comment]
Not sure whether NAV 2016 supports Azure SQL at all.
You can try to download and install the DVD and see whether it gives the same result.

**Comment by elweilando** [comment]
I tested the export with another database for nav2016 on the same Azure SQL. mcr.microsoft.com/dynamicsnav:2016-cu12-de works also with Azure SQL. 
It seems to be something with this specific database.
