### ISSUE TITLE
ARM template - additional container [BC15CU2] throw "Initialization of container $containerName failed"

### ISSUE THREAD

**Issue by beemubotokka** [microsoft/nav-docker#453]
Hi, 
I did clean start with ARM template (http://aka.ms/getbc) and at first round everything went well. Then I executed following container clause:
New-NavContainer -accept_eula -containerName "bc15cu2fi" -imageName "mcr.microsoft.com/businesscentral/onprem:cu2-fi-ltsc2019" -auth NavUserPassword -licenseFile "https://www.dropbox.com/..license.flf?dl=1" -useTraefik

Output:
NavContainerHelper is version 0.6.5.0
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Enabling SSL as otherwise all clients will see mixed HTTP / HTTPS request, which will cause problems e.g. on the mobile and modern windows clients
Pulling image mcr.microsoft.com/businesscentral/onprem:cu2-fi-ltsc2019
cu2-fi-ltsc2019: Pulling from businesscentral/onprem
65014b3c3121: Already exists
faf31ee0aa3d: Pulling fs layer
12dc3659100c: Pulling fs layer
f414e541ee3c: Pulling fs layer
8c280c670523: Pulling fs layer
45179d426cc4: Pulling fs layer
ddcea2e95c2e: Pulling fs layer
5f5dad69e903: Pulling fs layer
5ef637fb39f3: Pulling fs layer
d7d509fe501b: Pulling fs layer
8c280c670523: Waiting
32da2edb848e: Pulling fs layer
45179d426cc4: Waiting
0ea6a41afa6e: Pulling fs layer
ddcea2e95c2e: Waiting
fa725046e829: Pulling fs layer
5f5dad69e903: Waiting
40d6ced096a2: Pulling fs layer
5ef637fb39f3: Waiting
b49f8afa3690: Pulling fs layer
d7d509fe501b: Waiting
32da2edb848e: Waiting
3565a05d7e31: Pulling fs layer
11f9ea515e55: Pulling fs layer
4920f1ed1877: Pulling fs layer
95c5c607dcc4: Pulling fs layer
a2304198e6db: Pulling fs layer
43a6f0bcd507: Pulling fs layer
c8fcc712f7c8: Pulling fs layer
3b2938fa142f: Pulling fs layer
5eecb3513856: Pulling fs layer
5baae48cbabb: Pulling fs layer
2d23dee53e78: Pulling fs layer
04acc9e8a96c: Pulling fs layer
0faf08e1a04a: Pulling fs layer
a442328f57e0: Pulling fs layer
0ff77d5b8c75: Pulling fs layer
babff80b5eca: Pulling fs layer
5df3252e5f4a: Pulling fs layer
54a26a6ec7d0: Pulling fs layer
38f03e0d0643: Pulling fs layer
ca17e9d69a71: Pulling fs layer
fadae8a727c3: Pulling fs layer
705ce916a045: Pulling fs layer
0ea6a41afa6e: Waiting
fa725046e829: Waiting
40d6ced096a2: Waiting
b49f8afa3690: Waiting
3565a05d7e31: Waiting
11f9ea515e55: Waiting
4920f1ed1877: Waiting
95c5c607dcc4: Waiting
a2304198e6db: Waiting
43a6f0bcd507: Waiting
c8fcc712f7c8: Waiting
3b2938fa142f: Waiting
5eecb3513856: Waiting
5baae48cbabb: Waiting
2d23dee53e78: Waiting
04acc9e8a96c: Waiting
0faf08e1a04a: Waiting
a442328f57e0: Waiting
0ff77d5b8c75: Waiting
babff80b5eca: Waiting
5df3252e5f4a: Waiting
54a26a6ec7d0: Waiting
38f03e0d0643: Waiting
ca17e9d69a71: Waiting
fadae8a727c3: Waiting
705ce916a045: Waiting
f414e541ee3c: Verifying Checksum
f414e541ee3c: Download complete
8c280c670523: Verifying Checksum
8c280c670523: Download complete
12dc3659100c: Verifying Checksum
12dc3659100c: Download complete
ddcea2e95c2e: Verifying Checksum
ddcea2e95c2e: Download complete
faf31ee0aa3d: Verifying Checksum
faf31ee0aa3d: Download complete
5f5dad69e903: Verifying Checksum
5f5dad69e903: Download complete
5ef637fb39f3: Download complete
d7d509fe501b: Verifying Checksum
d7d509fe501b: Download complete
0ea6a41afa6e: Verifying Checksum
0ea6a41afa6e: Download complete
fa725046e829: Verifying Checksum
fa725046e829: Download complete
40d6ced096a2: Verifying Checksum
40d6ced096a2: Download complete
45179d426cc4: Verifying Checksum
45179d426cc4: Download complete
3565a05d7e31: Verifying Checksum
3565a05d7e31: Download complete
11f9ea515e55: Verifying Checksum
11f9ea515e55: Download complete
b49f8afa3690: Verifying Checksum
b49f8afa3690: Download complete
95c5c607dcc4: Verifying Checksum
95c5c607dcc4: Download complete
a2304198e6db: Verifying Checksum
a2304198e6db: Download complete
43a6f0bcd507: Verifying Checksum
43a6f0bcd507: Download complete
4920f1ed1877: Verifying Checksum
4920f1ed1877: Download complete
3b2938fa142f: Verifying Checksum
3b2938fa142f: Download complete
c8fcc712f7c8: Verifying Checksum
c8fcc712f7c8: Download complete
5eecb3513856: Verifying Checksum
5eecb3513856: Download complete
5baae48cbabb: Verifying Checksum
5baae48cbabb: Download complete
2d23dee53e78: Verifying Checksum
2d23dee53e78: Download complete
04acc9e8a96c: Verifying Checksum
04acc9e8a96c: Download complete
0faf08e1a04a: Verifying Checksum
0faf08e1a04a: Download complete
0ff77d5b8c75: Verifying Checksum
0ff77d5b8c75: Download complete
babff80b5eca: Verifying Checksum
babff80b5eca: Download complete
5df3252e5f4a: Verifying Checksum
5df3252e5f4a: Download complete
54a26a6ec7d0: Verifying Checksum
54a26a6ec7d0: Download complete
38f03e0d0643: Verifying Checksum
38f03e0d0643: Download complete
ca17e9d69a71: Verifying Checksum
ca17e9d69a71: Download complete
32da2edb848e: Verifying Checksum
32da2edb848e: Download complete
705ce916a045: Verifying Checksum
705ce916a045: Download complete
fadae8a727c3: Verifying Checksum
fadae8a727c3: Download complete
a442328f57e0: Verifying Checksum
a442328f57e0: Download complete
faf31ee0aa3d: Pull complete
12dc3659100c: Pull complete
f414e541ee3c: Pull complete
8c280c670523: Pull complete
45179d426cc4: Pull complete
ddcea2e95c2e: Pull complete
5f5dad69e903: Pull complete
5ef637fb39f3: Pull complete
d7d509fe501b: Pull complete
32da2edb848e: Pull complete
0ea6a41afa6e: Pull complete
fa725046e829: Pull complete
40d6ced096a2: Pull complete
b49f8afa3690: Pull complete
3565a05d7e31: Pull complete
11f9ea515e55: Pull complete
4920f1ed1877: Pull complete
95c5c607dcc4: Pull complete
a2304198e6db: Pull complete
43a6f0bcd507: Pull complete
c8fcc712f7c8: Pull complete
3b2938fa142f: Pull complete
5eecb3513856: Pull complete
5baae48cbabb: Pull complete
2d23dee53e78: Pull complete
04acc9e8a96c: Pull complete
0faf08e1a04a: Pull complete
a442328f57e0: Pull complete
0ff77d5b8c75: Pull complete
babff80b5eca: Pull complete
5df3252e5f4a: Pull complete
54a26a6ec7d0: Pull complete
38f03e0d0643: Pull complete
ca17e9d69a71: Pull complete
fadae8a727c3: Pull complete
705ce916a045: Pull complete
Digest: sha256:94ee558b54e242657432b1817911678ca9011b337b6e4c64
Status: Downloaded newer image for mcr.microsoft.com/businesscentral/onprem:cu2-fi-ltsc2019
Using image mcr.microsoft.com/businesscentral/onprem:cu2-fi-ltsc2019
PublicDnsName is ...cloudapp.azure.com
Creating Container bc15cu2fi
Version: 15.2.39040.0-fi
Style: onprem
Platform: 15.0.38951.0
Generic Tag: 0.0.9.97
Container OS Version: 10.0.17763.914 (ltsc2019)
Host OS Version: 10.0.17763.1098 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale fi-FI
Using process isolation
Adding special CheckHealth.ps1 to enable Traefik support
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file https://www.dropbox.com..license.flf?dl=1
Downloading C:\ProgramData\NavContainerHelper\Extensions\bc15cu2fi\my\license.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\bc15cu2fi\my:
- AdditionalOutput.ps1
- CheckHealth.ps1
- license.flf
- MainLoop.ps1
Creating container bc15cu2fi from image mcr.microsoft.com/businesscentral/onprem:cu2-fi-ltsc2019
17e8ec69e1cc5712f4162ee8f314271c165a175f31f4b
Waiting for container bc15cu2fi to be ready
Initializing...
Starting Container
Hostname is innodemobc
PublicDnsName is ...northeurope.cloudapp.azure.com
You are trying to run a container which is more than 90 days old.
    Microsoft recommends that you always run the latest version of our containers.
    Set the environment variable ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.
at <ScriptBlock>, C:\Run\navstart.ps1: line 54
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is innodemobc
PublicDnsName is ...northeurope.cloudapp.azure.com
You are trying to run a container which is more than 90 days old.
    Microsoft recommends that you always run the latest version of our containers.
    Set the environment variable ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.
at <ScriptBlock>, C:\Run\navstart.ps1: line 54
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container bc15cu2fi failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.0\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...c15cu2fi failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container bc15cu2fi failed
 

PS C:\demo>        docker ps -a
CONTAINER ID        IMAGE                                                      COMMAND                  CREATED             STATUS                      PORTS                               
                               NAMES
17e8ec69e1cc        mcr.microsoft.com/businesscentral/onprem:cu2-fi-ltsc2019   "powershell -Commandâ€¦"   13 minutes ago      Up 13 minutes (unhealthy)   80/tcp, 443/tcp, 1433/tcp, 7045-70
49/tcp, 8080/tcp                 bc15cu2fi
6771cff92236        mcr.microsoft.com/dynamicsnav:10.0.17763.1040-generic      "powershell -Commandâ€¦"   About an hour ago   Up 51 minutes (healthy)     80/tcp, 443/tcp, 1433/tcp, 7045-70
49/tcp, 8080/tcp                 navserver
7495cdfdcee1        stefanscherer/traefik-windows:v1.7.12                      "/traefik --docker.eâ€¦"   About an hour ago   Up 51 minutes               0.0.0.0:80->80/tcp, 0.0.0.0:443->4
43/tcp, 0.0.0.0:8080->8080/tcp   awesome_almeida

Also accept_outdated -parameter has tested, but it's forward to another error:
![image](https://user-images.githubusercontent.com/61850274/76959957-40ca6800-6923-11ea-8de1-edb6c16686ec.png)

**Comment by freddydk** [comment]
just add **-accept_outdated** to new-navcontainer, that will set the ACCEPT_OUTDATED environment variable to Y.

**Comment by beemubotokka** [comment]
Thank you, and I am very sorry for redundant ticket. 
Two weeks ago I created similar environment and all went good. Seemingly now it has taken over 90 days from BC15 CU2 release and that  -accept_outdated "Y" syntax were my stumble.
