### ISSUE TITLE
Wrong download

### ISSUE THREAD

**Issue by achecac** [microsoft/nav-docker#454]
I have download CreateBCSandBox from a customer's production cloud enviroment.
The docker image is this one:
$navdockerimage = 'mcr.microsoft.com/businesscentral/sandbox:15.3.40074.40822-es'
Which is fine, because it is the spanish localization that I want.

After some workarounds I finally can access Business Central on my machine, but localization is W1

Version: W1 15.4 (Platform 15.0.40939.41271 + Application 15.4.41023.41345)

Am I doing something wrong?

**Comment by achecac** [comment]
I answer my self: when download CreateBCSandBox from a BC Cloud enviroment, it includes

  -includeCSide `

This parameter causes an error while installing:
IncludeCSide is no longer supported in Dynamics 365 Business Central 2019 wave 2 release (1910 / 15.x)

As I have very little (very) knowledge of Powershell I thought that putting this symbol # before that parameter would override it, so I just edited in the following manner:

#-includeCSide

after installing several times I figured out that my correction, what it really did was to override that parameter AND THE REST of the following parameters.

Finally I just deleted that parameter and re-run ps file and then it worked out fine.

**Comment by freddydk** [comment]
Thanks for pointing this out - will remove the parameter from the script before downloaded.
