### ISSUE TITLE
Basic authentication for env:folders

### ISSUE THREAD

**Issue by narongschmidt** [microsoft/nav-docker#455]
We would like to use our public facing Artifactory instance for serving the zip file that we can pass to the env:folders variable. Unfortunately there is no basic authentication support at the moment. Would it be possible to add two more variables like env:foldersUsername and env:foldersPassword?

**Comment by freddydk** [comment]
I am not a big believer of username/password auth for accessing things, these credentials tend to be compromised.
The recommendation is to use a Secure Access Service URL, which is a URL including an accesstoken, which is time restricted. The SAS URL can be created using PowerShell and as such be part of spinning up the container - only working for 15 minutes or so.
