### ISSUE TITLE
bcinsider.azurecr.io

### ISSUE THREAD

**Issue by yrest** [microsoft/nav-docker#457]
Is there a full list of tags?

**Comment by NAVspecialist** [comment]
Take a look here:

https://www.waldo.be/2019/01/18/list-all-business-central-docker-image-tags-on-microsoft-container-services/

**Comment by yrest** [comment]
Cannot see the subject bcinsider.azurecr.io there. Can you?

**Comment by freddydk** [comment]
the function Get-NavContainerImageTags returns the tags. You need the credentials of course.

**Comment by yrest** [comment]
Thanks Freddy! I'll see if can figure it out. :)

(Get-NavContainerImageTags -imageName "bcinsider.azurecr.io" -registryCredential $credential).tags

Exception calling "Substring" with "1" argument(s): "startIndex cannot be larger than length of string.
Parameter name: startIndex"
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.6\ContainerInfo\Get-NavContainerImageTags.ps1:25 char:5
