### ISSUE TITLE
Your program license does not allow you to publish 'User Login Test Library'

### ISSUE THREAD

**Issue by kkgram** [microsoft/nav-docker#458]
Using the current build template http://aka.ms/bcsandbox stops with the error "Your program license does not allow you to publish 'User Login Test Library'" if you don't provide an license url in the template. 

I deployed using image mcr.microsoft.com/businesscentral/sandbox:dk-ltsc2019
Version 16.0.11240.12474
Country dk

The error occurs approx. 25 min. after "Running mcr.microsoft.com/businesscentral/sandbox:dk-ltsc2019 (this will take a few minutes)" and errors 
at , : line 12
PM Your program license does not allow you to publish 'User Login Test Library'.

**Comment by kkgram** [comment]
If I link to our developer license it work at the deployment completes, so the issue is only if you omit the License File URI/URL field in the BC Deployment template http://aka.ms/bcsandbox

![image](https://user-images.githubusercontent.com/32876762/79842366-025c1900-83b9-11ea-8b87-addb11c78c06.png)

**Comment by freddydk** [comment]
Will investigate.

**Comment by freddydk** [comment]
Not sure why that app should be published at all...

**Comment by MuhammadAizaz1** [comment]
Please share resolution steps of someone found the answer

**Comment by freddydk** [comment]
The reason for this is that the option Create Test Users = Yes requires a license.
Set Create Test Users to No.
I will fix the script to skip creating test users if no license is provided (and add an information about this in the log.)
