### ISSUE TITLE
ClickOnce Dev env crashes

### ISSUE THREAD

**Issue by pzentner** [Microsoft/nav-docker#46]
When I try to open the code view for a table, the finsql.exe is crashing with the following event:

`Application: finsql.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at <Module>.SetTypeInfoService(Void*)
   at <Module>._WinMainCRTStartup()`

`Faulting application name: finsql.exe, version: 11.0.18246.0, time stamp: 0x59a4aefc
Faulting module name: KERNELBASE.dll, version: 10.0.15063.502, time stamp: 0xc3955624
Exception code: 0xe0434352
Fault offset: 0x000eb802
Faulting process id: 0xe88
Faulting application start time: 0x01d32669db16c286
Faulting application path: C:\Temp\RoleTailored Client\finsql.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: eba8c9b5-3d3b-4c26-8575-add07c7c455f
Faulting package full name: 
Faulting package-relative application ID: `

Is this an issue with the ClickOnce deploy or something in the docker image? Had no time to actually research it in more detail.

**Comment by Koubek** [comment]
Please,
I would recommend to include some details about the image you use (at least this would be very helpful).

You can use:
```
docker inspect --format "{{ index .Config.Labels }}" [your_container_name_or_id]
```

**Comment by pzentner** [comment]
Sorry, September preview W1:

`map[tag:0.0.2.0 version:11.0.18246.0 country:W1 created:201708312002 cu:september legal:http://go.microsoft.com/fwlink/?LinkId=837447 maintainer:Freddy Kristiansen nav:devpreview]`

**Comment by Koubek** [comment]
Just to confirm - I am running NAV 2017 CU 9 image tagged with `0.0.2.1` and everything works fine (I can open standard C/SIDE editor, change objects, sync table schemas and even run RTC directly from C/SIDE).

**Comment by megel** [comment]
Looks like wrong assemblies? Do you use an old clickonce installation of C/Side

I use the dev-preview container and this version works well.

**Comment by Koubek** [comment]
I can see one strange thing: `Faulting application path: C:\Temp\RoleTailored Client\finsql.exe`. This path does not look like a ClickOnce folder.

**Comment by pzentner** [comment]
Yes, I noticed that as well, the folder doesn't even exist. So after rebooting it seems to work right now, but I don't understand where this would be coming from. ClickOnce was removed before and also wouldn't be included in Temp or anything. I guess, i'll close this for now and I'll open it again when it doesn't work again.
