### ISSUE TITLE
Any reliable way to check for Business Central to be ready for app deployments?

### ISSUE THREAD

**Issue by narongschmidt** [microsoft/nav-docker#462]
We have a CI pipeline that setups containers (kubernetes pods), builds and publishes apps to containers. We are currently polling the $WebBaseUrl/Health/System endpoint for status code 200 and then publish our apps. Unfortunately it's not working as expected. We receive 401 Unauthorized atleast every third time the pipeline runs. The apps are installed using the $WebBaseUrl/dev/apps endpoint.

**Comment by freddydk** [comment]
Why would you need to poll the endpoint?
To see whether the container is done initializing?

**Comment by freddydk** [comment]
The health endpoint cannot be used for that.
When creating containers in the containerhelper, I scan the output (docker logs) for Ready for connections - then it is. You might get the 401 because you try to publish before the user is created.

**Comment by narongschmidt** [comment]
> The health endpoint cannot be used for that.
> When creating containers in the containerhelper, I scan the output (docker logs) for Ready for connections - then it is. You might get the 401 because you try to publish before the user is created.

You are right, that would explain the 401 issue. Seems like I'll need to find a way for Kubernetes to wait until the initialization is finished before setting it to Ready.

Thank you!
