### ISSUE TITLE
Possibility to specify NST account

### ISSUE THREAD

**Issue by Koubek** [microsoft/nav-docker#467]
Hello again. Freddy, please, have you ever been considering to add a possibility to use non-System account for NST (create a WinUser and use that one or use Network Service account)?

## Reason

There are some scenarios when **NT AUTHORITY\SYSTEM** isn't the best option. For example:
 - You want to share a container with a partner/customer but you still want to store there some hidden data/files (e. g. a license) somewhere on the file system. But they should be able to deploy and via an extension, they can read all the files.
 - Also, there is a problem with Docker Swarm secrets. They will be able to read these as well (and theoretically send out then the content).
 - Today it's impossible to control any of the above as the system account can read everything. 

I can imagine using an alternative account with fewer privileges could help but this would be probably better to include already in the generic image instead of using the overrides. Or do you have any idea?

**Comment by Koubek** [comment]
Hi @freddydk, I can see you are working hard on pushing the changes... So sorry for bothering you but I would like to know your opinion regarding this issue. How do you see my request? I think as we (partners, customers) use containers in many areas, we really need to be able to handle somehow some sort of security and protection of some sensitive data. 

With the current setup, it's hard to achieve it IMO. That's why I would like to hear also your opinion.

**Comment by freddydk** [comment]
Are you suggesting an environment setting for NST account?
That would probably be fairly easily implemented.
But please realize that the upcoming changes to containerhelper and our docker images is going to make this much much easier for yourself to do.
I am expecting that most people who are not using the containerhelper will be creating their own modified version of the generic image and using that, to avoid overriding altogether.
This way, these people (like yourself) are in full control of when to uptake changes in the base repo etc.
much more about this later...

**Comment by Koubek** [comment]
Yeah, I agree, this approach will give us more flexibility. 

Anyway, I would like to see an "official example" on setting up NST using e. g. NETWORK SERVICE account (I tried to do it manually once the container was on but I had several problems with event logs, libraries like perflib etc.). I would need to spend some extra time on this and maybe you have already some experience so my effort would be probably a bit pointless. I also believe this could be useful for other partners.

**Comment by freddydk** [comment]
Yeah - it isn't a coincidence that SYSTEM was selected.
I wasn't able to make NETWORK SERVICE work - cannot remember the details.

**Comment by freddydk** [comment]
With artifacts, you can easily modify and build a new generic with whatever user you want to use.
See more here: https://freddysblog.com/2020/06/29/run-business-central-in-docker-using-a-custom-generic-image/

**Comment by Koubek** [comment]
Yeah, that's of course true. But I would like to some guidance (if you could provide any) in order to set up the account correctly (to work at all at least). 

I suppose there are some aspects you probably know better than anyone of us as you know the internals of the NST - like required permissions to access Event Logs and eventually other stuff as well.

**Comment by freddydk** [comment]
You would be able to find that info on docs: https://docs.microsoft.com/en-us/dynamics-nav/provisioning-the-microsoft-dynamics-nav-server-account
In the generic layer - I think it is only in navinstall.ps1 (service creation), setupdatabase.ps1 (db permissions) and setupconfiguration.ps1 (tcp permissions) the SYSTEM account is used, but as mentioned earlier, I don't know whether there would be more by using a different account.
It is not something I will be able to work on.
