### ISSUE TITLE
.NET Framework 3 install not working (NAV2013R2)

### ISSUE THREAD

**Issue by marknitek** [microsoft/nav-docker#468]
I try to create a container for NAV2013R2 by using the steps described here https://freddysblog.com/2017/11/29/can-i-run-nav-2015-and-earlier-on-docker/
>I placed the .cab for the .net framework in the prerequisite compontens

The process fails with an error about 
```
NAV Server Instance is not ready to serve requests
```
Further Investigation showed that the .net framework 3 was not installed:
```
C:\Run> get-itemproperty "Registry::HKLM\Software\Microsoft\NET Framework Setup\NDP\v3.0\Setup"
Cannot find path 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v3.0\Setup' because it does not exist.
    + CategoryInfo          : ObjectNotFound: (HKLM\Software\M...\NDP\v3.0\Setup:String) [Get-ItemProperty], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand
```
I tried to install it manually to see what happens:
```
C:\Run> Dism /online /enable-feature /all /featurename:NetFX3 /Source:"C:\NAVDVD\Prerequisite Components"

Deployment Image Servicing and Management tool
Version: 10.0.17763.1

Image Version: 10.0.17763.437

Enabling feature(s)

[=                          3.0%                           ]

[===                        5.9%                           ]

[===                        5.9%                           ]

[==========================100.0%==========================]

Error: 1058

The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

The DISM log file can be found at C:\Windows\Logs\DISM\dism.log
```
**The installation in the navinstall.ps1 does not account an error in the dism command as we have here, this should be fixed.**

From what i understand, this is an online update and therefore windowsupdate service must be running to install the .net framework component, right?
Looking at the services:
```
C:\Run> get-service wuauserv

Status   Name               DisplayName
------   ----               -----------
Stopped  wuauserv           Windows Update
```
Starting does not work:
```
 C:\Run> start-service wuauserv
Service 'Windows Update (wuauserv)' cannot be started due to the following error: Cannot start service wuauserv on
computer '.'.
```

Here my full command to create the container with navcontainerhelper:
```
New-NavContainer -auth Windows -accept_eula -accept_outdated -containerName $containerName -navDvdPath $localDVDPath -navDvdCountry CH -doNotExportObjectsToText -includeCSide -memoryLimit 8G -isolation process -updateHosts
```

**Comment by freddydk** [comment]
Maybe you need specifically use a ltsc2016 generic image - I don't think Server 2019 works with .net framework 3 and the stuff mentioned in that blog post.

**Comment by marknitek** [comment]
Ok i will test that, so then only hyper-v isolation will work on a windows server 2019 host i guess?

**Comment by freddydk** [comment]
Yes - it is very tricky with these very old unsupported versions...

**Comment by marknitek** [comment]
I tried with windows server 2016 image but that failed with:
```
Service Tier doesn't exist / is not installed
```
Then i got the .cab files from windows server 2019 iso and put them in to prerequisite componenents instead of the files from windows server 2016. 

![image](https://user-images.githubusercontent.com/2346803/84256059-bf463880-ab13-11ea-90e5-45b9c9debb0c.png)


And now its working!

![image](https://user-images.githubusercontent.com/2346803/84255971-9c1b8900-ab13-11ea-85df-5e798fbcf85b.png)



Thanks for pointing me to the right direction!
