### ISSUE TITLE
Unable to start NAV containers

### ISSUE THREAD

**Issue by kaspermoerch** [Microsoft/nav-docker#47]
I am unable to run NAV containers on my local machine.

I have tried with the following commands:
```
docker run -e ACCEPT_EULA=Y navdocker.azurecr.io/dynamics-nav:devpreview
docker run -e ACCEPT_EULA=Y navdocker.azurecr.io/dynamics-nav:devpreview-finus
docker run -e ACCEPT_EULA=Y navdocker.azurecr.io/dynamics-nav:devpreview-findk
```

They all produce the same result (the following is from the `finus` attempt):
```
Initializing...
Hostname is 9a4756201f6e
PublicDnsName is 9a4756201f6e
Running Specific Image
Starting Local SQL Server
Starting Internet Information Server
Using NavUserPassword Authentication
Using Database Connection localhost/SQLEXPRESS [FinancialsUS]
Modifying NAV Service Tier Config File for Docker
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 862EC1309B293AA369DAB005DC338F900546936E
Modifying NAV Service Tier Config File with Instance Specific Settings
Start NAV Service Tier
Failed to start service 'Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 308
at <ScriptBlock>, C:\Run\start.ps1: line 18
at <ScriptBlock>, <No file>: line 1
```

The container is created but can't start.

Running `docker start` on the container adds this to the log:

```
Initializing...
Hostname is 9a4756201f6e
PublicDnsName is 9a4756201f6e
Restarting Instance
Starting Local SQL Server
Starting Internet Information Server
Start NAV Service Tier
Container IP Address: 172.26.75.163
Container Hostname  : 9a4756201f6e
Container Dns Name  : 9a4756201f6e
Web Client          : https://9a4756201f6e/NAV/WebClient/
NAV Admin Username  : admin
NAV Admin Password  : Hesu7266

Files:
Cannot find path 'C:\inetpub\wwwroot\http' because it does not exist.
at <ScriptBlock>, C:\Run\navstart.ps1: line 385
at <ScriptBlock>, C:\Run\start.ps1: line 18
at <ScriptBlock>, <No file>: line 1
```

I'm running Docker Community Edition version 17.06.2-ce-win27 (13194) with Windows Containers.

**Comment by Koubek** [comment]
Like @johanemilsson says, try to specify the memory limit. With 2 GB you should be ok as well.
On CE you use hyper isolation and setting the memory limit actually preconfigure the VM running behind. It can react better when demanding more memory during the startup. This is my observation but the real reason could be different.

**Comment by freddydk** [comment]
In one of the next image updates, I will check whether the memory is the problem and give a better error message. I do not want to check memory up front, as the only reliable way I have found to check memory is using systeminfo - and that takes ~10 seconds.
So - if the container fails - write the error, check the memory and give an extra information stating that this is probably due to lack of memory.

**Comment by kaspermoerch** [comment]
I did see an OutOfMemoryException on one of my attempts, so that could definitely be the problem.

I will try adding the memory limit tomorrow and report back when I have.

**Comment by kaspermoerch** [comment]
It works like a charm with the memory limit specified.
