### ISSUE TITLE
Container crashes at startup (The environment block used to start a process cannot be longer than)

### ISSUE THREAD

**Issue by meilel** [microsoft/nav-docker#470]
Whenever I try to start a new BC container, it crashes with the following message:

```
Add-Type : The environment block used to start a process cannot be longer than
65535 bytes.  Your environment block is 77321 bytes long.  Remove some
environment variables and try again.
At C:\Run\start.ps1:47 char:1
+ Add-Type -TypeDefinition $Source -Language CSharp -WarningAction Sile ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], InvalidOperationEx
   ception
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.Power
   Shell.Commands.AddTypeCommand

```

I already have some running containers with the same setup, but since today I am not able to start a new one.
I tried to remove some env variables with no luck.

**Comment by freddydk** [comment]
You would need to give us some more information here.
What script are you using and the output of that script is a minimum.

**Comment by meilel** [comment]
@freddydk i found the issue, it was kubernetes related. there is a flag enableServiceLinks which adds all to service ports of the other containers as env variable in your container, which led to this error message. I fixed it by setting this flag to false
