### ISSUE TITLE
Can't download sympbols

### ISSUE THREAD

**Issue by guilliano** [microsoft/nav-docker#471]
Powershell:
`New-BCContainer -accept_eula -accept_outdate -containerName 'BCTest' -updatehosts -imageName 'mcr.microsoft.com/businesscentral/onprem:14.10.40471.0-be'`

Output:
`Container Hostname  : BCTest
Container Dns Name  : BCTest
Web Client          : http://BCTest/NAV/
Dev. Server         : http://BCTest
Dev. ServerInstance : NAV

Files:
http://BCTest:8080/al-3.0.193882.vsix`

I downloaded the VSIX and installed as extension in VS Code.

Launch.json
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "al",
            "request": "launch",
            "server": "http://BCTest/",
            "serverInstance": "NAV",
            "port": 80,
            "authentication": "Windows"
        }
    ]
}`

app.json
`  "id": "21e33d18-65f0-49fc-be84-8e571d899b66",
  "name": "Base",
  "publisher": "Default publisher",
  "version": "1.0.0.0",
  "brief": "Extension",
  "description": "Extension",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "./resources/Logo_group.png",
  "dependencies": [],
  "screenshots": [],
  "platform": "14.0.0.0",
  "application": "14.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 2001299
    }
  ],
  "contextSensitiveHelpUrl": "",
  "showMyCode": true,
  "runtime": "3.0",
  "features": [],
  "target": "Internal"`

**Comment by freddydk** [comment]
and what error do you get?
You could try to change your container to username/password auth - and the same in app.json - windows auth has caused a lot of issues.

**Comment by freddydk** [comment]
Stumpled over this one - in launch.json - you have port 80 - the port should be the Developer endpoint - typically 7049. You should delete the port in launch.json unless you have specifically changed something.
