### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/nav-docker#472]
Hi @freddydk ,

Still you are needed. :(
![image](https://user-images.githubusercontent.com/33481576/85500905-fdf2ed00-b601-11ea-89be-0f9a85482874.png)

DockerDo : docker.exe: Error response from daemon: container f5890fdbd17052d129377b7d47a6ced57b9c5403f27d4f2a54b2e7ef25f7c7ca encountered an 
error during hcsshim::System::Start: failure in a Windows system call: The operation timed out because a response was not received from the 
Virtual Machine hosting the Container. (0xc0370109).
ExitCode: 125
Commandline: docker run --env licenseFile="" --name TestV17 --hostname TestV17 --env auth=Windows --env username="sudarshan.khandal" --env 
ExitOnError=N --env locale=en-US --env databaseServer="" --env databaseInstance="" --volume 
"C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContainerHelper" --volume 
"C:\ProgramData\NavContainerHelper\Extensions\TestV17\my:C:\Run\my" --isolation hyperv --restart unless-stopped --memory 5GB --env 
enableApiServices=Y --env useSSL=N --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b16050a53
45MgB8AGkAcAA3AFAASQA3AEQAOAB0AEUAVABGADUAMAB3ADAAMAB2AFUARAAwAEEAPQA9AHwAZQA3ADUAZQA5ADIAOAA2ADQAMwAyAGEAZgA4AGYAMwBjADQAOQAzADMANAA4ADkAMAAyA
GMAZQBmAGQAOABhAGUAZQAzADYANQA2ADgAYgA0ADEAZgA1ADAAMgBkAGEAZQA1AGQAMwBkAGYAMQA5ADkAZAAxAGIANAA1AGIAOAA= --env 
passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y --env accept_outdated=Y --detach 
bcinsider.azurecr.io/bcsandbox-master:us-ltsc2016
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.5\ContainerHandling\New-NavContainer.ps1:1446 char:19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

Thanks
SUD
@freddydk

**Comment by freddydk** [comment]
This one is your docker installation - I have had a few cases of errors like this and making sure that windows and docker is updated and docker is reset to factory settings etc. has fixed the problem.
You can also see if anybody else found a solution here: https://github.com/microsoft/navcontainerhelper/issues?q=%22failure+in+a+Windows+system+call%22
