### ISSUE TITLE
Getting error while creating Business Central container 

### ISSUE THREAD

**Issue by MuhammadAizaz1** [microsoft/nav-docker#473]
I am getting an error while running script to create Business Central container. Please see script and error details below. 

**Powershell Script**
install-module navcontainerhelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true

$containername = 'BCContainer'
$navdockerimage = 'mcr.microsoft.com/businesscentral/sandbox:16.1.12629.12805-us'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth Windows `
                 -Credential $credential `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password

**Error Message at the end**
Creating SUPER user
Assign Premium plan for BCCONTAINER\DOCKERUSER
Container IP Address: 172.29.152.175
Container Hostname  : BCContainer
Container Dns Name  : BCContainer
Web Client          : http://BCContainer/BC/
Dev. Server         : http://BCContainer
Dev. ServerInstance : BC
Setting BCContainer to 172.29.152.175 in host hosts file

Files:
http://BCContainer:8080/ALLanguage.vsix

WARNING: You are running a container which is 137 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 267 seconds
Ready for connections!
Reading CustomSettings.config from BCContainer
Creating Desktop Shortcuts for BCContainer
Container BCContainer successfully created
Copy from container BCContainer (C:\Applications\system application\test\Microsoft_System Application Test Library.app
) to C:\ProgramData\NavContainerHelper\Extensions\BCContainer\_Microsoft_System Application Test Library.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\BCContainer\_Microsoft_System Application Test Library.app
Your program license does not allow you to publish 'User Login Test Library'.
at <ScriptBlock>, <No file>: line 12
Your program license does not allow you to publish 'User Login Test Library'.
At C:\Program 
Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.9\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37 
char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Manage 
   ment.Cmdlets.PublishNavApp
    + PSComputerName        : 3230cbdec7b702dc518ecff359814c427cee69b14c398679fe1bcaeb9db92617

**Comment by freddydk** [comment]
Remove the function call to 

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password

That requires a license
