### ISSUE TITLE
Test Automation Package not showing in Visual Studio Project after installing docker container

### ISSUE THREAD

**Issue by Sandygitl** [microsoft/nav-docker#474]
Hi Team,

I have created a new docker container from Docker Desktop for BusinessCentral.
I have also installed test tool kit by using command ImportTestToolKit and  also restarted the docker container,

I am able to see all test tool code units by running web client of this docker container but **not able to see test libraries and test toll packages in Visual Studio Project. Due to this I am not able to develop new test code units.**

If any one have faced the same issue or having any knowledge on that than please update.

**Comment by freddydk** [comment]
I guess you need to add references to the test apps.
You can see some of them here: https://dev.azure.com/businesscentralapps/_git/HelloWorld?path=%2Ftest%2Fapp.json

**Comment by Sandygitl** [comment]
Hi Freddy,

Thanks for the response.

Do you have any idea that these references added manually or  Can I copy these sample references or how can I create new one.

**Comment by freddydk** [comment]
You can grab the references from the file above. There are others - but I guess you would add them if you need them
I would expect all of this to be in the docs.

**Comment by Sandygitl** [comment]
Hi Freddy,

Above references not working as I am running docker container on my local machine as I am not having azure subscription. 

Is there any other way around to get reference symbols for Docker containers on local machine.

Thanks in Advance!

**Comment by Sandygitl** [comment]
Hi Freddy,

I have resolved it by adding test package dependencies from containers web page.

Thanks :)
