### ISSUE TITLE
Getting error while creating Business Central container using Get-BCArtifactUrl cmd

### ISSUE THREAD

**Issue by sradouan** [microsoft/nav-docker#475]
Hi, 
I'm unable to create a new container with the new method of artifact. this is the error message below.

```
$artifactUrl= Get-BCArtifactUrl -version 16.2 -country na -select Latest -type onprem

$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
New-BcContainer `
    -accept_eula `
    -containerName test `
    -artifactUrl $artifactUrl `
    -Credential $credential `
    -auth UserPassword `
    -updateHosts `
    -imagename myown `
    -licensefile 'c:\temp\mylicense.flf'
```

Error:

- updatehosts.ps1
Creating container test from image myown:onprem-16.2.13509.13779-na
5a6cca20a65f4c9b9ac433336e2fe7db4a6ba69b73c047338a8b9639cf74bfa4
Waiting for container test to be ready
Initializing...
Exception calling "Open" with "4" argument(s): "Access to the path 'c:\driversetc\hosts' is denied."
at UpdateHostsFile, C:\Run\my\updatehosts.ps1: line 20
at <ScriptBlock>, C:\Run\my\updatehosts.ps1: line 109
at <ScriptBlock>, C:\Run\my\SetupVariables.ps1: line 5
at <ScriptBlock>, C:\Run\navstart.ps1: line 24
at <ScriptBlock>, C:\Run\start.ps1: line 217
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Exception calling "Open" with "4" argument(s): "Access to the path 'c:\driversetc\hosts' is denied."
at UpdateHostsFile, C:\Run\my\updatehosts.ps1: line 20
at <ScriptBlock>, C:\Run\my\updatehosts.ps1: line 109
at <ScriptBlock>, C:\Run\my\SetupVariables.ps1: line 5
at <ScriptBlock>, C:\Run\navstart.ps1: line 24
at <ScriptBlock>, C:\Run\start.ps1: line 217
at <ScriptBlock>, <No file>: line 1
Initialization of container test failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.9\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container test failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container test failed

Thanks

**Comment by freddydk** [comment]
On the host - you can run the function Check-NavContainerHelperPermissions to check your permissions (and assign the missing permissions) if  you are not running as administrator.

**Comment by sradouan** [comment]
Hi Freddy,
i'm using Navcontainerhelper as administrator but still have the same error, could Kaspersky Antivirus how create this error non?
Thanks.

**Comment by freddydk** [comment]
I haven't seen other people having problems with updating hosts - but it could easily be Kaspersky.
If you remove -updateHosts then the error goes away - but then you will not be able to access the container by its name.

**Comment by sradouan** [comment]
Thanks Freddy.
