### ISSUE TITLE
Business Central On prem Docker networking Issue

### ISSUE THREAD

**Issue by tanya76** [microsoft/nav-docker#476]
PS C:\Windows\system32> docker start <Container ID>
docker : Error response from daemon: network multi-host-network not found
At line:1 char:1
+ docker start<Container ID>
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ...twork not found:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Error: failed to start containers: <Container ID>

**Comment by freddydk** [comment]
This issue doesn't contain any information that can be used to troubleshoot/help you from.
I need scripts, outputs and as much information as possible to be able to help
