### ISSUE TITLE
Local and BC user not created if Windows auth and clear text pwd is used

### ISSUE THREAD

**Issue by tfenster** [microsoft/nav-docker#479]
If you create a container with Windows auth and a clear text password, no local user and no BC user is created

Repro steps:
```
docker run -e accept_eula=y -e accept_outdated=y -e user=VM-Administrator -e password=Passw0rd123 -e auth=Windows -e usessl=n --name bc -p 80:80 mcr.microsoft.com/businesscentral/onprem:2004-ltsc2019
```
Output looks like this
```
Initializing...
Starting Container
Hostname is 59c541f527a5
PublicDnsName is 59c541f527a5
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Setting SA Password and enabling SA
Container IP Address: 172.20.203.255
Container Hostname  : 59c541f527a5
Container Dns Name  : 59c541f527a5
Web Client          : http://59c541f527a5/BC/
Dev. Server         : http://59c541f527a5
Dev. ServerInstance : BC

Files:
http://59c541f527a5:8080/ALLanguage.vsix

WARNING: You are running a container which is 182 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 55 seconds
Ready for connections!
Starting EventLog Monitor
Monitoring EventSources from EventLog[Application]:
- MicrosoftDynamicsNAVClientClientService
- MicrosoftDynamicsNAVClientWebClient
- MicrosoftDynamicsNavServer$BC
- MSSQL$SQLEXPRESS
```

If you then get a session into the container, e.g. with `docker exec -ti bc powershell -noexit c:\run\prompt.ps1` and check the created users, you will see that the expected VM-Administrator user is not created

```
PS C:\run> Get-NAVServerUser BC
PS C:\run> Get-LocalUser

Name               Enabled Description
----               ------- -----------
Administrator      False   Built-in account for administering the computer/domain
DefaultAccount     False   A user account managed by the system.
Guest              False   Built-in account for guest access to the computer/domain
WDAGUtilityAccount False   A user account managed and used by the system for Windows Defender Application Guard scenarios.
```

I don't understand why that happens because this https://github.com/microsoft/nav-docker/blob/master/generic/Run/SetupVariables.ps1#L59,L60 should fill the variable `$securepassword` which in turn because of this https://github.com/microsoft/nav-docker/blob/master/generic/Run/navstart.ps1#L180 should trigger the creation of the Windows user here https://github.com/microsoft/nav-docker/blob/master/generic/Run/SetupWindowsUsers.ps1#L9,L15 (the variable has different casing but that shouldn't matter IMHO). Then this https://github.com/microsoft/nav-docker/blob/master/generic/Run/navstart.ps1#L184 should trigger the NAV user creation here https://github.com/microsoft/nav-docker/blob/master/generic/Run/SetupNavUsers.ps1#L9,L16. 

Any ideas why this doesn't work? Am I missing something?

**Comment by freddydk** [comment]
change -e user=VM-Administrator to -e username=VM-Administrator

**Comment by tfenster** [comment]
I knew it was missing something stupid :( Thanks!

**Comment by freddydk** [comment]
Easiest way to debug stuff like this is to place the attached file in c:\temp\my\SetupWindowsUsers.ps1 and add -v c:\temp\my:c:\run\my - then you can directly inspect what variables ended up being and then backtrace.
[SetupWindowsUsers.txt](https://github.com/microsoft/nav-docker/files/5078377/SetupWindowsUsers.txt)
