### ISSUE TITLE
Special characters in the client

### ISSUE THREAD

**Issue by kaspermoerch** [Microsoft/nav-docker#48]
I'm not sure if this issue is related to docker. 

I ran the image `navdocker.azurecr.io/dynamics-nav:devpreview-findk` and connected to the client in my browser (both IE and Chrome).

The special characters don't look right:
![image](https://user-images.githubusercontent.com/1166791/30363006-e251c04e-985e-11e7-82a3-5dcbc36775f2.png)

**Comment by freddydk** [comment]
did you use -e locale=da-DK when running the container?

**Comment by kaspermoerch** [comment]
I did not but that doesn't seem to change anything:
![image](https://user-images.githubusercontent.com/1166791/30363857-0ee7fe4a-9862-11e7-92d2-21b766f2753f.png)

On the RoleCenter it looks okay though:
![image](https://user-images.githubusercontent.com/1166791/30363835-f497c638-9861-11e7-97a8-4e39f423ed88.png)

**Comment by freddydk** [comment]
Ok, it looks like something that goes wrong during building of the DK images.
We will have to fix this before going public with Containers, thanks for capturing this.

**Comment by freddydk** [comment]
Kasper, could you tell me whether this still fails? 
I haven't been able to repro this.

**Comment by kaspermoerch** [comment]
I am unable to reproduce the error.
