### ISSUE TITLE
New BC-Container Error: Cannot find path 'C:\inetpub\wwwroot\http' because it does not exist.

### ISSUE THREAD

**Issue by PGjata** [microsoft/nav-docker#480]
I am trying to create a new BC container but i get an error. The script is as follows:
install-module navcontainerhelper -Force

$imageName = "mcr.microsoft.com/businesscentral/sandbox:it"
$containerName = "BCTestRunner"
$navcredential = New-Object System.Management.Automation.PSCredential -argumentList "admin", (ConvertTo-SecureString -String "Admin123" -AsPlainText -Force)
$licenseFile = 'C:\Users\Test\Desktop\Licenze gennaio 2020\agic bc 16.flf'

New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -Auth NavUserPassword `
    -imageName $imageName `
    -Credential $navcredential `
    -assignPremiumPlan `
    -updateHosts `
    -alwaysPull `
    -isolation hyperv `
    -includeTestToolkit `
    -licenseFile $licenseFile `
    -memoryLimit 4G `
    -shortcuts Desktop `
    -doNotExportObjectsToText `
    -includeTestLibrariesOnly

and I get the following error:
You are trying to run a container which is more than 90 days old.
    Microsoft recommends that you always run the latest version of our containers.
    Set the environment variable ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.

I added the following line in  SetupVariables.ps1:
$Accept_outdated = "Y"
and then restarted the container. But now it gives me the following error:

Files:
Cannot find path 'C:\inetpub\wwwroot\http' because it does not exist.
at <ScriptBlock>, C:\Run\navstart.ps1: line 247
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container BCTestRunner failed
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.25\ContainerHandling\Wait-NavContainerReady.ps1:44 car:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...stRunner failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BCTestRunner failed

**Comment by freddydk** [comment]
You are running a very old version of NavContainerHelper - there are new versions out there and there is a replacement module called bccontainerhelper (read about those on my blog) - this is probably not the reason for the issue.

You need to add -accept_outdated to the new-bccontainer and not modify a dead container.

Furthermore - the docker images on mcr are not updated anymore - if you want to run new versions of Business Central you will need to use artifacts.

https://freddysblog.com/2020/06/25/changing-the-way-you-run-business-central-in-docker/
(there are a lot of other blog posts which describes how to do this)

**Comment by PGjata** [comment]
Thank you very much for your answer. I replaced navcontainerhelper with bccontainerheper, added -accept_outdated to the new-bccontainer, and also used artifacts instead of docker images. It worked like a charm :).

**Comment by freddydk** [comment]
Thanks for the info.
With artifacts you are using a generic image which matches the host OS and is likely not outdated (if it is, you should consider updating the host:-))
