### ISSUE TITLE
Initialization of container failed

### ISSUE THREAD

**Issue by AnantshreeChandola** [microsoft/nav-docker#481]
Error:
Initialization of container BC16-4US2 failed
At C:\Program 
Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...C16-4US2 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC16-4US2 failed

The following script gives the error:

install-module navcontainerhelper -force
$artifactUrl = "https://bcartifacts.azureedge.net/sandbox/16.4.14693.15807/us"
$containerName = "BC16-4US2"
$auth = "UserPassword"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'password' -AsPlainText -Force)
$licenseFile = "C:\Users\achandola\Desktop\License files\5164953 BC16.flf

New-BCContainer -accept_eula `
                -containerName $containerName `
                -auth $auth `
                -credential $credential `
                -licenseFile $licenseFile `
                -updateHosts `
                -includeAL `
                -artifactUrl $artifactUrl  `
                -memoryLimit 3G `
                -shortcuts Desktop

 

                #-Import-TestToolkitToBcContainer
                #-includeTestLibrariesOnly

**Comment by freddydk** [comment]
You would have to provide the output of the script in order for me to tell you want goes wrong.
My guess is that that script will succeed on 99% of the machines

**Comment by AnantshreeChandola** [comment]
Full Output:


PS C:\windows\system32> C:\Users\achandola\Desktop\Docker scripts\container creation.ps1
NavContainerHelper is version 0.7.0.26
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1903
Docker Client Version is 19.03.2
Docker Server Version is 19.03.2
Removing container BC16-4US2
Removing BC16-4US2 from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\BC16-4US2
Fetching all docker images
Using image mcr.microsoft.com/dynamicsnav:10.0.18362.658-generic
Creating Container BC16-4US2
Version: 16.4.14693.15807-US
Style: sandbox
Platform: 16.0.14648.15759
Generic Tag: 0.1.0.19
Container OS Version: 10.0.18362.658 (1903)
Host OS Version: 10.0.18362.657 (1903)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Users\achandola\Desktop\License files\5164953 BC16.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\BC16-4US2\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BC16-4US2 from image mcr.microsoft.com/dynamicsnav:10.0.18362.658-generic
a169f799d9c359dc6e05ad89bbb85f85b741a0f6c389dce00a93b51634fb3273
Waiting for container BC16-4US2 to be ready

Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.US
Installation took 98 seconds
Installation complete
Initializing...
Exception calling "Open" with "4" argument(s): "Access to the path 'c:\driversetc\hosts' is denied."
at UpdateHostsFile, C:\Run\my\updatehosts.ps1: line 20
at <ScriptBlock>, C:\Run\my\updatehosts.ps1: line 111
at <ScriptBlock>, C:\Run\my\SetupVariables.ps1: line 5
at <ScriptBlock>, C:\Run\navstart.ps1: line 24
at <ScriptBlock>, C:\Run\start.ps1: line 346
at <ScriptBlock>, <No file>: line 1Error

Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.US
Installation took 98 seconds
Installation complete
Initializing...
Exception calling "Open" with "4" argument(s): "Access to the path 'c:\driversetc\hosts' is denied."
at UpdateHostsFile, C:\Run\my\updatehosts.ps1: line 20
at <ScriptBlock>, C:\Run\my\updatehosts.ps1: line 111
at <ScriptBlock>, C:\Run\my\SetupVariables.ps1: line 5
at <ScriptBlock>, C:\Run\navstart.ps1: line 24
at <ScriptBlock>, C:\Run\start.ps1: line 346
at <ScriptBlock>, <No file>: line 1
Initialization of container BC16-4US2 failed
At C:\Program 
Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...C16-4US2 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC16-4US2 failed

**Comment by freddydk** [comment]
You are using a very old un-updated windows version - my first suggestion would be to update windows and try again.
If that still fails, it might be that you have an antivirus software, which disallows access to the hosts file.
If you remove -updatehosts then this error will go away, but you might not be able to use the hostname in the browser to use the webclient (nor in VS Code).

**Comment by AnantshreeChandola** [comment]
Hi @freddydk, After updating windows, again Initiaization failed, this is the output I got:

PS C:\windows\system32> C:\Users\achandola\Desktop\Docker scripts\container creation.ps1
NavContainerHelper is version 0.7.0.26
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1903
Docker Client Version is 19.03.2
Docker Server Version is 19.03.2
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.18362.778-generic
10.0.18362.778-generic: Pulling from dynamicsnav
5b663e3b9104: Already exists
63116c96f2c9: Pulling fs layer
2befd9acdefb: Pulling fs layer
e55876781c8d: Pulling fs layer
26ffb12321a5: Pulling fs layer
7434f81d5bcf: Pulling fs layer
c68daf11bccd: Pulling fs layer
26b04edbb860: Pulling fs layer
8f69a5dbe772: Pulling fs layer
a9787dfd062e: Pulling fs layer
10d52f9007f0: Pulling fs layer
a2b5ff91802c: Pulling fs layer
5ba5be89ab24: Pulling fs layer
d21e0d1cee62: Pulling fs layer
2dd3411d7f5c: Pulling fs layer
26ffb12321a5: Waiting
720b41c51cfc: Pulling fs layer
7434f81d5bcf: Waiting
804026a5a169: Pulling fs layer
c68daf11bccd: Waiting
26b04edbb860: Waiting
8f69a5dbe772: Waiting
10d52f9007f0: Waiting
d21e0d1cee62: Waiting
a2b5ff91802c: Waiting
5ba5be89ab24: Waiting
2dd3411d7f5c: Waiting
720b41c51cfc: Waiting
a9787dfd062e: Waiting
804026a5a169: Waiting
40969bcf68ea: Pulling fs layer
a5a698198af6: Pulling fs layer
9516b50da209: Pulling fs layer
d85d591d8a81: Pulling fs layer
6532667767ef: Pulling fs layer
1cb191bb2367: Pulling fs layer
40969bcf68ea: Waiting
a5a698198af6: Waiting
9516b50da209: Waiting
d85d591d8a81: Waiting
6532667767ef: Waiting
1cb191bb2367: Waiting
e55876781c8d: Verifying Checksum
e55876781c8d: Download complete
2befd9acdefb: Verifying Checksum
2befd9acdefb: Download complete
7434f81d5bcf: Verifying Checksum
7434f81d5bcf: Download complete
c68daf11bccd: Verifying Checksum
c68daf11bccd: Download complete
26b04edbb860: Verifying Checksum
26b04edbb860: Download complete
8f69a5dbe772: Verifying Checksum
8f69a5dbe772: Download complete
26ffb12321a5: Verifying Checksum
26ffb12321a5: Download complete
10d52f9007f0: Verifying Checksum
10d52f9007f0: Download complete
a2b5ff91802c: Verifying Checksum
a2b5ff91802c: Download complete
5ba5be89ab24: Verifying Checksum
5ba5be89ab24: Download complete
d21e0d1cee62: Verifying Checksum
d21e0d1cee62: Download complete
2dd3411d7f5c: Verifying Checksum
2dd3411d7f5c: Download complete
720b41c51cfc: Verifying Checksum
720b41c51cfc: Download complete
804026a5a169: Verifying Checksum
804026a5a169: Download complete
40969bcf68ea: Verifying Checksum
40969bcf68ea: Download complete
a5a698198af6: Verifying Checksum
a5a698198af6: Download complete
63116c96f2c9: Retrying in 5 seconds
63116c96f2c9: Retrying in 4 seconds
63116c96f2c9: Retrying in 3 seconds
63116c96f2c9: Retrying in 2 seconds
63116c96f2c9: Retrying in 1 second
a9787dfd062e: Verifying Checksum
a9787dfd062e: Download complete
d85d591d8a81: Verifying Checksum
d85d591d8a81: Download complete
6532667767ef: Verifying Checksum
6532667767ef: Download complete
1cb191bb2367: Verifying Checksum
1cb191bb2367: Download complete
9516b50da209: Verifying Checksum
9516b50da209: Download complete
63116c96f2c9: Verifying Checksum
63116c96f2c9: Download complete
63116c96f2c9: Pull complete
2befd9acdefb: Pull complete
e55876781c8d: Pull complete
26ffb12321a5: Pull complete
7434f81d5bcf: Pull complete
c68daf11bccd: Pull complete
26b04edbb860: Pull complete
8f69a5dbe772: Pull complete
a9787dfd062e: Pull complete
10d52f9007f0: Pull complete
a2b5ff91802c: Pull complete
5ba5be89ab24: Pull complete
d21e0d1cee62: Pull complete
2dd3411d7f5c: Pull complete
720b41c51cfc: Pull complete
804026a5a169: Pull complete
40969bcf68ea: Pull complete
a5a698198af6: Pull complete
9516b50da209: Pull complete
d85d591d8a81: Pull complete
6532667767ef: Pull complete
1cb191bb2367: Pull complete
Digest: sha256:b9bfec819f957d08cbe653a41caaeff1b93490fa6e07710a796be94baa870976
Status: Downloaded newer image for mcr.microsoft.com/dynamicsnav:10.0.18362.778-generic
mcr.microsoft.com/dynamicsnav:10.0.18362.778-generic
Using image mcr.microsoft.com/dynamicsnav:10.0.18362.778-generic
Creating Container BC16-4US2
Version: 16.4.14693.15807-US
Style: sandbox
Platform: 16.0.14648.15759
Generic Tag: 0.1.0.20
Container OS Version: 10.0.18362.778 (1903)
Host OS Version: 10.0.18362.778 (1903)
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Users\achandola\Desktop\License files\5164953 BC16.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\BC16-4US2\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BC16-4US2 from image mcr.microsoft.com/dynamicsnav:10.0.18362.778-generic
dcdda223d74cc68c2bab057bd262a094623de5b863a4d941b9178af800ad0fb1
Waiting for container BC16-4US2 to be ready

Determining Database Collation from c:\dl\sandbox\16.4.14693.15807\us\BusinessCentral-US.bak
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.US
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 163 seconds
Installation complete
Initializing...
Exception calling "Open" with "4" argument(s): "Access to the path 'c:\driversetc\hosts' is denied."
at UpdateHostsFile, C:\Run\my\updatehosts.ps1: line 20
at <ScriptBlock>, C:\Run\my\updatehosts.ps1: line 111
at <ScriptBlock>, C:\Run\my\SetupVariables.ps1: line 5
at <ScriptBlock>, C:\Run\navstart.ps1: line 24
at <ScriptBlock>, C:\Run\start.ps1: line 346
at <ScriptBlock>, <No file>: line 1Error

Determining Database Collation from c:\dl\sandbox\16.4.14693.15807\us\BusinessCentral-US.bak
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.US
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 163 seconds
Installation complete
Initializing...
Exception calling "Open" with "4" argument(s): "Access to the path 'c:\driversetc\hosts' is denied."
at UpdateHostsFile, C:\Run\my\updatehosts.ps1: line 20
at <ScriptBlock>, C:\Run\my\updatehosts.ps1: line 111
at <ScriptBlock>, C:\Run\my\SetupVariables.ps1: line 5
at <ScriptBlock>, C:\Run\navstart.ps1: line 24
at <ScriptBlock>, C:\Run\start.ps1: line 346
at <ScriptBlock>, <No file>: line 1
Initialization of container BC16-4US2 failed
At C:\Program 
Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...C16-4US2 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC16-4US2 failed

**Comment by freddydk** [comment]
It is hard for me to say what it is on your machine, which prevents containerhelper and the container from updating the hosts file.
Antivirus or other things are typically to blame - I do not know Dell SupportAssist
I assume you are running as administrator - else that could be the reason.
You could also start PowerShell as non-admin and run check-bccontainerhelperpermissions to see whether it can tell you anything.

**Comment by AnantshreeChandola** [comment]
@freddydk , I removed updatehosts, and then ran the script. I will updateIP manually each time I start the container. This works for me. Also, while I included -includeTestToolkit -includeTestLibrariesOnly ` in the same script, I am only able to install the 4 test apps. Upon pblishing the 5th one (Tests- Test Libraries) I get this:
Publishing C:\ProgramData\NavContainerHelper\Extensions\BC16-4US2\_Microsoft_Tests-TestLibraries_16.4.14693.15807.app
WARNING: UnhandledErrorMessage
The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being 
exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '10675199.02:48:05.47758
07'.
at <ScriptBlock>, <No file>: line 12
The socket connection was aborted. This could be caused by an error processing your message or a receive timeout 
being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was 
'10675199.02:48:05.4775807'.
At C:\Program 
Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 
char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Publish-NAVApp], CommunicationException

How can I resolve this?

**Comment by freddydk** [comment]
Note that the IP number changes when restarting containers and/or windows.
On the issue at hand, you could try -doNotUseRuntimePackages when creating your container or you could run flush-containerhelpercache if something in the cache is broken.

**Comment by AnantshreeChandola** [comment]
@freddydk Thanks for all your responses but still after adding -doNotUseRuntimePackages, I get this error:

Publishing C:\ProgramData\NavContainerHelper\Extensions\BC16-4US2\_Microsoft_Tests-TestLibraries_16.4.14693.15807.app
The background process reported an error with the following message: "The named pipe target process has ended.".
at Invoke-ScriptInNavContainer, C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandlin
g\Invoke-ScriptInNavContainer.ps1: line 39
at Publish-NavContainerApp, C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\AppHandling\Publish-
NavContainerApp.ps1: line 206
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ObjectHandling\Import-TestTool
kitToNavContainer.ps1: line 167
at Import-TestToolkitToNavContainer, C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ObjectHandl
ing\Import-TestToolkitToNavContainer.ps1: line 150
at New-NavContainer, C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandling\New-NavCo
ntainer.ps1: line 1694
at <ScriptBlock>, C:\Users\achandola\Desktop\Docker scripts\container creation.ps1: line 14
The background process reported an error with the following message: "The named pipe target process has ended.".
At C:\Program 
Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 
char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (a44d594988f72be...363dfa334b4be99:String) [], PSRemotingTransportExc 
   eption
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : a44d594988f72be0e2bb838b0e6d6f5916997d628678e59c3363dfa334b4be99
 

I also tried creating the container after running flush-containerhelpercache, but the same error came up

**Comment by freddydk** [comment]
Does get-eventlogfrombccontainer -containername <containername> reveal any reason in the event log?

**Comment by AnantshreeChandola** [comment]
Information  from the event log:

Type: System.ServiceModel.CommunicationException
Message: The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '10675199.02:48:05.4775807'.
StackTrace:
  
  Server stack trace: 
     at System.ServiceModel.Channels.StreamConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
     at System.ServiceModel.Channels.SessionConnectionReader.Receive(TimeSpan timeout)
     at System.ServiceModel.Channels.SynchronizedMessageSource.Receive(TimeSpan timeout)
     at System.ServiceModel.Channels.TransportDuplexSessionChannel.Receive(TimeSpan timeout)
     at System.ServiceModel.Channels.TransportDuplexSessionChannel.TryReceive(TimeSpan timeout, Message& message)
     at System.ServiceModel.Dispatcher.DuplexChannelBinder.Request(Message message, TimeSpan timeout)
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
  
  Exception rethrown at [0]: 
     at Microsoft.Dynamics.Nav.Management.NavCommand.WriteError(Exception exception, ErrorCategory category, Object target, Boolean rethrow)
     at Microsoft.Dynamics.Nav.Management.NavCommand.WriteError(Exception exception)
     at Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp.PublishToService()
     at Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
Source: Microsoft.Dynamics.Nav.Management
HResult: -2146233087
StackTrace:
  
  Server stack trace: 
     at System.ServiceModel.Channels.StreamConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
     at System.ServiceModel.Channels.SessionConnectionReader.Receive(TimeSpan timeout)
     at System.ServiceModel.Channels.SynchronizedMessageSource.Receive(TimeSpan timeout)
     at System.ServiceModel.Channels.TransportDuplexSessionChannel.Receive(TimeSpan timeout)
     at System.ServiceModel.Channels.TransportDuplexSessionChannel.TryReceive(TimeSpan timeout, Message& message)
     at System.ServiceModel.Dispatcher.DuplexChannelBinder.Request(Message message, TimeSpan timeout)
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
  
  Exception rethrown at [0]: 
     at Microsoft.Dynamics.Nav.Management.NavCommand.WriteError(Exception exception, ErrorCategory category, Object target, Boolean rethrow)
     at Microsoft.Dynamics.Nav.Management.NavCommand.WriteError(Exception exception)
     at Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp.PublishToService()
     at Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
----------------------------------
Type: System.IO.IOException
Message: The read operation failed, see inner exception.
StackTrace:
     at System.Net.Security.NegotiateStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
     at System.Net.Security.NegotiateStream.Read(Byte[] buffer, Int32 offset, Int32 count)
     at System.ServiceModel.Channels.StreamConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
Source: System
HResult: -2146232800
StackTrace:
     at System.Net.Security.NegotiateStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
     at System.Net.Security.NegotiateStream.Read(Byte[] buffer, Int32 offset, Int32 count)
     at System.ServiceModel.Channels.StreamConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
----------------------------------
Type: System.ServiceModel.CommunicationException
Message: The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '10675199.02:48:05.4775807'.
StackTrace:
     at System.ServiceModel.Channels.SocketConnection.ReadCore(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout, Boolean closing)
     at System.ServiceModel.Channels.SocketConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
     at System.ServiceModel.Channels.DelegatingConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
     at System.ServiceModel.Channels.ConnectionStream.Read(Byte[] buffer, Int32 offset, Int32 count)
     at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
     at System.Net.Security.NegotiateStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
     at System.Net.Security.NegotiateStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
Source: System.ServiceModel
HResult: -2146233087
StackTrace:
     at System.ServiceModel.Channels.SocketConnection.ReadCore(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout, Boolean closing)
     at System.ServiceModel.Channels.SocketConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
     at System.ServiceModel.Channels.DelegatingConnection.Read(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
     at System.ServiceModel.Channels.ConnectionStream.Read(Byte[] buffer, Int32 offset, Int32 count)
     at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
     at System.Net.Security.NegotiateStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
     at System.Net.Security.NegotiateStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
----------------------------------
Type: System.Net.Sockets.SocketException
ErrorCode: 10054
Message: An existing connection was forcibly closed by the remote host
SocketErrorCode: ConnectionReset
NativeErrorCode: 10054
StackTrace:    at System.ServiceModel.Channels.SocketConnection.ReadCore(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout, Boolean closing)
Source: System.ServiceModel
HResult: -2147467259
StackTrace:    at System.ServiceModel.Channels.SocketConnection.ReadCore(Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout, Boolean closing)

**Comment by freddydk** [comment]
probably a memory limit problem - I didn't see that you had - memorylimit 3G - please try with 5 or leave out the memory limit

**Comment by AnantshreeChandola** [comment]
@freddydk  Thank you so much for all your help. It finally worked.
