### ISSUE TITLE
FeatureKeys - just a question

### ISSUE THREAD

**Issue by sweikelt** [microsoft/nav-docker#482]
I'm sorry for opening an issue, but can any1 explain, what the -featureKeys switch is for?
i need a possibility to import an existing encryptionKey (we are using multiple containers on the same db) and i was wondering what this switch means.

if there is an other way to ask questions, i would appreciate any hints ;)

**Comment by freddydk** [comment]
-featureKeys is for enabling or disabling features in future/insider versions of the product.
What you are looking for happens here: https://github.com/microsoft/nav-docker/blob/c298143b1d624fafa6f1ae892baff40dd0783e0e/generic/Run/SetupDatabase.ps1#L129
put a DynamicsNAV.key in the shared my folder (-myscripts), then it should get picked up.

**Comment by sweikelt** [comment]
freddy - thank you very much! 
PS: you are doing a very good job
