### ISSUE TITLE
 Import-NAVApplicationObject SQL Server Error

### ISSUE THREAD

**Issue by mbagatelli** [microsoft/nav-docker#483]
When trying to run  Import-NAVApplicationObject inside the docker I get this error 
![image](https://user-images.githubusercontent.com/54594962/94132105-b9702b00-fe56-11ea-80e7-cb2e6bc6001a.png)

This is a 2017cu40 container that I'm trying to just import the new table.

I connected to the sql and gave db owner to the user in User Mapping 
![image](https://user-images.githubusercontent.com/54594962/94132390-22f03980-fe57-11ea-9625-7797b610789d.png)

What am I doing wrong? 
Thanks in advance.

**Comment by freddydk** [comment]
I think you need to specify username and password of the user used to start the container

**Comment by mbagatelli** [comment]
Thanks a lot for the fast reply Freddy.
I'm still very new to this (but loving it) and I fear that I have no idea on how to do that even after trying to research

**Comment by freddydk** [comment]
import-navapplicationobject -username sa -password (the password)

You can also use Import-ObjectsToNavContainer (from outside) and specify the container name instead

**Comment by mbagatelli** [comment]
Thanks Freddy, it worked now!
Much appreciated!
