### ISSUE TITLE
Virus warning in container for 16.5.15953.0

### ISSUE THREAD

**Issue by epernst** [microsoft/nav-docker#485]
I found that there earlier was an issue with virus warnings in #440.
Not sure if its related, but I've seen a similar message many times in the container event log, both with BC 14.x, 15.x and 16.x, on brand new images.

_Log Name:      Application
Source:        MicrosoftDynamicsNavServer$BC
Date:          02-10-2020 10:46:25
Event ID:      225
Task Category: (12)
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      DXS-dev
Description:
Operation did not complete successfully because the file contains a virus or potentially unwanted software.
Event Xml:
  <EventData>
    <Data>Server instance: BC
The service is shutting down.</Data>
  </EventData>_

A little later this comes:
_Log Name:      Application
Source:        MicrosoftDynamicsNavServer$BC
Date:          02-10-2020 10:46:34
Event ID:      226
Task Category: (12)
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      DXS-dev
Description:
This file contains a virus or potentially unwanted software and cannot be opened. Due to the nature of this virus or potentially unwanted software, the file has been removed from this location.
Event Xml:
  <EventData>
    <Data>Server instance: BC
The NAV application was mounted from database 'CRONUS' on database server 'LOCALHOST\SQLEXPRESS'.</Data>
  </EventData>_

This is an onprem 16.5.15953.0 DK container, with a tenant that has been mounted after it was created.
But as I wrote, then I have noticed this message before in 14.16 and 15.8 images as well, but there I were still able to use it as nothing happened. And since it was only information logs (not warnings or errors), then I didn't think more about it.

Now I cannot use the web client, even if it says that the tenant is operational. And this information log is the only thing I have to go with, trying to find the reason.

**Comment by freddydk** [comment]
Are you using images or artifacts?
Could you show me a script + full output of an example where this happens (that shows me OS versions numbers and a whole lot of things)

**Comment by epernst** [comment]
Just tried with a plain container, where I'm finding the same log entry.

```
$ArtifactUrl = Get-BCArtifactUrl -country dk -select Latest -type OnPrem -version 16
$License = 'C:\temp\license.flf'
New-BcContainer -accept_eula -containerName 'Virus' -artifactUrl $ArtifactUrl -licenseFile $License -updateHosts -doNotExportObjectsToText -auth NavUserPassword
```

BcContainerHelper is version 1.0.7
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 2004
Docker Client Version is 19.03.13
Docker Server Version is 19.03.13
Fetching all docker images
Using image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
Creating Container Virus
Version: 16.5.15897.15953-dk
Style: onprem
Multitenant: No
Platform: 16.0.15884.15941
Generic Tag: 0.1.0.23
Container OS Version: 10.0.19041.508 (2004)
Host OS Version: 10.0.19041.508 (2004)
Using process isolation
Using locale da-DK

**Comment by freddydk** [comment]
What antivirus are you running?

**Comment by freddydk** [comment]
I assume that if you are using Hyperv isolation, then it doesn't fail, right?

**Comment by epernst** [comment]
Well it doesn't fail as such. When I run the script above, then it creates a fully functional container, despite the virus information log. So I did find out that it's not this message that prevents me from mounting the tenant.

The machine is using standard Windows Security. 
When I use hyperv, then the same message comes:
Operation did not complete successfully because the file contains a virus or potentially unwanted software.

**Comment by freddydk** [comment]
Is the error from the event log inside the container?

**Comment by epernst** [comment]
Yes, it's the container event log.

**Comment by freddydk** [comment]
I can see that I get the same. It is an information level. There are no virus' in the generic image - they are scanned when published and the artifacts are created by our build team (same process as creating DVD's)
I might try to track down what file this is (causing a false positive) when I have time for it some day, but since it doesn't affect functionality I will postpone

**Comment by epernst** [comment]
That's about the same conclussion I came to. I just don't like to see any messages about potential viruses, even if it's fake news...
