### ISSUE TITLE
Missing images on registry

### ISSUE THREAD

**Issue by markusknappfr** [microsoft/nav-docker#486]
I am currently missing some images for business central onprem. When I look at https://mcr.microsoft.com/v2/businesscentral/onprem/tags/list for example bc onprem 2004 is only available til cu3, current is cu6.
Will these missing images will be available soon? Or did they move to another place?

**Comment by freddydk** [comment]
We do not create docker images anymore.
Instead we publish artifacts.
docs have been modified and you can also read a lot about it here: https://freddysblog.com/2020/06/25/changing-the-way-you-run-business-central-in-docker/
