### ISSUE TITLE
Error when exporting images to file

### ISSUE THREAD

**Issue by miraquel** [microsoft/nav-docker#487]
I want to export the backed up image of the Business Central Sandbox to a .tar file so I can load it into another environment. but I'm having an issue when exporting the image, there's an error message I don't know the cause of the issue

### Expected Behavior
Export an image with the command `docker save -o backup.tar backup`.
Image successfully converted to .tar format file

### Actual Behavior
Export an image with the command `docker save -o backup.tar backup`.
There's an error message that says, 

> Error response from daemon: read \\?\C:\ProgramData\Docker\windowsfilter\88d74bc7321fdc7696365259757582d8c83f841ae4695ee21dec7c800fcb9e7f\UtilityVM\Files\Windows\System32\Dism\UnattendProvider.dll: Data error (cyclic redundancy check).

**Comment by freddydk** [comment]
I don't think you will be able to "move" a Business Central container like that.
I have never tried and can see a million reasons why this would never work.
A better option would be to run the script that creates the container on another machine.
