### ISSUE TITLE
Importing Performance Toolkit to BC Container fails

### ISSUE THREAD

**Issue by AnantshreeChandola** [microsoft/nav-docker#489]
error AL1024: A package with publisher 'Microsoft', name 'Performance Toolkit', and a version compatible with '17.1.0.0' could not be loaded. Symbols for the requested app Performance Toolkit by 
Microsoft 17.1.0.0 could not be found in the database

Following is the script that I am using:
$artifactUrl = $artifactUrl = get-bcartifacturl -country base -storageAccount bcinsider -version 17.1 -sasToken XXXX
$auth = "UserPassword"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'password' -AsPlainText -Force)
$licenseFile = "C:\Users\achandola\Desktop\License files\5164953v16.flf"

 

New-BCContainer -accept_eula `
                -containerName $containerName `
                -auth $auth `
                -credential $credential `
                -licenseFile $licenseFile `
                -includeAL `
                -doNotExportObjectsToText `
                -artifactUrl $artifactUrl  `
                -assignPremiumPlan `
                -isolation hyperv `
                -updateHosts `
                -includeTestToolkit  `
                -doNotCheckHealth `
                -enableTaskScheduler:$false `
                -includePerformanceToolkit `

**Comment by freddydk** [comment]
Please do not include tokens in your issues

**Comment by freddydk** [comment]
You need to include -testtoolkit and -includeTestFrameworkOnly as well.
Next bccontainerhelper this will be automatic.
Please use this https://github.com/microsoft/navcontainerhelper/issues for containerhelper issues and follow the template.
thanks

**Comment by AnantshreeChandola** [comment]
My bad! I was just about to edit that. Thanks.

**Comment by AnantshreeChandola** [comment]
@freddydk I included those parameters as well but it didn't work for me. It fails while publishing _Microsoft_Performance Toolkit Samples.app

**Comment by freddydk** [comment]
Didn't see the response until now.
You would need to dump the full output of the container generation AND the full output when trying to import perf toolkit to get help,
