### ISSUE TITLE
WebClient freezes randomly with "is processing..."

### ISSUE THREAD

**Issue by marknitek** [microsoft/nav-docker#491]
We have 2 container hosts for a self service protal which we run multiple containers on (depending on the time of the day 5-15 per host).

The WebClient on these containers freezes from time to time (its not on a schedule or restricted to a specific action, some actions cause it more some others less). When it happens the WebClient is not responding and this message appears (sorry its in german, but it means "is processing..." or something alike
![image](https://user-images.githubusercontent.com/2346803/106619486-efde5500-6570-11eb-8008-51e4c508c1fe.png)

We have the issue on 17.* containers and 16.* Containers, i have not testet if its the case for versions below.

I can't get my head around why this is happening... 

Some Background Info:
- The hosts are all sized well, have enough RAM (64GB each, Usage is 60-80%)  
- The issue happens even when cpu usage is basicly idle (~10%)
- All VMs use external SQL Databases
- The Hosts affected are running on a **Nutanix** Cluster
- We use Transparent Networking
- There is no info in the event log
- Resmon did not tell my any process causing exessive load when the freeze happens

I have another Host for testing that runs on a hyper-v, where i can't reproduce the issue.
The VMs on Nutanix and on the Hyper-v are basically the same, in fact it was a copy of one of the VMs on Nutanix. 
What i see is there is a difference in the processors these vms can see:

**Nutanix Container Host**
![image](https://user-images.githubusercontent.com/2346803/106620261-ae01de80-6571-11eb-959a-6cbc2cee2d3d.png)

**Hyper-V Container Host**
![image](https://user-images.githubusercontent.com/2346803/106620328-c1ad4500-6571-11eb-8912-4f5586b53937.png)

Could that have an impact? Is there anything else know to cause these issues?
Any Ideas how to troubleshoot further?

**Comment by freddydk** [comment]
I have not tried Nutanix, but from your description it sounds like Nutanix and Docker or BC on Docker have compatibility issues.
@tfenster have you tried Nutanix?

**Comment by tfenster** [comment]
Sorry, never used it actively

**Comment by marknitek** [comment]
I will ask the nutanix engineers about that. 
What i know is that hyperv isolation is not recommended with nutanix. Bit since we use processs isolation and it was working aside from the freezes  i did not see an compatibility issue... Maybe there is one.

Are there other known issues with non hyper-v jypervisors for example ESXi?

**Comment by freddydk** [comment]
Is Nutanix a virtualization engine?

Hyper-v is not needed to run Docker, it runs just fine using process isolation on a Windows Machine and we strive to have Business Central generic images for all shipped windows versions to allow this.

Since virtualization engines are not needed, I won't be able to support any of those. (Hyper-v is the exception as that is MS)

**Comment by tfenster** [comment]
> Are there other known issues with non hyper-v jypervisors for example ESXi?

Quite some years ago I had issues with ESXi hosts becoming extremely slow in networking. But that was Windows Server 2016, I would guess in 2017. Shortly after the whole data center moved to hyper-v and we never saw issues related to that abstraction level again

**Comment by marknitek** [comment]
Well i'am no expert but its a hyper-converge system and its a indeed a virtualization engine.

Sure hyper-v is not needed and we absolutely use process isolation as i stated above. But the Container Host will almost always be a VM on a virtualization platform (hyper-v (or Azure), nutanix, ESX). No one is using barbone machines these days...
Therefore this should be a supported Szenario i think. It's a common platform as is ESX. 

But thank you for your inputs. I well have test a few more things and will update here if i make any progress. 
Last resort would be a separate hyper-v host which will only host the Container Host VMs (The existing one is just for testing and was about to be retired in favor of nutanix...)

**Comment by Koubek** [comment]
@marknitek  When this is happening (WebClient frozen), does it happen in one specific container only, or all of them running on the same host behave incorrectly then?

**Comment by marknitek** [comment]
@Koubek i think it is specific to that session. Because most of the time, opening another tab with a new session is fast again but degrades in performance shortly after again. 

I did a lot of testing and it seems like this is a networking (maybe switching) issue on our physical network.
My findings are that we have some nasty latency spikes in our network when doing testing with psping.exe. I measured huge spikes from a few ms to hundreds or in some scenarios (from one physical switch to another) even thousands. 
Wireshark shows me quite some TCP Retransmission Packets which could indicate for latency issues too.

Still it is very strange that this behaviour only affects BC WebClient in such a noticable way. 
My guess is that there is some pure latency management in terms of tcp packets going on (packets with high latency accumulating some kind of timeout or something like that. I'am no network expert, so i leave the further investigations to someone who is. 

Still if anything i wrote makes sense to someone please share some light if you know more about the latency/timeout mechanisms in BC WebClient. BTW is it using SignalR?

**Comment by Koubek** [comment]
Have you considered switching from transparent networking to a proper network and routing via e. g. Traefik? I would suggest testing that option with some containers. I remember having also some troubles when I started with docker on ESXi in combination with the transparent network driver. It was another issue, nothing related to the problem you are facing but I believe you might save avoid troubles by using another approach.

**Comment by marknitek** [comment]
Yes i considered going that route. But since portmapping a test container did not solve the issue and i think i tried traefik too at some point. So it does not solve my particular issue...

**Comment by marknitek** [comment]
After a very very time of trying things configurations, digging in tcp configuraitons, investigation with a network specialist, looking at wireshark recordings and lots of other investigations...

We finally found the root cause of the problem and solved it!
I was frustrated and searched the net another time (i did this already many times...) and stumbled upon this docker related network issue:
https://github.com/docker/for-win/issues/698

Then i read about RSC and what it does and it looked like it could be the cause if our issues. So i run the command an one of our servers:
```
Get-NetAdapaterRSC | Disable-NetAdapterRSC
```
And yeeeeeesssss it worked! Almost instantly the webclient went butter smooth, navigating the pages is a breeze now as expected.

So to anybody using multiple containers on a Windows Server 2009 even if you don't have problems i would recommend disabling RSC for better performance. It is even recommended to do so for any kind of Web Application. So i would say its a best practice to do so.
