### ISSUE TITLE
RoboCopyFiles missing in Helper Functions for Container Version: onprem/17.5.22499.22546/de 

### ISSUE THREAD

**Issue by svengrav** [microsoft/nav-docker#493]
When navinstall.ps1 tries to call RoboCopyFile, the command fails, because in HelperFunctions.ps1 the function is not yet present in this version. 

Container Baseimage: mcr.microsoft.com/businesscentral:10.0.17763.1817

![image](https://user-images.githubusercontent.com/23522177/113669436-0d848380-96b4-11eb-894a-aca24dc8f2ce.png)

I assume on newer images you added this feature and this is due to the older Windows version?

Ty

**Comment by freddydk** [comment]
That is because you have added navinstall in -myscripts yourself.
the new version of navinstall is not yet in the image - you would need to also add helperfunctions.ps1 to myscripts if you want to use that - or use the preview generic image (add -dev to generic imagename)

**Comment by svengrav** [comment]
Arg, thanks Freddy, I had totally forgotten that again. I am getting old. Came in with #1600. Then I'll add the HelperFunctions.ps1 and hopefully remember it. 😊

Thanks for the quick reply
