### ISSUE TITLE
21H1 Image

### ISSUE THREAD

**Issue by marknitek** [microsoft/nav-docker#497]
Is there an ETA for the 21H1 Generic Image?

**Comment by freddydk** [comment]
I have asked the Windows team, but no response.
I have found that if I use generic image "mcr.microsoft.com/businesscentral:10.0.19041.985" (2004) then it works much better on my 21H1 machine than "mcr.microsoft.com/businesscentral:10.0.19042.985" (20H2)
No idea why - but I can easily run 6 containers in HyperV mode with 2004 - and not even one with 20H2.

**Comment by kylehardin6** [comment]
Our experience has been that 21H1 breaks process isolation.

**Comment by freddydk** [comment]
Every major update breaks process isolation- windows can only use process isolation with the same version

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: kylehardin6 ***@***.***>
Sendt: Friday, May 28, 2021 7:48:09 PM
Til: microsoft/nav-docker ***@***.***>
Cc: Freddy Kristiansen ***@***.***>; Comment ***@***.***>
Emne: Re: [microsoft/nav-docker] 21H1 Image (#497)


Our experience has been that 21H1 breaks process isolation.

**Comment by freddydk** [comment]
I also found that 2004 (19041) works with process isolation on 21H1 (19043)
20H2 (19042) does not.

**Comment by freddydk** [comment]
BcContainerHelper 2.0.15 is updated to use 2004 when host is 21h1 and running process isolation.
