### ISSUE TITLE
How to access the RTC and Service folder of the docker image

### ISSUE THREAD

**Issue by megel** [Microsoft/nav-docker#5]
Is there a posibility to access the RTC / Service folders (inside the container) from computer e.q. as share?
I have found some of the folders in "C:\ProgramData\Docker\WindowsFilter\...\", but is the a better way to acces?

1) I want to use the docker image in a kind of "OnPrem" development szenario. So I want to access the following parts:
- **dockerimage**\Files\Program Files\Microsoft Dynamics NAV\100\Service\FinSQL.exe
- **dockerimage**\Files\Program Files (x86)\Microsoft Dynamics NAV\100\RoleTailored Client\FinSQL.exe
- NAV PowerShell scripts e.g. Microsoft.Dynamics.Nav.Ide.psm1

2) Can I specify the DB User / Password for the container or what is the default?

**Comment by Koubek** [comment]
To access **finsql.exe**:
You have DVD included in the container. This can be copied out of the container. 
You can also adjust the script to do so.

To use **RTC**:
You can use ClickOnce to access as a user.
You can create shares using `-v` attributes.

I am going to post some complex examples soon. There will be presented several scenarios, switches/parameters, gMSA etc.

**Comment by andupopescu** [comment]
I was thinking the same. It will be great to create a ClickOnce for finsql.exe even if it doesn't have the predefined database name and server but at least it will be the same version as the container.

**Comment by megel** [comment]
Yes, a ClickOnce would be very nice. I have found the folder inside of the docker ...ProgramData\Docker\windowsfilter\ folders:

![grafik](https://user-images.githubusercontent.com/15800069/29204340-bbf046b6-7e76-11e7-91cf-93a25c42f3a1.png)

I can start and access the database with this FinSQL.exe

![grafik](https://user-images.githubusercontent.com/15800069/29204512-c09b0e20-7e77-11e7-8f4f-0ea32e600833.png)

But currently I can not use the Debugger.

**Comment by Koubek** [comment]
Yes, the container filesystem is just a symlink. You can access it like (from the docker host) that but I wouldn\`t rely on this too much ;)

BTW - Can you modify the tables in this way?

**Comment by megel** [comment]
Yes I aggree, the access from the docker host is not so good - but it works currently.

It is possible to modify the objects in the database with this way - you have to change the license to your development license - than it works well.

The reason, why I try this stuff is - I want to setup and define an automated environment (maybe) based on Jenkins with several steps:
1. Define a Development Task
2. Jenkins provide the respective NAV with the Database including the current master BRANCH changes in a docker container
3. Developer do some **magic**
4. Developer finish and push the changes
5. Jenkins setup or create a new container based on current MASTER and inject the changes from the DEV-BRANCH = TEST-CONTAINER
6. Jenkins run the TEST-CONTAINER and run the automated tests
7. Success: Jenkins inform the Tester (by mail) / Fail: Jenkins inform the Developer
8. The Tester do some individual (UI based) Tests or the Consultant can validate the changes
9. The DEV-BRANCH is ready
10. TBD

**Comment by Koubek** [comment]
Yes, of course, this should work. I had some concerns but those were based on my previous experience running NAV services on the container and SQL in the domain as a habitual service and all this stuff without **gMSA**... This wasn\`t working well. 

Of course, your situation is different now (with MS containers), everything is running inside the container and MS adapted the images very well.

**Comment by Koubek** [comment]
@freddydk - Is there any chance to have finsql.exe provided via ClickOnce as well? 

This could really simplify the situation because you actually won\`t need any other media or copy the files between the container and the host or search docker volumes on your host etc.

@megel - I think there is another option. I will check it tonight and let you know.

If you don\`t see this option well we can probably close the issue...

**Comment by freddydk** [comment]
I will investigate...

**Comment by tfenster** [comment]
PR #16 should provide you with finsql via ClickOnce

**Comment by tfenster** [comment]
@megel What is happening when you try to debug? For me it does work (just a quick check: Breakpoint in OnOpenPage of page 1, start debugger, do "debug next", run page 1 --> debugger breaks as extected)

**Comment by andupopescu** [comment]
@tfenster - I've tried PR #16 and I get the below error. 
Not sure why, it can't find the 'C:\Run\NAVClientInstallation.html' as I placed it in the host shared directory. 
<img width="851" alt="screen shot 2017-08-12 at 22 37 13" src="https://user-images.githubusercontent.com/13029799/29244388-d473951a-7fae-11e7-8d85-996e10d085fb.png">

**Comment by Koubek** [comment]
@tfenster, @freddydk  - I have never tried running **c/side** using ClickOnce. I had some concerns about it. Please, have you tried working with libraries installed in GAC, modify a table etc.? Especially on a clean machine without another version (**c/side**) being installed previously. Can we expect any other issues/limitations?

**Comment by tfenster** [comment]
@andupopescu How did you try the PR and what did you do then? Probably the easiest would be to clone https://github.com/tfenster/nav-docker/tree/finsql-clickonce and do `docker build` and `docker run` there. NAVClientInstallation.html should be in the Run folder during build, then it will be there during run as well.

@Koubek I can debug, I can change and compile pages, I can't change and compile tables (but I am running without gMSAs, so that is to be expected and probably works otherwise). I also can't create DotNet variables, the client complains about a NavDotNetBrigde which ist missing. Probably we'll have to add one or more additional dlls, I'll try to find out. @freddydk Maybe any quick ideas about that one?

**Comment by megel** [comment]
@tfenster: I have reviewed the scenario with current **devpreview**: 

`docker run -v D:\Docker\My:c:\run\my -e ACCEPT_EULA=Y -e username=Admin -e password=Pass1234 -d -e WindowsAuth=N -e UseSSL=N -m 3G -e ClickOnce=Y navdocker.azurecr.io/dynamics-nav:devpreview`

The debugger start is now possible from "Session List":
![grafik](https://user-images.githubusercontent.com/15800069/29273000-b9933f0c-8102-11e7-883e-8e9c0b0722f0.png)

FinSQL starts from Image-Folder (ClickOnce not present)
![grafik](https://user-images.githubusercontent.com/15800069/29273181-8a8646f4-8103-11e7-90c8-2f1607d5306d.png)

A Run of an Object shows the right Instance:
![grafik](https://user-images.githubusercontent.com/15800069/29273205-b3b574a0-8103-11e7-968e-3b8982afadf8.png)

But the configuration is not present:
![grafik](https://user-images.githubusercontent.com/15800069/29273220-c41df678-8103-11e7-867c-9f2048c78de7.png)

The start of the Debugger Out of FinSql:
![grafik](https://user-images.githubusercontent.com/15800069/29273256-ead069a4-8103-11e7-98c3-c97c38b267b8.png)
ends in the same error:
![grafik](https://user-images.githubusercontent.com/15800069/29273294-0d0d65c6-8104-11e7-826c-2a1df245ae56.png)

FinSQL Options:
![grafik](https://user-images.githubusercontent.com/15800069/29273397-6c1c95b4-8104-11e7-8348-c8d8d4bc34c7.png)

So I recomment to add FinSql as ClickOnce.

@tfenster : Enable the **-d** Flag the Designer?

**Comment by tfenster** [comment]
I'd guess those errors are because of the not supported direct file system access from the host to files inside of the container. Let's see if #16 gets merged and if yes, if that fixes your problem. You could also clone that repo and create your custom build if you don't want to wait

**Comment by megel** [comment]
@tfenster I have tried to build a docker file from your REPO, but the container run only 17sec and stop with Exit(1)

**Comment by tfenster** [comment]
we'd need to go into more detail. If you want, join me here https://gitter.im/nav-docker-tfenster/Lobby

**Comment by tfenster** [comment]
ok, result of the gitter discussion: If you want to run a generic image that you built yourself you need to add a volume mapping for c:\NAVDVD which includes a NAV DVD. E.g. if you have a DVD at C:\install\NAV 2018 Dev July\ and your image is `clickonce` your command would be
```
docker run -e ACCEPT_EULA=Y -e username=Admin -e password=Pass1234 -d -e WindowsAuth=N -e UseSSL=N -m 3G -e ClickOnce=Y -v 'C:\install\NAV 2018 Dev July\:c:\NAVDVD' clickonce
```

**Comment by tfenster** [comment]
Now I've added Microsoft.Dynamics.Nav.DotNetBridge.dll and Microsoft.Dynamics.Nav.Types.dll. With that a no longer get crashes but I also only see assemblies in the .NET tab when creating a DotNet variable, nothing in the Dynamics NAV and Server tabs. Possibly because ClickOnce can only access the dlls that it can reach through it's own delivery? But least with that you should be able to develop anything but custom dll integrations

**Comment by freddydk** [comment]
If you add the AddIns folder to the finsql clickonce manifest as well as the windows client clickonce manifest – this should work.


/Freddy

**Comment by tfenster** [comment]
@freddydk with that adjustment I can see those Assemblies in the Dynamics NAV tab. I still see nothing in the Server tab. Are those the streamed ones? Maybe the ClickOnce deployment can't see them because they aren't part of the original manifest? However from my point of view even without those this is a pretty nice, self-contained environment

**Comment by tfenster** [comment]
One more minor addition to #16: I've changed the naming of the ClickOnce applications to include the build number instead of the hostname. To me it makes more sense to have the ClickOnce application only once per NAV build and not once per hostname

**Comment by freddydk** [comment]
Very nice work Tobias, I will review and test the pull request tomorrow.
Thanks:-)

**Comment by freddydk** [comment]
ClickOnce for finsql pull request accepted.
Generic image built and pushed.
Devpreview images for August and July being built and pushed now.
2017 and 2016 CU's will be built overnight.
