### ISSUE TITLE
Debugging a webservice call in a docker container isn't working.

### ISSUE THREAD

**Issue by JimAIT** [microsoft/nav-docker#500]
got this working previously in a regular on prem environment but it's not hitting my breakpoints in a docker container.

This is my Launch file

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "attach", //WebServoce
            "name": "cERP_EXT",
            "server": "http://cerp14/",
            "serverInstance": "BC",
            "authentication": "UserPassword",
            "startupObjectId": 14195805,
            "startupObjectType": "Page",
            "breakOnError": true,
            "schemaUpdateMode": "ForceSync",
            "breakOnNext": "WebServiceClient" //WebServoce
        }
    ]
}
Thanks for your help.

**Comment by freddydk** [comment]
Sorry for not seeing this issue, assuming it was resolved long ago.
