### ISSUE TITLE
FYI: Can not start a container 2013R2

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/nav-docker#501]
Hi,

This is kind of a follow up on Issue #379. 

We also got stuck with dism not able to enable the dotnet3 feature(s). What helped me (but not my collegue)  was to change the given code of 71\navinstall.ps1 to:

`Write-Host "Installing .NET 3"`

`Set-Service -Name wuauserv -StartupType "Manual"`

`DISM /Online /Quiet /Add-Package /PackagePath:"C:\NAVDVD\Prerequisite Components\microsoft-windows-netfx3-ondemand-package.cab" | Out-Null`

`Dism /online /enable-feature /all /featurename:NetFX3 /Source:"C:\NAVDVD\Prerequisite Components" /limitaccess | Out-Null`

I don't expect that there will be much energy put into this. But maybe it gives you or others a hint what causes issues with that part of the script...

to find out what works I did as suggested: went into the container (yes it is there even if it fails to get NAV running) and worked my way through this dism stuff until I found a combo that worked. I than took a copy of the navinstall.ps1 , changed it accordingly and handed it into new-navcontainer   -myScripts @("C:\temp\run71\navinstall.ps1")

**Comment by freddydk** [comment]
Thanks for sharing.
