### ISSUE TITLE
Problem with Insider Build when mapping addins folder to container

### ISSUE THREAD

**Issue by cmuris** [microsoft/nav-docker#502]
Hi,

I am getting an error when trying to create a container with the latest BC insider build, when I map the addins folder to the container like this:
$additionalParameters = @("--volume c:\work\bc19\:c:\run\Add-Ins")
New-BcContainer -accept_eula -accept_outdated -containerName 'BC19Insider' -imageName 'myown' -artifactUrl $artifactUrl -auth NavUserPassword -shortcuts DesktopFolder -additionalParameters $additionalParameters

In my case (I have two sub folders in my AddIns folder) it results in the following error
Container cannot be copied onto existing leaf item.
at <ScriptBlock>, C:\Run\SetupAddIns.ps1: line 13
at <ScriptBlock>, C:\Run\navstart.ps1: line 148
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1Error

The issue here is, that the SetupAddIns.ps1 script wants to copy the addins to the RoleTailoredClient "Add-Ins" folder. But it seems that, although in BC19 the RTC folder is still present, the Add-Ins folder isn't. The result is that Copy-Items tries to copy the source content into a single file in the destination instead of copying everything as it is in the source.

I don't believe that is relevant anymore to copy the addins to the RoletaileredClientFolder for newer BC versions, or is it? Otherwise the Add-Ins folder needs to be created if it doesn't exist.

**Comment by ti-jalopez** [comment]
Hi,
I've the same error creating a container for ci-nextmajor last weekend. 
Container created from https://bcinsider.azureedge.net/sandbox/19.1.30507.0/es

Best regards,

**Comment by freddydk** [comment]
Sorry for not seeing this issue, assuming it was resolved long ago.
