### ISSUE TITLE
New-BcContainer failing to start correctly

### ISSUE THREAD

**Issue by bsl-paul** [microsoft/nav-docker#506]
I'm creating a new container via the New-BcContainer command, but upon starting the container it gets stuck in a loop of restarting due to being unable to find dll files.
Script is as shown:

PS C:\Windows\system32> New-BcContainer BCTest -accept_eula -artifactUrl (Get-BCArtifactUrl -select Latest -country GB) -Credential (New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)) -updateHosts -auth NavUserPassword
BcContainerHelper is version 2.0.15
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 20H2
Docker Client Version is 20.10.8
Docker Server Version is 20.10.8
Removing BCTest from container hosts file
Removing BCTest-* from container hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\BCTest
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.19042.1165
Creating Container BCTest
Version: 18.4.28601.29648-GB
Style: sandbox
Multitenant: Yes
Platform: 18.0.28593.29542
Generic Tag: 1.0.1.7
Container OS Version: 10.0.19042.1165 (20H2)
Host OS Version: 10.0.19042.1165 (20H2)
Using process isolation
Using locale en-GB
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\BCTest\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BCTest from image mcr.microsoft.com/businesscentral:10.0.19042.1165
7bffe5fdfbbcd20c36a1619a325fa4a92d635dd700ec3c630507ee656a6ece98
Waiting for container BCTest to be ready
Add-Type : Could not find file
'C:\Users\ContainerAdministrator\AppData\Local\Temp\qww0qzeg\qww0qzeg.dll'.
At C:\Run\start.ps1:68 char:1
+ Add-Type -TypeDefinition $Source -Language CSharp -WarningAction Sile ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileNotFoundExcept
   ion
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerS
   hell.Commands.AddTypeCommand

Add-Type : Could not find file
'C:\Users\ContainerAdministrator\AppData\Local\Temp\qww0qzeg\qww0qzeg.dll'.
At C:\Run\start.ps1:68 char:1
+ Add-Type -TypeDefinition $Source -Language CSharp -WarningAction Sile ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileNotFoundExcept
   ion
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerS
   hell.Commands.AddTypeCommand

Add-Type : Could not find file
'C:\Users\ContainerAdministrator\AppData\Local\Temp\qww0qzeg\qww0qzeg.dll'.
At C:\Run\start.ps1:68 char:1
+ Add-Type -TypeDefinition $Source -Language CSharp -WarningAction Sile ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileNotFoundExcept
   ion
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerS
   hell.Commands.AddTypeCommand

Add-Type : Could not find file
'C:\Users\ContainerAdministrator\AppData\Local\Temp\qww0qzeg\qww0qzeg.dll'.
At C:\Run\start.ps1:68 char:1
+ Add-Type -TypeDefinition $Source -Language CSharp -WarningAction Sile ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileNotFoundExcept
   ion
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerS
   hell.Commands.AddTypeCommand

Add-Type : Could not find file
'C:\Users\ContainerAdministrator\AppData\Local\Temp\qww0qzeg\qww0qzeg.dll'.
At C:\Run\start.ps1:68 char:1
+ Add-Type -TypeDefinition $Source -Language CSharp -WarningAction Sile ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileNotFoundExcept
   ion

I built a container last week, which worked as expected. I deleted this prior to trying to create a new one and now I'm getting the errors above.
I've tried removing the BC Image and pulling it again and also reinstalling Docker Desktop, but no difference.
Any help or guidance would be gratefully received.

Thanks

Paul

**Comment by freddydk** [comment]
Could you try to add
-isolation hyperv
or 
-useGenericImage 'mcr.microsoft.com/businesscentral:10.0.19042.1165' -isolation process

**Comment by bsl-paul** [comment]
Thanks Freddy.
Adding the "-Isolation hyperv" switch seems to have done the trick.
