### ISSUE TITLE
Business Central Azure Sandbox v14, cannot download symbols

### ISSUE THREAD

**Issue by kimnoer** [microsoft/nav-docker#508]
Hello!

I've used aka.ms/bcsandboxazure to setup a BC v14.4 w1, and for some reason I cannot download symbols.  Everything else seems to be working just fine. Besides trying externally, I've also tried downloading directly on the with the same result.

This is what I get from VS Code:

[2022-02-18 11:00:45.21] Using reference symbols cache path: c:\Users\vmadmin\Documents\AL\ALProject1\./.alpackages
[2022-02-18 11:00:45.21] Targeting server 'http://rpbc14-2.northcentralus.cloudapp.azure.com/', server instance 'NAV' and tenant 'default'.
[2022-02-18 11:00:45.21] Please authenticate in the Visual Studio Code...
[2022-02-18 11:00:55.38] Using reference symbols cache path: c:\Users\vmadmin\Documents\AL\ALProject1\./.alpackages
[2022-02-18 11:00:55.38] Targeting server 'http://rpbc14-2.northcentralus.cloudapp.azure.com/', server instance 'NAV' and tenant 'default'.
[2022-02-18 11:00:55.39] Using user name and password authentication. User name used is: 'admin'.
[2022-02-18 11:00:55.39] Sending request to http://rpbc14-2.northcentralus.cloudapp.azure.com:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=14.0.0.0&tenant=default
[2022-02-18 11:00:55.39] Sending request to http://rpbc14-2.northcentralus.cloudapp.azure.com:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0&tenant=default
[2022-02-18 11:04:43.71] Error: An error occurred while sending the request.
The underlying connection was closed: An unexpected error occurred on a receive.
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
An existing connection was forcibly closed by the remote host

[2022-02-18 11:04:43.71] Error: An error occurred while sending the request.
The underlying connection was closed: An unexpected error occurred on a receive.
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
An existing connection was forcibly closed by the remote host

Getting the container Eventlog gives me this, which I think might be relevant-

The description for Event ID 705 from source MicrosoftDynamicsNavServer$NAV cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Server instance: NAV
Category: Sql
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 24d7592f-45d9-47ff-a708-deb427121aa2
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 8b2542c7-115f-48ad-9c92-396abefd4dfc
EventTime: 02/18/2022 10:03:35
Message Action completed successfully, but it took longer than the given threshold.
  Execution time: 16878 ms
  Threshold: 1000 ms
  Message: Long running SQL statement 
  Task ID: 3
  Connection ID: 5
  Database Name: CRONUS
  Current Company Name: 
  Statement: SELECT CT.SYS_CHANGE_VERSION, 0[Change Type], CT.SYS_CHANGE_OPERATION, CT.[Object Type], CT.[Object ID], '00000000-0000-0000-0000-000000000000'[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[Object Metadata], @maxChangeTrackingNumberObjectMetadata) CT
UNION ALL
SELECT CT.SYS_CHANGE_VERSION, 1[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], '00000000-0000-0000-0000-000000000000'[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [Debugger Breakpoint], @maxChangeTrackingNumberDebuggerBreakpoint) CT
UNION ALL
SELECT CT.SYS_CHANGE_VERSION, 2[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], '00000000-0000-0000-0000-000000000000'[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[Add-in], @maxChangeTrackingNumberAddIn) CT WHERE CT.SYS_CHANGE_OPERATION = 'U'
UNION ALL
SELECT CT.SYS_CHANGE_VERSION, 3[Change Type], CT.SYS_CHANGE_OPERATION, CT.[Object Type], CT.[Object ID], CT.[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App Object Metadata], @maxChangeTrackingNumberNavAppObjectMetadata) CT
UNION ALL
SELECT CT.SYS_CHANGE_VERSION, 4[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], CT.[App Package ID], CT.[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App Tenant App], @maxChangeTrackingNumberNavAppTenantApp) CT
UNION ALL
SELECT CT.SYS_CHANGE_VERSION, 5[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], CT.[Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App], @maxChangeTrackingNumberNavApp) CT
UNION ALL
SELECT CT.SYS_CHANGE_VERSION, 6[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], CT.[App Package ID], CT.[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App Publish Reference], @maxChangeTrackingNumberNavAppPublishReference) CT

Launch.json looks like this

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://rpbc14-2.northcentralus.cloudapp.azure.com/",
            "serverInstance": "NAV",
            "tenant": "default",
            "authentication": "UserPassword", 
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true
        }
    ]
}

**Comment by kimnoer** [comment]
@freddydk  - do you have any ideas?

**Comment by freddydk** [comment]
Sorry for not seeing this issue, assuming it was resolved long ago.
