### ISSUE TITLE
Report Builder is missing to edit the reports.

### ISSUE THREAD

**Issue by Koubek** [Microsoft/nav-docker#51]
Report Builder should be preinstalled on the machine to be able to design the reports (using Report Build option).

Not sure if is there any chance to deliver it within the ClickOnce package and invoke the delivered (specific) version.

**Comment by freddydk** [comment]
Report Builder is actually inside the docker image (used by finsql when publishing extensions v1 with reports). Haven't tried to include it in Clickonce.

**Comment by freddydk** [comment]
I have created an issue to add report builder to the Azure VMs.
It shouldn't be in the docker container, but it would be nice to have in the azure VM to complete the experience there.
https://github.com/Microsoft/nav-arm-templates/issues/30
