### ISSUE TITLE
BC Crashes after refreshing Data Administration page

### ISSUE THREAD

**Issue by AmandaTest** [microsoft/nav-docker#515]
Hi there,
I'm not sure if this is the right place to log this issue, but I was directed by MS Technical support team to log the issue here because it happens in the Docker Container on the latest insider builds which they cannot replicate on their on prem environments.  But here is the problem.  After creating a brand new container (US Cronus).  
1) In Tell Me, search for and launch Data Administration
2) On the Data Administration page, click Refresh
Result this will pop up a progress dialog but will eventually crash the system:
When did it begin and how often does it occur?
Occurs every time (happens for me 5 seconds after clicking the refresh button the first time.
What errors do you see?
Something went wrong
What's the environment and are there recent changes?
Version: US Business Central 21.0 (Platform 21.0.42790.0 + Application 21.0.42833.0) and
Version: US Business Central 20.2 (Platform 20.0.41086.42556 + Application 20.2.41144.42689)

**Comment by freddydk** [comment]
Data Administration page is not available when running on-premises as this is an online feature.
When running sandbox containers, the container thinks that it is online, but it isn't.
I will file a bug on the team, but I will assume that they block the page in sandbox containers more than they make data administration work.
