### ISSUE TITLE
Username/Password to NAV docker container

### ISSUE THREAD

**Issue by chaoz** [Microsoft/nav-docker#52]
>>Get started – run your first NAV docker container
>>On your machine with Docker, open a command prompt and type this command (please obtain username and password from Microsoft):

navdocker.azurecr.io leads to the Azure-login page and I've tried using the login information from my existing Azure account with no success.

What am I missing? Do you have any more specific information how to acquire valid  credentials?

//Nicklas

**Comment by Koubek** [comment]
You have to ask @freddydk as the login has nothing to do with your Azure credentials. Please, keep in mind that you are trying to access private docker registry hosted in Azure and the private registry for NAV are hosted by Microsoft and they create special userid and pwd.

**Comment by freddydk** [comment]
FYI, at Directions yesterday we told that we will be going live with docker images on the public docker hub autumn 2017, so probably within the next 1-2 months.
Until then the private registry is the only option and if you email me at freddyk at microsoft dot com then I can help you.

**Comment by chaoz** [comment]
Thank you for the information. I can wait until it's public.
