### ISSUE TITLE
Add support to use SQL Server Developer edition

### ISSUE THREAD

**Issue by amea20** [microsoft/nav-docker#521]
Hello,

When working on Business Central. we currently have disk space limitations when using SQL Server Express Edition as the default SQL Server, and would like to request an enhancement to support using SQL Server Developer edition.

Please let me know if you can look into that.

Thanks

**Comment by freddydk** [comment]
We are not going to change the version inside the container.
The workaround is to use SQL on the host (where you can have developer edition).
