### ISSUE TITLE
Generic Image updates

### ISSUE THREAD

**Issue by joachimcarrein** [microsoft/nav-docker#523]
It seems not all generic images are updated for v22 (the new files in 210-new)
We use 10.0.17763.1879 and 10.0.18362.1256 as OS, those don't have the new code to check if the nav.apps.management.psd1 is in de management folder. As a result -IncludeTestToolkit doesn't work.
I'm not sure if other stuff might be set up wrong as well.

**Comment by freddydk** [comment]
What generic tag are you seeing when creating a container?

**Comment by rdebath** [comment]
Please rebuild the "2004" image with the most recent version of this repo to fix IncludeTestToolkit for v24; that generic image predates the mentioned commit, [this commit is missing](https://github.com/microsoft/nav-docker/commit/c68964f10ea8fed9c9d6bee6295969a82fa20255) along with many others.

This also happens to ltsc2021 so I'm still running ltsc2019 despite the end of mainstream support.
```
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.19041.1415
mcr.microsoft.com/businesscentral:10.0.19041.1415
Generic Tag: 1.0.2.14
Container OS Version: 10.0.19041.1415 (2004)
Host OS Version: 10.0.19044.3930 (21H2)
Using process isolation
```

And Windows 10 Professional 22H2
```
BcContainerHelper version 6.0.5
Setting MicrosoftTelemetryConnectionString = 
### Running New-Bcimage using Artifact  https://bcinsider.azureedge.net/sandbox/24.0.15733.0/gb  ###
INFO: Windows 10 21H1/21H2 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1/21H2
WARNING: Unable to find matching generic image for your host OS. Using mcr.microsoft.com/businesscentral:10.0.19041.1415
...
Style: sandbox
Multitenant: No
Version: 24.0.15489.0
Platform: 24.0.15396.0
Generic Tag: 1.0.2.14
Container OS Version: 10.0.19041.1415 (2004)
Host OS Version: 10.0.19045.3930 (22H2)
Using process isolation
Using locale en-GB
...
WARNING: You are running a container which is 697 days old
```

**Comment by freddydk** [comment]
I will be investigating/updating generic images the upcoming week

**Comment by rdebath** [comment]
Actually it looks like this: https://github.com/microsoft/navcontainerhelper/issues/3369 belongs here.
the "WARNING: Could not find Microsoft.Dynamics.Nav.Apps.Management.psd1" message comes from this part of the bccontainerhelper scripts.

**Comment by freddydk** [comment]
Going forward we are only building ltsc - currently ltsc2016, ltsc2019 and ltsc2022.
If you are not on the same version as these images, you will need to use HyperV isolation.
All old and vulnerable images have been deleted.

**Comment by ntrappe-msft** [comment]
@freddydk If [this is the official Docker Hub](https://hub.docker.com/r/microsoft/businesscentral) for these images, you may want to update the page or the link on the README of this repo. It looks like it's listing very old support.
