### ISSUE TITLE
businesscentral image vulnerabilities

### ISSUE THREAD

**Issue by gntpet** [microsoft/nav-docker#530]
Hey @freddydk , 
I have been testing recently DockerScout, which does check the image for vulnerabilities, and run ir for the businesscentral image
mcr.microsoft.com/businesscentral:10.0.20348.1850

It comes with multiple critical vulnerabilities 
![image](https://github.com/microsoft/nav-docker/assets/16342128/f994b306-e826-4f48-99bf-701d7f9613e9)

Just wanted to bring it to your attention.

**Comment by freddydk** [comment]
The Generic Docker images have undergone a large change last month to get rid of all old and vulnerable images - we should (very soon) be in a compliant state with all.
