### ISSUE TITLE
Error when deploying the preview

### ISSUE THREAD

**Issue by johndcollins** [Microsoft/nav-docker#54]
Getting an error when deploying the preview. Other images like the 2017-na works fine.

PS C:\Users\Administrator> docker run -e accept_eula=Y navdocker.azurecr.io/dynamics-nav:devpreview-finus
Initializing...
Hostname is 08037660d722
PublicDnsName is 08037660d722
Running Specific Image
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
Starting Internet Information Server
Using NavUserPassword Authentication
Using Database Connection localhost/SQLEXPRESS [FinancialsUS]
Modifying NAV Service Tier Config File for Docker
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 2842DE1B630DF602F1052824EBD05F6EF0C4A2E7
Modifying NAV Service Tier Config File with Instance Specific Settings
Start NAV Service Tier
Using existing license file
Create DotNetCore NAV Web Server Instance
Incorrect function. (Exception from HRESULT: 0x80070001)
at New-NavSiteWithBindings, C:\Program Files\Microsoft Dynamics NAV\110\Web Client\Scripts\NAVWebClientManagement.psm1: line 362
at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\110\Web Client\Scripts\NAVWebClientManagement.psm1: line 324
at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\110\Web Client\Scripts\NAVWebClientManagement.psm1: line 223
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 159
at <ScriptBlock>, C:\Run\navstart.ps1: line 319
at <ScriptBlock>, C:\Run\start.ps1: line 18
at <ScriptBlock>, <No file>: line 1

**Comment by freddydk** [comment]
Are you running Windows 10?
Then you need to add -m 3G on the run line, else you will get strange errors in various places.
I am trying to find a way to be able to tell people this when an error occurs.

**Comment by johndcollins** [comment]
I'm running Windows Server 2016 Standard VM on Windows 10.

**Comment by freddydk** [comment]
and how much memory do you have in that Windows Server 2016?
These errors when starting the container are normally memory related.

**Comment by johndcollins** [comment]
4 GB, but I successfully deployed one with a powershell script giving more parameters.
I just tested again, and as soon as I added parameter : -e useSSL=N it succeeded.

**Comment by johndcollins** [comment]
Here are the two calls. As soon as I added the ssl parameter it succeeded.

PS C:\Configurations> docker run -e accept_eula=Y --name test2 --hostname test2 navdocker.azurecr.io/dynamics-nav:devpreview-finus
Initializing...
Hostname is test2
PublicDnsName is test2
Running Specific Image
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
Starting Internet Information Server
Using NavUserPassword Authentication
Using Database Connection localhost/SQLEXPRESS [FinancialsUS]
Modifying NAV Service Tier Config File for Docker
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 8C2A2BDD93AB103AA976C13EBE50BA4AE2D54901
Modifying NAV Service Tier Config File with Instance Specific Settings
Start NAV Service Tier
Using existing license file
Create DotNetCore NAV Web Server Instance
Incorrect function. (Exception from HRESULT: 0x80070001)
at New-NavSiteWithBindings, C:\Program Files\Microsoft Dynamics NAV\110\Web Client\Scripts\NAVWebClientManagement.psm1: line 362
at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\110\Web Client\Scripts\NAVWebClientManagement.psm1: line 324
at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\110\Web Client\Scripts\NAVWebClientManagement.psm1: line 223
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 159
at <ScriptBlock>, C:\Run\navstart.ps1: line 319
at <ScriptBlock>, C:\Run\start.ps1: line 18
at <ScriptBlock>, <No file>: line 1
PS C:\Configurations> docker run -e accept_eula=Y --name test2 --hostname test2 -e useSSL=N navdocker.azurecr.io/dynamics-nav:devpreview-finus
Initializing...
Hostname is test2
PublicDnsName is test2
Running Specific Image
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
Starting Internet Information Server
Using NavUserPassword Authentication
Using Database Connection localhost/SQLEXPRESS [FinancialsUS]
Modifying NAV Service Tier Config File for Docker
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 1BEEA0EC829EE3D665AED489EC4BA9D10EC9C65D
Modifying NAV Service Tier Config File with Instance Specific Settings
Start NAV Service Tier
Using existing license file
Create DotNetCore NAV Web Server Instance
Creating http download site
Creating Windows user
Enabling SA
Creating NAV user
Container IP Address: 172.20.118.26
Container Hostname  : test2
Container Dns Name  : test2
Web Client          : http://test2/NAV/WebClient/
NAV Admin Username  : admin
NAV Admin Password  : Wywy7557
Dev. Server         : http://test2
Dev. ServerInstance : NAV

Files:
http://test2:8080/al-0.9.12794.vsix

Ready for connections!

**Comment by freddydk** [comment]
Very strange.
Even more that 2017-na works.
Could you send me the output of 
docker inspect navdocker.azurecr.io/dynamics-nav:devpreview-finus
and
docker inspect navdocker.azurecr.io/dynamics-nav:2017-na

**Comment by johndcollins** [comment]
The difference between the two I think is that the preview uses DotNetCore and 2017 does not.

**Comment by johndcollins** [comment]
PS C:\Configurations> docker inspect navdocker.azurecr.io/dynamics-nav:devpreview-finus
[
    {
        "Id": "sha256:2b2437fce1d2401bffc55bceff4671979e869ad03cde1addb697778355933edc",
        "RepoTags": [
            "navdocker.azurecr.io/dynamics-nav:devpreview-finus"
        ],
        "RepoDigests": [
            "navdocker.azurecr.io/dynamics-nav@sha256:8d15c4efda989e76d65f86968606e23bdef25ebc47c04ce5fd150e7ddd718e73"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2017-09-10T22:04:08.8999912Z",
        "Container": "f4b421fbcb5af3164a309f1b61ab8328f156b6f7c613342e9a0f58a420226a2c",
        "ContainerConfig": {
            "Hostname": "fd2b31408dc0",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-0.9.12794.vsix",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/462dd2d3-68cb-46b9-b04a-71b91dea6c2a",
                "DatabaseServer=localhost",
                "DatabaseInstance=SQLEXPRESS",
                "DatabaseName=FinancialsUS",
                "DEVPREVIEWURL=https://nav2016wswe0.blob.core.windows.net/dvd/a011bede-1ff9-468a-ae90-6bad50011561"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                "#(nop) ",
                "LABEL created=201709102159 cu=september maintainer=Freddy Kristiansen nav=devpreview version=11.0.18323.0 country=finus"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "sha256:82ab99add4c316cbfd94980bdb70f7fc1158c92c5120f3f1cc99759c5baab3b4",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {
                "country": "finus",
                "created": "201709102159",
                "cu": "september",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Freddy Kristiansen",
                "nav": "devpreview",
                "tag": "0.0.2.3",
                "version": "11.0.18323.0"
            },
            "Shell": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"
            ]
        },
        "DockerVersion": "17.03.2-ee-5",
        "Author": "",
        "Config": {
            "Hostname": "fd2b31408dc0",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-0.9.12794.vsix",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/462dd2d3-68cb-46b9-b04a-71b91dea6c2a",
                "DatabaseServer=localhost",
                "DatabaseInstance=SQLEXPRESS",
                "DatabaseName=FinancialsUS",
                "DEVPREVIEWURL=https://nav2016wswe0.blob.core.windows.net/dvd/a011bede-1ff9-468a-ae90-6bad50011561"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "sha256:82ab99add4c316cbfd94980bdb70f7fc1158c92c5120f3f1cc99759c5baab3b4",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {
                "country": "finus",
                "created": "201709102159",
                "cu": "september",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Freddy Kristiansen",
                "nav": "devpreview",
                "tag": "0.0.2.3",
                "version": "11.0.18323.0"
            },
            "Shell": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"
            ]
        },
        "Architecture": "amd64",
        "Os": "windows",
        "OsVersion": "10.0.14393.1593",
        "Size": 14276031803,
        "VirtualSize": 14276031803,
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\docker\\windowsfilter\\7c215315b6ec7bff20cbdba3703a1af61827ef9ca9fa8d7e5db062ca4a19b091"
            },
            "Name": "windowsfilter"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:f358be10862ccbc329638b9e10b3d497dd7cd28b0e8c7931b4a545c88d7f7cd6",
                "sha256:7997471180059aa2483267e4132b3a7ce450b63834f2d9027b77a4ec01fa3f0b",
                "sha256:24af201bbffb75b64761d8ab07461950205ad1de699766147a31be0ebb54317c",
                "sha256:dbf548c3ce01d778e6fd77040d15f2590ef2ff71debd234555ea763686068378",
                "sha256:e3881e78a4c461eb59b51eef42aaf3cfd9191a049bb148d89f8c10998e64df5c",
                "sha256:0e30c9a8d111e5326a10aeea63e2f3f9ad1453693075669e16a3d1d8ed69c5c0",
                "sha256:f0aa052ade0d4a1602c3b1ea94e0aa68de2073d3af4193cb7ed64f42e91072a3",
                "sha256:9e5a8d00cc0e55fde63ea82e426759d8b46fe972b0ad7440ddcbe9f3a82e151b",
                "sha256:22b48bc6c2d67c2247f170d7b8629226b5bedfcbca83be483959e30655b80445",
                "sha256:d4be5a87a8fa0bc74d5e8ce92699c20cb27c713227f4993459f7a71964f2982b",
                "sha256:5c2089d8c4172819ecde70679eea1ab015e4abcf8ee67fe456fe9ce09c582b47",
                "sha256:aae71f4d88a04ec81a657b327718fa99493793fefd072d582a73421ff6eb2d04",
                "sha256:2ccb9786eb0348dbeacf14939818f71ef22e158bb43a669ffc1c4d0205c82ecf",
                "sha256:549262f7031d091b51d2675e08c82a3600b351044e15fadbc34bc1ecf9eda0b3",
                "sha256:991c0d2521bcdb93c8d677a9f6fefc37a99ef78a159347d18b6c651f46313215",
                "sha256:7b86ee87b3ec683df3405bba56e8d1377c16837d502c06a026507f5b5edec03e",
                "sha256:34afbf6a78c41296be6727f78c2660c6b294c3ef4f1852c3c50cda26d828fb94",
                "sha256:2f1c0e22b9e3e84c725a168f534503e21e24ac3ff23d462bbc80ea8296c140ce",
                "sha256:2988014bd86c8de39c75186aae8f68b055eb1425251d0a5470dd6da7fc2665d3",
                "sha256:110f9ce48f643caa8f58f8d12020baa302c0b7e2e846b6e6e3206d5eea0bb538",
                "sha256:fc198f11c668b347532d7281fe6bf3e73ff80ad1c9b8514b930c58b31b1188a6",
                "sha256:dded630efbb3b6e3ef976d593e57a912695b86a9e4342c1ac2ae131e9dafe838",
                "sha256:aae0fdca2569b81dae2609f66e9cff0f4e25f004fcf1ad1d3853caa862ca5615"
            ]
        }
    }
]

**Comment by johndcollins** [comment]
PS C:\Configurations> docker inspect navdocker.azurecr.io/dynamics-nav:2017-na
[
    {
        "Id": "sha256:7bba3a58621e222a8b184574546d5175bb0a0695f2700c85e8089e8f9491f4e8",
        "RepoTags": [
            "navdocker.azurecr.io/dynamics-nav:2017-na"
        ],
        "RepoDigests": [
            "navdocker.azurecr.io/dynamics-nav@sha256:418c3d421627a5e365492707fd49ac95b9d41edf6e40155b284c83e5aeb65550"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2017-09-11T12:09:12.0759025Z",
        "Container": "b5b7e8a1a14d0f1e523bcfdf71956f05b2e8070f021ce867712c4795406dad07",
        "ContainerConfig": {
            "Hostname": "fd2b31408dc0",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/d6af3ac0-8ec4-461e-87cf-3c3457d3d6cc",
                "DatabaseServer=localhost",
                "DatabaseInstance=SQLEXPRESS",
                "DatabaseName=CronusNA",
                "COUNTRYURL=https://nav2016wswe0.blob.core.windows.net/dvd/e11b75a1-1cc3-4c2a-a3b9-0f6fab14a843"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                "#(nop) ",
                "LABEL version=10.0.18197.0 country=na created=201709111205 cu=cu10 maintainer=Freddy Kristiansen nav=2017"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "sha256:ca658fa7ed6903262d2fa41edd0aba99ab659b90d3b2691b334baa206809cad4",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {
                "country": "na",
                "created": "201709111205",
                "cu": "cu10",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=724017",
                "maintainer": "Freddy Kristiansen",
                "nav": "2017",
                "tag": "0.0.2.3",
                "version": "10.0.18197.0"
            },
            "Shell": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"
            ]
        },
        "DockerVersion": "17.03.2-ee-5",
        "Author": "",
        "Config": {
            "Hostname": "fd2b31408dc0",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/d6af3ac0-8ec4-461e-87cf-3c3457d3d6cc",
                "DatabaseServer=localhost",
                "DatabaseInstance=SQLEXPRESS",
                "DatabaseName=CronusNA",
                "COUNTRYURL=https://nav2016wswe0.blob.core.windows.net/dvd/e11b75a1-1cc3-4c2a-a3b9-0f6fab14a843"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "sha256:ca658fa7ed6903262d2fa41edd0aba99ab659b90d3b2691b334baa206809cad4",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {
                "country": "na",
                "created": "201709111205",
                "cu": "cu10",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=724017",
                "maintainer": "Freddy Kristiansen",
                "nav": "2017",
                "tag": "0.0.2.3",
                "version": "10.0.18197.0"
            },
            "Shell": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"
            ]
        },
        "Architecture": "amd64",
        "Os": "windows",
        "OsVersion": "10.0.14393.1593",
        "Size": 13860381422,
        "VirtualSize": 13860381422,
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\docker\\windowsfilter\\63052be14be42127d98dee632bb15ca9ad8ce7e73f2ec64a18fdae21c93b5b44"
            },
            "Name": "windowsfilter"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:f358be10862ccbc329638b9e10b3d497dd7cd28b0e8c7931b4a545c88d7f7cd6",
                "sha256:7997471180059aa2483267e4132b3a7ce450b63834f2d9027b77a4ec01fa3f0b",
                "sha256:24af201bbffb75b64761d8ab07461950205ad1de699766147a31be0ebb54317c",
                "sha256:dbf548c3ce01d778e6fd77040d15f2590ef2ff71debd234555ea763686068378",
                "sha256:e3881e78a4c461eb59b51eef42aaf3cfd9191a049bb148d89f8c10998e64df5c",
                "sha256:0e30c9a8d111e5326a10aeea63e2f3f9ad1453693075669e16a3d1d8ed69c5c0",
                "sha256:f0aa052ade0d4a1602c3b1ea94e0aa68de2073d3af4193cb7ed64f42e91072a3",
                "sha256:9e5a8d00cc0e55fde63ea82e426759d8b46fe972b0ad7440ddcbe9f3a82e151b",
                "sha256:22b48bc6c2d67c2247f170d7b8629226b5bedfcbca83be483959e30655b80445",
                "sha256:d4be5a87a8fa0bc74d5e8ce92699c20cb27c713227f4993459f7a71964f2982b",
                "sha256:510206e4a9130e2906df1f090dc21f6b04d4ad8a271e54e3f233cf0301b835b5",
                "sha256:9556a9e253c3ffc22fca6ab699c243ab8ef26c0891039e22d5491d7d0266d786",
                "sha256:a052086f2366178f8aa704d75ceaed6c7ae69c62b766d4c3afca79f9a8da98b6",
                "sha256:048836daaf75b9a2e80fea3019f913939f2018e26f2b53fd8cb08607c56c0b6c",
                "sha256:957e7c309f26ef0f4728a5d058b546ea9b976ec6aa49bafd1d51b0db6cd95266",
                "sha256:c42846811fab647d5bd3f083fc472de93757172f0043aae7df203bd2ffb1ad32",
                "sha256:1655cb2fe692a15d5a37f5a9bbe0ccfbc555318e66de19a4f80665051a47be59",
                "sha256:bc7476f079acddceb8f424d68e74a23b4bbff0c12265048cdd081bf857351a8c",
                "sha256:a867cb349f36e99cc84b897437213f6ae5588738432bc2d3af776864d568bfd4",
                "sha256:3c72822209e88366934d65230cd1ed4fea49afc772f62c67af9bc43ec1df1949",
                "sha256:70f098c9cfabbb5ef26c390be09ce46cecdd4dbce55131c944fc68cb003e374d"
            ]
        }
    }
]

**Comment by freddydk** [comment]
John, if you install the latest updates to Windows Server 2016 (your host), then I think this problem goes away.
