### ISSUE TITLE
SQL CU Update is 404

### ISSUE THREAD

**Issue by rdebath** [microsoft/nav-docker#548]
The URL from `generic/DOCKERFILE` gives a http 404 error; specifically:
https://download.microsoft.com/download/6/e/7/6e72dddf-dfa4-4889-bc3d-e5d3a0fd11ce/SQLServer2019-KB5033688-x64.exe

This one seems to work...
https://download.microsoft.com/download/6/e/7/6e72dddf-dfa4-4889-bc3d-e5d3a0fd11ce/SQLServer2019-KB5035123-x64.exe

I guess this means I should add an "if it gives a 404 don't bother with the update" to the script.

**Comment by freddydk** [comment]
This will happen every month before I update these URLs for shipping a new version with latest updates.

**Comment by rdebath** [comment]
@freddydk  Master is currently out of date WRT this, should we be using the "newCDN" branch instead?

Or perhaps they can bother to provide you with a URL that you don't have to change every month, you know so that they don't waste your time on a job that a scheduled pipeline should be able to do!
