### ISSUE TITLE
BC24 Scripts are executed in Powershell 5 bridged mode. Performance is very low

### ISSUE THREAD

**Issue by PatrickSchiefer** [microsoft/nav-docker#549]
Hi,

it seems that BC24 container scripts are running in Powershell 5 instead of PWSH 7.

I guess it is because the shell is set to "powershell.exe" instead of PWSH

https://github.com/microsoft/nav-docker/blob/fdbb3372ad40a7cf958c283838af95b2d4d99ce8/generic/DOCKERFILE#L13C1-L14C111

Our containers need about twice the time to start in BC24. Build Pipelines in our case are also very slow.

@freddydk Could you please have a look?

BR
Patrick
```[tasklist]
### Tasks
```

**Comment by kine** [comment]
Addin link to similar problem in bccontainerhelper

https://github.com/microsoft/navcontainerhelper/issues/3487

**Comment by freddydk** [comment]
The latest ContainerHelper preview will use sessions from/to pwsh inside the container as well and no longer use bridged mode.
Later today (april 23rd) a new preview will be released, which also has SqlServer powershell module available in pwsh using genaric image version 1.0.2.20 (currently preview)
