### ISSUE TITLE
Configured debug request 'publish' is not supported

### ISSUE THREAD

**Issue by yrest** [Microsoft/nav-docker#55]
Hello there,

Have the docker running on local W10 with
docker run -m 3G --name uspreview `
           --hostname uspreview `
           --volume c:\Docker:c:\run\my `
           --env licensefile="c:\run\my\fin.flf" `
           --env accept_eula=Y `
           --env usessl=N `
           --env ClickOnce=Y `

Attempting to publish sample app from local VSCode-Insider 1.17.0 (not inside the VM) and getting above error for the following launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "publish",
            "name": "Publish",
            "server": "http://uspreview",
            "serverInstance": "nav",
            "authentication": "UserPassword"
        }
    ]
}

When doing AL:Go! Am getting the following after the first time
"The folder path is not valid or the folder already exists"
But actual .app file is created in the source folder, rather than in specified.
Could somebody please point me in the right direction?

**Comment by freddydk** [comment]
What error?

You might need a
"tenant": ""
in launch.json

**Comment by yrest** [comment]
Error as the subject - "Configured debug request 'publish' is not supported"

Have added blank tenant with the same outcome.

Interestingly, have deleted the target folder for AL:Go (created from previous attempt) and when trying the command again, right after the folder is recreated am getting message dialog that the folder does not exist anymore.

**Comment by freddydk** [comment]
Where did you get the AL Extensions for VS Code from?
AL:Go should default to a new non-existing folder each time as far as I know.
Can you access the Web Client in http://uspreview/nav/webclient?

**Comment by yrest** [comment]
The latest extension downloaded from container itself.
Can access the web client, clickonce client and dev environment no problem.

Al:go seems to be always directing me to c:\users\<profile>\documents\al\alproject1
Even though my “documents” folder is on different drive, that folder does exist, so i just delete it.
When blank project is created am trying to publish it with F5 getting error in subject.
But originally I wanted to publish Microsoft/AL hello world project, which doesn’t publish with the same symptoms.

**Comment by freddydk** [comment]
I am not sure that the Microsoft/AL Hello world project is up to date - will check that.
AL:Go should work, but you might have found an issue if your documents folder is changed, will check that too.

**Comment by yrest** [comment]
Thanks Freddy, Al:go am launching from Ctrl+Shift+P bar at the top, right?
Also, the default location for “my documents” is changed, but the original folder is still maintained blank by OS.

**Comment by freddydk** [comment]
Just realized that you wrote vscode-insider - please use vscode-stable.

**Comment by yrest** [comment]
Fresh VSCode 1.16.1 with a single extension AL 0.9.12794

Press Ctrl+Shift+P, then AL:Go!
It offers to create new project in C:\Users\<user>\Documents\AL\ALProject1
Even though "my documents" folder is in different place.

Press F5 and it logs the following output
[2017-09-27 14:47:08.81] Using reference symbols cache path: c:\Users\<user>\Documents\AL\ALProject1\.alpackages
[2017-09-27 14:47:08.81] Please authenticate in the Visual Studio Code...
[2017-09-27 14:47:21.02] Using reference symbols cache path: c:\Users\<user>\Documents\AL\ALProject1\.alpackages
[2017-09-27 14:47:21.03] Sending request to http://uspreview:7049/NAV/dev/packages?publisher=Microsoft&appName=US&versionText=11.0.0.0&tenant=default
[2017-09-27 14:47:21.03] Sending request to http://uspreview:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=11.0.0.0&tenant=default
[2017-09-27 14:47:24.82] All reference symbols have been downloaded.
Microsoft (R) AL Compiler version 0.9.12794
Copyright (C) Microsoft Corporation. All rights reserved

Success: The package is created.

Then on the top displays red error "Cannot read property 'type' of undefined"

for the following launch.json
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "al",
			"request": "publish",
			"name": "Local server",
			"server": "http://uspreview",
			"serverInstance": "NAV",
			"tenant": "default",
			"authentication": "UserPassword",
			"startupObjectId": 22
		}
	]
}

**Comment by yrest** [comment]
Actually, I pressed F5 again and it did this
[2017-09-27 15:15:06.64] Sending request to http://uspreview:7049/NAV/dev/apps?tenant=default
[2017-09-27 15:15:12.50] Success: The package has been published to the server.
Then launched default browser and tried to login, displaying page 22 then.

**Comment by yrest** [comment]
Also, when it launches default browser trying to log in, it fails with "cannot reach this page" and the console spits out the following error. But when I login "manually" the extension works on customer card.

TimeGenerated : 9/27/2017 3:25:34 PM
EntryType     : Error
Message       : Server instance: NAV
                Category: Development
                ClientSessionId: 00000000-0000-0000-0000-000000000000
                ClientActivityId: 00000000-0000-0000-0000-000000000000
                ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
                ServerActivityId: 00000000-0000-0000-0000-000000000000
                EventTime: 09/27/2017 14:25:34
                Message <ii>Failed request -- Method:GET; Url:<ii>http://usprev
                iew:7049/NAV/dev/signalr/negotiate?clientProtocol=1.4&connectio
                nData=[{"Name":"DebuggerHub"}]&Authentication=Basic 
                dm1hZG1pbjpQQHNzd29yZDE=</ii>; StatusCode:NotFound; 
                ReasonPhrase:Not Found; ResponseBody: <pi>{"Message":"No HTTP 
                resource was found that matches the request URI 'http://usprevi
                ew:7049/NAV/dev/signalr/negotiate?clientProtocol=1.4&connection
                Data=[{\"Name\":\"DebuggerHub\"}]&Authentication=Basic 
                dm1hZG1pbjpQQHNzd29yZDE='."}</pi></ii>
                ProcessId: 2776
                Tag: 00000LY
                ThreadId: 15
                CounterInformation:

**Comment by freddydk** [comment]
The latest two errors are known issues with September preview.
If you use tenant=default in September preview, then web Client login doesn't work.
You need to have tenant="" in launch.json

**Comment by yrest** [comment]
Thanks Freddy! Why would it not work in insider at all?

**Comment by freddydk** [comment]
It might, but insider builds are "untested" daily builds from VS Code.
Basically, we don't want to spend time on diving into bugs in VS Code Insider builds, when they might find those themselves before shipping.
The opposite of insider is stable - that kind of explains it:-)

**Comment by yrest** [comment]
Fair enough Freddy! So when you release a new update, the "docker pull" should update local image and no other manipulation is required?

**Comment by freddydk** [comment]
I don't think I understand the question?
Docker pull will download a new image
Docker run will run and image and create a container
Docker rm will remove a container

**Comment by yrest** [comment]
After Microsoft releases October update, the "docker pull" will download that and update local image, right?

**Comment by freddydk** [comment]
Correct, if you use the "devpreview-finus" tag.
if you use "devpreview-september-finus" then of course not.
Docker run will not download a new image automatically.

**Comment by yrest** [comment]
As one click we use Freddys script, which does rm, then pull and finally run. I just wanted to double check that the pull will always sync latest changes. Thanks Freddy!

**Comment by yrest** [comment]
Hi Freddy, we're back... 
The VSCode Stable has been updated to 1.17.0 and as you can guess, it is same error now - Chosen debug configuration has an unsupported attribute value `request`: 'publish'... 
FYI, on 1.18.0-insider, the AL Language 0.9.12794 AL:GO! does not do anything at all.
You haven't released anything yet? (Just checking)

**Comment by freddydk** [comment]
This has nothing to do with docker, the problem is between VS Code and the AL Extension
It is a known problem and they are working on a fix - it should only fail the first time as far as i know.

**Comment by yrest** [comment]
Thanks Freddy, fair enough. Did you release anything into docker?
