### ISSUE TITLE
This is failing again due to constantly changing URLs

### ISSUE THREAD

**Issue by rdebath** [microsoft/nav-docker#556]
File at the below address has been deleted.
`$sql2019LatestCuUrl = 'https://download.microsoft.com/download/6/e/7/6e72dddf-dfa4-4889-bc3d-e5d3a0fd11ce/SQLServer2019-KB5035123-x64.exe'`

I suggest you simply add a condition to skip that file if they provide you with a broken link.

**Comment by freddydk** [comment]
Reason is that a new CU has shipped - the old are being deleted.
I have moved the URLs to GitHub variables - and the pipeline is now grabbing the URLs from GitHub variables.
build.ps1 is being modified to use the same, here: https://github.com/microsoft/nav-docker/pull/557

In the meantime, can you test whether you can run this:

```
gh variable list --repo microsoft/nav-docker
```

with your credentials.

**Comment by freddydk** [comment]
BTW - I cannot skip - images will be flagged as insecure and removed by Microsoft security if we don't apply latest hotfixes every month.

**Comment by rdebath** [comment]
Actually a bit worse than I expected ...
```
failed to get variables: HTTP 403: Must have admin rights to Repository. (https://api.github.com/repos/microsoft/nav-docker/actions/variables?per_page=100)
```

Oh, and as for the URL, how about they give you one that doesn't break every month!

**Comment by freddydk** [comment]
Yeah, just found this out myself - will find a different way.

> Oh, and as for the URL, how about they give you one that doesn't break every month!
Yeah - would be good - I will investigate what I can do

**Comment by freddydk** [comment]
I will probably create a number of aka.ms shortlinks, which I can update when new URLs are available and through that keep the repo without changes.

**Comment by rdebath** [comment]
Well ... I guess that's okay for _me_. 😐 

Maybe can get away with using "GDR"s not "CU"s

**Comment by freddydk** [comment]
FYI https://github.com/microsoft/nav-docker/pull/557

**Comment by rdebath** [comment]
This doesn't look right.
``` diff
diff --git a/generic/tag.txt b/generic/tag.txt
index 14c12ac..beb3fe4 100644
--- a/generic/tag.txt
+++ b/generic/tag.txt
@@ -1 +1 @@
-﻿1.0.2.23
+﻿1.0.2.0
```

**Comment by freddydk** [comment]
The tag is now being applied by the build process - only the first 3 digits from tag.txt are used.
in build.ps1 (next version) - I will use the same tag as the latest shipped version.

**Comment by freddydk** [comment]
Working on adding fulltext (which is a requirement for next major now)

**Comment by freddydk** [comment]
This is now complete - and build grabs the url's from vanity urls (aka.ms/bcdocker-xxxUrl)
Everytime we build new images, we modify these urls to match latest

**Comment by rdebath** [comment]
Right, so when you next change the interface between this and BCContainer helper you'll be incrementing to 1.0.3.*
Actually, it looks to me like you should probably do that increment now and not just change the last number to a day number (ish) in the middle of 1.0.2.*.
