### ISSUE TITLE
Import Object FOB Fails

### ISSUE THREAD

**Issue by johndcollins** [Microsoft/nav-docker#56]
The documentation for importing a fob needs to be updated. When using the script from the word document I get the following error:

: [22922070] The following SQL Server error or errors occurred:
18456,"28000",[Microsoft][SQL Server Native Client 11.0][SQL Server]Login failed for user 'User Manager\ContainerAdministrator'.
4060,"42000",[Microsoft][SQL Server Native Client 11.0][SQL Server]Cannot open database "CRONUS" requested by the login. The login failed.

at Import-NAVApplicationObject<Process>, C:\Program Files (x86)\Microsoft Dynamics NAV\100\RoleTailored Client\Microsoft.Dynamics.Nav.Ide.psm1: line 147
at <ScriptBlock>, C:\Run\my\AdditionalSetup.ps1: line 4
at <ScriptBlock>, C:\Run\navstart.ps1: line 350
at <ScriptBlock>, C:\Run\start.ps1: line 18
at <ScriptBlock>, <No file>: line 1

**Comment by johndcollins** [comment]
The script should be:
Import-NAVApplicationObject -DatabaseServer "localhost" `
                            -DatabaseName $DatabaseName `
                            -Path (Join-Path $PSScriptRoot $objects) `
                            -ImportAction Overwrite `
                            -SynchronizeSchemaChanges Force `
                            -NavServerName "localhost" `
                            -NavServerInstance "NAV" `
                            -Username "SA" `
                            -Password $password `
                            -confirm:$false
This seems to work

**Comment by freddydk** [comment]
Looks correct.
I will fix the document.
I am also working on a module, which has a number of cmdlets for simplifying the work with NAV in Containers. That module will be on github shortly and included in the navdeveloperpreview.

**Comment by freddydk** [comment]
Have a look at this https://github.com/microsoft/navcontainerhelper - it contains functions for doing a lot of the common things

**Comment by freddydk** [comment]
Fixed
