### ISSUE TITLE
navdocker.az-azurecr.io/dynamics-nav - no such host found

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/nav-docker#57]
docker login "navdocker.azurecr.io" -u "<user>" -p "<pass>"
THEN
docker run -m 3G -e ACCEPT_EULA=Y navdocker.az-azurecr.io/dynamics-nav
OR 
docker run -m 3G -e ACCEPT_EULA=Y navdocker.az-azurecr.io/dynamics-nav:2017

Result: 
Unable to find image 'navdocker.az-azurecr.io/dynamics-nav:latest' locally
docker: Error response from daemon: Get https://navdocker.az-azurecr.io/v2/: dial tcp: lookup navdocker.az-azurecr.io on 192.168.65.1:53: no such host

Am I missing a step?

**Comment by freddydk** [comment]
it is navdocker.azurecr.io/dynamics-nav:2017
you misspelled the registry.
And you always need the tag.

**Comment by strophanthus** [comment]
Oh my, not sure where I got the extra az from. Thanks!
