### ISSUE TITLE
Error response from daemon: container

### ISSUE THREAD

**Issue by chiecnhanco** [Microsoft/nav-docker#59]
Help 
docker run --env accept_eula=Y --env username=$AdminUsername --env password=$adminPassword --name $containerName --hostname $hostName --env PublicDnsName=$publicdnsName --env locale=$locale --memory 2048mb --volume c:\NAVFolder:c:\NAVFolder --restart always $imageName

docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 54b52ee00c7cfb3ed94789ce7abde603dbbff302bc3375746b27291fb1ab7612 encountered 
an error during Start: failure in a Windows system call: The operation timed out because a response was not received from the Virtual Machine hosting the Container. (0xc0370109).
At E:\OneDrive\Alligacom\LUONGTHIEN\Docker\Init.ps1:75 char:1
+ docker run --env accept_eula=Y --env username=$AdminUsername --env pa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Program File.... (0xc0370109).:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by freddydk** [comment]
also - can you run other docker containers without errors? Try the nginx with a sample web site.

**Comment by chiecnhanco** [comment]
I run it on Window 10,
I try 
$ docker pull microsoft/nanoserver
$ docker images
$ docker run -it microsoft/nanoserver cmd
It work OK

**Comment by chiecnhanco** [comment]
I installed it on another computer and it still the same error (PC: with ram: 8GB)
Step install:
1. Install window 10, install update 
2. Install docker
3. Load Image navdocker.azurecr.io/dynamics-nav:devpreview
4. run docker 

$rootPath = "C:\NAVFolder"
$logfilePath = "c:\NAVFolder\logstatus.txt"
$adminUsername = "admin"
$adminPassword = "Dicadmin@123"
$hostName = "dicnavserver"
$containerName = "dicnavserver"
$publicdnsName = "dicnavserver"
$locale = "en-US"
$imageName = "navdocker.azurecr.io/dynamics-nav:devpreview"

docker run --env accept_eula=Y --env username=$AdminUsername --env password=$adminPassword --name $containerName --hostname $hostName --env PublicDnsName=$publicdnsName --env locale=$locale --memory 2048mb --volume c:\NAVFolder:c:\NAVFolder --restart always $imageName

**Comment by tfenster** [comment]
Please run 
`docker info`
and the shortest way to run the NAV containers on Win 10
`docker run --env accept_eula=y -m 2g navdocker.azurecr.io/dynamics-nav:devpreview`
and post the full output

**Comment by freddydk** [comment]
A few comments
If you have the option of using Windows Server 2016 - then you should always do so.
Windows 10 needs to reserve the 2gb of memory for the container.
In WIndows Server 2016 you can easily run the container with 4G memory - as it will just limit the memory for the container - but not reserve it. This means that the container can use more memory during startup if necessary.
I would still say that the problem seems unrelated to the NAV container - it can be network or docker setup.
On the trying to run another container - try to run the Microsoft SQL Server Developer container - the nano server really doesn't contain anything.

**Comment by Koubek** [comment]
You say 

> I installed it on another computer and it still the same error (PC: with ram: 8GB)

But the previous error was:
```
 Error response from daemon: container 54b52ee00c7cfb3ed94789ce7abde603dbbff302bc3375746b27291fb1ab7612 encountered
an error during Start: failure in a Windows system call: The operation timed out because a response was not received from the Virtual Machine hosting the Container. (0xc0370109).
At E:\OneDrive\Alligacom\LUONGTHIEN\Docker\Init.ps1:75 char:1
```

Is the error really the same? I can see two things in the error message:
* `The operation timed out because a response was not received from the Virtual Machine hosting the Container` which is the common problem that can be solved using `-m 2G` or `-m 3G`.
* The second thing I can see, and this one is really strange for me and I am not sure if this could have something to do with your problems, is the fact that in the error appear **OneDrive** path. I suppose you use this path only to share your script files to execute `docker run` commands. I suppose you don\`t use **graph** parameter to put also the filesystem into the **OneDrive** folder (I think I have already seen somebody trying to achieve this but in a project, not related with nav-docker repo).

**Comment by Koubek** [comment]
You can also try to turn off the antivirus running on the host.

**Comment by chiecnhanco** [comment]
Docker info
![image](https://user-images.githubusercontent.com/26807095/31158380-85cc8d7a-a8eb-11e7-8346-2a86b058d29a.png)

Docker images
![image](https://user-images.githubusercontent.com/26807095/31158395-a88c75be-a8eb-11e7-9566-de038480b350.png)

$ docker run -it microsoft/nanoserver cmd
![image](https://user-images.githubusercontent.com/26807095/31158465-331e1fb6-a8ec-11e7-9b43-6fd30722f4b3.png)

Run -m 2g or 3g
$ docker run --env accept_eula=y -m 2g navdocker.azurecr.io/dynamics-nav:devpreview
![image](https://user-images.githubusercontent.com/26807095/31158588-e2566e52-a8ec-11e7-89a6-c02b1571a0b4.png)

$ docker run --env accept_eula=y -m 4g navdocker.azurecr.io/dynamics-nav:devpreview
![image](https://user-images.githubusercontent.com/26807095/31158748-2c56b9de-a8ee-11e7-8942-73494ce7265d.png)

**Comment by tfenster** [comment]
Seems like others have had the same problem with non-NAV containers, see [here](https://github.com/moby/moby/issues/32810). Could you add your logs there as well as it seems like someone recently looked into it

**Comment by Koubek** [comment]
Please, you could maybe try the following steps: 
* Disable these features: Hyper-V, Containers
* Restart
* Enable the features again

And then try to run the container again.

**Comment by Koubek** [comment]
@chiecnhanco I have one additional question for you - didn`t you make a manual cleanup of  `C:\ProgramData\Docker\` folder (and subfolders, especially you should focus on `windowsfilter` folder).

If you did, this could be the problem.

**Comment by chiecnhanco** [comment]
@Koubek: Step following

- Disable these features: Hyper-V, Containers
- Restart
- Enable the features again

Yes i did, but still the same error

Next step:

- I remove images
- I check C:\ProgramData\Docker\ and manual cleanup 
- Remote C:\ProgramData\Docker\
- Remote docker  
- Disable these features: Hyper-V, Containers
- Restart
- Install Docker again

But not done!

**Comment by Koubek** [comment]
I had practically the same issues as I tried to make some manual cleanup. It is necessary to clean all folders once started with the cleanup. These are especially important:
C:\ProgramData\Docker\windowsfilter\
C:\ProgramData\Docker\containers\
C:\ProgramData\Docker\image\

But generally, I would recommend deleting of everything inside `C:\ProgramData\Docker` once touched by your hands...

Of course, if you use standard commands like `docker rmi`, `docker pune`..., you don\`t need to delete anything.

**Comment by chiecnhanco** [comment]
I've tried to docker rmi first and load images again, but not

**Comment by yrest** [comment]
@chiecnhanco , what is exact build of W10 you're running?

**Comment by freddydk** [comment]
https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/ should help you identify whether the problem is in Docker or in the Docker image.

**Comment by Mikyle** [comment]
if you are using window 10 Enterprise 10.0.1734 build 17134 the container does not work, it is because of one windows updates for security, if you use window 10 pro it should work fine.
