### ISSUE TITLE
Container gone after docker stop

### ISSUE THREAD

**Issue by richardrobberse** [Microsoft/nav-docker#60]
Whenever I use docker stop to stop a certain container it's gone and not visible through docker ps -a.
Executing a docker start again then results in an error from the daemon: 'No such container <containername>', so the container seems to be gone.

I'm running docker 17.06.2-ce-win27 (13194) stable on Windows 10 enterprise.

Anyone else had the same issue?
Help is very much appreciated!

**Comment by tfenster** [comment]
If you have -rm as Parma for your docker run command, then that would be by design

**Comment by richardrobberse** [comment]
@tfenster I'm not using -rm as parameter!
docker run `
    --rm `
    -m 3G `
    --name $hostname `
    --hostname $hostname `
    -v $PSScriptRoot\my:c:\run\my `
    -e Accept_eula=Y `
    -e Auth=Windows `
    -e username=richardr `
    -e password=$passplain `
    ${NAV_DOCKER_IMAGE}

**Comment by richardrobberse** [comment]
@tfenster You're right, my bad, thanks for the quick reply!

**Comment by jlumbroso** [comment]
@richardrobberse Thanks for asking this question... 😅

@tfenster Thanks for answering this question... 🥳
