### ISSUE TITLE
Running Page Preview from C/SIDE (ClickOnce) + gMSA

### ISSUE THREAD

**Issue by Koubek** [Microsoft/nav-docker#61]
When running Page Preview from C/SIDE deployed with ClickOnce + gMSA (Domain Authenticated) appears the following error:
![Cannot load the Visual Page Preview client assembly or some of its dependencies.](https://user-images.githubusercontent.com/24265973/31011463-a2ce46ec-a50e-11e7-9291-4d75271b8f0e.png)

Also, I noticed some time ago (and yes, I know I told you I had been able to run it correctly but it was a mistake to tell confirm it) that the enhanced dev environment doesn\`t appear. I can use only the old one (without intellisense, autocompletion etc.).

**Comment by freddydk** [comment]
We might remove click-once for CSIDE totally.
There seem to be a lot of issues with this and we have this in the generic layer, people will expect that it just works. People can add it themselves if they want to.

**Comment by tfenster** [comment]
Or maybe remove the documentation, keep the current default as "not installed" but also keep the code as undocumented feature? Maybe add something in the documentation that this is only for "read access"? This would currently be the only thing we'd need to change from the original images and I would definitely like to keep as close to the originals as possible

**Comment by megel** [comment]
Oh no, please don't remove the click-once for C/Side!

**Comment by Koubek** [comment]
Exactly - oh, no! 

Don\`t remove the ClickOnce for C/SIDE. I really love it and I don\`t even think there are too many bugs in there. I can work quite fast with the old-dev environment even without the instellisense and autocompletion ;) So this is no problem for me. 

The PAGE Preview as well (ok, it is helpful in the case you need to fiddle a bit more with the groups and sub-groups but generally I don\`t really need it).

And with gMSA it works really nice - I have multiple icons in Windows Start and just click and run C/SIDE for any environment. And then I run the object and RTC is ready within 3 - 5 seconds. It is pretty fast...

I have mentioned the issues just to be recorded and eventually solved (in the case the solution is easy but...).

**Comment by freddydk** [comment]
I won't remove ClickOnce:-)
But I also won't invest more in fixing it.
