### ISSUE TITLE
Are the skype call videos recorded, and can they be sent to me? 

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/nav-docker#62]
I seem to be missing some important information, as I'm not sure how to get from loading the image to actually running it and having access to the desktop. I'm not sure anymore that this is even how it should be working. The videos from the calls would help my terrible memory catch up a bit.

**Comment by freddydk** [comment]
You should read the how to document, which you can find right here in the github repo.

**Comment by strophanthus** [comment]
I have followed that guide many times, and am still not sure how to access it properly. I can, of course, access the folders in command line, but that is as far as  I've been able to get.

**Comment by freddydk** [comment]
Well, there is no desktop. Docker is running the NAV Service Tier in a container together with other services as needed. You should be able to connect with the web client. and yes, you can get into the container with a prompt and see the files inside.

**Comment by strophanthus** [comment]
Ah, I seem to be misunderstanding the purpose of Docker here.
