### ISSUE TITLE
CTP14 error with finsql clickonce

### ISSUE THREAD

**Issue by pzentner** [Microsoft/nav-docker#63]
When I am trying to install the dev environment through clickonce from the CTP14 docker build, I am getting the following error:

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\pzentner\Downloads\Finsql.application resulted in exception. Following failure messages were detected:
		+ Deployment and application do not have matching security zones.

**Comment by Koubek** [comment]
Please, have you tried access from Internet Explorer? If not, please, try it using IE.

**Comment by pzentner** [comment]
Ok, need to update or rephrase it: This error message above comes on Chrome. On IE or Edge, it works. Is this by design? :)

**Comment by Koubek** [comment]
Yeah, it works like this :)
