### ISSUE TITLE
USERSECURITYID

### ISSUE THREAD

**Issue by strophanthus** [Microsoft/nav-docker#64]
Will/could this be added to al at some point? 

We use it to filter on the Access Control table, to determine if the user has certain permissions.

**Comment by tfenster** [comment]
This is the repository for NAV on Docker, you probably are looking for the [AL](https://github.com/Microsoft/al) repository? And I would suggest to add a bit more information

**Comment by strophanthus** [comment]
ah crap, sorry about that. ignore all these, I will move them

**Comment by strophanthus** [comment]
wrong place
