### ISSUE TITLE
devpreview-october

### ISSUE THREAD

**Issue by pzentner** [Microsoft/nav-docker#68]
When trying to start this, I am getting the following error:

Could not load file or assembly 'Microsoft.Dynamics.Nav.Management, Version=11.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
at <ScriptBlock>, C:\Program Files\Microsoft Dynamics NAV\110\Service\Microsoft.Dynamics.Nav.Management.psm1: line 1
at <ScriptBlock>, C:\Run\navstart.ps1: line 218
at <ScriptBlock>, C:\Run\start.ps1: line 18
at <ScriptBlock>, <No file>: line 1

**Comment by freddydk** [comment]
devpreview-october is not released yet due to signing issues.

**Comment by pzentner** [comment]
I guess, I shouldn't be trying then to see, if I can pull new builds.??
________________________________


Peter Zentner
NAV-X, LLC
Phone: +1 877.779.6289
Email: pzentner@nav-x.com
Website: www.nav-x.com
Address: 670 N Beers Street, Bldg 4 - 2nd Floor, Holmdel, NJ 07733

**Comment by freddydk** [comment]
Correct - you should wait until we post on the team blog that a new version is available.
It will save you some time:-)
