### ISSUE TITLE
Cannot find host container

### ISSUE THREAD

**Issue by chiecnhanco** [Microsoft/nav-docker#69]
When i am trying run ping container
![image](https://user-images.githubusercontent.com/26807095/31374051-943b3c28-adc6-11e7-827e-b1ec9ec6ec61.png)

- docker ps -a (Status unhealthy) not healthy, how to change to healthy status ?
![image](https://user-images.githubusercontent.com/26807095/31374253-6c583be2-adc7-11e7-926b-87accfa11c23.png)

**Comment by tfenster** [comment]
Did you use a NAT network (which would happen if you specify no network arguments to `docker run`) or a transparent network? Or just share your full `docker run` command

**Comment by freddydk** [comment]
It might also be that docker defaults to using the wrong network (a non-connected one).
Try "docker network ls"
Can you access the container using the IP address?

**Comment by chiecnhanco** [comment]
![image](https://user-images.githubusercontent.com/26807095/31377599-ca106a6a-add2-11e7-925a-2b97dc4be245.png)
Yes, I can connect to copy file ....
I created the icon (NAV Container Command Prompt, NAV Container PowerShell Prompt) to connect 
![image](https://user-images.githubusercontent.com/26807095/31377728-39bd6e8a-add3-11e7-8fd8-cbc0954da34c.png)
When i try run NAV FinSql, then out error
![image](https://user-images.githubusercontent.com/26807095/31377863-ac38eec6-add3-11e7-9ac1-5d483798e204.png)

![image](https://user-images.githubusercontent.com/26807095/31377837-91dcdb00-add3-11e7-9624-c3dee625fea1.png)

**Comment by chiecnhanco** [comment]
@tfenster: how to NAT network, i installed default

**Comment by freddydk** [comment]
if you cannot ping win2016, then you also cannot open the database on that.
I assume that you are running on your own computer and not on a Azure VM right?
Is it Windows 10 or 2016?
You first need to figure out what's wrong with name resolution, which seems to be a docker installation problem unrelated to the NAV image.

**Comment by Koubek** [comment]
Both previous responses are correct. I don\`t expect problems related with omitting the network argument, I can see more probable the second response of @freddydk. I suppose you are using Win10 and the similar problems can happen in the case you are switching from LAN to WiFi or changing your WiFi connection. All network related changes can affect the Docker networking stack behavior.

For this reasons, it is always better trying it on your desktop where no network-related changes occur. If you are working on a notebook (I do the same), time to time you would need to adjust something.

I would check `Get-NetAdapter`. Please, avoid any unused hyper-v adapters. And please, post the result of the command (if possible).

**Comment by chiecnhanco** [comment]
I run win 2016 not run window 10 (https://github.com/Microsoft/nav-docker/issues/59)
![image](https://user-images.githubusercontent.com/26807095/31378569-f05b72de-add5-11e7-87bc-9b3a84c2a716.png)

**Comment by tfenster** [comment]
Did you maybe restart a container with the same name multiple times? IP / name resolution failed sometimes for me as well. If that is the case, then `ipconfig /flushdns` might help

**Comment by chiecnhanco** [comment]
See image out:
![image](https://user-images.githubusercontent.com/26807095/31379164-b6f9fbc6-add7-11e7-8107-c1d92dee4537.png)

**Comment by tfenster** [comment]
does `ping win2016` work after that?

**Comment by chiecnhanco** [comment]
Ping request could not find host win2016. Please check the name and try again.

**Comment by tfenster** [comment]
I have to say, I am out of ideas. I would suggest to ask Windows Container support

**Comment by Koubek** [comment]
Please, could you post the output of the following commands?:
`docker inspect nat`
`docker inspect [container_name_or_id]`

**Comment by arvkum** [comment]
just noticed this thread, looking the error from different angle, can you please try calling this as below
tcp:172.26.237.148\SQLEXPRESS,1433
![connect to db](https://user-images.githubusercontent.com/12175754/31386824-1ef76ec4-adc0-11e7-8b82-4dfdb4c731d5.JPG)

Arvind

**Comment by Koubek** [comment]
You say you run Win2016 and you add the reference to #59. But in the thread of the issue no. #59 you stated you were running your containers on Win10 host: 

> I run it on Window 10

So now, I am confused (I really don\`t understand if you are using Win10 host or Win2016 host).

@arvkum - The problem here is @chiecnhanco is not able to ping the container using hostname.

**Comment by chiecnhanco** [comment]
@Koubek: 
My laptop installed window 10
With win10
- Docker run not success reference https://github.com/Microsoft/nav-docker/issues/59
With win2016: I am init VM-HypeV 2016
- Docker run is success (output: Ready for connection!), but not able to ping the container using hostname

**Comment by freddydk** [comment]
So it seems like the only problem you are facing is DNS resolution, but to be sure:
What is the name of your Windows Server 2016 machine?
What is the full docker run command you are running? (mask passwords)

**Comment by chiecnhanco** [comment]
@arvkum:
![image](https://user-images.githubusercontent.com/26807095/31420467-e1a70078-ae6b-11e7-926b-5e7753d24cdb.png)

Sorry, server cannot be found
![image](https://user-images.githubusercontent.com/26807095/31420502-297f62a0-ae6c-11e7-80e6-1d7e5db2f90c.png)

**Comment by chiecnhanco** [comment]
@freddydk:
Name of Windows Server 2016 machine: WIN-3AG3SJS95CO
clear
$rootPath = "C:\NAVFolder"
$logfilePath = "c:\NAVFolder\logstatus.txt"
$adminUsername = "admin"
$adminPassword = "Dicadmin@123"
$hostName = "win2016"
$containerName = "win2016"
$publicdnsName = "win2016"
$locale = "en-US"
$imageName = "navdocker.azurecr.io/dynamics-nav:devpreview"

Write-Host 'Begin create container for NAV Server' -ForegroundColor Cyan
Log "Running $imageName"
docker run --env accept_eula=Y `
    --env username=$adminUsername `
    --env password=$adminPassword `
    --name $containerName `
    --hostname $hostName `
    --env PublicDnsName=$publicdnsName `
    --env locale=$locale `
    --volume c:\NAVFolder:c:\NAVFolder --restart always `
    -e useSSL=N `
    $imageName

**Comment by freddydk** [comment]
Copied and pasted the above and tried it on a Win2016 host here - that works:

![image](https://user-images.githubusercontent.com/10775043/31420907-9414bd5e-ae44-11e7-82c6-77a4df728d68.png)

So again, this must be container hostname resolution on your docker installation
your best option would be to investigate these options:
https://www.google.dk/search?q=host+cannot+resolve+container+hostname

**Comment by chiecnhanco** [comment]
@freddydk: thanks you so much!
I try it

**Comment by Koubek** [comment]
As I asked before, could you, please, run the following commands:
`docker inspect nat`
`docker inspect [container_name_or_id]`
and provide us the output?

**Comment by chiecnhanco** [comment]
- I turn off firewall, and ping host successfully.
- I have connected to nav
Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled false

**Comment by chiecnhanco** [comment]
Thanks all
