### ISSUE TITLE
Do not display user name and user pwd when introduced explicitely

### ISSUE THREAD

**Issue by Koubek** [Microsoft/nav-docker#7]
## Improvement:
Maybe we can avoid user name and user password (or at least the second one) will be displayed when introduced explicitly by the user (within `docker run`).

**Comment by freddydk** [comment]
Good idea, will be implemented.

**Comment by freddydk** [comment]
Has been implemented, new images will be generated

**Comment by megel** [comment]
The password is still accessable in the container with ```docker inspact <containername>``` 

```powershell
docker run --rm -m 3G -h "nav-dev" `
      -e Accept_eula=Y `
      -e Auth=Windows `
      -e username=$username `
      -e passwrod=$password `
      -d "devpreview"
```
```json
 {
            "StdinOnce": false,
            "Env": [
                "Accept_eula=Y",
                "Auth=Windows",
                "username=Username",
                "passwrod=MyPassword"
             ] 
}
```

@freddydk : I made some improvements about this security issue and want to commit my changes for review. I can't commit my branch - what should I do?

**Comment by freddydk** [comment]
You should be able to create a pull request.

**Comment by megel** [comment]
I have added 2 new parameters to the container (```SetupVariables.ps1```):
```
      -e passwordencrypted="$passenc" `
      -e passwordkeypath="$passkey" `
```
```json
{
            "Env": [
                "exitonerror=n",
                "Accept_eula=Y",
                "username=Username",
                "passwordkeypath=C:\\run\\my\\password.key",
                "passwordencrypted=76492d1116743f0423413b16050a5345MgB8AGEAdwBvAHkAUwBlAFAASAA3AEoAcwBkADcAKwB2AEMAZABwADMAagAvAHcAPQA9AHwAOABlADEAYgA1AGUANQAwAGIAZQBkADYAMQBkADcAOQA2AGMANwBlADAAYQA1AGIAMQBhAGYANAAwAGMAOQAzADkAYg
A3AGMAOQBlADAAMQAwAGQANwA0ADAANgA0AGUAMQAzADAAMQAwAGIANwA0ADcAYQA1ADUANwAxADcAMAA=",
                "Auth=Windows"
]
}
```

```passwordkeypath``` is a file for which is added to the My-Path of the container - including a random key for the password:
![grafik](https://user-images.githubusercontent.com/15800069/31601251-93187e54-b259-11e7-9f9e-99acc01c1e43.png)

This keyfile will be removed after the setup of windows user / NAV user in ```SetupVariables.ps1```.

All password variables will be cleared after the initialization in the powershell scripts - at least before the ```MainLoop.ps1``` starts.

Running a container can be done by:
1) Create a random key`and store it in the shared key-file:
```powershell
New-SecureKey "D:\Docker\my\password.key"
```
2) Input the secure password:
```powershell
$passenc   = New-SecurePassword "D:\Docker\my\password.key"
```

**Comment by freddydk** [comment]
@Koubek - I would like to hear your comments to this - you have setup passwords in secure stores earlier.

**Comment by megel** [comment]
From @Koubek Repo I uses the ````nav-docker-examples/basic_winauth/``` scripts and added the security improvements. So the time, when the password is available (unprotected) is during the container initialization. After the key is lost, the encrypted password is still present, but **more** safe than now.

**Comment by Koubek** [comment]
@megel Yes, definitely you are right. You don\`t have to pass the password in an unencrypted way and you won`t be able to see that. But...

I was considering the same some time ago and my conclusion was somewhat similar you have presented recently. But with one difference. 

You are still using a file to pass the secret key between your host and container. My personal opinion... You can simplify it and you can pass directly your password via the file (and then delete them) and the effect should be almost the same...

Or am I wrong? Maybe I am missing something but this was my conclusion I made several months ago. And the same conclusion comes to my mind today as well.

The good way is Docker Swarm, which of course, has its own impacts.
There is another option would be HashiCorp Vault:
https://www.vaultproject.io/
https://hub.docker.com/_/vault/

And of course, using gMSA and domain joined containers.

This is my opinion...

**Comment by megel** [comment]
@Koubek Yes you are right. The reason, why I added this simple (still unsecure) way is:

1) we still have some problems to setup gMSA at our infrastructure
2) WindowsAuth is simple to use
3) this kind of protection (delete the key file) increase the security with a minimum of impact and I know you can still copy the key file, when it is present during initialization, but well the password is still unprotected in the powershell at this time.

Currently I have to rebuild each pulled image with this modification.

**Comment by freddydk** [comment]
You actually don't have to rebuild anything. I think you should be able to override the SetupVariables script with a script which implements this functionality and place that in a my folder, which is shared to any image upon run.

**Comment by megel** [comment]
No, I have tried - this doesn't work:
![grafik](https://user-images.githubusercontent.com/15800069/31654954-cb24a7b8-b327-11e7-8c32-c39640726558.png)
