### ISSUE TITLE
Get-ContainerID returns null

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/nav-docker#70]
![image](https://user-images.githubusercontent.com/6551266/31398630-96f629e6-adb7-11e7-82b4-811ee1a24793.png)

**Comment by Koubek** [comment]
Hi, I have been testing it (the latest version of the module) and don\`t have any problem. I have used autocompletion to evaluate automatically the container name:

![image](https://user-images.githubusercontent.com/24265973/31399754-ada4879c-aded-11e7-9e55-dbe492a439b2.png)

**Comment by tfenster** [comment]
What does docker ps return?

**Comment by andrecavalcanti** [comment]
I have recreated the container and now it works. Thanks for the help.

![image](https://user-images.githubusercontent.com/6551266/31400920-3546a416-adbf-11e7-8c04-12bbc82e40aa.png)
