### ISSUE TITLE
Cannot Compile objects

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/nav-docker#71]
The server instance is running, I can access the webclient, but I cannot compile the objects. I have opened the finsql from the roletailoredclient folder on myfolder(host)

![image](https://user-images.githubusercontent.com/6551266/31405623-2bbb1e96-adcd-11e7-8c51-4ee70e1a183e.png)

**Comment by tfenster** [comment]
Do you run with Windows auth? That's necessary for table compilation to work

**Comment by andrecavalcanti** [comment]
I have changed it to windows authentication and now it works. Thanks for your help !!!!!
