### ISSUE TITLE
Cannot Export Objects

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/nav-docker#73]
I'm logged with windows Auth. When I run the Export-NavContainerObjects I get the error below

![image](https://user-images.githubusercontent.com/6551266/31452110-fa8a50bc-ae7b-11e7-92e3-6357191fe4b2.png)

**Comment by freddydk** [comment]
If you type help Export-NavContainerObjects you can see the syntax.

Export-NavContainerObjects -containerName test -objectsFolder c:\demo\objects -adminPassword <adminpassword> -filter "Modified=Yes"

works here. 
Documentation for navcontainerhelper is still due - work in progress, I just wanted to allow people to get going before everything was done done.

**Comment by andrecavalcanti** [comment]
Thanks. I have checked the help. 

When I enter the command I still get the same error.

![image](https://user-images.githubusercontent.com/6551266/31453926-cb9bc802-ae81-11e7-9626-af838434cfd4.png)

**Comment by freddydk** [comment]
What license are you using?

**Comment by andrecavalcanti** [comment]
I was using the license.flf on the DEMO folder. I have changed it to my partner license and it works correctly. Thanks for your help!!!!
