### ISSUE TITLE
Cannot export objects on 70000000 Range

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/nav-docker#74]
I have uploaded my partner license which I'm able to export all object (text) except the one for the extension I have created (70000000 Range). I am able to export them as text on the devpreview before September with the same license

![image](https://user-images.githubusercontent.com/6551266/31467792-3a8851fa-aea9-11e7-8a77-fd79ca22c340.png)

**Comment by Koubek** [comment]
In my eyes, it really doesn\`t look like a docker related problem.

If you are sure you are able to export all objects except this one using September preview and using the same license but with (for example) August preview you are able to expert all of them, then the problem should be in the core functionality (NAV-related problem; a problem of the build / build vs. license, maybe).

**Comment by andrecavalcanti** [comment]
Do you know if I need to get a new license 7m range? I have been using my partner license without any issues.

**Comment by freddydk** [comment]
Yes, if you haven't gotten a new partner license with the assigned 70mill range objects, you need that.

**Comment by andrecavalcanti** [comment]
ok. I'll get it. Thanks for your help
