### ISSUE TITLE
Not able to import objects import-objectstonavcontainer

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/nav-docker#75]
When I run import-objectstonavcontainer I get the error below, but I'm able to import the objects using import-navapplicationobject

Import-NAVApplicationObject -DatabaseName FinancialsUS -Password NavDevPre@2017 -Path c:\run\my\objects.fob -Username sa -ImportAction Overwrite

![image](https://user-images.githubusercontent.com/6551266/31528420-290a7810-afa1-11e7-8d5d-4c8e5b3d151d.png)

**Comment by freddydk** [comment]
How did you create the myserver?

**Comment by andrecavalcanti** [comment]
`$imageNameTag = "navdocker.azurecr.io/dynamics-nav:devpreview-finus"
docker rm myserver -f
docker pull $imageNameTag
docker run --name myserver `
           --hostname myserver `
           --volume c:\myfolder2:c:\run\my `
           --env accept_eula=Y `
           --env usessl=N `
           --env auth=Windows `
           --env username="vmadmin" `
           --env password="NavDevPre@2017" `
            --env ClickOnce=Y `
           --env ExitOnerror=N `
           $imageNameTag`

**Comment by freddydk** [comment]
You should use the new-csidedevcontainer  - or you need to share the c:\demo folder to the container using -v c:\demo:c:\demo
If you look into the script, you will find that it copies the file to a subfolder under c:\demo in order to make it accessible to the container and use it in the container.

**Comment by freddydk** [comment]
I will try to remove this dependency from the cmdlet in a future version.

**Comment by andrecavalcanti** [comment]
I have run the new-csidedevcontainer and I get the error below. Do you know what is the fullname about?

![image](https://user-images.githubusercontent.com/6551266/31697100-6e9696bc-b383-11e7-9de3-bcbb2a15e5e2.png)

**Comment by freddydk** [comment]
Looks like this in the navcontainerhelper:
    Write-Host "Create Desktop Shortcuts for $containerName"
    $winClientFolder = (Get-Item "$programFilesFolder\*\RoleTailored Client").FullName

Are you running the new-navcsidedevcontainer on your own box or in the Azure VM?
Could you type docker logs myserver and paste the output here?

**Comment by Koubek** [comment]
I had the same problem testing the same thing yesterday. Tested on my own Win10. I hadn`\t time to investigate too much but I personally think `AdditionalSetup.ps1` wasn`\t completed (or executed at all?) and then the following line failed:
```
$winClientFolder = (Get-Item "$programFilesFolder\*\RoleTailored Client").FullName
```

BTW, it looks like in the case you are not able to start container for any system problem (memory too low in my case :( ) the function `Wait-NavContainerReady` doesn`\t handle it and goes waiting...

**Comment by freddydk** [comment]
I will have a look at this next week.

**Comment by Koubek** [comment]
OK, don`\t worry. I have a hint... It looks like a problem related to the license file.

**Comment by Koubek** [comment]
I think the problem is that I reference my NAV license file in a non-$PSScriptRoot folder (for example: `c:\nav\licenses`) and of course, this is not being mapped correctly into the container.

Yes, I can see it. You need your license is being placed in the scripts\`s root folder (or a subfolder) and reference it using *full-path* reference.

And this is something I didn\`t...

**Comment by Koubek** [comment]
I suggest something like this:

```
    if (!(Test-Path $licenseFile)) {
        throw "License file '$licenseFile' must exist in order to create a Developer Server Container."
    }
    # << +++ <<
    if (!($licenseFile.Contains($demoFolder))) {
        throw "License file '$licenseFile' must be placed in $demoFolder folder or any of its subfolders and referenced using full-path format."
    }
    # >> +++ >>
    $containerLicenseFile = $licenseFile.Replace("$demoFolder\", "$containerDemoFolder\")
```

**Comment by andrecavalcanti** [comment]
I'm running the new-csidedev container on my own box

![image](https://user-images.githubusercontent.com/6551266/31721191-b8beede4-b3e6-11e7-9a63-007f5dc2e6e0.png)

**Comment by Koubek** [comment]
@andrecavalcanti Please, could you check my previous posts and confirm that your license file is being placed out of the script`s file subsystem?

I can confirm that the license file must be in the same folder where your `NavContainerHelper.psm1` is being placed or can be in a subfolder of this master folder).

Placing the license into a correct folder solved my problem (with the same symptoms you presented here).

**Comment by andrecavalcanti** [comment]
@Koubek I've placed the license file on C:\demo and it works. Thanks for your help
