### ISSUE TITLE
Updating Container CU Version

### ISSUE THREAD

**Issue by eknraw** [Microsoft/nav-docker#77]
Just tried to see what would happen if I hopped up the cumulative update version (2016 CU16) of a container and point it as an older version (2016 CU1) database.   Is this a scenario that would/should be supported with a container or would it be expected that an upgrade procedure has already been performed with an installed dev client? 

Log: 
Change Database Connection
Import Encryption Key
The Demo Database NAV (9-0) CU1 database on the 8579E5237573 server must be converted by Microsoft Dynamics NAV Development Environment before you can use it with this version of Microsoft Dynamics NAV.

**Comment by Koubek** [comment]
Yes, you are right. In this scenario, you have to upgrade/convert the database to be able to connect the docker service.

And yes, it would be nice to be able to upgrade the database in the same process (docker start) :)

**Comment by Koubek** [comment]
@eknraw BTW, I think you could use `New-CSideDevContainer` from [Microsoft/navcontainerhelper](https://github.com/Microsoft/navcontainerhelper) repository to simplify the conversion.

I haven\`t tried it yet (I have a very small experience with some specific functions only) but I think it should be possible to convert the DB using those scripts instead of having to install/copy C/SIDE files from DVD (and eventually downloading the DVD etc.).

**Comment by eknraw** [comment]
@Koubek Ok, I'll take a look at those functions, thanks!   Obviously what I'm after is the ability to bring up a container and be able to eventually convert with the ClickOnce DEV Client.  Possibly add an option to prevent any type of Client/Database interaction so it doesn't fail?

**Comment by Koubek** [comment]
@eknraw I think I have a solution. I\`ll post it tomorrow. You actually won\`t need any other toolset and you will be able to convert the database directly when starting the container. Or at least I hope you will ;)

**Comment by Koubek** [comment]
I think you could run the following (of course, you will need to adjust the parameters):
```
finsql.exe command=upgradedatabase, servername=sqlserver, database=[dbname], ntauthentication=0, username=[sqllogin], password=[sqlpwd], logfile=c:\run\my\upgrade.log
```

I would place this code into one of the overrides, maybe `SetupConfiguration.ps1` could be OK (the last command in this file).

**Comment by freddydk** [comment]
Please remember, that Docker isn't doing magic for you.
Docker just encapsulates the NAV Service Tier in a container and allow you to run it very easily on a machine, sharing resources etc.
Everything else is business as usual.

**Comment by Koubek** [comment]
Of course, but still, with the supported extensibility you anyone can do a lot of specific things.
People need to understand better the extensibility that NAV on Docker provides for them.

**Comment by freddydk** [comment]
Correct, thanks for pointing this out Jakup:-)

**Comment by eknraw** [comment]
@freddydk It might not be magic but it's pretty darn awesome. :)

Yes, it's not a large use case for sure.

I think my answer is probably the following, just confirmed this works fine.  I'm totally ok with this.

1. Spin up another container that relies on SQLExpress
2. Point that OneClick DEV environment at my persistent database, upgrade
3. Remove and replace existing container with proper CU container
4. ClickOnce client updates automatically
5. Enjoy not having to install NAV locally. :)
