### ISSUE TITLE
Return Control Back to Console

### ISSUE THREAD

**Issue by eknraw** [Microsoft/nav-docker#78]
Is there an option or way to have the docker run command, when it's finished, return control back to the console?   I'm experimenting with a CI pipeline and I *think* it's the healthcheck loop that might be preventing this?   I can probably do -d --log-driver=none as an option.  Would be nice to shave off time not having to wait and then check status of the container.

**Comment by tfenster** [comment]
You can run with -d and use Wait-NavContainerReady to find out when it is ready. After whatever you need to do just kill the container (or the CI box). Not exactly what you want to do, but should give you the same result. I actually just implemented and wrote about a CI pipeline as well [here](https://www.axians-infoma.de/navblog/continuous-integration-appveyor-github-nav/) with my implementation of what you want to do shown [here](https://github.com/tfenster/NavOnAppVeyor/blob/ebb2cdf924e2fb240368d4104807cbead4d6da4a/install.ps1#L27-L32)

**Comment by eknraw** [comment]
@tfenster Ok, that is exactly what I was thinking I'd need to do.  I was using the docker run task which is probably not the way to go (maintaining a long RUN command in a text box??).  Easily, moved off to PS like your example.  Thanks a bunch!
