### ISSUE TITLE
convert-txt2al does not renumber the table to 50010 range

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/nav-docker#79]
I run the convert-txt2al, but it does not renumber to 50100 range

![image](https://user-images.githubusercontent.com/6551266/31801131-ef8aa92a-b513-11e7-8da4-39a15e4da8fd.png)

**Comment by Koubek** [comment]
@andrecavalcanti Hi, many thanks for your feedback but I would like to ask you to classify better the issues. 

I think that this question fits better into [Microsoft/navcontainerhelper](https://github.com/Microsoft/navcontainerhelper) or even into [Microsoft/al](https://github.com/microsoft/al).

My opinion is that it has nothing to do with NAV on Docker... If I am wrong then sorry!!!

**Comment by andrecavalcanti** [comment]
@Koubek I have opened an issue on [Microsoft/al](https://github.com/microsoft/al)
Thanks
