### ISSUE TITLE
Activate Designer Mode in devpreview

### ISSUE THREAD

**Issue by ptijsma** [Microsoft/nav-docker#8]
I don't know if there's a smarter way to achieve this, but I discovered that the InClient Designer mode is not activated by default in the devpreview image.

I've now created a small AdditionalSetup.ps1 script to achieve this:

```
Write-Host "-- ADDITIONAL SETUP : START --"

Import-Module Webadministration
$iisRoot = 'IIS:Sites'
$navWebClientDir = (Get-ChildItem -Path $iisRoot | Where { $_.Name -like '*WebClient*' }).Name
$navWebInstancePath = (Get-ChildItem -Path (Join-Path $navRoot $navWebClientDir) | Where { $_.Name -eq 'NAV' }).physicalPath
Write-Host "Found Web Instance Path: $navWebInstancePath"
Write-Host "Adding Designer mode to web.config"

$NAVWebConfigFile = Join-Path $navWebInstancePath "web.config"
$NAVWebConfig = [xml](Get-Content $NAVWebConfigFile)
$designerKey = $NAVWebConfig.SelectSingleNode("//configuration/DynamicsNAVSettings/add[@key='designer']")
if ($designerkey) {
    Write-Host "Designer key already present, setting to 'true'"
    $designerkey.value = "true"
} else {
    Write-Host "Designer key not present, creating and setting to 'true'"
    $addelm = $NAVWebConfig.CreateElement("add")
    $keyatt = $NAVWebConfig.CreateAttribute("key")
    $keyatt.Value = "designer"
    $addelm.Attributes.Append($keyatt) | Out-Null
    $valatt = $NAVWebConfig.CreateAttribute("value")
    $valatt.Value = "true"
    $addelm.Attributes.Append($valatt) | Out-Null
    $NAVWebConfig.configuration.DynamicsNAVSettings.AppendChild($addelm) | Out-Null
}
$NAVWebConfig.Save($NAVWebConfigFile)
Write-Host "Web.Config file saved under: $NAVWebConfigFile"

Write-Host "-- ADDITIONAL SETUP : END --"
```

Let's say this file is located in **c:\myfolder** then a way to start the image and execute the script could be:
_(use the **-m 4G** option if running on Windows 10)_

`docker run --name devpreview -m 4G -e ACCEPT_EULA=Y -v c:\myfolder:c:\run\my navdocker.azurecr.io/dynamics-nav:devpreview`

**CMD Output:**

![designer mode output cmd](https://user-images.githubusercontent.com/18245218/29171554-3333bbe4-7ddd-11e7-8c95-6554ccf056b2.jpg)

**Web Client Result:**

![designer mode](https://user-images.githubusercontent.com/18245218/29171383-b2fb7160-7ddc-11e7-9f21-91cde7ef948a.jpg)

**Comment by freddydk** [comment]
Very cool Peter. For the July preview, this is the best way.
The August preview will have support for the in client designer directly.

**Comment by Koubek** [comment]
You can see my changes here:
https://github.com/Koubek/GENERIC/commit/97fbc19d246ce96931a652c779ad681a7333c8e6

But weren`t accepted for some logical reasons (next release will change sth. related).
