### ISSUE TITLE
How can I reset development environment if I have broken it?

### ISSUE THREAD

**Issue by dkatson** [Microsoft/nav-docker#80]
Hi I have broken dev environment and don't know how to reset it.
first I saw message 
Invalid object name 'FinancialsUS.dbo.CRONUS USA'. Statement(s) could not be prepared when i opened a page.

Then i've got another 
[2017-10-20 12:18:29.41] Sending request to https://nav2018us09.westeurope.cloudapp.azure.com:7049/NAV/dev/apps
[2017-10-20 12:18:29.57] The request for path /NAV/dev/apps failed with code InternalServerError. Reason: 

So i want just to reset dev environment

**Comment by freddydk** [comment]
What is your development environment?
Are you using the Azure VM (aka.ms/navdeveloperpreview) or are using docker locally?

**Comment by freddydk** [comment]
If a container is broken, remove it and create a new container.
If the Azure VM is broken, remove it and create a new VM.
