### ISSUE TITLE
Could not download reference symbols in local VS Code using docker

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/nav-docker#81]
I am trying to install latest NAV Development Preview on my local host. I'm using docker image **navdocker.azurecr.io/dynamics-nav:devpreview-us** to get the latest devpreview version with US database. 

I was able to start a container and open Dynamics 365 for Financials from a browser. This was my output from running a container:
```
Using existing license file
Create Web Site
Create NAV Web Server Instance
Enable Financials User Experience
Create http download site
NAV Admin Username  : admin
NAV Admin Password  : Duly5913
Container IP Address: 172.25.210.20
Container Hostname  : b12b2204a385
Web Client          : http://b12b2204a385/NAV/WebClient/
Dev. Server         : http://b12b2204a385
Dev. ServerInstance : NAV
```
But when i try to download symbols from new VS Code project i get the error:
```
[2017-10-24 12.43.48.75] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application locale and version are specified in the app.json file
```

My launch.json file looks like this:
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"type": "al",
			"request": "launch",
			"name": "Local server",
			"server": "http://b12b2204a385",
			"serverInstance": "NAV",
			"tenant": "",
			"authentication": "UserPassword",
			"startupObjectId": 22
		}
	]
}
```
And my app.json:
```
{
  "id": "345b5f4c-51a9-4330-9726-27e544e83249",
  "name": "Docker_demo01",
  "publisher": "Default publisher",
  "brief": "",
  "description": "",
  "version": "1.0.0.0",
  "compatibilityId": "1.0.0.0",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "capabilities": [],
  "dependencies": [],
  "screenshots": [],
  "platform": "11.0.0.0",
  "application": {
    "version": "11.0.0.0",
    "locale": "US"
  },
  "idRange": {
    "from": 50100,
    "to": 50149
  }
}
```
Version of the AL Language extension is: **0.9.13932**. Seems like it's a September update from change log. Don't have options to update to October version yet.

**Output of `$PSVersionTable` (from a powershell process):**

```
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by freddydk** [comment]
available country versions of the october preview is -finus, -fingb, -finca and -findk (not -us)
navdocker.azurecr.io is a temporary image repository which will be deleted soon. There might be old versions out there and you have found one.

**Comment by ivandjordjevic** [comment]
Thanks! I was able now to download symbols from server image:

``
[2017-10-25 11.02.09.48] Using reference symbols cache path: c:\Users\ivand\Documents\AL\Docker_demo01\.alpackages
[2017-10-25 11.02.09.49] All reference symbols are already downloaded
``
Still not able to build Hello World app:

`
Microsoft (R) AL Compiler version 0.9.13932
Copyright (C) Microsoft Corporation. All rights reserved
`
`
c:\Users\ivand\Documents\AL\Docker_demo01\HelloWorld.al(5,45): error AL0247: The target Page "Customer List" for the extension object is not found
Error: The package could not be created.
`

**Comment by freddydk** [comment]
This one probably belongs on AL/issues - but instead of the Hello World sample - try to create a new with AL GO! (Ctrl+Shift+P - AL GO!) - select local server and modify launch.json with what you have on the landing page.

**Comment by freddydk** [comment]
I also see, that you are using an old AL compiler in VS Code (0.9.13932) - you should uninstall that and install the new, which is available in the docker image (docker logs <name> will show you the url to use to download the .vsix)

**Comment by ivandjordjevic** [comment]
You were right, it was because of the AL version of extension. Thanks!

![image](https://user-images.githubusercontent.com/20359384/31992166-d5a112aa-b979-11e7-8612-e4eadb740487.png)

I was wondering what that .vsix file was in docker image log but now I know.
