### ISSUE TITLE
Running Docker NAV container with external SQL server

### ISSUE THREAD

**Issue by acyvas** [Microsoft/nav-docker#87]
Is scenario of using SQL server outside docker image supported? 

I suppose it is impossible to run NAV service on docker container, without joining it to domain, where SQL server is located. 

Other option is to specify database credentials, but I cannot find the way to submit those, when running docker image.

**Comment by freddydk** [comment]
There are a lot of options supported - some are documented in the how-to.docx in this repo, some will be documented later - but you can definitely use SQL outside the image. The SQL inside the image is only there for demo etc.

**Comment by acyvas** [comment]
Thank you! I have managed to get working with NavUserPasswordauthentication using SetupDatabase override script example provided in how-to. My mistake was useSSL=N which is not valid for NavUserPassword authentication. I have also changed TrustSQLServerCertificate to true.

Do you have any sources about how i could make docker to access other company servers using windows authentication?

**Comment by Koubek** [comment]
@acyvas I can recommend using [gMSA](https://docs.microsoft.com/cs-cz/virtualization/windowscontainers/manage-containers/manage-serviceaccounts). 

We use it and works really well.

**Comment by acyvas** [comment]
I have tried running container with credentialspec on Windows 10, but it times out.
@Koubek, does docker support gMSA on Windows 10?

**Comment by Koubek** [comment]
@acyvas I am not using **gMSA** on my own notebook but I can try it and confirm the results.

**Comment by acyvas** [comment]
@Koubek I have tried running container with credentialspec on Windows Server 2016 and at least packages runs fine and I can see right domain when I run nltest /parentdomain from docker container.
Looks that there are problems with gMSA support on Windows 10. 
It has been reported on this post as well:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts

**Comment by Koubek** [comment]
I have tested it on my Win10 and no success. Anyway, I am personally OK with the situation. We have automated the process of the creation of the containers via **gMSA** thanks to using security groups and multiple scripts (within a specific PS module deployed on each Docker host). It is very easy for us to spin any container with **gMSA** from WinServer (docker hosts - we have 3 hosts right now). 

But I can\`t imagine doing this from each user machine. Of course, you could create the groups as well but from my point of view, you would need to have a really good security strategy for these groups etc.

**Comment by ivandjordjevic** [comment]
I did set gMSA, but running a docker image with external SQL server returns this error in docker log right after Creating Windows User step...:
````
Microsoft Dynamics NAV Server is currently not ready to serve requests. Try again later, or contact your system administ
rator.
````

**Comment by Koubek** [comment]
I will check this probably the next week... I still don`t have the fall Creator Update installed on my notebook and will install the next week.
