### ISSUE TITLE
Configurable ServerInstance name

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/nav-docker#88]
if not already possible ... :-) ...
it would be nice to be able to configure the serverinstance-name for the NST on the docker container..

**Comment by freddydk** [comment]
It isn't possible and not something we are considering.
Every container will have exactly one server and adding the ability to change the server instance only complicates things.
Having said that, I assume that you can create a script and share that as AdditionalSetup.ps1 which does this - but it is not a scenario I recommend you to use.

**Comment by waldo1001** [comment]
Fair enough.  

The thing I need to get used to most probably is the fact there are multiple servers instead of multiple server instances.. .
