### ISSUE TITLE
MSVCR120.dll and MSVCP120.dll files missing.

### ISSUE THREAD

**Issue by CBlasek** [Microsoft/nav-docker#89]
When I try to download / run the development click from click once I receive the message about missing dlls. I installed the prereqs  as well. I did this from IE.

**Comment by freddydk** [comment]
I think you need
https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe
and
https://download.microsoft.com/download/3/A/6/3A632674-A016-4E31-A675-94BE390EA739/ENU/x64/sqlncli.msi

note that Development environment via click-once doesn't cover all development scenarios, there are a number of things you cannot do.
You could also use the navcontainerhelper powershell module (blog post coming up today)

**Comment by freddydk** [comment]
I have included this in the troubleshooting blog post.
https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/

**Comment by Cred-it** [comment]
Thanks Freddy !
