### ISSUE TITLE
Accessing the devpreview with Visual Studio Code

### ISSUE THREAD

**Issue by ptijsma** [Microsoft/nav-docker#9]
Is there a way to access the devpreview with VS Code?

I noticed this when running the image:

Dev. Server         : https://469690d94d02
Dev. ServerInstance : NAV

Files:
http://469690d94d02:8080/al-0.7.11459.vsix
http://469690d94d02:8080/certificate.cer

But no clue how to connect to it with a local VS Code

Supplied vsix (http://469690d94d02:8080/al-0.7.11459.vsix) installed in VS Code

**Comment by megel** [comment]
Looking for the same access. :)

**Comment by Koubek** [comment]
Use Dev Server URL, in your particular case use https://469690d94d02. You can find more info on the pages that dedicate to this stuff.

Install the extension, run command `AL: Go`, create new proyect and set the link in the project config file.

https://github.com/Microsoft/AL
https://community.dynamics.com/nav/b/mohanasdynamicsnavblog/archive/2016/12/21/developing-extensions-using-the-new-visual-studio-code-part-1
https://robertostefanettinavblog.com/2016/11/29/microsoft-al-al-language-code-samples-for-developing-extensions/

etc.

**Comment by freddydk** [comment]
In order to use VS Code with the July Preview - you need to run Windows Authentication with either gMSA or shared credentials.
August Preview (coming up) will support NavUserPassword as well, I will see how fast we can get that up there.

**Comment by ptijsma** [comment]
Thanks @freddydk 

That makes sense. I'll try that.

**Comment by Koubek** [comment]
Using simple WinAuth (no **gMSA**) I have no problem to download the symbols and start working:
![image](https://user-images.githubusercontent.com/24265973/29184676-48ad8926-7e07-11e7-9078-9b53087d7e0c.png)

Had to switch from US to W1 locales: `"locale": "W1"`
![image](https://user-images.githubusercontent.com/24265973/29184732-785c7970-7e07-11e7-968b-cb1acf4eeb60.png)

**Comment by ptijsma** [comment]
Yep, same here.

![vscode debug](https://user-images.githubusercontent.com/18245218/29185644-20cbf5a2-7e0a-11e7-942a-0dd3136b5fe9.jpg)

Made a few mods though. 
I made local copies of SetupNavUsers.ps1 and SetupSqlUsers.ps1 and put them in the c:\run\my share.
 
Not sure how to 'suggest' this in GitHub:
This is required since my password (pardon my French) does NOT follow the Password Complexity Requirements on my test machine.
I could also imagine this to be an issue with other test / demo environments.

**SetupNavUsers,ps1:**

```
if ($auth -eq "Windows") {
    if (($password -ne "") -and ($username -ne "")) {

        # PT Disable Password Complexity. Source: https://stackoverflow.com/questions/23260656/modify-local-security-policy-using-powershell
        Write-Host "Disabling Password Complexity Requirements"
        $tmpSecPol = "${env:appdata}\secpol.cfg"
        secedit /export /cfg $tmpSecPol | Out-Null
        $dummy = (gc $tmpSecPol).replace("PasswordComplexity = 1", "PasswordComplexity = 0") | Out-File $tmpSecPol 
        secedit /configure /db c:\windows\security\local.sdb /cfg $tmpSecPol /areas SECURITYPOLICY | Out-Null
        rm -force $tmpSecPol -confirm:$false | Out-Null
        # PT Disable Password Complexity

        Write-Host "Create Windows user"
        New-LocalUser -AccountNeverExpires -FullName $username -Name $username -Password (ConvertTo-SecureString -AsPlainText -String $password -Force) -ErrorAction Ignore | Out-Null
        Add-LocalGroupMember -Group administrators -Member $username -ErrorAction Ignore
    }

```

**SetupSqlUsers.ps1:**

```
if ($databaseServer -eq "localhost") {
    if ($password -ne "") {
        # PT Disable Password Complexity.
        #$sqlcmd = "ALTER LOGIN sa with password=" +"'" + $password + "'" + ";ALTER LOGIN sa ENABLE;"
        $sqlcmd = "ALTER LOGIN sa with password=" +"'" + $password + "'" + " , CHECK_POLICY = OFF;ALTER LOGIN sa ENABLE;"
        # PT Disable Password Complexity. Source: https://stackoverflow.com/questions/23260656/modify-local-security-policy-using-powershell
        & sqlcmd -Q $sqlcmd
    }
```

**Comment by Koubek** [comment]
I actually haven\`t had any problems related to the low password complexity. I have made dozens or hundreds of tests but really no problems with the passwords (Password1, etc.).

But maybe there are other people suffering the same issues.

If you want to provide your contribution you should create a PR (Pull Request).

**Comment by freddydk** [comment]
Two things.
For SQL - I wouldn't mind setting Check_Policy = OFF as the local SQL Server is only for TEST/Dev / change will be implemented.
For Windows - I won't take the change.
Easiest thing you could do is to add a setupvariables.ps1 and in that one call default behavior and then do the trick.
This means that when the SetupNavUsers script is executed later, the policy is fine. Alternatively use gMSA and avoid the password hassle in windows users.
