### ISSUE TITLE
Unable to access Web Client

### ISSUE THREAD

**Issue by gunnargestsson** [Microsoft/nav-docker#90]
HTTP Error 401.1 - Unauthorized

Running on Azure Windows 2016 with Containers.

Using

$DockerContainerId = docker.exe run -m 5G -v "$volume" -v "$rootPath" -e ACCEPT_EULA=Y -e username="$adminUsername" -e password="$AdminPassword" -e auth=Windows -e Windowsauth=Y --detach $image

to create the Container.

docker inspect 224a106acae8
[
    {
        "Id": "224a106acae83f0618949261201c2d72bc12adb0a8ce044d6e7ebdbb0b451a36",
        "Created": "2017-11-04T16:53:56.8489435Z",
        "Path": "powershell",
        "Args": [
            "-Command",
            "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
            ".\\Run\\start.ps1"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 18320,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-11-04T16:53:59.3098362Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2017-11-04T17:06:45.517133Z",
                        "End": "2017-11-04T17:06:45.9341358Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-04T17:07:15.936019Z",
                        "End": "2017-11-04T17:07:16.3720328Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-04T17:07:46.3722212Z",
                        "End": "2017-11-04T17:07:46.7791965Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-04T17:08:16.7804542Z",
                        "End": "2017-11-04T17:08:17.1964562Z",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2017-11-04T17:08:47.1982408Z",
                        "End": "2017-11-04T17:08:47.6262132Z",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:5c4d0a5581b26637ed142c8e3ae2db2891023029d77d635275947801a689c998",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\docker\\containers\\224a106acae83f0618949261201c2d72bc12adb0a8ce044d6e7ebdbb0b451a36\\224a106acae83f0618949261201c2d72bc12adb0a8ce04
4d6e7ebdbb0b451a36-json.log",
        "Name": "/modest_haibt",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "C:\\AdvaniaGIT\\Workspace\\a522612e-7dc2-41e4-9dc4-fb7c76ee1555:C:\\GIT",
                "C:\\NAVManagementWorkFolder:C:\\Host"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "process",
            "CpuShares": 0,
            "Memory": 5368709120,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\docker\\windowsfilter\\224a106acae83f0618949261201c2d72bc12adb0a8ce044d6e7ebdbb0b451a36"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\advaniagit\\workspace\\a522612e-7dc2-41e4-9dc4-fb7c76ee1555",
                "Destination": "c:\\git",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\AdvaniaGIT",
                "Destination": "c:\\host",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "224a106acae8",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "ACCEPT_EULA=Y",
                "username=navlightadmin",
                "password=**************",
                "auth=Windows",
                "Windowsauth=Y",
                "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-0.11.14380.vsix",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/796f8b26-d3fc-41fb-b289-b8fc4bab6950",
                "DatabaseServer=localhost",
                "DatabaseInstance=SQLEXPRESS",
                "DatabaseName=CRONUS"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "navdocker.azurecr.io/dynamics-nav:11.0.18843.0",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "W1",
                "created": "201710262234",
                "cu": "",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Freddy Kristiansen",
                "nav": "main",
                "osversion": "10.0.14393.1770",
                "tag": "0.0.3.1",
                "version": "11.0.18843.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "9ac28bbefd619f3beb43a71bc2e96a18e5b4af7984e6155f341af6cc5582b1ea",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "80/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "9ac28bbefd61",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "f2fa66e87355cdcc22c286dbd9fe05bb197a1185bc3ed7ce8582ef3e013e7a17",
                    "EndpointID": "1c1c9fb028767740e4f2f9f7833c06b584a5f6a3b2edcfc9698698387908f0c4",
                    "Gateway": "172.20.96.1",
                    "IPAddress": "172.20.99.243",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:09:e1:7c",
                    "DriverOpts": null
                }
            }
        }
    }
]

docker logs 224a106acae8
Initializing...
Hostname is 224a106acae8
PublicDnsName is 224a106acae8
Running Specific Image
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Using Database Connection localhost/SQLEXPRESS [CRONUS]
Modifying NAV Service Tier Config File for Docker
Modifying NAV Service Tier Config File with Instance Specific Settings
Start NAV Service Tier
Using existing license file
Creating DotNetCore NAV Web Server Instance
Creating http download site
Creating Windows user
Enabling SA
Creating NAV user
Container IP Address: 172.20.99.243
Container Hostname  : 224a106acae8
Container Dns Name  : 224a106acae8
Web Client          : http://224a106acae8/NAV/WebClient/
Dev. Server         : http://224a106acae8
Dev. ServerInstance : NAV

Files:
http://224a106acae8:8080/al-0.11.14380.vsix

Ready for connections!

**Comment by freddydk** [comment]
You can remove -e Windowsauth=Y (Setting Auth=Windows is sufficient)

If you use Windows Authentication, NAV on Docker defaults to http (not https).
If you want to get 18843 to work with windows auth you need to insert -e usessl=Y (before the imagename)
It is a Docker specific bug in WebClient in October and November update, but it is fixed later versions.

/Freddy

Fra: Gunnar Thor Gestsson [mailto:notifications@github.com]
Sendt: 4. november 2017 18:14
Til: Microsoft/nav-docker <nav-docker@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [Microsoft/nav-docker] Unable to access Web Client (#90)


HTTP Error 401.1 - Unauthorized

Running on Azure Windows 2016 with Containers.

Using

$DockerContainerId = docker.exe run -m 5G -v "$volume" -v "$rootPath" -e ACCEPT_EULA=Y -e username="$adminUsername" -e password="$AdminPassword" -e auth=Windows -e Windowsauth=Y --detach $image

to create the Container.

docker inspect 224a106acae8
[
{
"Id": "224a106acae83f0618949261201c2d72bc12adb0a8ce044d6e7ebdbb0b451a36",
"Created": "2017-11-04T16:53:56.8489435Z",
"Path": "powershell",
"Args": [
"-Command",
"$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
".\Run\start.ps1"
],
"State": {
"Status": "running",
"Running": true,
"Paused": false,
"Restarting": false,
"OOMKilled": false,
"Dead": false,
"Pid": 18320,
"ExitCode": 0,
"Error": "",
"StartedAt": "2017-11-04T16:53:59.3098362Z",
"FinishedAt": "0001-01-01T00:00:00Z",
"Health": {
"Status": "healthy",
"FailingStreak": 0,
"Log": [
{
"Start": "2017-11-04T17:06:45.517133Z",
"End": "2017-11-04T17:06:45.9341358Z",
"ExitCode": 0,
"Output": ""
},
{
"Start": "2017-11-04T17:07:15.936019Z",
"End": "2017-11-04T17:07:16.3720328Z",
"ExitCode": 0,
"Output": ""
},
{
"Start": "2017-11-04T17:07:46.3722212Z",
"End": "2017-11-04T17:07:46.7791965Z",
"ExitCode": 0,
"Output": ""
},
{
"Start": "2017-11-04T17:08:16.7804542Z",
"End": "2017-11-04T17:08:17.1964562Z",
"ExitCode": 0,
"Output": ""
},
{
"Start": "2017-11-04T17:08:47.1982408Z",
"End": "2017-11-04T17:08:47.6262132Z",
"ExitCode": 0,
"Output": ""
}
]
}
},
"Image": "sha256:5c4d0a5581b26637ed142c8e3ae2db2891023029d77d635275947801a689c998",
"ResolvConfPath": "",
"HostnamePath": "",
"HostsPath": "",
"LogPath": "C:\ProgramData\docker\containers\224a106acae83f0618949261201c2d72bc12adb0a8ce044d6e7ebdbb0b451a36\224a106acae83f0618949261201c2d72bc12adb0a8ce04
4d6e7ebdbb0b451a36-json.log",
"Name": "/modest_haibt",
"RestartCount": 0,
"Driver": "windowsfilter",
"MountLabel": "",
"ProcessLabel": "",
"AppArmorProfile": "",
"ExecIDs": null,
"HostConfig": {
"Binds": [
"C:\AdvaniaGIT\Workspace\a522612e-7dc2-41e4-9dc4-fb7c76ee1555:C:\GIT",
"C:\NAVManagementWorkFolder:C:\Host"
],
"ContainerIDFile": "",
"LogConfig": {
"Type": "json-file",
"Config": {}
},
"NetworkMode": "default",
"PortBindings": {},
"RestartPolicy": {
"Name": "no",
"MaximumRetryCount": 0
},
"AutoRemove": false,
"VolumeDriver": "",
"VolumesFrom": null,
"CapAdd": null,
"CapDrop": null,
"Dns": [],
"DnsOptions": [],
"DnsSearch": [],
"ExtraHosts": null,
"GroupAdd": null,
"IpcMode": "",
"Cgroup": "",
"Links": null,
"OomScoreAdj": 0,
"PidMode": "",
"Privileged": false,
"PublishAllPorts": false,
"ReadonlyRootfs": false,
"SecurityOpt": null,
"UTSMode": "",
"UsernsMode": "",
"ShmSize": 0,
"ConsoleSize": [
0,
0
],
"Isolation": "process",
"CpuShares": 0,
"Memory": 5368709120,
"NanoCpus": 0,
"CgroupParent": "",
"BlkioWeight": 0,
"BlkioWeightDevice": null,
"BlkioDeviceReadBps": null,
"BlkioDeviceWriteBps": null,
"BlkioDeviceReadIOps": null,
"BlkioDeviceWriteIOps": null,
"CpuPeriod": 0,
"CpuQuota": 0,
"CpuRealtimePeriod": 0,
"CpuRealtimeRuntime": 0,
"CpusetCpus": "",
"CpusetMems": "",
"Devices": [],
"DeviceCgroupRules": null,
"DiskQuota": 0,
"KernelMemory": 0,
"MemoryReservation": 0,
"MemorySwap": 0,
"MemorySwappiness": -1,
"OomKillDisable": false,
"PidsLimit": 0,
"Ulimits": null,
"CpuCount": 0,
"CpuPercent": 0,
"IOMaximumIOps": 0,
"IOMaximumBandwidth": 0
},
"GraphDriver": {
"Data": {
"dir": "C:\ProgramData\docker\windowsfilter\224a106acae83f0618949261201c2d72bc12adb0a8ce044d6e7ebdbb0b451a36"
},
"Name": "windowsfilter"
},
"Mounts": [
{
"Type": "bind",
"Source": "c:\advaniagit\workspace\a522612e-7dc2-41e4-9dc4-fb7c76ee1555",
"Destination": "c:\git",
"Mode": "",
"RW": true,
"Propagation": ""
},
{
"Type": "bind",
"Source": "c:\AdvaniaGIT",
"Destination": "c:\host",
"Mode": "",
"RW": true,
"Propagation": ""
}
],
"Config": {
"Hostname": "224a106acae8",
"Domainname": "",
"User": "",
"AttachStdin": false,
"AttachStdout": false,
"AttachStderr": false,
"ExposedPorts": {
"1433/tcp": {},
"443/tcp": {},
"7045/tcp": {},
"7046/tcp": {},
"7047/tcp": {},
"7048/tcp": {},
"7049/tcp": {},
"80/tcp": {},
"8080/tcp": {}
},
"Tty": false,
"OpenStdin": false,
"StdinOnce": false,
"Env": [
"ACCEPT_EULA=Y",
"username=navlightadmin",
"password=**************",
"auth=Windows",
"Windowsauth=Y",
"VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-0.11.14380.vsix",
"NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/796f8b26-d3fc-41fb-b289-b8fc4bab6950",
"DatabaseServer=localhost",
"DatabaseInstance=SQLEXPRESS",
"DatabaseName=CRONUS"
],
"Cmd": [
"powershell",
"-Command",
"$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
".\Run\start.ps1"
],
"Healthcheck": {
"Test": [
"CMD",
"powershell",
".\Run\HealthCheck.ps1"
],
"Interval": 30000000000,
"Timeout": 10000000000
},
"ArgsEscaped": true,
"Image": "navdocker.azurecr.io/dynamics-nav:11.0.18843.0",
"Volumes": null,
"WorkingDir": "",
"Entrypoint": null,
"OnBuild": null,
"Labels": {
"country": "W1",
"created": "201710262234",
"cu": "",
"eula": "https://go.microsoft.com/fwlink/?linkid=861843",
"legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
"maintainer": "Freddy Kristiansen",
"nav": "main",
"osversion": "10.0.14393.1770",
"tag": "0.0.3.1",
"version": "11.0.18843.0"
}
},
"NetworkSettings": {
"Bridge": "",
"SandboxID": "9ac28bbefd619f3beb43a71bc2e96a18e5b4af7984e6155f341af6cc5582b1ea",
"HairpinMode": false,
"LinkLocalIPv6Address": "",
"LinkLocalIPv6PrefixLen": 0,
"Ports": {
"1433/tcp": null,
"443/tcp": null,
"7045/tcp": null,
"7046/tcp": null,
"7047/tcp": null,
"7048/tcp": null,
"7049/tcp": null,
"80/tcp": null,
"8080/tcp": null
},
"SandboxKey": "9ac28bbefd61",
"SecondaryIPAddresses": null,
"SecondaryIPv6Addresses": null,
"EndpointID": "",
"Gateway": "",
"GlobalIPv6Address": "",
"GlobalIPv6PrefixLen": 0,
"IPAddress": "",
"IPPrefixLen": 0,
"IPv6Gateway": "",
"MacAddress": "",
"Networks": {
"nat": {
"IPAMConfig": null,
"Links": null,
"Aliases": null,
"NetworkID": "f2fa66e87355cdcc22c286dbd9fe05bb197a1185bc3ed7ce8582ef3e013e7a17",
"EndpointID": "1c1c9fb028767740e4f2f9f7833c06b584a5f6a3b2edcfc9698698387908f0c4",
"Gateway": "172.20.96.1",
"IPAddress": "172.20.99.243",
"IPPrefixLen": 16,
"IPv6Gateway": "",
"GlobalIPv6Address": "",
"GlobalIPv6PrefixLen": 0,
"MacAddress": "00:15:5d:09:e1:7c",
"DriverOpts": null
}
}
}
}
]

docker logs 224a106acae8
Initializing...
Hostname is 224a106acae8
PublicDnsName is 224a106acae8
Running Specific Image
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Using Database Connection localhost/SQLEXPRESS [CRONUS]
Modifying NAV Service Tier Config File for Docker
Modifying NAV Service Tier Config File with Instance Specific Settings
Start NAV Service Tier
Using existing license file
Creating DotNetCore NAV Web Server Instance
Creating http download site
Creating Windows user
Enabling SA
Creating NAV user
Container IP Address: 172.20.99.243
Container Hostname : 224a106acae8
Container Dns Name : 224a106acae8
Web Client : http://224a106acae8/NAV/WebClient/
Dev. Server : http://224a106acae8
Dev. ServerInstance : NAV

Files:
http://224a106acae8:8080/al-0.11.14380.vsix

Ready for connections!

**Comment by freddydk** [comment]
I can see you are using and downloaded the docker image from navdocker, meaning that you have access to this and MS Collaborate.
Could you retry your scenario with build 19101, available through MS Collaborate?
Thanks

**Comment by gunnargestsson** [comment]
Did, same result.

<title>IIS 10.0 Detailed Error - 401.1 - Unauthorized</title>

**Comment by freddydk** [comment]
I can repro this behavior if I am NOT connected to my domain controller and I am using cached credentials, is that the same setup you have?
.

**Comment by gunnargestsson** [comment]
Yes, standalone Azure machine

Kind regards,
Gunnar Gestsson

________________________________

**Comment by freddydk** [comment]
Run Windows Update.
The Nav On Docker Images are 10.0.14393.1770.
You are probably running 10.0.14393.1715 on the host.
For some reason - it gives this bug.
winver needs to return: 
![image](https://user-images.githubusercontent.com/10775043/32526172-3739657c-c428-11e7-9ecf-5afc5bc28342.png)

**Comment by freddydk** [comment]
Did you get this resolved?

**Comment by gunnargestsson** [comment]
Need to take a break from this to prepare for NAVTechDays.

Kind Regards,
Gunnar Gestsson

**Comment by freddydk** [comment]
Assuming that this was resolved.
