### ISSUE TITLE
Question: Policies for customized images on Docker Hub

### ISSUE THREAD

**Issue by tfenster** [Microsoft/nav-docker#95]
Are there any policies for publishing customized images based on your standard images on Docker Hub? There are a few like [this one](https://hub.docker.com/r/tchughesiv/mssql-server-linux/) built on top of MS "solutions" and obviously lots built on the Server Core / Nano images. My current need would be to publish one stripped down image for building and one which includes a Prometheus log scraper. Both in my opinion are to special to include in your standard images but might be useful for others and could then also be integrated e.g. in Portainer templates (which is not possible for azurecr.io hosted images as Portainer templates don't allow authenticating against registries)

**Comment by Koubek** [comment]
I had the same question and wanted to discuss it on NavTechDays. I think it is nice to be able to extend and push your own overlaying layers and create your containers. 

We use currently our internal repo (and I can\`t say that it is bad) as the policy is something I do not have very clear.

To make something special and generic (for all people using NAV on Docker) would be a bit more complicated because you would need to build the overlays for each image published by Microsoft and do it each time the changes will be published by MS (using webhooks etc...?)

**Comment by freddydk** [comment]
The policy is clear. At this time, the NAV on Docker images are shipped with the right to use them, not to redistribute them.

But, I will discuss this internally with people here.
On one side, I like the idea, but on the other side, we do not want a bunch of "old" images out there.

**Comment by tfenster** [comment]
I would be fine with rules like "you need to update to the latest base images after XY days" or something like that as I would need to automate that process anyways. But it would be good to allow the publisher to select which versions and variants he wants to support like "only 2017-w1 and 2017-de" but require him to state that clearly on the Docker Hub page

**Comment by tfenster** [comment]
@freddydk As there is some interest for 2019-based images now, did you come to a conclusion about custom images?

**Comment by freddydk** [comment]
Sorry Tobias, but we do not want partner images based on NAV/BC images on the public Docker Hub.
If you publish to a private docker repository to a private audience, we do not have any objections (nor would we ever find out:-))

**Comment by tfenster** [comment]
@freddydk Understood and thanks for providing a clear answer. Obviously not the one I was hoping for, but now I know how to go forward. On small followup: Would creating a privat repo and mentioning on my blog that people can ask for the credentials qualify as "private audience"?
