### ISSUE TITLE
NAV Development environment - ODBC error occurred

### ISSUE THREAD

**Issue by dejfidson** [Microsoft/nav-docker#96]
Hi everyone. I have a problem with the development environment running through ClickOnce. When I open the database the following error appears.

![odbcerror](https://user-images.githubusercontent.com/5273598/32516778-cbadd59a-c404-11e7-9179-28807bbaef39.PNG)

My container is created by the following command:

docker run --name dynamics-nav-2017-kom006 --hostname dynamics-nav-2017-kom006 -v C:\Docker\SharedFolder\dynamics-nav-2017-kom006:c:\run\my -e ACCEPT_EULA=Y -e username=admin -e password=Heslo.1234 -e WindowsAuth=N -e UseSSL=N -e ClickOnce=Y -m 4G microsoft/dynamics-nav:2017-cu10

**Comment by dejfidson** [comment]
Sorry... Here is error in english:

"Error: [Microsoft][ODBC Driver Manager] Data Source name not found and no default driver specified. State ID: IM002"

Do I have to install any pre-requisities on host? What are the pre-requisities?

**Comment by freddydk** [comment]
When you specify a hostname - that is what you use as server name.
and the hostname shouldn't be more than 15 characters in length.

**Comment by dejfidson** [comment]
The same problem is with the IP address of the server that is 172.31.93.254\SQLEXPRESS. I know that use of the development environment is limited but I just want to open the object designer.

**Comment by freddydk** [comment]
Did you try with a short name?

**Comment by dejfidson** [comment]
I tried now and result is the same:

![odbcerror2](https://user-images.githubusercontent.com/5273598/32519023-a9052884-c40b-11e7-9e3c-19d0aa68eea7.PNG)

How can I use development environment except ClickOnce? Is it better copy necessary files of development environment to a Shared Folder on host?

**Comment by freddydk** [comment]
I also tried this:
docker run --name kom006 --hostname kom006 -e ACCEPT_EULA=Y -e username=admin -e password=Heslo.1234 -e WindowsAuth=N -e UseSSL=N -e ClickOnce=Y -m 4G microsoft/dynamics-nav:2017-cu10

Works perfectly here.

Did you install the SQL Native Client: 
![image](https://user-images.githubusercontent.com/10775043/32519603-9f79f130-c40d-11e7-8e82-b7e82ccdc436.png)

**Comment by freddydk** [comment]
You can also use the navcontainerhelper to spin up your cside dev container - that will create a Cside shortcut on the desktop and copy the files out to the host in a shared folder.

**Comment by freddydk** [comment]
Not that I know of - it shares a folder with the container and lets the container copy the client executables to that folder, basically "installing" it on the client and connecting to the container (or whereever the SQL Server is).

**Comment by dejfidson** [comment]
Thank you so much for everything!

**Comment by Rehansatti** [comment]
Hi @freddydk ,
I have installed Business center sandbox. using the following script
New-NavContainer -containerName bcsandbox -accept_eula -assignPremiumPlan -auth NavUserPassword -doNotExportObjectsToText -enableSymbolLoading -imageName microsoft/bcsandbox:us -includeCSide -memoryLimit 4G -shortcuts Desktop -updateHosts

The Container is created success fully, the Web and windows clients are working as expected. But When i tried to run the Client Side Dev environment It is giving me the same error as above  
![image](https://user-images.githubusercontent.com/17067574/45887080-45689b80-bdd4-11e8-8f85-fc24a6cdaa2f.png)
. I am not sure How can  I install native client on this container. I can not access http://bcsandbox:8080/NAV.

Thanks

**Comment by tinfister** [comment]
I know it's an old thread, but it helped me today. Thank you for posting the thread and thank you @freddydk for blog. I was missing prerequisites for Clasic Dev Environment

**Comment by RITTMG** [comment]
More than 4 years later, this information helped me as well! A big thank you! :-)
