### ISSUE TITLE
Running Docker NAV container on Windows 10 pro

### ISSUE THREAD

**Issue by elweilando** [Microsoft/nav-docker#97]
I can't start nav docker on windows 10 professional.

- Windows Defender ist configured to ignore ProgramData\Docker.
- No other antivirus / antimalware software
- All Updates are installed.
- Docker is switched to containers
- docker hello-world runs with no issues

If I try to start 

`docker.exe run -m 5G  -e ACCEPT_EULA=Y -e auth=Windows -e usessl=Y navdocker.azurecr.io/dynamics-nav:9.0
.47042.0-de`

I get 

> Error response from daemon: container 43e96ca2b0535adeaebc5fab884b70b35f92afbdac8ed2c89aed07088e551567 encountered an error during CreateContainer: failure in a Windows system call: error this operation returned because the timeout period expired (0x5b4)

If I try to start

`docker.exe run -m 5G  -e ACCEPT_EULA=Y -e auth=Windows -e usessl=Y navdocker.azurecr.io/dynamics-nav:9.0.47042.0-de`

I get a little bit more, but still an error. 

> Initializing...
> Hostname is 9cbaf271dc8f
> PublicDnsName is 9cbaf271dc8f
> Running Specific Image
> Using NavUserPassword Authentication
> Starting Local SQL Server
> WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
> start...
> WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
> start...
> Starting Internet Information Server
> Using Database Connection localhost/SQLEXPRESS [CronusDE]
> Modifying NAV Service Tier Config File for Docker
> Creating Self Signed Certificate
> Self Signed Certificate Thumbprint 85D64F5237BF0A60579F8B7A2E242AAC6CABFC0C
> Modifying NAV Service Tier Config File with Instance Specific Settings
> Start NAV Service Tier
> Using existing license file
> Creating Web Site
> Creating NAV Web Server Instance
> Creating http download site
> Creating Windows user
> Enabling SA
> ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.

I have tested this on two machines

- Clean Windows 10 Pro installed with Parallels Desktop Pro virtualization on Mac OSX 10.11.6
- Clean Windows 10 Pro installed on a native machine

On both machines the same.

Run these commands on Windows Server 2016 Datacenter works like a charm.

**Comment by yrest** [comment]
What is your **docker info**

**Comment by elweilando** [comment]
Windows 10 Pro
> Containers: 44
>  Running: 0
>  Paused: 0
>  Stopped: 44
> Images: 4
> Server Version: 17.09.0-ce
> Storage Driver: windowsfilter
>  Windows:
> Logging Driver: json-file
> Plugins:
>  Volume: local
>  Network: ics l2bridge l2tunnel nat null overlay transparent
>  Log: awslogs etwlogs fluentd json-file logentries splunk syslog
> Swarm: inactive
> Default Isolation: hyperv
> Kernel Version: 10.0 16299 (16299.15.amd64fre.rs3_release.170928-1534)
> Operating System: Windows 10 Pro
> OSType: windows
> Architecture: x86_64
> CPUs: 4
> Total Memory: 9.807GiB
> Name: EL2B6C
> ID: Z2VJ:SONE:NYL3:FYMC:U6QV:PAGH:AQDA:TQO7:5SQX:LTSB:LDSH:6VTH
> Docker Root Dir: C:\ProgramData\Docker
> Debug Mode (client): false
> Debug Mode (server): true
>  File Descriptors: -1
>  Goroutines: 29
>  System Time: 2017-11-08T12:50:28.7649247+01:00
>  EventsListeners: 0
> Registry: https://index.docker.io/v1/
> Experimental: true
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false


2016 Datacenter
> Containers: 28
>  Running: 1
>  Paused: 0
>  Stopped: 27
> Images: 4
> Server Version: 17.06.1-ee-2
> Storage Driver: windowsfilter
>  Windows:
> Logging Driver: json-file
> Plugins:
>  Volume: local
>  Network: l2bridge l2tunnel nat null overlay transparent
>  Log: awslogs etwlogs fluentd json-file logentries splunk syslog
> Swarm: inactive
> Default Isolation: process
> Kernel Version: 10.0 14393 (14393.1770.amd64fre.rs1_release.170917-170
> Operating System: Windows Server 2016 Datacenter
> OSType: windows
> Architecture: x86_64
> CPUs: 2
> Total Memory: 16GiB
> Name: Dockertest
> ID: 6ZN6:F45F:ZKIE:TD7G:KALH:WMRR:XBCB:VLD5:6S65:JGV3:S6LH:RDGP
> Docker Root Dir: C:\ProgramData\docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false

**Comment by freddydk** [comment]
What is the result of
docker run -m 3G microsoft/dynamics-nav

**Comment by Koubek** [comment]
I can see you run WinAuth without your credentials.

**Comment by elweilando** [comment]
`docker run -m 3G microsoft/dynamics-nav`

> Initializing...
> Hostname is 1de0dba77be9
> PublicDnsName is 1de0dba77be9
> Running Specific Image
> You must accept the End User License Agreement before this container can start.
> Use Docker inspect to locate the Url for the EULA under Labels/legal.
> set the environment variable ACCEPT_EULA to 'Y' if you accept the agreement.

`docker run -m 3G microsoft/dynamics-nav -e ACCEPT_EULA=Y`

> C:\Program Files\Docker\docker.exe: Error response from daemon: container 3a83b251e
> 0cd166f1ae29be6626 encountered an error during CreateProcess: failure in a Windows
> he file specified. (0x2) extra info: {"ApplicationName":"","CommandLine":"-e ACCEPT
> :"C:\\","Environment":{"DatabaseInstance":"SQLEXPRESS","DatabaseName":"CRONUS","Dat
> "https://nav2016wswe0.blob.core.windows.net/dvd/c1d51a06-fbd1-4307-82b5-a5312e30071
> InPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}.

On virtual Win10Pro just
> Error response from daemon: container f2b3294decb7f1767eff8e5b84e7a49673606942c6a42ed2db307a144bf2fa1f encountered an error during CreateContainer: hcsshim: timeout waiting for notification

**Comment by Koubek** [comment]
@elweilando  Please, check my previous response.

**Comment by elweilando** [comment]
@Koubek It's the same behavoir with or without  -e auth=Windows

**Comment by freddydk** [comment]
It's not the same behavior - it is all different errors.

Imagename needs to be last (and I forgot the accept eula) - try:
docker run -m 3G -e ACCEPT_EULA=Y microsoft/dynamics-nav

**Comment by Koubek** [comment]
I agree with @freddydk . In my opinion, no one of your commands you provided was correct.

**Comment by elweilando** [comment]
Sorry. You're right. I had some copy & paste issues in my first commands.
Now, I can reproduce this:

Native Win10Pro (16GB Ram)
`docker.exe run -m 5G -e ACCEPT_EULA=Y navdocker.azurecr.io/dynamics-nav:9.0.47042.0-de`
`docker.exe run -m 5G -e ACCEPT_EULA=Y microsoft/dynamics-nav:2016-cu12-de`
>  failure in a Windows system call: error this operation returned because the timeout period expired (0x5b4)

`docker.exe run -m 3G -e ACCEPT_EULA=Y navdocker.azurecr.io/dynamics-nav:9.0.47042.0-de`
`docker.exe run -m 3G -e ACCEPT_EULA=Y microsoft/dynamics-nav:2016-cu12-de`
> Ready for Connections

Virtual Win10Pro (10GB Ram)
`docker.exe run -m 3G -e ACCEPT_EULA=Y microsoft/dynamics-nav:2016-cu12-de`
`docker.exe run -m 3G -e ACCEPT_EULA=Y navdocker.azurecr.io/dynamics-nav:9.0.47042.0-de`
>  encountered an error during CreateContainer: hcsshim: timeout waiting for notification

`docker.exe run -m 2G -e ACCEPT_EULA=Y microsoft/dynamics-nav:2016-cu12-de`
`docker.exe run -m 2G -e ACCEPT_EULA=Y navdocker.azurecr.io/dynamics-nav:9.0.47042.0-de`
> Ready for connections

Are there some docker settings to increase the memory for the docker instance?

**Comment by freddydk** [comment]
Why are you writing 2 lines per docker run - one taking the image from the official public repository and one from the private repository?
one docker run == one container.
In general, you should never use navdocker.azurecr.io anymore unless you have a reason.

**Comment by elweilando** [comment]
@freddydk I edited my comment above. 
I used only one line. I meant that both repos work.
The issues occurs if I change the memory parameter.

**Comment by freddydk** [comment]
I do not have detailed knowledge about docker or hypervisor settings on various platforms and we recommend that you use Windows Server for NAV on Docker.
it seems like the errors occur before the NAV on Docker container is launched, not much we can do about that.
If you want to pursue this, you might be able to do so at the Docker foums.

**Comment by elweilando** [comment]
It seams to be a bug in docker docker/for-win#767
https://forums.docker.com/t/windows-container-runs-with-m-3g-but-fails-to-start-with-m-4g/32568
